namespace AetherLove.Services.Localization;

internal static class PlacesRu
{
    public static readonly System.Collections.Generic.Dictionary<string, string> Strings = new()
    {
        // added after update 1.5.0
        ["places.title"] = "Места",
        ["places.load_failed"] = "Не удалось загрузить Места: {0}",
        ["places.happening_now"] = "Открыто сейчас",
        ["places.this_week"] = "На этой неделе",
        ["places.nothing_upcoming"] = "На этой неделе открытий не запланировано.",
        ["places.empty"] = "Ни одно заведение не подходит под ваши фильтры.",
        ["places.empty_hint"] = "Попробуйте расширить фильтры Мест.",
        ["places.today"] = "Сегодня",
        ["places.tomorrow"] = "Завтра",
        ["places.live"] = "СЕЙЧАС",
        ["places.ends_in"] = "Закроется через {0}",
        ["places.going"] = "{0} придут",
        ["places.back"] = "Назад",

        ["places.filters_title"] = "Фильтры Мест",
        ["places.filters_tags"] = "Показывать заведения с меткой",
        ["places.filters_regions"] = "Регионы",
        ["places.filters_hint"] = "Если ничего не выбрано, будет показываться всё. Эти фильтры отдельны и не влияют на ваши настройки подбора пар.",
        ["places.filters_apply"] = "Применить",

        ["places.tag_rp_venue"] = "Ролевое заведение",
        ["places.tag_barding"] = "Музыка бардов",
        ["places.tag_nsfw"] = "Заведение 18+",
        ["places.tag_live_dj"] = "Живые диджеи",
        ["places.tag_sync"] = "Есть синкшелл",
        ["places.tag_nightclub"] = "Ночной клуб",
        ["places.tag_bar_tavern"] = "Бар / Таверна",
        ["places.tag_cafe"] = "Кафе",
        ["places.tag_restaurant"] = "Ресторан",
        ["places.tag_casino"] = "Казино",
        ["places.tag_maid_cafe"] = "Мейд-кафе",
        ["places.tag_bathhouse"] = "Баня",
        ["places.tag_gpose_studio"] = "Студия GPose",
        ["places.tag_live_music"] = "Живая музыка",
        ["places.tag_market"] = "Рынок / Магазин",

        ["places.day_mon"] = "Пн",
        ["places.day_tue"] = "Вт",
        ["places.day_wed"] = "Ср",
        ["places.day_thu"] = "Чт",
        ["places.day_fri"] = "Пт",
        ["places.day_sat"] = "Сб",
        ["places.day_sun"] = "Вс",

        ["places.location_ward"] = "Вард {0}",
        ["places.location_plot"] = "Плот {0}",
        ["places.location_room"] = "Комната {0}",

        ["places.schedule"] = "Часы работы",
        ["places.rsvp"] = "Пойду",
        ["places.rsvp_going"] = "Приду ✓",

        ["places.reviews_title"] = "Отзывы",
        ["places.no_reviews"] = "Отзывов пока нет — будьте первыми!",
        ["places.no_rating_yet"] = "Оценок пока нет.",
        ["places.rating_summary"] = "{0} · {1} отзывов",
        ["places.write_review"] = "Написать отзыв",
        ["places.your_review"] = "Ваш отзыв",
        ["places.review_pending"] = "Ваш отзыв ожидает проверки и виден только вам.",
        ["places.review_submit"] = "Опубликовать отзыв",
        ["places.review_update"] = "Обновить отзыв",
        ["places.review_delete"] = "Удалить",
        ["places.review_delete_title"] = "Удалить отзыв?",
        ["places.review_delete_body"] = "Ваша оценка и текст будут удалены безвозвратно.",
        ["places.reviews_more"] = "Загрузить ещё отзывы",

        ["places.menu_my_venues"] = "Мои заведения",
        ["places.my_venues"] = "Мои заведения",
        ["places.my_venues_empty"] = "Вы ещё не создали заведение. Создайте его, чтобы появиться в Местах!",
        ["places.venue_saved"] = "Заведение сохранено.",
        ["places.new_venue"] = "+ Новое заведение",
        ["places.venue_cap"] = "Вы достигли лимита в {0} заведений.",
        ["places.venue_stats"] = "{0} лайков · {1} отзывов",
        ["places.venue_unlisted"] = "Скрыто модерацией",
        ["places.back_to_venues"] = "Назад",
        ["places.new_venue_title"] = "Новое заведение",
        ["places.edit_venue_title"] = "Редактировать заведение",

        ["places.section_details"] = "Сведения",
        ["places.venue_name"] = "Название заведения",
        ["places.venue_description"] = "Описание",
        ["places.section_tags"] = "Метки",
        ["places.section_location"] = "Расположение",
        ["places.use_current_location"] = "Использовать моё текущее местоположение",
        ["places.use_current_location_hint"] = "Встаньте внутри своего заведения, чтобы всё заполнилось автоматически.",
        ["places.venue_datacenter"] = "Дата-центр",
        ["places.venue_world"] = "Мир",
        ["places.venue_ward"] = "Вард",
        ["places.venue_plot"] = "Плот",
        ["places.venue_room"] = "Комната",
        ["places.venue_room_hint"] = "Для апартаментов укажите участок 0 и введите номер комнаты.",
        ["places.venue_timezone"] = "Часовой пояс заведения",
        ["places.venue_timezone_tip"] = "Часы работы ниже вводятся в этом часовом поясе. Посетители всегда видят их в своём местном времени.",

        ["places.section_hours"] = "Часы работы",
        ["places.hours_explainer"] = "Выберите дни, затем щёлкните час начала и час конца — промежуточные часы заполнятся автоматически, даже через полночь.",
        ["places.add_opening_time"] = "+ Добавить время работы",
        ["places.rule_weekly"] = "Еженедельно",
        ["places.rule_one_time"] = "Разово",
        ["places.rule_date_hint"] = "Дата (ГГГГ-ММ-ДД)",
        ["places.rule_span"] = "Открыто {0}",
        ["places.hours_pick_start"] = "Щёлкните, чтобы задать начало",
        ["places.hours_pick_end"] = "Щёлкните, чтобы задать конец",

        ["places.section_images"] = "Изображения",
        ["places.image_banner"] = "Баннер",
        ["places.image_logo"] = "Изображение заведения",
        ["places.image_banner_hint"] = "Широкий баннер (25:9). Показывается на странице заведения.",
        ["places.image_logo_hint"] = "Квадратное (1:1). Показывается на карточках заведения.",
        ["places.image_pick"] = "Выбрать изображение",
        ["places.image_ready"] = "Готово к сохранению",
        ["places.image_remove"] = "Убрать",
        ["places.crop_banner"] = "Обрезать баннер",
        ["places.crop_logo"] = "Обрезать изображение заведения",

        ["places.err_name"] = "Назовите ваше заведение (не короче 3 символов).",
        ["places.err_location"] = "Заполните дата-центр и мир.",
        ["places.err_plot_or_room"] = "Укажите номер участка или комнаты.",
        ["places.err_date"] = "Разовым открытиям нужна дата в формате ГГГГ-ММ-ДД.",
        ["places.err_days"] = "Еженедельным открытиям нужен хотя бы один выбранный день.",
        ["places.save_venue"] = "Сохранить заведение",
        ["places.delete_venue"] = "Удалить заведение",
        ["places.delete_venue_title"] = "Удалить заведение?",
        ["places.delete_venue_body"] = "«{0}» и все его лайки, отзывы и записи будут удалены безвозвратно.",

        // added after update 1.5.1
        ["places.venue_region"] = "Регион",
        ["places.venue_district"] = "Район",
        ["places.venue_dc_select"] = "Выберите дата-центр",
        ["places.venue_world_select"] = "Выберите мир",
        ["places.venue_tz_select"] = "Выберите часовой пояс",
        ["places.venue_tz_search"] = "Поиск…",
        ["places.err_description"] = "Добавьте описание.",
        ["places.err_tags"] = "Выберите хотя бы одну метку.",
        ["places.err_images"] = "Нужны и баннер, и логотип.",
        ["places.err_timezone"] = "Выберите часовой пояс.",
        ["places.err_hours"] = "Добавьте хотя бы одно время работы.",
        ["places.section_rsvpd"] = "Вы идёте",
        ["places.duration_hm"] = "{0} ч {1} мин",
        ["places.duration_m"] = "{0} мин",
        ["places.filters_nsfw"] = "Заведения 18+",
        ["places.reset_filters"] = "Сбросить фильтры",
        ["places.menu_filter"] = "Фильтр",
        ["places.menu_search"] = "Поиск",
        ["places.search_hint"] = "Поиск заведений…",
        ["places.no_search_results"] = "Ничего не найдено по вашему запросу.",
        ["places.open_now"] = "Открыто сейчас!",
        ["places.show_all_tags"] = "Показать все метки",
        ["places.no_reviews_owner"] = "Отзывов пока нет.",
        ["places.image_extra_banner"] = "Баннер карусели {0}",
        ["places.venue_pending"] = "Ожидает модерации",
        ["places.menu_addvenue"] = "Добавить моё заведение",
        ["places.addvenue_title"] = "Добавьте своё заведение",
        ["places.addvenue_intro"] = "У вас есть заведение? Раздел «Места» в AetherLove показывает его игрокам прямо в игре, и размещение является полностью бесплатным. Никаких взносов, платных уровней и подвохов.",
        ["places.addvenue_perks_header"] = "Зачем размещать заведение?",
        ["places.addvenue_perk_reviews_title"] = "Оценки и комментарии",
        ["places.addvenue_perk_reviews_body"] = "Гости могут оценивать ваше заведение и оставлять комментарии: отличный способ заявить о себе, заработать репутацию и получить честные отзывы.",
        ["places.addvenue_perk_reach_title"] = "Игроки прямо в игре",
        ["places.addvenue_perk_reach_body"] = "Ваше заведение, часы работы и текущие события видны именно там, где игроки уже находятся: внутри игры.",
        ["places.addvenue_perk_share_title"] = "Можно делиться в чатах",
        ["places.addvenue_perk_share_body"] = "Игроки могут делиться вашим заведением друг с другом прямо в чатах AetherLove.",
        ["places.addvenue_how_heading"] = "Как получить доступ",
        ["places.addvenue_how_body"] = "Роли для заведений выдаются через наш Discord-сервер. Присоединяйтесь к серверу и откройте тикет поддержки с просьбой о доступе к заведениям; после выдачи в вашем профиле откроется редактор «Мои заведения».",
        ["places.addvenue_discord_btn"] = "Перейти в Discord",
        ["places.addvenue_ticket_note"] = "В Discord откройте тикет для поддержки и попросите доступ к роли для заведений. Это занимает минуту и полностью бесплатно.",
        ["places.share"] = "Поделиться",
        ["places.share_title"] = "Поделиться заведением",
        ["places.share_search_hint"] = "Поиск по вашим парам…",
        ["places.share_send"] = "Поделиться",
        ["places.share_no_matches"] = "Пары не найдены.",
        ["places.share_loading"] = "Загрузка заведения…",
        ["places.share_unavailable"] = "Это заведение больше недоступно.",
        ["places.share_view"] = "Открыть заведение",
        ["places.back_to_chat"] = "Назад к чату",

        ["places.hide_venue"] = "Скрыть это заведение",
        ["places.hide_intro_title"] = "Скрытие заведений",
        ["places.hide_intro_body"] = "Это скрывает заведение из вашего обзора Мест. Оно скрыто только для вас, на этом устройстве. Вернуть скрытые заведения можно в любой момент через меню вверху этой страницы.",
        ["places.hide_intro_note"] = "Сейчас ничего не скрыто. В следующий раз заведение исчезнет сразу.",
        ["places.menu_hidden"] = "Скрытые заведения ({0})",
        ["places.hidden_title"] = "Скрытые заведения",
        ["places.unhide"] = "Показать",

        // added after update 1.6.0
        ["places.tag_247"] = "Заведение 24/7",
        ["places.filters_247"] = "Показывать заведения 24/7",
        ["places.tag_lgbtq"] = "ЛГБТК+",
        ["places.tag_minigames"] = "Мини-игры",
    };
}
