namespace AetherLove.Services.Localization;

internal static class PlacesDe
{
    public static readonly System.Collections.Generic.Dictionary<string, string> Strings = new()
    {
        // added after update 1.5.0
        ["places.title"] = "Orte",
        ["places.load_failed"] = "Orte konnten nicht geladen werden: {0}",
        ["places.happening_now"] = "Jetzt geöffnet",
        ["places.this_week"] = "Diese Woche",
        ["places.nothing_upcoming"] = "Diese Woche stehen keine Öffnungen an.",
        ["places.empty"] = "Keine Venues passen zu deinen Filtern.",
        ["places.empty_hint"] = "Versuche, deine Orte-Filter zu erweitern.",
        ["places.today"] = "Heute",
        ["places.tomorrow"] = "Morgen",
        ["places.live"] = "LIVE",
        ["places.ends_in"] = "Endet in {0}",
        ["places.going"] = "{0} dabei",
        ["places.back"] = "Zurück",

        ["places.filters_title"] = "Orte-Filter",
        ["places.filters_tags"] = "Venues zeigen mit Tag",
        ["places.filters_regions"] = "Regionen",
        ["places.filters_hint"] = "Keine Auswahl bedeutet: alles wird angezeigt. Diese Filter sind unabhängig von deinen Matching-Einstellungen.",
        ["places.filters_apply"] = "Anwenden",

        ["places.tag_rp_venue"] = "Rollenspiel-Venue",
        ["places.tag_barding"] = "Barden-Musik",
        ["places.tag_nsfw"] = "18+-Venue",
        ["places.tag_live_dj"] = "Live-DJs",
        ["places.tag_sync"] = "Sync aktiviert",
        ["places.tag_nightclub"] = "Nachtclub",
        ["places.tag_bar_tavern"] = "Bar / Taverne",
        ["places.tag_cafe"] = "Café",
        ["places.tag_restaurant"] = "Restaurant",
        ["places.tag_casino"] = "Casino",
        ["places.tag_maid_cafe"] = "Maid-Café",
        ["places.tag_bathhouse"] = "Badehaus",
        ["places.tag_gpose_studio"] = "Gpose-Studio",
        ["places.tag_live_music"] = "Live-Musik",
        ["places.tag_market"] = "Markt / Laden",

        ["places.day_mon"] = "Mo",
        ["places.day_tue"] = "Di",
        ["places.day_wed"] = "Mi",
        ["places.day_thu"] = "Do",
        ["places.day_fri"] = "Fr",
        ["places.day_sat"] = "Sa",
        ["places.day_sun"] = "So",

        ["places.location_ward"] = "Bezirk {0}",
        ["places.location_plot"] = "Grundstück {0}",
        ["places.location_room"] = "Zimmer {0}",

        ["places.schedule"] = "Öffnungszeiten",
        ["places.rsvp"] = "Zusagen",
        ["places.rsvp_going"] = "Dabei ✓",

        ["places.reviews_title"] = "Bewertungen",
        ["places.no_reviews"] = "Noch keine Bewertungen — sei die erste Person!",
        ["places.no_rating_yet"] = "Noch keine Wertungen.",
        ["places.rating_summary"] = "{0} · {1} Bewertungen",
        ["places.write_review"] = "Bewertung schreiben",
        ["places.your_review"] = "Deine Bewertung",
        ["places.review_pending"] = "Deine Bewertung wartet auf Moderation und ist nur für dich sichtbar.",
        ["places.review_submit"] = "Bewertung posten",
        ["places.review_update"] = "Bewertung aktualisieren",
        ["places.review_delete"] = "Löschen",
        ["places.review_delete_title"] = "Bewertung löschen?",
        ["places.review_delete_body"] = "Deine Wertung und dein Text werden dauerhaft entfernt.",
        ["places.reviews_more"] = "Weitere Bewertungen laden",

        ["places.menu_my_venues"] = "Meine Venues",
        ["places.my_venues"] = "Meine Venues",
        ["places.my_venues_empty"] = "Du hast noch keine Venue erstellt. Erstelle eine, um in Orte aufzutauchen!",
        ["places.venue_saved"] = "Venue gespeichert.",
        ["places.new_venue"] = "+ Neue Venue",
        ["places.venue_cap"] = "Du hast das Limit von {0} Venues erreicht.",
        ["places.venue_stats"] = "{0} Likes · {1} Bewertungen",
        ["places.venue_unlisted"] = "Von der Moderation ausgeblendet",
        ["places.back_to_venues"] = "Zurück",
        ["places.new_venue_title"] = "Neue Venue",
        ["places.edit_venue_title"] = "Venue bearbeiten",

        ["places.section_details"] = "Details",
        ["places.venue_name"] = "Name der Venue",
        ["places.venue_description"] = "Beschreibung",
        ["places.section_tags"] = "Tags",
        ["places.section_location"] = "Standort",
        ["places.use_current_location"] = "Meinen aktuellen Standort verwenden",
        ["places.use_current_location_hint"] = "Stell dich in deine Venue, um alles automatisch auszufüllen.",
        ["places.venue_datacenter"] = "Rechenzentrum",
        ["places.venue_world"] = "Welt",
        ["places.venue_ward"] = "Bezirk",
        ["places.venue_plot"] = "Grundstück",
        ["places.venue_room"] = "Zimmer",
        ["places.venue_room_hint"] = "Für Apartments das Grundstück auf 0 setzen und die Zimmernummer eingeben.",
        ["places.venue_timezone"] = "Zeitzone der Venue",
        ["places.venue_timezone_tip"] = "Die Öffnungszeiten unten werden in dieser Zeitzone eingegeben. Besucher sehen sie immer in ihre eigene Ortszeit umgerechnet.",

        ["places.section_hours"] = "Öffnungszeiten",
        ["places.hours_explainer"] = "Wähle die Tage und klicke dann auf eine Start- und eine Endstunde — die Stunden dazwischen füllen sich automatisch, auch über Mitternacht hinaus.",
        ["places.add_opening_time"] = "+ Öffnungszeit hinzufügen",
        ["places.rule_weekly"] = "Wöchentlich",
        ["places.rule_one_time"] = "Einmalig",
        ["places.rule_date_hint"] = "Datum (JJJJ-MM-TT)",
        ["places.rule_span"] = "Geöffnet {0}",
        ["places.hours_pick_start"] = "Klicken, um den Start zu setzen",
        ["places.hours_pick_end"] = "Klicken, um das Ende zu setzen",

        ["places.section_images"] = "Bilder",
        ["places.image_banner"] = "Banner",
        ["places.image_logo"] = "Venue-Bild",
        ["places.image_banner_hint"] = "Breites Banner (25:9). Wird auf deiner Venue-Seite gezeigt.",
        ["places.image_logo_hint"] = "Quadratisch (1:1). Wird auf Venue-Karten gezeigt.",
        ["places.image_pick"] = "Bild auswählen",
        ["places.image_ready"] = "Bereit zum Speichern",
        ["places.image_remove"] = "Entfernen",
        ["places.crop_banner"] = "Banner zuschneiden",
        ["places.crop_logo"] = "Venue-Bild zuschneiden",

        ["places.err_name"] = "Gib deiner Venue einen Namen (mindestens 3 Zeichen).",
        ["places.err_location"] = "Fülle Datenzentrum und Welt aus.",
        ["places.err_plot_or_room"] = "Gib eine Grundstücks- oder Zimmernummer an.",
        ["places.err_date"] = "Einmalige Öffnungen brauchen ein Datum im Format JJJJ-MM-TT.",
        ["places.err_days"] = "Wöchentliche Öffnungen brauchen mindestens einen ausgewählten Tag.",
        ["places.save_venue"] = "Venue speichern",
        ["places.delete_venue"] = "Venue löschen",
        ["places.delete_venue_title"] = "Venue löschen?",
        ["places.delete_venue_body"] = "\"{0}\" und alle Likes, Bewertungen und Zusagen werden dauerhaft entfernt.",

        // added after update 1.5.1
        ["places.venue_region"] = "Region",
        ["places.venue_district"] = "Wohngebiet",
        ["places.venue_dc_select"] = "Rechenzentrum wählen",
        ["places.venue_world_select"] = "Welt wählen",
        ["places.venue_tz_select"] = "Zeitzone wählen",
        ["places.venue_tz_search"] = "Suchen…",
        ["places.err_description"] = "Bitte füge eine Beschreibung hinzu.",
        ["places.err_tags"] = "Bitte wähle mindestens einen Tag.",
        ["places.err_images"] = "Ein Banner und ein Logo sind beide erforderlich.",
        ["places.err_timezone"] = "Bitte wähle eine Zeitzone.",
        ["places.err_hours"] = "Bitte füge mindestens eine Öffnungszeit hinzu.",
        ["places.section_rsvpd"] = "Deine Zusagen",
        ["places.duration_hm"] = "{0} h {1} min",
        ["places.duration_m"] = "{0} min",
        ["places.filters_nsfw"] = "18+-Venues",
        ["places.reset_filters"] = "Filter zurücksetzen",
        ["places.menu_filter"] = "Filter",
        ["places.menu_search"] = "Suche",
        ["places.search_hint"] = "Venues suchen…",
        ["places.no_search_results"] = "Keine Venues passen zu deiner Suche.",
        ["places.open_now"] = "Jetzt geöffnet!",
        ["places.show_all_tags"] = "Alle Tags anzeigen",
        ["places.no_reviews_owner"] = "Noch keine Bewertungen.",
        ["places.image_extra_banner"] = "Karussell-Banner {0}",
        ["places.venue_pending"] = "Prüfung ausstehend",
        ["places.menu_addvenue"] = "Meine Venue eintragen",
        ["places.addvenue_title"] = "Trag deine Venue ein",
        ["places.addvenue_intro"] = "Du betreibst eine Venue? AetherLove Places zeigt sie Spielern direkt im Spiel, und der Eintrag ist zu 100% kostenlos. Keine Gebühren, keine Bezahlstufen, kein Haken.",
        ["places.addvenue_perks_header"] = "Warum deine Venue eintragen?",
        ["places.addvenue_perk_reviews_title"] = "Bewertungen und Kommentare",
        ["places.addvenue_perk_reviews_body"] = "Gäste können deine Venue bewerten und Kommentare hinterlassen: eine tolle Art zu werben, einen Ruf aufzubauen und ehrliches Feedback zu bekommen.",
        ["places.addvenue_perk_reach_title"] = "Erreiche Spieler im Spiel",
        ["places.addvenue_perk_reach_body"] = "Deine Venue, Öffnungszeiten und laufende Events erscheinen genau dort, wo die Spieler schon sind: im Spiel.",
        ["places.addvenue_perk_share_title"] = "Teilbar in Chats",
        ["places.addvenue_perk_share_body"] = "Spieler können deine Venue direkt in ihren AetherLove-Chats miteinander teilen.",
        ["places.addvenue_how_heading"] = "So bekommst du Zugang",
        ["places.addvenue_how_body"] = "Venue-Rollen werden über unseren Discord vergeben. Tritt dem Server bei und eröffne ein Support-Ticket mit der Bitte um Venue-Zugang; sobald er erteilt ist, wird der Meine-Venues-Editor in deinem Profil freigeschaltet.",
        ["places.addvenue_discord_btn"] = "Tritt unserem Discord bei",
        ["places.addvenue_ticket_note"] = "Eröffne im Discord ein Support-Ticket und bitte um Venue-Zugang. Es dauert nur einen Moment und ist völlig kostenlos.",
        ["places.share"] = "Teilen",
        ["places.share_title"] = "Venue teilen",
        ["places.share_search_hint"] = "Matches durchsuchen…",
        ["places.share_send"] = "Teilen",
        ["places.share_no_matches"] = "Keine Matches gefunden.",
        ["places.share_loading"] = "Venue wird geladen…",
        ["places.share_unavailable"] = "Diese Venue ist nicht mehr verfügbar.",
        ["places.share_view"] = "Venue ansehen",
        ["places.back_to_chat"] = "Zurück zum Chat",

        ["places.hide_venue"] = "Diese Venue ausblenden",
        ["places.hide_intro_title"] = "Venues ausblenden",
        ["places.hide_intro_body"] = "Das blendet eine Venue aus deiner Places-Übersicht aus. Sie ist nur für dich, auf diesem Gerät, verborgen. Über das Menü oben auf dieser Seite kannst du ausgeblendete Venues jederzeit zurückholen.",
        ["places.hide_intro_note"] = "Gerade wurde noch nichts ausgeblendet. Beim nächsten Mal verschwindet die Venue sofort.",
        ["places.menu_hidden"] = "Ausgeblendete Venues ({0})",
        ["places.hidden_title"] = "Ausgeblendete Venues",
        ["places.unhide"] = "Anzeigen",

        // added after update 1.6.0
        ["places.tag_247"] = "24/7-Venue",
        ["places.filters_247"] = "24/7-Venues anzeigen",
        ["places.tag_lgbtq"] = "LGBTQ+",
        ["places.tag_minigames"] = "Minispiele",

        // added after update 1.6.1
        ["places.venue_discord"] = "Discord-Link",
        ["places.venue_discord_button"] = "Discord",
        ["places.err_discord"] = "Der Discord-Link muss discord.gg enthalten.",
    };
}
