namespace AetherLove.Services.Localization;

internal static class ProfileEn
{
    public static readonly System.Collections.Generic.Dictionary<string, string> Strings = new()
    {
        // ProfileScreen — load / empty states
        ["profile.load_failed"] = "Couldn't load profile: {0}",
        ["profile.none_loaded"] = "No profile loaded.",

        // ProfileScreen — sections
        ["profile.about"] = "About",
        ["profile.flairs"] = "Flairs",
        ["profile.looking_for"] = "Looking for",
        ["profile.content_interests"] = "Content Preferences",
        ["profile.info"] = "Info",
        ["profile.gender"] = "Gender",
        ["profile.languages"] = "Languages",
        ["profile.timezone"] = "Timezone",
        ["profile.favourite_job"] = "Favourite job",
        ["profile.favourite_location"] = "Favourite location",
        ["profile.favourite_expansion"] = "Favourite expansion",
        ["profile.favourite_song"] = "Favourite song",
        ["music.fetching"] = "Fetching song name…",
        ["music.saved"] = "Saved link (name pending)",
        ["music.invalid"] = "Couldn't read that link — paste a Spotify, SoundCloud, Apple Music, or YouTube Music song link.",
        ["music.open_tooltip"] = "Click to open",
        ["profile.favourite_movie"] = "Favourite movie",
        ["profile.favourite_anime"] = "Favourite anime",
        ["profile.favourite_ff_character"] = "Favourite FF character",
        ["profile.sync_tool"] = "Sync tool",
        ["profile.weekday_playtimes"] = "Weekday playtimes  (Mon–Fri)",
        ["profile.weekend_playtimes"] = "Weekend playtimes  (Sat–Sun)",
        ["profile.timezone_value"] = "{0} (current time: {1})",

        // ProfileScreen — Spotify / NSFW pill
        ["profile.nsfw_reveal"] = "Click to show NSFW image",

        // ProfileScreen — back pill
        ["profile.back_to_chat"] = "Back to chat",
        ["profile.back_to_swiping"] = "Back to swiping",

        // ProfileScreen — report flow
        ["profile.report_profile"] = "Report profile",
        ["profile.report_warning"] = "False or malicious reports lead to warnings on your own account, and repeated abuse can result in suspension. Only report profiles that actually violate the rules.",
        ["profile.report_prompt"] = "Tell our moderators what's wrong with {0}:",
        ["profile.this_profile"] = "this profile",
        ["profile.report_agree"] = "I understand false reports may result in warnings against my account.",
        ["profile.submitting"] = "Submitting…",
        ["profile.cancel"] = "Cancel",
        ["profile.submit_report"] = "Submit report",
        ["profile.report_submitted"] = "Report submitted",
        ["profile.report_thanks"] = "Thanks — our moderators will take a look. You won't see this profile again until you pull a fresh one from the deck.",
        ["profile.closing"] = "Closing…",
        ["profile.closing_in"] = "Closing in {0} seconds",
        ["profile.close"] = "Close",

        // ProfileScreen — copy profile text (viewing others only)
        ["profile.copy_text"] = "Copy profile text",
        ["profile.copy_warning_title"] = "Warning",
        ["profile.copy_warning_body"] = "You've copied someone's text. Be careful about clicking or following any links it contains — you do so at your own risk.",
        ["profile.copy_warning_agree"] = "I understand, and agree",

        // MyProfileScreen hub: stats + menu
        ["profile.section_myprofile"] = "My profile",
        ["profile.section_service"] = "Service",
        ["profile.menu_view"] = "View my profile",
        ["profile.menu_edit"] = "Modify profile",
        ["profile.menu_images"] = "Profile pictures",
        ["profile.stat_loves_you"] = "love you",
        ["profile.stat_matches"] = "Matches",
        ["profile.stat_match_rate"] = "Match rate",
        ["profile.back_to_my"] = "← Back",

        // MyProfileScreen — edit tab load / save
        ["profile.load_profile_failed"] = "Couldn't load your profile: {0}",
        ["profile.retry"] = "Retry",
        ["profile.saving"] = "Saving…",
        ["profile.saved"] = "Saved  ✓",
        ["profile.save_changes"] = "Save Changes",

        // MyProfileScreen — edit form section headings
        ["profile.heading_character"] = "Character",
        ["profile.heading_location"] = "Location",
        ["profile.heading_languages"] = "Languages I Speak",
        ["profile.heading_content"] = "I Enjoy the Following Content",
        ["profile.heading_looking_for"] = "I Am Looking For",
        ["profile.heading_nsfw"] = "NSFW",
        ["profile.heading_optional"] = "Optional",
        ["profile.heading_playtime"] = "Playtime",
        ["profile.heading_timezone"] = "Timezone",
        ["profile.heading_sync_tool"] = "Sync Tool",
        ["profile.heading_match_prefs"] = "Match Preferences",

        // MyProfileScreen — edit form labels / hints
        ["profile.display_name"] = "Display Name",
        ["profile.about_me"] = "About Me",
        ["profile.char_count"] = "{0} / 500 characters",
        ["profile.preview"] = "Preview",
        ["profile.bio_placeholder"] = "Your bio will appear here…",
        ["profile.race"] = "Race",
        ["profile.region"] = "Region",
        ["profile.languages_hint"] = "Select every language you are comfortable chatting in.",
        ["profile.content_hint"] = "Select everything that applies.",
        ["profile.looking_for_hint"] = "Being honest helps find better matches.",
        ["profile.nsfw_lalafell"] = "Adult and NSFW features are not available while your race is set to Lalafell. See the Terms of Service for details.",
        ["profile.nsfw_explainer"] = "NSFW stands for \"Not Safe For Work\": content containing nudity or sexual themes. Opt in to see and be matched with NSFW profiles.",
        ["profile.nsfw_optin"] = "NSFW Profiles: YES",
        ["profile.favourite_job_tooltip"] = "The job or role you enjoy the most. Type to filter.",
        ["profile.favourite_ff_character_full"] = "Favourite Final Fantasy Character",
        ["profile.weekday_playtimes_edit"] = "Weekday Playtimes (Mon–Fri)",
        ["profile.weekend_playtimes_edit"] = "Weekend Playtimes (Sat–Sun)",
        ["profile.sync_tool_hint"] = "Sync tools let matched users share mod appearances.",
        ["profile.match_prefs_body"] = "Tell us who you'd like to match with. These preferences help surface the right people for you.",
        ["profile.all"] = "All",
        ["profile.none"] = "None",
        ["profile.clear"] = "Clear",
        ["profile.filter_any_race"] = "  No selection: any race",
        ["profile.filter_any_gender"] = "  No selection: any gender",
        ["profile.filter_any_region"] = "  No selection: any region",
        ["profile.filter_any_language"] = "  No selection: no language preference",
        ["profile.spoken_language"] = "Spoken Language",
        ["profile.spoken_language_tooltip"] = "Leave all unchecked to match regardless of language.",

        // MyProfileScreen.Images — tab text
        ["profile.load_photos_failed"] = "Couldn't load your photos: {0}",
        ["profile.profile_picture"] = "Profile Picture",
        ["profile.profile_picture_desc"] = "Your profile picture is shown in the chat list and on match cards. Use a square close-up portrait of your FFXIV character.",
        ["profile.profile_photos"] = "Profile Photos",
        ["profile.profile_photos_desc"] = "Add portrait photos to your profile (10:16 ratio). The first slot is required; slots 2–4 are optional.",
        ["profile.declare_before_save"] = "Mark every extra photo as SFW or NSFW before saving.",

        // MyProfileScreen.Images — avatar section
        ["profile.new_photo_ready"] = "New photo ready, not yet saved.",
        ["profile.change_photo"] = "Change Photo",
        ["profile.profile_picture_set"] = "Profile picture: Set  ✓",
        ["profile.no_profile_picture"] = "No profile picture set.",
        ["profile.upload_avatar"] = "Upload Avatar…",

        // MyProfileScreen.Images — slot grid + active slot controls
        ["profile.slot_main"] = "Main",
        ["profile.tap_slot"] = "Tap a slot above to add or change a photo.",
        ["profile.main_photo"] = "Main photo",
        ["profile.extra_photo"] = "Extra photo {0}",
        ["profile.photo_will_be_removed"] = "Photo will be removed.",
        ["profile.undo"] = "Undo",
        ["profile.main_must_be_sfw"] = "Your main profile picture MUST be SFW. Uploading an NSFW picture is grounds for account suspension or deletion.",
        ["profile.sfw_or_nsfw"] = "Is this picture SFW or NSFW?",
        ["profile.sfw_mismatch_warning"] = "If our system detects you uploaded NSFW while SFW is selected, your photo will be held for moderation and you risk account suspension.",
        ["profile.photo_ready"] = "Photo ready, not yet saved.",
        ["profile.replace"] = "Replace",
        ["profile.photo_set"] = "Photo set  ✓",
        ["profile.currently_nsfw"] = "Currently: NSFW",
        ["profile.currently_sfw"] = "Currently: SFW",
        ["profile.remove"] = "Remove",
        ["profile.photo_required"] = "This photo is required.",
        ["profile.photo_optional"] = "This photo is optional.",
        ["profile.upload_photo"] = "Upload Photo…",

        // MyProfileScreen.Images — file picker / crop popup
        ["profile.select_image"] = "Select Image",
        ["profile.image_files_filter"] = "Image files",
        ["profile.crop_avatar"] = "Crop Avatar",
        ["profile.crop_main_photo"] = "Crop Main Photo",
        ["profile.crop_extra_photo"] = "Crop Extra Photo {0}",

        // added after update 1.4.3
        ["profile.menu_rp"] = "My RP Profiles",
        ["profile.rp_intro_title"] = "My RP Profiles",
        ["profile.rp_intro"] = "Add your FFXIV OCs (original characters) to your profile. Each character gets a name, a short story and an optional picture, and they show up on your profile for others to discover.",
        ["profile.characters"] = "Characters",
        ["profile.rp_add"] = "Add character",
        ["profile.rp_empty"] = "No characters yet. Add your first OC below!",
        ["profile.rp_limit_reached"] = "You can add up to {0} characters.",
        ["profile.rp_name"] = "Name / Title",
        ["profile.rp_bio"] = "About this character",
        ["profile.rp_delete"] = "Delete",
        ["profile.rp_delete_confirm"] = "Really delete?",
        ["profile.rp_move_up"] = "Move up",
        ["profile.rp_move_down"] = "Move down",
        ["profile.rp_image"] = "Image",
        ["profile.rp_upload_image"] = "Upload image",
        ["profile.rp_replace_image"] = "Replace image",
        ["profile.rp_remove_image"] = "Remove image",
        ["profile.rp_image_ready"] = "Image ready to save",
        ["profile.rp_image_nsfw"] = "This image is NSFW",
        ["profile.rp_image_expand"] = "View full size",
        ["profile.rp_image_back"] = "Back to profile",
        ["profile.rp_crop_image"] = "Crop Character Image",
        ["profile.rp_back"] = "Back",
        ["profile.rp_details"] = "Character details:",
    };
}
