namespace AetherLove.Services.Localization;

internal static class OnboardingEs
{
    public static readonly System.Collections.Generic.Dictionary<string, string> Strings = new()
    {
        ["onboarding.header_welcome"] = "¡Bienvenido!",
        ["onboarding.header_how_it_works"] = "Cómo funciona",
        ["onboarding.header_terms_of_service"] = "Términos del servicio",
        ["onboarding.header_sign_in"] = "Iniciar sesión",
        ["onboarding.header_secure_messages"] = "Protege tus mensajes",
        ["onboarding.header_your_profile"] = "Tu perfil",
        ["onboarding.header_profile_picture"] = "Foto de perfil",
        ["onboarding.header_your_photos"] = "Tus fotos",
        ["onboarding.header_optional_details"] = "Detalles opcionales",
        ["onboarding.header_match_preferences"] = "Preferencias de coincidencia",
        ["onboarding.header_make_it_yours"] = "Hazlo a tu gusto",
        ["onboarding.header_all_set"] = "¡Todo listo!",
        ["onboarding.header_default"] = "AetherLove",

        ["onboarding.back"] = "← Atrás",
        ["onboarding.saving"] = "Guardando…",
        ["onboarding.start_swiping"] = "Empezar a deslizar →",
        ["onboarding.finish"] = "Finalizar →",
        ["onboarding.retry"] = "Reintentar →",
        ["onboarding.next"] = "Siguiente →",
        ["onboarding.could_not_assemble"] = "No se pudo preparar {0}: {1}",
        ["onboarding.select_photo"] = "Seleccionar foto",
        ["onboarding.image_files"] = "Archivos de imagen",
        ["onboarding.crop_avatar"] = "Recortar avatar",
        ["onboarding.crop_main_photo"] = "Recortar foto principal",
        ["onboarding.crop_extra_photo"] = "Recortar foto adicional {0}",

        // Step 2 — How It Works
        ["onboarding.how_intro"] = "Así funciona AetherLove — desde crear tu perfil hasta chatear con tu primera coincidencia.",
        ["onboarding.how1_title"] = "Crea tu perfil",
        ["onboarding.how1_body"] = "Cuéntanos sobre tu personaje: su raza, servidor, idiomas y lo que buscas. Sube una foto de retrato. Esta es tu carta de presentación.",
        ["onboarding.how2_title"] = "Explora el mazo",
        ["onboarding.how2_body"] = "Cada vez que abras el mazo verás una pila de tarjetas de perfil. Desliza a la derecha (o toca ♥) para mostrar interés. Desliza a la izquierda (o toca X) para pasar.",
        ["onboarding.how3_title"] = "Define tus preferencias",
        ["onboarding.how3_body"] = "Elige la raza, la región, los idiomas y los intereses que te gustaría encontrar en una coincidencia. Cuanto más específico seas, mejores serán las coincidencias que verás.",
        ["onboarding.how4_title"] = "¡Coincide!",
        ["onboarding.how4_body"] = "Cuando dos personas se deslizan a la derecha mutuamente, se convierte en una coincidencia. Recibirás una notificación y se abrirá un chat privado automáticamente.",
        ["onboarding.how5_title"] = "Chatea dentro del juego",
        ["onboarding.how5_body"] = "Envía mensajes directamente a través del plugin, sin necesidad de ninguna app externa. Tus conversaciones están cifradas de extremo a extremo, así que ni siquiera los desarrolladores de AetherLove pueden leer tus chats.",
        ["onboarding.how6_title"] = "Mantén el control",
        ["onboarding.how6_body"] = "Actualiza tu perfil, ajusta tus preferencias o deshaz una coincidencia cuando quieras desde la pantalla de Ajustes. AetherLove NUNCA compartirá tu nombre completo de jugador, tu ubicación ni la información de tu cuenta con otros jugadores.",
        ["onboarding.how_ready"] = "¿Listo para empezar? Pulsa Siguiente para continuar.",

        // Step 2 — Terms of Service
        ["onboarding.tos_p1"] = "AetherLove es un plugin de emparejamiento social para Final Fantasy XIV dirigido a usuarios adultos. Al continuar, confirmas que tienes al menos 18 años y consientes participar en una plataforma social para adultos.",
        ["onboarding.tos_p2"] = "Entiendo que la información de perfil que proporciono —incluidos mi nombre visible, biografía, servidor de origen, datos del personaje y cualquier foto que suba— puede ser visible para otros usuarios de AetherLove. Soy responsable de la veracidad de mi perfil y de asegurarme de que las fotos que suba sean apropiadas y de que tengo derecho a compartirlas.",
        ["onboarding.tos_ownership"] = "Los personajes que aparezcan en cualquier foto que suba deben ser los míos. Si en una imagen aparece el personaje de otro jugador, confirmo que tengo su permiso para compartirla. No subiré capturas ni poses de personajes que no sean míos sin el consentimiento de su propietario.",
        ["onboarding.tos_p3"] = "Me comprometo a interactuar con respeto con todos los demás usuarios. El acoso, el contenido explícito no solicitado, los discursos de odio o cualquier forma de abuso hacia otros usuarios están estrictamente prohibidos. La infracción de estos términos puede conllevar la expulsión de la plataforma sin previo aviso ni posibilidad de apelación.",
        ["onboarding.tos_nsfl"] = "El contenido NSFL (\"Not Suitable For Life\") nunca está permitido en AetherLove bajo ninguna circunstancia. Esto incluye cualquier imagen o mensaje que muestre violencia sangrienta real o simulada, muerte, violencia gráfica, mutilación, lesiones graves, crueldad animal o autolesiones, así como cualquier otro material chocante o repugnante. Esto es totalmente independiente de la opción NSFW: marcar algo como NSFW nunca hace aceptable el contenido NSFL. Aplicamos una estricta política de tolerancia cero. Publicar contenido NSFL conlleva un baneo inmediato y permanente de la cuenta, sin previo aviso y sin derecho a apelación.",
        ["onboarding.tos_p4"] = "Entiendo que AetherLove es un plugin no oficial, creado por la comunidad, y que no está afiliado ni respaldado por Square Enix Co., Ltd. Se ofrece tal cual, sin garantías de disponibilidad, seguridad de datos o idoneidad para ningún fin. Los desarrolladores del plugin no se hacen responsables de las acciones de otros usuarios ni de las consecuencias derivadas del uso de este plugin.",
        ["onboarding.tos_p5"] = "Las decisiones de moderación —incluidas advertencias, suspensiones temporales y baneos permanentes— se toman a entera discreción del equipo de AetherLove. El equipo tiene la última palabra en todos los asuntos de moderación. Las decisiones no tienen por qué explicarse ni justificarse al usuario afectado, y no están sujetas a apelación salvo que el equipo indique explícitamente lo contrario.",
        ["onboarding.tos_p6"] = "Queremos y disfrutamos de los personajes Lalafell tanto como cualquiera, pero las funciones para adultos y NSFW no están disponibles para jugadores cuya raza de personaje sea Lalafell. Como los Lalafell tienen aspecto infantil, no hacemos distinciones caso por caso y aplicamos esta política de manera uniforme a todas las cuentas Lalafell. La opción de rol +18, la activación de NSFW y la subida de fotos NSFW están todas deshabilitadas mientras tu raza esté fijada como Lalafell. Intentar saltarse esta restricción es motivo de expulsión de la cuenta.",
        ["onboarding.tos_ai"] = "Moderación asistida por IA — Acepto que el texto de mi perfil y las imágenes de mi perfil se revisen automáticamente mediante las API de moderación de OpenAI para ayudar a detectar contenido que infrinja estas reglas y mantener AetherLove seguro para todos. Acepto además que mis imágenes de perfil sean evaluadas por un modelo adicional de OpenAI, tanto para comprobar si cumplen las reglas de imágenes de AetherLove (que muestren a mi propio personaje de Final Fantasy XIV, y no fan art, imágenes generadas por IA ni contenido no relacionado) como para determinar si son SFW o NSFW. El texto y las imágenes de mi perfil se envían a OpenAI únicamente para su moderación y nunca se usan para entrenar los modelos de OpenAI. Entiendo que toda decisión final de moderación la toma el equipo humano de AetherLove: la IA por sí sola nunca es responsable de una acción de moderación.",
        ["onboarding.tos_p7"] = "Reconozco que estos términos pueden actualizarse en cualquier momento. El uso continuado de AetherLove tras una actualización constituye la aceptación de los términos revisados.",
        ["onboarding.tos_read_carefully"] = "LEE CON ATENCIÓN",
        ["onboarding.tos_accepted"] = "Términos aceptados — pulsa Siguiente para continuar.",
        ["onboarding.tos_timer"] = "Por favor, lee con atención — el botón de aceptar estará disponible en {0} s",
        ["onboarding.tos_scroll_bottom"] = "Desplázate hasta el final para aceptar.",
        ["onboarding.tos_i_agree"] = "Acepto",

        // Step 3 — XIVAuth
        ["onboarding.auth_signin_with_xivauth"] = "Iniciar sesión con XIVAuth",
        ["onboarding.auth_intro"] = "AetherLove usa XIVAuth para verificar tu identidad como jugador activo de Final Fantasy XIV. No se necesita contraseña: la autenticación se gestiona de forma segura a través de tu cliente del juego.",
        ["onboarding.auth_contacting"] = "Contactando con AetherLove",
        ["onboarding.auth_dont_have_xivauth"] = "¿No tienes XIVAuth?",
        ["onboarding.auth_xivauth_explainer"] = "XIVAuth es un inicio de sesión único gratuito y gestionado por la comunidad para herramientas de Final Fantasy XIV. Confirma que eres un jugador real de FFXIV vinculando tu personaje de Lodestone, sin compartir nunca tu contraseña de Square Enix. Registrarse solo lleva un minuto.",
        ["onboarding.auth_create_account"] = "Crear una cuenta de XIVAuth",
        ["onboarding.auth_complete_in_browser"] = "Completa el inicio de sesión en tu navegador",
        ["onboarding.auth_browser_opened"] = "Se ha abierto una ventana del navegador. Termina de iniciar sesión con XIVAuth y vuelve aquí — este paso continuará automáticamente.",
        ["onboarding.auth_open_browser_again"] = "Abrir el navegador de nuevo",
        ["onboarding.auth_cancel"] = "Cancelar",
        ["onboarding.auth_loading_profile"] = "¡Sesión iniciada! Cargando tu perfil",
        ["onboarding.auth_signed_in"] = "¡Sesión iniciada!",
        ["onboarding.auth_welcome_back"] = "¡Bienvenido de nuevo!",
        ["onboarding.auth_welcome_back_named"] = "¡Bienvenido de nuevo, {0}!",
        ["onboarding.auth_details_loaded"] = "Hemos cargado tus datos — puedes empezar a deslizar ahora mismo.",
        ["onboarding.auth_timeout"] = "El inicio de sesión tardó demasiado. Inténtalo de nuevo.",
        ["onboarding.auth_failed"] = "Error al iniciar sesión.",
        ["onboarding.auth_try_again"] = "Intentar de nuevo",

        // Step 3a — Passphrase
        ["onboarding.pass_heading"] = "Protege tus mensajes",
        ["onboarding.pass_intro"] = "El equipo de AetherLove no puede leer tus mensajes privados — ni ahora ni nunca. Para hacerlo posible, ciframos cada mensaje con una clave que solo TÚ conoces. Define una frase de contraseña abajo. Una frase de contraseña es como una contraseña, pero una que debes recordar y guardar — no existe ningún botón de \"olvidé mi frase de contraseña\". Apúntala, guárdala en un gestor de contraseñas, haz lo que harías con una contraseña crítica.",
        ["onboarding.pass_warning"] = "Si usas AetherLove en otro ordenador —o compras uno nuevo— tendrás que introducir esta frase de contraseña de nuevo para leer tus chats. Sin ella, tus mensajes son ilegibles incluso para ti.",
        ["onboarding.pass_label"] = "Frase de contraseña",
        ["onboarding.pass_confirm_label"] = "Confirmar frase de contraseña",
        ["onboarding.pass_err_empty"] = "Por favor, introduce una frase de contraseña.",
        ["onboarding.pass_err_too_short"] = "La frase de contraseña debe tener al menos {0} caracteres.",
        ["onboarding.pass_err_confirm_empty"] = "Por favor, confirma tu frase de contraseña.",
        ["onboarding.pass_err_mismatch"] = "Las frases de contraseña no coinciden.",
        ["onboarding.pass_ack"] = "Entiendo que mi historial de chat no podrá recuperarse si olvido esta frase de contraseña.",
        ["onboarding.pass_securing"] = "Protegiendo tus claves…",
        ["onboarding.pass_strength_too_weak"] = "Demasiado débil",
        ["onboarding.pass_strength_weak"] = "Débil",
        ["onboarding.pass_strength_ok"] = "Aceptable",
        ["onboarding.pass_strength_good"] = "Buena",
        ["onboarding.pass_strength_strong"] = "Fuerte",

        // Step 4 — Profile (data labels)
        ["onboarding.region_na"] = "Norteamérica (NA)",
        ["onboarding.region_eu"] = "Europa (EU)",
        ["onboarding.region_oceania"] = "Oceanía",
        ["onboarding.region_japan"] = "Japón",
        ["onboarding.race_hyur"] = "Hyur",
        ["onboarding.race_elezen"] = "Elezen",
        ["onboarding.race_lalafell"] = "Lalafell",
        ["onboarding.race_miqote"] = "Miqo'te",
        ["onboarding.race_roegadyn"] = "Roegadyn",
        ["onboarding.race_au_ra"] = "Au Ra",
        ["onboarding.race_hrothgar"] = "Hrothgar",
        ["onboarding.race_viera"] = "Viera",
        ["onboarding.gender_male"] = "Hombre",
        ["onboarding.gender_female"] = "Mujer",
        ["onboarding.gender_other"] = "Otro",
        ["onboarding.content_housing"] = "Viviendas y decoración",
        ["onboarding.content_music_bard"] = "Música e interpretación de Bardo",
        ["onboarding.content_rp_venues"] = "Visitar locales de rol",
        ["onboarding.content_club_venues"] = "Visitar discotecas",
        ["onboarding.content_gpose"] = "Gpose",
        ["onboarding.content_story_lore"] = "Historia y trasfondo",
        ["onboarding.content_roulettes"] = "Ruletas",
        ["onboarding.content_regular"] = "Contenido normal",
        ["onboarding.content_extreme_trials"] = "Pruebas extremas",
        ["onboarding.content_savage"] = "Incursiones salvajes",
        ["onboarding.content_pvp"] = "JcJ",
        ["onboarding.content_blue_mage"] = "Mago Azul",
        ["onboarding.content_triple_triad"] = "Triple Tríada",
        ["onboarding.content_mahjong"] = "Mahjong",
        ["onboarding.content_treasure_hunts"] = "Cazas del tesoro",
        ["onboarding.content_crafting_gathering"] = "Artesanía y recolección",
        ["onboarding.content_fishing"] = "Pesca",
        ["onboarding.content_achievement_hunting"]= "Caza de logros",
        ["onboarding.lf_chatting"] = "Charlar con gente nueva",
        ["onboarding.lf_casual_buddies"] = "Compañeros de juego casual",
        ["onboarding.lf_gpose_glamour"] = "Compañeros de GPose y glamur",
        ["onboarding.lf_romance"] = "Un romance dentro del juego",
        ["onboarding.lf_long_term"] = "Una relación duradera dentro del juego",
        ["onboarding.lf_rp_partners"] = "Compañeros de rol",
        ["onboarding.lf_erp"] = "Rol +18 (ERP)",

        // Step 4 — Profile (body)
        ["onboarding.profile_intro"] = "Estos campos aparecen en la tarjeta pública de tu perfil y se usan para sugerir coincidencias.",
        ["onboarding.profile_identity"] = "Identidad",
        ["onboarding.profile_display_name"] = "Nombre visible",
        ["onboarding.profile_display_name_tip"] = "El nombre que ven los demás usuarios. Usa tu nombre de pila o un alias.\nNo se permiten espacios.",
        ["onboarding.profile_display_name_hint"] = "Nombre de pila o alias, sin espacios, al menos 3 caracteres.",
        ["onboarding.profile_about_me"] = "Sobre mí",
        ["onboarding.profile_about_me_tip"] = "Escribe una breve presentación. ¿Qué te gusta?\n¿Qué tipo de conexiones buscas?",
        ["onboarding.profile_char_count"] = "{0} / 500 caracteres",
        ["onboarding.profile_preview"] = "Vista previa",
        ["onboarding.profile_bio_placeholder"] = "Tu biografía aparecerá aquí…",
        ["onboarding.profile_location"] = "Ubicación",
        ["onboarding.profile_server_region"] = "Región del servidor",
        ["onboarding.profile_server_region_tip"] = "Selecciona tu región de Final Fantasy XIV.\nEsto ayuda a emparejarte con jugadores cercanos.",
        ["onboarding.profile_character"] = "Personaje",
        ["onboarding.profile_race"] = "Raza",
        ["onboarding.profile_gender"] = "Género",
        ["onboarding.profile_languages_speak"] = "Idiomas que hablo",
        ["onboarding.profile_languages_hint"] = "Selecciona todos los idiomas en los que te sientas cómodo chateando.",
        ["onboarding.profile_content_heading"] = "Disfruto del siguiente contenido",
        ["onboarding.profile_content_hint"] = "Selecciona todo lo que aplique — esto aparece en la tarjeta de tu perfil.",
        ["onboarding.profile_looking_for_heading"]= "Estoy buscando",
        ["onboarding.profile_looking_for_hint"] = "Selecciona todo lo que aplique (al menos uno es obligatorio). Ser sincero ayuda a encontrar mejores coincidencias.",
        ["onboarding.profile_erp_enables_nsfw"] = "    Seleccionar esto activa automáticamente el NSFW en tu perfil.",
        ["onboarding.profile_nsfw_heading"] = "NSFW",
        ["onboarding.profile_nsfw_lalafell"] = "Las funciones para adultos y NSFW no están disponibles mientras tu raza esté fijada como Lalafell. Consulta los Términos del servicio para más detalles.",
        ["onboarding.profile_nsfw_explainer"] = "NSFW significa \"Not Safe For Work\" (no apto para el trabajo): contenido con desnudos o temática sexual. ¿Quieres activar los perfiles NSFW? Esto dará lugar a posibles coincidencias con jugadores que hayan subido fotos NSFW a su perfil. Esas imágenes siempre aparecen difuminadas hasta que decidas revelarlas.",
        ["onboarding.profile_nsfw_checkbox"] = "Perfiles NSFW: SÍ",
        ["onboarding.profile_nsfw_locked"] = "Activado de forma obligatoria porque seleccionaste Rol +18 (ERP). Desmárcalo para cambiar este ajuste.",
        ["onboarding.profile_timezone"] = "Zona horaria",
        ["onboarding.profile_timezone_hint"] = "Se muestra a posibles coincidencias para que sepan cuándo estás activo.",

        // Step 5 — Avatar
        ["onboarding.avatar_heading"] = "Tu foto de perfil",
        ["onboarding.avatar_intro"] = "Tu foto de perfil se muestra en el chat y durante el emparejamiento. Requerimos una imagen cuadrada que contenga una foto de la cara de tu personaje de FFXIV.",
        ["onboarding.avatar_tip"] = "Consejo: una captura de G-Pose de retrato en primer plano funciona mejor.",
        ["onboarding.avatar_sfw_warning"] = "Tu foto de perfil principal DEBE ser SFW. Subir una foto NSFW es motivo de eliminación de la cuenta.",
        ["onboarding.avatar_browse"] = "Examinar…",
        ["onboarding.avatar_crop_hint"] = "El editor de recorte se abrió en una ventana aparte.\nHaz clic en \"Usar este recorte\" allí para confirmar tu avatar.",
        ["onboarding.avatar_no_image"] = "Aún no se ha seleccionado ninguna imagen.",
        ["onboarding.avatar_set"] = "¡Foto de perfil establecida!",
        ["onboarding.avatar_change_photo"] = "Cambiar foto",
        ["onboarding.avatar_its_a_match"] = "¡Es una coincidencia!",
        ["onboarding.avatar_match_preview_caption"] = "Vista previa: cómo aparece tu avatar en las tarjetas de coincidencia",

        // Step 5 — Image Disclaimer
        ["onboarding.disclaimer_intro"] = "AetherLove está hecho para jugadores de Final Fantasy XIV. Antes de subir cualquier imagen, lee atentamente las siguientes pautas.",
        ["onboarding.disclaimer_moderation"] = "Todas las subidas están sujetas a moderación automática y manual.",
        ["onboarding.disclaimer_general_heading"] = "General",
        ["onboarding.disclaimer_general_body"] = "Todas las imágenes subidas a AetherLove deben mostrar a tu personaje de Final Fantasy XIV. Las imágenes no relacionadas con personajes de Final Fantasy XIV serán rechazadas sin previo aviso.",
        ["onboarding.disclaimer_profile_images_heading"] = "Imágenes de perfil",
        ["onboarding.disclaimer_profile_images_body"] = "Las imágenes que se muestran en tu perfil deben ser capturas o G-Poses de tu propio personaje de Final Fantasy XIV. Lo siguiente está:",
        ["onboarding.disclaimer_not_allowed"] = "NO PERMITIDO:",
        ["onboarding.disclaimer_na_fan_art"] = "Fan art",
        ["onboarding.disclaimer_na_3d_renders"] = "Renders 3D personalizados",
        ["onboarding.disclaimer_na_ai"] = "Imágenes generadas por IA",
        ["onboarding.disclaimer_na_real_photos"] = "Fotografías de personas o lugares reales",
        ["onboarding.disclaimer_na_unrelated"] = "Cualquier imagen no relacionada con tu personaje de FFXIV",
        ["onboarding.disclaimer_profile_images_consent"] = "Sube solo imágenes de tu propio personaje. Si en una captura aparece el personaje de otro jugador, asegúrate primero de contar con su permiso. Por favor, no subas capturas ni poses del personaje de otra persona sin su consentimiento.",
        ["onboarding.disclaimer_nsfw_heading"] = "Contenido NSFW",
        ["onboarding.disclaimer_nsfw_body1"] = "Tu avatar principal y tu foto de perfil principal deben ser SFW (aptos para el trabajo). Una regla sencilla: si te sentirías cómodo mostrando la imagen a un jefe o compañero de trabajo, es aceptable como imagen principal.",
        ["onboarding.disclaimer_nsfw_body2"] = "Las fotos de perfil adicionales pueden contener contenido NSFW, pero deben marcarse explícitamente como tal al subirlas. Te recomendamos encarecidamente mantener tantas imágenes SFW como sea posible.",
        ["onboarding.disclaimer_nsfl_heading"] = "Contenido NSFL: Nunca permitido",
        ["onboarding.disclaimer_nsfl_body"] = "El contenido NSFL (\"Not Suitable For Life\") nunca está permitido en ninguna imagen, independientemente de si se marca como SFW o NSFW. Esto abarca cualquier representación de violencia sangrienta real o simulada, muerte, violencia gráfica, mutilación, lesiones graves, crueldad animal o autolesiones, además de cualquier otra cosa destinada a impactar, perturbar o repugnar. Esto es completamente independiente de las reglas NSFW anteriores: una marca NSFW permite contenido sugerente, nunca contenido NSFL.",
        ["onboarding.disclaimer_nsfl_zero_tolerance"] = "Tolerancia cero: subir contenido NSFL supone un baneo inmediato y permanente de la cuenta, sin previo aviso ni apelación.",
        ["onboarding.disclaimer_ai_heading"] = "Moderación asistida por IA",
        ["onboarding.disclaimer_ai_body"] = "Cada imagen que subes se revisa automáticamente mediante las API de moderación de OpenAI y es evaluada por un modelo adicional de OpenAI, tanto para comprobar si cumple las reglas de imágenes de arriba (que muestre a tu propio personaje de FFXIV y no sea fan art, una imagen generada por IA ni contenido no relacionado) como para determinar si es SFW o NSFW. Tus imágenes se envían a OpenAI únicamente para su moderación y nunca se usan para entrenar los modelos de OpenAI. Toda decisión final de moderación la toma el equipo humano de AetherLove: la IA por sí sola nunca es responsable de una acción de moderación.",
        ["onboarding.disclaimer_rules_heading"] = "¿Qué pasa si una imagen incumple las reglas?",
        ["onboarding.disclaimer_rules_body1"] = "Si se detecta que una de tus imágenes infringe estas pautas, recibirás una notificación. La imagen se eliminará automáticamente y tu perfil quedará en suspenso —shadowban— hasta que corrijas el problema.",
        ["onboarding.disclaimer_rules_body2"] = "Subir contenido dañino, abusivo o ilegal dará lugar a:",
        ["onboarding.disclaimer_permanent_ban"] = "Un baneo permanente de la cuenta.",
        ["onboarding.disclaimer_continue"] = "Entiendo, continuar",

        // Step 6 — Photos
        ["onboarding.photos_heading"] = "Fotos de perfil",
        ["onboarding.photos_intro"] = "Añade fotos de retrato a tu perfil (relación de aspecto 10:16). La primera ranura es obligatoria; las ranuras 2–4 son opcionales. Para mejores resultados usa imágenes de al menos 480 × 768 px.",
        ["onboarding.photos_main_thumb"] = "Principal",
        ["onboarding.photos_tap_slot"] = "Toca una ranura de arriba para añadir o gestionar una foto.",
        ["onboarding.photos_main_photo"] = "Foto principal",
        ["onboarding.photos_extra_photo"] = "Foto adicional {0}",
        ["onboarding.photos_main_sfw_warning"] = "Tu foto de perfil principal DEBE ser SFW. Subir una foto NSFW es motivo de suspensión o eliminación de la cuenta.",
        ["onboarding.photos_sfw_nsfw_question"] = "¿Esta foto es SFW o NSFW?",
        ["onboarding.photos_mismatch_warning"] = "Si nuestro sistema detecta que subiste contenido NSFW estando seleccionado SFW, tu foto quedará retenida para moderación y te arriesgas a la suspensión de la cuenta.",
        ["onboarding.photos_previously_uploaded"] = "Subida anteriormente.",
        ["onboarding.photos_confirmed"] = "Foto confirmada.",
        ["onboarding.photos_remove"] = "Eliminar",
        ["onboarding.photos_browse"] = "Examinar…",
        ["onboarding.photos_crop_hint"] = "El editor de recorte se abrió en una ventana aparte.\nHaz clic en \"Usar este recorte\" allí para confirmar la foto.",
        ["onboarding.photos_required"] = "Esta foto es obligatoria.",
        ["onboarding.photos_optional"] = "Esta foto es opcional.",

        // Step 7 — Optional
        ["onboarding.expansion_none"] = "(Ninguna)",
        ["onboarding.opt_heading"] = "Cuéntanos más sobre ti",
        ["onboarding.opt_intro"] = "Todos los campos de esta página son opcionales. Rellena tanto o tan poco como quieras — estos datos aparecen en la tarjeta de tu perfil y ayudan a otros a encontrarte.",
        ["onboarding.opt_fav_job"] = "Trabajo favorito",
        ["onboarding.opt_fav_job_tip"] = "El trabajo o rol que más disfrutas.\nEscribe para filtrar.",
        ["onboarding.opt_fav_location"] = "Lugar favorito",
        ["onboarding.opt_fav_location_tip"] = "Un lugar de Eorzea que te encanta visitar.\nEscribe para filtrar.",
        ["onboarding.opt_location_unavailable"] = "(datos de ubicación no disponibles)",
        ["onboarding.opt_location_none"] = "(Ninguno)",
        ["onboarding.opt_fav_expansion"] = "Expansión favorita",
        ["onboarding.opt_fav_expansion_tip"] = "Tu expansión favorita de FFXIV de todos los tiempos.",
        ["onboarding.opt_music_heading"] = "Canción favorita",
        ["onboarding.opt_music_tip"] = "Pega un enlace de Spotify, SoundCloud, Apple Music o YouTube Music.",
        ["onboarding.opt_fav_spotify"] = "Spotify",
        ["onboarding.opt_fav_spotify_tip"] = "Pega la URL de una pista de Spotify o el ID de la pista.\nEl nombre de la pista se obtiene automáticamente.",
        ["onboarding.opt_fav_soundcloud"] = "SoundCloud",
        ["onboarding.opt_fav_apple"] = "Apple Music",
        ["onboarding.opt_fav_youtube"] = "YouTube Music",
        ["onboarding.opt_fav_movie"] = "Película favorita",
        ["onboarding.opt_fav_movie_tip"] = "Tu película favorita de todos los tiempos — de cualquier género.",
        ["onboarding.opt_fav_anime"] = "Anime favorito",
        ["onboarding.opt_fav_anime_tip"] = "Tu serie o película de anime favorita.",
        ["onboarding.opt_fav_ff_character"] = "Personaje favorito de Final Fantasy",
        ["onboarding.opt_fav_ff_character_tip"] = "Cualquier personaje del universo de Final Fantasy.",
        ["onboarding.opt_weekday_playtimes"] = "Horarios de juego entre semana (lun–vie)",
        ["onboarding.opt_weekday_playtimes_tip"] = "Haz clic en las horas en que sueles estar en línea entre semana.\nPasa el cursor sobre una barra para ver la hora.\nElige tu hora local.",
        ["onboarding.opt_weekend_playtimes"] = "Horarios de juego en fin de semana (sáb–dom)",
        ["onboarding.opt_weekend_playtimes_tip"] = "Haz clic en las horas en que sueles estar en línea los fines de semana.\nPasa el cursor sobre una barra para ver la hora.\nElige tu hora local.",
        ["onboarding.opt_sync_tool"] = "Herramienta de sincronización usada",
        ["onboarding.opt_sync_tool_tip"] = "Las herramientas de sincronización como Lightless o Honsefarm permiten a los usuarios emparejados\ncompartir apariencias de mods automáticamente.",
        ["onboarding.time_am"] = "AM",
        ["onboarding.time_pm"] = "PM",

        // Step 8 — Filters
        ["onboarding.filters_intro"] = "Cuéntanos con quién te gustaría coincidir. Estas preferencias nos ayudan a mostrarte a las personas adecuadas — puedes ajustarlas en cualquier momento en los Ajustes.",
        ["onboarding.filters_heading"] = "Deseo coincidir con",
        ["onboarding.filters_race"] = "Raza",
        ["onboarding.filters_gender"] = "Género",
        ["onboarding.filters_region"] = "Región",
        ["onboarding.filters_spoken_language"] = "Idioma hablado",
        ["onboarding.filters_language_tip"] = "Déjalo todo sin marcar para coincidir sin importar el idioma hablado.",
        ["onboarding.filters_all"] = "Todos",
        ["onboarding.filters_none"] = "Ninguno",
        ["onboarding.filters_clear"] = "Limpiar",
        ["onboarding.filters_any_race"] = "  Sin selección — cualquier raza",
        ["onboarding.filters_any_gender"] = "  Sin selección — cualquier género",
        ["onboarding.filters_any_region"] = "  Sin selección — cualquier región",
        ["onboarding.filters_any_language"] = "  Sin selección — sin preferencia de idioma",

        // Step 9 — Finished
        ["onboarding.finished_heading"] = "¡Todo listo!",
        ["onboarding.finished_intro"] = "Tu perfil se ha creado y tus preferencias de coincidencia se han guardado. Ya puedes empezar a conectar con otros jugadores de Final Fantasy XIV.",
        ["onboarding.finished_verification_heading"] = "Verificación del perfil",
        ["onboarding.finished_verification_body"] = "Nuestro equipo de moderación revisará tu perfil en un plazo de 24 horas. Durante este tiempo tu perfil está totalmente activo — puedes explorar, coincidir y chatear de inmediato.",
        ["onboarding.finished_verification_note"] = "Solo nos pondremos en contacto si hay algún problema con tu perfil o tus imágenes.",
        ["onboarding.finished_swiping_heading"] = "Empieza a deslizar",
        ["onboarding.finished_swiping_body"] = "Ve al mazo para explorar perfiles. Toca ♥ en alguien que te interese — cuando esa persona también toque ♥, ¡es una coincidencia! Se abre un chat privado automáticamente.",
        ["onboarding.finished_rejected_heading"] = "Si se rechaza una imagen",
        ["onboarding.finished_rejected_body"] = "Si alguna de tus imágenes infringe nuestras pautas durante la revisión, recibirás una notificación. La imagen se eliminará y se te pedirá que la reemplaces. Mientras tanto, tu perfil sigue activo.",
        ["onboarding.finished_good_luck"] = "¡Mucha suerte ahí fuera — AetherLove está de tu parte! ♥",

        // Step 10 — Preferences
        ["onboarding.prefs_intro"] = "Haz que AetherLove sea tuyo — elige un tema de color y un tamaño de teléfono. Puedes cambiar ambos en cualquier momento en los Ajustes.",
        ["onboarding.prefs_theme"] = "Tema",
        ["onboarding.prefs_phone_size"] = "Tamaño del teléfono",

        // added after update (1.3.1)
        ["onboarding.content_ultimate_raiding"] = "Incursiones Ultimate",
        ["onboarding.content_deep_dungeons"] = "Mazmorras profundas",
        ["onboarding.content_variant_criterion"] = "Mazmorras variantes / de criterio",
        ["onboarding.content_field_operations"] = "Operaciones de campo (Bozja, Eureka)",
        ["onboarding.race_gender_warning"] = "¡Elige la raza y el género de tu personaje de FFXIV, no tu género en la vida real!",
        ["onboarding.tos_race_gender"] = "Acepto elegir la raza y el género correctos para mi personaje de Final Fantasy XIV durante la configuración, y entiendo que mi foto de perfil principal debe reflejar a ese personaje.",
    };
}
