namespace AetherLove.Services.Localization;

internal static class DeckPt
{
    public static readonly System.Collections.Generic.Dictionary<string, string> Strings = new()
    {
        ["deck.cooldown_heading"] = "Você viu tudo por enquanto!",
        ["deck.cooldown_body"] = "O AetherLove te entrega um novo lote de perfis a cada poucas horas, para que todo mundo tenha uma chance justa. Volte em breve para novos possíveis matches!",
        ["deck.new_matches_ready"] = "Novos matches estão prontos!",
        ["deck.server_error"] = "Não foi possível acessar o servidor: {0}",
        ["deck.view_profile"] = "Ver perfil",
        ["deck.like"] = "CURTIR",
        ["deck.nope"] = "PASSAR",
        ["deck.match_you"] = "Você",
        ["deck.match_your_match"] = "Seu match",
        ["deck.match_congratulations"] = "Parabéns!",
        ["deck.match_its_a_match"] = "Deu Match!",
        ["deck.match_fx_cosmic"] = "Duas almas, a mesma órbita",
        ["deck.match_fx_synthwave"] = "Rumo ao pôr do sol, juntos",
        ["deck.match_fx_aurora"] = "A mesma luz uniu vocês",
        ["deck.match_fx_kaleido"] = "A simetria perfeita",
        ["deck.match_fx_supernova"] = "Dois corações, uma só batida",
        ["deck.match_fx_vortex"] = "Atraídos pela mesma órbita",
        ["deck.match_fx_portal"] = "Saídos da mesma fenda",
        ["deck.match_fx_electric"] = "As faíscas estão voando",
        ["deck.match_fx_bubble"] = "Duas bolhas, o mesmo brilho",
        ["deck.match_fx_dna"] = "Um par de bases perfeito.",
        ["deck.match_fx_firework"] = "Que o céu comemore",
        ["deck.match_fx_vinyl"] = "Na mesma sintonia",
        ["deck.match_fx_arcade_players"] = "* JOGADOR 1 *   * JOGADOR 2 *",
        ["deck.match_fx_arcade_score"] = "PONTOS",
        ["deck.match_fx_constellation"] = "Escrito nas estrelas",
        ["deck.match_fx_slot"] = "Três iguais",
        ["deck.match_fx_slot_title"] = "PRÊMIO MÁXIMO!",
        ["deck.match_fx_tarot"] = "As cartas se alinham — dois destinos entrelaçados",
        ["deck.match_fx_tarot_title"] = "OS NAMORADOS",
        ["deck.match_fx_lavalamp"] = "Duas chamas, um só calor",
        ["deck.match_fx_lanterns"] = "Duas luzes, o mesmo céu",
        ["deck.match_fx_treasure"] = "Um par que vale ouro",
        ["deck.match_fx_treasure_title"] = "TESOURO ENCONTRADO",
        ["deck.match_start_chatting"] = "Começar a Conversar",
        ["deck.match_keep_swiping"] = "Continuar Deslizando",
        ["deck.no_pool_heading"] = "Sem mais matches",
        ["deck.no_pool_body"] = "Não foram encontrados mais matches para você com os seus critérios atuais. Amplie seus critérios e tente novamente mais tarde.",
    };
}
