namespace AetherLove.Services.Localization;

internal static class ChatDe
{
    public static readonly System.Collections.Generic.Dictionary<string, string> Strings = new()
    {
        // ===== Chat =====
        ["chat.no_conversation_selected"] = "Kein Gespräch ausgewählt.",
        ["chat.unreadable_message"] = "[unlesbare Nachricht]",
        ["chat.report_submitted_toast"] = "Meldung eingereicht. Unser Moderationsteam wird sie prüfen.",
        ["chat.view_profile"] = "Profil ansehen",
        ["chat.back_to_matches"] = "Zurück zu den Matches",
        ["chat.menu_open_profile"] = "Profil öffnen",
        ["chat.menu_copy_message"] = "Nachricht kopieren",
        ["chat.menu_pin"] = "Chat anheften",
        ["chat.menu_unpin"] = "Chat lösen",
        ["chat.menu_unmatch"] = "Match auflösen",
        ["chat.menu_block"] = "Blockieren",
        ["chat.menu_report_user"] = "Nutzer melden",
        ["chat.unmatch_title"] = "Match auflösen",
        ["chat.unmatch_body"] = "Wenn du das Match mit diesem Spieler auflöst, wird der Chat für beide Personen ausgeblendet. Wenn ihr euch später erneut matcht, erscheint euer Verlauf wieder.",
        ["chat.unmatch_confirm"] = "Match auflösen",
        ["chat.block_title"] = "Nutzer blockieren",
        ["chat.block_body"] = "Wenn du einen Nutzer blockierst, wird der Chat für beide Personen ausgeblendet und er erscheint künftig nicht mehr in deinen Matches.",
        ["chat.block_confirm"] = "Blockieren",
        ["chat.cancel"] = "Abbrechen",
        ["chat.loading_messages"] = "Nachrichten werden geladen…",
        ["chat.error"] = "Fehler: {0}",
        ["chat.e2e_self_broken"] = "Mit deiner E2E-Einrichtung stimmt etwas nicht. Bitte kontaktiere den Support.",
        ["chat.seen_suffix"] = " · gesehen",
        ["chat.send"] = "Senden",
        ["chat.emoji_button"] = ":)",
        ["chat.system_notice_line1"] = "Dies ist ein privater Chat zwischen dir und {0}. Dieser Chat ist Ende-zu-Ende-verschlüsselt, das AetherLove-Team kann deine Nachrichten nicht lesen. Oben rechts findest du ein Menü, um das Match aufzulösen, zu blockieren oder dein Match zu melden.",
        ["chat.system_notice_line2"] = "Denk daran: {0} kennt deinen vollständigen Namen oder deinen Standort nicht, bis du sie mit ihm teilst. Achte auf deine eigene Privatsphäre und teile nur mehr, wenn du bereit bist.",
        ["chat.i_understand"] = "Ich verstehe",
        ["chat.report_title"] = "Nutzer melden",
        ["chat.report_reason_prompt"] = "Bitte beschreibe den Grund für deine Meldung:",
        ["chat.report_agree"] = "Ich stimme zu, eine Meldung gegen {0} einzureichen",
        ["chat.report_agree_contents"] = "Ich stimme zu, den Inhalt dieses Gesprächs an das AetherLove-Team zu senden",
        ["chat.submitting"] = "Wird eingereicht…",
        ["chat.submit"] = "Einreichen",

        // Verify encryption
        ["verify.title"] = "Verschlüsselung überprüfen",
        ["verify.intro"] = "AetherLove verschlüsselt diesen Chat Ende-zu-Ende: Nur du und {0} könnt ihn lesen, nicht einmal unser Team. Das gewebte Muster unten wird aus euren beiden Verschlüsselungsschlüsseln erzeugt.",
        ["verify.unavailable"] = "Die Überprüfung ist noch nicht bereit. Sie steht zur Verfügung, sobald ihr beide die Verschlüsselung eingerichtet und die Schlüssel ausgetauscht habt.",
        ["verify.how"] = "Wenn {0} auf dem eigenen Bildschirm genau dasselbe Muster und denselben Code sieht, hört niemand euren Chat mit. Vergleicht sie per Sprachchat oder persönlich. Stimmen sie nicht überein, teile nichts Sensibles mehr und kontaktiere den Support.",
        ["verify.your_key"] = "Dein öffentlicher Schlüssel",
        ["verify.their_key"] = "Öffentlicher Schlüssel von {0}",
        ["verify.keys_explain"] = "Öffentliche Schlüssel können gefahrlos geteilt werden; so erkennen sich eure Apps gegenseitig. Die zugehörigen privaten Schlüssel verlassen niemals eure Geräte, daher kann kein Server (auch unserer nicht) eure Nachrichten lesen.",
        ["verify.back"] = "Zurück zum Chat",

        // ChatListScreen
        ["chat.preview_me_prefix"] = "Ich: ",
        ["chat.matches_title"] = "Matches",
        ["chat.archive_title"] = "Archiviert",
        ["chat.show_search"] = "Suche anzeigen",
        ["chat.hide_search"] = "Suche ausblenden",
        ["chat.search_hint"] = "Name oder Nachricht",
        ["chat.searching"] = "Suche läuft…",
        ["chat.search_estimate"] = "Dies kann {0}-{1} Sekunden dauern, wegen der Anzahl der Unterhaltungen.",
        ["chat.search_rate_limited"] = "Zu viele Unterhaltungen, um sie auf einmal zu durchsuchen. Bitte versuche es in einer Minute erneut.",
        ["chat.search_no_results"] = "Keine Treffer gefunden",
        ["chat.menu_archive"] = "Chat archivieren",
        ["chat.menu_unarchive"] = "Chat aus Archiv holen",
        ["chat.no_archived"] = "Keine archivierten Chats",
        ["chat.all_archived"] = "Alle deine Chats sind archiviert",
        ["chat.loading"] = "Wird geladen…",
        ["chat.matches_load_error"] = "Matches konnten nicht geladen werden: {0}",
        ["chat.connectivity_error"] = "Verbindung zum AetherLove-Server fehlgeschlagen. Versuche es erneut oder schau auf Discord nach dem Serverstatus.",
        ["chat.empty_state"] = "Du hast noch keine Matches — aber das ändert sich bald. Wische weiter!",
        ["chat.new_match"] = "neues Match",
        ["chat.say_hi"] = "Ihr habt gematcht — sag Hallo!",
        ["chat.time_ago_minutes"] = "vor {0} Min.",
        ["chat.time_ago_hours"] = "vor {0} Std.",
        ["chat.time_ago_days"] = "vor {0} T.",
    };
}
