namespace AetherLove.Services.Localization;

internal static class OnboardingDe
{
    public static readonly System.Collections.Generic.Dictionary<string, string> Strings = new()
    {
        // Onboarding
        // Header / navigation
        ["onboarding.header_welcome"] = "Willkommen!",
        ["onboarding.header_how_it_works"] = "So funktioniert's",
        ["onboarding.header_terms_of_service"] = "Nutzungsbedingungen",
        ["onboarding.header_sign_in"] = "Anmelden",
        ["onboarding.header_secure_messages"] = "Sichere deine Nachrichten",
        ["onboarding.header_your_profile"] = "Dein Profil",
        ["onboarding.header_profile_picture"] = "Profilbild",
        ["onboarding.header_your_photos"] = "Deine Fotos",
        ["onboarding.header_optional_details"] = "Optionale Angaben",
        ["onboarding.header_match_preferences"] = "Match-Einstellungen",
        ["onboarding.header_make_it_yours"] = "Mach es zu deinem",
        ["onboarding.header_all_set"] = "Alles bereit!",
        ["onboarding.header_default"] = "AetherLove",

        ["onboarding.back"] = "← Zurück",
        ["onboarding.saving"] = "Wird gespeichert…",
        ["onboarding.start_swiping"] = "Los geht's →",
        ["onboarding.finish"] = "Fertig →",
        ["onboarding.retry"] = "Erneut versuchen →",
        ["onboarding.next"] = "Weiter →",
        ["onboarding.could_not_assemble"] = "{0} konnte nicht zusammengestellt werden: {1}",
        ["onboarding.select_photo"] = "Foto auswählen",
        ["onboarding.image_files"] = "Bilddateien",
        ["onboarding.crop_avatar"] = "Avatar zuschneiden",
        ["onboarding.crop_main_photo"] = "Hauptfoto zuschneiden",
        ["onboarding.crop_extra_photo"] = "Zusatzfoto {0} zuschneiden",

        // Step 2 — How It Works
        ["onboarding.how_intro"] = "So funktioniert AetherLove — vom Erstellen deines Profils bis zum Chatten mit deinem ersten Match.",
        ["onboarding.how1_title"] = "Erstelle dein Profil",
        ["onboarding.how1_body"] = "Erzähl uns von deinem Charakter — deine Rasse, dein Server, deine Sprachen und wonach du suchst. Lade ein Porträtfoto hoch. Das ist deine Visitenkarte.",
        ["onboarding.how2_title"] = "Durchstöbere den Stapel",
        ["onboarding.how2_body"] = "Jedes Mal, wenn du den Stapel öffnest, siehst du eine Reihe Profilkarten. Wische nach rechts (oder tippe ♥), um Interesse zu zeigen. Wische nach links (oder tippe X), um zu passen.",
        ["onboarding.how3_title"] = "Lege deine Einstellungen fest",
        ["onboarding.how3_body"] = "Wähle die Rasse, Region, Sprachen und Interessen, die du dir bei einem Match wünschst. Je genauer du bist, desto besser sind die Matches, die dir angezeigt werden.",
        ["onboarding.how4_title"] = "Match!",
        ["onboarding.how4_body"] = "Wenn zwei Personen sich gegenseitig nach rechts wischen, entsteht ein Match. Du erhältst eine Benachrichtigung und ein privater Chat öffnet sich automatisch.",
        ["onboarding.how5_title"] = "Chatten im Spiel",
        ["onboarding.how5_body"] = "Schreibe Nachrichten direkt über das Plugin — keine externe App nötig. Deine Gespräche sind Ende-zu-Ende-verschlüsselt, sodass nicht einmal die Entwickler von AetherLove deine Chats lesen können.",
        ["onboarding.how6_title"] = "Behalte die Kontrolle",
        ["onboarding.how6_body"] = "Aktualisiere dein Profil, passe deine Einstellungen an oder löse ein Match jederzeit über den Einstellungsbildschirm auf. AetherLove gibt deinen vollständigen Spielernamen, deinen Standort oder deine Kontoinformationen NIEMALS an andere Spieler weiter.",
        ["onboarding.how_ready"] = "Bereit loszulegen? Klicke auf Weiter, um fortzufahren.",

        // Step 2 — Terms of Service
        ["onboarding.tos_p1"] = "AetherLove ist ein soziales Matchmaking-Plugin für Final Fantasy XIV, das für erwachsene Nutzer gedacht ist. Indem du fortfährst, bestätigst du, dass du mindestens 18 Jahre alt bist und der Teilnahme an einer sozialen Plattform für Erwachsene zustimmst.",
        ["onboarding.tos_p2"] = "Mir ist bewusst, dass die Profilinformationen, die ich angebe — einschließlich meines Anzeigenamens, meiner Biografie, meines Heimatservers, meiner Charakterdetails und aller von mir hochgeladenen Fotos — für andere AetherLove-Nutzer sichtbar sein können. Ich bin für die Richtigkeit meines Profils verantwortlich und dafür, dass alle von mir hochgeladenen Fotos angemessen sind und ich das Recht habe, sie zu teilen.",
        ["onboarding.tos_ownership"] = "Die in den von mir hochgeladenen Fotos gezeigten Charaktere müssen meine eigenen sein. Erscheint in einem Bild der Charakter eines anderen Spielers, bestätige ich, dass ich dessen Erlaubnis habe, das Bild zu teilen. Ich werde keine Screenshots oder Posen von Charakteren hochladen, die nicht mir gehören, ohne das Einverständnis des Besitzers.",
        ["onboarding.tos_p3"] = "Ich verpflichte mich, respektvoll mit allen anderen Nutzern umzugehen. Belästigung, unaufgeforderte explizite Inhalte, Hassrede oder jede Form von Missbrauch gegenüber anderen Nutzern sind strengstens untersagt. Ein Verstoß gegen diese Bedingungen kann zur Entfernung von der Plattform ohne Vorankündigung oder Einspruchsmöglichkeit führen.",
        ["onboarding.tos_nsfl"] = "NSFL-Inhalte (\"Not Suitable For Life\") sind auf AetherLove unter keinen Umständen erlaubt. Dazu gehört jedes Bild und jede Nachricht, die echte oder nachgestellte blutige Gewalt, Tod, grafische Gewalt, Verstümmelung, schwere Verletzungen, Tierquälerei oder Selbstverletzung zeigt, sowie alle anderen schockierenden oder abstoßenden Inhalte. Dies ist völlig unabhängig von der NSFW-Freigabe: Eine Kennzeichnung als NSFW macht NSFL-Inhalte niemals zulässig. Wir wenden eine strikte Null-Toleranz-Politik an. Das Veröffentlichen von NSFL-Inhalten führt zu einer sofortigen und dauerhaften Kontosperre, ohne Vorwarnung und ohne Einspruchsmöglichkeit.",
        ["onboarding.tos_p4"] = "Mir ist bewusst, dass AetherLove ein inoffizielles, von der Community erstelltes Plugin ist und weder mit Square Enix Co., Ltd. verbunden noch von dieser unterstützt wird. Es wird ohne Mängelgewähr bereitgestellt, ohne Garantie für Verfügbarkeit, Datensicherheit oder Eignung für einen bestimmten Zweck. Die Entwickler des Plugins sind nicht für die Handlungen anderer Nutzer oder für Folgen verantwortlich, die sich aus der Nutzung dieses Plugins ergeben.",
        ["onboarding.tos_p5"] = "Moderationsentscheidungen — einschließlich Verwarnungen, vorübergehender Sperren und dauerhafter Bann — liegen im alleinigen Ermessen des AetherLove-Teams. Das Team hat in allen Moderationsangelegenheiten das letzte Wort. Entscheidungen müssen dem betroffenen Nutzer weder erklärt noch begründet werden und sind nicht anfechtbar, sofern das Team nicht ausdrücklich etwas anderes angibt.",
        ["onboarding.tos_p6"] = "Wir lieben und mögen Lalafell-Charaktere genauso wie alle anderen, aber Erwachsenen- und NSFW-Funktionen stehen Spielern, deren Charakterrasse Lalafell ist, nicht zur Verfügung. Da Lalafell ein kindliches Aussehen haben, treffen wir keine Einzelfallentscheidung und wenden diese Richtlinie einheitlich auf jedes Lalafell-Konto an. Die Option für 18+-Rollenspiel, die NSFW-Aktivierung und das Hochladen von NSFW-Fotos sind allesamt deaktiviert, solange deine Rasse auf Lalafell eingestellt ist. Der Versuch, diese Einschränkung zu umgehen, ist ein Grund für die Entfernung des Kontos.",
        ["onboarding.tos_ai"] = "KI-gestützte Moderation — Ich stimme zu, dass mein Profiltext und meine Profilbilder automatisch mithilfe der Moderations-APIs von OpenAI überprüft werden, um Inhalte zu erkennen, die gegen diese Regeln verstoßen, und um AetherLove für alle sicher zu halten. Ich stimme außerdem zu, dass meine Profilbilder von einem zusätzlichen OpenAI-Modell bewertet werden — sowohl daraufhin, ob sie den Bildregeln von AetherLove entsprechen (also meinen eigenen Final Fantasy XIV-Charakter zeigen und keine Fan-Art, KI-generierten Bilder oder themenfremden Inhalte sind), als auch daraufhin, ob sie SFW oder NSFW sind. Mein Profiltext und meine Bilder werden ausschließlich zur Moderation an OpenAI übermittelt und niemals zum Training der Modelle von OpenAI verwendet. Mir ist bewusst, dass jede endgültige Moderationsentscheidung von den menschlichen Mitarbeitern von AetherLove getroffen wird — eine KI allein ist niemals für eine Moderationsmaßnahme verantwortlich.",
        ["onboarding.tos_p7"] = "Mir ist bewusst, dass diese Bedingungen jederzeit aktualisiert werden können. Die fortgesetzte Nutzung von AetherLove nach einer Aktualisierung gilt als Zustimmung zu den überarbeiteten Bedingungen.",
        ["onboarding.tos_read_carefully"] = "SORGFÄLTIG LESEN",
        ["onboarding.tos_accepted"] = "Bedingungen akzeptiert — drücke Weiter, um fortzufahren.",
        ["onboarding.tos_timer"] = "Bitte lies sorgfältig — Zustimmungsschaltfläche verfügbar in {0}s",
        ["onboarding.tos_scroll_bottom"] = "Scrolle nach unten, um zu akzeptieren.",
        ["onboarding.tos_i_agree"] = "Ich stimme zu",

        // Step 3 — XIVAuth
        ["onboarding.auth_signin_with_xivauth"] = "Mit XIVAuth anmelden",
        ["onboarding.auth_intro"] = "AetherLove nutzt XIVAuth, um deine Identität als aktiver Final Fantasy XIV-Spieler zu bestätigen. Es ist kein Passwort erforderlich — die Authentifizierung erfolgt sicher über deinen Spielclient.",
        ["onboarding.auth_contacting"] = "AetherLove wird kontaktiert",
        ["onboarding.auth_dont_have_xivauth"] = "Kein XIVAuth?",
        ["onboarding.auth_xivauth_explainer"] = "XIVAuth ist ein kostenloses, von der Community betriebenes Single Sign-On für Final Fantasy XIV-Tools. Es bestätigt, dass du ein echter FFXIV-Spieler bist, indem es deinen Lodestone-Charakter verknüpft — ohne jemals dein Square Enix-Passwort weiterzugeben. Die Registrierung dauert nur eine Minute.",
        ["onboarding.auth_create_account"] = "Ein XIVAuth-Konto erstellen",
        ["onboarding.auth_complete_in_browser"] = "Schließe die Anmeldung in deinem Browser ab",
        ["onboarding.auth_browser_opened"] = "Ein Browserfenster wurde geöffnet. Schließe die Anmeldung mit XIVAuth ab und kehre hierher zurück — dieser Schritt wird automatisch fortgesetzt.",
        ["onboarding.auth_open_browser_again"] = "Browser erneut öffnen",
        ["onboarding.auth_cancel"] = "Abbrechen",
        ["onboarding.auth_loading_profile"] = "Angemeldet! Dein Profil wird geladen",
        ["onboarding.auth_signed_in"] = "Angemeldet!",
        ["onboarding.auth_welcome_back"] = "Willkommen zurück!",
        ["onboarding.auth_welcome_back_named"] = "Willkommen zurück, {0}!",
        ["onboarding.auth_details_loaded"] = "Wir haben deine Daten geladen — du kannst sofort loslegen.",
        ["onboarding.auth_timeout"] = "Die Anmeldung hat zu lange gedauert. Bitte versuche es erneut.",
        ["onboarding.auth_failed"] = "Anmeldung fehlgeschlagen.",
        ["onboarding.auth_try_again"] = "Erneut versuchen",

        // Step 3a — Passphrase
        ["onboarding.pass_heading"] = "Sichere deine Nachrichten",
        ["onboarding.pass_intro"] = "Das AetherLove-Team kann deine privaten Nachrichten nicht lesen — weder jetzt noch jemals. Um das möglich zu machen, verschlüsseln wir jede Nachricht mit einem Schlüssel, den nur DU kennst. Lege unten eine Passphrase fest. Eine Passphrase ist wie ein Passwort, nur eines, das du dir merken und speichern musst — es gibt keine \"Passphrase vergessen\"-Schaltfläche. Schreib sie auf, speichere sie in einem Passwortmanager, tu alles, was du auch für ein kritisches Passwort tun würdest.",
        ["onboarding.pass_warning"] = "Wenn du AetherLove auf einem anderen Computer nutzt — oder dir einen neuen Computer kaufst — musst du diese Passphrase erneut eingeben, um deine Chats lesen zu können. Ohne sie sind deine Nachrichten selbst für dich unlesbar.",
        ["onboarding.pass_label"] = "Passphrase",
        ["onboarding.pass_confirm_label"] = "Passphrase bestätigen",
        ["onboarding.pass_err_empty"] = "Bitte gib eine Passphrase ein.",
        ["onboarding.pass_err_too_short"] = "Die Passphrase muss mindestens {0} Zeichen lang sein.",
        ["onboarding.pass_err_confirm_empty"] = "Bitte bestätige deine Passphrase.",
        ["onboarding.pass_err_mismatch"] = "Die Passphrasen stimmen nicht überein.",
        ["onboarding.pass_ack"] = "Mir ist bewusst, dass mein Chatverlauf nicht wiederhergestellt werden kann, wenn ich diese Passphrase vergesse.",
        ["onboarding.pass_securing"] = "Deine Schlüssel werden gesichert…",
        ["onboarding.pass_strength_too_weak"] = "Zu schwach",
        ["onboarding.pass_strength_weak"] = "Schwach",
        ["onboarding.pass_strength_ok"] = "Okay",
        ["onboarding.pass_strength_good"] = "Gut",
        ["onboarding.pass_strength_strong"] = "Stark",

        // Step 4 — Profile (data labels)
        ["onboarding.region_na"] = "Nordamerika (NA)",
        ["onboarding.region_eu"] = "Europa (EU)",
        ["onboarding.region_oceania"] = "Ozeanien",
        ["onboarding.region_japan"] = "Japan",
        ["onboarding.race_hyur"] = "Hyur",
        ["onboarding.race_elezen"] = "Elezen",
        ["onboarding.race_lalafell"] = "Lalafell",
        ["onboarding.race_miqote"] = "Miqo'te",
        ["onboarding.race_roegadyn"] = "Roegadyn",
        ["onboarding.race_au_ra"] = "Au Ra",
        ["onboarding.race_hrothgar"] = "Hrothgar",
        ["onboarding.race_viera"] = "Viera",
        ["onboarding.gender_male"] = "Männlich",
        ["onboarding.gender_female"] = "Weiblich",
        ["onboarding.gender_other"] = "Divers",
        ["onboarding.content_housing"] = "Häuser & Dekoration",
        ["onboarding.content_music_bard"] = "Musik & Barden-Auftritte",
        ["onboarding.content_rp_venues"] = "Besuch von Rollenspiel-Locations",
        ["onboarding.content_club_venues"] = "Besuch von Club-Locations",
        ["onboarding.content_gpose"] = "Gpose",
        ["onboarding.content_story_lore"] = "Story & Lore",
        ["onboarding.content_roulettes"] = "Zufallsinhalte",
        ["onboarding.content_regular"] = "Reguläre Inhalte",
        ["onboarding.content_extreme_trials"] = "Extreme Prüfungen",
        ["onboarding.content_savage"] = "Episch-Raids",
        ["onboarding.content_pvp"] = "PvP",
        ["onboarding.content_blue_mage"] = "Blaumagier",
        ["onboarding.content_triple_triad"] = "Triple Triad",
        ["onboarding.content_mahjong"] = "Mahjong",
        ["onboarding.content_treasure_hunts"] = "Schatzsuche",
        ["onboarding.content_crafting_gathering"] = "Handwerk & Sammeln",
        ["onboarding.content_fishing"] = "Angeln",
        ["onboarding.content_achievement_hunting"]= "Erfolge sammeln",
        ["onboarding.lf_chatting"] = "Mit neuen Leuten plaudern",
        ["onboarding.lf_casual_buddies"] = "Lockere Spielpartner",
        ["onboarding.lf_gpose_glamour"] = "GPose- und Glamour-Partner",
        ["onboarding.lf_romance"] = "Eine Romanze im Spiel",
        ["onboarding.lf_long_term"] = "Eine langfristige Beziehung im Spiel",
        ["onboarding.lf_rp_partners"] = "Rollenspiel-Partner",
        ["onboarding.lf_erp"] = "18+-Rollenspiel (ERP)",

        // Step 4 — Profile (body)
        ["onboarding.profile_intro"] = "Diese Felder erscheinen auf deiner öffentlichen Profilkarte und werden verwendet, um Matches vorzuschlagen.",
        ["onboarding.profile_identity"] = "Identität",
        ["onboarding.profile_display_name"] = "Anzeigename",
        ["onboarding.profile_display_name_tip"] = "Der Name, den andere Nutzer sehen. Nutze deinen Vornamen oder einen Alias.\nKeine Leerzeichen erlaubt.",
        ["onboarding.profile_display_name_hint"] = "Vorname oder Alias, keine Leerzeichen, mindestens 3 Zeichen.",
        ["onboarding.profile_about_me"] = "Über mich",
        ["onboarding.profile_about_me_tip"] = "Schreibe eine kurze Vorstellung. Was macht dir Spaß?\nWelche Art von Kontakten suchst du?",
        ["onboarding.profile_char_count"] = "{0} / 500 Zeichen",
        ["onboarding.profile_preview"] = "Vorschau",
        ["onboarding.profile_bio_placeholder"] = "Deine Biografie erscheint hier…",
        ["onboarding.profile_location"] = "Standort",
        ["onboarding.profile_server_region"] = "Server-Region",
        ["onboarding.profile_server_region_tip"] = "Wähle deine Final Fantasy XIV-Region.\nDas hilft, dich mit Spielern in deiner Nähe zu matchen.",
        ["onboarding.profile_character"] = "Charakter",
        ["onboarding.profile_race"] = "Rasse",
        ["onboarding.profile_gender"] = "Geschlecht",
        ["onboarding.profile_languages_speak"] = "Sprachen, die ich spreche",
        ["onboarding.profile_languages_hint"] = "Wähle jede Sprache, in der du dich beim Chatten wohlfühlst.",
        ["onboarding.profile_content_heading"] = "Folgende Inhalte machen mir Spaß",
        ["onboarding.profile_content_hint"] = "Wähle alles aus, was zutrifft — das erscheint auf deiner Profilkarte.",
        ["onboarding.profile_looking_for_heading"]= "Ich suche nach",
        ["onboarding.profile_looking_for_hint"] = "Wähle alles aus, was zutrifft (mindestens eines ist erforderlich). Ehrlichkeit hilft, bessere Matches zu finden.",
        ["onboarding.profile_erp_enables_nsfw"] = "    Wenn du dies auswählst, wird NSFW für dein Profil automatisch aktiviert.",
        ["onboarding.profile_nsfw_heading"] = "NSFW",
        ["onboarding.profile_nsfw_lalafell"] = "Erwachsenen- und NSFW-Funktionen stehen nicht zur Verfügung, solange deine Rasse auf Lalafell eingestellt ist. Details findest du in den Nutzungsbedingungen.",
        ["onboarding.profile_nsfw_explainer"] = "NSFW steht für \"Not Safe For Work\" — Inhalte mit Nacktheit oder sexuellen Themen. Möchtest du dich für NSFW-Profile anmelden? Das führt zu potenziellen Matches mit Spielern, die NSFW-Bilder zu ihrem Profil hochgeladen haben. Diese Bilder sind immer unkenntlich gemacht, bis du sie aufdeckst.",
        ["onboarding.profile_nsfw_checkbox"] = "NSFW-Profile: JA",
        ["onboarding.profile_nsfw_locked"] = "Aktiviert, weil du 18+-Rollenspiel (ERP) ausgewählt hast. Deaktiviere das, um diese Einstellung zu ändern.",
        ["onboarding.profile_timezone"] = "Zeitzone",
        ["onboarding.profile_timezone_hint"] = "Wird potenziellen Matches angezeigt, damit sie wissen, wann du aktiv bist.",

        // Step 5 — Avatar
        ["onboarding.avatar_heading"] = "Dein Profilbild",
        ["onboarding.avatar_intro"] = "Dein Profilbild wird im Chat und beim Matching angezeigt. Wir benötigen ein quadratisches Bild, das das Gesicht deines FFXIV-Charakters zeigt.",
        ["onboarding.avatar_tip"] = "Tipp: Ein Nahaufnahme-Porträt per G-Pose-Screenshot eignet sich am besten.",
        ["onboarding.avatar_sfw_warning"] = "Dein Hauptprofilbild MUSS SFW sein. Das Hochladen eines NSFW-Bildes ist ein Grund für die Löschung des Kontos.",
        ["onboarding.avatar_browse"] = "Durchsuchen…",
        ["onboarding.avatar_crop_hint"] = "Der Zuschnitt-Editor wurde in einem separaten Fenster geöffnet.\nKlicke dort auf \"Diesen Zuschnitt verwenden\", um deinen Avatar zu bestätigen.",
        ["onboarding.avatar_no_image"] = "Noch kein Bild ausgewählt.",
        ["onboarding.avatar_set"] = "Profilbild festgelegt!",
        ["onboarding.avatar_change_photo"] = "Foto ändern",
        ["onboarding.avatar_its_a_match"] = "Es ist ein Match!",
        ["onboarding.avatar_match_preview_caption"] = "Vorschau: So erscheint dein Avatar auf Match-Karten",

        // Step 5 — Image Disclaimer
        ["onboarding.disclaimer_intro"] = "AetherLove ist für Final Fantasy XIV-Spieler gemacht. Bitte lies die folgenden Richtlinien sorgfältig, bevor du Bilder hochlädst.",
        ["onboarding.disclaimer_moderation"] = "Alle Uploads unterliegen sowohl automatischer als auch manueller Moderation.",
        ["onboarding.disclaimer_general_heading"] = "Allgemeines",
        ["onboarding.disclaimer_general_body"] = "Alle bei AetherLove hochgeladenen Bilder müssen deinen Final Fantasy XIV-Charakter zeigen. Bilder, die nichts mit Final Fantasy XIV-Charakteren zu tun haben, werden ohne Vorankündigung abgelehnt.",
        ["onboarding.disclaimer_profile_images_heading"] = "Profilbilder",
        ["onboarding.disclaimer_profile_images_body"] = "Auf deinem Profil angezeigte Bilder müssen Screenshots oder G-Poses deines eigenen Final Fantasy XIV-Charakters sein. Folgendes ist:",
        ["onboarding.disclaimer_not_allowed"] = "NICHT ERLAUBT:",
        ["onboarding.disclaimer_na_fan_art"] = "Fan-Art",
        ["onboarding.disclaimer_na_3d_renders"] = "Eigene 3D-Renderings",
        ["onboarding.disclaimer_na_ai"] = "KI-generierte Bilder",
        ["onboarding.disclaimer_na_real_photos"] = "Fotos von echten Personen oder Orten",
        ["onboarding.disclaimer_na_unrelated"] = "Jedes Bild, das nichts mit deinem FFXIV-Charakter zu tun hat",
        ["onboarding.disclaimer_profile_images_consent"] = "Lade nur Bilder deines eigenen Charakters hoch. Wenn der Charakter eines anderen Spielers auf einem Bild zu sehen ist, hol dir vorher seine Erlaubnis. Bitte lade keine Screenshots oder Posen des Charakters einer anderen Person ohne deren Einverständnis hoch.",
        ["onboarding.disclaimer_nsfw_heading"] = "NSFW-Inhalte",
        ["onboarding.disclaimer_nsfw_body1"] = "Dein primärer Avatar und dein Hauptprofilbild müssen Safe For Work (SFW) sein. Eine einfache Faustregel: Wenn es dir nichts ausmachen würde, das Bild einem Vorgesetzten oder Kollegen zu zeigen, ist es als primäres Bild akzeptabel.",
        ["onboarding.disclaimer_nsfw_body2"] = "Zusätzliche Profilfotos dürfen NSFW-Inhalte enthalten, müssen aber beim Hochladen ausdrücklich als solche gekennzeichnet werden. Wir empfehlen dringend, so viele Bilder wie möglich SFW zu halten.",
        ["onboarding.disclaimer_nsfl_heading"] = "NSFL-Inhalte: Niemals erlaubt",
        ["onboarding.disclaimer_nsfl_body"] = "NSFL-Inhalte (\"Not Suitable For Life\") sind in keinem Bild erlaubt, unabhängig davon, ob es als SFW oder NSFW gekennzeichnet ist. Das umfasst jede Darstellung von echter oder nachgestellter blutiger Gewalt, Tod, grafischer Gewalt, Verstümmelung, schweren Verletzungen, Tierquälerei oder Selbstverletzung sowie alles andere, das schockieren, verstören oder anwidern soll. Dies ist völlig unabhängig von den NSFW-Regeln oben: Eine NSFW-Kennzeichnung erlaubt anzügliche Inhalte, niemals NSFL-Inhalte.",
        ["onboarding.disclaimer_nsfl_zero_tolerance"] = "Null Toleranz: Das Hochladen von NSFL-Inhalten führt zu einer sofortigen und dauerhaften Kontosperre, ohne Vorwarnung und ohne Einspruch.",
        ["onboarding.disclaimer_ai_heading"] = "KI-gestützte Moderation",
        ["onboarding.disclaimer_ai_body"] = "Jedes Bild, das du hochlädst, wird automatisch mithilfe der Moderations-APIs von OpenAI überprüft und von einem zusätzlichen OpenAI-Modell bewertet — sowohl daraufhin, ob es den oben genannten Bildregeln entspricht (also deinen eigenen FFXIV-Charakter zeigt und keine Fan-Art, kein KI-generiertes Bild und nichts Themenfremdes ist), als auch daraufhin, ob es SFW oder NSFW ist. Deine Bilder werden ausschließlich zur Moderation an OpenAI übermittelt und niemals zum Training der Modelle von OpenAI verwendet. Jede endgültige Moderationsentscheidung wird von den menschlichen Mitarbeitern von AetherLove getroffen — eine KI allein ist niemals für eine Moderationsmaßnahme verantwortlich.",
        ["onboarding.disclaimer_rules_heading"] = "Was passiert, wenn ein Bild gegen die Regeln verstößt?",
        ["onboarding.disclaimer_rules_body1"] = "Wenn festgestellt wird, dass eines deiner Bilder gegen diese Richtlinien verstößt, erhältst du eine Benachrichtigung. Das Bild wird automatisch entfernt und dein Profil wird vorübergehend gesperrt — shadowbanned — bis du das Problem behebst.",
        ["onboarding.disclaimer_rules_body2"] = "Das Hochladen von Inhalten, die schädlich, ausbeuterisch oder illegal sind, führt zu:",
        ["onboarding.disclaimer_permanent_ban"] = "Einer dauerhaften Kontosperre.",
        ["onboarding.disclaimer_continue"] = "Ich verstehe, weiter",

        // Step 6 — Photos
        ["onboarding.photos_heading"] = "Profilfotos",
        ["onboarding.photos_intro"] = "Füge deinem Profil Porträtfotos hinzu (Seitenverhältnis 10:16). Der erste Platz ist erforderlich; die Plätze 2–4 sind optional. Für beste Ergebnisse verwende Bilder mit mindestens 480 × 768 px.",
        ["onboarding.photos_main_thumb"] = "Haupt",
        ["onboarding.photos_tap_slot"] = "Tippe oben auf einen Platz, um ein Foto hinzuzufügen oder zu verwalten.",
        ["onboarding.photos_main_photo"] = "Hauptfoto",
        ["onboarding.photos_extra_photo"] = "Zusatzfoto {0}",
        ["onboarding.photos_main_sfw_warning"] = "Dein Hauptprofilbild MUSS SFW sein. Das Hochladen eines NSFW-Bildes ist ein Grund für die Sperrung oder Löschung des Kontos.",
        ["onboarding.photos_sfw_nsfw_question"] = "Ist dieses Bild SFW oder NSFW?",
        ["onboarding.photos_mismatch_warning"] = "Wenn unser System feststellt, dass du NSFW hochgeladen hast, während SFW ausgewählt ist, wird dein Foto zur Moderation zurückgehalten und du riskierst eine Kontosperrung.",
        ["onboarding.photos_previously_uploaded"] = "Zuvor hochgeladen.",
        ["onboarding.photos_confirmed"] = "Foto bestätigt.",
        ["onboarding.photos_remove"] = "Entfernen",
        ["onboarding.photos_browse"] = "Durchsuchen…",
        ["onboarding.photos_crop_hint"] = "Der Zuschnitt-Editor wurde in einem separaten Fenster geöffnet.\nKlicke dort auf \"Diesen Zuschnitt verwenden\", um das Foto zu bestätigen.",
        ["onboarding.photos_required"] = "Dieses Foto ist erforderlich.",
        ["onboarding.photos_optional"] = "Dieses Foto ist optional.",

        // Step 7 — Optional
        ["onboarding.expansion_none"] = "(Keine)",
        ["onboarding.opt_heading"] = "Erzähl uns mehr über dich",
        ["onboarding.opt_intro"] = "Alle Felder auf dieser Seite sind optional. Fülle so viel oder so wenig aus, wie du möchtest — diese Angaben erscheinen auf deiner Profilkarte und helfen anderen, dich zu finden.",
        ["onboarding.opt_fav_job"] = "Lieblingsjob",
        ["onboarding.opt_fav_job_tip"] = "Der Job oder die Rolle, die dir am meisten Spaß macht.\nTippe zum Filtern.",
        ["onboarding.opt_fav_location"] = "Lieblingsort",
        ["onboarding.opt_fav_location_tip"] = "Ein Ort in Eorzea, den du gern besuchst.\nTippe zum Filtern.",
        ["onboarding.opt_location_unavailable"] = "(Standortdaten nicht verfügbar)",
        ["onboarding.opt_location_none"] = "(Keiner)",
        ["onboarding.opt_fav_expansion"] = "Lieblingserweiterung",
        ["onboarding.opt_fav_expansion_tip"] = "Deine absolute Lieblings-FFXIV-Erweiterung.",
        ["onboarding.opt_music_heading"] = "Lieblingslied",
        ["onboarding.opt_music_tip"] = "Füge einen Link von Spotify, SoundCloud, Apple Music oder YouTube Music ein.",
        ["onboarding.opt_fav_spotify"] = "Spotify",
        ["onboarding.opt_fav_spotify_tip"] = "Füge eine Spotify-Track-URL oder Track-ID ein.\nDer Titelname wird automatisch abgerufen.",
        ["onboarding.opt_fav_soundcloud"] = "SoundCloud",
        ["onboarding.opt_fav_apple"] = "Apple Music",
        ["onboarding.opt_fav_youtube"] = "YouTube Music",
        ["onboarding.opt_fav_movie"] = "Lieblingsfilm",
        ["onboarding.opt_fav_movie_tip"] = "Dein absoluter Lieblingsfilm — jedes Genre.",
        ["onboarding.opt_fav_anime"] = "Lieblings-Anime",
        ["onboarding.opt_fav_anime_tip"] = "Deine Lieblings-Anime-Serie oder dein Lieblings-Anime-Film.",
        ["onboarding.opt_fav_ff_character"] = "Lieblings-Final-Fantasy-Charakter",
        ["onboarding.opt_fav_ff_character_tip"] = "Ein beliebiger Charakter aus dem Final Fantasy-Universum.",
        ["onboarding.opt_weekday_playtimes"] = "Spielzeiten unter der Woche (Mo–Fr)",
        ["onboarding.opt_weekday_playtimes_tip"] = "Klicke die Stunden an, zu denen du unter der Woche normalerweise online bist.\nFahre über einen Balken, um die Uhrzeit zu sehen.\nBitte wähle deine Ortszeit.",
        ["onboarding.opt_weekend_playtimes"] = "Spielzeiten am Wochenende (Sa–So)",
        ["onboarding.opt_weekend_playtimes_tip"] = "Klicke die Stunden an, zu denen du am Wochenende normalerweise online bist.\nFahre über einen Balken, um die Uhrzeit zu sehen.\nBitte wähle deine Ortszeit.",
        ["onboarding.opt_sync_tool"] = "Verwendetes Sync-Tool",
        ["onboarding.opt_sync_tool_tip"] = "Sync-Tools wie Lightless oder Honsefarm ermöglichen es gematchten Nutzern,\nMod-Erscheinungsbilder automatisch zu teilen.",
        ["onboarding.time_am"] = "AM",
        ["onboarding.time_pm"] = "PM",

        // Step 8 — Filters
        ["onboarding.filters_intro"] = "Sag uns, mit wem du dich matchen möchtest. Diese Einstellungen helfen uns, die richtigen Leute für dich anzuzeigen — du kannst sie jederzeit in den Einstellungen anpassen.",
        ["onboarding.filters_heading"] = "Ich möchte matchen mit",
        ["onboarding.filters_race"] = "Rasse",
        ["onboarding.filters_gender"] = "Geschlecht",
        ["onboarding.filters_region"] = "Region",
        ["onboarding.filters_spoken_language"] = "Gesprochene Sprache",
        ["onboarding.filters_language_tip"] = "Lass alles deaktiviert, um unabhängig von der gesprochenen Sprache zu matchen.",
        ["onboarding.filters_all"] = "Alle",
        ["onboarding.filters_none"] = "Keine",
        ["onboarding.filters_clear"] = "Zurücksetzen",
        ["onboarding.filters_any_race"] = "  Keine Auswahl — beliebige Rasse",
        ["onboarding.filters_any_gender"] = "  Keine Auswahl — beliebiges Geschlecht",
        ["onboarding.filters_any_region"] = "  Keine Auswahl — beliebige Region",
        ["onboarding.filters_any_language"] = "  Keine Auswahl — keine Sprachpräferenz",

        // Step 9 — Finished
        ["onboarding.finished_heading"] = "Alles bereit!",
        ["onboarding.finished_intro"] = "Dein Profil wurde erstellt und deine Match-Einstellungen wurden gespeichert. Du bist bereit, mit anderen Final Fantasy XIV-Spielern in Kontakt zu treten.",
        ["onboarding.finished_verification_heading"] = "Profilüberprüfung",
        ["onboarding.finished_verification_body"] = "Dein Profil wird innerhalb von 24 Stunden von unserem Moderationsteam überprüft. Während dieser Zeit ist dein Profil voll aktiv — du kannst sofort stöbern, matchen und chatten.",
        ["onboarding.finished_verification_note"] = "Wir melden uns nur, wenn es ein Problem mit deinem Profil oder deinen Bildern gibt.",
        ["onboarding.finished_swiping_heading"] = "Los geht's",
        ["onboarding.finished_swiping_body"] = "Geh zum Stapel, um Profile zu durchstöbern. Tippe auf ♥ bei jemandem, der dich interessiert — wenn er ebenfalls ♥ tippt, ist es ein Match! Ein privater Chat öffnet sich automatisch.",
        ["onboarding.finished_rejected_heading"] = "Falls ein Bild abgelehnt wird",
        ["onboarding.finished_rejected_body"] = "Falls eines deiner Bilder bei der Überprüfung gegen unsere Richtlinien verstößt, erhältst du eine Benachrichtigung. Das Bild wird entfernt und du wirst gebeten, es zu ersetzen. Dein Profil bleibt in der Zwischenzeit aktiv.",
        ["onboarding.finished_good_luck"] = "Viel Glück da draußen — AetherLove drückt dir die Daumen! ♥",

        // Step 10 — Preferences
        ["onboarding.prefs_intro"] = "Mach AetherLove zu deinem — wähle ein Farbschema und eine Telefongröße. Du kannst beides jederzeit in den Einstellungen ändern.",
        ["onboarding.prefs_theme"] = "Design",
        ["onboarding.prefs_phone_size"] = "Telefongröße",

        // added after update (1.3.1)
        ["onboarding.content_ultimate_raiding"] = "Fatale Raids",
        ["onboarding.content_deep_dungeons"] = "Tiefe Gewölbe",
        ["onboarding.content_variant_criterion"] = "Varianten-/Kriterium-Dungeons",
        ["onboarding.content_field_operations"] = "Feldoperationen (Bozja, Eureka)",
        ["onboarding.race_gender_warning"] = "Bitte wähle die Rasse und das Geschlecht deines FFXIV-Charakters, nicht dein Geschlecht im echten Leben!",
        ["onboarding.tos_race_gender"] = "Ich stimme zu, bei der Einrichtung die richtige Rasse und das richtige Geschlecht für meinen Final-Fantasy-XIV-Charakter zu wählen, und mir ist bewusst, dass mein Hauptprofilbild diesen Charakter widerspiegeln muss.",
    };
}
