namespace AetherLove.Services.Localization;

internal static class PlacesEs
{
    public static readonly System.Collections.Generic.Dictionary<string, string> Strings = new()
    {
        // added after update 1.5.0
        ["places.title"] = "Lugares",
        ["places.load_failed"] = "No se pudieron cargar los Lugares: {0}",
        ["places.happening_now"] = "Abierto ahora",
        ["places.this_week"] = "Esta semana",
        ["places.nothing_upcoming"] = "No hay aperturas próximas esta semana.",
        ["places.empty"] = "Ningún local coincide con tus filtros.",
        ["places.empty_hint"] = "Prueba a ampliar tus filtros de Lugares.",
        ["places.today"] = "Hoy",
        ["places.tomorrow"] = "Mañana",
        ["places.live"] = "EN VIVO",
        ["places.ends_in"] = "Termina en {0}",
        ["places.going"] = "{0} asistirán",
        ["places.back"] = "Volver",

        ["places.filters_title"] = "Filtros de Lugares",
        ["places.filters_tags"] = "Mostrar locales con etiqueta",
        ["places.filters_regions"] = "Regiones",
        ["places.filters_hint"] = "Si no seleccionas nada, se muestra todo. Estos filtros son independientes de tus preferencias de emparejamiento.",
        ["places.filters_apply"] = "Aplicar",

        ["places.tag_rp_venue"] = "Local de rol",
        ["places.tag_barding"] = "Música de bardo",
        ["places.tag_nsfw"] = "Local +18",
        ["places.tag_live_dj"] = "DJs en vivo",
        ["places.tag_sync"] = "Sync activado",
        ["places.tag_nightclub"] = "Discoteca",
        ["places.tag_bar_tavern"] = "Bar / Taberna",
        ["places.tag_cafe"] = "Cafetería",
        ["places.tag_restaurant"] = "Restaurante",
        ["places.tag_casino"] = "Casino",
        ["places.tag_maid_cafe"] = "Maid café",
        ["places.tag_bathhouse"] = "Casa de baños",
        ["places.tag_gpose_studio"] = "Estudio de gpose",
        ["places.tag_live_music"] = "Música en vivo",
        ["places.tag_market"] = "Mercado / Tienda",

        ["places.day_mon"] = "Lun",
        ["places.day_tue"] = "Mar",
        ["places.day_wed"] = "Mié",
        ["places.day_thu"] = "Jue",
        ["places.day_fri"] = "Vie",
        ["places.day_sat"] = "Sáb",
        ["places.day_sun"] = "Dom",

        ["places.location_ward"] = "Distrito {0}",
        ["places.location_plot"] = "Parcela {0}",
        ["places.location_room"] = "Habitación {0}",

        ["places.schedule"] = "Horarios de apertura",
        ["places.rsvp"] = "Apuntarme",
        ["places.rsvp_going"] = "Voy ✓",

        ["places.reviews_title"] = "Reseñas",
        ["places.no_reviews"] = "Aún no hay reseñas, ¡sé la primera persona!",
        ["places.no_rating_yet"] = "Aún no hay valoraciones.",
        ["places.rating_summary"] = "{0} · {1} reseñas",
        ["places.write_review"] = "Escribir una reseña",
        ["places.your_review"] = "Tu reseña",
        ["places.review_pending"] = "Tu reseña está pendiente de moderación y solo tú puedes verla.",
        ["places.review_submit"] = "Publicar reseña",
        ["places.review_update"] = "Actualizar reseña",
        ["places.review_delete"] = "Eliminar",
        ["places.review_delete_title"] = "¿Eliminar la reseña?",
        ["places.review_delete_body"] = "Tu valoración y tu texto se eliminarán permanentemente.",
        ["places.reviews_more"] = "Cargar más reseñas",

        ["places.menu_my_venues"] = "Mis locales",
        ["places.my_venues"] = "Mis locales",
        ["places.my_venues_empty"] = "Aún no has creado ningún local. ¡Crea uno para aparecer en Lugares!",
        ["places.venue_saved"] = "Local guardado.",
        ["places.new_venue"] = "+ Nuevo local",
        ["places.venue_cap"] = "Has alcanzado el límite de {0} locales.",
        ["places.venue_stats"] = "{0} me gusta · {1} reseñas",
        ["places.venue_unlisted"] = "Oculto por moderación",
        ["places.back_to_venues"] = "Volver",
        ["places.new_venue_title"] = "Nuevo local",
        ["places.edit_venue_title"] = "Editar local",

        ["places.section_details"] = "Detalles",
        ["places.venue_name"] = "Nombre del local",
        ["places.venue_description"] = "Descripción",
        ["places.section_tags"] = "Etiquetas",
        ["places.section_location"] = "Ubicación",
        ["places.use_current_location"] = "Usar mi ubicación actual",
        ["places.use_current_location_hint"] = "Colócate dentro de tu local para rellenarlo todo automáticamente.",
        ["places.venue_datacenter"] = "Centro de datos",
        ["places.venue_world"] = "Mundo",
        ["places.venue_ward"] = "Distrito",
        ["places.venue_plot"] = "Parcela",
        ["places.venue_room"] = "Habitación",
        ["places.venue_room_hint"] = "Para apartamentos, pon la parcela en 0 e introduce el número de habitación.",
        ["places.venue_timezone"] = "Zona horaria del local",
        ["places.venue_timezone_tip"] = "Los horarios de abajo se introducen en esta zona horaria. Los visitantes siempre los ven convertidos a su hora local.",

        ["places.section_hours"] = "Horarios de apertura",
        ["places.hours_explainer"] = "Elige los días y luego haz clic en una hora de inicio y otra de fin: las horas intermedias se rellenan solas, incluso pasada la medianoche.",
        ["places.add_opening_time"] = "+ Añadir horario",
        ["places.rule_weekly"] = "Semanal",
        ["places.rule_one_time"] = "Único",
        ["places.rule_date_hint"] = "Fecha (AAAA-MM-DD)",
        ["places.rule_span"] = "Abierto {0}",
        ["places.hours_pick_start"] = "Haz clic para fijar el inicio",
        ["places.hours_pick_end"] = "Haz clic para fijar el fin",

        ["places.section_images"] = "Imágenes",
        ["places.image_banner"] = "Banner",
        ["places.image_logo"] = "Imagen del local",
        ["places.image_banner_hint"] = "Banner ancho (25:9). Se muestra en la página de tu local.",
        ["places.image_logo_hint"] = "Cuadrada (1:1). Se muestra en las tarjetas del local.",
        ["places.image_pick"] = "Elegir imagen",
        ["places.image_ready"] = "Lista para guardar",
        ["places.image_remove"] = "Quitar",
        ["places.crop_banner"] = "Recortar banner",
        ["places.crop_logo"] = "Recortar imagen del local",

        ["places.err_name"] = "Ponle un nombre a tu local (mínimo 3 caracteres).",
        ["places.err_location"] = "Rellena el centro de datos y el mundo.",
        ["places.err_plot_or_room"] = "Indica un número de parcela o de habitación.",
        ["places.err_date"] = "Las aperturas únicas necesitan una fecha en formato AAAA-MM-DD.",
        ["places.err_days"] = "Las aperturas semanales necesitan al menos un día seleccionado.",
        ["places.save_venue"] = "Guardar local",
        ["places.delete_venue"] = "Eliminar local",
        ["places.delete_venue_title"] = "¿Eliminar el local?",
        ["places.delete_venue_body"] = "\"{0}\" y todos sus me gusta, reseñas y asistencias se eliminarán permanentemente.",

        // added after update 1.5.1
        ["places.venue_region"] = "Región",
        ["places.venue_district"] = "Distrito",
        ["places.venue_dc_select"] = "Elige un centro de datos",
        ["places.venue_world_select"] = "Elige un mundo",
        ["places.venue_tz_select"] = "Elige una zona horaria",
        ["places.venue_tz_search"] = "Buscar…",
        ["places.err_description"] = "Añade una descripción.",
        ["places.err_tags"] = "Elige al menos una etiqueta.",
        ["places.err_images"] = "Se requieren un banner y un logo.",
        ["places.err_timezone"] = "Elige una zona horaria.",
        ["places.err_hours"] = "Añade al menos un horario de apertura.",
        ["places.section_rsvpd"] = "Tus confirmaciones",
        ["places.duration_hm"] = "{0} h {1} min",
        ["places.duration_m"] = "{0} min",
        ["places.filters_nsfw"] = "Locales +18",
        ["places.reset_filters"] = "Restablecer filtros",
        ["places.menu_filter"] = "Filtrar",
        ["places.menu_search"] = "Buscar",
        ["places.search_hint"] = "Buscar locales…",
        ["places.no_search_results"] = "Ningún local coincide con tu búsqueda.",
        ["places.open_now"] = "¡Abierto ahora!",
        ["places.show_all_tags"] = "Mostrar todas las etiquetas",
        ["places.no_reviews_owner"] = "Aún no hay reseñas.",
        ["places.image_extra_banner"] = "Banner de carrusel {0}",
        ["places.venue_pending"] = "Pendiente de moderación",
        ["places.menu_addvenue"] = "Añadir mi local",
        ["places.addvenue_title"] = "Añade tu local",
        ["places.addvenue_intro"] = "¿Tienes un local? AetherLove Lugares lo pone delante de los jugadores dentro del propio juego, y publicarlo es 100% gratis. Sin cuotas, sin niveles de pago, sin trampa.",
        ["places.addvenue_perks_header"] = "¿Por qué publicar tu local?",
        ["places.addvenue_perk_reviews_title"] = "Valoraciones y comentarios",
        ["places.addvenue_perk_reviews_body"] = "Los visitantes pueden valorar tu local y dejar comentarios: una forma estupenda de promocionarte, ganar reputación y recibir opiniones sinceras.",
        ["places.addvenue_perk_reach_title"] = "Llega a los jugadores en el juego",
        ["places.addvenue_perk_reach_body"] = "Tu local, sus horarios y los eventos en vivo aparecen justo donde ya están los jugadores: dentro del juego.",
        ["places.addvenue_perk_share_title"] = "Compartible en chats",
        ["places.addvenue_perk_share_body"] = "Los jugadores pueden compartir tu local entre ellos directamente en sus chats de AetherLove.",
        ["places.addvenue_how_heading"] = "Cómo conseguir acceso",
        ["places.addvenue_how_body"] = "Los roles de local se conceden a través de nuestro Discord. Únete al servidor y abre un ticket de soporte pidiendo acceso de local; una vez concedido, el editor Mis locales se desbloquea en tu perfil.",
        ["places.addvenue_discord_btn"] = "Únete a nuestro Discord",
        ["places.addvenue_ticket_note"] = "En el Discord, abre un ticket de soporte y pide acceso de local. Solo lleva un momento y es completamente gratis.",
        ["places.share"] = "Compartir",
        ["places.share_title"] = "Compartir local",
        ["places.share_search_hint"] = "Busca entre tus matches…",
        ["places.share_send"] = "Compartir",
        ["places.share_no_matches"] = "No se encontraron matches.",
        ["places.share_loading"] = "Cargando el local…",
        ["places.share_unavailable"] = "Este local ya no está disponible.",
        ["places.share_view"] = "Ver local",
        ["places.back_to_chat"] = "Volver al chat",

        ["places.hide_venue"] = "Ocultar este local",
        ["places.hide_intro_title"] = "Ocultar locales",
        ["places.hide_intro_body"] = "Esto oculta un local de tu vista de Places. Solo se oculta para ti, en este dispositivo. Puedes recuperar los locales ocultos cuando quieras desde el menú de arriba de esta página.",
        ["places.hide_intro_note"] = "Ahora mismo no se ha ocultado nada. La próxima vez que lo elijas, el local desaparecerá al instante.",
        ["places.menu_hidden"] = "Locales ocultos ({0})",
        ["places.hidden_title"] = "Locales ocultos",
        ["places.unhide"] = "Mostrar",

        // added after update 1.6.0
        ["places.tag_247"] = "Local 24/7",
        ["places.filters_247"] = "Mostrar locales 24/7",
        ["places.tag_lgbtq"] = "LGBTQ+",
        ["places.tag_minigames"] = "Minijuegos",
    };
}
