namespace AetherLove.Services.Localization;

internal static class OnboardingRu
{
    public static readonly System.Collections.Generic.Dictionary<string, string> Strings = new()
    {
        ["onboarding.header_welcome"] = "Добро пожаловать!",
        ["onboarding.header_how_it_works"] = "Как это работает",
        ["onboarding.header_terms_of_service"] = "Условия использования",
        ["onboarding.header_sign_in"] = "Вход",
        ["onboarding.header_secure_messages"] = "Защитите ваши сообщения",
        ["onboarding.header_your_profile"] = "Ваш профиль",
        ["onboarding.header_profile_picture"] = "Фото профиля",
        ["onboarding.header_your_photos"] = "Ваши фотографии",
        ["onboarding.header_optional_details"] = "Дополнительные сведения",
        ["onboarding.header_match_preferences"] = "Предпочтения для пар",
        ["onboarding.header_make_it_yours"] = "Настройте под себя",
        ["onboarding.header_all_set"] = "Всё готово!",
        ["onboarding.header_default"] = "AetherLove",

        ["onboarding.back"] = "← Назад",
        ["onboarding.saving"] = "Сохранение…",
        ["onboarding.start_swiping"] = "Начать листать →",
        ["onboarding.finish"] = "Завершить →",
        ["onboarding.retry"] = "Повторить →",
        ["onboarding.next"] = "Далее →",
        ["onboarding.could_not_assemble"] = "Не удалось собрать {0}: {1}",
        ["onboarding.select_photo"] = "Выбрать фото",
        ["onboarding.image_files"] = "Файлы изображений",
        ["onboarding.crop_avatar"] = "Обрезать аватар",
        ["onboarding.crop_main_photo"] = "Обрезать главное фото",
        ["onboarding.crop_extra_photo"] = "Обрезать дополнительное фото {0}",

        // Step 2 — How It Works
        ["onboarding.how_intro"] = "Вот как работает AetherLove — от создания профиля до общения с вашей первой парой.",
        ["onboarding.how1_title"] = "Создайте профиль",
        ["onboarding.how1_body"] = "Расскажите нам о своём персонаже — раса, сервер, языки и то, что вы ищете. Загрузите портретное фото. Это ваша визитная карточка.",
        ["onboarding.how2_title"] = "Просматривайте колоду",
        ["onboarding.how2_body"] = "Каждый раз, открывая колоду, вы увидите стопку карточек профилей. Свайпните вправо (или нажмите ♥), чтобы поставить 'нравится'. Свайпните влево (или нажмите X), чтобы пропустить.",
        ["onboarding.how3_title"] = "Задайте предпочтения",
        ["onboarding.how3_body"] = "Выберите расу, регион, языки и интересы, которые вы хотели бы видеть у потенциальной пары. Чем точнее вы укажете, тем точнее будут пары по вашим предпочтениям.",
        ["onboarding.how4_title"] = "Пара!",
        ["onboarding.how4_body"] = "Когда оба человека листают вправо друг на друга, возникает пара. Вы получите уведомление, и приватный чат откроется автоматически.",
        ["onboarding.how5_title"] = "Общайтесь в игре",
        ["onboarding.how5_body"] = "Отправляйте сообщения прямо через плагин — без внешних приложений. Ваши сообщения защищены сквозным шифрованием, администрация AetherLove не может читать ваши чаты.",
        ["onboarding.how6_title"] = "Сохраняйте контроль",
        ["onboarding.how6_body"] = "Обновляйте профиль, изменяйте ваши предпочтения или отменяйте пары в любой момент на экране настроек. AetherLove НИКОГДА не передаёт другим игрокам ваше полное имя персонажа, местоположение или данные аккаунта.",
        ["onboarding.how_ready"] = "Готовы начать? Нажмите «Далее», чтобы продолжить.",

        // Step 2 — Terms of Service
        ["onboarding.tos_p1"] = "AetherLove — это плагин социальных знакомств для Final Fantasy XIV, предназначенный для совершеннолетних пользователей. Продолжая, вы подтверждаете, что вам не менее 18 лет, и соглашаетесь на регистрацию в социальной платформе для совершеннолетних.",
        ["onboarding.tos_p2"] = "Я понимаю, что предоставляемая мной информация профиля — включая отображаемое имя, описание, домашний сервер, сведения о персонаже и любые загружаемые мной фотографии — может быть видна другим пользователям AetherLove. Я несу ответственность за точность своего профиля и за то, чтобы любые загружаемые мной фотографии были уместными и чтобы у меня было право ими делиться.",
        ["onboarding.tos_ownership"] = "Персонажи на любых загружаемых мной фотографиях должны быть моими собственными. Если на изображении присутствует персонаж другого игрока, я подтверждаю, что у меня есть его разрешение на публикацию. Я не буду загружать скриншоты или позы персонажей, которые мне не принадлежат, без согласия их владельца.",
        ["onboarding.tos_p3"] = "Я обязуюсь уважительно взаимодействовать со всеми другими пользователями. Домогательства, нежелательный откровенный контент, разжигание ненависти или любые формы оскорблений в адрес других пользователей строго запрещены. Нарушение этих условий может привести к удалению с платформы без предупреждения и права на обжалование.",
        ["onboarding.tos_nsfl"] = "Контент NSFL (\"Not Suitable For Life\") никогда и ни при каких обстоятельствах не допускается в AetherLove. Сюда входит любое изображение или сообщение, изображающее реальное или постановочное насилие с кровью, смерть, графическое насилие, расчленение, тяжёлые травмы, жестокое обращение с животными или самоповреждение, а также любой другой шокирующий или отвратительный материал. Это полностью отдельно от опции NSFW: пометка контента как NSFW никогда не делает контент NSFL допустимым. Мы применяем строгую политику нулевой терпимости. Публикация контента NSFL влечёт немедленный и постоянный бан аккаунта без предупреждения и без права на обжалование.",
        ["onboarding.tos_p4"] = "Я понимаю, что AetherLove — это неофициальный плагин, созданный сообществом, и не связан с компанией Square Enix Co., Ltd. и не одобрен ею. Он предоставляется «как есть», без гарантий доступности, безопасности данных или пригодности для какой-либо цели. Разработчики плагина не несут ответственности за действия других пользователей или за любые последствия использования этого плагина.",
        ["onboarding.tos_p5"] = "Решения модераторов — включая предупреждения, временные и постоянные блокировки — принимаются исключительно по усмотрению администрации AetherLove. Последнее слово во всех вопросах модерации остаётся за администрацией. Решения могут не объясняться и не обосновываться перед затронутым пользователем и не подлежат обжалованию, если администрация прямо не указала иное.",
        ["onboarding.tos_p6"] = "Мы любим и ценим персонажей-лалафелей не меньше других, но взрослые и NSFW-функции недоступны игрокам, чья раса персонажа — лалафель. Поскольку лалафели выглядят по-детски, мы не делаем исключений в индивидуальном порядке и применяем эту политику единообразно ко всем аккаунтам-лалафелям. Опция ролевых игр 18+, согласие на NSFW и загрузка NSFW-фотографий отключены, пока раса вашего персонажа является лалафелем. Попытка обойти это ограничение приведет к удалению аккаунта.",
        ["onboarding.tos_ai"] = "Модерация с помощью ИИ — я согласен(а), что текст и изображения моего профиля автоматически проверяются с помощью API модерации OpenAI, чтобы помочь выявлять контент, нарушающий эти правила, и сохранять AetherLove безопасным для всех. Я также согласен(а), что изображения моего профиля оцениваются дополнительной моделью OpenAI — как на соответствие правилам AetherLove для изображений (изображение моего собственного персонажа Final Fantasy XIV, а не фан-арт, сгенерированные ИИ изображения или не связанный с этим контент), так и на предмет того, являются ли они SFW или NSFW. Текст и изображения моего профиля отправляются в OpenAI только для модерации и никогда не используются для обучения моделей OpenAI. Я понимаю, что каждое окончательное решение по модерации принимается сотрудниками-людьми AetherLove — ИИ сам по себе никогда не несёт ответственности за решение о модерации.",
        ["onboarding.tos_p7"] = "Я согласен(а), что эти условия могут быть обновлены в любое время. Продолжение использования AetherLove после обновления означает принятие изменённых условий.",
        ["onboarding.tos_read_carefully"] = "ПРОСИМ ОЗНАКОМИТЬСЯ",
        ["onboarding.tos_accepted"] = "Условия приняты — нажмите «Далее», чтобы продолжить.",
        ["onboarding.tos_timer"] = "Пожалуйста, ознакомьтесь — кнопка согласия будет доступна через {0}с",
        ["onboarding.tos_scroll_bottom"] = "Прокрутите до конца, чтобы принять.",
        ["onboarding.tos_i_agree"] = "Я согласен(а)",

        // Step 3 — XIVAuth
        ["onboarding.auth_signin_with_xivauth"] = "Войти через XIVAuth",
        ["onboarding.auth_intro"] = "AetherLove использует XIVAuth для идентификации игроков Final Fantasy XIV. Пароль не требуется — аутентификация безопасно выполняется через ваш игровой клиент.",
        ["onboarding.auth_contacting"] = "Связь с AetherLove",
        ["onboarding.auth_dont_have_xivauth"] = "Нет XIVAuth?",
        ["onboarding.auth_xivauth_explainer"] = "XIVAuth — это бесплатная единая система входа для инструментов Final Fantasy XIV, поддерживаемая сообществом. Она используется для подтверждения, что вы - настоящий игрок FFXIV, привязывая вашего персонажа с помощью Lodestone — не передавая при этом ваш пароль Square Enix. Регистрация займёт всего минуту.",
        ["onboarding.auth_create_account"] = "Создать аккаунт XIVAuth",
        ["onboarding.auth_complete_in_browser"] = "Завершите вход в браузере",
        ["onboarding.auth_browser_opened"] = "Окно браузера открыто. Завершите вход через XIVAuth, при возвращении — этот шаг продолжится автоматически.",
        ["onboarding.auth_open_browser_again"] = "Открыть браузер снова",
        ["onboarding.auth_cancel"] = "Отмена",
        ["onboarding.auth_loading_profile"] = "Вход выполнен! Загрузка вашего профиля",
        ["onboarding.auth_signed_in"] = "Вход выполнен!",
        ["onboarding.auth_welcome_back"] = "С возвращением!",
        ["onboarding.auth_welcome_back_named"] = "С возвращением, {0}!",
        ["onboarding.auth_details_loaded"] = "Мы загрузили ваши данные — можно сразу начинать листать.",
        ["onboarding.auth_timeout"] = "Вход занял слишком много времени. Пожалуйста, попробуйте снова.",
        ["onboarding.auth_failed"] = "Не удалось войти.",
        ["onboarding.auth_try_again"] = "Попробовать снова",

        // Step 3a — Passphrase
        ["onboarding.pass_heading"] = "Защитите ваши сообщения",
        ["onboarding.pass_intro"] = "Администрация AetherLove не может читать ваши личные сообщения — ни сейчас, ни когда-либо. Чтобы это было возможно, мы шифруем каждое сообщение ключом, который знаете только ВЫ. Задайте кодовую фразу ниже. Кодовая фраза похожа на пароль, но её вы должны запомнить и сохранить — кнопки «забыл кодовую фразу» здесь нет. Запишите её, сохраните в менеджере паролей, отнеситесь к ней как к любому важному для вас паролю.",
        ["onboarding.pass_warning"] = "⚠ Если вы используете AetherLove на чужом компьютере — или купите новый — вам нужно будет снова ввести эту кодовую фразу, чтобы читать свои чаты. Без неё ваши сообщения будут недоступны даже для вас.",
        ["onboarding.pass_label"] = "Кодовая фраза-пароль",
        ["onboarding.pass_confirm_label"] = "Подтвердите кодовую фразу",
        ["onboarding.pass_err_empty"] = "Пожалуйста, введите кодовую фразу.",
        ["onboarding.pass_err_too_short"] = "Кодовая фраза должна содержать не менее {0} символов.",
        ["onboarding.pass_err_confirm_empty"] = "Пожалуйста, подтвердите кодовую фразу.",
        ["onboarding.pass_err_mismatch"] = "Кодовые фразы не совпадают.",
        ["onboarding.pass_ack"] = "Я понимаю, что историю чатов нельзя будет восстановить, если я забуду эту кодовую фразу-пароль.",
        ["onboarding.pass_securing"] = "Защита ваших ключей…",
        ["onboarding.pass_strength_too_weak"] = "Слишком слабая",
        ["onboarding.pass_strength_weak"] = "Слабая",
        ["onboarding.pass_strength_ok"] = "Нормальная",
        ["onboarding.pass_strength_good"] = "Хорошая",
        ["onboarding.pass_strength_strong"] = "Надёжная",

        // Step 4 — Profile (data labels)
        ["onboarding.region_na"] = "Северная Америка (NA)",
        ["onboarding.region_eu"] = "Европа (EU)",
        ["onboarding.region_oceania"] = "Океания",
        ["onboarding.region_japan"] = "Япония",
        ["onboarding.race_hyur"] = "Хьюр (Hyur)",
        ["onboarding.race_elezen"] = "Элезен (Elezen)",
        ["onboarding.race_lalafell"] = "Лалафель (Lalafell)",
        ["onboarding.race_miqote"] = "Мико'те (Miqo'te)",
        ["onboarding.race_roegadyn"] = "Роегадин (Roegadyn)",
        ["onboarding.race_au_ra"] = "Ау Ра (Au Ra)",
        ["onboarding.race_hrothgar"] = "Хротгар (Hrothgar)",
        ["onboarding.race_viera"] = "Виера (Viera)",
        ["onboarding.gender_male"] = "Мужской",
        ["onboarding.gender_female"] = "Женский",
        ["onboarding.gender_other"] = "Другой",
        ["onboarding.content_housing"] = "Хаузинг",
        ["onboarding.content_music_bard"] = "Музыка и барды",
        ["onboarding.content_rp_venues"] = "Клубы с РП",
        ["onboarding.content_club_venues"] = "Посещение клубов",
        ["onboarding.content_gpose"] = "Gpose",
        ["onboarding.content_story_lore"] = "Сюжет и лор",
        ["onboarding.content_roulettes"] = "Рулетки",
        ["onboarding.content_regular"] = "Казуал. контент",
        ["onboarding.content_extreme_trials"] = "Экстримы",
        ["onboarding.content_savage"] = "Саважи",
        ["onboarding.content_pvp"] = "PvP",
        ["onboarding.content_blue_mage"] = "Синий маг",
        ["onboarding.content_triple_triad"] = "Triple Triad",
        ["onboarding.content_mahjong"] = "Маджонг",
        ["onboarding.content_treasure_hunts"] = "Охота за сокровищами",
        ["onboarding.content_crafting_gathering"] = "Крафт и сбор",
        ["onboarding.content_fishing"] = "Рыбалка",
        ["onboarding.content_achievement_hunting"]= "Охота за достижениями",
        ["onboarding.lf_chatting"] = "Общение с новыми людьми",
        ["onboarding.lf_casual_buddies"] = "Знакомства для непринуждённой игры",
        ["onboarding.lf_gpose_glamour"] = "Знакомства для GPose и гламура",
        ["onboarding.lf_romance"] = "Романтика в игре",
        ["onboarding.lf_long_term"] = "Долгие отношения в игре",
        ["onboarding.lf_rp_partners"] = "Партнёров для ролевых игр",
        ["onboarding.lf_erp"] = "Ролевые игры 18+ (ERP)",

        // Step 4 — Profile (body)
        ["onboarding.profile_intro"] = "Эти поля отображаются на вашей публичной карточке профиля и используются для подбора пар.",
        ["onboarding.profile_identity"] = "Личность",
        ["onboarding.profile_display_name"] = "Отображаемое имя",
        ["onboarding.profile_display_name_tip"] = "Имя, которое видят другие пользователи. Используйте имя или псевдоним.\nПробелы не допускаются.",
        ["onboarding.profile_display_name_hint"] = "Имя или псевдоним (без пробелов), минимум 3 символа.",
        ["onboarding.profile_about_me"] = "Обо мне",
        ["onboarding.profile_about_me_tip"] = "Напишите коротко о себе. Что вам нравится?\nКакие связи вы ищете?",
        ["onboarding.profile_char_count"] = "{0} / 500 символов",
        ["onboarding.profile_preview"] = "Предпросмотр",
        ["onboarding.profile_bio_placeholder"] = "Здесь появится ваше описание…",
        ["onboarding.profile_location"] = "Местоположение",
        ["onboarding.profile_server_region"] = "Регион сервера",
        ["onboarding.profile_server_region_tip"] = "Выберите свой регион Final Fantasy XIV.\nЭто помогает подбирать игроков поблизости.",
        ["onboarding.profile_character"] = "Персонаж",
        ["onboarding.profile_race"] = "Раса",
        ["onboarding.profile_gender"] = "Пол",
        ["onboarding.profile_languages_speak"] = "Языки, на которых я говорю",
        ["onboarding.profile_languages_hint"] = "Выберите все языки, на которых вам комфортно общаться.",
        ["onboarding.profile_content_heading"] = "Мне нравится следующий контент",
        ["onboarding.profile_content_hint"] = "Выберите всё подходящее — это отображается на вашей карточке профиля.",
        ["onboarding.profile_looking_for_heading"]= "Я ищу",
        ["onboarding.profile_looking_for_hint"] = "Выберите всё подходящее (нужно хотя бы одно). Честность помогает находить лучше пары.",
        ["onboarding.profile_erp_enables_nsfw"] = "    Выбор этого автоматически включает NSFW для вашего профиля.",
        ["onboarding.profile_nsfw_heading"] = "NSFW",
        ["onboarding.profile_nsfw_lalafell"] = "Взрослые и NSFW-функции недоступны, пока ваша раса установлена как лалафель. Подробнее см. в 'Условиях использования'.",
        ["onboarding.profile_nsfw_explainer"] = "NSFW означает «Not Safe For Work» — контент, содержащий наготу или сексуальный подтекст. Хотите включить показ NSFW-профилей? Это приведёт к возможным парам с игроками, загрузившими NSFW-изображения в свой профиль. Эти изображения всегда размыты, пока вы не разрешите их показывать.",
        ["onboarding.profile_nsfw_checkbox"] = "NSFW-профили: ДА",
        ["onboarding.profile_nsfw_locked"] = "Включено, потому что вы выбрали ролевые игры 18+ (ERP). Снимите эту галочку, чтобы изменить настройку.",
        ["onboarding.profile_timezone"] = "Часовой пояс",
        ["onboarding.profile_timezone_hint"] = "Показывается потенциальным парам, чтобы они знали, когда вы активны.",

        // Step 5 — Avatar
        ["onboarding.avatar_heading"] = "Ваше фото профиля",
        ["onboarding.avatar_intro"] = "Ваше фото профиля показывается в чате и при подборе пар. Требуется квадратное изображение с лицом вашего персонажа FFXIV.",
        ["onboarding.avatar_tip"] = "Совет: лучше всего подходит крупный портретный скриншот из GPose.",
        ["onboarding.avatar_sfw_warning"] = "Ваше главное фото профиля ДОЛЖНО быть SFW. Загрузка NSFW-изображения является поводом для удаления аккаунта.",
        ["onboarding.avatar_browse"] = "Обзор…",
        ["onboarding.avatar_crop_hint"] = "Редактор для обрезки фото открылся в отдельном окне.\nНажмите на «Использовать этот кадр», чтобы подтвердить аватар.",
        ["onboarding.avatar_no_image"] = "Изображение ещё не выбрано.",
        ["onboarding.avatar_set"] = "Фото профиля установлено!",
        ["onboarding.avatar_change_photo"] = "Сменить фото",
        ["onboarding.avatar_its_a_match"] = "Это пара!",
        ["onboarding.avatar_match_preview_caption"] = "Предпросмотр: как ваш аватар выглядит на карточках анкет",

        // Step 5 — Image Disclaimer
        ["onboarding.disclaimer_intro"] = "AetherLove создан для игроков Final Fantasy XIV. Прежде чем загружать изображения, пожалуйста, внимательно прочитайте следующие правила.",
        ["onboarding.disclaimer_moderation"] = "Все загрузки проходят как автоматическую, так и ручную модерацию.",
        ["onboarding.disclaimer_general_heading"] = "Общее",
        ["onboarding.disclaimer_general_body"] = "Все изображения, загружаемые в AetherLove, должны изображать вашего персонажа Final Fantasy XIV. Изображения, не связанные с персонажами Final Fantasy XIV, будут отклонены без предупреждения.",
        ["onboarding.disclaimer_profile_images_heading"] = "Изображения профиля",
        ["onboarding.disclaimer_profile_images_body"] = "Изображения в вашем профиле должны быть скриншотами или G-Pose вашего собственного персонажа Final Fantasy XIV. Следующее:",
        ["onboarding.disclaimer_not_allowed"] = "НЕ ДОПУСКАЕТСЯ:",
        ["onboarding.disclaimer_na_fan_art"] = "Фан-арт",
        ["onboarding.disclaimer_na_3d_renders"] = "Пользовательские 3D-рендеры",
        ["onboarding.disclaimer_na_ai"] = "Изображения, сгенерированные ИИ",
        ["onboarding.disclaimer_na_real_photos"] = "Фотографии реальных людей или мест",
        ["onboarding.disclaimer_na_unrelated"] = "Любое изображение, не связанное с вашим персонажем FFXIV",
        ["onboarding.disclaimer_profile_images_consent"] = "Загружайте только изображения вашего собственного персонажа. Если на снимке появляется персонаж другого игрока, сначала убедитесь, что у вас есть его разрешение. Пожалуйста, не загружайте скриншоты или позы чужого персонажа без согласия его владельца.",
        ["onboarding.disclaimer_nsfw_heading"] = "NSFW-контент",
        ["onboarding.disclaimer_nsfw_body1"] = "Ваш основной аватар и главное фото профиля должны быть Safe For Work (SFW). Простое правило: если вам было бы комфортно показать изображение руководителю или коллеге, оно подходит в качестве основного.",
        ["onboarding.disclaimer_nsfw_body2"] = "Дополнительные фотографии профиля могут содержать NSFW-контент, но при загрузке их нужно явно отметить как таковые. Мы настоятельно рекомендуем держать как можно больше изображений SFW.",
        ["onboarding.disclaimer_nsfl_heading"] = "Контент NSFL: никогда не допускается",
        ["onboarding.disclaimer_nsfl_body"] = "Контент NSFL (\"Not Suitable For Life\") никогда не допускается ни в одном изображении, независимо от того, отмечено оно как SFW или NSFW. Сюда относится любое изображение реального или постановочного насилия с кровью, смерти, графического насилия, расчленения, тяжёлых травм, жестокого обращения с животными или самоповреждения, а также всё прочее, призванное шокировать, травмировать или вызывать отвращение. Это полностью отдельно от правил NSFW выше: пометка NSFW разрешает откровенный контент, но никогда не контент NSFL.",
        ["onboarding.disclaimer_nsfl_zero_tolerance"] = "Нулевая терпимость: загрузка контента NSFL означает немедленный и постоянный бан аккаунта без предупреждения и без обжалования.",
        ["onboarding.disclaimer_ai_heading"] = "Модерация с помощью ИИ",
        ["onboarding.disclaimer_ai_body"] = "Каждое загружаемое вами изображение автоматически проверяется с помощью API модерации OpenAI и оценивается дополнительной моделью OpenAI — как на соответствие изложенным выше правилам для изображений (что на нём ваш собственный персонаж FFXIV, а не фан-арт, сгенерированное ИИ изображение или нечто не связанное), так и на предмет того, является ли оно SFW или NSFW. Ваши изображения отправляются в OpenAI только для модерации и никогда не используются для обучения моделей OpenAI. Каждое окончательное решение по модерации принимается сотрудниками-людьми AetherLove — ИИ сам по себе никогда не несёт ответственности за решение о модерации.",
        ["onboarding.disclaimer_rules_heading"] = "Что будет, если изображение нарушает правила?",
        ["onboarding.disclaimer_rules_body1"] = "Если одно из ваших изображений нарушает эти правила, вы получите уведомление. Изображение будет удалено автоматически, а ваш профиль будет приостановлен — теневой бан — пока вы не исправите проблему.",
        ["onboarding.disclaimer_rules_body2"] = "Загрузка контента, который является вредоносным, эксплуатирующим или незаконным, приведёт к:",
        ["onboarding.disclaimer_permanent_ban"] = "Постоянному бану аккаунта.",
        ["onboarding.disclaimer_continue"] = "Я согласен(а), продолжить",

        // Step 6 — Photos
        ["onboarding.photos_heading"] = "Фотографии профиля",
        ["onboarding.photos_intro"] = "Добавьте портретные фотографии в профиль (соотношение 10:16). Первое фото обязательно; фото 2–4 необязательны. Рекомендуются изображения не менее 480 × 768 пикс.",
        ["onboarding.photos_main_thumb"] = "Главное",
        ["onboarding.photos_tap_slot"] = "Нажмите на фото выше, чтобы добавить фото или управлять им.",
        ["onboarding.photos_main_photo"] = "Главное фото",
        ["onboarding.photos_extra_photo"] = "Дополнительное фото {0}",
        ["onboarding.photos_main_sfw_warning"] = "Ваше главное фото профиля ДОЛЖНО быть SFW. Загрузка NSFW-изображения приведет к приостановке или удалению аккаунта.",
        ["onboarding.photos_sfw_nsfw_question"] = "Это изображение SFW или NSFW?",
        ["onboarding.photos_mismatch_warning"] = "При обнаружении системой, что вы загрузили NSFW, выбрав при этом SFW, ваше фото будет отправлено на проверку и вы подвергаете аккаунт риску блокировки.",
        ["onboarding.photos_previously_uploaded"] = "Загружено ранее.",
        ["onboarding.photos_confirmed"] = "Фото загружено.",
        ["onboarding.photos_remove"] = "Удалить",
        ["onboarding.photos_browse"] = "Обзор…",
        ["onboarding.photos_crop_hint"] = "Редактор для обрезки фото открылся в отдельном окне.\nНажмите на «Использовать этот кадр», чтобы подтвердить фото.",
        ["onboarding.photos_required"] = "Это фото обязательно.",
        ["onboarding.photos_optional"] = "Это фото необязательно.",

        // Step 7 — Optional
        ["onboarding.expansion_none"] = "(Нет)",
        ["onboarding.opt_heading"] = "Расскажите о себе подробнее",
        ["onboarding.opt_intro"] = "Все поля на этой странице необязательны. Заполните столько, сколько пожелаете — эти сведения отображаются на вашей карточке профиля и помогают другим вас найти.",
        ["onboarding.opt_fav_job"] = "Любимая профессия",
        ["onboarding.opt_fav_job_tip"] = "Профессия или роль, которая вам нравится больше всего.\nВведите, чтобы отфильтровать.",
        ["onboarding.opt_fav_location"] = "Любимое место",
        ["onboarding.opt_fav_location_tip"] = "Место в Эорзии, которое вы любите посещать.\nВведите, чтобы отфильтровать.",
        ["onboarding.opt_location_unavailable"] = "(данные о местах недоступны)",
        ["onboarding.opt_location_none"] = "(Нет)",
        ["onboarding.opt_fav_expansion"] = "Любимое дополнение",
        ["onboarding.opt_fav_expansion_tip"] = "Ваше любимое дополнение FFXIV всех времён.",
        ["onboarding.opt_music_heading"] = "Любимая песня",
        ["onboarding.opt_music_tip"] = "Вставьте ссылку из Spotify, SoundCloud, Apple Music или YouTube Music.",
        ["onboarding.opt_fav_spotify"] = "Spotify",
        ["onboarding.opt_fav_spotify_tip"] = "Вставьте URL трека Spotify или ID трека.\nНазвание трека подтянется автоматически.",
        ["onboarding.opt_fav_soundcloud"] = "SoundCloud",
        ["onboarding.opt_fav_apple"] = "Apple Music",
        ["onboarding.opt_fav_youtube"] = "YouTube Music",
        ["onboarding.opt_fav_movie"] = "Любимый фильм",
        ["onboarding.opt_fav_movie_tip"] = "Ваш любимый фильм всех времён — любого жанра.",
        ["onboarding.opt_fav_anime"] = "Любимое аниме",
        ["onboarding.opt_fav_anime_tip"] = "Ваш любимый аниме-сериал или фильм.",
        ["onboarding.opt_fav_ff_character"] = "Любимый персонаж Final Fantasy",
        ["onboarding.opt_fav_ff_character_tip"] = "Любой персонаж из вселенной Final Fantasy.",
        ["onboarding.opt_weekday_playtimes"] = "Время игры в будни (Пн–Пт)",
        ["onboarding.opt_weekday_playtimes_tip"] = "Выберите время, когда вы обычно онлайн в будни.\nНаведите на столбец, чтобы увидеть время.",
        ["onboarding.opt_weekend_playtimes"] = "Время игры в выходные (Сб–Вс)",
        ["onboarding.opt_weekend_playtimes_tip"] = "Выберите время, когда вы обычно онлайн в выходные.\nНаведите на столбец, чтобы увидеть время.",
        ["onboarding.opt_sync_tool"] = "Плагин для синхронизации",
        ["onboarding.opt_sync_tool_tip"] = "Плагины для синхронизации, такие как Lightless или Honsefarm, позволяют парам\nавтоматически делиться модифицированным внешним видом.",
        ["onboarding.time_am"] = "AM",
        ["onboarding.time_pm"] = "PM",

        // Step 8 — Filters
        ["onboarding.filters_intro"] = "Расскажите, кого бы вы хотели найти. Выбранные предпочтения улучшат поиск — вы можете изменить их в любой момент в настройках.",
        ["onboarding.filters_heading"] = "Я хочу найти пару с",
        ["onboarding.filters_race"] = "Раса",
        ["onboarding.filters_gender"] = "Пол",
        ["onboarding.filters_region"] = "Регион",
        ["onboarding.filters_spoken_language"] = "Используемый язык",
        ["onboarding.filters_language_tip"] = "Если выбрано ничего, вам будет предложены анкеты всех доступных языков.",
        ["onboarding.filters_all"] = "Все",
        ["onboarding.filters_none"] = "Ничего",
        ["onboarding.filters_clear"] = "Очистить",
        ["onboarding.filters_any_race"] = "  Нет выбора — любая раса",
        ["onboarding.filters_any_gender"] = "  Нет выбора — любой пол",
        ["onboarding.filters_any_region"] = "  Нет выбора — любой регион",
        ["onboarding.filters_any_language"] = "  Нет выбора — нет предпочтений по языку",

        // Step 9 — Finished
        ["onboarding.finished_heading"] = "Всё готово!",
        ["onboarding.finished_intro"] = "Ваш профиль создан, предпочтения для пар сохранены. Вы готовы к знакомствам с другими игроками Final Fantasy XIV.",
        ["onboarding.finished_verification_heading"] = "Верификация профиля",
        ["onboarding.finished_verification_body"] = "Ваш профиль будет проверен нашими модераторами в течение 24 часов. В это время ваш профиль полностью активен — вы можете просматривать, находить пары и общаться прямо сейчас.",
        ["onboarding.finished_verification_note"] = "Мы свяжемся с вами только в случае нарушений правил вашим профилем или изображением.",
        ["onboarding.finished_swiping_heading"] = "Начните листать",
        ["onboarding.finished_swiping_body"] = "Перейдите в колоду, чтобы просматривать профили. Нажмите ♥ на том, кто вам интересен — когда они ответят ♥, это пара! Приватный чат откроется автоматически.",
        ["onboarding.finished_rejected_heading"] = "Если изображение отклонено",
        ["onboarding.finished_rejected_body"] = "Если какое-либо из ваших изображений нарушит наши правила при проверке, вы получите уведомление. Изображение будет удалено, и вас попросят его заменить. Тем временем ваш профиль остаётся активным.",
        ["onboarding.finished_good_luck"] = "Удачи — AetherLove держит за вас кулачки! ♥",

        // Step 10 — Preferences
        ["onboarding.prefs_intro"] = "Настройте AetherLove под себя — выберите цветовую тему и размер телефона. Оба параметра можно изменить в любой момент в настройках.",
        ["onboarding.prefs_theme"] = "Тема",
        ["onboarding.prefs_phone_size"] = "Размер телефона",

        // added after update (1.3.1)
        ["onboarding.content_ultimate_raiding"] = "Ультимейты",
        ["onboarding.content_deep_dungeons"] = "Глубокие подземелья",
        ["onboarding.content_variant_criterion"] = "Вариативные / критериальные подземелья",
        ["onboarding.content_field_operations"] = "Полевые операции (Bozja, Eureka)",
        ["onboarding.race_gender_warning"] = "Пожалуйста, выбирайте расу и пол вашего персонажа FFXIV, а не ваш пол в реальной жизни!",
        ["onboarding.tos_race_gender"] = "Я соглашаюсь выбрать правильные расу и пол для моего персонажа Final Fantasy XIV при настройке профиля и понимаю, что моё основное фото профиля должно соответствовать этому персонажу.",
    };
}
