namespace AetherLove.Services.Localization;

internal static class PlacesPt
{
    public static readonly System.Collections.Generic.Dictionary<string, string> Strings = new()
    {
        // added after update 1.5.0
        ["places.title"] = "Lugares",
        ["places.load_failed"] = "Não foi possível carregar os Lugares: {0}",
        ["places.happening_now"] = "Aberto agora",
        ["places.this_week"] = "Esta semana",
        ["places.nothing_upcoming"] = "Sem aberturas previstas esta semana.",
        ["places.empty"] = "Nenhum local corresponde aos seus filtros.",
        ["places.empty_hint"] = "Tente ampliar seus filtros de Lugares.",
        ["places.today"] = "Hoje",
        ["places.tomorrow"] = "Amanhã",
        ["places.live"] = "AO VIVO",
        ["places.ends_in"] = "Termina em {0}",
        ["places.going"] = "{0} vão",
        ["places.back"] = "Voltar",

        ["places.filters_title"] = "Filtros de Lugares",
        ["places.filters_tags"] = "Mostrar locais com a tag",
        ["places.filters_regions"] = "Regiões",
        ["places.filters_hint"] = "Sem seleção, tudo é mostrado. Estes filtros são independentes das suas preferências de matching.",
        ["places.filters_apply"] = "Aplicar",

        ["places.tag_rp_venue"] = "Local de roleplay",
        ["places.tag_barding"] = "Música de bardo",
        ["places.tag_nsfw"] = "Local +18",
        ["places.tag_live_dj"] = "DJs ao vivo",
        ["places.tag_sync"] = "Sync ativado",
        ["places.tag_nightclub"] = "Boate",
        ["places.tag_bar_tavern"] = "Bar / Taverna",
        ["places.tag_cafe"] = "Café",
        ["places.tag_restaurant"] = "Restaurante",
        ["places.tag_casino"] = "Cassino",
        ["places.tag_maid_cafe"] = "Maid café",
        ["places.tag_bathhouse"] = "Casa de banhos",
        ["places.tag_gpose_studio"] = "Estúdio de gpose",
        ["places.tag_live_music"] = "Música ao vivo",
        ["places.tag_market"] = "Mercado / Loja",

        ["places.day_mon"] = "Seg",
        ["places.day_tue"] = "Ter",
        ["places.day_wed"] = "Qua",
        ["places.day_thu"] = "Qui",
        ["places.day_fri"] = "Sex",
        ["places.day_sat"] = "Sáb",
        ["places.day_sun"] = "Dom",

        ["places.location_ward"] = "Distrito {0}",
        ["places.location_plot"] = "Lote {0}",
        ["places.location_room"] = "Quarto {0}",

        ["places.schedule"] = "Horários de funcionamento",
        ["places.rsvp"] = "Confirmar presença",
        ["places.rsvp_going"] = "Vou ✓",

        ["places.reviews_title"] = "Avaliações",
        ["places.no_reviews"] = "Ainda não há avaliações — seja a primeira pessoa!",
        ["places.no_rating_yet"] = "Ainda sem notas.",
        ["places.rating_summary"] = "{0} · {1} avaliações",
        ["places.write_review"] = "Escrever uma avaliação",
        ["places.your_review"] = "Sua avaliação",
        ["places.review_pending"] = "Sua avaliação aguarda moderação e só você pode vê-la.",
        ["places.review_submit"] = "Publicar avaliação",
        ["places.review_update"] = "Atualizar avaliação",
        ["places.review_delete"] = "Excluir",
        ["places.review_delete_title"] = "Excluir avaliação?",
        ["places.review_delete_body"] = "Sua nota e seu texto serão removidos permanentemente.",
        ["places.reviews_more"] = "Carregar mais avaliações",

        ["places.menu_my_venues"] = "Meus locais",
        ["places.my_venues"] = "Meus locais",
        ["places.my_venues_empty"] = "Você ainda não criou um local. Crie um para aparecer em Lugares!",
        ["places.venue_saved"] = "Local salvo.",
        ["places.new_venue"] = "+ Novo local",
        ["places.venue_cap"] = "Você atingiu o limite de {0} locais.",
        ["places.venue_stats"] = "{0} curtidas · {1} avaliações",
        ["places.venue_unlisted"] = "Ocultado pela moderação",
        ["places.back_to_venues"] = "Voltar",
        ["places.new_venue_title"] = "Novo local",
        ["places.edit_venue_title"] = "Editar local",

        ["places.section_details"] = "Detalhes",
        ["places.venue_name"] = "Nome do local",
        ["places.venue_description"] = "Descrição",
        ["places.section_tags"] = "Tags",
        ["places.section_location"] = "Localização",
        ["places.use_current_location"] = "Usar minha localização atual",
        ["places.use_current_location_hint"] = "Fique dentro do seu local para preencher tudo automaticamente.",
        ["places.venue_datacenter"] = "Data center",
        ["places.venue_world"] = "Mundo",
        ["places.venue_ward"] = "Distrito",
        ["places.venue_plot"] = "Lote",
        ["places.venue_room"] = "Quarto",
        ["places.venue_room_hint"] = "Para apartamentos, defina o lote como 0 e informe o número do quarto.",
        ["places.venue_timezone"] = "Fuso horário do local",
        ["places.venue_timezone_tip"] = "Os horários abaixo são inseridos neste fuso horário. Os visitantes sempre os veem convertidos para o horário local deles.",

        ["places.section_hours"] = "Horários de funcionamento",
        ["places.hours_explainer"] = "Escolha os dias e clique em uma hora de início e uma de fim — as horas intermediárias se preenchem sozinhas, mesmo depois da meia-noite.",
        ["places.add_opening_time"] = "+ Adicionar horário",
        ["places.rule_weekly"] = "Semanal",
        ["places.rule_one_time"] = "Único",
        ["places.rule_date_hint"] = "Data (AAAA-MM-DD)",
        ["places.rule_span"] = "Aberto {0}",
        ["places.hours_pick_start"] = "Clique para definir o início",
        ["places.hours_pick_end"] = "Clique para definir o fim",

        ["places.section_images"] = "Imagens",
        ["places.image_banner"] = "Banner",
        ["places.image_logo"] = "Imagem do local",
        ["places.image_banner_hint"] = "Banner largo, no mínimo {0}×{1}px. Exibido na página do seu local.",
        ["places.image_logo_hint"] = "Quadrada, no mínimo {0}px — exibida nos cartões do local.",
        ["places.image_pick"] = "Escolher imagem",
        ["places.image_ready"] = "Pronta para salvar",
        ["places.image_remove"] = "Remover",
        ["places.crop_banner"] = "Recortar banner",
        ["places.crop_logo"] = "Recortar imagem do local",

        ["places.err_name"] = "Dê um nome ao seu local (no mínimo 3 caracteres).",
        ["places.err_location"] = "Preencha o data center e o mundo.",
        ["places.err_plot_or_room"] = "Defina um número de lote ou de quarto.",
        ["places.err_date"] = "Aberturas únicas precisam de uma data no formato AAAA-MM-DD.",
        ["places.err_days"] = "Aberturas semanais precisam de pelo menos um dia selecionado.",
        ["places.save_venue"] = "Salvar local",
        ["places.delete_venue"] = "Excluir local",
        ["places.delete_venue_title"] = "Excluir o local?",
        ["places.delete_venue_body"] = "\"{0}\" e todas as curtidas, avaliações e presenças serão removidas permanentemente.",

        // added after update 1.5.1
        ["places.venue_region"] = "Região",
        ["places.venue_district"] = "Distrito",
        ["places.venue_dc_select"] = "Escolhe um data center",
        ["places.venue_world_select"] = "Escolhe um mundo",
        ["places.venue_tz_select"] = "Escolhe um fuso horário",
        ["places.venue_tz_search"] = "Pesquisar…",
        ["places.err_description"] = "Adiciona uma descrição.",
        ["places.err_tags"] = "Escolhe pelo menos uma etiqueta.",
        ["places.err_images"] = "São necessários um banner e um logótipo.",
        ["places.err_timezone"] = "Escolhe um fuso horário.",
        ["places.err_hours"] = "Adiciona pelo menos um horário de funcionamento.",
        ["places.section_rsvpd"] = "Suas confirmações",
        ["places.duration_hm"] = "{0} h {1} min",
        ["places.duration_m"] = "{0} min",
        ["places.filters_nsfw"] = "Locais +18",
        ["places.reset_filters"] = "Redefinir filtros",
        ["places.menu_filter"] = "Filtrar",
        ["places.menu_search"] = "Buscar",
        ["places.search_hint"] = "Buscar locais…",
        ["places.no_search_results"] = "Nenhum local corresponde à sua busca.",
        ["places.open_now"] = "Aberto agora!",
        ["places.show_all_tags"] = "Mostrar todas as etiquetas",
        ["places.no_reviews_owner"] = "Ainda não há avaliações.",
        ["places.image_extra_banner"] = "Banner do carrossel {0}",
        ["places.venue_pending"] = "Aguardando moderação",
        ["places.menu_addvenue"] = "Adicionar meu local",
        ["places.addvenue_title"] = "Adicione o seu local",
        ["places.addvenue_intro"] = "Você tem um local? O AetherLove Lugares o coloca na frente dos jogadores dentro do próprio jogo, e publicá-lo é 100% grátis. Sem taxas, sem planos pagos, sem pegadinha.",
        ["places.addvenue_perks_header"] = "Por que publicar o seu local?",
        ["places.addvenue_perk_reviews_title"] = "Avaliações e comentários",
        ["places.addvenue_perk_reviews_body"] = "Os visitantes podem avaliar o seu local e deixar comentários: uma ótima forma de divulgar, construir reputação e receber opiniões sinceras.",
        ["places.addvenue_perk_reach_title"] = "Alcance jogadores no jogo",
        ["places.addvenue_perk_reach_body"] = "O seu local, os horários e os eventos ao vivo aparecem exatamente onde os jogadores já estão: dentro do jogo.",
        ["places.addvenue_perk_share_title"] = "Compartilhável nos chats",
        ["places.addvenue_perk_share_body"] = "Os jogadores podem compartilhar o seu local uns com os outros diretamente nos chats do AetherLove.",
        ["places.addvenue_how_heading"] = "Como conseguir acesso",
        ["places.addvenue_how_body"] = "Os papéis de local são concedidos pelo nosso Discord. Entre no servidor e abra um ticket de suporte pedindo acesso de local; assim que for concedido, o editor Meus locais é liberado no seu perfil.",
        ["places.addvenue_discord_btn"] = "Entre no nosso Discord",
        ["places.addvenue_ticket_note"] = "No Discord, abra um ticket de suporte e peça acesso de local. Leva só um instante e é totalmente grátis.",
        ["places.share"] = "Compartilhar",
        ["places.share_title"] = "Compartilhar local",
        ["places.share_search_hint"] = "Pesquise seus matches…",
        ["places.share_send"] = "Compartilhar",
        ["places.share_no_matches"] = "Nenhum match encontrado.",
        ["places.share_loading"] = "Carregando o local…",
        ["places.share_unavailable"] = "Este local não está mais disponível.",
        ["places.share_view"] = "Ver local",
        ["places.back_to_chat"] = "Voltar ao chat",

        ["places.hide_venue"] = "Ocultar esta venue",
        ["places.hide_intro_title"] = "Ocultar venues",
        ["places.hide_intro_body"] = "Isto oculta uma venue da sua visão de Places. Ela fica oculta apenas para você, neste dispositivo. Você pode trazer venues ocultas de volta a qualquer momento pelo menu no topo desta página.",
        ["places.hide_intro_note"] = "Nada foi ocultado agora. Na próxima vez que escolher isto, a venue desaparecerá na hora.",
        ["places.menu_hidden"] = "Venues ocultas ({0})",
        ["places.hidden_title"] = "Venues ocultas",
        ["places.unhide"] = "Mostrar",
    };
}
