namespace AetherLove.Services.Localization;

internal static class ChatFr
{
    public static readonly System.Collections.Generic.Dictionary<string, string> Strings = new()
    {
        // ===== Chat =====
        ["chat.no_conversation_selected"] = "Aucune conversation sélectionnée.",
        ["chat.unreadable_message"] = "[message illisible]",
        ["chat.report_submitted_toast"] = "Signalement envoyé. Notre équipe de modération l'examinera.",
        ["chat.view_profile"] = "Voir le profil",
        ["chat.back_to_matches"] = "Retour aux correspondances",
        ["chat.menu_open_profile"] = "Ouvrir le profil",
        ["chat.menu_copy_message"] = "Copier le message",
        ["chat.menu_pin"] = "Épingler le chat",
        ["chat.menu_unpin"] = "Désépingler le chat",
        ["chat.menu_unmatch"] = "Annuler la correspondance",
        ["chat.menu_block"] = "Bloquer",
        ["chat.menu_report_user"] = "Signaler l'utilisateur",
        ["chat.unmatch_title"] = "Annuler la correspondance",
        ["chat.unmatch_body"] = "Lorsque vous annulez la correspondance avec ce joueur, le chat sera masqué pour les deux personnes. Si vous correspondez à nouveau plus tard, votre historique réapparaîtra.",
        ["chat.unmatch_confirm"] = "Annuler la correspondance",
        ["chat.block_title"] = "Bloquer l'utilisateur",
        ["chat.block_body"] = "Lorsque vous bloquez un utilisateur, le chat est masqué pour les deux personnes et il n'apparaîtra plus dans vos correspondances à l'avenir.",
        ["chat.block_confirm"] = "Bloquer",
        ["chat.cancel"] = "Annuler",
        ["chat.loading_messages"] = "Chargement des messages…",
        ["chat.error"] = "Erreur : {0}",
        ["chat.e2e_self_broken"] = "Un problème est survenu avec votre configuration E2E, veuillez contacter le support.",
        ["chat.seen_suffix"] = " · vu",
        ["chat.send"] = "Envoyer",
        ["chat.emoji_button"] = ":)",
        ["chat.system_notice_line1"] = "Ceci est un chat privé entre vous et {0}. Ce chat est chiffré de bout en bout, l'équipe d'AetherLove ne peut pas lire vos messages. En haut à droite, vous trouverez un menu pour annuler la correspondance, bloquer ou signaler votre correspondance.",
        ["chat.system_notice_line2"] = "N'oubliez pas : {0} ne connaît pas votre nom complet ni votre localisation tant que vous ne les partagez pas. Prenez soin de votre vie privée et ne partagez davantage que lorsque vous êtes prêt.",
        ["chat.i_understand"] = "J'ai compris",
        ["chat.report_title"] = "Signaler l'utilisateur",
        ["chat.report_reason_prompt"] = "Veuillez décrire la raison de votre signalement :",
        ["chat.report_agree"] = "J'accepte de soumettre un signalement à l'encontre de {0}",
        ["chat.report_agree_contents"] = "J'accepte d'envoyer le contenu de cette conversation à l'équipe d'AetherLove",
        ["chat.submitting"] = "Envoi…",
        ["chat.submit"] = "Envoyer",

        // Verify encryption
        ["verify.title"] = "Vérifier le chiffrement",
        ["verify.intro"] = "AetherLove chiffre cette conversation de bout en bout : vous seul et {0} pouvez la lire, pas même notre équipe. Le motif tissé ci-dessous est généré à partir de vos deux clés de chiffrement.",
        ["verify.unavailable"] = "La vérification n'est pas encore prête. Elle sera disponible une fois que vous aurez tous les deux configuré le chiffrement et échangé vos clés.",
        ["verify.how"] = "Si {0} voit exactement le même motif et le même code sur son écran, personne n'intercepte votre conversation. Comparez-les par chat vocal ou en personne. S'ils ne correspondent pas, ne partagez plus rien de sensible et contactez le support.",
        ["verify.your_key"] = "Votre clé publique",
        ["verify.their_key"] = "Clé publique de {0}",
        ["verify.keys_explain"] = "Les clés publiques peuvent être partagées sans risque ; c'est ainsi que vos applications se reconnaissent. Les clés privées correspondantes ne quittent jamais vos appareils, donc aucun serveur (pas même le nôtre) ne peut lire vos messages.",
        ["verify.back"] = "Retour au chat",

        // ChatListScreen
        ["chat.preview_me_prefix"] = "Moi : ",
        ["chat.matches_title"] = "Correspondances",
        ["chat.archive_title"] = "Archivés",
        ["chat.show_search"] = "Afficher la recherche",
        ["chat.hide_search"] = "Masquer la recherche",
        ["chat.search_hint"] = "Nom ou message",
        ["chat.searching"] = "Recherche en cours…",
        ["chat.search_estimate"] = "Cela peut prendre {0}-{1} secondes en raison du nombre de conversations.",
        ["chat.search_rate_limited"] = "Trop de conversations à rechercher d'un coup. Réessayez dans une minute.",
        ["chat.search_no_results"] = "Aucun résultat trouvé",
        ["chat.menu_archive"] = "Archiver le chat",
        ["chat.menu_unarchive"] = "Désarchiver le chat",
        ["chat.no_archived"] = "Aucun chat archivé",
        ["chat.all_archived"] = "Tous vos chats sont archivés",
        ["chat.loading"] = "Chargement…",
        ["chat.matches_load_error"] = "Impossible de charger les correspondances : {0}",
        ["chat.connectivity_error"] = "Impossible de se connecter au serveur AetherLove. Veuillez réessayer ou consulter Discord pour voir l'état du serveur.",
        ["chat.empty_state"] = "Vous n'avez pas encore de correspondances — mais cela changera bientôt. Continuez à swiper !",
        ["chat.new_match"] = "nouvelle correspondance",
        ["chat.say_hi"] = "Vous avez un match — dites bonjour !",
        ["chat.time_ago_minutes"] = "il y a {0} min",
        ["chat.time_ago_hours"] = "il y a {0} h",
        ["chat.time_ago_days"] = "il y a {0} j",
    };
}
