namespace AetherLove.Services.Localization;

internal static class PlacesEn
{
    public static readonly System.Collections.Generic.Dictionary<string, string> Strings = new()
    {
        // added after update 1.5.0
        ["places.title"] = "Places",
        ["places.load_failed"] = "Couldn't load Places: {0}",
        ["places.happening_now"] = "Happening now",
        ["places.this_week"] = "This week",
        ["places.nothing_upcoming"] = "No upcoming openings this week.",
        ["places.empty"] = "No venues match your filters yet.",
        ["places.empty_hint"] = "Try widening your Places filters.",
        ["places.today"] = "Today",
        ["places.tomorrow"] = "Tomorrow",
        ["places.live"] = "LIVE",
        ["places.ends_in"] = "Ends in {0}",
        ["places.going"] = "{0} going",
        ["places.back"] = "Back",

        ["places.filters_title"] = "Places filters",
        ["places.filters_tags"] = "Show venues tagged",
        ["places.filters_regions"] = "Regions",
        ["places.filters_hint"] = "Nothing selected means everything is shown. These filters are separate from your matching preferences.",
        ["places.filters_apply"] = "Apply",

        ["places.tag_rp_venue"] = "Roleplay venue",
        ["places.tag_barding"] = "Barding",
        ["places.tag_nsfw"] = "18+ venue",
        ["places.tag_live_dj"] = "Live DJs",
        ["places.tag_sync"] = "Sync enabled",
        ["places.tag_nightclub"] = "Nightclub",
        ["places.tag_bar_tavern"] = "Bar / Tavern",
        ["places.tag_cafe"] = "Café",
        ["places.tag_restaurant"] = "Restaurant",
        ["places.tag_casino"] = "Casino",
        ["places.tag_maid_cafe"] = "Maid café",
        ["places.tag_bathhouse"] = "Bathhouse",
        ["places.tag_gpose_studio"] = "Gpose studio",
        ["places.tag_live_music"] = "Live music",
        ["places.tag_market"] = "Market / Shop",

        ["places.day_mon"] = "Mon",
        ["places.day_tue"] = "Tue",
        ["places.day_wed"] = "Wed",
        ["places.day_thu"] = "Thu",
        ["places.day_fri"] = "Fri",
        ["places.day_sat"] = "Sat",
        ["places.day_sun"] = "Sun",

        ["places.location_ward"] = "Ward {0}",
        ["places.location_plot"] = "Plot {0}",
        ["places.location_room"] = "Room {0}",

        ["places.schedule"] = "Opening times",
        ["places.rsvp"] = "RSVP",
        ["places.rsvp_going"] = "Going ✓",

        ["places.reviews_title"] = "Reviews",
        ["places.no_reviews"] = "No reviews yet — be the first!",
        ["places.no_rating_yet"] = "No ratings yet.",
        ["places.rating_summary"] = "{0} · {1} reviews",
        ["places.write_review"] = "Write a review",
        ["places.your_review"] = "Your review",
        ["places.review_pending"] = "Your review is awaiting moderation and is only visible to you.",
        ["places.review_submit"] = "Post review",
        ["places.review_update"] = "Update review",
        ["places.review_delete"] = "Delete",
        ["places.review_delete_title"] = "Delete review?",
        ["places.review_delete_body"] = "Your rating and text will be removed permanently.",
        ["places.reviews_more"] = "Load more reviews",

        ["places.menu_my_venues"] = "My venues",
        ["places.my_venues"] = "My venues",
        ["places.my_venues_empty"] = "You haven't created a venue yet. Create one to show up in Places!",
        ["places.venue_saved"] = "Venue saved.",
        ["places.new_venue"] = "+ New venue",
        ["places.venue_cap"] = "You've reached the limit of {0} venues.",
        ["places.venue_stats"] = "{0} likes · {1} reviews",
        ["places.venue_unlisted"] = "Unlisted by moderation",
        ["places.back_to_venues"] = "Back",
        ["places.new_venue_title"] = "New venue",
        ["places.edit_venue_title"] = "Edit venue",

        ["places.section_details"] = "Details",
        ["places.venue_name"] = "Venue name",
        ["places.venue_description"] = "Description",
        ["places.section_tags"] = "Tags",
        ["places.section_location"] = "Location",
        ["places.use_current_location"] = "Use my current location",
        ["places.use_current_location_hint"] = "Stand inside your venue to fill everything in automatically.",
        ["places.venue_datacenter"] = "Datacenter",
        ["places.venue_world"] = "World",
        ["places.venue_ward"] = "Ward",
        ["places.venue_plot"] = "Plot",
        ["places.venue_room"] = "Room",
        ["places.venue_room_hint"] = "For apartments, set the plot to 0 and enter the room number.",
        ["places.venue_timezone"] = "Venue timezone",
        ["places.venue_timezone_tip"] = "Opening times below are entered in this timezone. Visitors always see them converted to their own local time.",

        ["places.section_hours"] = "Opening times",
        ["places.hours_explainer"] = "Pick the days, then click a start hour and an end hour — the hours in between fill in automatically, even past midnight.",
        ["places.add_opening_time"] = "+ Add opening time",
        ["places.rule_weekly"] = "Weekly",
        ["places.rule_one_time"] = "One-time",
        ["places.rule_date_hint"] = "Date (YYYY-MM-DD)",
        ["places.rule_span"] = "Open {0}",
        ["places.hours_pick_start"] = "Click to set the start",
        ["places.hours_pick_end"] = "Click to set the end",

        ["places.section_images"] = "Images",
        ["places.image_banner"] = "Banner",
        ["places.image_logo"] = "Venue picture",
        ["places.image_banner_hint"] = "Wide banner, at least {0}×{1}px. Shown on your venue page.",
        ["places.image_logo_hint"] = "Square, at least {0}px — shown on venue cards.",
        ["places.image_pick"] = "Choose image",
        ["places.image_ready"] = "Ready to save",
        ["places.image_remove"] = "Remove",
        ["places.crop_banner"] = "Crop banner",
        ["places.crop_logo"] = "Crop venue picture",

        ["places.err_name"] = "Give your venue a name (at least 3 characters).",
        ["places.err_location"] = "Fill in the data center and world.",
        ["places.err_plot_or_room"] = "Set a plot number or a room number.",
        ["places.err_date"] = "One-time openings need a date in YYYY-MM-DD format.",
        ["places.err_days"] = "Weekly openings need at least one day selected.",
        ["places.save_venue"] = "Save venue",
        ["places.delete_venue"] = "Delete venue",
        ["places.delete_venue_title"] = "Delete venue?",
        ["places.delete_venue_body"] = "\"{0}\" and all of its likes, reviews and RSVPs will be removed permanently.",

        // added after update 1.5.1
        ["places.venue_region"] = "Region",
        ["places.venue_district"] = "District",
        ["places.venue_dc_select"] = "Select a datacenter",
        ["places.venue_world_select"] = "Select a world",
        ["places.venue_tz_select"] = "Select a timezone",
        ["places.venue_tz_search"] = "Search…",
        ["places.err_description"] = "Please add a description.",
        ["places.err_tags"] = "Please choose at least one tag.",
        ["places.err_images"] = "A banner and a logo are both required.",
        ["places.err_timezone"] = "Please choose a timezone.",
        ["places.err_hours"] = "Please add at least one opening time.",
        ["places.section_rsvpd"] = "RSVP'd",
        ["places.duration_hm"] = "{0}h {1}m",
        ["places.duration_m"] = "{0}m",
        ["places.filters_nsfw"] = "18+ venues",
        ["places.reset_filters"] = "Reset filters",
        ["places.menu_filter"] = "Filter",
        ["places.menu_search"] = "Search",
        ["places.search_hint"] = "Search venues…",
        ["places.no_search_results"] = "No venues match your search.",
        ["places.open_now"] = "Open right now!",
        ["places.show_all_tags"] = "Show all tags",
        ["places.no_reviews_owner"] = "No reviews yet.",
        ["places.image_extra_banner"] = "Carousel banner {0}",
        ["places.venue_pending"] = "Pending moderation",
        ["places.menu_addvenue"] = "Add my venue",
        ["places.addvenue_title"] = "Add your venue",
        ["places.addvenue_intro"] = "Run a venue? AetherLove Places puts it in front of players right inside the game, and listing it is 100% free. No fees, no paid tiers, no catch.",
        ["places.addvenue_perks_header"] = "Why list your venue?",
        ["places.addvenue_perk_reviews_title"] = "Ratings and comments",
        ["places.addvenue_perk_reviews_body"] = "Guests can rate your venue and leave comments: a great way to advertise, build a reputation, and get honest feedback.",
        ["places.addvenue_perk_reach_title"] = "Reach players in-game",
        ["places.addvenue_perk_reach_body"] = "Your venue, opening times and live events show up right where players already are: inside the game.",
        ["places.addvenue_perk_share_title"] = "Shareable in chats",
        ["places.addvenue_perk_share_body"] = "Users can share your venue with each other directly in their AetherLove chats.",
        ["places.addvenue_how_heading"] = "How to get access",
        ["places.addvenue_how_body"] = "Venue roles are handed out through our Discord. Join the server and open a support ticket asking for venue access; once granted, the My Venues editor unlocks on your profile.",
        ["places.addvenue_discord_btn"] = "Join our Discord",
        ["places.addvenue_ticket_note"] = "In the Discord, open a support ticket and ask for venue access. It only takes a moment and it is completely free.",
        ["places.share"] = "Share",
        ["places.share_title"] = "Share venue",
        ["places.share_search_hint"] = "Search your matches…",
        ["places.share_send"] = "Share",
        ["places.share_no_matches"] = "No matches found.",
        ["places.share_loading"] = "Loading venue…",
        ["places.share_unavailable"] = "This venue is no longer available.",
        ["places.share_view"] = "View venue",
        ["places.back_to_chat"] = "Back to the chat",

        ["places.hide_venue"] = "Hide this venue",
        ["places.hide_intro_title"] = "Hide venues",
        ["places.hide_intro_body"] = "This hides a venue from your Places overview. It's hidden only for you, on this device. You can bring hidden venues back any time via the menu at the top of this page.",
        ["places.hide_intro_note"] = "Nothing was hidden just now. The next time you choose this, the venue disappears immediately.",
        ["places.menu_hidden"] = "Hidden venues ({0})",
        ["places.hidden_title"] = "Hidden venues",
        ["places.unhide"] = "Show",
    };
}
