namespace AetherLove.Services.Localization;

internal static class ChatRu
{
    public static readonly System.Collections.Generic.Dictionary<string, string> Strings = new()
    {
        ["chat.no_conversation_selected"] = "Чат не выбран.",
        ["chat.unreadable_message"] = "[нечитаемое сообщение]",
        ["chat.report_submitted_toast"] = "Жалоба отправлена. Команда модераторов рассмотрит её.",
        ["chat.view_profile"] = "Открыть профиль",
        ["chat.back_to_matches"] = "Назад к парам",
        ["chat.menu_open_profile"] = "Открыть профиль",
        ["chat.menu_copy_message"] = "Скопировать сообщение",
        ["chat.menu_pin"] = "Закрепить чат",
        ["chat.menu_unpin"] = "Открепить чат",
        ["chat.menu_unmatch"] = "Отменить пару",
        ["chat.menu_block"] = "Заблокировать",
        ["chat.menu_report_user"] = "Пожаловаться на пользователя",
        ["chat.unmatch_title"] = "Отменить пару",
        ["chat.unmatch_body"] = "При отмене пары с этим игроком, чат будет скрыт у обоих. При появлении пары в будущем, ваша история появится вновь.",
        ["chat.unmatch_confirm"] = "Отменить пару",
        ["chat.block_title"] = "Заблокировать пользователя",
        ["chat.block_body"] = "При блокировке этого пользователя, чат будет скрыт у обоих, и он не будет появляться в ваших парах в будущем.",
        ["chat.block_confirm"] = "Заблокировать",
        ["chat.cancel"] = "Отмена",
        ["chat.loading_messages"] = "Загрузка сообщений…",
        ["chat.e2e_self_broken"] = "Что-то не так с вашей настройкой E2E. Пожалуйста, обратитесь в поддержку.",
        ["chat.seen_suffix"] = " · просмотрено",
        ["chat.send"] = "Отправить",
        ["chat.emoji_button"] = ":)",
        ["chat.system_notice_line1"] = "Это приватный чат между вами и {0}. Этот чат защищён сквозным шифрованием, администрация AetherLove не имеет доступа к вашим сообщениям. В правом верхнем углу вы найдёте меню для отмены пары, блокировки или жалобы на вашу пару.",
        ["chat.system_notice_line2"] = "Помните: {0} не знает вашего полного имени или местоположения, до тех пор, пока вы сами не поделитесь этим. Будьте осторожны с чувствительной/конфиденциальной информацией и делитесь этим, только когда будете уверены в этом.",
        ["chat.i_understand"] = "Понятно",
        ["chat.report_title"] = "Пожаловаться на пользователя",
        ["chat.report_reason_prompt"] = "Пожалуйста, опишите причину вашей жалобы:",
        ["chat.report_agree"] = "Я согласен(а) подать жалобу на {0}",
        ["chat.report_agree_contents"] = "Я согласен(а) отправить содержимое этого чата администрации AetherLove",
        ["chat.submitting"] = "Отправка…",
        ["chat.submit"] = "Отправить",

        // Verify encryption
        ["verify.title"] = "Проверить шифрование",
        ["verify.intro"] = "AetherLove шифрует этот чат сквозным шифрованием: прочитать его можете только вы и {0}, даже наша команда не может. Сплетённый узор ниже создаётся из ваших двух ключей шифрования.",
        ["verify.unavailable"] = "Проверка пока недоступна. Она появится, как только вы оба настроите шифрование и обменяетесь ключами.",
        ["verify.how"] = "Если {0} видит на своём экране точно такой же узор и код, ваш чат никто не перехватывает. Сравните их в голосовом чате или лично. Если они не совпадают, прекратите делиться чем-либо личным и обратитесь в поддержку.",
        ["verify.your_key"] = "Ваш открытый ключ",
        ["verify.their_key"] = "Открытый ключ {0}",
        ["verify.keys_explain"] = "Открытыми ключами можно безопасно делиться; так ваши приложения узнают друг друга. Соответствующие закрытые ключи никогда не покидают ваши устройства, поэтому ни один сервер (даже наш) не может прочитать ваши сообщения.",
        ["verify.back"] = "Назад к чату",

        // ChatListScreen
        ["chat.preview_me_prefix"] = "Я: ",
        ["chat.matches_title"] = "Пары",
        ["chat.archive_title"] = "Архив",
        ["chat.show_search"] = "Показать поиск",
        ["chat.hide_search"] = "Скрыть поиск",
        ["chat.search_hint"] = "Имя или сообщение",
        ["chat.searching"] = "Поиск…",
        ["chat.search_no_results"] = "Ничего не найдено",
        ["chat.menu_archive"] = "Архивировать чат",
        ["chat.menu_unarchive"] = "Вернуть из архива",
        ["chat.no_archived"] = "Нет архивированных чатов",
        ["chat.all_archived"] = "Все ваши чаты в архиве",
        ["chat.matches_load_error"] = "Не удалось загрузить пары: {0}",
        ["chat.connectivity_error"] = "Не удалось подключиться к серверу AetherLove. Попробуйте ещё раз или загляните в Discord, чтобы узнать статус сервера.",
        ["chat.empty_state"] = "У вас пока нет пар — но скоро это изменится. Продолжайте листать!",
        ["chat.new_match"] = "новая пара",
        ["chat.say_hi"] = "У Вас пара! — скажите привет!",
        ["chat.time_ago_minutes"] = "{0} мин назад",
        ["chat.time_ago_hours"] = "{0} ч назад",
        ["chat.time_ago_days"] = "{0} дн назад",

        // added after update (1.3.1)
        ["chat.you"] = "Вы",
        ["chat.reply"] = "Ответить",
        ["chat.pin_message"] = "Закрепить сообщение",
        ["chat.unpin_message"] = "Открепить сообщение",
        ["chat.pinned_messages"] = "Закреплённые сообщения",
        ["chat.pinned_messages_menu"] = "Закреплённые сообщения ({0})",
        ["chat.quote_unavailable"] = "(исходное сообщение недоступно)",
        ["chat.quote_generic"] = "(сообщение)",
        ["chat.replying_to"] = "Ответ для {0}",
        ["chat.reaction_remove_hint"] = "нажмите, чтобы убрать",
        ["chat.jump"] = "Перейти",
        ["chat.unpin"] = "Открепить",
    };
}
