namespace AetherLove.Services.Localization;

internal static class OnboardingPt
{
    public static readonly System.Collections.Generic.Dictionary<string, string> Strings = new()
    {
        // Header / navigation
        ["onboarding.header_welcome"] = "Bem-vindo!",
        ["onboarding.header_how_it_works"] = "Como Funciona",
        ["onboarding.header_terms_of_service"] = "Termos de Serviço",
        ["onboarding.header_sign_in"] = "Entrar",
        ["onboarding.header_secure_messages"] = "Proteja Suas Mensagens",
        ["onboarding.header_your_profile"] = "Seu Perfil",
        ["onboarding.header_profile_picture"] = "Foto de Perfil",
        ["onboarding.header_your_photos"] = "Suas Fotos",
        ["onboarding.header_optional_details"] = "Detalhes Opcionais",
        ["onboarding.header_match_preferences"] = "Preferências de Match",
        ["onboarding.header_make_it_yours"] = "Deixe do Seu Jeito",
        ["onboarding.header_all_set"] = "Tudo Pronto!",
        ["onboarding.header_default"] = "AetherLove",

        ["onboarding.save_failed"] = "Falha ao salvar: {0}",
        ["onboarding.back"] = "← Voltar",
        ["onboarding.saving"] = "Salvando…",
        ["onboarding.start_swiping"] = "Começar a Deslizar →",
        ["onboarding.finish"] = "Concluir →",
        ["onboarding.retry"] = "Tentar de novo →",
        ["onboarding.next"] = "Avançar →",
        ["onboarding.could_not_assemble"] = "Não foi possível montar {0}: {1}",
        ["onboarding.select_photo"] = "Selecionar Foto",
        ["onboarding.image_files"] = "Arquivos de imagem",
        ["onboarding.crop_avatar"] = "Recortar Avatar",
        ["onboarding.crop_main_photo"] = "Recortar Foto Principal",
        ["onboarding.crop_extra_photo"] = "Recortar Foto Extra {0}",

        // Step 2 — How It Works
        ["onboarding.how_intro"] = "Veja como o AetherLove funciona — desde montar seu perfil até conversar com seu primeiro match.",
        ["onboarding.how1_title"] = "Monte Seu Perfil",
        ["onboarding.how1_body"] = "Conte sobre seu personagem — sua race, servidor, idiomas e o que você procura. Envie uma foto de retrato. Esse é o seu cartão de visitas.",
        ["onboarding.how2_title"] = "Explore o Deck",
        ["onboarding.how2_body"] = "Toda vez que você abre o deck, vê uma pilha de cartões de perfil. Deslize para a direita (ou toque em ♥) para demonstrar interesse. Deslize para a esquerda (ou toque em X) para passar.",
        ["onboarding.how3_title"] = "Defina Suas Preferências",
        ["onboarding.how3_body"] = "Escolha a race, região, idiomas e interesses que você gostaria de encontrar em um match. Quanto mais específico você for, melhores serão os matches que aparecerão.",
        ["onboarding.how4_title"] = "Dê Match!",
        ["onboarding.how4_body"] = "Quando duas pessoas deslizam para a direita uma na outra, vira um Match. Você recebe uma notificação e uma conversa privada abre automaticamente.",
        ["onboarding.how5_title"] = "Converse No Jogo",
        ["onboarding.how5_body"] = "Envie mensagens direto pelo plugin — sem precisar de nenhum app externo. Suas conversas são criptografadas de ponta a ponta, então nem os desenvolvedores do AetherLove conseguem ler seus chats.",
        ["onboarding.how6_title"] = "Mantenha o Controle",
        ["onboarding.how6_body"] = "Atualize seu perfil, ajuste suas preferências ou desfaça o match a qualquer momento na tela de Configurações. O AetherLove NUNCA vai compartilhar seu nome completo de jogador, localização ou informações de conta com outros jogadores.",
        ["onboarding.how_ready"] = "Pronto para começar? Clique em Avançar para continuar.",

        // Step 2 — Terms of Service
        ["onboarding.tos_p1"] = "O AetherLove é um plugin social de matchmaking para Final Fantasy XIV, destinado a usuários adultos. Ao continuar, você confirma que tem pelo menos 18 anos de idade e consente em participar de uma plataforma social adulta.",
        ["onboarding.tos_p2"] = "Eu entendo que as informações de perfil que forneço — incluindo meu nome de exibição, bio, servidor de origem, detalhes do personagem e quaisquer fotos que eu enviar — podem ser visíveis para outros usuários do AetherLove. Sou responsável pela exatidão do meu perfil e por garantir que quaisquer fotos que eu envie sejam apropriadas e que eu tenha o direito de compartilhá-las.",
        ["onboarding.tos_p3"] = "Eu concordo em interagir respeitosamente com todos os outros usuários. Assédio, conteúdo explícito não solicitado, discurso de ódio ou qualquer forma de abuso contra outros usuários são estritamente proibidos. A violação destes termos pode resultar na remoção da plataforma sem aviso ou direito a recurso.",
        ["onboarding.tos_p4"] = "Eu entendo que o AetherLove é um plugin não oficial, feito pela comunidade, e não é afiliado nem endossado pela Square Enix Co., Ltd. Ele é fornecido no estado em que se encontra, sem garantias de disponibilidade, segurança de dados ou adequação a qualquer finalidade. Os desenvolvedores do plugin não são responsáveis pelas ações de outros usuários nem por quaisquer consequências decorrentes do uso deste plugin.",
        ["onboarding.tos_p5"] = "As decisões de moderação — incluindo advertências, suspensões temporárias e banimentos permanentes — são tomadas a critério exclusivo da equipe do AetherLove. A equipe tem a palavra final em todas as questões de moderação. As decisões não precisam ser explicadas ou justificadas ao usuário afetado e não estão sujeitas a recurso, a menos que a equipe declare explicitamente o contrário.",
        ["onboarding.tos_p6"] = "Nós amamos e curtimos os personagens Lalafell tanto quanto qualquer pessoa, mas os recursos adultos e NSFW não estão disponíveis para jogadores cuja race do personagem seja Lalafell. Como os Lalafell têm aparência infantil, não fazemos distinção caso a caso e aplicamos essa política de forma uniforme a todas as contas Lalafell. A opção de Roleplay 18+, a adesão ao NSFW e os envios de fotos NSFW ficam todos desativados enquanto sua race estiver definida como Lalafell. Tentar burlar essa restrição é motivo para remoção da conta.",
        ["onboarding.tos_p7"] = "Eu reconheço que estes termos podem ser atualizados a qualquer momento. O uso contínuo do AetherLove após uma atualização constitui aceitação dos termos revisados.",
        ["onboarding.tos_read_carefully"] = "LEIA COM ATENÇÃO",
        ["onboarding.tos_accepted"] = "Termos aceitos — pressione Avançar para continuar.",
        ["onboarding.tos_timer"] = "Por favor, leia com atenção — o botão de concordar fica disponível em {0}s",
        ["onboarding.tos_scroll_bottom"] = "Role até o final para aceitar.",
        ["onboarding.tos_i_agree"] = "Eu Concordo",

        // Step 3 — XIVAuth
        ["onboarding.auth_signin_with_xivauth"] = "Entrar com XIVAuth",
        ["onboarding.auth_intro"] = "O AetherLove usa o XIVAuth para verificar sua identidade como jogador ativo de Final Fantasy XIV. Nenhuma senha é necessária — a autenticação é feita com segurança através do seu cliente do jogo.",
        ["onboarding.auth_contacting"] = "Contatando o AetherLove",
        ["onboarding.auth_dont_have_xivauth"] = "Não tem XIVAuth?",
        ["onboarding.auth_xivauth_explainer"] = "O XIVAuth é um login único (SSO) gratuito e mantido pela comunidade para ferramentas de Final Fantasy XIV. Ele confirma que você é um jogador de FFXIV de verdade vinculando seu personagem do Lodestone — sem nunca compartilhar sua senha da Square Enix. Cadastrar-se leva apenas um minuto.",
        ["onboarding.auth_create_account"] = "Criar uma conta XIVAuth",
        ["onboarding.auth_complete_in_browser"] = "Conclua o login no seu navegador",
        ["onboarding.auth_browser_opened"] = "Uma janela do navegador foi aberta. Conclua o login com o XIVAuth e volte aqui — esta etapa continuará automaticamente.",
        ["onboarding.auth_open_browser_again"] = "Abrir o navegador novamente",
        ["onboarding.auth_cancel"] = "Cancelar",
        ["onboarding.auth_loading_profile"] = "Conectado! Carregando seu perfil",
        ["onboarding.auth_signed_in"] = "Conectado!",
        ["onboarding.auth_welcome_back"] = "Bem-vindo de volta!",
        ["onboarding.auth_welcome_back_named"] = "Bem-vindo de volta, {0}!",
        ["onboarding.auth_details_loaded"] = "Carregamos seus dados — você já pode começar a deslizar agora mesmo.",
        ["onboarding.auth_timeout"] = "O login demorou demais. Por favor, tente novamente.",
        ["onboarding.auth_failed"] = "Falha no login.",
        ["onboarding.auth_try_again"] = "Tentar novamente",

        // Step 3a — Passphrase
        ["onboarding.pass_heading"] = "Proteja suas mensagens",
        ["onboarding.pass_intro"] = "A equipe do AetherLove não consegue ler suas mensagens privadas — nem agora, nem nunca. Para tornar isso possível, criptografamos cada mensagem usando uma chave que só VOCÊ conhece. Defina uma frase-senha abaixo. Uma frase-senha é como uma senha, mas que você precisa lembrar e guardar — não existe botão de \"esqueci minha frase-senha\". Anote-a, guarde-a em um gerenciador de senhas, faça o que faria com uma senha crítica.",
        ["onboarding.pass_warning"] = "Se você usar o AetherLove em outro computador — ou comprar um computador novo — precisará digitar esta frase-senha de novo para ler seus chats. Sem ela, suas mensagens ficam ilegíveis até para você.",
        ["onboarding.pass_label"] = "Frase-senha",
        ["onboarding.pass_confirm_label"] = "Confirme a frase-senha",
        ["onboarding.pass_err_empty"] = "Por favor, digite uma frase-senha.",
        ["onboarding.pass_err_too_short"] = "A frase-senha deve ter pelo menos {0} caracteres.",
        ["onboarding.pass_err_confirm_empty"] = "Por favor, confirme sua frase-senha.",
        ["onboarding.pass_err_mismatch"] = "As frases-senha não coincidem.",
        ["onboarding.pass_ack"] = "Eu entendo que meu histórico de conversas não poderá ser recuperado se eu esquecer esta frase-senha.",
        ["onboarding.pass_securing"] = "Protegendo suas chaves…",
        ["onboarding.pass_strength_too_weak"] = "Muito fraca",
        ["onboarding.pass_strength_weak"] = "Fraca",
        ["onboarding.pass_strength_ok"] = "Razoável",
        ["onboarding.pass_strength_good"] = "Boa",
        ["onboarding.pass_strength_strong"] = "Forte",

        // Step 4 — Profile (data labels)
        ["onboarding.region_na"] = "América do Norte (NA)",
        ["onboarding.region_eu"] = "Europa (EU)",
        ["onboarding.region_oceania"] = "Oceania",
        ["onboarding.region_japan"] = "Japão",
        ["onboarding.region_prefer_not_to_say"] = "Prefiro não dizer",
        ["onboarding.race_hyur"] = "Hyur",
        ["onboarding.race_elezen"] = "Elezen",
        ["onboarding.race_lalafell"] = "Lalafell",
        ["onboarding.race_miqote"] = "Miqo'te",
        ["onboarding.race_roegadyn"] = "Roegadyn",
        ["onboarding.race_au_ra"] = "Au Ra",
        ["onboarding.race_hrothgar"] = "Hrothgar",
        ["onboarding.race_viera"] = "Viera",
        ["onboarding.gender_male"] = "Masculino",
        ["onboarding.gender_female"] = "Feminino",
        ["onboarding.content_housing"] = "Housing e decoração",
        ["onboarding.content_music_bard"] = "Música e performance de Bard",
        ["onboarding.content_rp_venues"] = "Visitar locais de Roleplay",
        ["onboarding.content_club_venues"] = "Visitar baladas (Clubs)",
        ["onboarding.content_gpose"] = "Gpose",
        ["onboarding.content_story_lore"] = "História e Lore",
        ["onboarding.content_roulettes"] = "Roulettes",
        ["onboarding.content_regular"] = "Conteúdo regular",
        ["onboarding.content_extreme_trials"] = "Extreme Trials",
        ["onboarding.content_savage"] = "Raid Savage",
        ["onboarding.content_pvp"] = "PvP",
        ["onboarding.content_blue_mage"] = "Blue Mage",
        ["onboarding.content_triple_triad"] = "Triple Triad",
        ["onboarding.content_mahjong"] = "Mahjong",
        ["onboarding.content_treasure_hunts"] = "Caças ao Tesouro",
        ["onboarding.content_crafting_gathering"] = "Crafting e Gathering",
        ["onboarding.content_fishing"] = "Pesca",
        ["onboarding.content_achievement_hunting"]= "Caça a Conquistas",
        ["onboarding.lf_chatting"] = "Conversar com gente nova",
        ["onboarding.lf_casual_buddies"] = "Parceiros para jogar casualmente",
        ["onboarding.lf_gpose_glamour"] = "Parceiros de GPose e glamour",
        ["onboarding.lf_romance"] = "Um romance no jogo",
        ["onboarding.lf_long_term"] = "Um relacionamento de longo prazo no jogo",
        ["onboarding.lf_rp_partners"] = "Parceiros de Roleplay",
        ["onboarding.lf_erp"] = "Roleplay 18+ (ERP)",

        // Step 4 — Profile (body)
        ["onboarding.profile_intro"] = "Estes campos aparecem no seu cartão de perfil público e são usados para sugerir matches.",
        ["onboarding.profile_identity"] = "Identidade",
        ["onboarding.profile_display_name"] = "Nome de Exibição",
        ["onboarding.profile_display_name_tip"] = "O nome que os outros usuários veem. Use seu primeiro nome ou um apelido.\nNão são permitidos espaços.",
        ["onboarding.profile_display_name_hint"] = "Primeiro nome ou apelido, sem espaços.",
        ["onboarding.profile_about_me"] = "Sobre mim",
        ["onboarding.profile_about_me_tip"] = "Escreva uma breve apresentação. O que você curte?\nQue tipo de conexões você procura?",
        ["onboarding.profile_char_count"] = "{0} / 500 caracteres",
        ["onboarding.profile_preview"] = "Prévia",
        ["onboarding.profile_bio_placeholder"] = "Sua bio vai aparecer aqui…",
        ["onboarding.profile_location"] = "Localização",
        ["onboarding.profile_server_region"] = "Região do Servidor",
        ["onboarding.profile_server_region_tip"] = "Selecione sua região de Final Fantasy XIV.\nIsso ajuda a combinar você com jogadores próximos.",
        ["onboarding.profile_character"] = "Personagem",
        ["onboarding.profile_race"] = "Race",
        ["onboarding.profile_gender"] = "Gênero",
        ["onboarding.profile_languages_speak"] = "Idiomas que Eu Falo",
        ["onboarding.profile_languages_hint"] = "Selecione todos os idiomas em que você se sente à vontade para conversar.",
        ["onboarding.profile_content_heading"] = "Eu Curto os Seguintes Conteúdos",
        ["onboarding.profile_content_hint"] = "Selecione tudo o que se aplica — isso aparece no seu cartão de perfil.",
        ["onboarding.profile_looking_for_heading"]= "Estou Procurando Por",
        ["onboarding.profile_looking_for_hint"] = "Selecione tudo o que se aplica (pelo menos um é obrigatório). Ser honesto ajuda a encontrar matches melhores.",
        ["onboarding.profile_erp_enables_nsfw"] = "    Selecionar isto ativa automaticamente o NSFW no seu perfil.",
        ["onboarding.profile_nsfw_heading"] = "NSFW",
        ["onboarding.profile_nsfw_lalafell"] = "Os recursos adultos e NSFW não estão disponíveis enquanto sua race estiver definida como Lalafell. Consulte os Termos de Serviço para mais detalhes.",
        ["onboarding.profile_nsfw_explainer"] = "NSFW significa \"Not Safe For Work\" (impróprio para o trabalho) — conteúdo que contém nudez ou temas sexuais. Você quer aderir a perfis NSFW? Isso resultará em possíveis matches com jogadores que enviaram fotos NSFW ao perfil. Essas imagens ficam sempre desfocadas até você escolher revelá-las.",
        ["onboarding.profile_nsfw_checkbox"] = "Perfis NSFW: SIM",
        ["onboarding.profile_nsfw_locked"] = "Ativado obrigatoriamente porque você selecionou Roleplay 18+ (ERP). Desmarque essa opção para alterar esta configuração.",
        ["onboarding.profile_timezone"] = "Fuso horário",
        ["onboarding.profile_timezone_hint"] = "Mostrado para possíveis matches para que saibam quando você está ativo.",

        // Step 5 — Avatar
        ["onboarding.avatar_heading"] = "Sua Foto de Perfil",
        ["onboarding.avatar_intro"] = "Sua foto de perfil é exibida no chat e durante o matching. Exigimos uma imagem quadrada que contenha uma foto do rosto do seu personagem de FFXIV.",
        ["onboarding.avatar_tip"] = "Dica: uma captura de tela de G-Pose com retrato em close funciona melhor.",
        ["onboarding.avatar_sfw_warning"] = "Sua foto de perfil principal PRECISA ser SFW. Enviar uma foto NSFW é motivo para exclusão da conta.",
        ["onboarding.avatar_browse"] = "Procurar…",
        ["onboarding.avatar_crop_hint"] = "O editor de recorte abriu em uma janela separada.\nClique em \"Usar este recorte\" lá para confirmar seu avatar.",
        ["onboarding.avatar_no_image"] = "Nenhuma imagem selecionada ainda.",
        ["onboarding.avatar_set"] = "Foto de perfil definida!",
        ["onboarding.avatar_change_photo"] = "Trocar foto",
        ["onboarding.avatar_its_a_match"] = "Deu Match!",
        ["onboarding.avatar_match_preview_caption"] = "Prévia: como seu avatar aparece nos cartões de match",

        // Step 5 — Image Disclaimer
        ["onboarding.disclaimer_intro"] = "O AetherLove é feito para jogadores de Final Fantasy XIV. Antes de enviar qualquer imagem, por favor leia as seguintes diretrizes com atenção.",
        ["onboarding.disclaimer_moderation"] = "Todos os envios estão sujeitos à moderação automática e manual.",
        ["onboarding.disclaimer_general_heading"] = "Geral",
        ["onboarding.disclaimer_general_body"] = "Todas as imagens enviadas ao AetherLove devem retratar seu personagem de Final Fantasy XIV. Imagens não relacionadas a personagens de Final Fantasy XIV serão rejeitadas sem aviso.",
        ["onboarding.disclaimer_profile_images_heading"] = "Imagens de Perfil",
        ["onboarding.disclaimer_profile_images_body"] = "As imagens exibidas no seu perfil devem ser capturas de tela ou G-Poses do seu próprio personagem de Final Fantasy XIV. NÃO são permitidos:",
        ["onboarding.disclaimer_not_allowed"] = "NÃO PERMITIDO:",
        ["onboarding.disclaimer_na_fan_art"] = "Fan art",
        ["onboarding.disclaimer_na_3d_renders"] = "Renders 3D personalizados",
        ["onboarding.disclaimer_na_ai"] = "Imagens geradas por IA",
        ["onboarding.disclaimer_na_real_photos"] = "Fotografias de pessoas ou lugares reais",
        ["onboarding.disclaimer_na_unrelated"] = "Qualquer imagem não relacionada ao seu personagem de FFXIV",
        ["onboarding.disclaimer_nsfw_heading"] = "Conteúdo NSFW",
        ["onboarding.disclaimer_nsfw_body1"] = "Seu avatar principal e sua foto de perfil principal devem ser Safe For Work (SFW). Uma regra prática simples: se você se sentiria à vontade mostrando a imagem a um gerente ou colega, ela é aceitável como imagem principal.",
        ["onboarding.disclaimer_nsfw_body2"] = "Fotos adicionais do perfil podem conter conteúdo NSFW, mas devem ser explicitamente marcadas como tal ao enviar. Recomendamos fortemente manter o máximo de imagens possível como SFW.",
        ["onboarding.disclaimer_rules_heading"] = "O Que Acontece Se uma Imagem Quebrar as Regras?",
        ["onboarding.disclaimer_rules_body1"] = "Se uma das suas imagens for considerada uma violação destas diretrizes, você receberá uma notificação. A imagem será removida automaticamente e seu perfil ficará em espera — shadowban — até você corrigir o problema.",
        ["onboarding.disclaimer_rules_body2"] = "Enviar conteúdo que seja prejudicial, abusivo ou ilegal resultará em:",
        ["onboarding.disclaimer_permanent_ban"] = "Banimento permanente da conta.",
        ["onboarding.disclaimer_continue"] = "Eu entendi, continuar",

        // Step 6 — Photos
        ["onboarding.photos_heading"] = "Fotos do perfil",
        ["onboarding.photos_intro"] = "Adicione fotos de retrato ao seu perfil (proporção 10:16). O primeiro espaço é obrigatório; os espaços 2 a 4 são opcionais. Para melhores resultados, use imagens de pelo menos 480 × 768 px.",
        ["onboarding.photos_main_thumb"] = "Principal",
        ["onboarding.photos_tap_slot"] = "Toque em um espaço acima para adicionar ou gerenciar uma foto.",
        ["onboarding.photos_main_photo"] = "Foto principal",
        ["onboarding.photos_extra_photo"] = "Foto extra {0}",
        ["onboarding.photos_main_sfw_warning"] = "Sua foto de perfil principal PRECISA ser SFW. Enviar uma foto NSFW é motivo para suspensão ou exclusão da conta.",
        ["onboarding.photos_sfw_nsfw_question"] = "Esta foto é SFW ou NSFW?",
        ["onboarding.photos_mismatch_warning"] = "Se nosso sistema detectar que você enviou conteúdo NSFW enquanto SFW está selecionado, sua foto ficará retida para moderação e você corre o risco de ter a conta suspensa.",
        ["onboarding.photos_previously_uploaded"] = "Enviada anteriormente.",
        ["onboarding.photos_confirmed"] = "Foto confirmada.",
        ["onboarding.photos_remove"] = "Remover",
        ["onboarding.photos_browse"] = "Procurar…",
        ["onboarding.photos_crop_hint"] = "O editor de recorte abriu em uma janela separada.\nClique em \"Usar este recorte\" lá para confirmar a foto.",
        ["onboarding.photos_required"] = "Esta foto é obrigatória.",
        ["onboarding.photos_optional"] = "Esta foto é opcional.",

        // Step 7 — Optional
        ["onboarding.expansion_none"] = "(Nenhuma)",
        ["onboarding.sync_none"] = "Não uso ferramenta de sync",
        ["onboarding.opt_heading"] = "Conte mais sobre você",
        ["onboarding.opt_intro"] = "Todos os campos desta página são opcionais. Preencha quanto quiser — estes detalhes aparecem no seu cartão de perfil e ajudam os outros a encontrar você.",
        ["onboarding.opt_fav_job"] = "Job Favorito",
        ["onboarding.opt_fav_job_tip"] = "O job ou papel que você mais curte.\nDigite para filtrar.",
        ["onboarding.opt_fav_location"] = "Lugar Favorito",
        ["onboarding.opt_fav_location_tip"] = "Um lugar em Eorzea que você adora visitar.\nDigite para filtrar.",
        ["onboarding.opt_location_unavailable"] = "(dados de localização indisponíveis)",
        ["onboarding.opt_location_none"] = "(Nenhum)",
        ["onboarding.opt_fav_expansion"] = "Expansão Favorita",
        ["onboarding.opt_fav_expansion_tip"] = "Sua expansão favorita de todos os tempos do FFXIV.",
        ["onboarding.opt_music_heading"] = "Música favorita",
        ["onboarding.opt_music_tip"] = "Cole um link do Spotify, SoundCloud, Apple Music ou YouTube Music.",
        ["onboarding.opt_fav_spotify"] = "Spotify",
        ["onboarding.opt_fav_spotify_tip"] = "Cole a URL de uma faixa do Spotify ou o ID da faixa.\nO nome da faixa é obtido automaticamente.",
        ["onboarding.opt_fav_soundcloud"] = "SoundCloud",
        ["onboarding.opt_fav_apple"] = "Apple Music",
        ["onboarding.opt_fav_youtube"] = "YouTube Music",
        ["onboarding.opt_spotify_fetching"] = "Obtendo nome da faixa…",
        ["onboarding.opt_spotify_track_id"] = "ID da faixa: {0}",
        ["onboarding.opt_spotify_fetch_failed"] = "(não foi possível obter o título)",
        ["onboarding.opt_fav_movie"] = "Filme Favorito",
        ["onboarding.opt_fav_movie_tip"] = "Seu filme favorito de todos os tempos — de qualquer gênero.",
        ["onboarding.opt_fav_anime"] = "Anime Favorito",
        ["onboarding.opt_fav_anime_tip"] = "Sua série ou filme de anime favorito.",
        ["onboarding.opt_fav_ff_character"] = "Personagem Favorito de Final Fantasy",
        ["onboarding.opt_fav_ff_character_tip"] = "Qualquer personagem do universo Final Fantasy.",
        ["onboarding.opt_weekday_playtimes"] = "Horários de Jogo nos Dias de Semana (Seg–Sex)",
        ["onboarding.opt_weekday_playtimes_tip"] = "Clique nas horas em que você costuma estar online nos dias de semana.\nPasse o mouse sobre uma barra para ver o horário.\nEscolha o seu horário local.",
        ["onboarding.opt_weekend_playtimes"] = "Horários de Jogo no Fim de Semana (Sáb–Dom)",
        ["onboarding.opt_weekend_playtimes_tip"] = "Clique nas horas em que você costuma estar online nos fins de semana.\nPasse o mouse sobre uma barra para ver o horário.\nEscolha o seu horário local.",
        ["onboarding.opt_sync_tool"] = "Ferramenta de sync usada",
        ["onboarding.opt_sync_tool_tip"] = "Ferramentas de sync como Lightless ou Honsefarm permitem que usuários\nque deram match compartilhem aparências de mods automaticamente.",
        ["onboarding.time_am"] = "AM",
        ["onboarding.time_pm"] = "PM",

        // Step 8 — Filters
        ["onboarding.filters_intro"] = "Conte com quem você gostaria de dar match. Estas preferências nos ajudam a mostrar as pessoas certas para você — você pode ajustá-las a qualquer momento nas Configurações.",
        ["onboarding.filters_heading"] = "Quero Dar Match Com",
        ["onboarding.filters_race"] = "Race",
        ["onboarding.filters_gender"] = "Gênero",
        ["onboarding.filters_region"] = "Região",
        ["onboarding.filters_spoken_language"] = "Idioma Falado",
        ["onboarding.filters_language_tip"] = "Deixe tudo desmarcado para dar match independentemente do idioma falado.",
        ["onboarding.filters_all"] = "Todos",
        ["onboarding.filters_none"] = "Nenhum",
        ["onboarding.filters_clear"] = "Limpar",
        ["onboarding.filters_any_race"] = "  Sem seleção — qualquer race",
        ["onboarding.filters_any_gender"] = "  Sem seleção — qualquer gênero",
        ["onboarding.filters_any_region"] = "  Sem seleção — qualquer região",
        ["onboarding.filters_any_language"] = "  Sem seleção — sem preferência de idioma",

        // Step 9 — Finished
        ["onboarding.finished_heading"] = "Tudo Pronto!",
        ["onboarding.finished_intro"] = "Seu perfil foi criado e suas preferências de match foram salvas. Você está pronto para começar a se conectar com outros jogadores de Final Fantasy XIV.",
        ["onboarding.finished_verification_heading"] = "Verificação de Perfil",
        ["onboarding.finished_verification_body"] = "Seu perfil será revisado pela nossa equipe de moderação dentro de 24 horas. Durante esse período, seu perfil fica totalmente ativo — você pode explorar, dar match e conversar imediatamente.",
        ["onboarding.finished_verification_note"] = "Só entraremos em contato se houver algum problema com seu perfil ou imagens.",
        ["onboarding.finished_swiping_heading"] = "Comece a Deslizar",
        ["onboarding.finished_swiping_body"] = "Vá até o Deck para explorar perfis. Toque em ♥ em alguém que te interessa — quando essa pessoa tocar em ♥ de volta, é um Match! Uma conversa privada abre automaticamente.",
        ["onboarding.finished_rejected_heading"] = "Se uma Imagem For Rejeitada",
        ["onboarding.finished_rejected_body"] = "Se alguma das suas imagens violar nossas diretrizes durante a revisão, você receberá uma notificação. A imagem será removida e pediremos que você a substitua. Seu perfil continua ativo nesse meio-tempo.",
        ["onboarding.finished_good_luck"] = "Boa sorte por aí — o AetherLove está torcendo por você! ♥",

        // Step 10 — Preferences
        ["onboarding.prefs_intro"] = "Deixe o AetherLove com a sua cara — escolha um tema de cores e um tamanho de telefone. Você pode mudar ambos a qualquer momento nas Configurações.",
        ["onboarding.prefs_theme"] = "Tema",
        ["onboarding.prefs_phone_size"] = "Tamanho do telefone",
    };
}
