namespace AetherLove.Services.Localization;

internal static class DeckPt
{
    public static readonly System.Collections.Generic.Dictionary<string, string> Strings = new()
    {
        ["deck.cooldown_heading"] = "Viu tudo por enquanto!",
        ["deck.cooldown_body"] = "O AetherLove entrega-te um novo conjunto de perfis a cada poucas horas, para que todo mundo tenha uma chance justa. Volte em breve para novos possíveis matches!",
        ["deck.new_matches_ready"] = "Novos matches estão prontos!",
        ["deck.server_error"] = "Não foi possível acessar o servidor: {0}",
        ["deck.view_profile"] = "Ver perfil",
        ["deck.like"] = "GOSTAR",
        ["deck.nope"] = "PASSAR",
        ["deck.match_you"] = "Tu",
        ["deck.match_your_match"] = "Des-te match",
        ["deck.match_congratulations"] = "Parabéns!",
        ["deck.match_its_a_match"] = "Deu Match!",
        ["deck.match_fx_cosmic"] = "Duas almas, o mesmo universo",
        ["deck.match_fx_synthwave"] = "Juntos, rumo ao pôr do sol",
        ["deck.match_fx_aurora"] = "A mesma luz juntou vocês",
        ["deck.match_fx_kaleido"] = "A simetria perfeita",
        ["deck.match_fx_supernova"] = "Dois corações, uma só batimento",
        ["deck.match_fx_vortex"] = "Atraídos para o mesmo universo",
        ["deck.match_fx_portal"] = "Cortados do mesmo tecido",
        ["deck.match_fx_electric"] = "As faíscas estão a voar",
        ["deck.match_fx_bubble"] = "Duas bolhas a brilhar juntas",
        ["deck.match_fx_dna"] = "Um par perfeito.",
        ["deck.match_fx_firework"] = "Que o céu festeje",
        ["deck.match_fx_vinyl"] = "Na mesma sintonia",
        ["deck.match_fx_arcade_players"] = "* JOGADOR 1 *   * JOGADOR 2 *",
        ["deck.match_fx_arcade_score"] = "PONTOS",
        ["deck.match_fx_constellation"] = "Escrito nas estrelas",
        ["deck.match_fx_slot"] = "Three of a kind",
        ["deck.match_fx_slot_title"] = "JACKPOT!",
        ["deck.match_fx_tarot"] = "As cartas se alinharam — dois destinos entrelaçados",
        ["deck.match_fx_tarot_title"] = "OS NAMORADOS",
        ["deck.match_fx_lavalamp"] = "Duas chamas, um só fogo",
        ["deck.match_fx_lanterns"] = "Duas luzes, o mesmo céu",
        ["deck.match_fx_treasure"] = "Um par que vale ouro",
        ["deck.match_fx_treasure_title"] = "TESOURO ENCONTRADO",
        ["deck.match_start_chatting"] = "Começar a Conversar",
        ["deck.match_keep_swiping"] = "Continuar Deslizando",
        ["deck.no_pool_heading"] = "Sem novos matches para você com base nas suas preferências",
        ["deck.no_pool_body"] = "Durante o beta, isto é esperado",
        ["deck.next_deck"] = "Próximo deck: {0}",
        // added after update (1.3.1)
        ["deck.reswipe_tooltip"] = "Desfazer seu último deslize",
        ["deck.reswipe_cooldown"] = "Desfazer disponível em {0} h {1} min",
        ["deck.reswipe_matched_title"] = "Já deu match!",
        ["deck.reswipe_matched"] = "Você não pode desfazer em um perfil com quem já deu match.",
        ["deck.decide_later_tooltip"] = "Decidir depois",
        ["deck.decide_later_disabled"] = "Esta é a última carta do seu deck.",
        ["deck.reswipe_intro_title"] = "Desfazer seu último deslize",
        ["deck.reswipe_intro"] = "Isto desfaz seu último deslize e traz aquele perfil de volta ao topo. Você pode usar uma vez a cada 24 horas. Fechar este aviso não gasta seu desfazer, então toque no botão novamente quando quiser usá-lo.",
    };
}
