namespace AetherLove.Services.Localization;

internal static class ChatFr
{
    public static readonly System.Collections.Generic.Dictionary<string, string> Strings = new()
    {
        // Chat
        ["chat.no_conversation_selected"] = "Aucune conversation sélectionnée.",
        ["chat.unreadable_message"] = "[message illisible]",
        ["chat.report_submitted_toast"] = "Signalement envoyé. Notre équipe de modération l'examinera.",
        ["chat.view_profile"] = "Voir le profil",
        ["chat.back_to_matches"] = "Retour aux correspondances",
        ["chat.menu_open_profile"] = "Ouvrir le profil",
        ["chat.menu_copy_message"] = "Copier le message",
        ["chat.menu_pin"] = "Épingler le chat",
        ["chat.menu_unpin"] = "Désépingler le chat",
        ["chat.menu_unmatch"] = "Annuler la correspondance",
        ["chat.menu_block"] = "Bloquer",
        ["chat.menu_report_user"] = "Signaler l'utilisateur",
        ["chat.unmatch_title"] = "Annuler la correspondance",
        ["chat.unmatch_body"] = "Lorsque vous annulez la correspondance avec ce joueur, le chat sera masqué pour les deux personnes. Si vous correspondez à nouveau plus tard, votre historique réapparaîtra.",
        ["chat.unmatch_confirm"] = "Annuler la correspondance",
        ["chat.block_title"] = "Bloquer l'utilisateur",
        ["chat.block_body"] = "Lorsque vous bloquez un utilisateur, le chat est masqué pour les deux personnes et il n'apparaîtra plus dans vos correspondances à l'avenir.",
        ["chat.block_confirm"] = "Bloquer",
        ["chat.cancel"] = "Annuler",
        ["chat.loading_messages"] = "Chargement des messages…",
        ["chat.e2e_self_broken"] = "Un problème est survenu avec votre configuration E2E, veuillez contacter le support.",
        ["chat.seen_suffix"] = " · vu",
        ["chat.send"] = "Envoyer",
        ["chat.emoji_button"] = ":)",
        ["chat.system_notice_line1"] = "Ceci est un chat privé entre vous et {0}. Ce chat est chiffré de bout en bout, l'équipe d'AetherLove ne peut pas lire vos messages. En haut à droite, vous trouverez un menu pour annuler la correspondance, bloquer ou signaler votre correspondance.",
        ["chat.system_notice_line2"] = "N'oubliez pas : {0} ne connaît pas votre nom complet ni votre localisation tant que vous ne les partagez pas. Prenez soin de votre vie privée et ne partagez davantage que lorsque vous êtes prêt.",
        ["chat.i_understand"] = "J'ai compris",
        ["chat.report_title"] = "Signaler l'utilisateur",
        ["chat.report_reason_prompt"] = "Veuillez décrire la raison de votre signalement :",
        ["chat.report_agree"] = "J'accepte de soumettre un signalement à l'encontre de {0}",
        ["chat.report_agree_contents"] = "J'accepte d'envoyer le contenu de cette conversation à l'équipe d'AetherLove",
        ["chat.submitting"] = "Envoi…",
        ["chat.submit"] = "Envoyer",

        // Verify encryption
        ["verify.title"] = "Vérifier le chiffrement",
        ["verify.intro"] = "AetherLove chiffre cette conversation de bout en bout : vous seul et {0} pouvez la lire, pas même notre équipe. Le motif tissé ci-dessous est généré à partir de vos deux clés de chiffrement.",
        ["verify.unavailable"] = "La vérification n'est pas encore prête. Elle sera disponible une fois que vous aurez tous les deux configuré le chiffrement et échangé vos clés.",
        ["verify.how"] = "Si {0} voit exactement le même motif et le même code sur son écran, personne n'intercepte votre conversation. Comparez-les par chat vocal ou en personne. S'ils ne correspondent pas, ne partagez plus rien de sensible et contactez le support.",
        ["verify.your_key"] = "Votre clé publique",
        ["verify.their_key"] = "Clé publique de {0}",
        ["verify.keys_explain"] = "Les clés publiques peuvent être partagées sans risque ; c'est ainsi que vos applications se reconnaissent. Les clés privées correspondantes ne quittent jamais vos appareils, donc aucun serveur (pas même le nôtre) ne peut lire vos messages.",
        ["verify.back"] = "Retour au chat",

        // ChatListScreen
        ["chat.preview_me_prefix"] = "Moi : ",
        ["chat.preview_venue"] = "A partagé un établissement",
        ["chat.matches_title"] = "Correspondances",
        ["chat.show_search"] = "Afficher la recherche",
        ["chat.hide_search"] = "Masquer la recherche",
        ["chat.search_hint"] = "Nom ou message",
        ["chat.searching"] = "Recherche en cours…",
        ["chat.search_no_results"] = "Aucun résultat trouvé",
        ["chat.matches_load_error"] = "Impossible de charger les correspondances : {0}",
        ["chat.connectivity_error"] = "Impossible de se connecter au serveur AetherLove. Veuillez réessayer ou consulter Discord pour voir l'état du serveur.",
        ["chat.empty_state"] = "Vous n'avez pas encore de correspondances — mais cela changera bientôt. Continuez à swiper !",
        ["chat.new_match"] = "nouvelle correspondance",
        ["chat.say_hi"] = "Vous avez un match — dites bonjour !",
        ["chat.time_ago_minutes"] = "il y a {0} min",
        ["chat.time_ago_hours"] = "il y a {0} h",
        ["chat.time_ago_days"] = "il y a {0} j",

        // added after update (1.3.1)
        ["chat.you"] = "Vous",
        ["chat.reply"] = "Répondre",
        ["chat.pin_message"] = "Épingler le message",
        ["chat.unpin_message"] = "Détacher le message",
        ["chat.pinned_messages"] = "Messages épinglés",
        ["chat.pinned_messages_menu"] = "Messages épinglés ({0})",
        ["chat.quote_unavailable"] = "(message d'origine indisponible)",
        ["chat.quote_generic"] = "(message)",
        ["chat.replying_to"] = "Réponse à {0}",
        ["chat.reaction_remove_hint"] = "cliquez pour retirer",
        ["chat.jump"] = "Aller",
        ["chat.unpin"] = "Détacher",

        // added after update 1.4.3
        ["chat.menu_search"] = "Rechercher des messages",
        ["chat.search_messages_hint"] = "Rechercher dans cette conversation...",
        ["chat.category_new"] = "Nouvelle catégorie",
        ["chat.category_edit"] = "Modifier la catégorie",
        ["chat.category_delete"] = "Supprimer la catégorie",
        ["chat.category_delete_body"] = "Voulez-vous vraiment supprimer {0} ? Les conversations qu'elle contient reviendront dans votre liste de correspondances.",
        ["chat.category_delete_confirm"] = "Supprimer",
        ["chat.category_name_hint"] = "Nom de la catégorie",
        ["chat.category_create"] = "Créer",
        ["chat.category_save"] = "Enregistrer",
        ["chat.menu_move_to_category"] = "Déplacer vers une catégorie",
        ["chat.menu_remove_from_category"] = "Retirer de la catégorie",
        ["chat.category_empty"] = "Aucune conversation dans cette catégorie pour l'instant. Glissez-y une conversation ou faites un clic droit sur une conversation et choisissez Déplacer vers une catégorie.",
        ["chat.category_count"] = "Conversations : {0}",
        ["chat.category_archive_default"] = "Archives",
        ["chat.all_categorized"] = "Toutes vos conversations sont rangées dans des catégories",

        // added after update 1.5.1
        ["chat.menu_view_blocked"] = "Voir les bloqués",
        ["blocked.title"] = "Utilisateurs bloqués",
        ["blocked.intro_body"] = "Vous pouvez débloquer ici les profils que vous avez bloqués par le passé. En débloquant quelqu'un, aucun match automatique n'est recréé, mais vous pourrez à nouveau vous croiser dans le deck.",
        ["blocked.empty"] = "Vous n'avez bloqué personne.",
        ["blocked.loading"] = "Chargement...",
        ["blocked.since"] = "Bloqué le {0}",
        ["blocked.unblock"] = "Débloquer",
        ["blocked.confirm_title"] = "Débloquer {0} ?",
        ["blocked.confirm_body"] = "Aucun match automatique ne sera recréé, mais vous pourrez à nouveau vous croiser dans le deck.",
    };
}
