namespace AetherLove.Services.Localization;

internal static class PlacesFr
{
    public static readonly System.Collections.Generic.Dictionary<string, string> Strings = new()
    {
        // added after update 1.5.0
        ["places.title"] = "Lieux",
        ["places.load_failed"] = "Impossible de charger les Lieux : {0}",
        ["places.happening_now"] = "Ouvert en ce moment",
        ["places.this_week"] = "Cette semaine",
        ["places.nothing_upcoming"] = "Aucune ouverture prévue cette semaine.",
        ["places.empty"] = "Aucun établissement ne correspond à vos filtres.",
        ["places.empty_hint"] = "Essayez d'élargir vos filtres de Lieux.",
        ["places.today"] = "Aujourd'hui",
        ["places.tomorrow"] = "Demain",
        ["places.live"] = "EN DIRECT",
        ["places.ends_in"] = "Se termine dans {0}",
        ["places.going"] = "{0} participants",
        ["places.back"] = "Retour",

        ["places.filters_title"] = "Filtres des Lieux",
        ["places.filters_tags"] = "Afficher les établissements avec le tag",
        ["places.filters_regions"] = "Régions",
        ["places.filters_hint"] = "Sans sélection, tout est affiché. Ces filtres sont indépendants de vos préférences de matching.",
        ["places.filters_apply"] = "Appliquer",

        ["places.tag_rp_venue"] = "Lieu de roleplay",
        ["places.tag_barding"] = "Musique de barde",
        ["places.tag_nsfw"] = "Établissement 18+",
        ["places.tag_live_dj"] = "DJ en direct",
        ["places.tag_sync"] = "Sync activé",
        ["places.tag_nightclub"] = "Boîte de nuit",
        ["places.tag_bar_tavern"] = "Bar / Taverne",
        ["places.tag_cafe"] = "Café",
        ["places.tag_restaurant"] = "Restaurant",
        ["places.tag_casino"] = "Casino",
        ["places.tag_maid_cafe"] = "Maid café",
        ["places.tag_bathhouse"] = "Bains publics",
        ["places.tag_gpose_studio"] = "Studio gpose",
        ["places.tag_live_music"] = "Musique en direct",
        ["places.tag_market"] = "Marché / Boutique",

        ["places.day_mon"] = "Lun",
        ["places.day_tue"] = "Mar",
        ["places.day_wed"] = "Mer",
        ["places.day_thu"] = "Jeu",
        ["places.day_fri"] = "Ven",
        ["places.day_sat"] = "Sam",
        ["places.day_sun"] = "Dim",

        ["places.location_ward"] = "Secteur {0}",
        ["places.location_plot"] = "Parcelle {0}",
        ["places.location_room"] = "Chambre {0}",

        ["places.schedule"] = "Horaires d'ouverture",
        ["places.rsvp"] = "Participer",
        ["places.rsvp_going"] = "J'y vais ✓",

        ["places.reviews_title"] = "Avis",
        ["places.no_reviews"] = "Pas encore d'avis — soyez le premier !",
        ["places.no_rating_yet"] = "Pas encore de notes.",
        ["places.rating_summary"] = "{0} · {1} avis",
        ["places.write_review"] = "Écrire un avis",
        ["places.your_review"] = "Votre avis",
        ["places.review_pending"] = "Votre avis attend la modération et n'est visible que par vous.",
        ["places.review_submit"] = "Publier l'avis",
        ["places.review_update"] = "Mettre à jour l'avis",
        ["places.review_delete"] = "Supprimer",
        ["places.review_delete_title"] = "Supprimer l'avis ?",
        ["places.review_delete_body"] = "Votre note et votre texte seront supprimés définitivement.",
        ["places.reviews_more"] = "Charger plus d'avis",

        ["places.menu_my_venues"] = "Mes établissements",
        ["places.my_venues"] = "Mes établissements",
        ["places.my_venues_empty"] = "Vous n'avez pas encore créé d'établissement. Créez-en un pour apparaître dans les Lieux !",
        ["places.venue_saved"] = "Établissement enregistré.",
        ["places.new_venue"] = "+ Nouvel établissement",
        ["places.venue_cap"] = "Vous avez atteint la limite de {0} établissements.",
        ["places.venue_stats"] = "{0} j'aime · {1} avis",
        ["places.venue_unlisted"] = "Masqué par la modération",
        ["places.back_to_venues"] = "Retour",
        ["places.new_venue_title"] = "Nouvel établissement",
        ["places.edit_venue_title"] = "Modifier l'établissement",

        ["places.section_details"] = "Détails",
        ["places.venue_name"] = "Nom de l'établissement",
        ["places.venue_description"] = "Description",
        ["places.section_tags"] = "Tags",
        ["places.section_location"] = "Emplacement",
        ["places.use_current_location"] = "Utiliser ma position actuelle",
        ["places.use_current_location_hint"] = "Placez-vous dans votre établissement pour tout remplir automatiquement.",
        ["places.venue_datacenter"] = "Centre de données",
        ["places.venue_world"] = "Monde",
        ["places.venue_ward"] = "Secteur",
        ["places.venue_plot"] = "Parcelle",
        ["places.venue_room"] = "Chambre",
        ["places.venue_room_hint"] = "Pour un appartement, mettez la parcelle à 0 et indiquez le numéro de chambre.",
        ["places.venue_timezone"] = "Fuseau horaire de l'établissement",
        ["places.venue_timezone_tip"] = "Les horaires ci-dessous sont saisis dans ce fuseau horaire. Les visiteurs les voient toujours convertis dans leur heure locale.",

        ["places.section_hours"] = "Horaires d'ouverture",
        ["places.hours_explainer"] = "Choisissez les jours, puis cliquez sur une heure de début et une heure de fin — les heures intermédiaires se remplissent automatiquement, même après minuit.",
        ["places.add_opening_time"] = "+ Ajouter un horaire",
        ["places.rule_weekly"] = "Hebdomadaire",
        ["places.rule_one_time"] = "Ponctuel",
        ["places.rule_date_hint"] = "Date (AAAA-MM-JJ)",
        ["places.rule_span"] = "Ouvert {0}",
        ["places.hours_pick_start"] = "Cliquez pour définir le début",
        ["places.hours_pick_end"] = "Cliquez pour définir la fin",

        ["places.section_images"] = "Images",
        ["places.image_banner"] = "Bannière",
        ["places.image_logo"] = "Image de l'établissement",
        ["places.image_banner_hint"] = "Bannière large (25:9). Affichée sur la page de votre établissement.",
        ["places.image_logo_hint"] = "Carrée (1:1). Affichée sur les cartes de l'établissement.",
        ["places.image_pick"] = "Choisir une image",
        ["places.image_ready"] = "Prête à enregistrer",
        ["places.image_remove"] = "Retirer",
        ["places.crop_banner"] = "Recadrer la bannière",
        ["places.crop_logo"] = "Recadrer l'image de l'établissement",

        ["places.err_name"] = "Donnez un nom à votre établissement (au moins 3 caractères).",
        ["places.err_location"] = "Renseignez le centre de données et le monde.",
        ["places.err_plot_or_room"] = "Indiquez un numéro de parcelle ou de chambre.",
        ["places.err_date"] = "Les ouvertures ponctuelles nécessitent une date au format AAAA-MM-JJ.",
        ["places.err_days"] = "Les ouvertures hebdomadaires nécessitent au moins un jour sélectionné.",
        ["places.save_venue"] = "Enregistrer l'établissement",
        ["places.delete_venue"] = "Supprimer l'établissement",
        ["places.delete_venue_title"] = "Supprimer l'établissement ?",
        ["places.delete_venue_body"] = "« {0} » et tous ses j'aime, avis et participations seront supprimés définitivement.",

        // added after update 1.5.1
        ["places.venue_region"] = "Région",
        ["places.venue_district"] = "Quartier",
        ["places.venue_dc_select"] = "Choisir un centre de données",
        ["places.venue_world_select"] = "Choisir un monde",
        ["places.venue_tz_select"] = "Choisir un fuseau horaire",
        ["places.venue_tz_search"] = "Rechercher…",
        ["places.err_description"] = "Veuillez ajouter une description.",
        ["places.err_tags"] = "Veuillez choisir au moins un tag.",
        ["places.err_images"] = "Une bannière et un logo sont tous deux requis.",
        ["places.err_timezone"] = "Veuillez choisir un fuseau horaire.",
        ["places.err_hours"] = "Veuillez ajouter au moins un horaire d'ouverture.",
        ["places.section_rsvpd"] = "Vos participations",
        ["places.duration_hm"] = "{0} h {1} min",
        ["places.duration_m"] = "{0} min",
        ["places.filters_nsfw"] = "Établissements 18+",
        ["places.reset_filters"] = "Réinitialiser les filtres",
        ["places.menu_filter"] = "Filtrer",
        ["places.menu_search"] = "Rechercher",
        ["places.search_hint"] = "Rechercher des établissements…",
        ["places.no_search_results"] = "Aucun établissement ne correspond à votre recherche.",
        ["places.open_now"] = "Ouvert maintenant !",
        ["places.show_all_tags"] = "Afficher tous les tags",
        ["places.no_reviews_owner"] = "Pas encore d'avis.",
        ["places.image_extra_banner"] = "Bannière du carrousel {0}",
        ["places.venue_pending"] = "En attente de modération",
        ["places.menu_addvenue"] = "Ajouter mon établissement",
        ["places.addvenue_title"] = "Ajoutez votre établissement",
        ["places.addvenue_intro"] = "Vous tenez un établissement ? AetherLove Lieux le présente aux joueurs directement dans le jeu, et l'inscription est 100% gratuite. Pas de frais, pas d'offres payantes, pas de piège.",
        ["places.addvenue_perks_header"] = "Pourquoi inscrire votre établissement ?",
        ["places.addvenue_perk_reviews_title"] = "Notes et commentaires",
        ["places.addvenue_perk_reviews_body"] = "Les visiteurs peuvent noter votre établissement et laisser des commentaires : un excellent moyen de vous faire connaître, de bâtir une réputation et de recevoir des avis sincères.",
        ["places.addvenue_perk_reach_title"] = "Touchez les joueurs en jeu",
        ["places.addvenue_perk_reach_body"] = "Votre établissement, ses horaires et ses événements en direct apparaissent là où les joueurs se trouvent déjà : dans le jeu.",
        ["places.addvenue_perk_share_title"] = "Partageable dans les discussions",
        ["places.addvenue_perk_share_body"] = "Les joueurs peuvent partager votre établissement entre eux directement dans leurs discussions AetherLove.",
        ["places.addvenue_how_heading"] = "Comment obtenir l'accès",
        ["places.addvenue_how_body"] = "Les rôles d'établissement sont attribués via notre Discord. Rejoignez le serveur et ouvrez un ticket de support pour demander l'accès établissement ; une fois accordé, l'éditeur Mes établissements se débloque sur votre profil.",
        ["places.addvenue_discord_btn"] = "Rejoignez notre Discord",
        ["places.addvenue_ticket_note"] = "Sur le Discord, ouvrez un ticket de support et demandez l'accès établissement. Cela ne prend qu'un instant et c'est entièrement gratuit.",
        ["places.share"] = "Partager",
        ["places.share_title"] = "Partager l'établissement",
        ["places.share_search_hint"] = "Rechercher parmi vos matchs…",
        ["places.share_send"] = "Partager",
        ["places.share_no_matches"] = "Aucun match trouvé.",
        ["places.share_loading"] = "Chargement de l'établissement…",
        ["places.share_unavailable"] = "Cet établissement n'est plus disponible.",
        ["places.share_view"] = "Voir l'établissement",
        ["places.back_to_chat"] = "Retour à la discussion",

        ["places.hide_venue"] = "Masquer cette venue",
        ["places.hide_intro_title"] = "Masquer des venues",
        ["places.hide_intro_body"] = "Ceci masque une venue de votre aperçu Places. Elle n'est masquée que pour vous, sur cet appareil. Vous pouvez récupérer les venues masquées à tout moment via le menu en haut de cette page.",
        ["places.hide_intro_note"] = "Rien n'a été masqué pour l'instant. La prochaine fois, la venue disparaîtra immédiatement.",
        ["places.menu_hidden"] = "Venues masquées ({0})",
        ["places.hidden_title"] = "Venues masquées",
        ["places.unhide"] = "Afficher",

        // added after update 1.6.0
        ["places.tag_247"] = "Établissement 24h/24",
        ["places.filters_247"] = "Afficher les établissements 24h/24",
        ["places.tag_lgbtq"] = "LGBTQ+",
        ["places.tag_minigames"] = "Mini-jeux",
    };
}
