namespace AetherLove.Services.Localization;

internal static class OnboardingEn
{
    public static readonly System.Collections.Generic.Dictionary<string, string> Strings = new()
    {
        // Header / navigation (OnboardingScreen.cs)
        ["onboarding.header_welcome"] = "Welcome!",
        ["onboarding.header_how_it_works"] = "How It Works",
        ["onboarding.header_terms_of_service"] = "Terms of Service",
        ["onboarding.header_sign_in"] = "Sign In",
        ["onboarding.header_secure_messages"] = "Secure Your Messages",
        ["onboarding.header_your_profile"] = "Your Profile",
        ["onboarding.header_profile_picture"] = "Profile Picture",
        ["onboarding.header_your_photos"] = "Your Photos",
        ["onboarding.header_optional_details"] = "Optional Details",
        ["onboarding.header_match_preferences"] = "Match Preferences",
        ["onboarding.header_make_it_yours"] = "Make It Yours",
        ["onboarding.header_all_set"] = "You're All Set!",
        ["onboarding.header_default"] = "AetherLove",

        ["onboarding.save_failed"] = "Save failed: {0}",
        ["onboarding.back"] = "← Back",
        ["onboarding.saving"] = "Saving…",
        ["onboarding.start_swiping"] = "Start Swiping →",
        ["onboarding.finish"] = "Finish →",
        ["onboarding.retry"] = "Retry →",
        ["onboarding.next"] = "Next →",
        ["onboarding.could_not_assemble"] = "Could not assemble {0}: {1}",
        ["onboarding.select_photo"] = "Select Photo",
        ["onboarding.image_files"] = "Image files",
        ["onboarding.crop_avatar"] = "Crop Avatar",
        ["onboarding.crop_main_photo"] = "Crop Main Photo",
        ["onboarding.crop_extra_photo"] = "Crop Extra Photo {0}",

        // Step 2 — How It Works
        ["onboarding.how_intro"] = "Here's how AetherLove works — from building your profile to chatting with your first match.",
        ["onboarding.how1_title"] = "Build Your Profile",
        ["onboarding.how1_body"] = "Tell us about your character — your race, server, languages, and what you're looking for. Upload a portrait photo. This is your calling card.",
        ["onboarding.how2_title"] = "Browse the Deck",
        ["onboarding.how2_body"] = "Every time you open the deck you'll see a stack of profile cards. Swipe right (or tap ♥) to express interest. Swipe left (or tap X) to pass.",
        ["onboarding.how3_title"] = "Set Your Preferences",
        ["onboarding.how3_body"] = "Choose the race, region, languages, and interests you'd like to find in a match. The more specific you are, the better the matches you'll be shown.",
        ["onboarding.how4_title"] = "Match!",
        ["onboarding.how4_body"] = "When two people both swipe right on each other it becomes a Match. You'll get a notification and a private chat opens automatically.",
        ["onboarding.how5_title"] = "Chat In-Game",
        ["onboarding.how5_body"] = "Send messages directly through the plugin — no external app needed. Your conversations are end-to-end encrypted, so not even the AetherLove developers can read your chats.",
        ["onboarding.how6_title"] = "Stay In Control",
        ["onboarding.how6_body"] = "Update your profile, adjust your preferences, or unmatch at any time from the Settings screen. AetherLove will NEVER share your full player name, location, or account information with other players.",
        ["onboarding.how_ready"] = "Ready to get started? Click Next to continue.",

        // Step 2 — Terms of Service
        ["onboarding.tos_p1"] = "AetherLove is a social matchmaking plugin for Final Fantasy XIV intended for adult users. By continuing, you confirm that you are at least 18 years of age and consent to participate in an adult social platform.",
        ["onboarding.tos_p2"] = "I understand that profile information I provide — including my display name, bio, home server, character details, and any photos I upload — may be visible to other AetherLove users. I am responsible for the accuracy of my profile and for ensuring that any photos I upload are appropriate and that I have the right to share them.",
        ["onboarding.tos_p3"] = "I agree to interact respectfully with all other users. Harassment, unsolicited explicit content, hate speech, or any form of abuse toward other users is strictly prohibited. Violation of these terms may result in removal from the platform without notice or appeal.",
        ["onboarding.tos_p4"] = "I understand that AetherLove is an unofficial, community-made plugin and is not affiliated with or endorsed by Square Enix Co., Ltd. It is provided as-is, with no guarantees of availability, data security, or fitness for any purpose. The plugin developers are not responsible for the actions of other users or for any consequences arising from use of this plugin.",
        ["onboarding.tos_p5"] = "Moderation decisions — including warnings, temporary suspensions, and permanent bans — are made at the sole discretion of the AetherLove staff. Staff have the final say in all moderation matters. Decisions need not be explained or justified to the affected user, and are not subject to appeal unless explicitly stated otherwise by staff.",
        ["onboarding.tos_p6"] = "We love and enjoy Lalafell characters as much as anyone, but adult and NSFW features are not available to players whose character race is Lalafell. Because Lalafells are child-like in appearance, we make no case-by-case distinction and apply this policy uniformly to every Lalafell account. The 18+ Roleplaying option, the NSFW opt-in, and NSFW photo uploads are all disabled while your race is set to Lalafell. Attempting to bypass this restriction is grounds for account removal.",
        ["onboarding.tos_p7"] = "I acknowledge that these terms may be updated at any time. Continued use of AetherLove after an update constitutes acceptance of the revised terms.",
        ["onboarding.tos_read_carefully"] = "READ CAREFULLY",
        ["onboarding.tos_accepted"] = "Terms accepted — press Next to continue.",
        ["onboarding.tos_timer"] = "Please read carefully — agree button available in {0}s",
        ["onboarding.tos_scroll_bottom"] = "Scroll to the bottom to accept.",
        ["onboarding.tos_i_agree"] = "I Agree",

        // Step 3 — XIVAuth
        ["onboarding.auth_signin_with_xivauth"] = "Sign in with XIVAuth",
        ["onboarding.auth_intro"] = "AetherLove uses XIVAuth to verify your identity as an active Final Fantasy XIV player. No password is required — authentication is handled securely through your game client.",
        ["onboarding.auth_contacting"] = "Contacting AetherLove",
        ["onboarding.auth_dont_have_xivauth"] = "Don't have XIVAuth?",
        ["onboarding.auth_xivauth_explainer"] = "XIVAuth is a free, community-run single sign-on for Final Fantasy XIV tools. It confirms you're a real FFXIV player by linking your Lodestone character — without ever sharing your Square Enix password. Signing up takes only a minute.",
        ["onboarding.auth_create_account"] = "Create a XIVAuth account",
        ["onboarding.auth_complete_in_browser"] = "Complete sign-in in your browser",
        ["onboarding.auth_browser_opened"] = "A browser window has opened. Finish signing in with XIVAuth and return here — this step will continue automatically.",
        ["onboarding.auth_open_browser_again"] = "Open browser again",
        ["onboarding.auth_cancel"] = "Cancel",
        ["onboarding.auth_loading_profile"] = "Signed in! Loading your profile",
        ["onboarding.auth_signed_in"] = "Signed in!",
        ["onboarding.auth_welcome_back"] = "Welcome back!",
        ["onboarding.auth_welcome_back_named"] = "Welcome back, {0}!",
        ["onboarding.auth_details_loaded"] = "We've loaded your details — you can start swiping right away.",
        ["onboarding.auth_timeout"] = "Sign-in took too long. Please try again.",
        ["onboarding.auth_failed"] = "Sign-in failed.",
        ["onboarding.auth_try_again"] = "Try again",

        // Step 3a — Passphrase
        ["onboarding.pass_heading"] = "Secure your messages",
        ["onboarding.pass_intro"] = "AetherLove staff cannot read your private messages — not now, not ever. To make that possible, we encrypt every message using a key that only YOU know. Set a passphrase below. A passphrase is just like a password, but one you must remember and save — there is no \"forgot my passphrase\" button. Write it down, store it in a password manager, do whatever you'd do for a critical password.",
        ["onboarding.pass_warning"] = "If you use AetherLove on a different computer — or buy a new computer — you will need to enter this passphrase again to read your chats. Without it, your messages are unreadable even to you.",
        ["onboarding.pass_label"] = "Passphrase",
        ["onboarding.pass_confirm_label"] = "Confirm passphrase",
        ["onboarding.pass_err_empty"] = "Please enter a passphrase.",
        ["onboarding.pass_err_too_short"] = "Passphrase must be at least {0} characters.",
        ["onboarding.pass_err_confirm_empty"] = "Please confirm your passphrase.",
        ["onboarding.pass_err_mismatch"] = "Passphrases don't match.",
        ["onboarding.pass_ack"] = "I understand my chat history cannot be recovered if I forget this passphrase.",
        ["onboarding.pass_securing"] = "Securing your keys…",
        ["onboarding.pass_strength_too_weak"] = "Too weak",
        ["onboarding.pass_strength_weak"] = "Weak",
        ["onboarding.pass_strength_ok"] = "OK",
        ["onboarding.pass_strength_good"] = "Good",
        ["onboarding.pass_strength_strong"] = "Strong",

        // Step 4 — Profile (data labels)
        ["onboarding.region_na"] = "North America (NA)",
        ["onboarding.region_eu"] = "Europe (EU)",
        ["onboarding.region_oceania"] = "Oceania",
        ["onboarding.region_japan"] = "Japan",
        ["onboarding.region_prefer_not_to_say"] = "Prefer not to say",
        ["onboarding.race_hyur"] = "Hyur",
        ["onboarding.race_elezen"] = "Elezen",
        ["onboarding.race_lalafell"] = "Lalafell",
        ["onboarding.race_miqote"] = "Miqo'te",
        ["onboarding.race_roegadyn"] = "Roegadyn",
        ["onboarding.race_au_ra"] = "Au Ra",
        ["onboarding.race_hrothgar"] = "Hrothgar",
        ["onboarding.race_viera"] = "Viera",
        ["onboarding.gender_male"] = "Male",
        ["onboarding.gender_female"] = "Female",
        ["onboarding.content_housing"] = "Housing & decoration",
        ["onboarding.content_music_bard"] = "Music & Bard performance",
        ["onboarding.content_rp_venues"] = "Visiting Roleplaying Venues",
        ["onboarding.content_club_venues"] = "Visiting Club Venues",
        ["onboarding.content_gpose"] = "Gpose",
        ["onboarding.content_story_lore"] = "Story & Lore",
        ["onboarding.content_roulettes"] = "Roulettes",
        ["onboarding.content_regular"] = "Regular content",
        ["onboarding.content_extreme_trials"] = "Extreme Trials",
        ["onboarding.content_savage"] = "Savage raiding",
        ["onboarding.content_pvp"] = "PvP",
        ["onboarding.content_blue_mage"] = "Blue Mage",
        ["onboarding.content_triple_triad"] = "Triple Triad",
        ["onboarding.content_mahjong"] = "Mahjong",
        ["onboarding.content_treasure_hunts"] = "Treasure Hunts",
        ["onboarding.content_crafting_gathering"] = "Crafting & Gathering",
        ["onboarding.content_fishing"] = "Fishing",
        ["onboarding.content_achievement_hunting"]= "Achievement Hunting",
        ["onboarding.lf_chatting"] = "Chatting to new people",
        ["onboarding.lf_casual_buddies"] = "Casual play buddies",
        ["onboarding.lf_gpose_glamour"] = "GPose and glamour partners",
        ["onboarding.lf_romance"] = "An in-game romance",
        ["onboarding.lf_long_term"] = "A long-term in-game relationship",
        ["onboarding.lf_rp_partners"] = "Roleplaying partners",
        ["onboarding.lf_erp"] = "18+ Roleplaying (ERP)",

        // Step 4 — Profile (body)
        ["onboarding.profile_intro"] = "These fields appear on your public profile card and are used to suggest matches.",
        ["onboarding.profile_identity"] = "Identity",
        ["onboarding.profile_display_name"] = "Display Name",
        ["onboarding.profile_display_name_tip"] = "The name other users see. Use your first name or an alias.\nNo spaces allowed.",
        ["onboarding.profile_display_name_hint"] = "First name or alias, no spaces.",
        ["onboarding.profile_about_me"] = "About me",
        ["onboarding.profile_about_me_tip"] = "Write a short intro. What do you enjoy?\nWhat kind of connections are you looking for?",
        ["onboarding.profile_char_count"] = "{0} / 500 characters",
        ["onboarding.profile_preview"] = "Preview",
        ["onboarding.profile_bio_placeholder"] = "Your bio will appear here…",
        ["onboarding.profile_location"] = "Location",
        ["onboarding.profile_server_region"] = "Server Region",
        ["onboarding.profile_server_region_tip"] = "Select your Final Fantasy XIV region.\nThis helps match you with nearby players.",
        ["onboarding.profile_character"] = "Character",
        ["onboarding.profile_race"] = "Race",
        ["onboarding.profile_gender"] = "Gender",
        ["onboarding.profile_languages_speak"] = "Languages I Speak",
        ["onboarding.profile_languages_hint"] = "Select every language you are comfortable chatting in.",
        ["onboarding.profile_content_heading"] = "I Enjoy the Following Content",
        ["onboarding.profile_content_hint"] = "Select everything that applies — this appears on your profile card.",
        ["onboarding.profile_looking_for_heading"]= "I Am Looking For",
        ["onboarding.profile_looking_for_hint"] = "Select everything that applies (at least one is required). Being honest helps find better matches.",
        ["onboarding.profile_erp_enables_nsfw"] = "    Selecting this automatically enables NSFW for your profile.",
        ["onboarding.profile_nsfw_heading"] = "NSFW",
        ["onboarding.profile_nsfw_lalafell"] = "Adult and NSFW features are not available while your race is set to Lalafell. See the Terms of Service for details.",
        ["onboarding.profile_nsfw_explainer"] = "NSFW stands for \"Not Safe For Work\" — content that contains nudity or sexual themes. Do you want to opt-in to NSFW profiles? This will result in potential matches with players who have uploaded NSFW pictures to their profile. These images are always blurred until you choose to reveal them.",
        ["onboarding.profile_nsfw_checkbox"] = "NSFW Profiles: YES",
        ["onboarding.profile_nsfw_locked"] = "Locked on because you selected 18+ Roleplaying (ERP). Uncheck that to change this setting.",
        ["onboarding.profile_timezone"] = "Timezone",
        ["onboarding.profile_timezone_hint"] = "Shown to potential matches so they know when you're active.",

        // Step 5 — Avatar
        ["onboarding.avatar_heading"] = "Your Profile Picture",
        ["onboarding.avatar_intro"] = "Your profile picture is shown in the chat and during matching. We require a square image that contains a picture of your FFXIV character's face.",
        ["onboarding.avatar_tip"] = "Tip: a close-up portrait G-Pose screenshot works best.",
        ["onboarding.avatar_sfw_warning"] = "Your main profile picture MUST be SFW. Uploading a NSFW picture is reason for account deletion.",
        ["onboarding.avatar_browse"] = "Browse…",
        ["onboarding.avatar_crop_hint"] = "The crop editor opened in a separate window.\nClick \"Use this crop\" there to confirm your avatar.",
        ["onboarding.avatar_no_image"] = "No image selected yet.",
        ["onboarding.avatar_set"] = "Profile picture set!",
        ["onboarding.avatar_change_photo"] = "Change photo",
        ["onboarding.avatar_its_a_match"] = "It's a Match!",
        ["onboarding.avatar_match_preview_caption"] = "Preview: how your avatar appears on match cards",

        // Step 5 — Image Disclaimer
        ["onboarding.disclaimer_intro"] = "AetherLove is built for Final Fantasy XIV players. Before uploading any images, please read the following guidelines carefully.",
        ["onboarding.disclaimer_moderation"] = "All uploads are subject to both automated and manual moderation.",
        ["onboarding.disclaimer_general_heading"] = "General",
        ["onboarding.disclaimer_general_body"] = "All images uploaded to AetherLove must depict your Final Fantasy XIV character. Images unrelated to Final Fantasy XIV characters will be rejected without notice.",
        ["onboarding.disclaimer_profile_images_heading"] = "Profile Images",
        ["onboarding.disclaimer_profile_images_body"] = "Images displayed on your profile must be screenshots or G-Poses of your own Final Fantasy XIV character. The following are:",
        ["onboarding.disclaimer_not_allowed"] = "NOT ALLOWED:",
        ["onboarding.disclaimer_na_fan_art"] = "Fan art",
        ["onboarding.disclaimer_na_3d_renders"] = "Custom 3D renders",
        ["onboarding.disclaimer_na_ai"] = "AI-generated images",
        ["onboarding.disclaimer_na_real_photos"] = "Photographs of real people or places",
        ["onboarding.disclaimer_na_unrelated"] = "Any image unrelated to your FFXIV character",
        ["onboarding.disclaimer_nsfw_heading"] = "NSFW Content",
        ["onboarding.disclaimer_nsfw_body1"] = "Your primary avatar and your main profile picture must be Safe For Work (SFW). A simple rule of thumb: if you would be comfortable showing the image to a manager or colleague, it is acceptable as a primary image.",
        ["onboarding.disclaimer_nsfw_body2"] = "Additional profile photos may contain NSFW content, but must be explicitly marked as such when uploading. We strongly encourage keeping as many images SFW as possible.",
        ["onboarding.disclaimer_rules_heading"] = "What Happens If an Image Breaks the Rules?",
        ["onboarding.disclaimer_rules_body1"] = "If one of your images is found to violate these guidelines, you will receive a notification. The image will be removed automatically and your profile will be placed on hold — shadowbanned — until you correct the issue.",
        ["onboarding.disclaimer_rules_body2"] = "Uploading content that is harmful, exploitative, or illegal will result in:",
        ["onboarding.disclaimer_permanent_ban"] = "A permanent account ban.",
        ["onboarding.disclaimer_continue"] = "I understand, continue",

        // Step 6 — Photos
        ["onboarding.photos_heading"] = "Profile photos",
        ["onboarding.photos_intro"] = "Add portrait photos to your profile (10:16 aspect ratio). The first slot is required; slots 2–4 are optional. For best results use images at least 480 × 768 px.",
        ["onboarding.photos_main_thumb"] = "Main",
        ["onboarding.photos_tap_slot"] = "Tap a slot above to add or manage a photo.",
        ["onboarding.photos_main_photo"] = "Main photo",
        ["onboarding.photos_extra_photo"] = "Extra photo {0}",
        ["onboarding.photos_main_sfw_warning"] = "Your main profile picture MUST be SFW. Uploading an NSFW picture is grounds for account suspension or deletion.",
        ["onboarding.photos_sfw_nsfw_question"] = "Is this picture SFW or NSFW?",
        ["onboarding.photos_mismatch_warning"] = "If our system detects you uploaded NSFW while SFW is selected, your photo will be held for moderation and you risk account suspension.",
        ["onboarding.photos_previously_uploaded"] = "Previously uploaded.",
        ["onboarding.photos_confirmed"] = "Photo confirmed.",
        ["onboarding.photos_remove"] = "Remove",
        ["onboarding.photos_browse"] = "Browse…",
        ["onboarding.photos_crop_hint"] = "The crop editor opened in a separate window.\nClick \"Use this crop\" there to confirm the photo.",
        ["onboarding.photos_required"] = "This photo is required.",
        ["onboarding.photos_optional"] = "This photo is optional.",

        // Step 7 — Optional
        ["onboarding.expansion_none"] = "(None)",
        ["onboarding.sync_none"] = "I don't use a sync tool",
        ["onboarding.opt_heading"] = "Tell us more about yourself",
        ["onboarding.opt_intro"] = "All fields on this page are optional. Fill in as much or as little as you like — these details appear on your profile card and help others find you.",
        ["onboarding.opt_fav_job"] = "Favourite Job",
        ["onboarding.opt_fav_job_tip"] = "The job or role you enjoy the most.\nType to filter.",
        ["onboarding.opt_fav_location"] = "Favourite Location",
        ["onboarding.opt_fav_location_tip"] = "A place in Eorzea you love to visit.\nType to filter.",
        ["onboarding.opt_location_unavailable"] = "(location data unavailable)",
        ["onboarding.opt_location_none"] = "(None)",
        ["onboarding.opt_fav_expansion"] = "Favourite Expansion",
        ["onboarding.opt_fav_expansion_tip"] = "Your all-time favourite FFXIV expansion.",
        ["onboarding.opt_fav_spotify"] = "Favourite Spotify Song",
        ["onboarding.opt_fav_spotify_tip"] = "Paste a Spotify track URL or track ID.\nThe track name is fetched automatically.",
        ["onboarding.opt_spotify_fetching"] = "Fetching track name…",
        ["onboarding.opt_spotify_track_id"] = "Track ID: {0}",
        ["onboarding.opt_spotify_fetch_failed"] = "(could not fetch title)",
        ["onboarding.opt_fav_movie"] = "Favourite Movie",
        ["onboarding.opt_fav_movie_tip"] = "Your all-time favourite film — any genre.",
        ["onboarding.opt_fav_anime"] = "Favourite Anime",
        ["onboarding.opt_fav_anime_tip"] = "Your favourite anime series or film.",
        ["onboarding.opt_fav_ff_character"] = "Favourite Final Fantasy Character",
        ["onboarding.opt_fav_ff_character_tip"] = "Any character from the Final Fantasy universe.",
        ["onboarding.opt_weekday_playtimes"] = "Weekday Playtimes (Mon–Fri)",
        ["onboarding.opt_weekday_playtimes_tip"] = "Click the hours you're typically online on weekdays.\nHover a bar to see the time.\nPlease choose your local time.",
        ["onboarding.opt_weekend_playtimes"] = "Weekend Playtimes (Sat–Sun)",
        ["onboarding.opt_weekend_playtimes_tip"] = "Click the hours you're typically online on weekends.\nHover a bar to see the time.\nPlease choose your local time.",
        ["onboarding.opt_sync_tool"] = "Sync tool used",
        ["onboarding.opt_sync_tool_tip"] = "Sync tools like Lightless or Honsefarm let matched users\nshare mod appearances automatically.",
        ["onboarding.time_am"] = "AM",
        ["onboarding.time_pm"] = "PM",

        // Step 8 — Filters
        ["onboarding.filters_intro"] = "Tell us who you'd like to match with. These preferences help us surface the right people for you — you can adjust them at any time in Settings.",
        ["onboarding.filters_heading"] = "I Wish to Match With",
        ["onboarding.filters_race"] = "Race",
        ["onboarding.filters_gender"] = "Gender",
        ["onboarding.filters_region"] = "Region",
        ["onboarding.filters_spoken_language"] = "Spoken Language",
        ["onboarding.filters_language_tip"] = "Leave all unchecked to match regardless of language spoken.",
        ["onboarding.filters_all"] = "All",
        ["onboarding.filters_none"] = "None",
        ["onboarding.filters_clear"] = "Clear",
        ["onboarding.filters_any_race"] = "  No selection — any race",
        ["onboarding.filters_any_gender"] = "  No selection — any gender",
        ["onboarding.filters_any_region"] = "  No selection — any region",
        ["onboarding.filters_any_language"] = "  No selection — no language preference",

        // Step 9 — Finished
        ["onboarding.finished_heading"] = "You're All Set!",
        ["onboarding.finished_intro"] = "Your profile has been created and your match preferences saved. You're ready to start connecting with other Final Fantasy XIV players.",
        ["onboarding.finished_verification_heading"] = "Profile Verification",
        ["onboarding.finished_verification_body"] = "Your profile will be reviewed by our moderation team within 24 hours. During this time your profile is fully active — you can browse, match, and chat right away.",
        ["onboarding.finished_verification_note"] = "We will only reach out if there is an issue with your profile or images.",
        ["onboarding.finished_swiping_heading"] = "Start Swiping",
        ["onboarding.finished_swiping_body"] = "Head to the Deck to browse profiles. Tap ♥ on someone you're interested in — when they tap ♥ back, it's a Match! A private chat opens automatically.",
        ["onboarding.finished_rejected_heading"] = "If an Image Is Rejected",
        ["onboarding.finished_rejected_body"] = "If any of your images violate our guidelines during review, you'll receive a notification. The image will be removed and you'll be asked to replace it. Your profile remains active in the meantime.",
        ["onboarding.finished_good_luck"] = "Good luck out there — AetherLove is rooting for you! ♥",

        // Step 10 — Preferences
        ["onboarding.prefs_intro"] = "Make AetherLove yours — pick a colour theme and a phone size. You can change both any time in Settings.",
        ["onboarding.prefs_theme"] = "Theme",
        ["onboarding.prefs_phone_size"] = "Phone size",
    };
}
