namespace AetherLove.Services.Localization;

internal static class ProfileFr
{
    public static readonly System.Collections.Generic.Dictionary<string, string> Strings = new()
    {
        // Profile
        ["profile.load_failed"] = "Impossible de charger le profil : {0}",
        ["profile.none_loaded"] = "Aucun profil chargé.",

        ["profile.about"] = "À propos",
        ["profile.flairs"] = "Badges",
        ["profile.looking_for"] = "Recherche",
        ["profile.content_interests"] = "Préférences de contenu",
        ["profile.info"] = "Infos",
        ["profile.gender"] = "Sexe",
        ["profile.languages"] = "Langues",
        ["profile.timezone"] = "Fuseau horaire",
        ["profile.favourite_job"] = "Job favori",
        ["profile.favourite_location"] = "Lieu favori",
        ["profile.favourite_expansion"] = "Extension favorite",
        ["profile.favourite_song"] = "Chanson favorite",
        ["music.fetching"] = "Récupération du nom de la chanson…",
        ["music.saved"] = "Lien enregistré (nom en attente)",
        ["music.invalid"] = "Impossible de lire ce lien — collez un lien de chanson Spotify, SoundCloud, Apple Music ou YouTube Music.",
        ["music.open_tooltip"] = "Cliquez pour ouvrir",
        ["profile.favourite_movie"] = "Film favori",
        ["profile.favourite_anime"] = "Anime favori",
        ["profile.favourite_ff_character"] = "Personnage FF favori",
        ["profile.sync_tool"] = "Outil de synchronisation",
        ["profile.weekday_playtimes"] = "Heures de jeu en semaine  (lun.–ven.)",
        ["profile.weekend_playtimes"] = "Heures de jeu le week-end  (sam.–dim.)",
        ["profile.timezone_value"] = "{0} (heure actuelle : {1})",

        ["profile.nsfw_reveal"] = "Cliquez pour afficher l'image NSFW",

        ["profile.back_to_chat"] = "Retour au chat",
        ["profile.back_to_swiping"] = "Retour au swipe",

        ["profile.report_profile"] = "Signaler le profil",
        ["profile.report_warning"] = "Les signalements faux ou malveillants entraînent des avertissements sur votre propre compte, et les abus répétés peuvent entraîner une suspension. Ne signalez que les profils qui enfreignent réellement les règles.",
        ["profile.report_prompt"] = "Indiquez à nos modérateurs ce qui ne va pas avec {0} :",
        ["profile.this_profile"] = "ce profil",
        ["profile.report_agree"] = "Je comprends que les faux signalements peuvent entraîner des avertissements sur mon compte.",
        ["profile.submitting"] = "Envoi…",
        ["profile.cancel"] = "Annuler",
        ["profile.submit_report"] = "Envoyer le signalement",
        ["profile.report_submitted"] = "Signalement envoyé",
        ["profile.report_thanks"] = "Merci — nos modérateurs vont y jeter un œil. Vous ne reverrez plus ce profil tant que vous n'en aurez pas tiré un nouveau du deck.",
        ["profile.closing"] = "Fermeture…",
        ["profile.closing_in"] = "Fermeture dans {0} secondes",
        ["profile.close"] = "Fermer",

        // ProfileScreen - copy profile text (viewing others only)
        ["profile.copy_text"] = "Copier le texte du profil",
        ["profile.copy_warning_title"] = "Avertissement",
        ["profile.copy_warning_body"] = "Vous venez de copier le texte de quelqu'un. Faites attention avant de cliquer sur les liens qu'il pourrait contenir ou de les suivre — vous le faites à vos propres risques.",
        ["profile.copy_warning_agree"] = "J'ai compris et j'accepte",

        // MyProfileScreen hub: stats + menu
        ["profile.section_myprofile"] = "Mon profil",
        ["profile.section_service"] = "Service",
        ["profile.menu_view"] = "Voir mon profil",
        ["profile.menu_edit"] = "Modifier le profil",
        ["profile.menu_images"] = "Photos de profil",
        ["profile.stat_loves_you"] = "vous aiment",
        ["profile.stat_matches"] = "Matchs",
        ["profile.stat_match_rate"] = "Taux de match",
        ["profile.back_to_my"] = "← Retour",

        ["profile.load_profile_failed"] = "Impossible de charger votre profil : {0}",
        ["profile.retry"] = "Réessayer",
        ["profile.saving"] = "Enregistrement…",
        ["profile.saved"] = "Enregistré  ✓",
        ["profile.save_changes"] = "Enregistrer les modifications",

        ["profile.heading_character"] = "Personnage",
        ["profile.heading_location"] = "Localisation",
        ["profile.heading_languages"] = "Langues que je parle",
        ["profile.heading_content"] = "J'apprécie le contenu suivant",
        ["profile.heading_looking_for"] = "Je recherche",
        ["profile.heading_nsfw"] = "NSFW",
        ["profile.heading_optional"] = "Facultatif",
        ["profile.heading_playtime"] = "Heures de jeu",
        ["profile.heading_timezone"] = "Fuseau horaire",
        ["profile.heading_sync_tool"] = "Outil de synchronisation",
        ["profile.heading_match_prefs"] = "Préférences de correspondance",

        ["profile.display_name"] = "Nom affiché",
        ["profile.about_me"] = "À propos de moi",
        ["profile.char_count"] = "{0} / 500 caractères",
        ["profile.preview"] = "Aperçu",
        ["profile.bio_placeholder"] = "Votre bio apparaîtra ici…",
        ["profile.race"] = "Race",
        ["profile.region"] = "Région",
        ["profile.languages_hint"] = "Sélectionnez toutes les langues dans lesquelles vous êtes à l'aise pour discuter.",
        ["profile.content_hint"] = "Sélectionnez tout ce qui s'applique.",
        ["profile.looking_for_hint"] = "Être honnête aide à trouver de meilleures correspondances.",
        ["profile.nsfw_lalafell"] = "Les fonctionnalités pour adultes et NSFW ne sont pas disponibles tant que votre race est définie sur Lalafell. Consultez les conditions d'utilisation pour plus de détails.",
        ["profile.nsfw_explainer"] = "NSFW signifie « Not Safe For Work » : du contenu comportant de la nudité ou des thèmes sexuels. Activez cette option pour voir des profils NSFW et y correspondre.",
        ["profile.nsfw_optin"] = "Profils NSFW : OUI",
        ["profile.favourite_job_tooltip"] = "Le job ou le rôle que vous appréciez le plus. Tapez pour filtrer.",
        ["profile.favourite_ff_character_full"] = "Personnage de Final Fantasy favori",
        ["profile.weekday_playtimes_edit"] = "Heures de jeu en semaine (lun.–ven.)",
        ["profile.weekend_playtimes_edit"] = "Heures de jeu le week-end (sam.–dim.)",
        ["profile.sync_tool_hint"] = "Les outils de synchronisation permettent aux utilisateurs en correspondance de partager les apparences de mods.",
        ["profile.match_prefs_body"] = "Dites-nous avec qui vous aimeriez correspondre. Ces préférences nous aident à vous présenter les bonnes personnes.",
        ["profile.all"] = "Tout",
        ["profile.none"] = "Aucun",
        ["profile.clear"] = "Effacer",
        ["profile.filter_any_race"] = "  Aucune sélection : toutes les races",
        ["profile.filter_any_gender"] = "  Aucune sélection : tous les sexes",
        ["profile.filter_any_region"] = "  Aucune sélection : toutes les régions",
        ["profile.filter_any_language"] = "  Aucune sélection : aucune préférence de langue",
        ["profile.spoken_language"] = "Langue parlée",
        ["profile.spoken_language_tooltip"] = "Ne cochez rien pour correspondre quelle que soit la langue.",
        ["profile.load_photos_failed"] = "Impossible de charger vos photos : {0}",
        ["profile.profile_picture"] = "Photo de profil",
        ["profile.profile_picture_desc"] = "Votre photo de profil est affichée dans la liste de chat et sur les fiches de match. Utilisez un portrait carré en gros plan de votre personnage FFXIV.",
        ["profile.profile_photos"] = "Photos de profil",
        ["profile.profile_photos_desc"] = "Ajoutez des portraits à votre profil (format 10:16). Le premier emplacement est obligatoire ; les emplacements 2 à 4 sont facultatifs.",
        ["profile.declare_before_save"] = "Marquez chaque photo supplémentaire comme SFW ou NSFW avant d'enregistrer.",

        ["profile.new_photo_ready"] = "Nouvelle photo prête, pas encore enregistrée.",
        ["profile.change_photo"] = "Changer de photo",
        ["profile.profile_picture_set"] = "Photo de profil : Définie  ✓",
        ["profile.no_profile_picture"] = "Aucune photo de profil définie.",
        ["profile.upload_avatar"] = "Envoyer un avatar…",

        ["profile.slot_main"] = "Principale",
        ["profile.tap_slot"] = "Touchez un emplacement ci-dessus pour ajouter ou changer une photo.",
        ["profile.main_photo"] = "Photo principale",
        ["profile.extra_photo"] = "Photo supplémentaire {0}",
        ["profile.photo_will_be_removed"] = "La photo sera supprimée.",
        ["profile.undo"] = "Annuler",
        ["profile.main_must_be_sfw"] = "Votre photo de profil principale DOIT être SFW. Envoyer une photo NSFW est un motif de suspension ou de suppression de compte.",
        ["profile.sfw_or_nsfw"] = "Cette photo est-elle SFW ou NSFW ?",
        ["profile.sfw_mismatch_warning"] = "Si notre système détecte que vous avez envoyé une image NSFW alors que SFW est sélectionné, votre photo sera mise en attente de modération et vous risquez une suspension de compte.",
        ["profile.photo_ready"] = "Photo prête, pas encore enregistrée.",
        ["profile.replace"] = "Remplacer",
        ["profile.photo_set"] = "Photo définie  ✓",
        ["profile.currently_nsfw"] = "Actuellement : NSFW",
        ["profile.currently_sfw"] = "Actuellement : SFW",
        ["profile.remove"] = "Supprimer",
        ["profile.photo_required"] = "Cette photo est obligatoire.",
        ["profile.photo_optional"] = "Cette photo est facultative.",
        ["profile.upload_photo"] = "Envoyer une photo…",

        ["profile.select_image"] = "Sélectionner une image",
        ["profile.image_files_filter"] = "Fichiers image",
        ["profile.crop_avatar"] = "Recadrer l'avatar",
        ["profile.crop_main_photo"] = "Recadrer la photo principale",
        ["profile.crop_extra_photo"] = "Recadrer la photo supplémentaire {0}",

        // added after update 1.4.3
        ["profile.menu_rp"] = "Mes profils RP",
        ["profile.rp_intro_title"] = "Mes profils RP",
        ["profile.rp_intro"] = "Ajoutez vos OCs FFXIV (personnages originaux) à votre profil. Chaque personnage a un nom, une courte histoire et une image optionnelle, et ils apparaissent sur votre profil pour que les autres les découvrent.",
        ["profile.characters"] = "Personnages",
        ["profile.rp_add"] = "Ajouter un personnage",
        ["profile.rp_empty"] = "Pas encore de personnages. Ajoutez votre premier OC ci-dessous !",
        ["profile.rp_limit_reached"] = "Vous pouvez ajouter jusqu'à {0} personnages.",
        ["profile.rp_name"] = "Nom / Titre",
        ["profile.rp_bio"] = "À propos de ce personnage",
        ["profile.rp_delete"] = "Supprimer",
        ["profile.rp_delete_confirm"] = "Vraiment supprimer ?",
        ["profile.rp_move_up"] = "Monter",
        ["profile.rp_move_down"] = "Descendre",
        ["profile.rp_image"] = "Image",
        ["profile.rp_upload_image"] = "Téléverser une image",
        ["profile.rp_replace_image"] = "Remplacer l'image",
        ["profile.rp_remove_image"] = "Retirer l'image",
        ["profile.rp_image_ready"] = "Image prête à enregistrer",
        ["profile.rp_image_nsfw"] = "Cette image est NSFW",
        ["profile.rp_image_expand"] = "Voir en taille réelle",
        ["profile.rp_image_back"] = "Retour au profil",
        ["profile.rp_crop_image"] = "Recadrer l'image du personnage",
        ["profile.rp_back"] = "Retour",
        ["profile.rp_details"] = "Détails du personnage :",

        // added after update 1.5.1
        ["profile.slot_locked"] = "Cet emplacement de photo nécessite un abonnement de soutien actif. Vous pouvez retirer la photo ou vous réabonner pour l'utiliser à nouveau.",
        ["profile.rp_extra_image"] = "Image supplémentaire {0} (soutien)",
        ["profile.section_supporter"] = "Soutien",
        ["profile.menu_sup_vanity"] = "Styles personnalisés",
        ["profile.menu_sup_stats"] = "Statistiques bonus",
        ["profile.sup_intro"] = "Merci de soutenir AetherLove ! Choisissez un style pour votre nom et décidez d'afficher ou non le badge de soutien. Tout le monde peut les voir.",
        ["profile.sup_name_style"] = "Style du nom",
        ["profile.sup_show_badge"] = "Afficher le badge de soutien",
        ["profile.sup_badge_hint"] = "Affiche le tag de soutien sur votre profil. L'étoile à côté de votre nom est toujours visible.",
        ["profile.sup_stats_intro"] = "Un aperçu réservé aux soutiens de la façon dont votre profil se porte à travers le royaume.",
        ["profile.sup_stat_likes_received"] = "Likes reçus",
        ["profile.sup_stat_superlikes"] = "Superlikes reçus",
        ["profile.sup_stat_views"] = "Vues du profil",
        ["profile.sup_stat_impressions"] = "Apparitions en deck",
        ["profile.sup_stat_likes_given"] = "Likes donnés",
        ["profile.sup_stat_passes_given"] = "Refus donnés",
        ["profile.sup_stat_matches"] = "Matchs",
        ["profile.sup_stat_like_rate"] = "Votre taux de like",
        ["profile.sup_stat_match_rate"] = "Votre taux de match",
        ["profile.style_none"] = "Par défaut",
        ["profile.style_crimson"] = "Cramoisi",
        ["profile.style_gold"] = "Or",
        ["profile.style_emerald"] = "Émeraude",
        ["profile.style_sapphire"] = "Saphir",
        ["profile.style_violet"] = "Violet",
        ["profile.style_rose"] = "Rose",
        ["profile.style_rainbow"] = "Arc-en-ciel (animé)",
        ["profile.style_shimmer"] = "Reflet doré (animé)",
        ["profile.style_pulse"] = "Pulsation rose (animé)",
    };
}
