namespace AetherLove.Services.Localization;

internal static class DeckEs
{
    public static readonly System.Collections.Generic.Dictionary<string, string> Strings = new()
    {
        ["deck.cooldown_heading"] = "¡Estás al día!",
        ["deck.cooldown_body"] = "AetherLove te ofrece una nueva tanda de perfiles cada pocas horas, para que todos tengan una oportunidad justa. ¡Vuelve pronto para ver nuevas coincidencias potenciales!",
        ["deck.new_matches_ready"] = "¡Hay nuevas coincidencias listas!",
        ["deck.server_error"] = "No se pudo conectar con el servidor: {0}",
        ["deck.view_profile"] = "Ver perfil",
        ["deck.like"] = "ME GUSTA",
        ["deck.nope"] = "PASO",
        ["deck.match_you"] = "Tú",
        ["deck.match_your_match"] = "Tu coincidencia",
        ["deck.match_congratulations"] = "¡Enhorabuena!",
        ["deck.match_its_a_match"] = "¡Es una coincidencia!",
        ["deck.match_fx_cosmic"] = "Dos almas, una misma órbita",
        ["deck.match_fx_synthwave"] = "Rumbo al atardecer, sin frenos",
        ["deck.match_fx_aurora"] = "La luz os unió",
        ["deck.match_fx_kaleido"] = "Encajáis a la perfección",
        ["deck.match_fx_supernova"] = "Vuestros corazones laten al unísono",
        ["deck.match_fx_vortex"] = "Atraídos a la misma órbita",
        ["deck.match_fx_portal"] = "Surgidos de la misma grieta",
        ["deck.match_fx_electric"] = "Saltan chispas",
        ["deck.match_fx_bubble"] = "Dos burbujas, un mismo brillo",
        ["deck.match_fx_dna"] = "Una pareja de bases perfecta.",
        ["deck.match_fx_firework"] = "Que el cielo lo celebre",
        ["deck.match_fx_vinyl"] = "En la misma sintonía",
        ["deck.match_fx_arcade_players"] = "* JUGADOR 1 *   * JUGADOR 2 *",
        ["deck.match_fx_arcade_score"] = "PUNTUACIÓN",
        ["deck.match_fx_constellation"] = "Escrito en las estrellas",
        ["deck.match_fx_slot"] = "Tres iguales",
        ["deck.match_fx_slot_title"] = "¡PREMIO GORDO!",
        ["deck.match_fx_tarot"] = "Las cartas se alinean — dos destinos entrelazados",
        ["deck.match_fx_tarot_title"] = "LOS ENAMORADOS",
        ["deck.match_fx_lavalamp"] = "Dos llamas, un mismo fulgor",
        ["deck.match_fx_lanterns"] = "Dos luces, un mismo cielo",
        ["deck.match_fx_treasure"] = "Un flechazo que vale su peso en oro",
        ["deck.match_fx_treasure_title"] = "TESORO ENCONTRADO",
        ["deck.match_start_chatting"] = "Empezar a chatear",
        ["deck.match_keep_swiping"] = "Seguir deslizando",
        ["deck.no_pool_heading"] = "Sin más coincidencias",
        ["deck.no_pool_body"] = "No se encontraron más coincidencias para ti con tus criterios actuales. Amplía tus criterios e inténtalo de nuevo más tarde.",
    };
}
