namespace AetherLove.Services.Localization;

internal static class ProfilePt
{
    public static readonly System.Collections.Generic.Dictionary<string, string> Strings = new()
    {
        // ProfileScreen — load / empty states
        ["profile.load_failed"] = "Não foi possível carregar o perfil: {0}",
        ["profile.none_loaded"] = "Nenhum perfil carregado.",

        // ProfileScreen — sections
        ["profile.about"] = "Sobre",
        ["profile.flairs"] = "Emblemas",
        ["profile.looking_for"] = "Procurando por",
        ["profile.content_interests"] = "Preferências de conteúdo",
        ["profile.info"] = "Informações",
        ["profile.gender"] = "Gênero",
        ["profile.languages"] = "Idiomas",
        ["profile.timezone"] = "Fuso horário",
        ["profile.favourite_job"] = "Job favorito",
        ["profile.favourite_location"] = "Lugar favorito",
        ["profile.favourite_expansion"] = "Expansão favorita",
        ["profile.favourite_song"] = "Música favorita",
        ["music.fetching"] = "Obtendo o nome da música…",
        ["music.saved"] = "Link salvo (nome pendente)",
        ["music.invalid"] = "Não foi possível ler o link — cole um link de música do Spotify, SoundCloud, Apple Music ou YouTube Music.",
        ["music.open_tooltip"] = "Clique para abrir",
        ["profile.favourite_movie"] = "Filme favorito",
        ["profile.favourite_anime"] = "Anime favorito",
        ["profile.favourite_ff_character"] = "Personagem favorito de FF",
        ["profile.sync_tool"] = "Ferramenta de sync",
        ["profile.weekday_playtimes"] = "Horários de jogo nos dias de semana  (Seg–Sex)",
        ["profile.weekend_playtimes"] = "Horários de jogo no fim de semana  (Sáb–Dom)",
        ["profile.timezone_value"] = "{0} (hora atual: {1})",

        // ProfileScreen — Spotify / NSFW pill
        ["profile.nsfw_reveal"] = "Clique para ver a imagem NSFW",

        // ProfileScreen — back pill
        ["profile.back_to_chat"] = "Voltar ao chat",
        ["profile.back_to_swiping"] = "Voltar a deslizar",

        // ProfileScreen — report flow
        ["profile.report_profile"] = "Denunciar perfil",
        ["profile.report_warning"] = "Denúncias falsas ou maliciosas geram advertências na sua própria conta, e abuso repetido pode resultar em suspensão. Só denuncie perfis que realmente violam as regras.",
        ["profile.report_prompt"] = "Diga aos nossos moderadores o que há de errado com {0}:",
        ["profile.this_profile"] = "este perfil",
        ["profile.report_agree"] = "Eu entendo que denúncias falsas podem resultar em advertências contra minha conta.",
        ["profile.submitting"] = "Enviando…",
        ["profile.cancel"] = "Cancelar",
        ["profile.submit_report"] = "Enviar denúncia",
        ["profile.report_submitted"] = "Denúncia enviada",
        ["profile.report_thanks"] = "Obrigado — os nossos moderadores vão verificar. Não vais ver este perfil de novo até puxar um novo do deck.",
        ["profile.closing"] = "Fechando…",
        ["profile.closing_in"] = "Fechando em {0} segundos",
        ["profile.close"] = "Fechar",

        // ProfileScreen — copy profile text (viewing others only)
        ["profile.copy_text"] = "Copiar texto do perfil",
        ["profile.copy_warning_title"] = "Aviso",
        ["profile.copy_warning_body"] = "Você copiou o texto de outra pessoa. Tenha cuidado ao clicar ou acessar qualquer link que ele contenha — você faz isso por sua conta e risco.",
        ["profile.copy_warning_agree"] = "Entendi e concordo",

        // MyProfileScreen hub: stats + menu
        ["profile.section_myprofile"] = "Meu perfil",
        ["profile.section_service"] = "Serviço",
        ["profile.menu_view"] = "Ver meu perfil",
        ["profile.menu_edit"] = "Modificar perfil",
        ["profile.menu_images"] = "Fotos do perfil",
        ["profile.stat_loves_you"] = "te amam",
        ["profile.stat_matches"] = "Matches",
        ["profile.stat_match_rate"] = "Taxa de match",
        ["profile.back_to_my"] = "← Voltar",

        // MyProfileScreen — edit tab load / save
        ["profile.load_profile_failed"] = "Não foi possível carregar seu perfil: {0}",
        ["profile.retry"] = "Tentar de novo",
        ["profile.saving"] = "Guardando…",
        ["profile.saved"] = "Guardado  ✓",
        ["profile.save_changes"] = "guardar Alterações",

        // MyProfileScreen — edit form section headings
        ["profile.heading_character"] = "Personagem",
        ["profile.heading_location"] = "Localização",
        ["profile.heading_languages"] = "Idiomas que Eu Falo",
        ["profile.heading_content"] = "Eu Gosto dos Seguintes Conteúdos",
        ["profile.heading_looking_for"] = "Estou a Procura De",
        ["profile.heading_nsfw"] = "NSFW",
        ["profile.heading_optional"] = "Opcional",
        ["profile.heading_playtime"] = "Horário de Jogo",
        ["profile.heading_timezone"] = "Fuso horário",
        ["profile.heading_sync_tool"] = "Ferramenta de Sync",
        ["profile.heading_match_prefs"] = "Preferências de Match",

        // MyProfileScreen — edit form labels / hints
        ["profile.display_name"] = "Nome de Exibição",
        ["profile.about_me"] = "Sobre Mim",
        ["profile.char_count"] = "{0} / 500 caracteres",
        ["profile.preview"] = "pré-visualizar",
        ["profile.bio_placeholder"] = "Sua bio vai aparecer aqui…",
        ["profile.race"] = "Raça",
        ["profile.region"] = "Região",
        ["profile.languages_hint"] = "Selecione todos os idiomas em que você se sente à vontade para conversar.",
        ["profile.content_hint"] = "Selecione tudo o que se aplica.",
        ["profile.looking_for_hint"] = "Ser honesto ajuda a encontrar matches melhores.",
        ["profile.nsfw_lalafell"] = "Os recursos adultos e NSFW não estão disponíveis enquanto sua race estiver definida como Lalafell. Consulte os Termos de Serviço para mais detalhes.",
        ["profile.nsfw_explainer"] = "NSFW significa \"Not Safe For Work\" (impróprio para o trabalho): conteúdo que contém nudez ou temas sexuais. Adira para ver e dar match com perfis NSFW.",
        ["profile.nsfw_optin"] = "Perfis NSFW: SIM",
        ["profile.favourite_job_tooltip"] = "O job ou papel que você mais curte. Digite para filtrar.",
        ["profile.favourite_ff_character_full"] = "Personagem Favorito de Final Fantasy",
        ["profile.weekday_playtimes_edit"] = "Horários de Jogo nos Dias de Semana (Seg–Sex)",
        ["profile.weekend_playtimes_edit"] = "Horários de Jogo no Fim de Semana (Sáb–Dom)",
        ["profile.sync_tool_hint"] = "Ferramentas de sync permitem que usuários que deram match compartilhem aparências de mods.",
        ["profile.match_prefs_body"] = "Conte com quem você gostaria de dar match. Estas preferências ajudam a mostrar as pessoas certas para você.",
        ["profile.all"] = "Todos",
        ["profile.none"] = "Nenhum",
        ["profile.clear"] = "Limpar",
        ["profile.filter_any_race"] = "  Sem seleção: qualquer race",
        ["profile.filter_any_gender"] = "  Sem seleção: qualquer gênero",
        ["profile.filter_any_region"] = "  Sem seleção: qualquer região",
        ["profile.filter_any_language"] = "  Sem seleção: sem preferência de idioma",
        ["profile.spoken_language"] = "Idioma Falado",
        ["profile.spoken_language_tooltip"] = "Deixe tudo desmarcado para dar match independentemente do idioma.",

        // MyProfileScreen.Images — tab text
        ["profile.load_photos_failed"] = "Não foi possível carregar suas fotos: {0}",
        ["profile.profile_picture"] = "Foto de Perfil",
        ["profile.profile_picture_desc"] = "Sua foto de perfil é exibida na lista de chats e nos cartões de match. Use um retrato quadrado em close do seu personagem de FFXIV.",
        ["profile.profile_photos"] = "Fotos do Perfil",
        ["profile.profile_photos_desc"] = "Adicione fotos de retrato ao seu perfil (proporção 10:16). O primeiro espaço é obrigatório; os espaços 2 a 4 são opcionais.",
        ["profile.declare_before_save"] = "Marque cada foto extra como SFW ou NSFW antes de salvar.",

        // MyProfileScreen.Images — avatar section
        ["profile.new_photo_ready"] = "Nova foto pronta, ainda não salva.",
        ["profile.change_photo"] = "Trocar Foto",
        ["profile.profile_picture_set"] = "Foto de perfil: Definida  ✓",
        ["profile.no_profile_picture"] = "Nenhuma foto de perfil definida.",
        ["profile.upload_avatar"] = "Enviar Avatar…",

        // MyProfileScreen.Images — slot grid + active slot controls
        ["profile.slot_main"] = "Principal",
        ["profile.tap_slot"] = "Toque em um espaço acima para adicionar ou trocar uma foto.",
        ["profile.main_photo"] = "Foto principal",
        ["profile.extra_photo"] = "Foto extra {0}",
        ["profile.photo_will_be_removed"] = "A foto será removida.",
        ["profile.undo"] = "Desfazer",
        ["profile.main_must_be_sfw"] = "Sua foto de perfil principal PRECISA ser SFW. Enviar uma foto NSFW é motivo para suspensão ou exclusão da conta.",
        ["profile.sfw_or_nsfw"] = "Esta foto é SFW ou NSFW?",
        ["profile.sfw_mismatch_warning"] = "Se nosso sistema detectar que você enviou conteúdo NSFW enquanto SFW está selecionado, sua foto ficará retida para moderação e você corre o risco de ter a conta suspensa.",
        ["profile.photo_ready"] = "Foto pronta, ainda não salva.",
        ["profile.replace"] = "Substituir",
        ["profile.photo_set"] = "Foto definida  ✓",
        ["profile.currently_nsfw"] = "Atualmente: NSFW",
        ["profile.currently_sfw"] = "Atualmente: SFW",
        ["profile.remove"] = "Remover",
        ["profile.photo_required"] = "Esta foto é obrigatória.",
        ["profile.photo_optional"] = "Esta foto é opcional.",
        ["profile.upload_photo"] = "Enviar Foto…",

        // MyProfileScreen.Images — file picker / crop popup
        ["profile.select_image"] = "Selecionar Imagem",
        ["profile.image_files_filter"] = "Arquivos de imagem",
        ["profile.crop_avatar"] = "Recortar Avatar",
        ["profile.crop_main_photo"] = "Recortar Foto Principal",
        ["profile.crop_extra_photo"] = "Recortar Foto Extra {0}",

        // added after update 1.4.3
        ["profile.menu_rp"] = "Meus Perfis de RP",
        ["profile.rp_intro_title"] = "Meus Perfis de RP",
        ["profile.rp_intro"] = "Adicione seus OCs de FFXIV (personagens originais) ao seu perfil. Cada personagem tem um nome, uma breve história e uma imagem opcional, e eles aparecem no seu perfil para os outros descobrirem.",
        ["profile.characters"] = "Personagens",
        ["profile.rp_add"] = "Adicionar personagem",
        ["profile.rp_empty"] = "Nenhum personagem ainda. Adicione seu primeiro OC abaixo!",
        ["profile.rp_limit_reached"] = "Você pode adicionar até {0} personagens.",
        ["profile.rp_name"] = "Nome / Título",
        ["profile.rp_bio"] = "Sobre este personagem",
        ["profile.rp_delete"] = "Excluir",
        ["profile.rp_delete_confirm"] = "Excluir mesmo?",
        ["profile.rp_move_up"] = "Mover para cima",
        ["profile.rp_move_down"] = "Mover para baixo",
        ["profile.rp_image"] = "Imagem",
        ["profile.rp_upload_image"] = "Enviar imagem",
        ["profile.rp_replace_image"] = "Substituir imagem",
        ["profile.rp_remove_image"] = "Remover imagem",
        ["profile.rp_image_ready"] = "Imagem pronta para salvar",
        ["profile.rp_image_nsfw"] = "Esta imagem é NSFW",
        ["profile.rp_image_expand"] = "Ver em tamanho real",
        ["profile.rp_image_back"] = "Voltar ao perfil",
        ["profile.rp_crop_image"] = "Recortar Imagem do Personagem",
        ["profile.rp_back"] = "Voltar",
        ["profile.rp_details"] = "Detalhes do personagem:",
    };
}
