namespace AetherLove.Services.Localization;

internal static class DeckEn
{
    public static readonly System.Collections.Generic.Dictionary<string, string> Strings = new()
    {
        ["deck.cooldown_heading"] = "You're all caught up!",
        ["deck.cooldown_body"] = "AetherLove hands you a fresh batch of profiles every few hours, so everyone gets a fair look. Check back soon for new potential matches!",
        ["deck.new_matches_ready"] = "New matches are ready!",
        ["deck.server_error"] = "Couldn't reach the server: {0}",
        ["deck.view_profile"] = "View profile",
        ["deck.like"] = "LIKE",
        ["deck.nope"] = "NOPE",
        ["deck.match_you"] = "You",
        ["deck.match_your_match"] = "Your match",
        ["deck.match_congratulations"] = "Congratulations!",
        ["deck.match_its_a_match"] = "It's a Match!",
        ["deck.match_fx_cosmic"] = "Two souls, one orbit",
        ["deck.match_fx_synthwave"] = "Cruising into the sunset",
        ["deck.match_fx_aurora"] = "Drawn together by the light",
        ["deck.match_fx_kaleido"] = "Symmetry found",
        ["deck.match_fx_supernova"] = "Your hearts beat as one",
        ["deck.match_fx_vortex"] = "Pulled into the same orbit",
        ["deck.match_fx_portal"] = "Torn from the same rift",
        ["deck.match_fx_electric"] = "Sparks are flying",
        ["deck.match_fx_bubble"] = "Two bubbles, one shimmer",
        ["deck.match_fx_dna"] = "A perfect match of base pairs.",
        ["deck.match_fx_firework"] = "Let the sky celebrate",
        ["deck.match_fx_vinyl"] = "On the same wavelength",
        ["deck.match_fx_arcade_players"] = "* PLAYER 1 *   * PLAYER 2 *",
        ["deck.match_fx_arcade_score"] = "SCORE",
        ["deck.match_fx_constellation"] = "Written in the stars",
        ["deck.match_fx_slot"] = "Three of a kind",
        ["deck.match_fx_slot_title"] = "JACKPOT!",
        ["deck.match_fx_tarot"] = "The cards align — two destinies entwined",
        ["deck.match_fx_tarot_title"] = "THE LOVERS",
        ["deck.match_fx_lavalamp"] = "Two flames, one glow",
        ["deck.match_fx_lanterns"] = "Two lights, one sky",
        ["deck.match_fx_treasure"] = "It's a match worth its weight in gold",
        ["deck.match_fx_treasure_title"] = "TREASURE FOUND",
        ["deck.match_start_chatting"] = "Start Chatting",
        ["deck.match_keep_swiping"] = "Keep Swiping",
        ["deck.no_pool_heading"] = "You're out of matches",
        ["deck.no_pool_body"] = "No more matches were found for you with your current criteria. Broaden your criteria, and try again later.",
        ["deck.next_deck"] = "Next deck: {0}",
        // added after update (1.3.1)
        ["deck.reswipe_tooltip"] = "Undo your last swipe",
        ["deck.reswipe_cooldown"] = "Reswipe available in {0}h:{1:00}m",
        ["deck.reswipe_matched_title"] = "Already a match!",
        ["deck.reswipe_matched"] = "You cannot reswipe on a matched profile.",
        ["deck.decide_later_tooltip"] = "Decide later",
        ["deck.decide_later_disabled"] = "This is the last card in your deck.",
        ["deck.reswipe_intro_title"] = "Undo your last swipe",
        ["deck.reswipe_intro"] = "This takes back your last swipe and brings that profile right back to the top. You can use it once every 24 hours. Closing this note won't use up your undo, so tap the button again when you're ready.",
    };
}
