namespace AetherLove.Services.Localization;

internal static class DeckRu
{
    public static readonly System.Collections.Generic.Dictionary<string, string> Strings = new()
    {
        ["deck.cooldown_heading"] = "А на этом всё!",
        ["deck.cooldown_body"] = "AetherLove выдаёт вам часть актуальных профилей каждые несколько часов, чтобы у всех был равный шанс. Загляните позже за новыми потенциальными парами!",
        ["deck.new_matches_ready"] = "Новые пары готовы!",
        ["deck.server_error"] = "Не удалось подключиться к серверу: {0}",
        ["deck.view_profile"] = "Открыть профиль",
        ["deck.like"] = "НРАВИТСЯ",
        ["deck.nope"] = "НЕТ",
        ["deck.match_you"] = "Вы",
        ["deck.match_your_match"] = "Ваша пара",
        ["deck.match_congratulations"] = "Поздравляем!",
        ["deck.match_its_a_match"] = "Это пара!",
        ["deck.match_fx_cosmic"] = "Две души на одной орбите",
        ["deck.match_fx_synthwave"] = "Мчимся навстречу закату",
        ["deck.match_fx_aurora"] = "Сведённые сиянием",
        ["deck.match_fx_kaleido"] = "Идеальная симметрия",
        ["deck.match_fx_supernova"] = "Сердца бьются в унисон",
        ["deck.match_fx_vortex"] = "Затянуты в один водоворот",
        ["deck.match_fx_portal"] = "Из одного разлома",
        ["deck.match_fx_electric"] = "Между вами искрит",
        ["deck.match_fx_bubble"] = "Два пузырька, одно мерцание",
        ["deck.match_fx_dna"] = "Идеальная пара — ген к гену.",
        ["deck.match_fx_firework"] = "Пусть небо ликует",
        ["deck.match_fx_vinyl"] = "На одной волне",
        ["deck.match_fx_arcade_players"] = "* ИГРОК 1 *   * ИГРОК 2 *",
        ["deck.match_fx_arcade_score"] = "СЧЁТ",
        ["deck.match_fx_constellation"] = "Так распорядились звёзды",
        ["deck.match_fx_slot"] = "Три в ряд",
        ["deck.match_fx_slot_title"] = "ДЖЕКПОТ!",
        ["deck.match_fx_tarot"] = "Карты сошлись — две судьбы переплелись",
        ["deck.match_fx_tarot_title"] = "ВЛЮБЛЁННЫЕ",
        ["deck.match_fx_lavalamp"] = "Два пламени, одно сияние",
        ["deck.match_fx_lanterns"] = "Два огонька, одно небо",
        ["deck.match_fx_treasure"] = "Эта пара на вес золота",
        ["deck.match_fx_treasure_title"] = "СОКРОВИЩЕ НАЙДЕНО",
        ["deck.match_start_chatting"] = "Начать общение",
        ["deck.match_keep_swiping"] = "Продолжить листать",
        ["deck.no_pool_heading"] = "Пары закончились",
        ["deck.no_pool_body"] = "По вашим текущим критериям больше пар не найдено. Расширьте критерии и повторите попытку позже.",
        ["deck.next_deck"] = "Следующая колода: {0}",
    };
}
