namespace AetherLove.Services.Localization;

internal static class ChatPt
{
    public static readonly System.Collections.Generic.Dictionary<string, string> Strings = new()
    {
        ["chat.no_conversation_selected"] = "Nenhuma conversa selecionada.",
        ["chat.unreadable_message"] = "[mensagem ilegível]",
        ["chat.report_submitted_toast"] = "Denúncia enviada. Nossa equipa de moderação vai analisá-la.",
        ["chat.view_profile"] = "Ver perfil",
        ["chat.back_to_matches"] = "Voltar aos matches",
        ["chat.menu_open_profile"] = "Abrir perfil",
        ["chat.menu_copy_message"] = "Copiar mensagem",
        ["chat.menu_pin"] = "Fixar conversa",
        ["chat.menu_unpin"] = "Desafixar conversa",
        ["chat.menu_unmatch"] = "Desfazer match",
        ["chat.menu_block"] = "Bloquear",
        ["chat.menu_report_user"] = "Denunciar Usuário",
        ["chat.unmatch_title"] = "Desfazer match",
        ["chat.unmatch_body"] = "Quando você desfaz o match com este jogador, a conversa fica oculta para os dois. Se vocês derem match de novo mais tarde, o histórico reaparece.",
        ["chat.unmatch_confirm"] = "Desfazer match",
        ["chat.block_title"] = "Bloquear Usuário",
        ["chat.block_body"] = "Quando você bloqueia um usuário, a conversa fica oculta para os dois e ele não aparecerá nos seus matches no futuro.",
        ["chat.block_confirm"] = "Bloquear",
        ["chat.cancel"] = "Cancelar",
        ["chat.loading_messages"] = "Carregando mensagens…",
        ["chat.e2e_self_broken"] = "Algo está errado com a tua configuração E2E. Contacta o suporte.",
        ["chat.seen_suffix"] = " · visto",
        ["chat.send"] = "Enviar",
        ["chat.emoji_button"] = ":)",
        ["chat.system_notice_line1"] = "Este é um chat privado entre você e {0}. Este chat é criptografado de ponta a ponta, a equipe do AetherLove não consegue ler suas mensagens. No canto superior direito, você encontra um menu para desfazer o match, bloquear ou denunciar seu match.",
        ["chat.system_notice_line2"] = "Lembra: {0} não sabe o teu nome completo nem a tua localização até ser compartilhado entre os dois. Cuida da Tua própria privacidade e só compartilha mais quando estiver pronto.",
        ["chat.i_understand"] = "Eu entendi",
        ["chat.report_title"] = "Denunciar Usuário",
        ["chat.report_reason_prompt"] = "Por favor, descreva o motivo da sua denúncia:",
        ["chat.report_agree"] = "Eu concordo em enviar uma denúncia contra {0}",
        ["chat.report_agree_contents"] = "Eu concordo em enviar o conteúdo desta conversa para a equipe do AetherLove",
        ["chat.submitting"] = "Enviando…",
        ["chat.submit"] = "Enviar",

        // Verify encryption
        ["verify.title"] = "Verificar a criptografia",
        ["verify.intro"] = "O AetherLove criptografa este chat de ponta a ponta: somente você e {0} podem lê-lo, nem mesmo nossa equipe. O padrão entrelaçado abaixo é gerado a partir das chaves de criptografia de vocês dois.",
        ["verify.unavailable"] = "A verificação ainda não está pronta. Ela ficará disponível assim que vocês dois tiverem configurado a criptografia e trocado as chaves.",
        ["verify.how"] = "Se {0} vir exatamente o mesmo padrão e o mesmo código na tela, ninguém está interceptando o chat de vocês. Comparem por chat de voz ou pessoalmente. Se não coincidirem, pare de compartilhar qualquer coisa sensível e contate o suporte.",
        ["verify.your_key"] = "Sua chave pública",
        ["verify.their_key"] = "Chave pública de {0}",
        ["verify.keys_explain"] = "As chaves públicas podem ser compartilhadas com segurança; é assim que os aplicativos de vocês se reconhecem. As chaves privadas correspondentes nunca saem dos seus aparelhos, então nenhum servidor (nem mesmo o nosso) pode ler suas mensagens.",
        ["verify.back"] = "Voltar ao chat",

        // ChatListScreen
        ["chat.preview_me_prefix"] = "Eu: ",
        ["chat.preview_venue"] = "Compartilhou um local",
        ["chat.matches_title"] = "Matches",
        ["chat.show_search"] = "Mostrar busca",
        ["chat.hide_search"] = "Ocultar busca",
        ["chat.search_hint"] = "Nome ou mensagem",
        ["chat.searching"] = "Buscando…",
        ["chat.search_no_results"] = "Nenhum resultado encontrado",
        ["chat.matches_load_error"] = "Não foi possível carregar os matches: {0}",
        ["chat.connectivity_error"] = "Não foi possível conectar ao servidor do AetherLove. Tente novamente ou visite o Discord para ver o status do servidor.",
        ["chat.empty_state"] = "Você ainda não tem matches — mas isso vai mudar logo. Continue deslizando!",
        ["chat.new_match"] = "novo match",
        ["chat.say_hi"] = "Vocês deram match — diz olá!",
        ["chat.time_ago_minutes"] = "há {0}min",
        ["chat.time_ago_hours"] = "há {0}h",
        ["chat.time_ago_days"] = "há {0}d",

        // added after update (1.3.1)
        ["chat.you"] = "Você",
        ["chat.reply"] = "Responder",
        ["chat.pin_message"] = "Fixar mensagem",
        ["chat.unpin_message"] = "Desafixar mensagem",
        ["chat.pinned_messages"] = "Mensagens fixadas",
        ["chat.pinned_messages_menu"] = "Mensagens fixadas ({0})",
        ["chat.quote_unavailable"] = "(mensagem original indisponível)",
        ["chat.quote_generic"] = "(mensagem)",
        ["chat.replying_to"] = "Respondendo a {0}",
        ["chat.reaction_remove_hint"] = "clique para remover",
        ["chat.jump"] = "Ir",
        ["chat.unpin"] = "Desafixar",

        // added after update 1.4.3
        ["chat.menu_search"] = "Procurar mensagens",
        ["chat.search_messages_hint"] = "Procurar nesta conversa...",
        ["chat.category_new"] = "Nova categoria",
        ["chat.category_edit"] = "Editar categoria",
        ["chat.category_delete"] = "Eliminar categoria",
        ["chat.category_delete_body"] = "Tens a certeza de que queres eliminar {0}? As conversas lá dentro voltam para a tua lista de matches.",
        ["chat.category_delete_confirm"] = "Eliminar",
        ["chat.category_name_hint"] = "Nome da categoria",
        ["chat.category_create"] = "Criar",
        ["chat.category_save"] = "Guardar",
        ["chat.menu_move_to_category"] = "Mover para categoria",
        ["chat.menu_remove_from_category"] = "Remover da categoria",
        ["chat.category_empty"] = "Ainda não há conversas nesta categoria. Arrasta uma conversa para aqui ou clica com o botão direito numa conversa e escolhe Mover para categoria.",
        ["chat.category_count"] = "Conversas: {0}",
        ["chat.category_archive_default"] = "Arquivo",
        ["chat.all_categorized"] = "Todas as tuas conversas estão organizadas em categorias",

        // added after update 1.5.1
        ["chat.menu_view_blocked"] = "Ver bloqueados",
        ["blocked.title"] = "Usuários bloqueados",
        ["blocked.intro_body"] = "Aqui você pode desbloquear perfis que bloqueou no passado. Ao desbloquear alguém, não haverá match automático, mas vocês podem voltar a se ver no deck.",
        ["blocked.empty"] = "Você não bloqueou ninguém.",
        ["blocked.loading"] = "Carregando...",
        ["blocked.since"] = "Bloqueado em {0}",
        ["blocked.unblock"] = "Desbloquear",
        ["blocked.confirm_title"] = "Desbloquear {0}?",
        ["blocked.confirm_body"] = "Não haverá match automático, mas vocês podem voltar a se ver no deck.",
    };
}
