namespace AetherLove.Services.Localization;

internal static class ProfileEs
{
    public static readonly System.Collections.Generic.Dictionary<string, string> Strings = new()
    {
        ["profile.load_failed"] = "No se pudo cargar el perfil: {0}",
        ["profile.none_loaded"] = "Ningún perfil cargado.",

        ["profile.about"] = "Sobre mí",
        ["profile.flairs"] = "Distintivos",
        ["profile.looking_for"] = "Busco",
        ["profile.content_interests"] = "Preferencias de contenido",
        ["profile.info"] = "Información",
        ["profile.gender"] = "Género",
        ["profile.languages"] = "Idiomas",
        ["profile.timezone"] = "Zona horaria",
        ["profile.favourite_job"] = "Trabajo favorito",
        ["profile.favourite_location"] = "Lugar favorito",
        ["profile.favourite_expansion"] = "Expansión favorita",
        ["profile.favourite_spotify_song"] = "Canción favorita de Spotify",
        ["profile.favourite_song"] = "Canción favorita",
        ["music.fetching"] = "Obteniendo el nombre de la canción…",
        ["music.saved"] = "Enlace guardado (nombre pendiente)",
        ["music.invalid"] = "No se pudo leer ese enlace — pega un enlace de canción de Spotify, SoundCloud, Apple Music o YouTube Music.",
        ["music.open_tooltip"] = "Haz clic para abrir",
        ["profile.favourite_movie"] = "Película favorita",
        ["profile.favourite_anime"] = "Anime favorito",
        ["profile.favourite_ff_character"] = "Personaje favorito de FF",
        ["profile.sync_tool"] = "Herramienta de sincronización",
        ["profile.uses_sync_tool"] = "Usa herramienta de sincronización",
        ["profile.preferred"] = "Preferido",
        ["profile.yes"] = "Sí",
        ["profile.no"] = "No",
        ["profile.weekday_playtimes"] = "Horarios de juego entre semana  (lun–vie)",
        ["profile.weekend_playtimes"] = "Horarios de juego en fin de semana  (sáb–dom)",
        ["profile.timezone_value"] = "{0} (hora actual: {1})",

        ["profile.spotify_open_tooltip"] = "Haz clic para abrir en Spotify",
        ["profile.nsfw_reveal"] = "Haz clic para mostrar la imagen NSFW",

        ["profile.back_to_chat"] = "Volver al chat",
        ["profile.back_to_swiping"] = "Volver a deslizar",

        ["profile.report_profile"] = "Denunciar perfil",
        ["profile.report_warning"] = "Las denuncias falsas o malintencionadas conllevan advertencias en tu propia cuenta, y el abuso reiterado puede dar lugar a una suspensión. Denuncia solo los perfiles que realmente infrinjan las reglas.",
        ["profile.report_prompt"] = "Dile a nuestros moderadores qué pasa con {0}:",
        ["profile.this_profile"] = "este perfil",
        ["profile.report_agree"] = "Entiendo que las denuncias falsas pueden conllevar advertencias contra mi cuenta.",
        ["profile.submitting"] = "Enviando…",
        ["profile.cancel"] = "Cancelar",
        ["profile.submit_report"] = "Enviar denuncia",
        ["profile.report_submitted"] = "Denuncia enviada",
        ["profile.report_thanks"] = "Gracias — nuestros moderadores lo revisarán. No volverás a ver este perfil hasta que saques uno nuevo del mazo.",
        ["profile.closing"] = "Cerrando…",
        ["profile.closing_in"] = "Cerrando en {0} segundos",
        ["profile.close"] = "Cerrar",

        ["profile.tab_view"] = "Ver perfil",
        ["profile.tab_edit"] = "Editar perfil",
        ["profile.tab_images"] = "Cambiar imágenes",

        ["profile.load_profile_failed"] = "No se pudo cargar tu perfil: {0}",
        ["profile.retry"] = "Reintentar",
        ["profile.save_failed"] = "Error al guardar: {0}",
        ["profile.saving"] = "Guardando…",
        ["profile.saved"] = "Guardado  ✓",
        ["profile.save_changes"] = "Guardar cambios",

        ["profile.heading_identity"] = "Identidad",
        ["profile.heading_character"] = "Personaje",
        ["profile.heading_location"] = "Ubicación",
        ["profile.heading_languages"] = "Idiomas que hablo",
        ["profile.heading_content"] = "Disfruto del siguiente contenido",
        ["profile.heading_looking_for"] = "Estoy buscando",
        ["profile.heading_nsfw"] = "NSFW",
        ["profile.heading_optional"] = "Opcional",
        ["profile.heading_playtime"] = "Horario de juego",
        ["profile.heading_timezone"] = "Zona horaria",
        ["profile.heading_sync_tool"] = "Herramienta de sincronización",
        ["profile.heading_match_prefs"] = "Preferencias de coincidencia",

        ["profile.display_name"] = "Nombre visible",
        ["profile.display_name_hint"] = "Nombre de pila o alias, sin espacios.",
        ["profile.about_me"] = "Sobre mí",
        ["profile.char_count"] = "{0} / 500 caracteres",
        ["profile.preview"] = "Vista previa",
        ["profile.bio_placeholder"] = "Tu biografía aparecerá aquí…",
        ["profile.race"] = "Raza",
        ["profile.region"] = "Región",
        ["profile.languages_hint"] = "Selecciona todos los idiomas en los que te sientas cómodo chateando.",
        ["profile.content_hint"] = "Selecciona todo lo que aplique.",
        ["profile.looking_for_hint"] = "Ser sincero ayuda a encontrar mejores coincidencias.",
        ["profile.nsfw_lalafell"] = "Las funciones para adultos y NSFW no están disponibles mientras tu raza esté fijada como Lalafell. Consulta los Términos del servicio para más detalles.",
        ["profile.nsfw_explainer"] = "NSFW significa \"Not Safe For Work\" (no apto para el trabajo): contenido con desnudos o temática sexual. Actívalo para ver perfiles NSFW y coincidir con ellos.",
        ["profile.nsfw_optin"] = "Perfiles NSFW: SÍ",
        ["profile.favourite_job_tooltip"] = "El trabajo o rol que más disfrutas. Escribe para filtrar.",
        ["profile.favourite_spotify"] = "Canción favorita de Spotify",
        ["profile.spotify_tooltip"] = "Pega la URL de una pista de Spotify o el ID de la pista.",
        ["profile.track_id"] = "ID de pista: {0}",
        ["profile.favourite_ff_character_full"] = "Personaje favorito de Final Fantasy",
        ["profile.weekday_playtimes_edit"] = "Horarios de juego entre semana (lun–vie)",
        ["profile.weekend_playtimes_edit"] = "Horarios de juego en fin de semana (sáb–dom)",
        ["profile.sync_tool_hint"] = "Las herramientas de sincronización permiten a los usuarios emparejados compartir apariencias de mods.",
        ["profile.match_prefs_body"] = "Cuéntanos con quién te gustaría coincidir. Estas preferencias ayudan a mostrarte a las personas adecuadas.",
        ["profile.all"] = "Todos",
        ["profile.none"] = "Ninguno",
        ["profile.clear"] = "Limpiar",
        ["profile.filter_any_race"] = "  Sin selección: cualquier raza",
        ["profile.filter_any_gender"] = "  Sin selección: cualquier género",
        ["profile.filter_any_region"] = "  Sin selección: cualquier región",
        ["profile.filter_any_language"] = "  Sin selección: sin preferencia de idioma",
        ["profile.spoken_language"] = "Idioma hablado",
        ["profile.spoken_language_tooltip"] = "Déjalo todo sin marcar para coincidir sin importar el idioma.",
        ["profile.load_photos_failed"] = "No se pudieron cargar tus fotos: {0}",
        ["profile.profile_picture"] = "Foto de perfil",
        ["profile.profile_picture_desc"] = "Tu foto de perfil se muestra en la lista de chats y en las tarjetas de coincidencia. Usa un retrato cuadrado en primer plano de tu personaje de FFXIV.",
        ["profile.profile_photos"] = "Fotos de perfil",
        ["profile.profile_photos_desc"] = "Añade fotos de retrato a tu perfil (relación 10:16). La primera ranura es obligatoria; las ranuras 2–4 son opcionales.",
        ["profile.declare_before_save"] = "Marca cada foto adicional como SFW o NSFW antes de guardar.",

        ["profile.new_photo_ready"] = "Foto nueva lista, aún sin guardar.",
        ["profile.change_photo"] = "Cambiar foto",
        ["profile.profile_picture_set"] = "Foto de perfil: Establecida  ✓",
        ["profile.no_profile_picture"] = "No hay foto de perfil establecida.",
        ["profile.upload_avatar"] = "Subir avatar…",

        ["profile.slot_main"] = "Principal",
        ["profile.tap_slot"] = "Toca una ranura de arriba para añadir o cambiar una foto.",
        ["profile.main_photo"] = "Foto principal",
        ["profile.extra_photo"] = "Foto adicional {0}",
        ["profile.photo_will_be_removed"] = "La foto se eliminará.",
        ["profile.undo"] = "Deshacer",
        ["profile.main_must_be_sfw"] = "Tu foto de perfil principal DEBE ser SFW. Subir una foto NSFW es motivo de suspensión o eliminación de la cuenta.",
        ["profile.sfw_or_nsfw"] = "¿Esta foto es SFW o NSFW?",
        ["profile.sfw_mismatch_warning"] = "Si nuestro sistema detecta que subiste contenido NSFW estando seleccionado SFW, tu foto quedará retenida para moderación y te arriesgas a la suspensión de la cuenta.",
        ["profile.photo_ready"] = "Foto lista, aún sin guardar.",
        ["profile.replace"] = "Reemplazar",
        ["profile.photo_set"] = "Foto establecida  ✓",
        ["profile.currently_nsfw"] = "Actualmente: NSFW",
        ["profile.currently_sfw"] = "Actualmente: SFW",
        ["profile.remove"] = "Eliminar",
        ["profile.photo_required"] = "Esta foto es obligatoria.",
        ["profile.photo_optional"] = "Esta foto es opcional.",
        ["profile.upload_photo"] = "Subir foto…",

        ["profile.select_image"] = "Seleccionar imagen",
        ["profile.image_files_filter"] = "Archivos de imagen",
        ["profile.crop_avatar"] = "Recortar avatar",
        ["profile.crop_main_photo"] = "Recortar foto principal",
        ["profile.crop_extra_photo"] = "Recortar foto adicional {0}",
    };
}
