using System.Collections.Generic;

namespace AetherOS.Apps.Calculator.Localization;

/// <summary>The Calculator app's own UI strings, merged into the central tables at app registration. Key
/// faces (digits, operators, ENTER, WINDOW, ZOOM and the rest) are device silkscreen and stay untranslated.</summary>
public static class AppStrings
{
    private static readonly IReadOnlyDictionary<string, string> En = new Dictionary<string, string>
    {
        // added after update 2.3.3 (calculator)
        ["os.calc_deg"] = "DEG",
        ["os.calc_rad"] = "RAD",
        ["os.calc_history_empty"] = "Type something, then press ENTER.",
        ["os.calc_sto_prompt"] = "STO: press ALPHA, then a letter.",
        ["os.calc_stored"] = "Stored: {0} = {1}",
        ["os.calc_err_syntax"] = "Syntax error",
        ["os.calc_err_domain"] = "Domain error",
        ["os.calc_err_divzero"] = "Divide by zero",
        ["os.calc_err_overflow"] = "Number too large",
        ["os.calc_err_undefined"] = "Undefined",
        ["os.calc_err_depth"] = "Expression too deep",
        ["os.calc_err_generic"] = "Error",
        ["os.calc_view_home"] = "Home",
        ["os.calc_view_trace"] = "Trace",
        ["os.calc_view_tblset"] = "Setup",
        ["os.calc_view_graph"] = "Graph",
        ["os.calc_view_table"] = "Table",
        ["os.calc_graph_no_functions"] = "No functions are switched on. Open Y= and type one.",
        ["os.calc_mode_simple"] = "Simple calculator",
        ["os.calc_mode_simple_hint"] = "The everyday keypad: four operations, percent, and a running tape.",
        ["os.calc_mode_graphing"] = "Graphing calculator",
        ["os.calc_mode_graphing_hint"] = "The full handheld: functions, plots, tracing and value tables.",
        ["os.calc_tour_mode_title"] = "Which calculator do you want?",
        ["os.calc_tour_mode_body"] = "One is for working out a repair bill. The other plots curves. Pick whichever suits you now, nothing is locked in.",
        ["os.calc_tour_mode_switch"] = "You can switch at any time from the menu at the top right.",
        ["os.calc_tour_simple_title"] = "Ready when you are",
        ["os.calc_tour_simple_body"] = "Type a sum and press =, or use the keypad. Every answer stays on the tape above, and Ans holds the last one.",
        ["os.calc_tour_simple_f1"] = "Type straight into the entry line or use the keys",
        ["os.calc_tour_simple_f2"] = "The tape keeps every answer you have worked out",
        ["os.calc_tour_simple_f3"] = "Swap to the graphing calculator whenever you need it",
        ["os.calc_tour_s2_step1"] = "1. Press Y= and pick a slot",
        ["os.calc_tour_s2_step2"] = "2. Type an expression using x, like x^2-3",
        ["os.calc_tour_s2_step3"] = "3. Press GRAPH to draw it",
        ["os.calc_tour_s2_slots"] = "Four slots, Y1 to Y4, each drawn in its own colour",
        ["os.calc_graph_how_to"] = "Press Y=, type something with x in it, then press GRAPH.",
        ["os.calc_graph_add_function"] = "Open Y=",
        ["os.calc_trace_hint"] = "Drag the plot to pan, scroll to zoom.",
        ["os.calc_y_title"] = "Y= editor",
        ["os.calc_y_hint"] = "Write x for the variable, like x^2-3. Switch a line off to hide it.",
        ["os.calc_window_title"] = "Window",
        ["os.calc_window_xmin"] = "x min",
        ["os.calc_window_xmax"] = "x max",
        ["os.calc_window_ymin"] = "y min",
        ["os.calc_window_ymax"] = "y max",
        ["os.calc_window_apply"] = "Apply",
        ["os.calc_window_bad"] = "Each minimum must be below its maximum.",
        ["os.calc_zoom_title"] = "Zoom",
        ["os.calc_zoom_standard"] = "Standard",
        ["os.calc_zoom_trig"] = "Trig",
        ["os.calc_zoom_square"] = "Square",
        ["os.calc_zoom_fit"] = "Fit",
        ["os.calc_zoom_in"] = "Zoom in",
        ["os.calc_zoom_out"] = "Zoom out",
        ["os.calc_calc_title"] = "Calc",
        ["os.calc_calc_root"] = "Root",
        ["os.calc_calc_min"] = "Minimum",
        ["os.calc_calc_max"] = "Maximum",
        ["os.calc_calc_intersect"] = "Intersect",
        ["os.calc_calc_derivative"] = "dy/dx",
        ["os.calc_calc_integral"] = "Integral",
        ["os.calc_calc_first"] = "First function",
        ["os.calc_calc_second"] = "Second function",
        ["os.calc_calc_lower"] = "Lower bound",
        ["os.calc_calc_upper"] = "Upper bound",
        ["os.calc_calc_at"] = "At x",
        ["os.calc_calc_run"] = "Compute",
        ["os.calc_calc_none"] = "Nothing found in that range.",
        ["os.calc_no_function"] = "Switch a function on first.",
        ["os.calc_tblset_title"] = "Table setup",
        ["os.calc_tblset_start"] = "Start",
        ["os.calc_tblset_step"] = "Step",
        ["os.calc_tblset_bad"] = "The step cannot be zero.",
        ["os.calc_table_empty"] = "No functions are switched on.",
        ["os.calc_menu_tour"] = "Start the tour",
        ["os.calc_menu_clear_history"] = "Clear the tape",
        ["os.calc_menu_reset_window"] = "Reset the graph window",
        ["os.calc_tour_s0_title"] = "A whole graphing calculator",
        ["os.calc_tour_s0_body"] = "It types, it plots and it tabulates, all inside your phone.",
        ["os.calc_tour_s0_f1"] = "Full expressions with powers, roots and logs",
        ["os.calc_tour_s0_f2"] = "Four functions plotted at once",
        ["os.calc_tour_s0_f3"] = "A value table beside every curve",
        ["os.calc_tour_s1_title"] = "The keypad",
        ["os.calc_tour_s1_body"] = "Every key has three faces. Press 2nd or ALPHA first to reach the other two.",
        ["os.calc_tour_s1_f1"] = "2nd turns on the amber legend above each key",
        ["os.calc_tour_s1_f2"] = "ALPHA types the green letters A to Z",
        ["os.calc_tour_s1_f3"] = "DEL rubs out a character, CLEAR wipes the line",
        ["os.calc_tour_s2_title"] = "Y= and the graph",
        ["os.calc_tour_s2_body"] = "Type up to four functions of x, then watch them draw.",
        ["os.calc_tour_s2_f2"] = "A gap in a curve means it has no value there",
        ["os.calc_tour_s3_title"] = "Trace and zoom",
        ["os.calc_tour_s3_body"] = "Walk along a curve and read its numbers, or move the window around it.",
        ["os.calc_tour_s3_f1"] = "Drag the plot to pan, scroll to zoom",
        ["os.calc_tour_s3_f2"] = "ZOOM has standard, trig, square and fit",
        ["os.calc_tour_s3_f3"] = "CALC finds roots, extremes, slopes and areas",
        ["os.calc_tour_s4_title"] = "The table",
        ["os.calc_tour_s4_body"] = "Pick where x starts and how far it steps, and read every function down the page.",
        ["os.calc_tour_s4_f1"] = "TBLSET sets the start and the step",
        ["os.calc_tour_s4_f2"] = "One column per switched-on function",
        ["os.calc_tour_s4_hint"] = "That is the whole machine. Go and use it.",
        ["os.calc_tour_start_btn"] = "Start calculating",
    };

    private static readonly IReadOnlyDictionary<string, string> De = new Dictionary<string, string>
    {
        // added after update 2.3.3 (calculator)
        ["os.calc_deg"] = "GRAD",
        ["os.calc_rad"] = "BOG",
        ["os.calc_history_empty"] = "Tipp etwas ein und drück ENTER.",
        ["os.calc_sto_prompt"] = "STO: erst ALPHA, dann einen Buchstaben.",
        ["os.calc_stored"] = "Gespeichert: {0} = {1}",
        ["os.calc_err_syntax"] = "Syntaxfehler",
        ["os.calc_err_domain"] = "Außerhalb des Definitionsbereichs",
        ["os.calc_err_divzero"] = "Division durch null",
        ["os.calc_err_overflow"] = "Zahl zu groß",
        ["os.calc_err_undefined"] = "Nicht definiert",
        ["os.calc_err_depth"] = "Ausdruck zu verschachtelt",
        ["os.calc_err_generic"] = "Fehler",
        ["os.calc_view_home"] = "Start",
        ["os.calc_view_trace"] = "Verfolgen",
        ["os.calc_view_tblset"] = "Setup",
        ["os.calc_view_graph"] = "Graph",
        ["os.calc_view_table"] = "Tabelle",
        ["os.calc_graph_no_functions"] = "Keine Funktion ist aktiv. Öffne Y= und tipp eine ein.",
        ["os.calc_mode_simple"] = "Einfacher Rechner",
        ["os.calc_mode_simple_hint"] = "Das Alltagsfeld: vier Grundrechenarten, Prozent und ein laufender Streifen.",
        ["os.calc_mode_graphing"] = "Grafikrechner",
        ["os.calc_mode_graphing_hint"] = "Der ganze Taschenrechner: Funktionen, Plots, Trace und Wertetabellen.",
        ["os.calc_tour_mode_title"] = "Welchen Rechner möchtest du?",
        ["os.calc_tour_mode_body"] = "Der eine rechnet die Reparaturrechnung aus, der andere zeichnet Kurven. Nimm, was gerade passt, festgelegt ist damit nichts.",
        ["os.calc_tour_mode_switch"] = "Wechseln kannst du jederzeit über das Menü oben rechts.",
        ["os.calc_tour_simple_title"] = "Fertig, wenn du es bist",
        ["os.calc_tour_simple_body"] = "Tipp eine Rechnung und drück =, oder nutz das Tastenfeld. Jedes Ergebnis bleibt oben auf dem Streifen, und Ans hält das letzte.",
        ["os.calc_tour_simple_f1"] = "Tipp direkt in die Eingabezeile oder nimm die Tasten",
        ["os.calc_tour_simple_f2"] = "Der Streifen behält jedes ausgerechnete Ergebnis",
        ["os.calc_tour_simple_f3"] = "Wechsle zum Grafikrechner, wann immer du ihn brauchst",
        ["os.calc_tour_s2_step1"] = "1. Y= drücken und einen Platz wählen",
        ["os.calc_tour_s2_step2"] = "2. Einen Ausdruck mit x eintippen, etwa x^2-3",
        ["os.calc_tour_s2_step3"] = "3. GRAPH drücken, fertig gezeichnet",
        ["os.calc_tour_s2_slots"] = "Vier Plätze, Y1 bis Y4, jeder in eigener Farbe gezeichnet",
        ["os.calc_graph_how_to"] = "Y= drücken, etwas mit x eintippen, dann GRAPH.",
        ["os.calc_graph_add_function"] = "Y= öffnen",
        ["os.calc_trace_hint"] = "Zieh den Plot zum Verschieben, scroll zum Zoomen.",
        ["os.calc_y_title"] = "Y=-Editor",
        ["os.calc_y_hint"] = "Schreib x als Variable, etwa x^2-3. Schalt eine Zeile ab, um sie auszublenden.",
        ["os.calc_window_title"] = "Fenster",
        ["os.calc_window_xmin"] = "x min",
        ["os.calc_window_xmax"] = "x max",
        ["os.calc_window_ymin"] = "y min",
        ["os.calc_window_ymax"] = "y max",
        ["os.calc_window_apply"] = "Übernehmen",
        ["os.calc_window_bad"] = "Jedes Minimum muss unter seinem Maximum liegen.",
        ["os.calc_zoom_title"] = "Zoom",
        ["os.calc_zoom_standard"] = "Standard",
        ["os.calc_zoom_trig"] = "Trigo",
        ["os.calc_zoom_square"] = "Quadrat",
        ["os.calc_zoom_fit"] = "Anpassen",
        ["os.calc_zoom_in"] = "Heranzoomen",
        ["os.calc_zoom_out"] = "Herauszoomen",
        ["os.calc_calc_title"] = "Calc",
        ["os.calc_calc_root"] = "Nullstelle",
        ["os.calc_calc_min"] = "Minimum",
        ["os.calc_calc_max"] = "Maximum",
        ["os.calc_calc_intersect"] = "Schnittpunkt",
        ["os.calc_calc_derivative"] = "dy/dx",
        ["os.calc_calc_integral"] = "Integral",
        ["os.calc_calc_first"] = "Erste Funktion",
        ["os.calc_calc_second"] = "Zweite Funktion",
        ["os.calc_calc_lower"] = "Untere Grenze",
        ["os.calc_calc_upper"] = "Obere Grenze",
        ["os.calc_calc_at"] = "Bei x",
        ["os.calc_calc_run"] = "Berechnen",
        ["os.calc_calc_none"] = "In diesem Bereich nichts gefunden.",
        ["os.calc_no_function"] = "Schalt zuerst eine Funktion ein.",
        ["os.calc_tblset_title"] = "Tabellen-Setup",
        ["os.calc_tblset_start"] = "Start",
        ["os.calc_tblset_step"] = "Schritt",
        ["os.calc_tblset_bad"] = "Der Schritt darf nicht null sein.",
        ["os.calc_table_empty"] = "Keine Funktion ist aktiv.",
        ["os.calc_menu_tour"] = "Tour starten",
        ["os.calc_menu_clear_history"] = "Verlauf löschen",
        ["os.calc_menu_reset_window"] = "Fenster zurücksetzen",
        ["os.calc_tour_s0_title"] = "Ein echter Grafikrechner",
        ["os.calc_tour_s0_body"] = "Er rechnet, zeichnet und tabelliert, alles auf deinem Handy.",
        ["os.calc_tour_s0_f1"] = "Ganze Ausdrücke mit Potenzen, Wurzeln und Logarithmen",
        ["os.calc_tour_s0_f2"] = "Vier Funktionen gleichzeitig im Plot",
        ["os.calc_tour_s0_f3"] = "Eine Wertetabelle zu jeder Kurve",
        ["os.calc_tour_s1_title"] = "Das Tastenfeld",
        ["os.calc_tour_s1_body"] = "Jede Taste hat drei Gesichter. Drück erst 2nd oder ALPHA für die anderen beiden.",
        ["os.calc_tour_s1_f1"] = "2nd aktiviert die bernsteinfarbene Beschriftung über der Taste",
        ["os.calc_tour_s1_f2"] = "ALPHA tippt die grünen Buchstaben A bis Z",
        ["os.calc_tour_s1_f3"] = "DEL löscht ein Zeichen, CLEAR die ganze Zeile",
        ["os.calc_tour_s2_title"] = "Y= und der Graph",
        ["os.calc_tour_s2_body"] = "Tipp bis zu vier Funktionen von x ein und sieh ihnen beim Zeichnen zu.",
        ["os.calc_tour_s2_f2"] = "Eine Lücke heißt: dort gibt es keinen Wert",
        ["os.calc_tour_s3_title"] = "Trace und Zoom",
        ["os.calc_tour_s3_body"] = "Lauf die Kurve entlang und lies die Zahlen ab, oder verschieb das Fenster.",
        ["os.calc_tour_s3_f1"] = "Zieh den Plot zum Verschieben, scroll zum Zoomen",
        ["os.calc_tour_s3_f2"] = "ZOOM bietet Standard, Trigo, Quadrat und Anpassen",
        ["os.calc_tour_s3_f3"] = "CALC findet Nullstellen, Extrema, Steigungen und Flächen",
        ["os.calc_tour_s4_title"] = "Die Tabelle",
        ["os.calc_tour_s4_body"] = "Leg fest, wo x beginnt und wie weit es springt, und lies alles Zeile für Zeile.",
        ["os.calc_tour_s4_f1"] = "TBLSET setzt Start und Schrittweite",
        ["os.calc_tour_s4_f2"] = "Eine Spalte pro eingeschalteter Funktion",
        ["os.calc_tour_s4_hint"] = "Das ist die ganze Maschine. Viel Spaß damit.",
        ["os.calc_tour_start_btn"] = "Los rechnen",
    };

    private static readonly IReadOnlyDictionary<string, string> Es = new Dictionary<string, string>
    {
        // added after update 2.3.3 (calculator)
        ["os.calc_deg"] = "GRA",
        ["os.calc_rad"] = "RAD",
        ["os.calc_history_empty"] = "Escribe algo y pulsa ENTER.",
        ["os.calc_sto_prompt"] = "STO: pulsa ALPHA y luego una letra.",
        ["os.calc_stored"] = "Guardado: {0} = {1}",
        ["os.calc_err_syntax"] = "Error de sintaxis",
        ["os.calc_err_domain"] = "Fuera del dominio",
        ["os.calc_err_divzero"] = "División entre cero",
        ["os.calc_err_overflow"] = "Número demasiado grande",
        ["os.calc_err_undefined"] = "Indefinido",
        ["os.calc_err_depth"] = "Expresión demasiado anidada",
        ["os.calc_err_generic"] = "Error",
        ["os.calc_view_home"] = "Inicio",
        ["os.calc_view_trace"] = "Trazar",
        ["os.calc_view_tblset"] = "Ajustes",
        ["os.calc_view_graph"] = "Gráfica",
        ["os.calc_view_table"] = "Tabla",
        ["os.calc_graph_no_functions"] = "No hay ninguna función activa. Abre Y= y escribe una.",
        ["os.calc_mode_simple"] = "Calculadora sencilla",
        ["os.calc_mode_simple_hint"] = "El teclado de cada día: cuatro operaciones, porcentaje y una cinta con el historial.",
        ["os.calc_mode_graphing"] = "Calculadora gráfica",
        ["os.calc_mode_graphing_hint"] = "La calculadora completa: funciones, gráficas, trazado y tablas de valores.",
        ["os.calc_tour_mode_title"] = "¿Qué calculadora quieres?",
        ["os.calc_tour_mode_body"] = "Una sirve para calcular una factura, la otra dibuja curvas. Elige la que te venga bien ahora, no queda nada fijado.",
        ["os.calc_tour_mode_switch"] = "Puedes cambiar cuando quieras desde el menú de arriba a la derecha.",
        ["os.calc_tour_simple_title"] = "Lista cuando tú lo estés",
        ["os.calc_tour_simple_body"] = "Escribe una cuenta y pulsa =, o usa el teclado. Cada resultado se queda en la cinta de arriba, y Ans guarda el último.",
        ["os.calc_tour_simple_f1"] = "Escribe directamente en la línea de entrada o usa las teclas",
        ["os.calc_tour_simple_f2"] = "La cinta guarda todos los resultados que has sacado",
        ["os.calc_tour_simple_f3"] = "Cambia a la calculadora gráfica cuando la necesites",
        ["os.calc_tour_s2_step1"] = "1. Pulsa Y= y elige una ranura",
        ["os.calc_tour_s2_step2"] = "2. Escribe una expresión con x, como x^2-3",
        ["os.calc_tour_s2_step3"] = "3. Pulsa GRAPH para dibujarla",
        ["os.calc_tour_s2_slots"] = "Cuatro ranuras, de Y1 a Y4, cada una con su color",
        ["os.calc_graph_how_to"] = "Pulsa Y=, escribe algo con x y pulsa GRAPH.",
        ["os.calc_graph_add_function"] = "Abrir Y=",
        ["os.calc_trace_hint"] = "Arrastra la gráfica para moverla, usa la rueda para acercar.",
        ["os.calc_y_title"] = "Editor Y=",
        ["os.calc_y_hint"] = "Usa x como variable, por ejemplo x^2-3. Apaga una línea para ocultarla.",
        ["os.calc_window_title"] = "Ventana",
        ["os.calc_window_xmin"] = "x mín",
        ["os.calc_window_xmax"] = "x máx",
        ["os.calc_window_ymin"] = "y mín",
        ["os.calc_window_ymax"] = "y máx",
        ["os.calc_window_apply"] = "Aplicar",
        ["os.calc_window_bad"] = "Cada mínimo debe ser menor que su máximo.",
        ["os.calc_zoom_title"] = "Zoom",
        ["os.calc_zoom_standard"] = "Estándar",
        ["os.calc_zoom_trig"] = "Trigo",
        ["os.calc_zoom_square"] = "Cuadrado",
        ["os.calc_zoom_fit"] = "Ajustar",
        ["os.calc_zoom_in"] = "Acercar",
        ["os.calc_zoom_out"] = "Alejar",
        ["os.calc_calc_title"] = "Calc",
        ["os.calc_calc_root"] = "Raíz",
        ["os.calc_calc_min"] = "Mínimo",
        ["os.calc_calc_max"] = "Máximo",
        ["os.calc_calc_intersect"] = "Intersección",
        ["os.calc_calc_derivative"] = "dy/dx",
        ["os.calc_calc_integral"] = "Integral",
        ["os.calc_calc_first"] = "Primera función",
        ["os.calc_calc_second"] = "Segunda función",
        ["os.calc_calc_lower"] = "Límite inferior",
        ["os.calc_calc_upper"] = "Límite superior",
        ["os.calc_calc_at"] = "En x",
        ["os.calc_calc_run"] = "Calcular",
        ["os.calc_calc_none"] = "No se ha encontrado nada en ese rango.",
        ["os.calc_no_function"] = "Enciende antes una función.",
        ["os.calc_tblset_title"] = "Ajustes de tabla",
        ["os.calc_tblset_start"] = "Inicio",
        ["os.calc_tblset_step"] = "Paso",
        ["os.calc_tblset_bad"] = "El paso no puede ser cero.",
        ["os.calc_table_empty"] = "No hay ninguna función activa.",
        ["os.calc_menu_tour"] = "Empezar el tour",
        ["os.calc_menu_clear_history"] = "Borrar el historial",
        ["os.calc_menu_reset_window"] = "Restablecer la ventana",
        ["os.calc_tour_s0_title"] = "Una calculadora gráfica entera",
        ["os.calc_tour_s0_body"] = "Calcula, dibuja y tabula, todo dentro de tu teléfono.",
        ["os.calc_tour_s0_f1"] = "Expresiones completas con potencias, raíces y logaritmos",
        ["os.calc_tour_s0_f2"] = "Cuatro funciones dibujadas a la vez",
        ["os.calc_tour_s0_f3"] = "Una tabla de valores junto a cada curva",
        ["os.calc_tour_s1_title"] = "El teclado",
        ["os.calc_tour_s1_body"] = "Cada tecla tiene tres caras. Pulsa 2nd o ALPHA para llegar a las otras dos.",
        ["os.calc_tour_s1_f1"] = "2nd activa la leyenda ámbar de encima de la tecla",
        ["os.calc_tour_s1_f2"] = "ALPHA escribe las letras verdes de la A a la Z",
        ["os.calc_tour_s1_f3"] = "DEL borra un carácter y CLEAR limpia la línea",
        ["os.calc_tour_s2_title"] = "Y= y la gráfica",
        ["os.calc_tour_s2_body"] = "Escribe hasta cuatro funciones de x y míralas dibujarse.",
        ["os.calc_tour_s2_f2"] = "Un hueco en la curva significa que ahí no hay valor",
        ["os.calc_tour_s3_title"] = "Trace y zoom",
        ["os.calc_tour_s3_body"] = "Recorre la curva leyendo sus números o mueve la ventana a tu gusto.",
        ["os.calc_tour_s3_f1"] = "Arrastra para desplazar, usa la rueda para el zoom",
        ["os.calc_tour_s3_f2"] = "ZOOM trae estándar, trigo, cuadrado y ajustar",
        ["os.calc_tour_s3_f3"] = "CALC encuentra raíces, extremos, pendientes y áreas",
        ["os.calc_tour_s4_title"] = "La tabla",
        ["os.calc_tour_s4_body"] = "Elige dónde empieza x y cuánto avanza, y lee cada función hacia abajo.",
        ["os.calc_tour_s4_f1"] = "TBLSET fija el inicio y el paso",
        ["os.calc_tour_s4_f2"] = "Una columna por cada función encendida",
        ["os.calc_tour_s4_hint"] = "Esta es toda la máquina. Ve a usarla.",
        ["os.calc_tour_start_btn"] = "Empezar a calcular",
    };

    private static readonly IReadOnlyDictionary<string, string> Fr = new Dictionary<string, string>
    {
        // added after update 2.3.3 (calculator)
        ["os.calc_deg"] = "DEG",
        ["os.calc_rad"] = "RAD",
        ["os.calc_history_empty"] = "Tapez quelque chose, puis appuyez sur ENTER.",
        ["os.calc_sto_prompt"] = "STO : appuyez sur ALPHA, puis sur une lettre.",
        ["os.calc_stored"] = "Enregistré : {0} = {1}",
        ["os.calc_err_syntax"] = "Erreur de syntaxe",
        ["os.calc_err_domain"] = "Hors du domaine",
        ["os.calc_err_divzero"] = "Division par zéro",
        ["os.calc_err_overflow"] = "Nombre trop grand",
        ["os.calc_err_undefined"] = "Non défini",
        ["os.calc_err_depth"] = "Expression trop imbriquée",
        ["os.calc_err_generic"] = "Erreur",
        ["os.calc_view_home"] = "Accueil",
        ["os.calc_view_trace"] = "Tracer",
        ["os.calc_view_tblset"] = "Réglages",
        ["os.calc_view_graph"] = "Graphe",
        ["os.calc_view_table"] = "Table",
        ["os.calc_graph_no_functions"] = "Aucune fonction n'est active. Ouvrez Y= et saisissez-en une.",
        ["os.calc_mode_simple"] = "Calculatrice simple",
        ["os.calc_mode_simple_hint"] = "Le clavier de tous les jours : quatre opérations, pourcentage et un ruban d'historique.",
        ["os.calc_mode_graphing"] = "Calculatrice graphique",
        ["os.calc_mode_graphing_hint"] = "La calculatrice complète : fonctions, courbes, trace et tables de valeurs.",
        ["os.calc_tour_mode_title"] = "Quelle calculatrice voulez-vous ?",
        ["os.calc_tour_mode_body"] = "L'une calcule une note de réparation, l'autre trace des courbes. Prenez celle qui vous arrange, rien n'est figé.",
        ["os.calc_tour_mode_switch"] = "Vous pouvez changer à tout moment depuis le menu en haut à droite.",
        ["os.calc_tour_simple_title"] = "Prête quand vous l'êtes",
        ["os.calc_tour_simple_body"] = "Tapez un calcul et appuyez sur =, ou servez-vous du clavier. Chaque résultat reste sur le ruban au-dessus, et Ans garde le dernier.",
        ["os.calc_tour_simple_f1"] = "Tapez directement dans la ligne de saisie ou utilisez les touches",
        ["os.calc_tour_simple_f2"] = "Le ruban conserve tous les résultats obtenus",
        ["os.calc_tour_simple_f3"] = "Passez à la calculatrice graphique dès que vous en avez besoin",
        ["os.calc_tour_s2_step1"] = "1. Appuyez sur Y= et choisissez une ligne",
        ["os.calc_tour_s2_step2"] = "2. Tapez une expression avec x, par exemple x^2-3",
        ["os.calc_tour_s2_step3"] = "3. Appuyez sur GRAPH pour la tracer",
        ["os.calc_tour_s2_slots"] = "Quatre lignes, Y1 à Y4, chacune tracée dans sa couleur",
        ["os.calc_graph_how_to"] = "Appuyez sur Y=, tapez quelque chose avec x, puis GRAPH.",
        ["os.calc_graph_add_function"] = "Ouvrir Y=",
        ["os.calc_trace_hint"] = "Faites glisser le graphe pour vous déplacer, molette pour zoomer.",
        ["os.calc_y_title"] = "Éditeur Y=",
        ["os.calc_y_hint"] = "Utilisez x comme variable, par exemple x^2-3. Désactivez une ligne pour la masquer.",
        ["os.calc_window_title"] = "Fenêtre",
        ["os.calc_window_xmin"] = "x min",
        ["os.calc_window_xmax"] = "x max",
        ["os.calc_window_ymin"] = "y min",
        ["os.calc_window_ymax"] = "y max",
        ["os.calc_window_apply"] = "Appliquer",
        ["os.calc_window_bad"] = "Chaque minimum doit rester sous son maximum.",
        ["os.calc_zoom_title"] = "Zoom",
        ["os.calc_zoom_standard"] = "Standard",
        ["os.calc_zoom_trig"] = "Trigo",
        ["os.calc_zoom_square"] = "Carré",
        ["os.calc_zoom_fit"] = "Ajuster",
        ["os.calc_zoom_in"] = "Zoom avant",
        ["os.calc_zoom_out"] = "Zoom arrière",
        ["os.calc_calc_title"] = "Calc",
        ["os.calc_calc_root"] = "Racine",
        ["os.calc_calc_min"] = "Minimum",
        ["os.calc_calc_max"] = "Maximum",
        ["os.calc_calc_intersect"] = "Intersection",
        ["os.calc_calc_derivative"] = "dy/dx",
        ["os.calc_calc_integral"] = "Intégrale",
        ["os.calc_calc_first"] = "Première fonction",
        ["os.calc_calc_second"] = "Deuxième fonction",
        ["os.calc_calc_lower"] = "Borne inférieure",
        ["os.calc_calc_upper"] = "Borne supérieure",
        ["os.calc_calc_at"] = "En x",
        ["os.calc_calc_run"] = "Calculer",
        ["os.calc_calc_none"] = "Rien trouvé dans cet intervalle.",
        ["os.calc_no_function"] = "Activez d'abord une fonction.",
        ["os.calc_tblset_title"] = "Réglages de la table",
        ["os.calc_tblset_start"] = "Début",
        ["os.calc_tblset_step"] = "Pas",
        ["os.calc_tblset_bad"] = "Le pas ne peut pas être nul.",
        ["os.calc_table_empty"] = "Aucune fonction n'est active.",
        ["os.calc_menu_tour"] = "Lancer la visite",
        ["os.calc_menu_clear_history"] = "Effacer l'historique",
        ["os.calc_menu_reset_window"] = "Réinitialiser la fenêtre",
        ["os.calc_tour_s0_title"] = "Une vraie calculatrice graphique",
        ["os.calc_tour_s0_body"] = "Elle calcule, elle trace et elle tabule, le tout dans votre téléphone.",
        ["os.calc_tour_s0_f1"] = "Des expressions complètes : puissances, racines, logarithmes",
        ["os.calc_tour_s0_f2"] = "Quatre fonctions tracées en même temps",
        ["os.calc_tour_s0_f3"] = "Une table de valeurs à côté de chaque courbe",
        ["os.calc_tour_s1_title"] = "Le clavier",
        ["os.calc_tour_s1_body"] = "Chaque touche a trois visages. Appuyez sur 2nd ou ALPHA pour atteindre les deux autres.",
        ["os.calc_tour_s1_f1"] = "2nd active la légende ambre au-dessus de la touche",
        ["os.calc_tour_s1_f2"] = "ALPHA tape les lettres vertes de A à Z",
        ["os.calc_tour_s1_f3"] = "DEL efface un caractère, CLEAR vide la ligne",
        ["os.calc_tour_s2_title"] = "Y= et le graphe",
        ["os.calc_tour_s2_body"] = "Saisissez jusqu'à quatre fonctions de x et regardez-les se tracer.",
        ["os.calc_tour_s2_f2"] = "Un trou dans la courbe veut dire qu'il n'y a pas de valeur",
        ["os.calc_tour_s3_title"] = "Trace et zoom",
        ["os.calc_tour_s3_body"] = "Parcourez la courbe et lisez ses nombres, ou déplacez la fenêtre autour.",
        ["os.calc_tour_s3_f1"] = "Glissez pour vous déplacer, molette pour zoomer",
        ["os.calc_tour_s3_f2"] = "ZOOM propose standard, trigo, carré et ajuster",
        ["os.calc_tour_s3_f3"] = "CALC trouve racines, extremums, pentes et aires",
        ["os.calc_tour_s4_title"] = "La table",
        ["os.calc_tour_s4_body"] = "Choisissez où x commence et de combien il avance, puis lisez chaque fonction.",
        ["os.calc_tour_s4_f1"] = "TBLSET fixe le début et le pas",
        ["os.calc_tour_s4_f2"] = "Une colonne par fonction activée",
        ["os.calc_tour_s4_hint"] = "Voilà toute la machine. À vous de jouer.",
        ["os.calc_tour_start_btn"] = "Commencer à calculer",
    };

    private static readonly IReadOnlyDictionary<string, string> Pt = new Dictionary<string, string>
    {
        // added after update 2.3.3 (calculator)
        ["os.calc_deg"] = "GRA",
        ["os.calc_rad"] = "RAD",
        ["os.calc_history_empty"] = "Escreva algo e aperte ENTER.",
        ["os.calc_sto_prompt"] = "STO: aperte ALPHA e depois uma letra.",
        ["os.calc_stored"] = "Guardado: {0} = {1}",
        ["os.calc_err_syntax"] = "Erro de sintaxe",
        ["os.calc_err_domain"] = "Fora do domínio",
        ["os.calc_err_divzero"] = "Divisão por zero",
        ["os.calc_err_overflow"] = "Número grande demais",
        ["os.calc_err_undefined"] = "Indefinido",
        ["os.calc_err_depth"] = "Expressão aninhada demais",
        ["os.calc_err_generic"] = "Erro",
        ["os.calc_view_home"] = "Início",
        ["os.calc_view_trace"] = "Traçar",
        ["os.calc_view_tblset"] = "Ajustes",
        ["os.calc_view_graph"] = "Gráfico",
        ["os.calc_view_table"] = "Tabela",
        ["os.calc_graph_no_functions"] = "Nenhuma função está ligada. Abra o Y= e escreva uma.",
        ["os.calc_mode_simple"] = "Calculadora simples",
        ["os.calc_mode_simple_hint"] = "O teclado do dia a dia: quatro operações, percentagem e uma fita com o histórico.",
        ["os.calc_mode_graphing"] = "Calculadora gráfica",
        ["os.calc_mode_graphing_hint"] = "A calculadora completa: funções, gráficos, traçado e tabelas de valores.",
        ["os.calc_tour_mode_title"] = "Qual calculadora queres?",
        ["os.calc_tour_mode_body"] = "Uma serve para calcular uma conta, a outra desenha curvas. Escolhe a que te der jeito agora, nada fica fechado.",
        ["os.calc_tour_mode_switch"] = "Podes trocar quando quiseres pelo menu no canto superior direito.",
        ["os.calc_tour_simple_title"] = "Pronta quando tu estiveres",
        ["os.calc_tour_simple_body"] = "Escreve uma conta e carrega em =, ou usa o teclado. Cada resultado fica na fita acima, e Ans guarda o último.",
        ["os.calc_tour_simple_f1"] = "Escreve direto na linha de entrada ou usa as teclas",
        ["os.calc_tour_simple_f2"] = "A fita guarda todos os resultados que já tiraste",
        ["os.calc_tour_simple_f3"] = "Muda para a calculadora gráfica sempre que precisares",
        ["os.calc_tour_s2_step1"] = "1. Carrega em Y= e escolhe uma linha",
        ["os.calc_tour_s2_step2"] = "2. Escreve uma expressão com x, tipo x^2-3",
        ["os.calc_tour_s2_step3"] = "3. Carrega em GRAPH para desenhar",
        ["os.calc_tour_s2_slots"] = "Quatro linhas, Y1 a Y4, cada uma na sua cor",
        ["os.calc_graph_how_to"] = "Carrega em Y=, escreve algo com x e depois GRAPH.",
        ["os.calc_graph_add_function"] = "Abrir Y=",
        ["os.calc_trace_hint"] = "Arraste o gráfico para mover, use a roda para dar zoom.",
        ["os.calc_y_title"] = "Editor Y=",
        ["os.calc_y_hint"] = "Use x como variável, tipo x^2-3. Desligue uma linha para escondê-la.",
        ["os.calc_window_title"] = "Janela",
        ["os.calc_window_xmin"] = "x mín",
        ["os.calc_window_xmax"] = "x máx",
        ["os.calc_window_ymin"] = "y mín",
        ["os.calc_window_ymax"] = "y máx",
        ["os.calc_window_apply"] = "Aplicar",
        ["os.calc_window_bad"] = "Cada mínimo precisa ficar abaixo do seu máximo.",
        ["os.calc_zoom_title"] = "Zoom",
        ["os.calc_zoom_standard"] = "Padrão",
        ["os.calc_zoom_trig"] = "Trigo",
        ["os.calc_zoom_square"] = "Quadrado",
        ["os.calc_zoom_fit"] = "Ajustar",
        ["os.calc_zoom_in"] = "Aproximar",
        ["os.calc_zoom_out"] = "Afastar",
        ["os.calc_calc_title"] = "Calc",
        ["os.calc_calc_root"] = "Raiz",
        ["os.calc_calc_min"] = "Mínimo",
        ["os.calc_calc_max"] = "Máximo",
        ["os.calc_calc_intersect"] = "Interseção",
        ["os.calc_calc_derivative"] = "dy/dx",
        ["os.calc_calc_integral"] = "Integral",
        ["os.calc_calc_first"] = "Primeira função",
        ["os.calc_calc_second"] = "Segunda função",
        ["os.calc_calc_lower"] = "Limite inferior",
        ["os.calc_calc_upper"] = "Limite superior",
        ["os.calc_calc_at"] = "Em x",
        ["os.calc_calc_run"] = "Calcular",
        ["os.calc_calc_none"] = "Nada encontrado nesse intervalo.",
        ["os.calc_no_function"] = "Ligue uma função primeiro.",
        ["os.calc_tblset_title"] = "Ajustes da tabela",
        ["os.calc_tblset_start"] = "Início",
        ["os.calc_tblset_step"] = "Passo",
        ["os.calc_tblset_bad"] = "O passo não pode ser zero.",
        ["os.calc_table_empty"] = "Nenhuma função está ligada.",
        ["os.calc_menu_tour"] = "Começar o tour",
        ["os.calc_menu_clear_history"] = "Limpar o histórico",
        ["os.calc_menu_reset_window"] = "Redefinir a janela",
        ["os.calc_tour_s0_title"] = "Uma calculadora gráfica inteira",
        ["os.calc_tour_s0_body"] = "Ela calcula, desenha e tabela, tudo dentro do seu telefone.",
        ["os.calc_tour_s0_f1"] = "Expressões completas com potências, raízes e logaritmos",
        ["os.calc_tour_s0_f2"] = "Quatro funções desenhadas ao mesmo tempo",
        ["os.calc_tour_s0_f3"] = "Uma tabela de valores ao lado de cada curva",
        ["os.calc_tour_s1_title"] = "O teclado",
        ["os.calc_tour_s1_body"] = "Cada tecla tem três caras. Aperte 2nd ou ALPHA para chegar nas outras duas.",
        ["os.calc_tour_s1_f1"] = "2nd liga a legenda âmbar acima da tecla",
        ["os.calc_tour_s1_f2"] = "ALPHA escreve as letras verdes de A a Z",
        ["os.calc_tour_s1_f3"] = "DEL apaga um caractere, CLEAR limpa a linha",
        ["os.calc_tour_s2_title"] = "Y= e o gráfico",
        ["os.calc_tour_s2_body"] = "Escreva até quatro funções de x e veja elas se desenharem.",
        ["os.calc_tour_s2_f2"] = "Um buraco na curva quer dizer que ali não há valor",
        ["os.calc_tour_s3_title"] = "Trace e zoom",
        ["os.calc_tour_s3_body"] = "Ande pela curva lendo os números ou mova a janela em volta dela.",
        ["os.calc_tour_s3_f1"] = "Arraste para mover, use a roda para o zoom",
        ["os.calc_tour_s3_f2"] = "O ZOOM traz padrão, trigo, quadrado e ajustar",
        ["os.calc_tour_s3_f3"] = "O CALC acha raízes, extremos, inclinações e áreas",
        ["os.calc_tour_s4_title"] = "A tabela",
        ["os.calc_tour_s4_body"] = "Escolha onde x começa e de quanto em quanto ele anda, e leia tudo linha a linha.",
        ["os.calc_tour_s4_f1"] = "O TBLSET define o início e o passo",
        ["os.calc_tour_s4_f2"] = "Uma coluna para cada função ligada",
        ["os.calc_tour_s4_hint"] = "É a máquina inteira. Vai lá usar.",
        ["os.calc_tour_start_btn"] = "Começar a calcular",
    };

    private static readonly IReadOnlyDictionary<string, string> Ru = new Dictionary<string, string>
    {
        // added after update 2.3.3 (calculator)
        ["os.calc_deg"] = "ГРАД",
        ["os.calc_rad"] = "РАД",
        ["os.calc_history_empty"] = "Наберите выражение и нажмите ENTER.",
        ["os.calc_sto_prompt"] = "STO: нажмите ALPHA, затем букву.",
        ["os.calc_stored"] = "Сохранено: {0} = {1}",
        ["os.calc_err_syntax"] = "Ошибка в записи",
        ["os.calc_err_domain"] = "Вне области определения",
        ["os.calc_err_divzero"] = "Деление на ноль",
        ["os.calc_err_overflow"] = "Слишком большое число",
        ["os.calc_err_undefined"] = "Не определено",
        ["os.calc_err_depth"] = "Слишком много вложений",
        ["os.calc_err_generic"] = "Ошибка",
        ["os.calc_view_home"] = "Главная",
        ["os.calc_view_trace"] = "Трасса",
        ["os.calc_view_tblset"] = "Настройки",
        ["os.calc_view_graph"] = "График",
        ["os.calc_view_table"] = "Таблица",
        ["os.calc_graph_no_functions"] = "Ни одна функция не включена. Откройте Y= и впишите её.",
        ["os.calc_mode_simple"] = "Простой калькулятор",
        ["os.calc_mode_simple_hint"] = "Обычная клавиатура: четыре действия, проценты и лента с историей.",
        ["os.calc_mode_graphing"] = "Графический калькулятор",
        ["os.calc_mode_graphing_hint"] = "Полноценный аппарат: функции, графики, трассировка и таблицы значений.",
        ["os.calc_tour_mode_title"] = "Какой калькулятор нужен?",
        ["os.calc_tour_mode_body"] = "Один посчитает счёт за ремонт, другой построит кривую. Выбирай, что удобнее сейчас, ничего не фиксируется навсегда.",
        ["os.calc_tour_mode_switch"] = "Переключиться можно в любой момент через меню справа вверху.",
        ["os.calc_tour_simple_title"] = "Всё готово",
        ["os.calc_tour_simple_body"] = "Набери пример и нажми =, или пользуйся клавишами. Каждый ответ остаётся на ленте сверху, а Ans хранит последний.",
        ["os.calc_tour_simple_f1"] = "Набирай прямо в строке ввода или жми клавиши",
        ["os.calc_tour_simple_f2"] = "Лента хранит все посчитанные ответы",
        ["os.calc_tour_simple_f3"] = "Переключайся на графический, когда он понадобится",
        ["os.calc_tour_s2_step1"] = "1. Нажми Y= и выбери строку",
        ["os.calc_tour_s2_step2"] = "2. Введи выражение с x, например x^2-3",
        ["os.calc_tour_s2_step3"] = "3. Нажми GRAPH, и график построится",
        ["os.calc_tour_s2_slots"] = "Четыре строки, от Y1 до Y4, у каждой свой цвет",
        ["os.calc_graph_how_to"] = "Нажми Y=, введи что-нибудь с x, затем GRAPH.",
        ["os.calc_graph_add_function"] = "Открыть Y=",
        ["os.calc_trace_hint"] = "Тяните график мышью, колесо приближает.",
        ["os.calc_y_title"] = "Редактор Y=",
        ["os.calc_y_hint"] = "Переменная это x, например x^2-3. Выключите строку, чтобы спрятать её.",
        ["os.calc_window_title"] = "Окно",
        ["os.calc_window_xmin"] = "x мин",
        ["os.calc_window_xmax"] = "x макс",
        ["os.calc_window_ymin"] = "y мин",
        ["os.calc_window_ymax"] = "y макс",
        ["os.calc_window_apply"] = "Применить",
        ["os.calc_window_bad"] = "Минимум должен быть меньше максимума.",
        ["os.calc_zoom_title"] = "Масштаб",
        ["os.calc_zoom_standard"] = "Стандарт",
        ["os.calc_zoom_trig"] = "Триг.",
        ["os.calc_zoom_square"] = "Квадрат",
        ["os.calc_zoom_fit"] = "По данным",
        ["os.calc_zoom_in"] = "Приблизить",
        ["os.calc_zoom_out"] = "Отдалить",
        ["os.calc_calc_title"] = "Calc",
        ["os.calc_calc_root"] = "Корень",
        ["os.calc_calc_min"] = "Минимум",
        ["os.calc_calc_max"] = "Максимум",
        ["os.calc_calc_intersect"] = "Пересечение",
        ["os.calc_calc_derivative"] = "dy/dx",
        ["os.calc_calc_integral"] = "Интеграл",
        ["os.calc_calc_first"] = "Первая функция",
        ["os.calc_calc_second"] = "Вторая функция",
        ["os.calc_calc_lower"] = "Нижняя граница",
        ["os.calc_calc_upper"] = "Верхняя граница",
        ["os.calc_calc_at"] = "При x",
        ["os.calc_calc_run"] = "Посчитать",
        ["os.calc_calc_none"] = "В этом диапазоне ничего не нашлось.",
        ["os.calc_no_function"] = "Сначала включите функцию.",
        ["os.calc_tblset_title"] = "Настройка таблицы",
        ["os.calc_tblset_start"] = "Начало",
        ["os.calc_tblset_step"] = "Шаг",
        ["os.calc_tblset_bad"] = "Шаг не может быть нулевым.",
        ["os.calc_table_empty"] = "Ни одна функция не включена.",
        ["os.calc_menu_tour"] = "Запустить тур",
        ["os.calc_menu_clear_history"] = "Очистить ленту",
        ["os.calc_menu_reset_window"] = "Сбросить окно графика",
        ["os.calc_tour_s0_title"] = "Полноценный графический калькулятор",
        ["os.calc_tour_s0_body"] = "Считает, рисует и сводит в таблицу, прямо в телефоне.",
        ["os.calc_tour_s0_f1"] = "Целые выражения со степенями, корнями и логарифмами",
        ["os.calc_tour_s0_f2"] = "Сразу четыре функции на одном поле",
        ["os.calc_tour_s0_f3"] = "Таблица значений рядом с каждой кривой",
        ["os.calc_tour_s1_title"] = "Клавиатура",
        ["os.calc_tour_s1_body"] = "У каждой клавиши три значения. Нажмите 2nd или ALPHA, чтобы добраться до остальных.",
        ["os.calc_tour_s1_f1"] = "2nd включает янтарную надпись над клавишей",
        ["os.calc_tour_s1_f2"] = "ALPHA печатает зелёные буквы от A до Z",
        ["os.calc_tour_s1_f3"] = "DEL стирает символ, CLEAR очищает строку",
        ["os.calc_tour_s2_title"] = "Y= и график",
        ["os.calc_tour_s2_body"] = "Впишите до четырёх функций от x и смотрите, как они рисуются.",
        ["os.calc_tour_s2_f2"] = "Разрыв в кривой значит, что там нет значения",
        ["os.calc_tour_s3_title"] = "Трассировка и масштаб",
        ["os.calc_tour_s3_body"] = "Пройдитесь по кривой и считайте числа или подвиньте окно вокруг неё.",
        ["os.calc_tour_s3_f1"] = "Тяните график мышью, колесо меняет масштаб",
        ["os.calc_tour_s3_f2"] = "В ZOOM есть стандарт, тригонометрия, квадрат и подгонка",
        ["os.calc_tour_s3_f3"] = "CALC находит корни, экстремумы, наклон и площадь",
        ["os.calc_tour_s4_title"] = "Таблица",
        ["os.calc_tour_s4_body"] = "Задайте, где начинается x и с каким шагом он идёт, и читайте столбцы вниз.",
        ["os.calc_tour_s4_f1"] = "TBLSET задаёт начало и шаг",
        ["os.calc_tour_s4_f2"] = "По колонке на каждую включённую функцию",
        ["os.calc_tour_s4_hint"] = "Вот и вся машина. Пользуйтесь.",
        ["os.calc_tour_start_btn"] = "Начать считать",
    };

    public static readonly IReadOnlyDictionary<string, IReadOnlyDictionary<string, string>> Packs =
        new Dictionary<string, IReadOnlyDictionary<string, string>>
        {
            ["en"] = En,
            ["de"] = De,
            ["es"] = Es,
            ["fr"] = Fr,
            ["pt"] = Pt,
            ["ru"] = Ru,
        };
}
