using System.Collections.Generic;

namespace AetherOS.Apps.Racer.Localization;

public static partial class AppStrings
{
    // added after update 2.7.0 (racing cards)
    private static readonly IReadOnlyDictionary<string, string> CardsEs = new Dictionary<string, string>
    {
        // Album (the Bonus cards tab)
        ["os.racer_album_intro"] = "Los sobres de premios te dan cartas de carreras. Elige una carta de Oro y dos cartas de Plata para tu mano.",
        ["os.racer_album_levels"] = "Un sobre puede darte una carta que ya tienes. Entonces esa carta sube un nivel. En el nivel 2, su efecto es un 15% más fuerte. En el nivel 3, es un 30% más fuerte. Los sobres dejan de darte una carta cuando llega al nivel 3.",
        ["os.racer_album_filter_elements"] = "Todos los elementos",
        ["os.racer_album_filter_cards"] = "Todas las cartas",
        ["os.racer_album_filter_gold"] = "Oro",
        ["os.racer_album_filter_silver"] = "Plata",
        ["os.racer_album_compact"] = "Compacto",
        ["os.racer_album_search"] = "Buscar una carta",
        ["os.racer_album_no_match"] = "Ninguna carta coincide. Cambia los filtros.",
        ["os.racer_album_none"] = "Aún no tienes cartas de carreras. Abre sobres de premios para conseguirlas.",
        ["os.racer_album_progress"] = "{0} de {1} cartas encontradas",
        ["os.racer_album_copies"] = "{0} copias",
        ["os.racer_album_not_found"] = "Aún no encontrada",
        // Hand dock and hand strips
        ["os.racer_hand_title"] = "Cartas de carrera",
        ["os.racer_hand_choose_gold"] = "Elegir Oro",
        ["os.racer_hand_choose_silver"] = "Elegir Plata",
        ["os.racer_hand_swap"] = "Cambiar",
        ["os.racer_hand_remove"] = "Quitar",
        ["os.racer_hand_saved"] = "Mano guardada",
        ["os.racer_hand_saving"] = "Guardando tu mano...",
        ["os.racer_hand_race"] = "Correr con esta mano",
        ["os.racer_hand_change"] = "Cambiar mano",
        ["os.racer_hand_enter_cup"] = "Entrar con esta mano",
        ["os.racer_hand_locked_cup"] = "Fijada para esta copa",
        ["os.racer_hand_empty"] = "Tu mano está vacía. Añade cartas desde tu álbum.",
        ["os.racer_hand_slot_gold"] = "Ranura de Oro",
        ["os.racer_hand_slot_silver"] = "Ranura de Plata {0}",
        ["os.racer_hand_in_hand"] = "En la mano",
        // Hand faults: one sentence per rule the server or the local check can refuse on
        ["os.racer_hand_fault_unknown"] = "Esa carta ya no está en el juego. Elige otra.",
        ["os.racer_hand_fault_not_owned"] = "No tienes esa carta.",
        ["os.racer_hand_fault_wrong_band"] = "Las cartas de Oro van en la ranura de Oro. Las cartas de Plata van en las ranuras de Plata.",
        ["os.racer_hand_fault_duplicate"] = "Esa carta ya está en tu mano.",
        ["os.racer_hand_fault_shape"] = "Una mano lleva una carta de Oro y dos cartas de Plata.",
        ["os.racer_hand_fault_failed"] = "Tu mano no se ha guardado. Inténtalo de nuevo.",
        // Inspect page
        ["os.racer_inspect_tab_card"] = "Carta",
        ["os.racer_inspect_tab_art"] = "Arte",
        ["os.racer_inspect_tab_info"] = "Info",
        ["os.racer_inspect_when"] = "Cuándo funciona",
        ["os.racer_inspect_how"] = "Cómo funciona",
        ["os.racer_inspect_exact"] = "Reglas y números exactos",
        ["os.racer_inspect_story"] = "Historia y acabado",
        ["os.racer_inspect_flip"] = "Dar la vuelta a la carta",
        ["os.racer_card_gold"] = "Carta de Oro",
        ["os.racer_card_silver"] = "Carta de Plata",
        ["os.racer_card_automatic"] = "Automática",
        ["os.racer_card_once"] = "Una vez por carrera",
        ["os.racer_card_passive"] = "Pasiva",
        ["os.racer_card_rank"] = "N.º {0}",
        ["os.racer_card_level"] = "Nivel {0}",
        ["os.racer_card_level_max"] = "Nivel máximo",
        ["os.racer_card_effect_bonus"] = "Efecto +{0}%",
        ["os.racer_card_copy_of"] = "Copia {0} de {1}",
        ["os.racer_card_equip_gold"] = "Poner en la ranura de Oro",
        ["os.racer_card_equip_silver_1"] = "Poner en la ranura de Plata 1",
        ["os.racer_card_equip_silver_2"] = "Poner en la ranura de Plata 2",
        ["os.racer_card_unequip"] = "Quitar de la mano",
        ["os.racer_card_locked"] = "Aún no tienes esta carta. Puede salir en un sobre de premios.",
        // In-race notice and the result line
        ["os.racer_notice_gold_used"] = "Usó una carta de Oro",
        ["os.racer_replay_unavailable"] = "Esta carrera usó cartas más nuevas que las que conoce tu plugin. Actualiza el plugin para verla. El resultado cuenta igual.",
        // Pack reveal and the starter grant
        ["os.racer_pack_prize_card"] = "Carta de carreras",
        ["os.racer_card_reveal_new"] = "Carta nueva",
        ["os.racer_card_reveal_level_up"] = "Ahora nivel {0}",
        ["os.racer_cards_starter_title"] = "Tus primeras cartas",
        ["os.racer_cards_starter_body"] = "Tienes tres cartas de carreras para empezar. Ya están en tu mano.",
        // Guard texts shared by every card of one operation kind. RaceCardGuards maps a card id to its index.
        ["os.racer_card_guard_1"] = "Tu Lumi se cansa más despacio mientras corre. Sus sprints lo cansan igual que antes. Esta carta no devuelve la energía que tu Lumi ya ha gastado.",
        ["os.racer_card_guard_2"] = "Tu Lumi corre con más astucia. Elige mejores caminos entre los demás corredores. Encuentra más huecos para adelantarlos. Tropieza menos. También se cansa un poco menos. Si las dos cartas de Plata hacen esto, los dos efectos se suman, pero solo hasta un límite.",
        ["os.racer_card_guard_3"] = "Tu Lumi empieza sus propios sprints más a menudo. Cada sprint es igual de rápido y de largo que antes. Los Lumis solo empiezan sus propios sprints en la última parte de la carrera. Tu Lumi sigue necesitando un descanso corto entre sprints.",
        ["os.racer_card_guard_4"] = "La velocidad máxima de tu Lumi es un poco mayor durante toda la carrera. También puede mantener un ritmo algo más rápido antes de cansarse. Las curvas, los otros corredores y el cansancio siguen frenándolo. Por eso su tiempo de llegada no mejora en la misma cantidad.",
        ["os.racer_card_guard_5"] = "Esta carta solo ayuda en la salida. Tu Lumi sale un poco antes. Cada Lumi sigue esperando al menos 0,04 segundos antes de poder salir.",
        ["os.racer_card_guard_6"] = "Tu Lumi recupera algo de energía y puede correr más tiempo antes de cansarse. La carta solo funciona si tu Lumi ya ha gastado al menos esa cantidad de energía. Si tu Lumi se está quedando sin fuerzas, eso termina. La cantidad es una parte de su energía total, no de la que le queda.",
        ["os.racer_card_guard_7"] = "La carta solo funciona mientras tu Lumi está tropezando. Hace que ese tropiezo termine antes. Si el tropiezo casi ha terminado, termina en el acto. No evita que tu Lumi vuelva a tropezar más tarde.",
        ["os.racer_card_guard_8"] = "Tu Lumi corre más rápido durante un momento. Ya debe correr al 75% de su velocidad máxima o más. Después de la carta, a tu Lumi le debe quedar más del 15% de su energía. No puede ocurrir si tu Lumi se está quedando sin fuerzas, está encerrado, está tropezando o está haciendo un sprint. Tampoco puede ocurrir justo después de un sprint. Si tu Lumi está a punto de empezar su sprint final, la carta espera. Las curvas y los otros corredores aún pueden frenar a tu Lumi. Después, tu Lumi vuelve a su velocidad máxima normal.",
        ["os.racer_card_guard_9"] = "Tu Lumi hace un sprint durante un momento. Debe haber una recta delante. Después de la carta, a tu Lumi le debe quedar más del 15% de su energía. No puede ocurrir si tu Lumi se está quedando sin fuerzas, está encerrado, está tropezando o está haciendo un sprint. Tampoco puede ocurrir justo después de un sprint. Si tu Lumi está a punto de empezar su sprint final, la carta espera. El sprint es igual de rápido que los sprints propios de tu Lumi. Después, tu Lumi puede volver a empezar sus propios sprints enseguida.",
        // The 54 Core Set cards in catalogue order: name, face caption, availability, description, exact rule, story.
        ["os.racer_card_second_sunrise_name"] = "Segundo Amanecer",
        ["os.racer_card_second_sunrise_short"] = "Recupera energía al cansarse",
        ["os.racer_card_second_sunrise_cond"] = "Cuando a tu Lumi le queda poca energía.",
        ["os.racer_card_second_sunrise_desc"] = "Cuando a tu Lumi le queda poca energía, recupera algo de energía. Espera hasta que le quede muy poca.",
        ["os.racer_card_second_sunrise_exact"] = "Funciona una vez por carrera. Tu Lumi recupera el 5% de su energía. Solo si a tu Lumi le queda el 24% de su energía o menos. Puede ocurrir después del primer cuarto de la carrera, hasta cerca de la meta.",
        ["os.racer_card_second_sunrise_story"] = "La mañana encontró una brasa más.",

        ["os.racer_card_banked_embers_name"] = "Brasas Guardadas",
        ["os.racer_card_banked_embers_short"] = "Se cansa menos",
        ["os.racer_card_banked_embers_cond"] = "Durante toda la carrera.",
        ["os.racer_card_banked_embers_desc"] = "Tu Lumi se cansa un poco más despacio durante toda la carrera. Le queda un poco más de energía cerca de la meta.",
        ["os.racer_card_banked_embers_exact"] = "Funciona durante toda la carrera. Tu Lumi se cansa aproximadamente un 2,4% menos.",
        ["os.racer_card_banked_embers_story"] = "Un calor pequeño puede durar mucho camino.",

        ["os.racer_card_lantern_vigil_name"] = "Vigilia del Farol",
        ["os.racer_card_lantern_vigil_short"] = "Más astuto al final",
        ["os.racer_card_lantern_vigil_cond"] = "Al final de la carrera, hasta la meta.",
        ["os.racer_card_lantern_vigil_desc"] = "Al final de la carrera, tu Lumi corre con más astucia. Encuentra más huecos para adelantar a otros corredores. También tropieza menos.",
        ["os.racer_card_lantern_vigil_exact"] = "Funciona al final de la carrera, hasta la meta. Tu Lumi corre con más astucia. El efecto es medio.",
        ["os.racer_card_lantern_vigil_story"] = "Siempre hay alguien que te deja una luz encendida.",

        ["os.racer_card_warm_footing_name"] = "Pisada Cálida",
        ["os.racer_card_warm_footing_short"] = "Más astuto con mal tiempo",
        ["os.racer_card_warm_footing_cond"] = "Durante toda la carrera. Solo con lluvia, nieve, viento fuerte, calor, estática o polvo.",
        ["os.racer_card_warm_footing_desc"] = "Con mal tiempo, tu Lumi corre con más astucia. Encuentra más huecos para adelantar a otros corredores. También tropieza menos.",
        ["os.racer_card_warm_footing_exact"] = "Funciona durante toda la carrera. Tu Lumi corre con más astucia. El efecto es pequeño. Solo con lluvia, nieve, viento fuerte, calor, estática o polvo.",
        ["os.racer_card_warm_footing_story"] = "Encontró la única piedra que el invierno olvidó.",

        ["os.racer_card_cinder_leap_name"] = "Salto de Ceniza",
        ["os.racer_card_cinder_leap_short"] = "Sprint para perseguir al líder",
        ["os.racer_card_cinder_leap_cond"] = "Mientras tu Lumi va detrás del líder.",
        ["os.racer_card_cinder_leap_desc"] = "A mitad de la carrera, tu Lumi hace un sprint para perseguir al líder. Debe haber una recta delante.",
        ["os.racer_card_cinder_leap_exact"] = "Funciona una vez por carrera. Tu Lumi hace un sprint de 0,55 segundos. Esto gasta el 1% de su energía. El líder debe ir al menos 1,2 cuerpos por delante. Puede ocurrir a mitad de la carrera.",
        ["os.racer_card_cinder_leap_story"] = "Por un latido, hasta las cenizas volaron.",

        ["os.racer_card_slow_burn_name"] = "Fuego Lento",
        ["os.racer_card_slow_burn_short"] = "Se cansa menos en subida",
        ["os.racer_card_slow_burn_cond"] = "En subida.",
        ["os.racer_card_slow_burn_desc"] = "En subida, tu Lumi se cansa más despacio. Le queda más energía para el resto de la carrera.",
        ["os.racer_card_slow_burn_exact"] = "Funciona siempre que tu Lumi corre en subida. Tu Lumi se cansa aproximadamente un 7% menos.",
        ["os.racer_card_slow_burn_story"] = "La cuesta fue paciente. La brasa también.",

        ["os.racer_card_sheltered_spark_name"] = "Chispa al Abrigo",
        ["os.racer_card_sheltered_spark_short"] = "Más sprints con mal tiempo",
        ["os.racer_card_sheltered_spark_cond"] = "Durante toda la carrera. Solo con lluvia, nieve, viento fuerte, calor, estática o polvo.",
        ["os.racer_card_sheltered_spark_desc"] = "Con mal tiempo, tu Lumi empieza sus propios sprints más a menudo.",
        ["os.racer_card_sheltered_spark_exact"] = "Funciona durante toda la carrera. Tu Lumi empieza sus propios sprints un 11% más a menudo. Solo con lluvia, nieve, viento fuerte, calor, estática o polvo.",
        ["os.racer_card_sheltered_spark_story"] = "La lluvia podía esperar fuera.",

        ["os.racer_card_home_by_firelight_name"] = "Hogar a la Lumbre",
        ["os.racer_card_home_by_firelight_short"] = "Velocidad máxima mayor",
        ["os.racer_card_home_by_firelight_cond"] = "Durante toda la carrera.",
        ["os.racer_card_home_by_firelight_desc"] = "Tu Lumi corre un poquito más rápido durante toda la carrera.",
        ["os.racer_card_home_by_firelight_exact"] = "Funciona durante toda la carrera. La velocidad máxima de tu Lumi es un poco mayor. En una carrera larga, eso lo pone hasta unos 0,3 cuerpos más adelante.",
        ["os.racer_card_home_by_firelight_story"] = "Los últimos pasos olían a hogar.",

        ["os.racer_card_last_light_name"] = "La Última Luz",
        ["os.racer_card_last_light_short"] = "Sprint para perseguir al líder",
        ["os.racer_card_last_light_cond"] = "Mientras tu Lumi va detrás del líder.",
        ["os.racer_card_last_light_desc"] = "Cerca del final de la carrera, tu Lumi hace un sprint para perseguir al líder. Debe haber una recta delante.",
        ["os.racer_card_last_light_exact"] = "Funciona una vez por carrera. Tu Lumi hace un sprint de 0,65 segundos. Esto gasta el 1% de su energía. El líder debe ir al menos 0,5 cuerpos por delante. Puede ocurrir cerca del final de la carrera.",
        ["os.racer_card_last_light_story"] = "Guardó un pensamiento brillante para el final.",

        ["os.racer_card_storm_whispers_name"] = "Susurros de Tormenta",
        ["os.racer_card_storm_whispers_short"] = "Corre con más astucia",
        ["os.racer_card_storm_whispers_cond"] = "Durante toda la carrera.",
        ["os.racer_card_storm_whispers_desc"] = "Tu Lumi corre con más astucia durante toda la carrera. Encuentra más huecos para adelantar a otros corredores. También tropieza menos.",
        ["os.racer_card_storm_whispers_exact"] = "Funciona durante toda la carrera. Tu Lumi corre con más astucia. El efecto es pequeño.",
        ["os.racer_card_storm_whispers_story"] = "El chisporroteo más suave lo avisó primero.",

        ["os.racer_card_borrowed_thunder_name"] = "Trueno Prestado",
        ["os.racer_card_borrowed_thunder_short"] = "Sprint en una recta",
        ["os.racer_card_borrowed_thunder_cond"] = "En una recta.",
        ["os.racer_card_borrowed_thunder_desc"] = "A mitad de la carrera, tu Lumi hace un sprint en una recta.",
        ["os.racer_card_borrowed_thunder_exact"] = "Funciona una vez por carrera. Tu Lumi hace un sprint de 0,45 segundos. Esto gasta el 1% de su energía. Puede ocurrir a mitad de la carrera.",
        ["os.racer_card_borrowed_thunder_story"] = "Una nube pequeña respondió muy alto.",

        ["os.racer_card_paper_promises_name"] = "Promesas de Papel",
        ["os.racer_card_paper_promises_short"] = "Sale antes",
        ["os.racer_card_paper_promises_cond"] = "En la salida.",
        ["os.racer_card_paper_promises_desc"] = "Tu Lumi sale antes.",
        ["os.racer_card_paper_promises_exact"] = "Funciona en la salida de la carrera. La espera de tu Lumi en la salida es un 4% más corta. Cada Lumi sigue esperando al menos 0,04 segundos.",
        ["os.racer_card_paper_promises_story"] = "Mantuvo su forma cuando cambió el viento.",

        ["os.racer_card_blink_of_brilliance_name"] = "Destello Brillante",
        ["os.racer_card_blink_of_brilliance_short"] = "Acelera cuando deja de estar bloqueado",
        ["os.racer_card_blink_of_brilliance_cond"] = "Justo después de que tu Lumi deja de estar bloqueado, mientras aún tiene un corredor delante.",
        ["os.racer_card_blink_of_brilliance_desc"] = "Justo después de que otro corredor deja de bloquear a tu Lumi, corre más rápido durante un momento. Esto puede pasar en casi toda la carrera.",
        ["os.racer_card_blink_of_brilliance_exact"] = "Funciona una vez por carrera, desde poco después de la salida hasta cerca de la meta. La velocidad máxima de tu Lumi es un 8% mayor durante 1,4 segundos. Esto gasta el 1% de su energía. Solo en el primer segundo después de que tu Lumi deja de estar bloqueado. Debe haber un corredor delante.",
        ["os.racer_card_blink_of_brilliance_story"] = "La respuesta estuvo ahí un momento.",

        ["os.racer_card_quiet_charge_name"] = "Carga Silenciosa",
        ["os.racer_card_quiet_charge_short"] = "Más sprints",
        ["os.racer_card_quiet_charge_cond"] = "Durante toda la carrera.",
        ["os.racer_card_quiet_charge_desc"] = "Tu Lumi empieza sus propios sprints más a menudo durante toda la carrera.",
        ["os.racer_card_quiet_charge_exact"] = "Funciona durante toda la carrera. Tu Lumi empieza sus propios sprints un 7,5% más a menudo.",
        ["os.racer_card_quiet_charge_story"] = "No había prisa por gastar la chispa.",

        ["os.racer_card_copper_company_name"] = "Compañía de Cobre",
        ["os.racer_card_copper_company_short"] = "Se cansa menos detrás de otro",
        ["os.racer_card_copper_company_cond"] = "Mientras sigue de cerca a otro corredor.",
        ["os.racer_card_copper_company_desc"] = "Mientras tu Lumi sigue de cerca a otro corredor, se cansa más despacio. La ayuda termina cuando deja de seguirlo de cerca.",
        ["os.racer_card_copper_company_exact"] = "Funciona siempre que tu Lumi sigue de cerca a otro corredor. Tu Lumi se cansa aproximadamente un 9,1% menos.",
        ["os.racer_card_copper_company_story"] = "El camino sonaba más amable en compañía.",

        ["os.racer_card_after_the_flash_name"] = "Tras el Relámpago",
        ["os.racer_card_after_the_flash_short"] = "Más astuto tras tropiezos con mal tiempo",
        ["os.racer_card_after_the_flash_cond"] = "Justo después de un tropiezo. Solo con lluvia, nieve, viento fuerte, calor, estática o polvo.",
        ["os.racer_card_after_the_flash_desc"] = "Con mal tiempo, justo después de un tropiezo, tu Lumi corre con más astucia durante poco tiempo. Encuentra más huecos para adelantar a otros corredores. Es menos probable que vuelva a tropezar.",
        ["os.racer_card_after_the_flash_exact"] = "Funciona en los 2 segundos siguientes al final de cada tropiezo. Tu Lumi corre con más astucia. El efecto es grande. Solo con lluvia, nieve, viento fuerte, calor, estática o polvo.",
        ["os.racer_card_after_the_flash_story"] = "Los charcos lo recordaban. Siguió adelante.",

        ["os.racer_card_bright_idea_name"] = "Idea Brillante",
        ["os.racer_card_bright_idea_short"] = "Más astuto en curvas",
        ["os.racer_card_bright_idea_cond"] = "En una curva.",
        ["os.racer_card_bright_idea_desc"] = "En las curvas, tu Lumi corre con más astucia. Encuentra más huecos para adelantar a otros corredores. También tropieza menos.",
        ["os.racer_card_bright_idea_exact"] = "Funciona siempre que tu Lumi corre en una curva. Tu Lumi corre con más astucia. El efecto es medio.",
        ["os.racer_card_bright_idea_story"] = "Vio un camino entre las gotas de lluvia.",

        ["os.racer_card_catch_the_spark_name"] = "Atrapa la Chispa",
        ["os.racer_card_catch_the_spark_short"] = "Sprint tras un tropiezo",
        ["os.racer_card_catch_the_spark_cond"] = "Justo después de un tropiezo.",
        ["os.racer_card_catch_the_spark_desc"] = "Justo después de un tropiezo, tu Lumi hace un sprint para arrancar de nuevo. Debe haber una recta delante.",
        ["os.racer_card_catch_the_spark_exact"] = "Funciona una vez por carrera. Tu Lumi hace un sprint de 0,5 segundos. Esto gasta el 1% de su energía. Solo en los 2 segundos siguientes al final de un tropiezo. Puede ocurrir desde poco después de la salida hasta cerca de la meta.",
        ["os.racer_card_catch_the_spark_story"] = "No era tarde para darse cuenta.",

        ["os.racer_card_featherlight_steps_name"] = "Pasos de Pluma",
        ["os.racer_card_featherlight_steps_short"] = "Se cansa menos al principio",
        ["os.racer_card_featherlight_steps_cond"] = "En el primer tercio de la carrera.",
        ["os.racer_card_featherlight_steps_desc"] = "En el primer tercio de la carrera, tu Lumi se cansa más despacio. Le queda más energía para más adelante.",
        ["os.racer_card_featherlight_steps_exact"] = "Funciona en el primer tercio de la carrera. Tu Lumi se cansa aproximadamente un 3,8% menos.",
        ["os.racer_card_featherlight_steps_story"] = "La hierba apenas notó que había pasado.",

        ["os.racer_card_leeward_path_name"] = "Senda a Sotavento",
        ["os.racer_card_leeward_path_short"] = "Se cansa menos con viento",
        ["os.racer_card_leeward_path_cond"] = "Durante toda la carrera. Solo con viento fuerte.",
        ["os.racer_card_leeward_path_desc"] = "Con viento fuerte, tu Lumi se cansa más despacio durante toda la carrera. Le queda más energía cerca de la meta.",
        ["os.racer_card_leeward_path_exact"] = "Funciona durante toda la carrera. Tu Lumi se cansa aproximadamente un 4,8% menos. Solo con viento fuerte.",
        ["os.racer_card_leeward_path_story"] = "La colina guardaba un poco de calma en este lado.",

        ["os.racer_card_thread_the_gust_name"] = "Entre Ráfagas",
        ["os.racer_card_thread_the_gust_short"] = "Acelera cuando deja de estar bloqueado",
        ["os.racer_card_thread_the_gust_cond"] = "Justo después de que tu Lumi deja de estar bloqueado, mientras aún tiene un corredor delante.",
        ["os.racer_card_thread_the_gust_desc"] = "A mitad de la carrera, justo después de que otro corredor deja de bloquear a tu Lumi, corre más rápido durante un momento.",
        ["os.racer_card_thread_the_gust_exact"] = "Funciona una vez por carrera, a mitad de la carrera. La velocidad máxima de tu Lumi es un 9% mayor durante 1,5 segundos. Esto gasta el 1% de su energía. Solo en el primer segundo después de que tu Lumi deja de estar bloqueado. Debe haber un corredor delante.",
        ["os.racer_card_thread_the_gust_story"] = "La brisa dejó el hueco justo.",

        ["os.racer_card_lift_together_name"] = "Impulso Compartido",
        ["os.racer_card_lift_together_short"] = "Recupera energía detrás de otro",
        ["os.racer_card_lift_together_cond"] = "Mientras corre justo detrás de otro corredor.",
        ["os.racer_card_lift_together_desc"] = "A mitad de la carrera, tu Lumi recupera algo de energía. Debe correr justo detrás de otro corredor, no a un lado.",
        ["os.racer_card_lift_together_exact"] = "Funciona una vez por carrera. Tu Lumi recupera el 4% de su energía. Solo mientras tu Lumi corre justo detrás de otro corredor. Puede ocurrir a mitad de la carrera.",
        ["os.racer_card_lift_together_story"] = "El valor viajaba en la misma brisa.",

        ["os.racer_card_ribbon_weather_name"] = "Tiempo de Cintas",
        ["os.racer_card_ribbon_weather_short"] = "Más astuto con cielo despejado",
        ["os.racer_card_ribbon_weather_cond"] = "Durante toda la carrera. Solo con cielo despejado.",
        ["os.racer_card_ribbon_weather_desc"] = "Con cielo despejado, tu Lumi corre con más astucia durante toda la carrera. Encuentra más huecos para adelantar a otros corredores. También tropieza menos.",
        ["os.racer_card_ribbon_weather_exact"] = "Funciona durante toda la carrera. Tu Lumi corre con más astucia. El efecto es pequeño. Solo con cielo despejado.",
        ["os.racer_card_ribbon_weather_story"] = "Un solo aleteo fue todo el aviso que necesitó.",

        ["os.racer_card_long_glide_name"] = "El Largo Planeo",
        ["os.racer_card_long_glide_short"] = "Se cansa menos con cielo despejado",
        ["os.racer_card_long_glide_cond"] = "Durante toda la carrera. Solo con cielo despejado.",
        ["os.racer_card_long_glide_desc"] = "Con cielo despejado, tu Lumi se cansa más despacio durante toda la carrera. Le queda más energía cerca de la meta.",
        ["os.racer_card_long_glide_exact"] = "Funciona durante toda la carrera. Tu Lumi se cansa aproximadamente un 2,7% menos. Solo con cielo despejado.",
        ["os.racer_card_long_glide_story"] = "Había tiempo para dejar que el aire hiciera su parte.",

        ["os.racer_card_pocket_of_calm_name"] = "Rincón de Calma",
        ["os.racer_card_pocket_of_calm_short"] = "Más astuto en grupo",
        ["os.racer_card_pocket_of_calm_cond"] = "Con otros corredores cerca.",
        ["os.racer_card_pocket_of_calm_desc"] = "Cuando hay al menos otros 2 corredores cerca, tu Lumi corre con más astucia. Encuentra más huecos para adelantarlos.",
        ["os.racer_card_pocket_of_calm_exact"] = "Funciona siempre que hay al menos otros 2 corredores cerca. Tu Lumi corre con más astucia. El efecto es medio.",
        ["os.racer_card_pocket_of_calm_story"] = "Hizo hueco para una respiración tranquila.",

        ["os.racer_card_borrowed_wings_name"] = "Alas Prestadas",
        ["os.racer_card_borrowed_wings_short"] = "Tropiezo tardío más corto",
        ["os.racer_card_borrowed_wings_cond"] = "Mientras tu Lumi está tropezando.",
        ["os.racer_card_borrowed_wings_desc"] = "En la segunda mitad de la carrera, esta carta hace que un tropiezo termine antes.",
        ["os.racer_card_borrowed_wings_exact"] = "Funciona una vez por carrera. El tropiezo de tu Lumi termina hasta 0,35 segundos antes. Solo mientras tu Lumi está tropezando. Puede ocurrir en la segunda mitad de la carrera.",
        ["os.racer_card_borrowed_wings_story"] = "La siguiente respiración ya venía de camino.",

        ["os.racer_card_home_on_the_breeze_name"] = "A Casa con la Brisa",
        ["os.racer_card_home_on_the_breeze_short"] = "Más rápido con mal tiempo",
        ["os.racer_card_home_on_the_breeze_cond"] = "Durante toda la carrera. Solo con lluvia, nieve, viento fuerte, calor, estática o polvo.",
        ["os.racer_card_home_on_the_breeze_desc"] = "Con mal tiempo, tu Lumi corre un poquito más rápido durante toda la carrera.",
        ["os.racer_card_home_on_the_breeze_exact"] = "Funciona durante toda la carrera. La velocidad máxima de tu Lumi es un poco mayor. En una carrera larga, eso lo pone hasta unos 0,43 cuerpos más adelante. Solo con lluvia, nieve, viento fuerte, calor, estática o polvo.",
        ["os.racer_card_home_on_the_breeze_story"] = "Reconocía el jardín por cómo respiraba.",

        ["os.racer_card_quiet_footing_name"] = "Pisada Serena",
        ["os.racer_card_quiet_footing_short"] = "Más astuto en curvas cerradas",
        ["os.racer_card_quiet_footing_cond"] = "En una curva cerrada.",
        ["os.racer_card_quiet_footing_desc"] = "En las curvas cerradas, tu Lumi corre con más astucia. Encuentra más huecos para adelantar a otros corredores. También tropieza menos.",
        ["os.racer_card_quiet_footing_exact"] = "Funciona siempre que tu Lumi corre en una curva cerrada. Tu Lumi corre con más astucia. El efecto es grande.",
        ["os.racer_card_quiet_footing_story"] = "La escarcha dejó sitio a unos pies cuidadosos.",

        ["os.racer_card_winter_reprieve_name"] = "Tregua de Invierno",
        ["os.racer_card_winter_reprieve_short"] = "Recupera energía con lluvia o nieve",
        ["os.racer_card_winter_reprieve_cond"] = "Cuando a tu Lumi le queda poca energía. Solo con lluvia o nieve.",
        ["os.racer_card_winter_reprieve_desc"] = "Con lluvia o nieve, cuando a tu Lumi le queda poca energía, recupera algo de energía. Puede funcionar pronto en la carrera.",
        ["os.racer_card_winter_reprieve_exact"] = "Funciona una vez por carrera. Tu Lumi recupera el 5,5% de su energía. Solo si a tu Lumi le queda el 30% de su energía o menos. Solo con lluvia o nieve. Puede ocurrir después del primer cuarto de la carrera, hasta cerca de la meta.",
        ["os.racer_card_winter_reprieve_story"] = "El frío se quedó quieto por un momento amable.",

        ["os.racer_card_clear_reflection_name"] = "Reflejo Claro",
        ["os.racer_card_clear_reflection_short"] = "Sale antes con cielo despejado",
        ["os.racer_card_clear_reflection_cond"] = "En la salida. Solo con cielo despejado.",
        ["os.racer_card_clear_reflection_desc"] = "Con cielo despejado, tu Lumi sale antes.",
        ["os.racer_card_clear_reflection_exact"] = "Funciona en la salida de la carrera. La espera de tu Lumi en la salida es un 5% más corta. Cada Lumi sigue esperando al menos 0,04 segundos. Solo con cielo despejado.",
        ["os.racer_card_clear_reflection_story"] = "Escuchaba con los ojos.",

        ["os.racer_card_under_the_snow_name"] = "Bajo la Nieve",
        ["os.racer_card_under_the_snow_short"] = "Se cansa menos con nieve",
        ["os.racer_card_under_the_snow_cond"] = "Durante toda la carrera. Solo con nieve.",
        ["os.racer_card_under_the_snow_desc"] = "Con nieve, tu Lumi se cansa más despacio durante toda la carrera. Le queda más energía cerca de la meta.",
        ["os.racer_card_under_the_snow_exact"] = "Funciona durante toda la carrera. Tu Lumi se cansa aproximadamente un 4,8% menos. Solo con nieve.",
        ["os.racer_card_under_the_snow_story"] = "El invierno mantuvo caliente su cuarto más pequeño.",

        ["os.racer_card_still_as_starlight_name"] = "Calma Estelar",
        ["os.racer_card_still_as_starlight_short"] = "Más astuto al final con cielo despejado",
        ["os.racer_card_still_as_starlight_cond"] = "Al final de la carrera, hasta la meta. Solo con cielo despejado.",
        ["os.racer_card_still_as_starlight_desc"] = "Con cielo despejado, tu Lumi corre con más astucia al final de la carrera. Encuentra más huecos para adelantar a otros corredores. También tropieza menos.",
        ["os.racer_card_still_as_starlight_exact"] = "Funciona al final de la carrera, hasta la meta. Tu Lumi corre con más astucia. El efecto es medio. Solo con cielo despejado.",
        ["os.racer_card_still_as_starlight_story"] = "Hasta las estrellas parecían bajar la voz.",

        ["os.racer_card_one_perfect_step_name"] = "Un Paso Perfecto",
        ["os.racer_card_one_perfect_step_short"] = "Acelera tras una curva",
        ["os.racer_card_one_perfect_step_cond"] = "Justo después de una curva.",
        ["os.racer_card_one_perfect_step_desc"] = "Justo después de una curva, tu Lumi corre más rápido durante un momento.",
        ["os.racer_card_one_perfect_step_exact"] = "Funciona una vez por carrera. La velocidad máxima de tu Lumi es un 8,5% mayor durante 1,4 segundos. Esto gasta el 1% de su energía. Solo en el primer segundo después de una curva. Puede ocurrir desde poco después de la salida hasta cerca de la meta.",
        ["os.racer_card_one_perfect_step_story"] = "Confió en el pequeño trozo de suelo despejado.",

        ["os.racer_card_ring_the_frost_name"] = "Toque de Escarcha",
        ["os.racer_card_ring_the_frost_short"] = "Tropiezo más corto",
        ["os.racer_card_ring_the_frost_cond"] = "Mientras tu Lumi está tropezando.",
        ["os.racer_card_ring_the_frost_desc"] = "Casi en cualquier momento de la carrera, esta carta hace que un tropiezo termine antes.",
        ["os.racer_card_ring_the_frost_exact"] = "Funciona una vez por carrera. El tropiezo de tu Lumi termina hasta 0,3 segundos antes. Solo mientras tu Lumi está tropezando. Puede ocurrir casi en cualquier momento de la carrera.",
        ["os.racer_card_ring_the_frost_story"] = "Una nota clara sacudió la preocupación.",

        ["os.racer_card_soft_landing_name"] = "Aterrizaje Suave",
        ["os.racer_card_soft_landing_short"] = "Más astuto en bajada",
        ["os.racer_card_soft_landing_cond"] = "En bajada.",
        ["os.racer_card_soft_landing_desc"] = "En bajada, tu Lumi corre con más astucia. Encuentra más huecos para adelantar a otros corredores. También tropieza menos.",
        ["os.racer_card_soft_landing_exact"] = "Funciona siempre que tu Lumi corre en bajada. Tu Lumi corre con más astucia. El efecto es grande.",
        ["os.racer_card_soft_landing_story"] = "La nieve había guardado ese sitio.",

        ["os.racer_card_thaw_comes_slowly_name"] = "Deshielo Lento",
        ["os.racer_card_thaw_comes_slowly_short"] = "Se cansa menos al final",
        ["os.racer_card_thaw_comes_slowly_cond"] = "Al final de la carrera, hasta la meta.",
        ["os.racer_card_thaw_comes_slowly_desc"] = "Al final de la carrera, tu Lumi se cansa más despacio. Le queda más energía para llegar a la meta.",
        ["os.racer_card_thaw_comes_slowly_exact"] = "Funciona al final de la carrera, hasta la meta. Tu Lumi se cansa aproximadamente un 4,8% menos.",
        ["os.racer_card_thaw_comes_slowly_story"] = "Un poco de calor bastó para empezar.",

        ["os.racer_card_follow_the_flow_name"] = "Sigue la Corriente",
        ["os.racer_card_follow_the_flow_short"] = "Se cansa menos en rectas",
        ["os.racer_card_follow_the_flow_cond"] = "En una recta.",
        ["os.racer_card_follow_the_flow_desc"] = "En las rectas, tu Lumi se cansa más despacio. Le queda más energía para el resto de la carrera.",
        ["os.racer_card_follow_the_flow_exact"] = "Funciona siempre que tu Lumi corre en una recta. Tu Lumi se cansa aproximadamente un 4,3% menos.",
        ["os.racer_card_follow_the_flow_story"] = "La corriente conocía un camino más suave.",

        ["os.racer_card_puddle_lessons_name"] = "Lección de Charcos",
        ["os.racer_card_puddle_lessons_short"] = "Más astuto tras un tropiezo",
        ["os.racer_card_puddle_lessons_cond"] = "Justo después de un tropiezo.",
        ["os.racer_card_puddle_lessons_desc"] = "Justo después de un tropiezo, tu Lumi corre con más astucia durante poco tiempo. Encuentra más huecos para adelantar a otros corredores. Es menos probable que vuelva a tropezar.",
        ["os.racer_card_puddle_lessons_exact"] = "Funciona en los 2 segundos siguientes al final de cada tropiezo. Tu Lumi corre con más astucia. El efecto es medio.",
        ["os.racer_card_puddle_lessons_story"] = "Cada charco tenía algo nuevo que decir.",

        ["os.racer_card_turning_tide_name"] = "Cambio de Marea",
        ["os.racer_card_turning_tide_short"] = "Recupera energía al cansarse",
        ["os.racer_card_turning_tide_cond"] = "Cuando a tu Lumi le queda poca energía.",
        ["os.racer_card_turning_tide_desc"] = "Desde más o menos la mitad de la carrera, cuando a tu Lumi le queda poca energía, recupera algo de energía.",
        ["os.racer_card_turning_tide_exact"] = "Funciona una vez por carrera. Tu Lumi recupera el 4% de su energía. Solo si a tu Lumi le queda el 35% de su energía o menos. Puede ocurrir desde más o menos la mitad de la carrera hasta cerca de la meta.",
        ["os.racer_card_turning_tide_story"] = "El agua ofreció otro camino para pasar.",

        ["os.racer_card_pearls_of_patience_name"] = "Perlas de Paciencia",
        ["os.racer_card_pearls_of_patience_short"] = "Más sprints en la segunda mitad",
        ["os.racer_card_pearls_of_patience_cond"] = "En la segunda mitad de la carrera.",
        ["os.racer_card_pearls_of_patience_desc"] = "En la segunda mitad de la carrera, tu Lumi empieza sus propios sprints más a menudo.",
        ["os.racer_card_pearls_of_patience_exact"] = "Funciona en la segunda mitad de la carrera. Tu Lumi empieza sus propios sprints un 13% más a menudo.",
        ["os.racer_card_pearls_of_patience_story"] = "Dejó que las burbujas subieran a su ritmo.",

        ["os.racer_card_over_the_water_name"] = "Sobre el Agua",
        ["os.racer_card_over_the_water_short"] = "Sprint para perseguir al líder",
        ["os.racer_card_over_the_water_cond"] = "Mientras tu Lumi va detrás del líder.",
        ["os.racer_card_over_the_water_desc"] = "Después del primer tercio de la carrera, tu Lumi hace un sprint para perseguir al líder. Debe haber una recta delante.",
        ["os.racer_card_over_the_water_exact"] = "Funciona una vez por carrera. Tu Lumi hace un sprint de 0,65 segundos. Esto gasta el 1% de su energía. El líder debe ir al menos 0,8 cuerpos por delante. Puede ocurrir después del primer tercio de la carrera, hasta cerca de la meta.",
        ["os.racer_card_over_the_water_story"] = "Había la piedra justa para ser valiente.",

        ["os.racer_card_rain_on_glass_name"] = "Lluvia en Cristal",
        ["os.racer_card_rain_on_glass_short"] = "Más astuto en curvas con lluvia",
        ["os.racer_card_rain_on_glass_cond"] = "En una curva. Solo con lluvia.",
        ["os.racer_card_rain_on_glass_desc"] = "En las curvas con lluvia, tu Lumi corre con más astucia. Encuentra más huecos para adelantar a otros corredores. También tropieza menos.",
        ["os.racer_card_rain_on_glass_exact"] = "Funciona siempre que tu Lumi corre en una curva. Tu Lumi corre con más astucia. El efecto es grande. Solo con lluvia.",
        ["os.racer_card_rain_on_glass_story"] = "Contó las pausas entre las gotas.",

        ["os.racer_card_ripple_returned_name"] = "Onda de Vuelta",
        ["os.racer_card_ripple_returned_short"] = "Recupera energía tras un tropiezo",
        ["os.racer_card_ripple_returned_cond"] = "Justo después de un tropiezo.",
        ["os.racer_card_ripple_returned_desc"] = "Justo después de un tropiezo, tu Lumi recupera algo de energía.",
        ["os.racer_card_ripple_returned_exact"] = "Funciona una vez por carrera. Tu Lumi recupera el 5% de su energía. Solo en los 2 segundos siguientes al final de un tropiezo. Puede ocurrir desde poco después de la salida hasta cerca de la meta.",
        ["os.racer_card_ripple_returned_story"] = "La segunda ola lo encontró preparado.",

        ["os.racer_card_low_tide_friends_name"] = "Amigos de Bajamar",
        ["os.racer_card_low_tide_friends_short"] = "Más astuto detrás de otro",
        ["os.racer_card_low_tide_friends_cond"] = "Mientras sigue de cerca a otro corredor.",
        ["os.racer_card_low_tide_friends_desc"] = "Mientras tu Lumi sigue de cerca a otro corredor, corre con más astucia. Encuentra más huecos para adelantar a otros corredores. También tropieza menos.",
        ["os.racer_card_low_tide_friends_exact"] = "Funciona siempre que tu Lumi sigue de cerca a otro corredor. Tu Lumi corre con más astucia. El efecto es grande.",
        ["os.racer_card_low_tide_friends_story"] = "Algunos viajes van mejor a ritmo de charla.",

        ["os.racer_card_smooth_pebble_promise_name"] = "Promesa de Guijarro",
        ["os.racer_card_smooth_pebble_promise_short"] = "Más rápido con cielo despejado",
        ["os.racer_card_smooth_pebble_promise_cond"] = "Durante toda la carrera. Solo con cielo despejado.",
        ["os.racer_card_smooth_pebble_promise_desc"] = "Con cielo despejado, tu Lumi corre un poquito más rápido durante toda la carrera.",
        ["os.racer_card_smooth_pebble_promise_exact"] = "Funciona durante toda la carrera. La velocidad máxima de tu Lumi es un poco mayor. En una carrera larga, eso lo pone hasta unos 0,35 cuerpos más adelante. Solo con cielo despejado.",
        ["os.racer_card_smooth_pebble_promise_story"] = "Llevó aquella cosita todo el camino de vuelta.",

        ["os.racer_card_stand_together_name"] = "Juntos en Pie",
        ["os.racer_card_stand_together_short"] = "Recupera energía en grupo",
        ["os.racer_card_stand_together_cond"] = "Con otros corredores cerca.",
        ["os.racer_card_stand_together_desc"] = "A mitad de la carrera, tu Lumi recupera algo de energía. Debe haber al menos otros 2 corredores cerca.",
        ["os.racer_card_stand_together_exact"] = "Funciona una vez por carrera. Tu Lumi recupera el 4% de su energía. Solo si hay al menos otros 2 corredores cerca. Puede ocurrir a mitad de la carrera.",
        ["os.racer_card_stand_together_story"] = "Se sentía un poco más alto junto a un amigo.",

        ["os.racer_card_roots_remember_name"] = "Raíces que Recuerdan",
        ["os.racer_card_roots_remember_short"] = "Más astuto en subida",
        ["os.racer_card_roots_remember_cond"] = "En subida.",
        ["os.racer_card_roots_remember_desc"] = "En subida, tu Lumi corre con más astucia. Encuentra más huecos para adelantar a otros corredores. También tropieza menos.",
        ["os.racer_card_roots_remember_exact"] = "Funciona siempre que tu Lumi corre en subida. Tu Lumi corre con más astucia. El efecto es grande.",
        ["os.racer_card_roots_remember_story"] = "El camino más viejo aún sabía su nombre.",

        ["os.racer_card_patient_path_name"] = "Senda Paciente",
        ["os.racer_card_patient_path_short"] = "Se cansa menos al principio con cielo despejado",
        ["os.racer_card_patient_path_cond"] = "En la primera mitad de la carrera. Solo con cielo despejado.",
        ["os.racer_card_patient_path_desc"] = "Con cielo despejado, tu Lumi se cansa más despacio en la primera mitad de la carrera. Le queda más energía para después.",
        ["os.racer_card_patient_path_exact"] = "Funciona en la primera mitad de la carrera. Tu Lumi se cansa aproximadamente un 5,2% menos. Solo con cielo despejado.",
        ["os.racer_card_patient_path_story"] = "Los pasos pequeños también lo llevaban a algún sitio.",

        ["os.racer_card_mossbound_shelter_name"] = "Refugio de Musgo",
        ["os.racer_card_mossbound_shelter_short"] = "Se cansa menos con polvo",
        ["os.racer_card_mossbound_shelter_cond"] = "Durante toda la carrera. Solo con polvo.",
        ["os.racer_card_mossbound_shelter_desc"] = "Con polvo, tu Lumi se cansa más despacio durante toda la carrera. Le queda más energía cerca de la meta.",
        ["os.racer_card_mossbound_shelter_exact"] = "Funciona durante toda la carrera. Tu Lumi se cansa aproximadamente un 4,8% menos. Solo con polvo.",
        ["os.racer_card_mossbound_shelter_story"] = "La piedra había guardado un rincón seco solo para esto.",

        ["os.racer_card_little_ballast_name"] = "Un Poco de Lastre",
        ["os.racer_card_little_ballast_short"] = "Sale antes con mal tiempo",
        ["os.racer_card_little_ballast_cond"] = "En la salida. Solo con lluvia, nieve, viento fuerte, calor, estática o polvo.",
        ["os.racer_card_little_ballast_desc"] = "Con mal tiempo, tu Lumi sale antes.",
        ["os.racer_card_little_ballast_exact"] = "Funciona en la salida de la carrera. La espera de tu Lumi en la salida es un 5,5% más corta. Cada Lumi sigue esperando al menos 0,04 segundos. Solo con lluvia, nieve, viento fuerte, calor, estática o polvo.",
        ["os.racer_card_little_ballast_story"] = "Un peso pequeño ayudó a que el mundo se sintiera firme.",

        ["os.racer_card_hold_the_hill_name"] = "Domina la Cuesta",
        ["os.racer_card_hold_the_hill_short"] = "Acelera tras una subida",
        ["os.racer_card_hold_the_hill_cond"] = "Justo después de terminar una subida.",
        ["os.racer_card_hold_the_hill_desc"] = "Justo después de terminar una subida, tu Lumi corre más rápido durante un momento.",
        ["os.racer_card_hold_the_hill_exact"] = "Funciona una vez por carrera. La velocidad máxima de tu Lumi es un 10% mayor durante 1,6 segundos. Esto gasta el 1% de su energía. Solo en el primer segundo después de terminar una subida. Puede ocurrir desde poco después de la salida hasta cerca de la meta.",
        ["os.racer_card_hold_the_hill_story"] = "La cuesta preguntó. Respondió con un empujón más.",

        ["os.racer_card_kindly_ground_name"] = "Suelo Amable",
        ["os.racer_card_kindly_ground_short"] = "Se cansa menos tras un tropiezo",
        ["os.racer_card_kindly_ground_cond"] = "Justo después de un tropiezo.",
        ["os.racer_card_kindly_ground_desc"] = "Justo después de un tropiezo, tu Lumi se cansa más despacio durante poco tiempo.",
        ["os.racer_card_kindly_ground_exact"] = "Funciona en los 2 segundos siguientes al final de cada tropiezo. Tu Lumi se cansa aproximadamente un 9,1% menos.",
        ["os.racer_card_kindly_ground_story"] = "A la tierra no le importó un momento de descanso.",

        ["os.racer_card_mountain_answers_name"] = "La Montaña Responde",
        ["os.racer_card_mountain_answers_short"] = "Tropiezo temprano más corto",
        ["os.racer_card_mountain_answers_cond"] = "Mientras tu Lumi está tropezando.",
        ["os.racer_card_mountain_answers_desc"] = "En la primera mitad de la carrera, esta carta hace que un tropiezo termine antes.",
        ["os.racer_card_mountain_answers_exact"] = "Funciona una vez por carrera. El tropiezo de tu Lumi termina hasta 0,4 segundos antes. Solo mientras tu Lumi está tropezando. Puede ocurrir en la primera mitad de la carrera.",
        ["os.racer_card_mountain_answers_story"] = "Su pequeña nota valiente encontró un eco enorme.",

        ["os.racer_card_home_in_a_shell_name"] = "Hogar en la Concha",
        ["os.racer_card_home_in_a_shell_short"] = "Se cansa menos con poca energía",
        ["os.racer_card_home_in_a_shell_cond"] = "Cuando a tu Lumi le queda poca energía.",
        ["os.racer_card_home_in_a_shell_desc"] = "Cuando a tu Lumi le queda poca energía, se cansa más despacio. Deja de ayudar en cuanto su energía vuelve a subir.",
        ["os.racer_card_home_in_a_shell_exact"] = "Funciona siempre que a tu Lumi le queda el 35% de su energía o menos. Tu Lumi se cansa aproximadamente un 6,5% menos.",
        ["os.racer_card_home_in_a_shell_story"] = "Se había traído la parte tranquila de casa.",

        ["os.racer_hand_pick_prompt"] = "{0}: toca una carta abajo.",
        ["os.racer_album_off"] = "Las cartas de carreras están desactivadas ahora mismo.",
        ["os.racer_pack_accessory"] = "Accesorio",
        ["os.racer_pack_colour"] = "Color",
        ["os.racer_card_move_silver"] = "Mover a la ranura de Plata {0}",
        ["os.racer_hand_explain"] = "Las cartas de carrera dan bonificaciones a tu {0} durante las carreras. Una carta de Oro es una carta activa que {0} usa por su cuenta. Las cartas de Plata son mejoras pasivas de distintos tipos. Elige tus cartas.",
        ["os.racer_hand_enter_the_cup"] = "Entrar en la copa",
        ["os.racer_hand_none_gold"] = "Aún no tienes cartas de Oro. Los sobres de premios pueden darte algunas.",
        ["os.racer_hand_none_silver"] = "Aún no tienes cartas de Plata. Los sobres de premios pueden darte algunas.",
        ["os.racer_cards_per_row_1"] = "Mostrar una carta por fila",
        ["os.racer_cards_per_row_2"] = "Mostrar dos cartas por fila",
        ["os.racer_cards_per_row_3"] = "Mostrar tres cartas por fila",
        ["os.racer_inspect_levels"] = "Niveles",
        ["os.racer_inspect_level_bonus"] = "{0}% de bonificación extra",
        ["os.racer_inspect_level_default"] = "Bonificación normal de la carta",
        ["os.racer_hand_lumi"] = "Lumi",
        ["os.racer_hand_info_close"] = "Cerrar",
    };
}
