using System.Collections.Generic;

namespace AetherOS.Apps.Racer.Localization;

public static partial class AppStrings
{
    // added after update 2.7.0 (racing cards)
    private static readonly IReadOnlyDictionary<string, string> CardsDe = new Dictionary<string, string>
    {
        // Album (the Bonus cards tab)
        ["os.racer_album_intro"] = "Preispäckchen geben dir Rennkarten. Wähl eine Goldkarte und zwei Silberkarten für deine Hand.",
        ["os.racer_album_levels"] = "Ein Preispäckchen kann dir eine Karte geben, die du schon hast. Diese Karte steigt dann eine Stufe auf. Auf Stufe 2 ist ihr Effekt 15% stärker. Auf Stufe 3 ist er 30% stärker. Preispäckchen geben dir eine Karte nicht mehr, sobald sie Stufe 3 erreicht hat.",
        ["os.racer_album_filter_elements"] = "Alle Elemente",
        ["os.racer_album_filter_cards"] = "Alle Karten",
        ["os.racer_album_filter_gold"] = "Gold",
        ["os.racer_album_filter_silver"] = "Silber",
        ["os.racer_album_compact"] = "Kompakt",
        ["os.racer_album_search"] = "Karte suchen",
        ["os.racer_album_no_match"] = "Keine Karte passt. Ändere die Filter.",
        ["os.racer_album_none"] = "Du hast noch keine Rennkarten. Öffne Preispäckchen, um welche zu bekommen.",
        ["os.racer_album_progress"] = "{0} von {1} Karten gefunden",
        ["os.racer_album_copies"] = "{0} Kopien",
        ["os.racer_album_not_found"] = "Noch nicht gefunden",
        // Hand dock and hand strips
        ["os.racer_hand_title"] = "Rennkarten",
        ["os.racer_hand_choose_gold"] = "Gold wählen",
        ["os.racer_hand_choose_silver"] = "Silber wählen",
        ["os.racer_hand_swap"] = "Tauschen",
        ["os.racer_hand_remove"] = "Entfernen",
        ["os.racer_hand_saved"] = "Hand gespeichert",
        ["os.racer_hand_saving"] = "Hand wird gespeichert...",
        ["os.racer_hand_race"] = "Mit dieser Hand rennen",
        ["os.racer_hand_change"] = "Hand ändern",
        ["os.racer_hand_enter_cup"] = "Mit dieser Hand teilnehmen",
        ["os.racer_hand_locked_cup"] = "Für diesen Pokal festgelegt",
        ["os.racer_hand_empty"] = "Deine Hand ist leer. Füge Karten aus deinem Album hinzu.",
        ["os.racer_hand_slot_gold"] = "Goldplatz",
        ["os.racer_hand_slot_silver"] = "Silberplatz {0}",
        ["os.racer_hand_in_hand"] = "In der Hand",
        // Hand faults: one sentence per rule the server or the local check can refuse on
        ["os.racer_hand_fault_unknown"] = "Diese Karte gibt es nicht mehr im Spiel. Wähl eine andere.",
        ["os.racer_hand_fault_not_owned"] = "Du hast diese Karte nicht.",
        ["os.racer_hand_fault_wrong_band"] = "Goldkarten gehören in den Goldplatz. Silberkarten gehören in die Silberplätze.",
        ["os.racer_hand_fault_duplicate"] = "Diese Karte ist schon in deiner Hand.",
        ["os.racer_hand_fault_shape"] = "Eine Hand besteht aus einer Goldkarte und zwei Silberkarten.",
        ["os.racer_hand_fault_failed"] = "Deine Hand wurde nicht gespeichert. Versuch es noch mal.",
        // Inspect page
        ["os.racer_inspect_tab_card"] = "Karte",
        ["os.racer_inspect_tab_art"] = "Bild",
        ["os.racer_inspect_tab_info"] = "Info",
        ["os.racer_inspect_when"] = "Wann sie wirkt",
        ["os.racer_inspect_how"] = "So funktioniert sie",
        ["os.racer_inspect_exact"] = "Genaue Regeln und Zahlen",
        ["os.racer_inspect_story"] = "Geschichte und Veredelung",
        ["os.racer_inspect_flip"] = "Karte umdrehen",
        ["os.racer_card_gold"] = "Goldkarte",
        ["os.racer_card_silver"] = "Silberkarte",
        ["os.racer_card_automatic"] = "Automatisch",
        ["os.racer_card_once"] = "Einmal pro Rennen",
        ["os.racer_card_passive"] = "Passiv",
        ["os.racer_card_rank"] = "Nr. {0}",
        ["os.racer_card_level"] = "Stufe {0}",
        ["os.racer_card_level_max"] = "Höchste Stufe",
        ["os.racer_card_effect_bonus"] = "Effekt +{0}%",
        ["os.racer_card_copy_of"] = "Kopie {0} von {1}",
        ["os.racer_card_equip_gold"] = "In den Goldplatz legen",
        ["os.racer_card_equip_silver_1"] = "In Silberplatz 1 legen",
        ["os.racer_card_equip_silver_2"] = "In Silberplatz 2 legen",
        ["os.racer_card_unequip"] = "Aus der Hand nehmen",
        ["os.racer_card_locked"] = "Du hast diese Karte noch nicht. Preispäckchen können sie dir geben.",
        // In-race notice and the result line
        ["os.racer_notice_gold_used"] = "Goldkarte eingesetzt",
        ["os.racer_replay_unavailable"] = "Dieses Rennen hat neuere Karten benutzt, als dein Plugin kennt. Aktualisiere das Plugin, um es anzusehen. Das Ergebnis zählt trotzdem.",
        // Pack reveal and the starter grant
        ["os.racer_pack_prize_card"] = "Rennkarte",
        ["os.racer_card_reveal_new"] = "Neue Karte",
        ["os.racer_card_reveal_level_up"] = "Jetzt Stufe {0}",
        ["os.racer_cards_starter_title"] = "Deine ersten Karten",
        ["os.racer_cards_starter_body"] = "Du hast drei Rennkarten zum Start bekommen. Sie sind schon in deiner Hand.",
        // Guard texts shared by every card of one operation kind. RaceCardGuards maps a card id to its index.
        ["os.racer_card_guard_1"] = "Dein Lumi ermüdet beim Laufen langsamer. Seine Sprints machen ihn trotzdem so müde wie vorher. Diese Karte gibt keine Energie zurück, die dein Lumi schon verbraucht hat.",
        ["os.racer_card_guard_2"] = "Dein Lumi läuft klüger. Er wählt bessere Wege zwischen den anderen Läufern. Er findet öfter einen Weg an ihnen vorbei. Er stolpert seltener. Er ermüdet auch etwas langsamer. Wenn beide Silberkarten das tun, addieren sich die Effekte, aber nur bis zu einer Grenze.",
        ["os.racer_card_guard_3"] = "Dein Lumi startet öfter eigene Sprints. Jeder Sprint ist so schnell und so lang wie vorher. Lumis starten eigene Sprints nur im späteren Teil des Rennens. Dein Lumi braucht zwischen zwei Sprints trotzdem eine kurze Pause.",
        ["os.racer_card_guard_4"] = "Das Höchsttempo deines Lumis ist das ganze Rennen lang etwas höher. Er kann auch ein etwas schnelleres Tempo halten, bevor er müde wird. Kurven, andere Läufer und Müdigkeit bremsen ihn trotzdem. Seine Zielzeit wird deshalb nicht um denselben Wert besser.",
        ["os.racer_card_guard_5"] = "Diese Karte hilft nur am Start. Dein Lumi läuft am Start etwas früher los. Jeder Lumi wartet trotzdem mindestens 0,04 Sekunden, bevor er loslaufen kann.",
        ["os.racer_card_guard_6"] = "Dein Lumi bekommt etwas Energie zurück und kann länger laufen, bevor er müde wird. Die Karte wirkt nur, wenn dein Lumi schon mindestens so viel Energie verbraucht hat. Wenn dein Lumi gerade nachlässt, hört das auf. Der Wert ist ein Anteil seiner vollen Energie, nicht des Rests.",
        ["os.racer_card_guard_7"] = "Die Karte wirkt nur, solange dein Lumi stolpert. Sie lässt dieses Stolpern früher enden. Wenn das Stolpern fast vorbei ist, endet es sofort. Sie verhindert nicht, dass dein Lumi später wieder stolpert.",
        ["os.racer_card_guard_8"] = "Dein Lumi läuft für einen Moment schneller. Er muss schon mit mindestens 75% seines Höchsttempos laufen. Nach der Karte muss dein Lumi noch mehr als 15% seiner Energie haben. Sie kann nicht wirken, solange dein Lumi nachlässt, eingekeilt ist, stolpert oder sprintet. Sie kann auch nicht direkt nach einem Sprint wirken. Wenn dein Lumi gleich seinen Schlusssprint startet, wartet die Karte. Kurven und andere Läufer können deinen Lumi trotzdem bremsen. Danach läuft dein Lumi wieder mit seinem normalen Höchsttempo.",
        ["os.racer_card_guard_9"] = "Dein Lumi sprintet für einen Moment. Die Strecke vor ihm muss gerade sein. Nach der Karte muss dein Lumi noch mehr als 15% seiner Energie haben. Sie kann nicht wirken, solange dein Lumi nachlässt, eingekeilt ist, stolpert oder sprintet. Sie kann auch nicht direkt nach einem Sprint wirken. Wenn dein Lumi gleich seinen Schlusssprint startet, wartet die Karte. Der Sprint ist so schnell wie die eigenen Sprints deines Lumis. Danach kann dein Lumi sofort wieder eigene Sprints starten.",
        // The 54 Core Set cards in catalogue order: name, face caption, availability, description, exact rule, story.
        ["os.racer_card_second_sunrise_name"] = "Zweiter Sonnenaufgang",
        ["os.racer_card_second_sunrise_short"] = "Holt Energie bei Müdigkeit",
        ["os.racer_card_second_sunrise_cond"] = "Wenn dein Lumi wenig Energie hat.",
        ["os.racer_card_second_sunrise_desc"] = "Wenn dein Lumi wenig Energie hat, bekommt er etwas Energie zurück. Sie wartet, bis dein Lumi sehr wenig Energie hat.",
        ["os.racer_card_second_sunrise_exact"] = "Wirkt einmal pro Rennen. Dein Lumi bekommt 5% seiner Energie zurück. Nur wenn dein Lumi noch 24% seiner Energie oder weniger hat. Das kann nach dem ersten Viertel des Rennens passieren, bis kurz vor dem Ziel.",
        ["os.racer_card_second_sunrise_story"] = "Der Morgen fand noch eine Glut.",

        ["os.racer_card_banked_embers_name"] = "Gehütete Glut",
        ["os.racer_card_banked_embers_short"] = "Ermüdet langsamer",
        ["os.racer_card_banked_embers_cond"] = "Das ganze Rennen lang.",
        ["os.racer_card_banked_embers_desc"] = "Dein Lumi ermüdet das ganze Rennen lang etwas langsamer. Kurz vor dem Ziel hat er etwas mehr Energie übrig.",
        ["os.racer_card_banked_embers_exact"] = "Wirkt das ganze Rennen lang. Dein Lumi ermüdet etwa 2,4% weniger.",
        ["os.racer_card_banked_embers_story"] = "Eine kleine Wärme reicht für einen langen Weg.",

        ["os.racer_card_lantern_vigil_name"] = "Laternenwache",
        ["os.racer_card_lantern_vigil_short"] = "Läuft gegen Ende klüger",
        ["os.racer_card_lantern_vigil_cond"] = "Spät im Rennen, bis zum Ziel.",
        ["os.racer_card_lantern_vigil_desc"] = "Spät im Rennen läuft dein Lumi klüger. Er findet öfter einen Weg an anderen Läufern vorbei. Er stolpert auch seltener.",
        ["os.racer_card_lantern_vigil_exact"] = "Wirkt spät im Rennen, bis zum Ziel. Dein Lumi läuft klüger. Der Effekt ist mittel.",
        ["os.racer_card_lantern_vigil_story"] = "Jemand lässt immer ein Licht für dich an.",

        ["os.racer_card_warm_footing_name"] = "Warmer Tritt",
        ["os.racer_card_warm_footing_short"] = "Läuft klüger bei schlechtem Wetter",
        ["os.racer_card_warm_footing_cond"] = "Das ganze Rennen lang. Nur bei Regen, Schnee, starkem Wind, Hitze, Statik oder Staub.",
        ["os.racer_card_warm_footing_desc"] = "Bei schlechtem Wetter läuft dein Lumi klüger. Er findet öfter einen Weg an anderen Läufern vorbei. Er stolpert auch seltener.",
        ["os.racer_card_warm_footing_exact"] = "Wirkt das ganze Rennen lang. Dein Lumi läuft klüger. Der Effekt ist klein. Nur bei Regen, Schnee, starkem Wind, Hitze, Statik oder Staub.",
        ["os.racer_card_warm_footing_story"] = "Es fand den einen Stein, den der Winter übersehen hatte.",

        ["os.racer_card_cinder_leap_name"] = "Aschensprung",
        ["os.racer_card_cinder_leap_short"] = "Sprintet dem Führenden nach",
        ["os.racer_card_cinder_leap_cond"] = "Solange dein Lumi hinter dem Führenden liegt.",
        ["os.racer_card_cinder_leap_desc"] = "In der Mitte des Rennens sprintet dein Lumi dem Führenden nach. Die Strecke vor ihm muss gerade sein.",
        ["os.racer_card_cinder_leap_exact"] = "Wirkt einmal pro Rennen. Dein Lumi sprintet 0,55 Sekunden lang. Das verbraucht 1% seiner Energie. Der Führende muss mindestens 1,2 Körperlängen vorne liegen. Das kann in der Mitte des Rennens passieren.",
        ["os.racer_card_cinder_leap_story"] = "Für einen Herzschlag flog sogar die Asche.",

        ["os.racer_card_slow_burn_name"] = "Langsame Glut",
        ["os.racer_card_slow_burn_short"] = "Ermüdet bergauf langsamer",
        ["os.racer_card_slow_burn_cond"] = "Solange es bergauf geht.",
        ["os.racer_card_slow_burn_desc"] = "Solange es bergauf geht, ermüdet dein Lumi langsamer. So hat er mehr Energie für den Rest des Rennens.",
        ["os.racer_card_slow_burn_exact"] = "Wirkt immer, wenn dein Lumi bergauf läuft. Dein Lumi ermüdet etwa 7% weniger.",
        ["os.racer_card_slow_burn_story"] = "Der Hügel war geduldig. Die Glut auch.",

        ["os.racer_card_sheltered_spark_name"] = "Geschützter Funke",
        ["os.racer_card_sheltered_spark_short"] = "Sprintet öfter bei schlechtem Wetter",
        ["os.racer_card_sheltered_spark_cond"] = "Das ganze Rennen lang. Nur bei Regen, Schnee, starkem Wind, Hitze, Statik oder Staub.",
        ["os.racer_card_sheltered_spark_desc"] = "Bei schlechtem Wetter startet dein Lumi öfter eigene Sprints.",
        ["os.racer_card_sheltered_spark_exact"] = "Wirkt das ganze Rennen lang. Dein Lumi startet 11% öfter eigene Sprints. Nur bei Regen, Schnee, starkem Wind, Hitze, Statik oder Staub.",
        ["os.racer_card_sheltered_spark_story"] = "Der Regen konnte draußen warten.",

        ["os.racer_card_home_by_firelight_name"] = "Heim im Feuerschein",
        ["os.racer_card_home_by_firelight_short"] = "Höheres Höchsttempo",
        ["os.racer_card_home_by_firelight_cond"] = "Das ganze Rennen lang.",
        ["os.racer_card_home_by_firelight_desc"] = "Dein Lumi läuft das ganze Rennen lang ein kleines bisschen schneller.",
        ["os.racer_card_home_by_firelight_exact"] = "Wirkt das ganze Rennen lang. Das Höchsttempo deines Lumis ist etwas höher. Über ein langes Rennen bringt ihn das bis zu etwa 0,3 Körperlängen weiter nach vorne.",
        ["os.racer_card_home_by_firelight_story"] = "Die letzten Schritte rochen nach Zuhause.",

        ["os.racer_card_last_light_name"] = "Das letzte Licht",
        ["os.racer_card_last_light_short"] = "Sprintet dem Führenden nach",
        ["os.racer_card_last_light_cond"] = "Solange dein Lumi hinter dem Führenden liegt.",
        ["os.racer_card_last_light_desc"] = "Kurz vor dem Ende des Rennens sprintet dein Lumi dem Führenden nach. Die Strecke vor ihm muss gerade sein.",
        ["os.racer_card_last_light_exact"] = "Wirkt einmal pro Rennen. Dein Lumi sprintet 0,65 Sekunden lang. Das verbraucht 1% seiner Energie. Der Führende muss mindestens 0,5 Körperlängen vorne liegen. Das kann kurz vor dem Ende des Rennens passieren.",
        ["os.racer_card_last_light_story"] = "Es hob sich einen hellen Gedanken für den Schluss auf.",

        ["os.racer_card_storm_whispers_name"] = "Sturmflüstern",
        ["os.racer_card_storm_whispers_short"] = "Läuft klüger",
        ["os.racer_card_storm_whispers_cond"] = "Das ganze Rennen lang.",
        ["os.racer_card_storm_whispers_desc"] = "Dein Lumi läuft das ganze Rennen lang klüger. Er findet öfter einen Weg an anderen Läufern vorbei. Er stolpert auch seltener.",
        ["os.racer_card_storm_whispers_exact"] = "Wirkt das ganze Rennen lang. Dein Lumi läuft klüger. Der Effekt ist klein.",
        ["os.racer_card_storm_whispers_story"] = "Das leiseste Knistern verriet es zuerst.",

        ["os.racer_card_borrowed_thunder_name"] = "Geliehener Donner",
        ["os.racer_card_borrowed_thunder_short"] = "Sprintet auf einer Geraden",
        ["os.racer_card_borrowed_thunder_cond"] = "Auf einer Geraden.",
        ["os.racer_card_borrowed_thunder_desc"] = "In der Mitte des Rennens sprintet dein Lumi auf einer Geraden.",
        ["os.racer_card_borrowed_thunder_exact"] = "Wirkt einmal pro Rennen. Dein Lumi sprintet 0,45 Sekunden lang. Das verbraucht 1% seiner Energie. Das kann in der Mitte des Rennens passieren.",
        ["os.racer_card_borrowed_thunder_story"] = "Eine kleine Wolke antwortete sehr laut.",

        ["os.racer_card_paper_promises_name"] = "Papierversprechen",
        ["os.racer_card_paper_promises_short"] = "Startet früher",
        ["os.racer_card_paper_promises_cond"] = "Am Start.",
        ["os.racer_card_paper_promises_desc"] = "Dein Lumi läuft am Start früher los.",
        ["os.racer_card_paper_promises_exact"] = "Wirkt am Start des Rennens. Dein Lumi wartet am Start 4% kürzer. Jeder Lumi wartet trotzdem mindestens 0,04 Sekunden.",
        ["os.racer_card_paper_promises_story"] = "Es behielt seine Form, als der Wind drehte.",

        ["os.racer_card_blink_of_brilliance_name"] = "Geistesblitz",
        ["os.racer_card_blink_of_brilliance_short"] = "Wird schneller, wenn er nicht mehr eingekeilt ist",
        ["os.racer_card_blink_of_brilliance_cond"] = "Kurz nachdem dein Lumi nicht mehr eingekeilt ist, während noch ein Läufer vor ihm ist.",
        ["os.racer_card_blink_of_brilliance_desc"] = "Kurz nachdem dein Lumi nicht mehr von einem anderen Läufer eingekeilt wird, läuft er für einen Moment schneller. Das kann in den meisten Teilen des Rennens passieren.",
        ["os.racer_card_blink_of_brilliance_exact"] = "Wirkt einmal pro Rennen, von kurz nach dem Start bis kurz vor dem Ziel. Das Höchsttempo deines Lumis ist 1,4 Sekunden lang 8% höher. Das verbraucht 1% seiner Energie. Nur in der ersten Sekunde, nachdem dein Lumi nicht mehr eingekeilt ist. Ein Läufer muss vor ihm sein.",
        ["os.racer_card_blink_of_brilliance_story"] = "Für einen Moment war die Antwort da.",

        ["os.racer_card_quiet_charge_name"] = "Stille Ladung",
        ["os.racer_card_quiet_charge_short"] = "Sprintet öfter",
        ["os.racer_card_quiet_charge_cond"] = "Das ganze Rennen lang.",
        ["os.racer_card_quiet_charge_desc"] = "Dein Lumi startet das ganze Rennen lang öfter eigene Sprints.",
        ["os.racer_card_quiet_charge_exact"] = "Wirkt das ganze Rennen lang. Dein Lumi startet 7,5% öfter eigene Sprints.",
        ["os.racer_card_quiet_charge_story"] = "Es gab keine Eile, den Funken auszugeben.",

        ["os.racer_card_copper_company_name"] = "Kupfergefährten",
        ["os.racer_card_copper_company_short"] = "Weniger müde hinter einem Läufer",
        ["os.racer_card_copper_company_cond"] = "Solange dein Lumi dicht hinter einem anderen Läufer läuft.",
        ["os.racer_card_copper_company_desc"] = "Solange dein Lumi dicht hinter einem anderen Läufer läuft, ermüdet er langsamer. Die Hilfe endet, wenn er nicht mehr dicht dahinter ist.",
        ["os.racer_card_copper_company_exact"] = "Wirkt immer, wenn dein Lumi dicht hinter einem anderen Läufer läuft. Dein Lumi ermüdet etwa 9,1% weniger.",
        ["os.racer_card_copper_company_story"] = "Der Weg klang freundlicher in Gesellschaft.",

        ["os.racer_card_after_the_flash_name"] = "Nach dem Blitz",
        ["os.racer_card_after_the_flash_short"] = "Läuft nach Stolpern bei schlechtem Wetter klüger",
        ["os.racer_card_after_the_flash_cond"] = "Kurz nach einem Stolpern. Nur bei Regen, Schnee, starkem Wind, Hitze, Statik oder Staub.",
        ["os.racer_card_after_the_flash_desc"] = "Bei schlechtem Wetter läuft dein Lumi kurz nach einem Stolpern eine kurze Zeit klüger. Er findet öfter einen Weg an anderen Läufern vorbei. Er stolpert nicht so leicht gleich wieder.",
        ["os.racer_card_after_the_flash_exact"] = "Wirkt in den 2 Sekunden nach dem Ende jedes Stolperns. Dein Lumi läuft klüger. Der Effekt ist groß. Nur bei Regen, Schnee, starkem Wind, Hitze, Statik oder Staub.",
        ["os.racer_card_after_the_flash_story"] = "Die Pfützen erinnerten sich. Es lief weiter.",

        ["os.racer_card_bright_idea_name"] = "Helle Idee",
        ["os.racer_card_bright_idea_short"] = "Läuft in Kurven klüger",
        ["os.racer_card_bright_idea_cond"] = "In einer Kurve.",
        ["os.racer_card_bright_idea_desc"] = "In Kurven läuft dein Lumi klüger. Er findet öfter einen Weg an anderen Läufern vorbei. Er stolpert auch seltener.",
        ["os.racer_card_bright_idea_exact"] = "Wirkt immer, wenn dein Lumi durch eine Kurve läuft. Dein Lumi läuft klüger. Der Effekt ist mittel.",
        ["os.racer_card_bright_idea_story"] = "Es sah einen Weg zwischen den Regentropfen.",

        ["os.racer_card_catch_the_spark_name"] = "Fang den Funken",
        ["os.racer_card_catch_the_spark_short"] = "Sprintet nach einem Stolpern",
        ["os.racer_card_catch_the_spark_cond"] = "Kurz nach einem Stolpern.",
        ["os.racer_card_catch_the_spark_desc"] = "Kurz nach einem Stolpern sprintet dein Lumi, um wieder in Fahrt zu kommen. Die Strecke vor ihm muss gerade sein.",
        ["os.racer_card_catch_the_spark_exact"] = "Wirkt einmal pro Rennen. Dein Lumi sprintet 0,5 Sekunden lang. Das verbraucht 1% seiner Energie. Nur in den 2 Sekunden nach dem Ende eines Stolperns. Das kann von kurz nach dem Start bis kurz vor dem Ziel passieren.",
        ["os.racer_card_catch_the_spark_story"] = "Es war nicht zu spät, es zu bemerken.",

        ["os.racer_card_featherlight_steps_name"] = "Federleichte Schritte",
        ["os.racer_card_featherlight_steps_short"] = "Ermüdet früh im Rennen langsamer",
        ["os.racer_card_featherlight_steps_cond"] = "Im ersten Drittel des Rennens.",
        ["os.racer_card_featherlight_steps_desc"] = "Im ersten Drittel des Rennens ermüdet dein Lumi langsamer. So hat er später im Rennen mehr Energie.",
        ["os.racer_card_featherlight_steps_exact"] = "Wirkt im ersten Drittel des Rennens. Dein Lumi ermüdet etwa 3,8% weniger.",
        ["os.racer_card_featherlight_steps_story"] = "Das Gras merkte kaum, dass es vorbei war.",

        ["os.racer_card_leeward_path_name"] = "Der windstille Pfad",
        ["os.racer_card_leeward_path_short"] = "Ermüdet bei Wind langsamer",
        ["os.racer_card_leeward_path_cond"] = "Das ganze Rennen lang. Nur bei starkem Wind.",
        ["os.racer_card_leeward_path_desc"] = "Bei starkem Wind ermüdet dein Lumi das ganze Rennen lang langsamer. Kurz vor dem Ziel hat er mehr Energie übrig.",
        ["os.racer_card_leeward_path_exact"] = "Wirkt das ganze Rennen lang. Dein Lumi ermüdet etwa 4,8% weniger. Nur bei starkem Wind.",
        ["os.racer_card_leeward_path_story"] = "Auf dieser Seite hielt der Hügel ein wenig Ruhe bereit.",

        ["os.racer_card_thread_the_gust_name"] = "Durch die Böe",
        ["os.racer_card_thread_the_gust_short"] = "Wird schneller, wenn er nicht mehr eingekeilt ist",
        ["os.racer_card_thread_the_gust_cond"] = "Kurz nachdem dein Lumi nicht mehr eingekeilt ist, während noch ein Läufer vor ihm ist.",
        ["os.racer_card_thread_the_gust_desc"] = "In der Mitte des Rennens läuft dein Lumi für einen Moment schneller, kurz nachdem er nicht mehr von einem anderen Läufer eingekeilt wird.",
        ["os.racer_card_thread_the_gust_exact"] = "Wirkt einmal pro Rennen, in der Mitte des Rennens. Das Höchsttempo deines Lumis ist 1,5 Sekunden lang 9% höher. Das verbraucht 1% seiner Energie. Nur in der ersten Sekunde, nachdem dein Lumi nicht mehr eingekeilt ist. Ein Läufer muss vor ihm sein.",
        ["os.racer_card_thread_the_gust_story"] = "Die Brise ließ gerade genug Platz.",

        ["os.racer_card_lift_together_name"] = "Gemeinsamer Aufwind",
        ["os.racer_card_lift_together_short"] = "Holt Energie hinter einem Läufer",
        ["os.racer_card_lift_together_cond"] = "Solange dein Lumi direkt hinter einem anderen Läufer läuft.",
        ["os.racer_card_lift_together_desc"] = "In der Mitte des Rennens bekommt dein Lumi etwas Energie zurück. Er muss direkt hinter einem anderen Läufer laufen, nicht seitlich daneben.",
        ["os.racer_card_lift_together_exact"] = "Wirkt einmal pro Rennen. Dein Lumi bekommt 4% seiner Energie zurück. Nur solange dein Lumi direkt hinter einem anderen Läufer läuft. Das kann in der Mitte des Rennens passieren.",
        ["os.racer_card_lift_together_story"] = "Der Mut reiste auf derselben Brise.",

        ["os.racer_card_ribbon_weather_name"] = "Bänderwetter",
        ["os.racer_card_ribbon_weather_short"] = "Läuft klüger bei klarem Wetter",
        ["os.racer_card_ribbon_weather_cond"] = "Das ganze Rennen lang. Nur bei klarem Wetter.",
        ["os.racer_card_ribbon_weather_desc"] = "Bei klarem Wetter läuft dein Lumi das ganze Rennen lang klüger. Er findet öfter einen Weg an anderen Läufern vorbei. Er stolpert auch seltener.",
        ["os.racer_card_ribbon_weather_exact"] = "Wirkt das ganze Rennen lang. Dein Lumi läuft klüger. Der Effekt ist klein. Nur bei klarem Wetter.",
        ["os.racer_card_ribbon_weather_story"] = "Ein Flattern war alle Warnung, die es brauchte.",

        ["os.racer_card_long_glide_name"] = "Der lange Gleitflug",
        ["os.racer_card_long_glide_short"] = "Ermüdet langsamer bei klarem Wetter",
        ["os.racer_card_long_glide_cond"] = "Das ganze Rennen lang. Nur bei klarem Wetter.",
        ["os.racer_card_long_glide_desc"] = "Bei klarem Wetter ermüdet dein Lumi das ganze Rennen lang langsamer. Kurz vor dem Ziel hat er mehr Energie übrig.",
        ["os.racer_card_long_glide_exact"] = "Wirkt das ganze Rennen lang. Dein Lumi ermüdet etwa 2,7% weniger. Nur bei klarem Wetter.",
        ["os.racer_card_long_glide_story"] = "Es war Zeit, die Luft ihren Teil tun zu lassen.",

        ["os.racer_card_pocket_of_calm_name"] = "Insel der Ruhe",
        ["os.racer_card_pocket_of_calm_short"] = "Läuft klüger in einer Gruppe",
        ["os.racer_card_pocket_of_calm_cond"] = "Wenn andere Läufer in der Nähe sind.",
        ["os.racer_card_pocket_of_calm_desc"] = "Wenn mindestens 2 andere Läufer in der Nähe sind, läuft dein Lumi klüger. Er findet öfter einen Weg an ihnen vorbei.",
        ["os.racer_card_pocket_of_calm_exact"] = "Wirkt immer, wenn mindestens 2 andere Läufer in der Nähe sind. Dein Lumi läuft klüger. Der Effekt ist mittel.",
        ["os.racer_card_pocket_of_calm_story"] = "Es schuf Platz für einen ruhigen Atemzug.",

        ["os.racer_card_borrowed_wings_name"] = "Geliehene Flügel",
        ["os.racer_card_borrowed_wings_short"] = "Kürzeres spätes Stolpern",
        ["os.racer_card_borrowed_wings_cond"] = "Solange dein Lumi stolpert.",
        ["os.racer_card_borrowed_wings_desc"] = "In der zweiten Hälfte des Rennens lässt diese Karte ein Stolpern früher enden.",
        ["os.racer_card_borrowed_wings_exact"] = "Wirkt einmal pro Rennen. Das Stolpern deines Lumis endet bis zu 0,35 Sekunden früher. Nur solange dein Lumi stolpert. Das kann in der zweiten Hälfte des Rennens passieren.",
        ["os.racer_card_borrowed_wings_story"] = "Der nächste Atemzug war schon unterwegs.",

        ["os.racer_card_home_on_the_breeze_name"] = "Heim auf der Brise",
        ["os.racer_card_home_on_the_breeze_short"] = "Schneller bei schlechtem Wetter",
        ["os.racer_card_home_on_the_breeze_cond"] = "Das ganze Rennen lang. Nur bei Regen, Schnee, starkem Wind, Hitze, Statik oder Staub.",
        ["os.racer_card_home_on_the_breeze_desc"] = "Bei schlechtem Wetter läuft dein Lumi das ganze Rennen lang ein kleines bisschen schneller.",
        ["os.racer_card_home_on_the_breeze_exact"] = "Wirkt das ganze Rennen lang. Das Höchsttempo deines Lumis ist etwas höher. Über ein langes Rennen bringt ihn das bis zu etwa 0,43 Körperlängen weiter nach vorne. Nur bei Regen, Schnee, starkem Wind, Hitze, Statik oder Staub.",
        ["os.racer_card_home_on_the_breeze_story"] = "Es erkannte den Garten daran, wie er atmete.",

        ["os.racer_card_quiet_footing_name"] = "Leiser Tritt",
        ["os.racer_card_quiet_footing_short"] = "Läuft in engen Kurven klüger",
        ["os.racer_card_quiet_footing_cond"] = "In einer engen Kurve.",
        ["os.racer_card_quiet_footing_desc"] = "In engen Kurven läuft dein Lumi klüger. Er findet öfter einen Weg an anderen Läufern vorbei. Er stolpert auch seltener.",
        ["os.racer_card_quiet_footing_exact"] = "Wirkt immer, wenn dein Lumi durch eine enge Kurve läuft. Dein Lumi läuft klüger. Der Effekt ist groß.",
        ["os.racer_card_quiet_footing_story"] = "Der Frost machte Platz für vorsichtige Füße.",

        ["os.racer_card_winter_reprieve_name"] = "Winters Atempause",
        ["os.racer_card_winter_reprieve_short"] = "Holt Energie bei Regen oder Schnee",
        ["os.racer_card_winter_reprieve_cond"] = "Wenn dein Lumi wenig Energie hat. Nur bei Regen oder Schnee.",
        ["os.racer_card_winter_reprieve_desc"] = "Bei Regen oder Schnee bekommt dein Lumi etwas Energie zurück, wenn er wenig Energie hat. Sie kann schon früh im Rennen wirken.",
        ["os.racer_card_winter_reprieve_exact"] = "Wirkt einmal pro Rennen. Dein Lumi bekommt 5,5% seiner Energie zurück. Nur wenn dein Lumi noch 30% seiner Energie oder weniger hat. Nur bei Regen oder Schnee. Das kann nach dem ersten Viertel des Rennens passieren, bis kurz vor dem Ziel.",
        ["os.racer_card_winter_reprieve_story"] = "Die Kälte hielt für einen freundlichen Moment still.",

        ["os.racer_card_clear_reflection_name"] = "Klare Spiegelung",
        ["os.racer_card_clear_reflection_short"] = "Startet früher bei klarem Wetter",
        ["os.racer_card_clear_reflection_cond"] = "Am Start. Nur bei klarem Wetter.",
        ["os.racer_card_clear_reflection_desc"] = "Bei klarem Wetter läuft dein Lumi am Start früher los.",
        ["os.racer_card_clear_reflection_exact"] = "Wirkt am Start des Rennens. Dein Lumi wartet am Start 5% kürzer. Jeder Lumi wartet trotzdem mindestens 0,04 Sekunden. Nur bei klarem Wetter.",
        ["os.racer_card_clear_reflection_story"] = "Es hörte mit den Augen zu.",

        ["os.racer_card_under_the_snow_name"] = "Unter dem Schnee",
        ["os.racer_card_under_the_snow_short"] = "Ermüdet bei Schnee langsamer",
        ["os.racer_card_under_the_snow_cond"] = "Das ganze Rennen lang. Nur bei Schnee.",
        ["os.racer_card_under_the_snow_desc"] = "Bei Schnee ermüdet dein Lumi das ganze Rennen lang langsamer. Kurz vor dem Ziel hat er mehr Energie übrig.",
        ["os.racer_card_under_the_snow_exact"] = "Wirkt das ganze Rennen lang. Dein Lumi ermüdet etwa 4,8% weniger. Nur bei Schnee.",
        ["os.racer_card_under_the_snow_story"] = "Der Winter hielt sein kleinstes Zimmer warm.",

        ["os.racer_card_still_as_starlight_name"] = "Still wie Sternenlicht",
        ["os.racer_card_still_as_starlight_short"] = "Läuft spät bei klarem Wetter klüger",
        ["os.racer_card_still_as_starlight_cond"] = "Spät im Rennen, bis zum Ziel. Nur bei klarem Wetter.",
        ["os.racer_card_still_as_starlight_desc"] = "Bei klarem Wetter läuft dein Lumi spät im Rennen klüger. Er findet öfter einen Weg an anderen Läufern vorbei. Er stolpert auch seltener.",
        ["os.racer_card_still_as_starlight_exact"] = "Wirkt spät im Rennen, bis zum Ziel. Dein Lumi läuft klüger. Der Effekt ist mittel. Nur bei klarem Wetter.",
        ["os.racer_card_still_as_starlight_story"] = "Sogar die Sterne schienen leiser zu werden.",

        ["os.racer_card_one_perfect_step_name"] = "Ein perfekter Schritt",
        ["os.racer_card_one_perfect_step_short"] = "Wird nach einer Kurve schneller",
        ["os.racer_card_one_perfect_step_cond"] = "Kurz nach einer Kurve.",
        ["os.racer_card_one_perfect_step_desc"] = "Kurz nach einer Kurve läuft dein Lumi für einen Moment schneller.",
        ["os.racer_card_one_perfect_step_exact"] = "Wirkt einmal pro Rennen. Das Höchsttempo deines Lumis ist 1,4 Sekunden lang 8,5% höher. Das verbraucht 1% seiner Energie. Nur in der ersten Sekunde nach einer Kurve. Das kann von kurz nach dem Start bis kurz vor dem Ziel passieren.",
        ["os.racer_card_one_perfect_step_story"] = "Es vertraute dem kleinen Stück freiem Boden.",

        ["os.racer_card_ring_the_frost_name"] = "Läute den Frost",
        ["os.racer_card_ring_the_frost_short"] = "Kürzeres Stolpern",
        ["os.racer_card_ring_the_frost_cond"] = "Solange dein Lumi stolpert.",
        ["os.racer_card_ring_the_frost_desc"] = "Fast jederzeit im Rennen lässt diese Karte ein Stolpern früher enden.",
        ["os.racer_card_ring_the_frost_exact"] = "Wirkt einmal pro Rennen. Das Stolpern deines Lumis endet bis zu 0,3 Sekunden früher. Nur solange dein Lumi stolpert. Das kann fast jederzeit im Rennen passieren.",
        ["os.racer_card_ring_the_frost_story"] = "Ein klarer Ton schüttelte die Sorge ab.",

        ["os.racer_card_soft_landing_name"] = "Sanfte Landung",
        ["os.racer_card_soft_landing_short"] = "Läuft bergab klüger",
        ["os.racer_card_soft_landing_cond"] = "Solange es bergab geht.",
        ["os.racer_card_soft_landing_desc"] = "Solange es bergab geht, läuft dein Lumi klüger. Er findet öfter einen Weg an anderen Läufern vorbei. Er stolpert auch seltener.",
        ["os.racer_card_soft_landing_exact"] = "Wirkt immer, wenn dein Lumi bergab läuft. Dein Lumi läuft klüger. Der Effekt ist groß.",
        ["os.racer_card_soft_landing_story"] = "Der Schnee hatte sich diese Stelle aufgehoben.",

        ["os.racer_card_thaw_comes_slowly_name"] = "Langsames Tauwetter",
        ["os.racer_card_thaw_comes_slowly_short"] = "Ermüdet gegen Ende langsamer",
        ["os.racer_card_thaw_comes_slowly_cond"] = "Spät im Rennen, bis zum Ziel.",
        ["os.racer_card_thaw_comes_slowly_desc"] = "Spät im Rennen ermüdet dein Lumi langsamer. So hat er mehr Energie für den Schluss.",
        ["os.racer_card_thaw_comes_slowly_exact"] = "Wirkt spät im Rennen, bis zum Ziel. Dein Lumi ermüdet etwa 4,8% weniger.",
        ["os.racer_card_thaw_comes_slowly_story"] = "Ein wenig Wärme reichte für den Anfang.",

        ["os.racer_card_follow_the_flow_name"] = "Folge der Strömung",
        ["os.racer_card_follow_the_flow_short"] = "Ermüdet auf Geraden langsamer",
        ["os.racer_card_follow_the_flow_cond"] = "Auf einer Geraden.",
        ["os.racer_card_follow_the_flow_desc"] = "Auf Geraden ermüdet dein Lumi langsamer. So hat er mehr Energie für den Rest des Rennens.",
        ["os.racer_card_follow_the_flow_exact"] = "Wirkt immer, wenn dein Lumi auf einer Geraden läuft. Dein Lumi ermüdet etwa 4,3% weniger.",
        ["os.racer_card_follow_the_flow_story"] = "Die Strömung kannte einen sanfteren Weg.",

        ["os.racer_card_puddle_lessons_name"] = "Pfützenlektionen",
        ["os.racer_card_puddle_lessons_short"] = "Läuft nach einem Stolpern klüger",
        ["os.racer_card_puddle_lessons_cond"] = "Kurz nach einem Stolpern.",
        ["os.racer_card_puddle_lessons_desc"] = "Kurz nach einem Stolpern läuft dein Lumi eine kurze Zeit klüger. Er findet öfter einen Weg an anderen Läufern vorbei. Er stolpert nicht so leicht gleich wieder.",
        ["os.racer_card_puddle_lessons_exact"] = "Wirkt in den 2 Sekunden nach dem Ende jedes Stolperns. Dein Lumi läuft klüger. Der Effekt ist mittel.",
        ["os.racer_card_puddle_lessons_story"] = "Jede Pfütze hatte etwas Neues zu erzählen.",

        ["os.racer_card_turning_tide_name"] = "Die Flut dreht",
        ["os.racer_card_turning_tide_short"] = "Holt Energie bei Müdigkeit",
        ["os.racer_card_turning_tide_cond"] = "Wenn dein Lumi wenig Energie hat.",
        ["os.racer_card_turning_tide_desc"] = "Ab etwa der Hälfte des Rennens bekommt dein Lumi etwas Energie zurück, wenn er wenig Energie hat.",
        ["os.racer_card_turning_tide_exact"] = "Wirkt einmal pro Rennen. Dein Lumi bekommt 4% seiner Energie zurück. Nur wenn dein Lumi noch 35% seiner Energie oder weniger hat. Das kann ab etwa der Hälfte des Rennens bis kurz vor dem Ziel passieren.",
        ["os.racer_card_turning_tide_story"] = "Das Wasser bot einen anderen Weg hindurch.",

        ["os.racer_card_pearls_of_patience_name"] = "Perlen der Geduld",
        ["os.racer_card_pearls_of_patience_short"] = "Sprintet öfter in der zweiten Hälfte",
        ["os.racer_card_pearls_of_patience_cond"] = "In der zweiten Hälfte des Rennens.",
        ["os.racer_card_pearls_of_patience_desc"] = "In der zweiten Hälfte des Rennens startet dein Lumi öfter eigene Sprints.",
        ["os.racer_card_pearls_of_patience_exact"] = "Wirkt in der zweiten Hälfte des Rennens. Dein Lumi startet 13% öfter eigene Sprints.",
        ["os.racer_card_pearls_of_patience_story"] = "Es ließ die Blasen in ihrem eigenen Tempo aufsteigen.",

        ["os.racer_card_over_the_water_name"] = "Übers Wasser",
        ["os.racer_card_over_the_water_short"] = "Sprintet dem Führenden nach",
        ["os.racer_card_over_the_water_cond"] = "Solange dein Lumi hinter dem Führenden liegt.",
        ["os.racer_card_over_the_water_desc"] = "Nach dem ersten Drittel des Rennens sprintet dein Lumi dem Führenden nach. Die Strecke vor ihm muss gerade sein.",
        ["os.racer_card_over_the_water_exact"] = "Wirkt einmal pro Rennen. Dein Lumi sprintet 0,65 Sekunden lang. Das verbraucht 1% seiner Energie. Der Führende muss mindestens 0,8 Körperlängen vorne liegen. Das kann nach dem ersten Drittel des Rennens passieren, bis kurz vor dem Ziel.",
        ["os.racer_card_over_the_water_story"] = "Es gab gerade genug Stein, um mutig zu sein.",

        ["os.racer_card_rain_on_glass_name"] = "Regen auf Glas",
        ["os.racer_card_rain_on_glass_short"] = "Läuft in Kurven bei Regen klüger",
        ["os.racer_card_rain_on_glass_cond"] = "In einer Kurve. Nur bei Regen.",
        ["os.racer_card_rain_on_glass_desc"] = "In Kurven bei Regen läuft dein Lumi klüger. Er findet öfter einen Weg an anderen Läufern vorbei. Er stolpert auch seltener.",
        ["os.racer_card_rain_on_glass_exact"] = "Wirkt immer, wenn dein Lumi durch eine Kurve läuft. Dein Lumi läuft klüger. Der Effekt ist groß. Nur bei Regen.",
        ["os.racer_card_rain_on_glass_story"] = "Es zählte die Pausen zwischen den Tropfen.",

        ["os.racer_card_ripple_returned_name"] = "Rückkehr der Welle",
        ["os.racer_card_ripple_returned_short"] = "Holt Energie nach einem Stolpern",
        ["os.racer_card_ripple_returned_cond"] = "Kurz nach einem Stolpern.",
        ["os.racer_card_ripple_returned_desc"] = "Kurz nach einem Stolpern bekommt dein Lumi etwas Energie zurück.",
        ["os.racer_card_ripple_returned_exact"] = "Wirkt einmal pro Rennen. Dein Lumi bekommt 5% seiner Energie zurück. Nur in den 2 Sekunden nach dem Ende eines Stolperns. Das kann von kurz nach dem Start bis kurz vor dem Ziel passieren.",
        ["os.racer_card_ripple_returned_story"] = "Die zweite Welle fand es bereit.",

        ["os.racer_card_low_tide_friends_name"] = "Freunde bei Ebbe",
        ["os.racer_card_low_tide_friends_short"] = "Läuft klüger hinter einem Läufer",
        ["os.racer_card_low_tide_friends_cond"] = "Solange dein Lumi dicht hinter einem anderen Läufer läuft.",
        ["os.racer_card_low_tide_friends_desc"] = "Solange dein Lumi dicht hinter einem anderen Läufer bleibt, läuft er klüger. Er findet öfter einen Weg an anderen Läufern vorbei. Er stolpert auch seltener.",
        ["os.racer_card_low_tide_friends_exact"] = "Wirkt immer, wenn dein Lumi dicht hinter einem anderen Läufer läuft. Dein Lumi läuft klüger. Der Effekt ist groß.",
        ["os.racer_card_low_tide_friends_story"] = "Manche Wege gehen sich besser im Plaudertempo.",

        ["os.racer_card_smooth_pebble_promise_name"] = "Kieselversprechen",
        ["os.racer_card_smooth_pebble_promise_short"] = "Schneller bei klarem Wetter",
        ["os.racer_card_smooth_pebble_promise_cond"] = "Das ganze Rennen lang. Nur bei klarem Wetter.",
        ["os.racer_card_smooth_pebble_promise_desc"] = "Bei klarem Wetter läuft dein Lumi das ganze Rennen lang ein kleines bisschen schneller.",
        ["os.racer_card_smooth_pebble_promise_exact"] = "Wirkt das ganze Rennen lang. Das Höchsttempo deines Lumis ist etwas höher. Über ein langes Rennen bringt ihn das bis zu etwa 0,35 Körperlängen weiter nach vorne. Nur bei klarem Wetter.",
        ["os.racer_card_smooth_pebble_promise_story"] = "Es trug das kleine Ding den ganzen Weg zurück.",

        ["os.racer_card_stand_together_name"] = "Zusammenstehen",
        ["os.racer_card_stand_together_short"] = "Holt Energie in einer Gruppe",
        ["os.racer_card_stand_together_cond"] = "Wenn andere Läufer in der Nähe sind.",
        ["os.racer_card_stand_together_desc"] = "In der Mitte des Rennens bekommt dein Lumi etwas Energie zurück. Mindestens 2 andere Läufer müssen in der Nähe sein.",
        ["os.racer_card_stand_together_exact"] = "Wirkt einmal pro Rennen. Dein Lumi bekommt 4% seiner Energie zurück. Nur wenn mindestens 2 andere Läufer in der Nähe sind. Das kann in der Mitte des Rennens passieren.",
        ["os.racer_card_stand_together_story"] = "Neben einem Freund stand es ein wenig aufrechter.",

        ["os.racer_card_roots_remember_name"] = "Wurzeln erinnern sich",
        ["os.racer_card_roots_remember_short"] = "Läuft bergauf klüger",
        ["os.racer_card_roots_remember_cond"] = "Solange es bergauf geht.",
        ["os.racer_card_roots_remember_desc"] = "Solange es bergauf geht, läuft dein Lumi klüger. Er findet öfter einen Weg an anderen Läufern vorbei. Er stolpert auch seltener.",
        ["os.racer_card_roots_remember_exact"] = "Wirkt immer, wenn dein Lumi bergauf läuft. Dein Lumi läuft klüger. Der Effekt ist groß.",
        ["os.racer_card_roots_remember_story"] = "Der älteste Pfad kannte noch seinen Namen.",

        ["os.racer_card_patient_path_name"] = "Der geduldige Pfad",
        ["os.racer_card_patient_path_short"] = "Ermüdet früh bei klarem Wetter langsamer",
        ["os.racer_card_patient_path_cond"] = "In der ersten Hälfte des Rennens. Nur bei klarem Wetter.",
        ["os.racer_card_patient_path_desc"] = "Bei klarem Wetter ermüdet dein Lumi in der ersten Hälfte des Rennens langsamer. So hat er später mehr Energie übrig.",
        ["os.racer_card_patient_path_exact"] = "Wirkt in der ersten Hälfte des Rennens. Dein Lumi ermüdet etwa 5,2% weniger. Nur bei klarem Wetter.",
        ["os.racer_card_patient_path_story"] = "Kleine Schritte brachten es trotzdem irgendwohin.",

        ["os.racer_card_mossbound_shelter_name"] = "Schutz unterm Moos",
        ["os.racer_card_mossbound_shelter_short"] = "Ermüdet bei Staub langsamer",
        ["os.racer_card_mossbound_shelter_cond"] = "Das ganze Rennen lang. Nur bei Staub.",
        ["os.racer_card_mossbound_shelter_desc"] = "Bei Staub ermüdet dein Lumi das ganze Rennen lang langsamer. Kurz vor dem Ziel hat er mehr Energie übrig.",
        ["os.racer_card_mossbound_shelter_exact"] = "Wirkt das ganze Rennen lang. Dein Lumi ermüdet etwa 4,8% weniger. Nur bei Staub.",
        ["os.racer_card_mossbound_shelter_story"] = "Der Stein hatte genau dafür eine trockene Ecke bewahrt.",

        ["os.racer_card_little_ballast_name"] = "Ein wenig Ballast",
        ["os.racer_card_little_ballast_short"] = "Startet früher bei schlechtem Wetter",
        ["os.racer_card_little_ballast_cond"] = "Am Start. Nur bei Regen, Schnee, starkem Wind, Hitze, Statik oder Staub.",
        ["os.racer_card_little_ballast_desc"] = "Bei schlechtem Wetter läuft dein Lumi am Start früher los.",
        ["os.racer_card_little_ballast_exact"] = "Wirkt am Start des Rennens. Dein Lumi wartet am Start 5,5% kürzer. Jeder Lumi wartet trotzdem mindestens 0,04 Sekunden. Nur bei Regen, Schnee, starkem Wind, Hitze, Statik oder Staub.",
        ["os.racer_card_little_ballast_story"] = "Ein kleines Gewicht ließ die Welt ruhiger wirken.",

        ["os.racer_card_hold_the_hill_name"] = "Halte den Hügel",
        ["os.racer_card_hold_the_hill_short"] = "Wird nach einem Anstieg schneller",
        ["os.racer_card_hold_the_hill_cond"] = "Kurz nachdem ein Anstieg endet.",
        ["os.racer_card_hold_the_hill_desc"] = "Kurz nachdem ein Anstieg endet, läuft dein Lumi für einen Moment schneller.",
        ["os.racer_card_hold_the_hill_exact"] = "Wirkt einmal pro Rennen. Das Höchsttempo deines Lumis ist 1,6 Sekunden lang 10% höher. Das verbraucht 1% seiner Energie. Nur in der ersten Sekunde nach dem Ende eines Anstiegs. Das kann von kurz nach dem Start bis kurz vor dem Ziel passieren.",
        ["os.racer_card_hold_the_hill_story"] = "Der Hang fragte. Es antwortete mit einem Schub mehr.",

        ["os.racer_card_kindly_ground_name"] = "Gütiger Boden",
        ["os.racer_card_kindly_ground_short"] = "Ermüdet nach Stolpern langsamer",
        ["os.racer_card_kindly_ground_cond"] = "Kurz nach einem Stolpern.",
        ["os.racer_card_kindly_ground_desc"] = "Kurz nach einem Stolpern ermüdet dein Lumi eine kurze Zeit langsamer.",
        ["os.racer_card_kindly_ground_exact"] = "Wirkt in den 2 Sekunden nach dem Ende jedes Stolperns. Dein Lumi ermüdet etwa 9,1% weniger.",
        ["os.racer_card_kindly_ground_story"] = "Die Erde hatte nichts gegen einen Moment Rast.",

        ["os.racer_card_mountain_answers_name"] = "Der Berg antwortet",
        ["os.racer_card_mountain_answers_short"] = "Kürzeres frühes Stolpern",
        ["os.racer_card_mountain_answers_cond"] = "Solange dein Lumi stolpert.",
        ["os.racer_card_mountain_answers_desc"] = "In der ersten Hälfte des Rennens lässt diese Karte ein Stolpern früher enden.",
        ["os.racer_card_mountain_answers_exact"] = "Wirkt einmal pro Rennen. Das Stolpern deines Lumis endet bis zu 0,4 Sekunden früher. Nur solange dein Lumi stolpert. Das kann in der ersten Hälfte des Rennens passieren.",
        ["os.racer_card_mountain_answers_story"] = "Sein kleiner mutiger Ton fand ein sehr großes Echo.",

        ["os.racer_card_home_in_a_shell_name"] = "Heim in der Schale",
        ["os.racer_card_home_in_a_shell_short"] = "Ermüdet langsamer bei Müdigkeit",
        ["os.racer_card_home_in_a_shell_cond"] = "Wenn dein Lumi wenig Energie hat.",
        ["os.racer_card_home_in_a_shell_desc"] = "Wenn dein Lumi wenig Energie hat, ermüdet er langsamer. Sie hilft nicht mehr, sobald seine Energie wieder höher ist.",
        ["os.racer_card_home_in_a_shell_exact"] = "Wirkt immer, wenn dein Lumi noch 35% seiner Energie oder weniger hat. Dein Lumi ermüdet etwa 6,5% weniger.",
        ["os.racer_card_home_in_a_shell_story"] = "Es hatte den stillen Teil von Zuhause mitgebracht.",

        ["os.racer_hand_pick_prompt"] = "{0}: Tipp unten auf eine Karte.",
        ["os.racer_album_off"] = "Rennkarten sind gerade ausgeschaltet.",
        ["os.racer_pack_accessory"] = "Accessoire",
        ["os.racer_pack_colour"] = "Farbe",
        ["os.racer_card_move_silver"] = "In Silberplatz {0} verschieben",
        ["os.racer_hand_explain"] = "Rennkarten geben deinem {0} Boni in Rennen. Eine Goldkarte ist eine aktive Karte, die {0} von selbst einsetzt. Silberkarten sind passive Buffs verschiedener Art. Wähl deine Karten.",
        ["os.racer_hand_enter_the_cup"] = "Am Pokal teilnehmen",
        ["os.racer_hand_none_gold"] = "Du hast noch keine Goldkarten. Preispäckchen können dir welche geben.",
        ["os.racer_hand_none_silver"] = "Du hast noch keine Silberkarten. Preispäckchen können dir welche geben.",
        ["os.racer_cards_per_row_1"] = "Eine Karte pro Reihe zeigen",
        ["os.racer_cards_per_row_2"] = "Zwei Karten pro Reihe zeigen",
        ["os.racer_cards_per_row_3"] = "Drei Karten pro Reihe zeigen",
        ["os.racer_inspect_levels"] = "Stufen",
        ["os.racer_inspect_level_bonus"] = "{0}% Extrabonus",
        ["os.racer_inspect_level_default"] = "Standardbonus der Karte",
        ["os.racer_hand_lumi"] = "Lumi",
        ["os.racer_hand_info_close"] = "Schließen",
    };
}
