using System.Collections.Generic;

namespace AetherOS.Apps.Racer.Localization;

public static partial class AppStrings
{
    // added after update 2.7.0 (racing cards)
    private static readonly IReadOnlyDictionary<string, string> CardsRu = new Dictionary<string, string>
    {
        // Album (the Bonus cards tab)
        ["os.racer_album_intro"] = "Наборы с призами дают гоночные карты. Выбери одну золотую карту и две серебряные для своей руки.",
        ["os.racer_album_levels"] = "Из набора может выпасть карта, которая у тебя уже есть. Тогда её уровень повышается на один. На уровне 2 её эффект сильнее на 15%. На уровне 3 он сильнее на 30%. Когда карта достигает уровня 3, наборы больше её не дают.",
        ["os.racer_album_filter_elements"] = "Все стихии",
        ["os.racer_album_filter_cards"] = "Все карты",
        ["os.racer_album_filter_gold"] = "Золотые",
        ["os.racer_album_filter_silver"] = "Серебряные",
        ["os.racer_album_compact"] = "Компактно",
        ["os.racer_album_search"] = "Найти карту",
        ["os.racer_album_no_match"] = "Таких карт нет. Измени фильтры.",
        ["os.racer_album_none"] = "У тебя пока нет гоночных карт. Открывай наборы с призами, чтобы их получить.",
        ["os.racer_album_progress"] = "Найдено карт: {0} из {1}",
        ["os.racer_album_copies"] = "Копий: {0}",
        ["os.racer_album_not_found"] = "Пока не найдена",
        // Hand dock and hand strips
        ["os.racer_hand_title"] = "Карты для забега",
        ["os.racer_hand_choose_gold"] = "Выбрать золотую",
        ["os.racer_hand_choose_silver"] = "Выбрать серебряную",
        ["os.racer_hand_swap"] = "Заменить",
        ["os.racer_hand_remove"] = "Убрать",
        ["os.racer_hand_saved"] = "Рука сохранена",
        ["os.racer_hand_saving"] = "Сохраняем руку...",
        ["os.racer_hand_race"] = "Бежать с этой рукой",
        ["os.racer_hand_change"] = "Сменить руку",
        ["os.racer_hand_enter_cup"] = "Участвовать с этой рукой",
        ["os.racer_hand_locked_cup"] = "Закреплена на этот кубок",
        ["os.racer_hand_empty"] = "Твоя рука пуста. Добавь карты из альбома.",
        ["os.racer_hand_slot_gold"] = "Золотой слот",
        ["os.racer_hand_slot_silver"] = "Серебряный слот {0}",
        ["os.racer_hand_in_hand"] = "В руке",
        // Hand faults: one sentence per rule the server or the local check can refuse on
        ["os.racer_hand_fault_unknown"] = "Этой карты больше нет в игре. Выбери другую.",
        ["os.racer_hand_fault_not_owned"] = "У тебя нет этой карты.",
        ["os.racer_hand_fault_wrong_band"] = "Золотые карты кладут в золотой слот. Серебряные карты кладут в серебряные слоты.",
        ["os.racer_hand_fault_duplicate"] = "Эта карта уже в твоей руке.",
        ["os.racer_hand_fault_shape"] = "В руке одна золотая карта и две серебряные.",
        ["os.racer_hand_fault_failed"] = "Рука не сохранилась. Попробуй ещё раз.",
        // Inspect page
        ["os.racer_inspect_tab_card"] = "Карта",
        ["os.racer_inspect_tab_art"] = "Арт",
        ["os.racer_inspect_tab_info"] = "Инфо",
        ["os.racer_inspect_when"] = "Когда работает",
        ["os.racer_inspect_how"] = "Как работает",
        ["os.racer_inspect_exact"] = "Точные правила и числа",
        ["os.racer_inspect_story"] = "История и отделка",
        ["os.racer_inspect_flip"] = "Перевернуть карту",
        ["os.racer_card_gold"] = "Золотая карта",
        ["os.racer_card_silver"] = "Серебряная карта",
        ["os.racer_card_automatic"] = "Автоматически",
        ["os.racer_card_once"] = "Раз за забег",
        ["os.racer_card_passive"] = "Пассивная",
        ["os.racer_card_rank"] = "№ {0}",
        ["os.racer_card_level"] = "Уровень {0}",
        ["os.racer_card_level_max"] = "Максимальный уровень",
        ["os.racer_card_effect_bonus"] = "Эффект +{0}%",
        ["os.racer_card_copy_of"] = "Копия {0} из {1}",
        ["os.racer_card_equip_gold"] = "В золотой слот",
        ["os.racer_card_equip_silver_1"] = "В серебряный слот 1",
        ["os.racer_card_equip_silver_2"] = "В серебряный слот 2",
        ["os.racer_card_unequip"] = "Убрать из руки",
        ["os.racer_card_locked"] = "У тебя пока нет этой карты. Её можно получить из набора с призами.",
        // In-race notice and the result line
        ["os.racer_notice_gold_used"] = "Использована золотая карта",
        ["os.racer_replay_unavailable"] = "В этом забеге были карты новее, чем знает твой плагин. Обнови плагин, чтобы посмотреть забег. Результат всё равно засчитан.",
        // Pack reveal and the starter grant
        ["os.racer_pack_prize_card"] = "Гоночная карта",
        ["os.racer_card_reveal_new"] = "Новая карта",
        ["os.racer_card_reveal_level_up"] = "Теперь уровень {0}",
        ["os.racer_cards_starter_title"] = "Твои первые карты",
        ["os.racer_cards_starter_body"] = "Для начала тебе выданы три гоночные карты. Они уже в твоей руке.",
        // Guard texts shared by every card of one operation kind. RaceCardGuards maps a card id to its index.
        ["os.racer_card_guard_1"] = "Твой Луми устаёт медленнее, пока бежит. Рывки утомляют его так же, как раньше. Карта не возвращает силы, которые твой Луми уже потратил.",
        ["os.racer_card_guard_2"] = "Твой Луми бежит умнее. Он выбирает путь среди соперников лучше. Он чаще находит, как их обойти. Он реже спотыкается. Он также чуть меньше устаёт. Если это делают обе серебряные карты, эффекты складываются, но только до предела.",
        ["os.racer_card_guard_3"] = "Твой Луми чаще сам делает рывки. Каждый рывок такой же быстрый и длинный, как раньше. Луми сами делают рывки только во второй части забега. Твоему Луми всё так же нужен короткий отдых между рывками.",
        ["os.racer_card_guard_4"] = "Максимальная скорость твоего Луми весь забег чуть выше. Он также может держать чуть более быстрый темп, пока не устанет. Повороты, соперники и усталость всё так же его замедляют. Поэтому время финиша улучшается не на ту же величину.",
        ["os.racer_card_guard_5"] = "Карта помогает только на старте. Твой Луми срывается со старта чуть раньше. Каждый Луми всё равно ждёт не меньше 0,04 секунды, прежде чем побежать.",
        ["os.racer_card_guard_6"] = "Твой Луми восстанавливает часть сил и может дольше бежать, не уставая. Карта срабатывает, только если твой Луми уже потратил не меньше этой доли сил. Если твой Луми сдаёт, он перестаёт сдавать. Доля считается от всех его сил, а не от остатка.",
        ["os.racer_card_guard_7"] = "Карта работает, только пока твой Луми спотыкается. Она заканчивает это спотыкание раньше. Если спотыкание почти закончилось, оно заканчивается сразу. Карта не мешает твоему Луми споткнуться снова позже.",
        ["os.racer_card_guard_8"] = "Твой Луми ненадолго бежит быстрее. Он уже должен бежать не медленнее 75% своей максимальной скорости. После карты у твоего Луми должно остаться больше 15% сил. Это не может случиться, пока твой Луми сдаёт, зажат в толпе, спотыкается или делает рывок. Это также не может случиться сразу после рывка. Если твой Луми вот-вот начнёт финишный рывок, карта ждёт. Повороты и соперники всё так же могут замедлить твоего Луми. Потом твой Луми возвращается к обычной максимальной скорости.",
        ["os.racer_card_guard_9"] = "Твой Луми делает короткий рывок. Впереди должна быть прямая. После карты у твоего Луми должно остаться больше 15% сил. Это не может случиться, пока твой Луми сдаёт, зажат в толпе, спотыкается или делает рывок. Это также не может случиться сразу после рывка. Если твой Луми вот-вот начнёт финишный рывок, карта ждёт. Этот рывок такой же быстрый, как собственные рывки твоего Луми. Потом твой Луми может сразу снова делать рывки сам.",
        // The 54 Core Set cards in catalogue order: name, face caption, availability, description, exact rule, story.
        ["os.racer_card_second_sunrise_name"] = "Второй рассвет",
        ["os.racer_card_second_sunrise_short"] = "Возвращает силы при усталости",
        ["os.racer_card_second_sunrise_cond"] = "Когда у твоего Луми мало сил.",
        ["os.racer_card_second_sunrise_desc"] = "Когда у твоего Луми мало сил, он восстанавливает их часть. Карта ждёт, пока сил станет совсем мало.",
        ["os.racer_card_second_sunrise_exact"] = "Срабатывает один раз за забег. Твой Луми восстанавливает 5% сил. Только когда у твоего Луми осталось не больше 24% сил. Это может случиться после первой четверти забега и почти до финиша.",
        ["os.racer_card_second_sunrise_story"] = "Утро нашло ещё один уголёк.",

        ["os.racer_card_banked_embers_name"] = "Тлеющие угли",
        ["os.racer_card_banked_embers_short"] = "Меньше устаёт",
        ["os.racer_card_banked_embers_cond"] = "Весь забег.",
        ["os.racer_card_banked_embers_desc"] = "Весь забег твой Луми устаёт чуть медленнее. К финишу у него остаётся чуть больше сил.",
        ["os.racer_card_banked_embers_exact"] = "Действует весь забег. Твой Луми устаёт примерно на 2,4% меньше.",
        ["os.racer_card_banked_embers_story"] = "Маленького тепла хватает надолго.",

        ["os.racer_card_lantern_vigil_name"] = "Дозорный фонарь",
        ["os.racer_card_lantern_vigil_short"] = "Бежит умнее в конце",
        ["os.racer_card_lantern_vigil_cond"] = "В конце забега, до самого финиша.",
        ["os.racer_card_lantern_vigil_desc"] = "В конце забега твой Луми бежит умнее. Он чаще находит, как обойти соперников. Он также реже спотыкается.",
        ["os.racer_card_lantern_vigil_exact"] = "Действует в конце забега, до самого финиша. Твой Луми бежит умнее. Эффект средний.",
        ["os.racer_card_lantern_vigil_story"] = "Кто-то всегда оставляет для тебя свет.",

        ["os.racer_card_warm_footing_name"] = "Тёплая опора",
        ["os.racer_card_warm_footing_short"] = "Бежит умнее в плохую погоду",
        ["os.racer_card_warm_footing_cond"] = "Весь забег. Только в дождь, снег, сильный ветер, жару, статику или пыль.",
        ["os.racer_card_warm_footing_desc"] = "В плохую погоду твой Луми бежит умнее. Он чаще находит, как обойти соперников. Он также реже спотыкается.",
        ["os.racer_card_warm_footing_exact"] = "Действует весь забег. Твой Луми бежит умнее. Эффект слабый. Только в дождь, снег, сильный ветер, жару, статику или пыль.",
        ["os.racer_card_warm_footing_story"] = "Он нашёл единственный камень, который зима пропустила.",

        ["os.racer_card_cinder_leap_name"] = "Прыжок из пепла",
        ["os.racer_card_cinder_leap_short"] = "Рывок в погоню за лидером",
        ["os.racer_card_cinder_leap_cond"] = "Пока твой Луми позади лидера.",
        ["os.racer_card_cinder_leap_desc"] = "В середине забега твой Луми делает рывок, чтобы догнать лидера. Впереди должна быть прямая.",
        ["os.racer_card_cinder_leap_exact"] = "Срабатывает один раз за забег. Твой Луми делает рывок на 0,55 секунды. Это отнимает 1% сил. Лидер должен быть впереди хотя бы на 1,2 корпуса. Это может случиться в середине забега.",
        ["os.racer_card_cinder_leap_story"] = "На один удар сердца взлетел даже пепел.",

        ["os.racer_card_slow_burn_name"] = "Медленный жар",
        ["os.racer_card_slow_burn_short"] = "Меньше устаёт в гору",
        ["os.racer_card_slow_burn_cond"] = "На подъёме.",
        ["os.racer_card_slow_burn_desc"] = "На подъёме твой Луми устаёт медленнее. На остаток забега у него остаётся больше сил.",
        ["os.racer_card_slow_burn_exact"] = "Действует, пока твой Луми бежит в гору. Твой Луми устаёт примерно на 7% меньше.",
        ["os.racer_card_slow_burn_story"] = "Холм был терпелив. Уголёк тоже.",

        ["os.racer_card_sheltered_spark_name"] = "Искра в укрытии",
        ["os.racer_card_sheltered_spark_short"] = "Больше рывков в плохую погоду",
        ["os.racer_card_sheltered_spark_cond"] = "Весь забег. Только в дождь, снег, сильный ветер, жару, статику или пыль.",
        ["os.racer_card_sheltered_spark_desc"] = "В плохую погоду твой Луми чаще сам делает рывки.",
        ["os.racer_card_sheltered_spark_exact"] = "Действует весь забег. Твой Луми сам делает рывки на 11% чаще. Только в дождь, снег, сильный ветер, жару, статику или пыль.",
        ["os.racer_card_sheltered_spark_story"] = "Дождь мог подождать снаружи.",

        ["os.racer_card_home_by_firelight_name"] = "Домой к очагу",
        ["os.racer_card_home_by_firelight_short"] = "Выше максимальная скорость",
        ["os.racer_card_home_by_firelight_cond"] = "Весь забег.",
        ["os.racer_card_home_by_firelight_desc"] = "Весь забег твой Луми бежит чуточку быстрее.",
        ["os.racer_card_home_by_firelight_exact"] = "Действует весь забег. Максимальная скорость твоего Луми немного выше. За долгий забег это даёт ему примерно до 0,3 корпуса преимущества.",
        ["os.racer_card_home_by_firelight_story"] = "Последние шаги пахли домом.",

        ["os.racer_card_last_light_name"] = "Последний свет",
        ["os.racer_card_last_light_short"] = "Рывок в погоню за лидером",
        ["os.racer_card_last_light_cond"] = "Пока твой Луми позади лидера.",
        ["os.racer_card_last_light_desc"] = "Ближе к концу забега твой Луми делает рывок, чтобы догнать лидера. Впереди должна быть прямая.",
        ["os.racer_card_last_light_exact"] = "Срабатывает один раз за забег. Твой Луми делает рывок на 0,65 секунды. Это отнимает 1% сил. Лидер должен быть впереди хотя бы на 0,5 корпуса. Это может случиться ближе к концу забега.",
        ["os.racer_card_last_light_story"] = "Он приберёг одну светлую мысль напоследок.",

        ["os.racer_card_storm_whispers_name"] = "Шёпот грозы",
        ["os.racer_card_storm_whispers_short"] = "Бежит умнее",
        ["os.racer_card_storm_whispers_cond"] = "Весь забег.",
        ["os.racer_card_storm_whispers_desc"] = "Весь забег твой Луми бежит умнее. Он чаще находит, как обойти соперников. Он также реже спотыкается.",
        ["os.racer_card_storm_whispers_exact"] = "Действует весь забег. Твой Луми бежит умнее. Эффект слабый.",
        ["os.racer_card_storm_whispers_story"] = "Самый тихий треск сказал ему первым.",

        ["os.racer_card_borrowed_thunder_name"] = "Одолженный гром",
        ["os.racer_card_borrowed_thunder_short"] = "Рывок на прямой",
        ["os.racer_card_borrowed_thunder_cond"] = "На прямой.",
        ["os.racer_card_borrowed_thunder_desc"] = "В середине забега твой Луми делает рывок на прямой.",
        ["os.racer_card_borrowed_thunder_exact"] = "Срабатывает один раз за забег. Твой Луми делает рывок на 0,45 секунды. Это отнимает 1% сил. Это может случиться в середине забега.",
        ["os.racer_card_borrowed_thunder_story"] = "Маленькое облако ответило очень громко.",

        ["os.racer_card_paper_promises_name"] = "Бумажные обещания",
        ["os.racer_card_paper_promises_short"] = "Раньше стартует",
        ["os.racer_card_paper_promises_cond"] = "На старте.",
        ["os.racer_card_paper_promises_desc"] = "Твой Луми раньше срывается со старта.",
        ["os.racer_card_paper_promises_exact"] = "Действует на старте забега. Твой Луми ждёт на старте на 4% меньше. Каждый Луми всё равно ждёт не меньше 0,04 секунды.",
        ["os.racer_card_paper_promises_story"] = "Он не потерял форму, когда ветер сменился.",

        ["os.racer_card_blink_of_brilliance_name"] = "Проблеск озарения",
        ["os.racer_card_blink_of_brilliance_short"] = "Ускоряется, когда больше не зажат",
        ["os.racer_card_blink_of_brilliance_cond"] = "Сразу после того, как твой Луми перестал быть зажатым, пока впереди ещё есть соперник.",
        ["os.racer_card_blink_of_brilliance_desc"] = "Твой Луми ненадолго бежит быстрее сразу после того, как соперник перестаёт его зажимать. Это может случиться на большей части забега.",
        ["os.racer_card_blink_of_brilliance_exact"] = "Срабатывает один раз за забег, после старта и почти до финиша. Максимальная скорость твоего Луми выше на 8% в течение 1,4 секунды. Это отнимает 1% сил. Только в первую секунду после того, как твой Луми перестал быть зажатым. Впереди должен быть соперник.",
        ["os.racer_card_blink_of_brilliance_story"] = "На миг ответ был совсем рядом.",

        ["os.racer_card_quiet_charge_name"] = "Тихий заряд",
        ["os.racer_card_quiet_charge_short"] = "Чаще делает рывки",
        ["os.racer_card_quiet_charge_cond"] = "Весь забег.",
        ["os.racer_card_quiet_charge_desc"] = "Весь забег твой Луми чаще сам делает рывки.",
        ["os.racer_card_quiet_charge_exact"] = "Действует весь забег. Твой Луми сам делает рывки на 7,5% чаще.",
        ["os.racer_card_quiet_charge_story"] = "Спешить тратить искру было незачем.",

        ["os.racer_card_copper_company_name"] = "Медная компания",
        ["os.racer_card_copper_company_short"] = "Меньше устаёт за соперником",
        ["os.racer_card_copper_company_cond"] = "Пока держится вплотную за соперником.",
        ["os.racer_card_copper_company_desc"] = "Пока твой Луми держится вплотную за соперником, он устаёт медленнее. Помощь пропадает, как только он перестаёт держаться вплотную.",
        ["os.racer_card_copper_company_exact"] = "Действует, пока твой Луми держится вплотную за соперником. Твой Луми устаёт примерно на 9,1% меньше.",
        ["os.racer_card_copper_company_story"] = "В компании дорога звучала добрее.",

        ["os.racer_card_after_the_flash_name"] = "После вспышки",
        ["os.racer_card_after_the_flash_short"] = "Бежит умнее после спотыканий в плохую погоду",
        ["os.racer_card_after_the_flash_cond"] = "Сразу после спотыкания. Только в дождь, снег, сильный ветер, жару, статику или пыль.",
        ["os.racer_card_after_the_flash_desc"] = "В плохую погоду, сразу после спотыкания, твой Луми ненадолго бежит умнее. Он чаще находит, как обойти соперников. Он реже спотыкается снова.",
        ["os.racer_card_after_the_flash_exact"] = "Действует 2 секунды после каждого спотыкания. Твой Луми бежит умнее. Эффект сильный. Только в дождь, снег, сильный ветер, жару, статику или пыль.",
        ["os.racer_card_after_the_flash_story"] = "Лужи помнили. Он бежал дальше.",

        ["os.racer_card_bright_idea_name"] = "Светлая мысль",
        ["os.racer_card_bright_idea_short"] = "Бежит умнее в поворотах",
        ["os.racer_card_bright_idea_cond"] = "В повороте.",
        ["os.racer_card_bright_idea_desc"] = "В поворотах твой Луми бежит умнее. Он чаще находит, как обойти соперников. Он также реже спотыкается.",
        ["os.racer_card_bright_idea_exact"] = "Действует, пока твой Луми бежит в повороте. Твой Луми бежит умнее. Эффект средний.",
        ["os.racer_card_bright_idea_story"] = "Он увидел путь между каплями дождя.",

        ["os.racer_card_catch_the_spark_name"] = "Поймай искру",
        ["os.racer_card_catch_the_spark_short"] = "Рывок после спотыкания",
        ["os.racer_card_catch_the_spark_cond"] = "Сразу после спотыкания.",
        ["os.racer_card_catch_the_spark_desc"] = "Сразу после спотыкания твой Луми делает рывок, чтобы снова набрать ход. Впереди должна быть прямая.",
        ["os.racer_card_catch_the_spark_exact"] = "Срабатывает один раз за забег. Твой Луми делает рывок на 0,5 секунды. Это отнимает 1% сил. Только в течение 2 секунд после спотыкания. Это может случиться после старта и почти до финиша.",
        ["os.racer_card_catch_the_spark_story"] = "Заметить было ещё не поздно.",

        ["os.racer_card_featherlight_steps_name"] = "Шаги легче пера",
        ["os.racer_card_featherlight_steps_short"] = "Меньше устаёт в начале",
        ["os.racer_card_featherlight_steps_cond"] = "В первой трети забега.",
        ["os.racer_card_featherlight_steps_desc"] = "В первой трети забега твой Луми устаёт медленнее. На потом у него остаётся больше сил.",
        ["os.racer_card_featherlight_steps_exact"] = "Действует в первой трети забега. Твой Луми устаёт примерно на 3,8% меньше.",
        ["os.racer_card_featherlight_steps_story"] = "Трава едва заметила, что он пробежал.",

        ["os.racer_card_leeward_path_name"] = "Подветренная тропа",
        ["os.racer_card_leeward_path_short"] = "Меньше устаёт в сильный ветер",
        ["os.racer_card_leeward_path_cond"] = "Весь забег. Только в сильный ветер.",
        ["os.racer_card_leeward_path_desc"] = "В сильный ветер твой Луми весь забег устаёт медленнее. К финишу у него остаётся больше сил.",
        ["os.racer_card_leeward_path_exact"] = "Действует весь забег. Твой Луми устаёт примерно на 4,8% меньше. Только в сильный ветер.",
        ["os.racer_card_leeward_path_story"] = "С этой стороны холм хранил немного тишины.",

        ["os.racer_card_thread_the_gust_name"] = "Сквозь порыв",
        ["os.racer_card_thread_the_gust_short"] = "Ускоряется, когда больше не зажат",
        ["os.racer_card_thread_the_gust_cond"] = "Сразу после того, как твой Луми перестал быть зажатым, пока впереди ещё есть соперник.",
        ["os.racer_card_thread_the_gust_desc"] = "В середине забега твой Луми ненадолго бежит быстрее сразу после того, как соперник перестаёт его зажимать.",
        ["os.racer_card_thread_the_gust_exact"] = "Срабатывает один раз за забег, в середине забега. Максимальная скорость твоего Луми выше на 9% в течение 1,5 секунды. Это отнимает 1% сил. Только в первую секунду после того, как твой Луми перестал быть зажатым. Впереди должен быть соперник.",
        ["os.racer_card_thread_the_gust_story"] = "Ветерок оставил ровно столько места, сколько нужно.",

        ["os.racer_card_lift_together_name"] = "Вместе на ветру",
        ["os.racer_card_lift_together_short"] = "Возвращает силы за соперником",
        ["os.racer_card_lift_together_cond"] = "Пока бежит прямо за соперником.",
        ["os.racer_card_lift_together_desc"] = "В середине забега твой Луми восстанавливает часть сил. Он должен бежать прямо за соперником, а не сбоку.",
        ["os.racer_card_lift_together_exact"] = "Срабатывает один раз за забег. Твой Луми восстанавливает 4% сил. Только пока твой Луми бежит прямо за соперником. Это может случиться в середине забега.",
        ["os.racer_card_lift_together_story"] = "Смелость летела на том же ветерке.",

        ["os.racer_card_ribbon_weather_name"] = "Ленточная погода",
        ["os.racer_card_ribbon_weather_short"] = "Бежит умнее в ясную погоду",
        ["os.racer_card_ribbon_weather_cond"] = "Весь забег. Только в ясную погоду.",
        ["os.racer_card_ribbon_weather_desc"] = "В ясную погоду твой Луми весь забег бежит умнее. Он чаще находит, как обойти соперников. Он также реже спотыкается.",
        ["os.racer_card_ribbon_weather_exact"] = "Действует весь забег. Твой Луми бежит умнее. Эффект слабый. Только в ясную погоду.",
        ["os.racer_card_ribbon_weather_story"] = "Одного трепета ленты ему хватило.",

        ["os.racer_card_long_glide_name"] = "Долгое парение",
        ["os.racer_card_long_glide_short"] = "Меньше устаёт в ясную погоду",
        ["os.racer_card_long_glide_cond"] = "Весь забег. Только в ясную погоду.",
        ["os.racer_card_long_glide_desc"] = "В ясную погоду твой Луми весь забег устаёт медленнее. К финишу у него остаётся больше сил.",
        ["os.racer_card_long_glide_exact"] = "Действует весь забег. Твой Луми устаёт примерно на 2,7% меньше. Только в ясную погоду.",
        ["os.racer_card_long_glide_story"] = "Было время дать воздуху сделать своё дело.",

        ["os.racer_card_pocket_of_calm_name"] = "Островок покоя",
        ["os.racer_card_pocket_of_calm_short"] = "Бежит умнее в группе",
        ["os.racer_card_pocket_of_calm_cond"] = "Когда рядом соперники.",
        ["os.racer_card_pocket_of_calm_desc"] = "Когда рядом хотя бы 2 соперника, твой Луми бежит умнее. Он чаще находит, как их обойти.",
        ["os.racer_card_pocket_of_calm_exact"] = "Действует, пока рядом хотя бы 2 соперника. Твой Луми бежит умнее. Эффект средний.",
        ["os.racer_card_pocket_of_calm_story"] = "Он нашёл место для одного тихого вдоха.",

        ["os.racer_card_borrowed_wings_name"] = "Крылья взаймы",
        ["os.racer_card_borrowed_wings_short"] = "Короче спотыкание в конце",
        ["os.racer_card_borrowed_wings_cond"] = "Пока твой Луми спотыкается.",
        ["os.racer_card_borrowed_wings_desc"] = "Во второй половине забега эта карта один раз сокращает спотыкание.",
        ["os.racer_card_borrowed_wings_exact"] = "Срабатывает один раз за забег. Спотыкание твоего Луми заканчивается до 0,35 секунды раньше. Только пока твой Луми спотыкается. Это может случиться во второй половине забега.",
        ["os.racer_card_borrowed_wings_story"] = "Следующий вдох уже был в пути.",

        ["os.racer_card_home_on_the_breeze_name"] = "Домой с ветерком",
        ["os.racer_card_home_on_the_breeze_short"] = "Быстрее в плохую погоду",
        ["os.racer_card_home_on_the_breeze_cond"] = "Весь забег. Только в дождь, снег, сильный ветер, жару, статику или пыль.",
        ["os.racer_card_home_on_the_breeze_desc"] = "В плохую погоду твой Луми весь забег бежит чуточку быстрее.",
        ["os.racer_card_home_on_the_breeze_exact"] = "Действует весь забег. Максимальная скорость твоего Луми немного выше. За долгий забег это даёт ему примерно до 0,43 корпуса преимущества. Только в дождь, снег, сильный ветер, жару, статику или пыль.",
        ["os.racer_card_home_on_the_breeze_story"] = "Он узнал сад по тому, как тот дышал.",

        ["os.racer_card_quiet_footing_name"] = "Тихая поступь",
        ["os.racer_card_quiet_footing_short"] = "Бежит умнее в крутых поворотах",
        ["os.racer_card_quiet_footing_cond"] = "В крутом повороте.",
        ["os.racer_card_quiet_footing_desc"] = "В крутых поворотах твой Луми бежит умнее. Он чаще находит, как обойти соперников. Он также реже спотыкается.",
        ["os.racer_card_quiet_footing_exact"] = "Действует, пока твой Луми бежит в крутом повороте. Твой Луми бежит умнее. Эффект сильный.",
        ["os.racer_card_quiet_footing_story"] = "Иней уступил место осторожным лапам.",

        ["os.racer_card_winter_reprieve_name"] = "Зимняя передышка",
        ["os.racer_card_winter_reprieve_short"] = "Возвращает силы в дождь или снег",
        ["os.racer_card_winter_reprieve_cond"] = "Когда у твоего Луми мало сил. Только в дождь или снег.",
        ["os.racer_card_winter_reprieve_desc"] = "В дождь или снег, когда у твоего Луми мало сил, он восстанавливает их часть. Карта может сработать рано в забеге.",
        ["os.racer_card_winter_reprieve_exact"] = "Срабатывает один раз за забег. Твой Луми восстанавливает 5,5% сил. Только когда у твоего Луми осталось не больше 30% сил. Только в дождь или снег. Это может случиться после первой четверти забега и почти до финиша.",
        ["os.racer_card_winter_reprieve_story"] = "Холод замер на один добрый миг.",

        ["os.racer_card_clear_reflection_name"] = "Чистое отражение",
        ["os.racer_card_clear_reflection_short"] = "Раньше стартует в ясную погоду",
        ["os.racer_card_clear_reflection_cond"] = "На старте. Только в ясную погоду.",
        ["os.racer_card_clear_reflection_desc"] = "В ясную погоду твой Луми раньше срывается со старта.",
        ["os.racer_card_clear_reflection_exact"] = "Действует на старте забега. Твой Луми ждёт на старте на 5% меньше. Каждый Луми всё равно ждёт не меньше 0,04 секунды. Только в ясную погоду.",
        ["os.racer_card_clear_reflection_story"] = "Он слушал глазами.",

        ["os.racer_card_under_the_snow_name"] = "Под снегом",
        ["os.racer_card_under_the_snow_short"] = "Меньше устаёт в снегопад",
        ["os.racer_card_under_the_snow_cond"] = "Весь забег. Только в снегопад.",
        ["os.racer_card_under_the_snow_desc"] = "В снегопад твой Луми весь забег устаёт медленнее. К финишу у него остаётся больше сил.",
        ["os.racer_card_under_the_snow_exact"] = "Действует весь забег. Твой Луми устаёт примерно на 4,8% меньше. Только в снегопад.",
        ["os.racer_card_under_the_snow_story"] = "Зима сохранила тепло в самой маленькой комнатке.",

        ["os.racer_card_still_as_starlight_name"] = "Тихо, как звёзды",
        ["os.racer_card_still_as_starlight_short"] = "Бежит умнее в конце в ясную погоду",
        ["os.racer_card_still_as_starlight_cond"] = "В конце забега, до самого финиша. Только в ясную погоду.",
        ["os.racer_card_still_as_starlight_desc"] = "В ясную погоду твой Луми бежит умнее в конце забега. Он чаще находит, как обойти соперников. Он также реже спотыкается.",
        ["os.racer_card_still_as_starlight_exact"] = "Действует в конце забега, до самого финиша. Твой Луми бежит умнее. Эффект средний. Только в ясную погоду.",
        ["os.racer_card_still_as_starlight_story"] = "Даже звёзды, казалось, стали говорить тише.",

        ["os.racer_card_one_perfect_step_name"] = "Один верный шаг",
        ["os.racer_card_one_perfect_step_short"] = "Ускоряется после поворота",
        ["os.racer_card_one_perfect_step_cond"] = "Сразу после поворота.",
        ["os.racer_card_one_perfect_step_desc"] = "Сразу после поворота твой Луми ненадолго бежит быстрее.",
        ["os.racer_card_one_perfect_step_exact"] = "Срабатывает один раз за забег. Максимальная скорость твоего Луми выше на 8,5% в течение 1,4 секунды. Это отнимает 1% сил. Только в первую секунду после поворота. Это может случиться после старта и почти до финиша.",
        ["os.racer_card_one_perfect_step_story"] = "Он доверился маленькому пятачку чистой земли.",

        ["os.racer_card_ring_the_frost_name"] = "Звон инея",
        ["os.racer_card_ring_the_frost_short"] = "Короче спотыкание",
        ["os.racer_card_ring_the_frost_cond"] = "Пока твой Луми спотыкается.",
        ["os.racer_card_ring_the_frost_desc"] = "Почти в любой момент забега эта карта один раз сокращает спотыкание.",
        ["os.racer_card_ring_the_frost_exact"] = "Срабатывает один раз за забег. Спотыкание твоего Луми заканчивается до 0,3 секунды раньше. Только пока твой Луми спотыкается. Это может случиться почти в любой момент забега.",
        ["os.racer_card_ring_the_frost_story"] = "Одна чистая нота стряхнула тревогу.",

        ["os.racer_card_soft_landing_name"] = "Мягкая посадка",
        ["os.racer_card_soft_landing_short"] = "Бежит умнее под гору",
        ["os.racer_card_soft_landing_cond"] = "На спуске.",
        ["os.racer_card_soft_landing_desc"] = "На спуске твой Луми бежит умнее. Он чаще находит, как обойти соперников. Он также реже спотыкается.",
        ["os.racer_card_soft_landing_exact"] = "Действует, пока твой Луми бежит под гору. Твой Луми бежит умнее. Эффект сильный.",
        ["os.racer_card_soft_landing_story"] = "Снег берёг это место.",

        ["os.racer_card_thaw_comes_slowly_name"] = "Оттепель не спешит",
        ["os.racer_card_thaw_comes_slowly_short"] = "Меньше устаёт в конце",
        ["os.racer_card_thaw_comes_slowly_cond"] = "В конце забега, до самого финиша.",
        ["os.racer_card_thaw_comes_slowly_desc"] = "В конце забега твой Луми устаёт медленнее. К финишу у него остаётся больше сил.",
        ["os.racer_card_thaw_comes_slowly_exact"] = "Действует в конце забега, до самого финиша. Твой Луми устаёт примерно на 4,8% меньше.",
        ["os.racer_card_thaw_comes_slowly_story"] = "Немного тепла хватило, чтобы начать.",

        ["os.racer_card_follow_the_flow_name"] = "По течению",
        ["os.racer_card_follow_the_flow_short"] = "Меньше устаёт на прямых",
        ["os.racer_card_follow_the_flow_cond"] = "На прямой.",
        ["os.racer_card_follow_the_flow_desc"] = "На прямых твой Луми устаёт медленнее. На остаток забега у него остаётся больше сил.",
        ["os.racer_card_follow_the_flow_exact"] = "Действует, пока твой Луми бежит по прямой. Твой Луми устаёт примерно на 4,3% меньше.",
        ["os.racer_card_follow_the_flow_story"] = "Течение знало путь помягче.",

        ["os.racer_card_puddle_lessons_name"] = "Уроки луж",
        ["os.racer_card_puddle_lessons_short"] = "Бежит умнее после спотыкания",
        ["os.racer_card_puddle_lessons_cond"] = "Сразу после спотыкания.",
        ["os.racer_card_puddle_lessons_desc"] = "Сразу после спотыкания твой Луми ненадолго бежит умнее. Он чаще находит, как обойти соперников. Он реже спотыкается снова.",
        ["os.racer_card_puddle_lessons_exact"] = "Действует 2 секунды после каждого спотыкания. Твой Луми бежит умнее. Эффект средний.",
        ["os.racer_card_puddle_lessons_story"] = "У каждой лужи было что рассказать.",

        ["os.racer_card_turning_tide_name"] = "Смена прилива",
        ["os.racer_card_turning_tide_short"] = "Возвращает силы при усталости",
        ["os.racer_card_turning_tide_cond"] = "Когда у твоего Луми мало сил.",
        ["os.racer_card_turning_tide_desc"] = "Примерно с середины забега, когда у твоего Луми мало сил, он восстанавливает их часть.",
        ["os.racer_card_turning_tide_exact"] = "Срабатывает один раз за забег. Твой Луми восстанавливает 4% сил. Только когда у твоего Луми осталось не больше 35% сил. Это может случиться примерно с середины забега и почти до финиша.",
        ["os.racer_card_turning_tide_story"] = "Вода предложила другой путь.",

        ["os.racer_card_pearls_of_patience_name"] = "Жемчуг терпения",
        ["os.racer_card_pearls_of_patience_short"] = "Больше рывков во второй половине",
        ["os.racer_card_pearls_of_patience_cond"] = "Во второй половине забега.",
        ["os.racer_card_pearls_of_patience_desc"] = "Во второй половине забега твой Луми чаще сам делает рывки.",
        ["os.racer_card_pearls_of_patience_exact"] = "Действует во второй половине забега. Твой Луми сам делает рывки на 13% чаще.",
        ["os.racer_card_pearls_of_patience_story"] = "Он дал пузырькам подняться в своё время.",

        ["os.racer_card_over_the_water_name"] = "Через воду",
        ["os.racer_card_over_the_water_short"] = "Рывок в погоню за лидером",
        ["os.racer_card_over_the_water_cond"] = "Пока твой Луми позади лидера.",
        ["os.racer_card_over_the_water_desc"] = "После первой трети забега твой Луми делает рывок, чтобы догнать лидера. Впереди должна быть прямая.",
        ["os.racer_card_over_the_water_exact"] = "Срабатывает один раз за забег. Твой Луми делает рывок на 0,65 секунды. Это отнимает 1% сил. Лидер должен быть впереди хотя бы на 0,8 корпуса. Это может случиться после первой трети забега и почти до финиша.",
        ["os.racer_card_over_the_water_story"] = "Камней хватило ровно на то, чтобы быть смелым.",

        ["os.racer_card_rain_on_glass_name"] = "Дождь по стеклу",
        ["os.racer_card_rain_on_glass_short"] = "Бежит умнее в мокрых поворотах",
        ["os.racer_card_rain_on_glass_cond"] = "В повороте. Только в дождь.",
        ["os.racer_card_rain_on_glass_desc"] = "В поворотах в дождь твой Луми бежит умнее. Он чаще находит, как обойти соперников. Он также реже спотыкается.",
        ["os.racer_card_rain_on_glass_exact"] = "Действует, пока твой Луми бежит в повороте. Твой Луми бежит умнее. Эффект сильный. Только в дождь.",
        ["os.racer_card_rain_on_glass_story"] = "Он считал паузы между каплями.",

        ["os.racer_card_ripple_returned_name"] = "Ответная рябь",
        ["os.racer_card_ripple_returned_short"] = "Возвращает силы после спотыкания",
        ["os.racer_card_ripple_returned_cond"] = "Сразу после спотыкания.",
        ["os.racer_card_ripple_returned_desc"] = "Сразу после спотыкания твой Луми восстанавливает часть сил.",
        ["os.racer_card_ripple_returned_exact"] = "Срабатывает один раз за забег. Твой Луми восстанавливает 5% сил. Только в течение 2 секунд после спотыкания. Это может случиться после старта и почти до финиша.",
        ["os.racer_card_ripple_returned_story"] = "Вторая волна застала его готовым.",

        ["os.racer_card_low_tide_friends_name"] = "Друзья отлива",
        ["os.racer_card_low_tide_friends_short"] = "Бежит умнее за соперником",
        ["os.racer_card_low_tide_friends_cond"] = "Пока держится вплотную за соперником.",
        ["os.racer_card_low_tide_friends_desc"] = "Пока твой Луми держится вплотную за соперником, он бежит умнее. Он чаще находит, как обойти соперников. Он также реже спотыкается.",
        ["os.racer_card_low_tide_friends_exact"] = "Действует, пока твой Луми держится вплотную за соперником. Твой Луми бежит умнее. Эффект сильный.",
        ["os.racer_card_low_tide_friends_story"] = "Некоторые дороги лучше проходить со скоростью разговора.",

        ["os.racer_card_smooth_pebble_promise_name"] = "Гладкий камешек",
        ["os.racer_card_smooth_pebble_promise_short"] = "Быстрее в ясную погоду",
        ["os.racer_card_smooth_pebble_promise_cond"] = "Весь забег. Только в ясную погоду.",
        ["os.racer_card_smooth_pebble_promise_desc"] = "В ясную погоду твой Луми весь забег бежит чуточку быстрее.",
        ["os.racer_card_smooth_pebble_promise_exact"] = "Действует весь забег. Максимальная скорость твоего Луми немного выше. За долгий забег это даёт ему примерно до 0,35 корпуса преимущества. Только в ясную погоду.",
        ["os.racer_card_smooth_pebble_promise_story"] = "Он донёс эту мелочь до самого дома.",

        ["os.racer_card_stand_together_name"] = "Плечом к плечу",
        ["os.racer_card_stand_together_short"] = "Возвращает силы в группе",
        ["os.racer_card_stand_together_cond"] = "Когда рядом соперники.",
        ["os.racer_card_stand_together_desc"] = "В середине забега твой Луми восстанавливает часть сил. Рядом должны быть хотя бы 2 соперника.",
        ["os.racer_card_stand_together_exact"] = "Срабатывает один раз за забег. Твой Луми восстанавливает 4% сил. Только когда рядом хотя бы 2 соперника. Это может случиться в середине забега.",
        ["os.racer_card_stand_together_story"] = "Рядом с другом он стоял чуть выше.",

        ["os.racer_card_roots_remember_name"] = "Корни помнят",
        ["os.racer_card_roots_remember_short"] = "Бежит умнее в гору",
        ["os.racer_card_roots_remember_cond"] = "На подъёме.",
        ["os.racer_card_roots_remember_desc"] = "На подъёме твой Луми бежит умнее. Он чаще находит, как обойти соперников. Он также реже спотыкается.",
        ["os.racer_card_roots_remember_exact"] = "Действует, пока твой Луми бежит в гору. Твой Луми бежит умнее. Эффект сильный.",
        ["os.racer_card_roots_remember_story"] = "Самая старая тропа всё ещё помнила его имя.",

        ["os.racer_card_patient_path_name"] = "Терпеливый путь",
        ["os.racer_card_patient_path_short"] = "Меньше устаёт в начале в ясную погоду",
        ["os.racer_card_patient_path_cond"] = "В первой половине забега. Только в ясную погоду.",
        ["os.racer_card_patient_path_desc"] = "В ясную погоду твой Луми устаёт медленнее в первой половине забега. На потом у него остаётся больше сил.",
        ["os.racer_card_patient_path_exact"] = "Действует в первой половине забега. Твой Луми устаёт примерно на 5,2% меньше. Только в ясную погоду.",
        ["os.racer_card_patient_path_story"] = "Маленькие шаги всё равно вели его куда-то.",

        ["os.racer_card_mossbound_shelter_name"] = "Укрытие во мху",
        ["os.racer_card_mossbound_shelter_short"] = "Меньше устаёт в пыльную погоду",
        ["os.racer_card_mossbound_shelter_cond"] = "Весь забег. Только в пыльную погоду.",
        ["os.racer_card_mossbound_shelter_desc"] = "В пыльную погоду твой Луми весь забег устаёт медленнее. К финишу у него остаётся больше сил.",
        ["os.racer_card_mossbound_shelter_exact"] = "Действует весь забег. Твой Луми устаёт примерно на 4,8% меньше. Только в пыльную погоду.",
        ["os.racer_card_mossbound_shelter_story"] = "Камень приберёг сухой уголок как раз для этого.",

        ["os.racer_card_little_ballast_name"] = "Немного балласта",
        ["os.racer_card_little_ballast_short"] = "Раньше стартует в плохую погоду",
        ["os.racer_card_little_ballast_cond"] = "На старте. Только в дождь, снег, сильный ветер, жару, статику или пыль.",
        ["os.racer_card_little_ballast_desc"] = "В плохую погоду твой Луми раньше срывается со старта.",
        ["os.racer_card_little_ballast_exact"] = "Действует на старте забега. Твой Луми ждёт на старте на 5,5% меньше. Каждый Луми всё равно ждёт не меньше 0,04 секунды. Только в дождь, снег, сильный ветер, жару, статику или пыль.",
        ["os.racer_card_little_ballast_story"] = "Один маленький груз сделал мир устойчивее.",

        ["os.racer_card_hold_the_hill_name"] = "Удержать холм",
        ["os.racer_card_hold_the_hill_short"] = "Ускоряется после подъёма",
        ["os.racer_card_hold_the_hill_cond"] = "Сразу после подъёма.",
        ["os.racer_card_hold_the_hill_desc"] = "Сразу после подъёма твой Луми ненадолго бежит быстрее.",
        ["os.racer_card_hold_the_hill_exact"] = "Срабатывает один раз за забег. Максимальная скорость твоего Луми выше на 10% в течение 1,6 секунды. Это отнимает 1% сил. Только в первую секунду после подъёма. Это может случиться после старта и почти до финиша.",
        ["os.racer_card_hold_the_hill_story"] = "Склон спросил. Он ответил ещё одним усилием.",

        ["os.racer_card_kindly_ground_name"] = "Добрая земля",
        ["os.racer_card_kindly_ground_short"] = "Меньше устаёт после спотыкания",
        ["os.racer_card_kindly_ground_cond"] = "Сразу после спотыкания.",
        ["os.racer_card_kindly_ground_desc"] = "Сразу после спотыкания твой Луми ненадолго устаёт медленнее.",
        ["os.racer_card_kindly_ground_exact"] = "Действует 2 секунды после каждого спотыкания. Твой Луми устаёт примерно на 9,1% меньше.",
        ["os.racer_card_kindly_ground_story"] = "Земля была не против минутки отдыха.",

        ["os.racer_card_mountain_answers_name"] = "Гора отвечает",
        ["os.racer_card_mountain_answers_short"] = "Короче спотыкание в начале",
        ["os.racer_card_mountain_answers_cond"] = "Пока твой Луми спотыкается.",
        ["os.racer_card_mountain_answers_desc"] = "В первой половине забега эта карта один раз сокращает спотыкание.",
        ["os.racer_card_mountain_answers_exact"] = "Срабатывает один раз за забег. Спотыкание твоего Луми заканчивается до 0,4 секунды раньше. Только пока твой Луми спотыкается. Это может случиться в первой половине забега.",
        ["os.racer_card_mountain_answers_story"] = "Его маленькая смелая нота нашла очень большое эхо.",

        ["os.racer_card_home_in_a_shell_name"] = "Дом в ракушке",
        ["os.racer_card_home_in_a_shell_short"] = "Меньше устаёт, когда сил мало",
        ["os.racer_card_home_in_a_shell_cond"] = "Когда у твоего Луми мало сил.",
        ["os.racer_card_home_in_a_shell_desc"] = "Когда у твоего Луми мало сил, он устаёт медленнее. Карта перестаёт помогать, когда сил снова становится больше.",
        ["os.racer_card_home_in_a_shell_exact"] = "Действует, когда у твоего Луми осталось не больше 35% сил. Твой Луми устаёт примерно на 6,5% меньше.",
        ["os.racer_card_home_in_a_shell_story"] = "Он взял с собой тихую частичку дома.",

        ["os.racer_hand_pick_prompt"] = "{0}: нажми на карту ниже.",
        ["os.racer_album_off"] = "Гоночные карты сейчас отключены.",
        ["os.racer_pack_accessory"] = "Аксессуар",
        ["os.racer_pack_colour"] = "Цвет",
        ["os.racer_card_move_silver"] = "Переложить в серебряный слот {0}",
        ["os.racer_hand_explain"] = "Карты для забега дают твоему {0} бонусы в забегах. Золотая карта активная, {0} использует её сам. Серебряные карты дают разные пассивные бонусы. Выбери свои карты.",
        ["os.racer_hand_enter_the_cup"] = "Участвовать в кубке",
        ["os.racer_hand_none_gold"] = "У тебя пока нет золотых карт. Их можно получить из наборов с призами.",
        ["os.racer_hand_none_silver"] = "У тебя пока нет серебряных карт. Их можно получить из наборов с призами.",
        ["os.racer_cards_per_row_1"] = "Показывать одну карту в ряду",
        ["os.racer_cards_per_row_2"] = "Показывать две карты в ряду",
        ["os.racer_cards_per_row_3"] = "Показывать три карты в ряду",
        ["os.racer_inspect_levels"] = "Уровни",
        ["os.racer_inspect_level_bonus"] = "Плюс {0}% к бонусу",
        ["os.racer_inspect_level_default"] = "Обычный бонус карты",
        ["os.racer_hand_lumi"] = "Луми",
        ["os.racer_hand_info_close"] = "Закрыть",
    };
}
