using System.Collections.Generic;

namespace AetherOS.Apps.Racer.Localization;

public static partial class AppStrings
{
    // added after update 2.7.0 (racing cards)
    private static readonly IReadOnlyDictionary<string, string> CardsPt = new Dictionary<string, string>
    {
        // Album (the Bonus cards tab)
        ["os.racer_album_intro"] = "Os pacotes de prémios dão-te cartas de corrida. Escolhe uma carta de ouro e duas cartas de prata para a tua mão.",
        ["os.racer_album_levels"] = "Um pacote pode dar-te uma carta que já tens. Essa carta sobe então um nível. No nível 2, o efeito dela é 15% mais forte. No nível 3, é 30% mais forte. Os pacotes deixam de te dar uma carta quando ela chega ao nível 3.",
        ["os.racer_album_filter_elements"] = "Todos os elementos",
        ["os.racer_album_filter_cards"] = "Todas as cartas",
        ["os.racer_album_filter_gold"] = "Ouro",
        ["os.racer_album_filter_silver"] = "Prata",
        ["os.racer_album_compact"] = "Compacto",
        ["os.racer_album_search"] = "Procurar uma carta",
        ["os.racer_album_no_match"] = "Nenhuma carta corresponde. Muda os filtros.",
        ["os.racer_album_none"] = "Ainda não tens cartas de corrida. Abre pacotes de prémios para as ganhares.",
        ["os.racer_album_progress"] = "{0} de {1} cartas encontradas",
        ["os.racer_album_copies"] = "{0} cópias",
        ["os.racer_album_not_found"] = "Ainda não encontrada",
        // Hand dock and hand strips
        ["os.racer_hand_title"] = "Cartas de corrida",
        ["os.racer_hand_choose_gold"] = "Escolher ouro",
        ["os.racer_hand_choose_silver"] = "Escolher prata",
        ["os.racer_hand_swap"] = "Trocar",
        ["os.racer_hand_remove"] = "Remover",
        ["os.racer_hand_saved"] = "Mão guardada",
        ["os.racer_hand_saving"] = "A guardar a tua mão...",
        ["os.racer_hand_race"] = "Correr com esta mão",
        ["os.racer_hand_change"] = "Mudar de mão",
        ["os.racer_hand_enter_cup"] = "Entrar com esta mão",
        ["os.racer_hand_locked_cup"] = "Fixa para esta taça",
        ["os.racer_hand_empty"] = "A tua mão está vazia. Junta cartas do teu álbum.",
        ["os.racer_hand_slot_gold"] = "Posição de ouro",
        ["os.racer_hand_slot_silver"] = "Posição de prata {0}",
        ["os.racer_hand_in_hand"] = "Na mão",
        // Hand faults: one sentence per rule the server or the local check can refuse on
        ["os.racer_hand_fault_unknown"] = "Essa carta já não está no jogo. Escolhe outra.",
        ["os.racer_hand_fault_not_owned"] = "Não tens essa carta.",
        ["os.racer_hand_fault_wrong_band"] = "As cartas de ouro vão na posição de ouro. As cartas de prata vão nas posições de prata.",
        ["os.racer_hand_fault_duplicate"] = "Essa carta já está na tua mão.",
        ["os.racer_hand_fault_shape"] = "Uma mão tem uma carta de ouro e duas cartas de prata.",
        ["os.racer_hand_fault_failed"] = "A tua mão não foi guardada. Tenta outra vez.",
        // Inspect page
        ["os.racer_inspect_tab_card"] = "Carta",
        ["os.racer_inspect_tab_art"] = "Arte",
        ["os.racer_inspect_tab_info"] = "Info",
        ["os.racer_inspect_when"] = "Quando funciona",
        ["os.racer_inspect_how"] = "Como funciona",
        ["os.racer_inspect_exact"] = "Regras e números exatos",
        ["os.racer_inspect_story"] = "História e acabamento",
        ["os.racer_inspect_flip"] = "Virar a carta",
        ["os.racer_card_gold"] = "Carta de ouro",
        ["os.racer_card_silver"] = "Carta de prata",
        ["os.racer_card_automatic"] = "Automática",
        ["os.racer_card_once"] = "Uma vez por corrida",
        ["os.racer_card_passive"] = "Passiva",
        ["os.racer_card_rank"] = "N.º {0}",
        ["os.racer_card_level"] = "Nível {0}",
        ["os.racer_card_level_max"] = "Nível máximo",
        ["os.racer_card_effect_bonus"] = "Efeito +{0}%",
        ["os.racer_card_copy_of"] = "Cópia {0} de {1}",
        ["os.racer_card_equip_gold"] = "Pôr na posição de ouro",
        ["os.racer_card_equip_silver_1"] = "Pôr na posição de prata 1",
        ["os.racer_card_equip_silver_2"] = "Pôr na posição de prata 2",
        ["os.racer_card_unequip"] = "Tirar da mão",
        ["os.racer_card_locked"] = "Ainda não tens esta carta. Os pacotes de prémios podem dar-ta.",
        // In-race notice and the result line
        ["os.racer_notice_gold_used"] = "Usou uma carta de ouro",
        ["os.racer_replay_unavailable"] = "Esta corrida usou cartas mais recentes do que as que o teu plugin conhece. Atualiza o plugin para a veres. O resultado conta na mesma.",
        // Pack reveal and the starter grant
        ["os.racer_pack_prize_card"] = "Carta de corrida",
        ["os.racer_card_reveal_new"] = "Carta nova",
        ["os.racer_card_reveal_level_up"] = "Agora nível {0}",
        ["os.racer_cards_starter_title"] = "As tuas primeiras cartas",
        ["os.racer_cards_starter_body"] = "Recebeste três cartas de corrida para começar. Já estão na tua mão.",
        // Guard texts shared by every card of one operation kind. RaceCardGuards maps a card id to its index.
        ["os.racer_card_guard_1"] = "O teu Lumi cansa-se mais devagar enquanto corre. Os sprints cansam-no tanto como antes. Esta carta não devolve a energia que o teu Lumi já gastou.",
        ["os.racer_card_guard_2"] = "O teu Lumi corre de forma mais esperta. Escolhe melhores caminhos entre os outros corredores. Encontra mais formas de os passar. Tropeça menos vezes. Também se cansa um pouco menos. Se as duas cartas de prata fizerem isto, os dois efeitos somam-se, mas só até um limite.",
        ["os.racer_card_guard_3"] = "O teu Lumi começa os seus próprios sprints mais vezes. Cada sprint é tão rápido e tão longo como antes. Os Lumis só começam os seus próprios sprints na parte final da corrida. O teu Lumi continua a precisar de um pequeno descanso entre sprints.",
        ["os.racer_card_guard_4"] = "A velocidade máxima do teu Lumi fica um pouco maior durante toda a corrida. Também consegue manter um ritmo um pouco mais rápido antes de se cansar. As curvas, os outros corredores e o cansaço continuam a abrandá-lo. Por isso, o tempo final não melhora na mesma medida.",
        ["os.racer_card_guard_5"] = "Esta carta só ajuda na partida. O teu Lumi sai da partida um pouco mais cedo. Cada Lumi continua a esperar pelo menos 0,04 segundos antes de poder arrancar.",
        ["os.racer_card_guard_6"] = "O teu Lumi recupera alguma energia e consegue correr mais tempo antes de se cansar. A carta só funciona quando o teu Lumi já gastou pelo menos essa energia. Se o teu Lumi estiver exausto, deixa de estar. O valor é uma parte da energia total, não do que resta.",
        ["os.racer_card_guard_7"] = "A carta só funciona enquanto o teu Lumi está a tropeçar. Faz esse tropeção acabar mais cedo. Se o tropeção estiver quase no fim, acaba logo. Não impede o teu Lumi de voltar a tropeçar mais tarde.",
        ["os.racer_card_guard_8"] = "O teu Lumi corre mais depressa por um momento. Já tem de correr a pelo menos 75% da sua velocidade máxima. Depois da carta, o teu Lumi ainda tem de ter mais de 15% da sua energia. Não pode acontecer enquanto o teu Lumi está exausto, bloqueado, a tropeçar ou num sprint. Também não pode acontecer logo depois de um sprint. Se o teu Lumi estiver prestes a começar o seu sprint final, a carta espera. As curvas e os outros corredores ainda podem abrandar o teu Lumi. Depois, o teu Lumi volta à sua velocidade máxima normal.",
        ["os.racer_card_guard_9"] = "O teu Lumi faz um sprint por um momento. O caminho à frente tem de ser reto. Depois da carta, o teu Lumi ainda tem de ter mais de 15% da sua energia. Não pode acontecer enquanto o teu Lumi está exausto, bloqueado, a tropeçar ou num sprint. Também não pode acontecer logo depois de um sprint. Se o teu Lumi estiver prestes a começar o seu sprint final, a carta espera. O sprint é tão rápido como os sprints do próprio Lumi. Depois, o teu Lumi pode voltar logo a começar os seus próprios sprints.",
        // The 54 Core Set cards in catalogue order: name, face caption, availability, description, exact rule, story.
        ["os.racer_card_second_sunrise_name"] = "Segundo Amanhecer",
        ["os.racer_card_second_sunrise_short"] = "Recupera energia quando cansado",
        ["os.racer_card_second_sunrise_cond"] = "Quando o teu Lumi tem pouca energia.",
        ["os.racer_card_second_sunrise_desc"] = "Quando o teu Lumi tem pouca energia, recupera alguma energia. Espera até o teu Lumi estar muito baixo de energia.",
        ["os.racer_card_second_sunrise_exact"] = "Funciona uma vez por corrida. O teu Lumi recupera 5% da sua energia. Só quando o teu Lumi tem 24% da energia ou menos. Pode acontecer depois do primeiro quarto da corrida, até perto da meta.",
        ["os.racer_card_second_sunrise_story"] = "A manhã encontrou mais uma brasa.",

        ["os.racer_card_banked_embers_name"] = "Brasas Guardadas",
        ["os.racer_card_banked_embers_short"] = "Cansa-se menos",
        ["os.racer_card_banked_embers_cond"] = "Durante toda a corrida.",
        ["os.racer_card_banked_embers_desc"] = "O teu Lumi cansa-se um pouco mais devagar durante toda a corrida. Tem um pouco mais de energia perto da meta.",
        ["os.racer_card_banked_embers_exact"] = "Funciona durante toda a corrida. O teu Lumi cansa-se cerca de 2,4% menos.",
        ["os.racer_card_banked_embers_story"] = "Um pequeno calor pode ir longe.",

        ["os.racer_card_lantern_vigil_name"] = "Vigília da Lanterna",
        ["os.racer_card_lantern_vigil_short"] = "Mais esperto perto do fim",
        ["os.racer_card_lantern_vigil_cond"] = "Na parte final da corrida, até à meta.",
        ["os.racer_card_lantern_vigil_desc"] = "Na parte final da corrida, o teu Lumi corre de forma mais esperta. Encontra mais formas de passar os outros corredores. Também tropeça menos vezes.",
        ["os.racer_card_lantern_vigil_exact"] = "Funciona na parte final da corrida, até à meta. O teu Lumi corre de forma mais esperta. O efeito é médio.",
        ["os.racer_card_lantern_vigil_story"] = "Há sempre alguém que te deixa uma luz acesa.",

        ["os.racer_card_warm_footing_name"] = "Pés Quentes",
        ["os.racer_card_warm_footing_short"] = "Mais esperto com mau tempo",
        ["os.racer_card_warm_footing_cond"] = "Durante toda a corrida. Só com chuva, neve, vento forte, calor, estática ou poeira.",
        ["os.racer_card_warm_footing_desc"] = "Com mau tempo, o teu Lumi corre de forma mais esperta. Encontra mais formas de passar os outros corredores. Também tropeça menos vezes.",
        ["os.racer_card_warm_footing_exact"] = "Funciona durante toda a corrida. O teu Lumi corre de forma mais esperta. O efeito é pequeno. Só com chuva, neve, vento forte, calor, estática ou poeira.",
        ["os.racer_card_warm_footing_story"] = "Encontrou a única pedra que o inverno esqueceu.",

        ["os.racer_card_cinder_leap_name"] = "Salto de Cinza",
        ["os.racer_card_cinder_leap_short"] = "Sprint para perseguir o líder",
        ["os.racer_card_cinder_leap_cond"] = "Enquanto o teu Lumi está atrás do líder.",
        ["os.racer_card_cinder_leap_desc"] = "A meio da corrida, o teu Lumi faz um sprint para perseguir o líder. O caminho à frente tem de ser reto.",
        ["os.racer_card_cinder_leap_exact"] = "Funciona uma vez por corrida. O teu Lumi faz um sprint de 0,55 segundos. Isto gasta 1% da sua energia. O líder tem de estar pelo menos 1,2 corpos à frente. Pode acontecer a meio da corrida.",
        ["os.racer_card_cinder_leap_story"] = "Por um batimento, até as cinzas voaram.",

        ["os.racer_card_slow_burn_name"] = "Fogo Lento",
        ["os.racer_card_slow_burn_short"] = "Cansa-se menos a subir",
        ["os.racer_card_slow_burn_cond"] = "Enquanto sobe.",
        ["os.racer_card_slow_burn_desc"] = "Enquanto sobe, o teu Lumi cansa-se mais devagar. Fica com mais energia para o resto da corrida.",
        ["os.racer_card_slow_burn_exact"] = "Funciona sempre que o teu Lumi corre a subir. O teu Lumi cansa-se cerca de 7% menos.",
        ["os.racer_card_slow_burn_story"] = "A colina foi paciente. A brasa também.",

        ["os.racer_card_sheltered_spark_name"] = "Faísca Abrigada",
        ["os.racer_card_sheltered_spark_short"] = "Mais sprints com mau tempo",
        ["os.racer_card_sheltered_spark_cond"] = "Durante toda a corrida. Só com chuva, neve, vento forte, calor, estática ou poeira.",
        ["os.racer_card_sheltered_spark_desc"] = "Com mau tempo, o teu Lumi começa os seus próprios sprints mais vezes.",
        ["os.racer_card_sheltered_spark_exact"] = "Funciona durante toda a corrida. O teu Lumi começa os seus próprios sprints 11% mais vezes. Só com chuva, neve, vento forte, calor, estática ou poeira.",
        ["os.racer_card_sheltered_spark_story"] = "A chuva podia esperar lá fora.",

        ["os.racer_card_home_by_firelight_name"] = "Lar à Luz do Fogo",
        ["os.racer_card_home_by_firelight_short"] = "Velocidade máxima maior",
        ["os.racer_card_home_by_firelight_cond"] = "Durante toda a corrida.",
        ["os.racer_card_home_by_firelight_desc"] = "O teu Lumi corre um pouquinho mais depressa durante toda a corrida.",
        ["os.racer_card_home_by_firelight_exact"] = "Funciona durante toda a corrida. A velocidade máxima do teu Lumi é um pouco maior. Numa corrida longa, isso pode pôr o teu Lumi até cerca de 0,3 corpos mais à frente.",
        ["os.racer_card_home_by_firelight_story"] = "Os últimos passos cheiravam a casa.",

        ["os.racer_card_last_light_name"] = "A Última Luz",
        ["os.racer_card_last_light_short"] = "Sprint para perseguir o líder",
        ["os.racer_card_last_light_cond"] = "Enquanto o teu Lumi está atrás do líder.",
        ["os.racer_card_last_light_desc"] = "Perto do fim da corrida, o teu Lumi faz um sprint para perseguir o líder. O caminho à frente tem de ser reto.",
        ["os.racer_card_last_light_exact"] = "Funciona uma vez por corrida. O teu Lumi faz um sprint de 0,65 segundos. Isto gasta 1% da sua energia. O líder tem de estar pelo menos 0,5 corpos à frente. Pode acontecer perto do fim da corrida.",
        ["os.racer_card_last_light_story"] = "Guardou um pensamento brilhante para o fim.",

        ["os.racer_card_storm_whispers_name"] = "Sussurro da Tempestade",
        ["os.racer_card_storm_whispers_short"] = "Mais esperto",
        ["os.racer_card_storm_whispers_cond"] = "Durante toda a corrida.",
        ["os.racer_card_storm_whispers_desc"] = "O teu Lumi corre de forma mais esperta durante toda a corrida. Encontra mais formas de passar os outros corredores. Também tropeça menos vezes.",
        ["os.racer_card_storm_whispers_exact"] = "Funciona durante toda a corrida. O teu Lumi corre de forma mais esperta. O efeito é pequeno.",
        ["os.racer_card_storm_whispers_story"] = "O estalido mais baixinho avisou primeiro.",

        ["os.racer_card_borrowed_thunder_name"] = "Trovão Emprestado",
        ["os.racer_card_borrowed_thunder_short"] = "Sprint numa reta",
        ["os.racer_card_borrowed_thunder_cond"] = "Numa reta.",
        ["os.racer_card_borrowed_thunder_desc"] = "A meio da corrida, o teu Lumi faz um sprint numa reta.",
        ["os.racer_card_borrowed_thunder_exact"] = "Funciona uma vez por corrida. O teu Lumi faz um sprint de 0,45 segundos. Isto gasta 1% da sua energia. Pode acontecer a meio da corrida.",
        ["os.racer_card_borrowed_thunder_story"] = "Uma nuvem pequena respondeu bem alto.",

        ["os.racer_card_paper_promises_name"] = "Promessas de Papel",
        ["os.racer_card_paper_promises_short"] = "Arranca mais cedo",
        ["os.racer_card_paper_promises_cond"] = "Na partida.",
        ["os.racer_card_paper_promises_desc"] = "O teu Lumi sai da partida mais cedo.",
        ["os.racer_card_paper_promises_exact"] = "Funciona na partida da corrida. A espera do teu Lumi na partida é 4% mais curta. Cada Lumi continua a esperar pelo menos 0,04 segundos.",
        ["os.racer_card_paper_promises_story"] = "Manteve a forma quando o vento mudou.",

        ["os.racer_card_blink_of_brilliance_name"] = "Lampejo Brilhante",
        ["os.racer_card_blink_of_brilliance_short"] = "Acelera quando deixa de estar bloqueado",
        ["os.racer_card_blink_of_brilliance_cond"] = "Logo depois de o teu Lumi deixar de estar bloqueado, enquanto ainda há um corredor à frente.",
        ["os.racer_card_blink_of_brilliance_desc"] = "Logo depois de o teu Lumi deixar de estar bloqueado por outro corredor, corre mais depressa por um momento. Isto pode acontecer durante a maior parte da corrida.",
        ["os.racer_card_blink_of_brilliance_exact"] = "Funciona uma vez por corrida, desde pouco depois da partida até perto da meta. A velocidade máxima do teu Lumi é 8% maior durante 1,4 segundos. Isto gasta 1% da sua energia. Só no primeiro segundo depois de o teu Lumi deixar de estar bloqueado. Tem de haver um corredor à frente.",
        ["os.racer_card_blink_of_brilliance_story"] = "A resposta esteve ali por um momento.",

        ["os.racer_card_quiet_charge_name"] = "Uma Carga Silenciosa",
        ["os.racer_card_quiet_charge_short"] = "Mais sprints",
        ["os.racer_card_quiet_charge_cond"] = "Durante toda a corrida.",
        ["os.racer_card_quiet_charge_desc"] = "O teu Lumi começa os seus próprios sprints mais vezes durante toda a corrida.",
        ["os.racer_card_quiet_charge_exact"] = "Funciona durante toda a corrida. O teu Lumi começa os seus próprios sprints 7,5% mais vezes.",
        ["os.racer_card_quiet_charge_story"] = "Não havia pressa em gastar a faísca.",

        ["os.racer_card_copper_company_name"] = "Companhia de Cobre",
        ["os.racer_card_copper_company_short"] = "Cansa-se menos atrás de outro",
        ["os.racer_card_copper_company_cond"] = "Enquanto corre atrás de outro corredor, perto dele.",
        ["os.racer_card_copper_company_desc"] = "Enquanto o teu Lumi corre atrás de outro corredor, perto dele, cansa-se mais devagar. A ajuda acaba quando deixa de estar perto dele.",
        ["os.racer_card_copper_company_exact"] = "Funciona sempre que o teu Lumi corre atrás de outro corredor, perto dele. O teu Lumi cansa-se cerca de 9,1% menos.",
        ["os.racer_card_copper_company_story"] = "O caminho soava mais amigo com companhia.",

        ["os.racer_card_after_the_flash_name"] = "Depois do Clarão",
        ["os.racer_card_after_the_flash_short"] = "Mais esperto após tropeçar com mau tempo",
        ["os.racer_card_after_the_flash_cond"] = "Logo depois de um tropeção. Só com chuva, neve, vento forte, calor, estática ou poeira.",
        ["os.racer_card_after_the_flash_desc"] = "Com mau tempo, logo depois de um tropeção, o teu Lumi corre de forma mais esperta durante pouco tempo. Encontra mais formas de passar os outros corredores. Tem menos probabilidade de voltar a tropeçar.",
        ["os.racer_card_after_the_flash_exact"] = "Funciona nos 2 segundos depois do fim de cada tropeção. O teu Lumi corre de forma mais esperta. O efeito é grande. Só com chuva, neve, vento forte, calor, estática ou poeira.",
        ["os.racer_card_after_the_flash_story"] = "As poças lembravam-se. Ele continuou.",

        ["os.racer_card_bright_idea_name"] = "Ideia Brilhante",
        ["os.racer_card_bright_idea_short"] = "Mais esperto nas curvas",
        ["os.racer_card_bright_idea_cond"] = "Numa curva.",
        ["os.racer_card_bright_idea_desc"] = "Nas curvas, o teu Lumi corre de forma mais esperta. Encontra mais formas de passar os outros corredores. Também tropeça menos vezes.",
        ["os.racer_card_bright_idea_exact"] = "Funciona sempre que o teu Lumi corre numa curva. O teu Lumi corre de forma mais esperta. O efeito é médio.",
        ["os.racer_card_bright_idea_story"] = "Viu um caminho entre as gotas de chuva.",

        ["os.racer_card_catch_the_spark_name"] = "Apanha a Faísca",
        ["os.racer_card_catch_the_spark_short"] = "Sprint após tropeçar",
        ["os.racer_card_catch_the_spark_cond"] = "Logo depois de um tropeção.",
        ["os.racer_card_catch_the_spark_desc"] = "Logo depois de um tropeção, o teu Lumi faz um sprint para voltar a arrancar. O caminho à frente tem de ser reto.",
        ["os.racer_card_catch_the_spark_exact"] = "Funciona uma vez por corrida. O teu Lumi faz um sprint de 0,5 segundos. Isto gasta 1% da sua energia. Só nos 2 segundos depois do fim de um tropeção. Pode acontecer desde pouco depois da partida até perto da meta.",
        ["os.racer_card_catch_the_spark_story"] = "Ainda não era tarde para reparar.",

        ["os.racer_card_featherlight_steps_name"] = "Passos de Pluma",
        ["os.racer_card_featherlight_steps_short"] = "Cansa-se menos no início",
        ["os.racer_card_featherlight_steps_cond"] = "No primeiro terço da corrida.",
        ["os.racer_card_featherlight_steps_desc"] = "No primeiro terço da corrida, o teu Lumi cansa-se mais devagar. Fica com mais energia para mais tarde na corrida.",
        ["os.racer_card_featherlight_steps_exact"] = "Funciona no primeiro terço da corrida. O teu Lumi cansa-se cerca de 3,8% menos.",
        ["os.racer_card_featherlight_steps_story"] = "A relva mal deu por ele passar.",

        ["os.racer_card_leeward_path_name"] = "O Caminho Abrigado",
        ["os.racer_card_leeward_path_short"] = "Cansa-se menos com vento",
        ["os.racer_card_leeward_path_cond"] = "Durante toda a corrida. Só com vento forte.",
        ["os.racer_card_leeward_path_desc"] = "Com vento forte, o teu Lumi cansa-se mais devagar durante toda a corrida. Tem mais energia perto da meta.",
        ["os.racer_card_leeward_path_exact"] = "Funciona durante toda a corrida. O teu Lumi cansa-se cerca de 4,8% menos. Só com vento forte.",
        ["os.racer_card_leeward_path_story"] = "A colina guardou um pouco de sossego deste lado.",

        ["os.racer_card_thread_the_gust_name"] = "Por Entre a Rajada",
        ["os.racer_card_thread_the_gust_short"] = "Acelera quando deixa de estar bloqueado",
        ["os.racer_card_thread_the_gust_cond"] = "Logo depois de o teu Lumi deixar de estar bloqueado, enquanto ainda há um corredor à frente.",
        ["os.racer_card_thread_the_gust_desc"] = "A meio da corrida, logo depois de o teu Lumi deixar de estar bloqueado por outro corredor, corre mais depressa por um momento.",
        ["os.racer_card_thread_the_gust_exact"] = "Funciona uma vez por corrida, a meio da corrida. A velocidade máxima do teu Lumi é 9% maior durante 1,5 segundos. Isto gasta 1% da sua energia. Só no primeiro segundo depois de o teu Lumi deixar de estar bloqueado. Tem de haver um corredor à frente.",
        ["os.racer_card_thread_the_gust_story"] = "A brisa deixou espaço à justa.",

        ["os.racer_card_lift_together_name"] = "Um Impulso a Dois",
        ["os.racer_card_lift_together_short"] = "Recupera energia atrás de outro",
        ["os.racer_card_lift_together_cond"] = "Enquanto corre mesmo atrás de outro corredor.",
        ["os.racer_card_lift_together_desc"] = "A meio da corrida, o teu Lumi recupera alguma energia. Tem de correr mesmo atrás de outro corredor, não ao lado.",
        ["os.racer_card_lift_together_exact"] = "Funciona uma vez por corrida. O teu Lumi recupera 4% da sua energia. Só enquanto o teu Lumi corre mesmo atrás de outro corredor. Pode acontecer a meio da corrida.",
        ["os.racer_card_lift_together_story"] = "A coragem viajou na mesma brisa.",

        ["os.racer_card_ribbon_weather_name"] = "Tempo de Fitas",
        ["os.racer_card_ribbon_weather_short"] = "Mais esperto com céu limpo",
        ["os.racer_card_ribbon_weather_cond"] = "Durante toda a corrida. Só com céu limpo.",
        ["os.racer_card_ribbon_weather_desc"] = "Com céu limpo, o teu Lumi corre de forma mais esperta durante toda a corrida. Encontra mais formas de passar os outros corredores. Também tropeça menos vezes.",
        ["os.racer_card_ribbon_weather_exact"] = "Funciona durante toda a corrida. O teu Lumi corre de forma mais esperta. O efeito é pequeno. Só com céu limpo.",
        ["os.racer_card_ribbon_weather_story"] = "Um só esvoaçar foi todo o aviso de que precisou.",

        ["os.racer_card_long_glide_name"] = "O Longo Planar",
        ["os.racer_card_long_glide_short"] = "Cansa-se menos com céu limpo",
        ["os.racer_card_long_glide_cond"] = "Durante toda a corrida. Só com céu limpo.",
        ["os.racer_card_long_glide_desc"] = "Com céu limpo, o teu Lumi cansa-se mais devagar durante toda a corrida. Tem mais energia perto da meta.",
        ["os.racer_card_long_glide_exact"] = "Funciona durante toda a corrida. O teu Lumi cansa-se cerca de 2,7% menos. Só com céu limpo.",
        ["os.racer_card_long_glide_story"] = "Houve tempo para deixar o ar fazer a sua parte.",

        ["os.racer_card_pocket_of_calm_name"] = "Recanto de Calma",
        ["os.racer_card_pocket_of_calm_short"] = "Mais esperto em grupo",
        ["os.racer_card_pocket_of_calm_cond"] = "Com outros corredores por perto.",
        ["os.racer_card_pocket_of_calm_desc"] = "Quando há pelo menos 2 outros corredores por perto, o teu Lumi corre de forma mais esperta. Encontra mais formas de os passar.",
        ["os.racer_card_pocket_of_calm_exact"] = "Funciona sempre que há pelo menos 2 outros corredores por perto. O teu Lumi corre de forma mais esperta. O efeito é médio.",
        ["os.racer_card_pocket_of_calm_story"] = "Abriu espaço para uma respiração calma.",

        ["os.racer_card_borrowed_wings_name"] = "Asas Emprestadas",
        ["os.racer_card_borrowed_wings_short"] = "Tropeção mais curto no fim",
        ["os.racer_card_borrowed_wings_cond"] = "Enquanto o teu Lumi está a tropeçar.",
        ["os.racer_card_borrowed_wings_desc"] = "Na segunda metade da corrida, esta carta faz um tropeção acabar mais cedo.",
        ["os.racer_card_borrowed_wings_exact"] = "Funciona uma vez por corrida. O tropeção do teu Lumi acaba até 0,35 segundos mais cedo. Só enquanto o teu Lumi está a tropeçar. Pode acontecer na segunda metade da corrida.",
        ["os.racer_card_borrowed_wings_story"] = "A próxima respiração já vinha a caminho.",

        ["os.racer_card_home_on_the_breeze_name"] = "Lar na Brisa",
        ["os.racer_card_home_on_the_breeze_short"] = "Mais rápido com mau tempo",
        ["os.racer_card_home_on_the_breeze_cond"] = "Durante toda a corrida. Só com chuva, neve, vento forte, calor, estática ou poeira.",
        ["os.racer_card_home_on_the_breeze_desc"] = "Com mau tempo, o teu Lumi corre um pouquinho mais depressa durante toda a corrida.",
        ["os.racer_card_home_on_the_breeze_exact"] = "Funciona durante toda a corrida. A velocidade máxima do teu Lumi é um pouco maior. Numa corrida longa, isso pode pôr o teu Lumi até cerca de 0,43 corpos mais à frente. Só com chuva, neve, vento forte, calor, estática ou poeira.",
        ["os.racer_card_home_on_the_breeze_story"] = "Conhecia o jardim pela forma como respirava.",

        ["os.racer_card_quiet_footing_name"] = "Pés Serenos",
        ["os.racer_card_quiet_footing_short"] = "Mais esperto em curvas fechadas",
        ["os.racer_card_quiet_footing_cond"] = "Numa curva fechada.",
        ["os.racer_card_quiet_footing_desc"] = "Nas curvas fechadas, o teu Lumi corre de forma mais esperta. Encontra mais formas de passar os outros corredores. Também tropeça menos vezes.",
        ["os.racer_card_quiet_footing_exact"] = "Funciona sempre que o teu Lumi corre numa curva fechada. O teu Lumi corre de forma mais esperta. O efeito é grande.",
        ["os.racer_card_quiet_footing_story"] = "A geada abriu espaço para pés cuidadosos.",

        ["os.racer_card_winter_reprieve_name"] = "Trégua do Inverno",
        ["os.racer_card_winter_reprieve_short"] = "Recupera energia com chuva ou neve",
        ["os.racer_card_winter_reprieve_cond"] = "Quando o teu Lumi tem pouca energia. Só com chuva ou neve.",
        ["os.racer_card_winter_reprieve_desc"] = "Com chuva ou neve, quando o teu Lumi tem pouca energia, recupera alguma energia. Pode funcionar cedo na corrida.",
        ["os.racer_card_winter_reprieve_exact"] = "Funciona uma vez por corrida. O teu Lumi recupera 5,5% da sua energia. Só quando o teu Lumi tem 30% da energia ou menos. Só com chuva ou neve. Pode acontecer depois do primeiro quarto da corrida, até perto da meta.",
        ["os.racer_card_winter_reprieve_story"] = "O frio parou por um momento bondoso.",

        ["os.racer_card_clear_reflection_name"] = "Um Reflexo Claro",
        ["os.racer_card_clear_reflection_short"] = "Arranca mais cedo com céu limpo",
        ["os.racer_card_clear_reflection_cond"] = "Na partida. Só com céu limpo.",
        ["os.racer_card_clear_reflection_desc"] = "Com céu limpo, o teu Lumi sai da partida mais cedo.",
        ["os.racer_card_clear_reflection_exact"] = "Funciona na partida da corrida. A espera do teu Lumi na partida é 5% mais curta. Cada Lumi continua a esperar pelo menos 0,04 segundos. Só com céu limpo.",
        ["os.racer_card_clear_reflection_story"] = "Ouviu com os olhos.",

        ["os.racer_card_under_the_snow_name"] = "Debaixo da Neve",
        ["os.racer_card_under_the_snow_short"] = "Cansa-se menos com neve",
        ["os.racer_card_under_the_snow_cond"] = "Durante toda a corrida. Só com neve.",
        ["os.racer_card_under_the_snow_desc"] = "Com neve, o teu Lumi cansa-se mais devagar durante toda a corrida. Tem mais energia perto da meta.",
        ["os.racer_card_under_the_snow_exact"] = "Funciona durante toda a corrida. O teu Lumi cansa-se cerca de 4,8% menos. Só com neve.",
        ["os.racer_card_under_the_snow_story"] = "O inverno manteve quente o seu quarto mais pequeno.",

        ["os.racer_card_still_as_starlight_name"] = "Calmo como as Estrelas",
        ["os.racer_card_still_as_starlight_short"] = "Mais esperto no fim com céu limpo",
        ["os.racer_card_still_as_starlight_cond"] = "Na parte final da corrida, até à meta. Só com céu limpo.",
        ["os.racer_card_still_as_starlight_desc"] = "Com céu limpo, o teu Lumi corre de forma mais esperta na parte final da corrida. Encontra mais formas de passar os outros corredores. Também tropeça menos vezes.",
        ["os.racer_card_still_as_starlight_exact"] = "Funciona na parte final da corrida, até à meta. O teu Lumi corre de forma mais esperta. O efeito é médio. Só com céu limpo.",
        ["os.racer_card_still_as_starlight_story"] = "Até as estrelas pareceram baixar a voz.",

        ["os.racer_card_one_perfect_step_name"] = "Um Passo Perfeito",
        ["os.racer_card_one_perfect_step_short"] = "Acelera depois de uma curva",
        ["os.racer_card_one_perfect_step_cond"] = "Logo depois de uma curva.",
        ["os.racer_card_one_perfect_step_desc"] = "Logo depois de uma curva, o teu Lumi corre mais depressa por um momento.",
        ["os.racer_card_one_perfect_step_exact"] = "Funciona uma vez por corrida. A velocidade máxima do teu Lumi é 8,5% maior durante 1,4 segundos. Isto gasta 1% da sua energia. Só no primeiro segundo depois de uma curva. Pode acontecer desde pouco depois da partida até perto da meta.",
        ["os.racer_card_one_perfect_step_story"] = "Confiou no pedacinho de chão limpo.",

        ["os.racer_card_ring_the_frost_name"] = "Sino de Geada",
        ["os.racer_card_ring_the_frost_short"] = "Tropeção mais curto",
        ["os.racer_card_ring_the_frost_cond"] = "Enquanto o teu Lumi está a tropeçar.",
        ["os.racer_card_ring_the_frost_desc"] = "Em quase qualquer momento da corrida, esta carta faz um tropeção acabar mais cedo.",
        ["os.racer_card_ring_the_frost_exact"] = "Funciona uma vez por corrida. O tropeção do teu Lumi acaba até 0,3 segundos mais cedo. Só enquanto o teu Lumi está a tropeçar. Pode acontecer em quase qualquer momento da corrida.",
        ["os.racer_card_ring_the_frost_story"] = "Uma nota clara sacudiu a preocupação.",

        ["os.racer_card_soft_landing_name"] = "Aterragem Suave",
        ["os.racer_card_soft_landing_short"] = "Mais esperto a descer",
        ["os.racer_card_soft_landing_cond"] = "Enquanto desce.",
        ["os.racer_card_soft_landing_desc"] = "Enquanto desce, o teu Lumi corre de forma mais esperta. Encontra mais formas de passar os outros corredores. Também tropeça menos vezes.",
        ["os.racer_card_soft_landing_exact"] = "Funciona sempre que o teu Lumi corre a descer. O teu Lumi corre de forma mais esperta. O efeito é grande.",
        ["os.racer_card_soft_landing_story"] = "A neve tinha guardado aquele lugar.",

        ["os.racer_card_thaw_comes_slowly_name"] = "O Degelo Vem Devagar",
        ["os.racer_card_thaw_comes_slowly_short"] = "Cansa-se menos perto do fim",
        ["os.racer_card_thaw_comes_slowly_cond"] = "Na parte final da corrida, até à meta.",
        ["os.racer_card_thaw_comes_slowly_desc"] = "Na parte final da corrida, o teu Lumi cansa-se mais devagar. Fica com mais energia para a meta.",
        ["os.racer_card_thaw_comes_slowly_exact"] = "Funciona na parte final da corrida, até à meta. O teu Lumi cansa-se cerca de 4,8% menos.",
        ["os.racer_card_thaw_comes_slowly_story"] = "Um pouco de calor bastou para começar.",

        ["os.racer_card_follow_the_flow_name"] = "Segue a Corrente",
        ["os.racer_card_follow_the_flow_short"] = "Cansa-se menos nas retas",
        ["os.racer_card_follow_the_flow_cond"] = "Numa reta.",
        ["os.racer_card_follow_the_flow_desc"] = "Nas retas, o teu Lumi cansa-se mais devagar. Fica com mais energia para o resto da corrida.",
        ["os.racer_card_follow_the_flow_exact"] = "Funciona sempre que o teu Lumi corre numa reta. O teu Lumi cansa-se cerca de 4,3% menos.",
        ["os.racer_card_follow_the_flow_story"] = "A corrente conhecia um caminho mais suave.",

        ["os.racer_card_puddle_lessons_name"] = "Lições da Poça",
        ["os.racer_card_puddle_lessons_short"] = "Mais esperto após um tropeção",
        ["os.racer_card_puddle_lessons_cond"] = "Logo depois de um tropeção.",
        ["os.racer_card_puddle_lessons_desc"] = "Logo depois de um tropeção, o teu Lumi corre de forma mais esperta durante pouco tempo. Encontra mais formas de passar os outros corredores. Tem menos probabilidade de voltar a tropeçar.",
        ["os.racer_card_puddle_lessons_exact"] = "Funciona nos 2 segundos depois do fim de cada tropeção. O teu Lumi corre de forma mais esperta. O efeito é médio.",
        ["os.racer_card_puddle_lessons_story"] = "Cada poça tinha algo novo para dizer.",

        ["os.racer_card_turning_tide_name"] = "Maré a Virar",
        ["os.racer_card_turning_tide_short"] = "Recupera energia quando cansado",
        ["os.racer_card_turning_tide_cond"] = "Quando o teu Lumi tem pouca energia.",
        ["os.racer_card_turning_tide_desc"] = "Desde mais ou menos a meio, quando o teu Lumi tem pouca energia, recupera alguma energia.",
        ["os.racer_card_turning_tide_exact"] = "Funciona uma vez por corrida. O teu Lumi recupera 4% da sua energia. Só quando o teu Lumi tem 35% da energia ou menos. Pode acontecer desde mais ou menos a meio até perto da meta.",
        ["os.racer_card_turning_tide_story"] = "A água ofereceu outra passagem.",

        ["os.racer_card_pearls_of_patience_name"] = "Pérolas de Paciência",
        ["os.racer_card_pearls_of_patience_short"] = "Mais sprints na segunda metade",
        ["os.racer_card_pearls_of_patience_cond"] = "Na segunda metade da corrida.",
        ["os.racer_card_pearls_of_patience_desc"] = "Na segunda metade da corrida, o teu Lumi começa os seus próprios sprints mais vezes.",
        ["os.racer_card_pearls_of_patience_exact"] = "Funciona na segunda metade da corrida. O teu Lumi começa os seus próprios sprints 13% mais vezes.",
        ["os.racer_card_pearls_of_patience_story"] = "Deixou as bolhas subir ao seu ritmo.",

        ["os.racer_card_over_the_water_name"] = "Sobre a Água",
        ["os.racer_card_over_the_water_short"] = "Sprint para perseguir o líder",
        ["os.racer_card_over_the_water_cond"] = "Enquanto o teu Lumi está atrás do líder.",
        ["os.racer_card_over_the_water_desc"] = "Depois do primeiro terço da corrida, o teu Lumi faz um sprint para perseguir o líder. O caminho à frente tem de ser reto.",
        ["os.racer_card_over_the_water_exact"] = "Funciona uma vez por corrida. O teu Lumi faz um sprint de 0,65 segundos. Isto gasta 1% da sua energia. O líder tem de estar pelo menos 0,8 corpos à frente. Pode acontecer depois do primeiro terço da corrida, até perto da meta.",
        ["os.racer_card_over_the_water_story"] = "Havia pedra à justa para ser corajoso.",

        ["os.racer_card_rain_on_glass_name"] = "Chuva no Vidro",
        ["os.racer_card_rain_on_glass_short"] = "Mais esperto em curvas à chuva",
        ["os.racer_card_rain_on_glass_cond"] = "Numa curva. Só com chuva.",
        ["os.racer_card_rain_on_glass_desc"] = "Nas curvas com chuva, o teu Lumi corre de forma mais esperta. Encontra mais formas de passar os outros corredores. Também tropeça menos vezes.",
        ["os.racer_card_rain_on_glass_exact"] = "Funciona sempre que o teu Lumi corre numa curva. O teu Lumi corre de forma mais esperta. O efeito é grande. Só com chuva.",
        ["os.racer_card_rain_on_glass_story"] = "Contou as pausas entre as gotas.",

        ["os.racer_card_ripple_returned_name"] = "Uma Onda que Voltou",
        ["os.racer_card_ripple_returned_short"] = "Recupera energia após tropeçar",
        ["os.racer_card_ripple_returned_cond"] = "Logo depois de um tropeção.",
        ["os.racer_card_ripple_returned_desc"] = "Logo depois de um tropeção, o teu Lumi recupera alguma energia.",
        ["os.racer_card_ripple_returned_exact"] = "Funciona uma vez por corrida. O teu Lumi recupera 5% da sua energia. Só nos 2 segundos depois do fim de um tropeção. Pode acontecer desde pouco depois da partida até perto da meta.",
        ["os.racer_card_ripple_returned_story"] = "A segunda onda encontrou-o pronto.",

        ["os.racer_card_low_tide_friends_name"] = "Amigos da Maré Baixa",
        ["os.racer_card_low_tide_friends_short"] = "Mais esperto atrás de outro",
        ["os.racer_card_low_tide_friends_cond"] = "Enquanto corre atrás de outro corredor, perto dele.",
        ["os.racer_card_low_tide_friends_desc"] = "Enquanto o teu Lumi vai atrás de outro corredor, perto dele, corre de forma mais esperta. Encontra mais formas de passar os outros corredores. Também tropeça menos vezes.",
        ["os.racer_card_low_tide_friends_exact"] = "Funciona sempre que o teu Lumi corre atrás de outro corredor, perto dele. O teu Lumi corre de forma mais esperta. O efeito é grande.",
        ["os.racer_card_low_tide_friends_story"] = "Algumas viagens são melhores a passo de conversa.",

        ["os.racer_card_smooth_pebble_promise_name"] = "Promessa do Seixo Liso",
        ["os.racer_card_smooth_pebble_promise_short"] = "Mais rápido com céu limpo",
        ["os.racer_card_smooth_pebble_promise_cond"] = "Durante toda a corrida. Só com céu limpo.",
        ["os.racer_card_smooth_pebble_promise_desc"] = "Com céu limpo, o teu Lumi corre um pouquinho mais depressa durante toda a corrida.",
        ["os.racer_card_smooth_pebble_promise_exact"] = "Funciona durante toda a corrida. A velocidade máxima do teu Lumi é um pouco maior. Numa corrida longa, isso pode pôr o teu Lumi até cerca de 0,35 corpos mais à frente. Só com céu limpo.",
        ["os.racer_card_smooth_pebble_promise_story"] = "Trouxe a coisinha até casa.",

        ["os.racer_card_stand_together_name"] = "Lado a Lado",
        ["os.racer_card_stand_together_short"] = "Recupera energia em grupo",
        ["os.racer_card_stand_together_cond"] = "Com outros corredores por perto.",
        ["os.racer_card_stand_together_desc"] = "A meio da corrida, o teu Lumi recupera alguma energia. Tem de haver pelo menos 2 outros corredores por perto.",
        ["os.racer_card_stand_together_exact"] = "Funciona uma vez por corrida. O teu Lumi recupera 4% da sua energia. Só quando há pelo menos 2 outros corredores por perto. Pode acontecer a meio da corrida.",
        ["os.racer_card_stand_together_story"] = "Ficou um pouco mais alto ao lado de um amigo.",

        ["os.racer_card_roots_remember_name"] = "As Raízes Lembram",
        ["os.racer_card_roots_remember_short"] = "Mais esperto a subir",
        ["os.racer_card_roots_remember_cond"] = "Enquanto sobe.",
        ["os.racer_card_roots_remember_desc"] = "Enquanto sobe, o teu Lumi corre de forma mais esperta. Encontra mais formas de passar os outros corredores. Também tropeça menos vezes.",
        ["os.racer_card_roots_remember_exact"] = "Funciona sempre que o teu Lumi corre a subir. O teu Lumi corre de forma mais esperta. O efeito é grande.",
        ["os.racer_card_roots_remember_story"] = "O caminho mais antigo ainda sabia o seu nome.",

        ["os.racer_card_patient_path_name"] = "O Caminho Paciente",
        ["os.racer_card_patient_path_short"] = "Cansa-se menos no início com céu limpo",
        ["os.racer_card_patient_path_cond"] = "Na primeira metade da corrida. Só com céu limpo.",
        ["os.racer_card_patient_path_desc"] = "Com céu limpo, o teu Lumi cansa-se mais devagar na primeira metade da corrida. Tem mais energia para mais tarde.",
        ["os.racer_card_patient_path_exact"] = "Funciona na primeira metade da corrida. O teu Lumi cansa-se cerca de 5,2% menos. Só com céu limpo.",
        ["os.racer_card_patient_path_story"] = "Os passos pequenos ainda o levavam a algum lado.",

        ["os.racer_card_mossbound_shelter_name"] = "Abrigo de Musgo",
        ["os.racer_card_mossbound_shelter_short"] = "Cansa-se menos com poeira",
        ["os.racer_card_mossbound_shelter_cond"] = "Durante toda a corrida. Só com poeira.",
        ["os.racer_card_mossbound_shelter_desc"] = "Com poeira, o teu Lumi cansa-se mais devagar durante toda a corrida. Tem mais energia perto da meta.",
        ["os.racer_card_mossbound_shelter_exact"] = "Funciona durante toda a corrida. O teu Lumi cansa-se cerca de 4,8% menos. Só com poeira.",
        ["os.racer_card_mossbound_shelter_story"] = "A pedra tinha guardado um canto seco só para isto.",

        ["os.racer_card_little_ballast_name"] = "Um Pouco de Lastro",
        ["os.racer_card_little_ballast_short"] = "Arranca mais cedo com mau tempo",
        ["os.racer_card_little_ballast_cond"] = "Na partida. Só com chuva, neve, vento forte, calor, estática ou poeira.",
        ["os.racer_card_little_ballast_desc"] = "Com mau tempo, o teu Lumi sai da partida mais cedo.",
        ["os.racer_card_little_ballast_exact"] = "Funciona na partida da corrida. A espera do teu Lumi na partida é 5,5% mais curta. Cada Lumi continua a esperar pelo menos 0,04 segundos. Só com chuva, neve, vento forte, calor, estática ou poeira.",
        ["os.racer_card_little_ballast_story"] = "Um peso pequeno ajudou o mundo a parecer firme.",

        ["os.racer_card_hold_the_hill_name"] = "Segura a Colina",
        ["os.racer_card_hold_the_hill_short"] = "Acelera depois de uma subida",
        ["os.racer_card_hold_the_hill_cond"] = "Logo depois do fim de uma subida.",
        ["os.racer_card_hold_the_hill_desc"] = "Logo depois do fim de uma subida, o teu Lumi corre mais depressa por um momento.",
        ["os.racer_card_hold_the_hill_exact"] = "Funciona uma vez por corrida. A velocidade máxima do teu Lumi é 10% maior durante 1,6 segundos. Isto gasta 1% da sua energia. Só no primeiro segundo depois do fim de uma subida. Pode acontecer desde pouco depois da partida até perto da meta.",
        ["os.racer_card_hold_the_hill_story"] = "A encosta perguntou. Ele respondeu com mais um empurrão.",

        ["os.racer_card_kindly_ground_name"] = "Chão Bondoso",
        ["os.racer_card_kindly_ground_short"] = "Cansa-se menos após tropeçar",
        ["os.racer_card_kindly_ground_cond"] = "Logo depois de um tropeção.",
        ["os.racer_card_kindly_ground_desc"] = "Logo depois de um tropeção, o teu Lumi cansa-se mais devagar durante pouco tempo.",
        ["os.racer_card_kindly_ground_exact"] = "Funciona nos 2 segundos depois do fim de cada tropeção. O teu Lumi cansa-se cerca de 9,1% menos.",
        ["os.racer_card_kindly_ground_story"] = "A terra não se importou com um momento de descanso.",

        ["os.racer_card_mountain_answers_name"] = "A Montanha Responde",
        ["os.racer_card_mountain_answers_short"] = "Tropeção mais curto no início",
        ["os.racer_card_mountain_answers_cond"] = "Enquanto o teu Lumi está a tropeçar.",
        ["os.racer_card_mountain_answers_desc"] = "Na primeira metade da corrida, esta carta faz um tropeção acabar mais cedo.",
        ["os.racer_card_mountain_answers_exact"] = "Funciona uma vez por corrida. O tropeção do teu Lumi acaba até 0,4 segundos mais cedo. Só enquanto o teu Lumi está a tropeçar. Pode acontecer na primeira metade da corrida.",
        ["os.racer_card_mountain_answers_story"] = "A sua pequena nota corajosa encontrou um eco enorme.",

        ["os.racer_card_home_in_a_shell_name"] = "Lar numa Concha",
        ["os.racer_card_home_in_a_shell_short"] = "Cansa-se menos quando cansado",
        ["os.racer_card_home_in_a_shell_cond"] = "Quando o teu Lumi tem pouca energia.",
        ["os.racer_card_home_in_a_shell_desc"] = "Quando o teu Lumi tem pouca energia, cansa-se mais devagar. Deixa de ajudar assim que a energia volta a subir.",
        ["os.racer_card_home_in_a_shell_exact"] = "Funciona sempre que o teu Lumi tem 35% da energia ou menos. O teu Lumi cansa-se cerca de 6,5% menos.",
        ["os.racer_card_home_in_a_shell_story"] = "Trouxe consigo a parte sossegada de casa.",

        ["os.racer_hand_pick_prompt"] = "{0}: toca numa carta abaixo.",
        ["os.racer_album_off"] = "As cartas de corrida estão desligadas neste momento.",
        ["os.racer_pack_accessory"] = "Acessório",
        ["os.racer_pack_colour"] = "Cor",
        ["os.racer_card_move_silver"] = "Mover para a posição de prata {0}",
        ["os.racer_hand_explain"] = "As cartas de corrida dão bónus ao teu {0} durante as corridas. Uma carta de ouro é uma carta ativa que o {0} usa sozinho. As cartas de prata são bónus passivos de vários tipos. Escolhe as tuas cartas.",
        ["os.racer_hand_enter_the_cup"] = "Entrar na taça",
        ["os.racer_hand_none_gold"] = "Ainda não tens cartas de ouro. Os pacotes de prémios podem dar-te algumas.",
        ["os.racer_hand_none_silver"] = "Ainda não tens cartas de prata. Os pacotes de prémios podem dar-te algumas.",
        ["os.racer_cards_per_row_1"] = "Mostrar uma carta por linha",
        ["os.racer_cards_per_row_2"] = "Mostrar duas cartas por linha",
        ["os.racer_cards_per_row_3"] = "Mostrar três cartas por linha",
        ["os.racer_inspect_levels"] = "Níveis",
        ["os.racer_inspect_level_bonus"] = "{0}% de bónus extra",
        ["os.racer_inspect_level_default"] = "Bónus normal da carta",
        ["os.racer_hand_lumi"] = "Lumi",
        ["os.racer_hand_info_close"] = "Fechar",
    };
}
