using System.Collections.Generic;

namespace AetherOS.Apps.Racer.Localization;

public static partial class AppStrings
{
    // added after update 2.7.0 (racing cards)
    private static readonly IReadOnlyDictionary<string, string> CardsFr = new Dictionary<string, string>
    {
        // Album (the Bonus cards tab)
        ["os.racer_album_intro"] = "Les paquets de récompenses te donnent des cartes de course. Choisis une carte Or et deux cartes Argent pour ta main.",
        ["os.racer_album_levels"] = "Un paquet peut te donner une carte que tu as déjà. Cette carte monte alors d'un niveau. Au niveau 2, son effet est 15% plus fort. Au niveau 3, il est 30% plus fort. Les paquets ne te donnent plus une carte une fois qu'elle atteint le niveau 3.",
        ["os.racer_album_filter_elements"] = "Tous les éléments",
        ["os.racer_album_filter_cards"] = "Toutes les cartes",
        ["os.racer_album_filter_gold"] = "Or",
        ["os.racer_album_filter_silver"] = "Argent",
        ["os.racer_album_compact"] = "Compact",
        ["os.racer_album_search"] = "Trouver une carte",
        ["os.racer_album_no_match"] = "Aucune carte ne correspond. Change les filtres.",
        ["os.racer_album_none"] = "Tu n'as pas encore de cartes de course. Ouvre des paquets de récompenses pour en obtenir.",
        ["os.racer_album_progress"] = "{0} cartes sur {1} trouvées",
        ["os.racer_album_copies"] = "{0} copies",
        ["os.racer_album_not_found"] = "Pas encore trouvée",
        // Hand dock and hand strips
        ["os.racer_hand_title"] = "Cartes de course",
        ["os.racer_hand_choose_gold"] = "Choisir Or",
        ["os.racer_hand_choose_silver"] = "Choisir Argent",
        ["os.racer_hand_swap"] = "Échanger",
        ["os.racer_hand_remove"] = "Retirer",
        ["os.racer_hand_saved"] = "Main enregistrée",
        ["os.racer_hand_saving"] = "Enregistrement de ta main...",
        ["os.racer_hand_race"] = "Courir avec cette main",
        ["os.racer_hand_change"] = "Changer de main",
        ["os.racer_hand_enter_cup"] = "Participer avec cette main",
        ["os.racer_hand_locked_cup"] = "Verrouillée pour cette coupe",
        ["os.racer_hand_empty"] = "Ta main est vide. Ajoute des cartes depuis ton album.",
        ["os.racer_hand_slot_gold"] = "Emplacement Or",
        ["os.racer_hand_slot_silver"] = "Emplacement Argent {0}",
        ["os.racer_hand_in_hand"] = "En main",
        // Hand faults: one sentence per rule the server or the local check can refuse on
        ["os.racer_hand_fault_unknown"] = "Cette carte n'existe plus dans le jeu. Choisis-en une autre.",
        ["os.racer_hand_fault_not_owned"] = "Tu n'as pas cette carte.",
        ["os.racer_hand_fault_wrong_band"] = "Les cartes Or vont dans l'emplacement Or. Les cartes Argent vont dans les emplacements Argent.",
        ["os.racer_hand_fault_duplicate"] = "Cette carte est déjà dans ta main.",
        ["os.racer_hand_fault_shape"] = "Une main contient une carte Or et deux cartes Argent.",
        ["os.racer_hand_fault_failed"] = "Ta main n'a pas été enregistrée. Réessaie.",
        // Inspect page
        ["os.racer_inspect_tab_card"] = "Carte",
        ["os.racer_inspect_tab_art"] = "Illustration",
        ["os.racer_inspect_tab_info"] = "Infos",
        ["os.racer_inspect_when"] = "Quand elle agit",
        ["os.racer_inspect_how"] = "Comment elle agit",
        ["os.racer_inspect_exact"] = "Règles et chiffres exacts",
        ["os.racer_inspect_story"] = "Histoire et finition",
        ["os.racer_inspect_flip"] = "Retourner la carte",
        ["os.racer_card_gold"] = "Carte Or",
        ["os.racer_card_silver"] = "Carte Argent",
        ["os.racer_card_automatic"] = "Automatique",
        ["os.racer_card_once"] = "Une fois par course",
        ["os.racer_card_passive"] = "Passive",
        ["os.racer_card_rank"] = "N° {0}",
        ["os.racer_card_level"] = "Niveau {0}",
        ["os.racer_card_level_max"] = "Niveau maximum",
        ["os.racer_card_effect_bonus"] = "Effet +{0}%",
        ["os.racer_card_copy_of"] = "Copie {0} sur {1}",
        ["os.racer_card_equip_gold"] = "Mettre dans l'emplacement Or",
        ["os.racer_card_equip_silver_1"] = "Mettre dans l'emplacement Argent 1",
        ["os.racer_card_equip_silver_2"] = "Mettre dans l'emplacement Argent 2",
        ["os.racer_card_unequip"] = "Retirer de la main",
        ["os.racer_card_locked"] = "Tu n'as pas encore cette carte. Les paquets de récompenses peuvent te la donner.",
        // In-race notice and the result line
        ["os.racer_notice_gold_used"] = "A utilisé une carte Or",
        ["os.racer_replay_unavailable"] = "Cette course a utilisé des cartes plus récentes que celles que ton plugin connaît. Mets le plugin à jour pour la regarder. Le résultat compte quand même.",
        // Pack reveal and the starter grant
        ["os.racer_pack_prize_card"] = "Carte de course",
        ["os.racer_card_reveal_new"] = "Nouvelle carte",
        ["os.racer_card_reveal_level_up"] = "Maintenant niveau {0}",
        ["os.racer_cards_starter_title"] = "Tes premières cartes",
        ["os.racer_cards_starter_body"] = "Tu as reçu trois cartes de course pour commencer. Elles sont déjà dans ta main.",
        // Guard texts shared by every card of one operation kind. RaceCardGuards maps a card id to its index.
        ["os.racer_card_guard_1"] = "Ton Lumi se fatigue moins vite pendant qu'il court. Ses sprints le fatiguent toujours autant qu'avant. Cette carte ne rend pas l'énergie que ton Lumi a déjà dépensée.",
        ["os.racer_card_guard_2"] = "Ton Lumi court plus intelligemment. Il choisit de meilleurs chemins entre les autres coureurs. Il trouve plus de passages pour les doubler. Il trébuche moins souvent. Il se fatigue aussi un peu moins. Si tes deux cartes Argent font cela, leurs effets s'additionnent, mais seulement jusqu'à une limite.",
        ["os.racer_card_guard_3"] = "Ton Lumi lance ses propres sprints plus souvent. Chaque sprint est aussi rapide et aussi long qu'avant. Les Lumis ne lancent leurs propres sprints que dans la dernière partie de la course. Ton Lumi a toujours besoin d'une courte pause entre deux sprints.",
        ["os.racer_card_guard_4"] = "La vitesse de pointe de ton Lumi est un peu plus haute pendant toute la course. Il peut aussi tenir une allure un peu plus rapide avant de se fatiguer. Les virages, les autres coureurs et la fatigue le ralentissent toujours. Son temps à l'arrivée ne s'améliore donc pas d'autant.",
        ["os.racer_card_guard_5"] = "Cette carte n'aide qu'au départ. Ton Lumi quitte le départ un peu plus tôt. Chaque Lumi attend quand même au moins 0,04 seconde avant de pouvoir partir.",
        ["os.racer_card_guard_6"] = "Ton Lumi récupère un peu d'énergie et peut courir plus longtemps avant de se fatiguer. La carte n'agit que si ton Lumi a déjà dépensé au moins autant d'énergie. Si ton Lumi faiblit, il cesse de faiblir. Le montant est une part de toute son énergie, pas de ce qu'il lui reste.",
        ["os.racer_card_guard_7"] = "La carte n'agit que pendant que ton Lumi trébuche. Elle fait finir ce faux pas plus tôt. Si le faux pas est presque fini, il s'arrête tout de suite. Elle n'empêche pas ton Lumi de trébucher à nouveau plus tard.",
        ["os.racer_card_guard_8"] = "Ton Lumi court plus vite un instant. Il doit déjà courir à 75% de sa vitesse de pointe ou plus. Après la carte, il doit encore rester à ton Lumi plus de 15% de son énergie. Cela ne peut pas arriver quand ton Lumi faiblit, est bloqué, trébuche ou sprinte. Cela ne peut pas non plus arriver juste après un sprint. Si ton Lumi va lancer son sprint final, la carte attend. Les virages et les autres coureurs peuvent toujours ralentir ton Lumi. Ensuite, ton Lumi revient à sa vitesse de pointe normale.",
        ["os.racer_card_guard_9"] = "Ton Lumi sprinte un instant. La route devant lui doit être droite. Après la carte, il doit encore rester à ton Lumi plus de 15% de son énergie. Cela ne peut pas arriver quand ton Lumi faiblit, est bloqué, trébuche ou sprinte. Cela ne peut pas non plus arriver juste après un sprint. Si ton Lumi va lancer son sprint final, la carte attend. Ce sprint est aussi rapide que les propres sprints de ton Lumi. Ensuite, ton Lumi peut tout de suite relancer ses propres sprints.",
        // The 54 Core Set cards in catalogue order: name, face caption, availability, description, exact rule, story.
        ["os.racer_card_second_sunrise_name"] = "Deuxième Aurore",
        ["os.racer_card_second_sunrise_short"] = "Récupère de l'énergie si fatigué",
        ["os.racer_card_second_sunrise_cond"] = "Quand ton Lumi a peu d'énergie.",
        ["os.racer_card_second_sunrise_desc"] = "Quand ton Lumi a peu d'énergie, il récupère un peu d'énergie. Elle attend que l'énergie de ton Lumi soit très basse.",
        ["os.racer_card_second_sunrise_exact"] = "Agit une fois par course. Ton Lumi récupère 5% de son énergie. Seulement s'il reste à ton Lumi 24% de son énergie ou moins. Cela peut arriver après le premier quart de la course, jusqu'à peu avant l'arrivée.",
        ["os.racer_card_second_sunrise_story"] = "Le matin a trouvé une braise de plus.",

        ["os.racer_card_banked_embers_name"] = "Braises Couvées",
        ["os.racer_card_banked_embers_short"] = "Se fatigue moins",
        ["os.racer_card_banked_embers_cond"] = "Pendant toute la course.",
        ["os.racer_card_banked_embers_desc"] = "Ton Lumi se fatigue un peu moins vite pendant toute la course. Il lui reste un peu plus d'énergie près de l'arrivée.",
        ["os.racer_card_banked_embers_exact"] = "Agit pendant toute la course. Ton Lumi se fatigue environ 2,4% de moins.",
        ["os.racer_card_banked_embers_story"] = "Une petite chaleur peut durer longtemps.",

        ["os.racer_card_lantern_vigil_name"] = "Veille de Lanterne",
        ["os.racer_card_lantern_vigil_short"] = "Court plus malin vers la fin",
        ["os.racer_card_lantern_vigil_cond"] = "En fin de course, jusqu'à l'arrivée.",
        ["os.racer_card_lantern_vigil_desc"] = "En fin de course, ton Lumi court plus intelligemment. Il trouve plus de passages pour doubler les autres coureurs. Il trébuche aussi moins souvent.",
        ["os.racer_card_lantern_vigil_exact"] = "Agit en fin de course, jusqu'à l'arrivée. Ton Lumi court plus intelligemment. L'effet est moyen.",
        ["os.racer_card_lantern_vigil_story"] = "Quelqu'un laisse toujours une lumière pour toi.",

        ["os.racer_card_warm_footing_name"] = "Pas au Chaud",
        ["os.racer_card_warm_footing_short"] = "Court plus malin par mauvais temps",
        ["os.racer_card_warm_footing_cond"] = "Pendant toute la course. Seulement en cas de pluie, de neige, de vent fort, de chaleur, d'électricité statique ou de poussière.",
        ["os.racer_card_warm_footing_desc"] = "Par mauvais temps, ton Lumi court plus intelligemment. Il trouve plus de passages pour doubler les autres coureurs. Il trébuche aussi moins souvent.",
        ["os.racer_card_warm_footing_exact"] = "Agit pendant toute la course. Ton Lumi court plus intelligemment. L'effet est faible. Seulement en cas de pluie, de neige, de vent fort, de chaleur, d'électricité statique ou de poussière.",
        ["os.racer_card_warm_footing_story"] = "Il a trouvé la seule pierre que l'hiver avait oubliée.",

        ["os.racer_card_cinder_leap_name"] = "Bond de Cendre",
        ["os.racer_card_cinder_leap_short"] = "Sprinte pour rattraper la tête",
        ["os.racer_card_cinder_leap_cond"] = "Quand ton Lumi est derrière le coureur en tête.",
        ["os.racer_card_cinder_leap_desc"] = "Au milieu de la course, ton Lumi sprinte pour rattraper le coureur en tête. La route devant lui doit être droite.",
        ["os.racer_card_cinder_leap_exact"] = "Agit une fois par course. Ton Lumi sprinte pendant 0,55 seconde. Cela lui coûte 1% de son énergie. Le coureur en tête doit avoir au moins 1,2 longueur d'avance. Cela peut arriver au milieu de la course.",
        ["os.racer_card_cinder_leap_story"] = "Le temps d'un battement de cœur, même les cendres ont volé.",

        ["os.racer_card_slow_burn_name"] = "Feu Doux",
        ["os.racer_card_slow_burn_short"] = "Se fatigue moins en montée",
        ["os.racer_card_slow_burn_cond"] = "En montée.",
        ["os.racer_card_slow_burn_desc"] = "En montée, ton Lumi se fatigue moins vite. Il lui reste plus d'énergie pour la suite de la course.",
        ["os.racer_card_slow_burn_exact"] = "Agit chaque fois que ton Lumi court en montée. Ton Lumi se fatigue environ 7% de moins.",
        ["os.racer_card_slow_burn_story"] = "La colline était patiente. La braise aussi.",

        ["os.racer_card_sheltered_spark_name"] = "Étincelle à l'Abri",
        ["os.racer_card_sheltered_spark_short"] = "Sprinte plus par mauvais temps",
        ["os.racer_card_sheltered_spark_cond"] = "Pendant toute la course. Seulement en cas de pluie, de neige, de vent fort, de chaleur, d'électricité statique ou de poussière.",
        ["os.racer_card_sheltered_spark_desc"] = "Par mauvais temps, ton Lumi lance ses propres sprints plus souvent.",
        ["os.racer_card_sheltered_spark_exact"] = "Agit pendant toute la course. Ton Lumi lance ses propres sprints 11% plus souvent. Seulement en cas de pluie, de neige, de vent fort, de chaleur, d'électricité statique ou de poussière.",
        ["os.racer_card_sheltered_spark_story"] = "La pluie pouvait attendre dehors.",

        ["os.racer_card_home_by_firelight_name"] = "Retour au Coin du Feu",
        ["os.racer_card_home_by_firelight_short"] = "Vitesse de pointe plus haute",
        ["os.racer_card_home_by_firelight_cond"] = "Pendant toute la course.",
        ["os.racer_card_home_by_firelight_desc"] = "Ton Lumi court un tout petit peu plus vite pendant toute la course.",
        ["os.racer_card_home_by_firelight_exact"] = "Agit pendant toute la course. La vitesse de pointe de ton Lumi est un peu plus haute. Sur une longue course, cela peut lui donner jusqu'à environ 0,3 longueur d'avance en plus.",
        ["os.racer_card_home_by_firelight_story"] = "Les derniers pas sentaient la maison.",

        ["os.racer_card_last_light_name"] = "La Dernière Lueur",
        ["os.racer_card_last_light_short"] = "Sprinte pour rattraper la tête",
        ["os.racer_card_last_light_cond"] = "Quand ton Lumi est derrière le coureur en tête.",
        ["os.racer_card_last_light_desc"] = "Près de la fin de la course, ton Lumi sprinte pour rattraper le coureur en tête. La route devant lui doit être droite.",
        ["os.racer_card_last_light_exact"] = "Agit une fois par course. Ton Lumi sprinte pendant 0,65 seconde. Cela lui coûte 1% de son énergie. Le coureur en tête doit avoir au moins 0,5 longueur d'avance. Cela peut arriver près de la fin de la course.",
        ["os.racer_card_last_light_story"] = "Il a gardé une pensée lumineuse pour la fin.",

        ["os.racer_card_storm_whispers_name"] = "Murmures d'Orage",
        ["os.racer_card_storm_whispers_short"] = "Court plus malin",
        ["os.racer_card_storm_whispers_cond"] = "Pendant toute la course.",
        ["os.racer_card_storm_whispers_desc"] = "Ton Lumi court plus intelligemment pendant toute la course. Il trouve plus de passages pour doubler les autres coureurs. Il trébuche aussi moins souvent.",
        ["os.racer_card_storm_whispers_exact"] = "Agit pendant toute la course. Ton Lumi court plus intelligemment. L'effet est faible.",
        ["os.racer_card_storm_whispers_story"] = "Le plus discret des crépitements l'a prévenu en premier.",

        ["os.racer_card_borrowed_thunder_name"] = "Tonnerre Emprunté",
        ["os.racer_card_borrowed_thunder_short"] = "Sprinte en ligne droite",
        ["os.racer_card_borrowed_thunder_cond"] = "Sur une ligne droite.",
        ["os.racer_card_borrowed_thunder_desc"] = "Au milieu de la course, ton Lumi sprinte sur une ligne droite.",
        ["os.racer_card_borrowed_thunder_exact"] = "Agit une fois par course. Ton Lumi sprinte pendant 0,45 seconde. Cela lui coûte 1% de son énergie. Cela peut arriver au milieu de la course.",
        ["os.racer_card_borrowed_thunder_story"] = "Un petit nuage a répondu très fort.",

        ["os.racer_card_paper_promises_name"] = "Promesses de Papier",
        ["os.racer_card_paper_promises_short"] = "Démarre plus tôt",
        ["os.racer_card_paper_promises_cond"] = "Au départ.",
        ["os.racer_card_paper_promises_desc"] = "Ton Lumi quitte le départ plus tôt.",
        ["os.racer_card_paper_promises_exact"] = "Agit au départ de la course. L'attente de ton Lumi au départ est 4% plus courte. Chaque Lumi attend quand même au moins 0,04 seconde.",
        ["os.racer_card_paper_promises_story"] = "Il a gardé sa forme quand le vent a tourné.",

        ["os.racer_card_blink_of_brilliance_name"] = "Éclair de Génie",
        ["os.racer_card_blink_of_brilliance_short"] = "Accélère une fois débloqué",
        ["os.racer_card_blink_of_brilliance_cond"] = "Juste après que ton Lumi n'est plus bloqué, pendant qu'un coureur est encore devant.",
        ["os.racer_card_blink_of_brilliance_desc"] = "Juste après que ton Lumi n'est plus bloqué par un autre coureur, il court plus vite un instant. Cela peut arriver pendant la majeure partie de la course.",
        ["os.racer_card_blink_of_brilliance_exact"] = "Agit une fois par course, de peu après le départ jusqu'à peu avant l'arrivée. La vitesse de pointe de ton Lumi est 8% plus haute pendant 1,4 seconde. Cela lui coûte 1% de son énergie. Seulement dans la première seconde après que ton Lumi n'est plus bloqué. Un coureur doit être devant.",
        ["os.racer_card_blink_of_brilliance_story"] = "La réponse était là, le temps d'un instant.",

        ["os.racer_card_quiet_charge_name"] = "Charge Discrète",
        ["os.racer_card_quiet_charge_short"] = "Sprinte plus souvent",
        ["os.racer_card_quiet_charge_cond"] = "Pendant toute la course.",
        ["os.racer_card_quiet_charge_desc"] = "Ton Lumi lance ses propres sprints plus souvent pendant toute la course.",
        ["os.racer_card_quiet_charge_exact"] = "Agit pendant toute la course. Ton Lumi lance ses propres sprints 7,5% plus souvent.",
        ["os.racer_card_quiet_charge_story"] = "Rien ne pressait de dépenser l'étincelle.",

        ["os.racer_card_copper_company_name"] = "Compagnie de Cuivre",
        ["os.racer_card_copper_company_short"] = "Se fatigue moins derrière un coureur",
        ["os.racer_card_copper_company_cond"] = "Quand ton Lumi suit un autre coureur de près.",
        ["os.racer_card_copper_company_desc"] = "Quand ton Lumi suit un autre coureur de près, il se fatigue moins vite. L'aide s'arrête quand il ne le suit plus de près.",
        ["os.racer_card_copper_company_exact"] = "Agit chaque fois que ton Lumi suit un autre coureur de près. Ton Lumi se fatigue environ 9,1% de moins.",
        ["os.racer_card_copper_company_story"] = "Le chemin semblait plus doux à deux.",

        ["os.racer_card_after_the_flash_name"] = "Après l'Éclair",
        ["os.racer_card_after_the_flash_short"] = "Court plus malin après les faux pas par mauvais temps",
        ["os.racer_card_after_the_flash_cond"] = "Juste après un faux pas. Seulement en cas de pluie, de neige, de vent fort, de chaleur, d'électricité statique ou de poussière.",
        ["os.racer_card_after_the_flash_desc"] = "Par mauvais temps, juste après un faux pas, ton Lumi court plus intelligemment pendant un court moment. Il trouve plus de passages pour doubler les autres coureurs. Il risque moins de trébucher à nouveau.",
        ["os.racer_card_after_the_flash_exact"] = "Agit pendant les 2 secondes après la fin de chaque faux pas. Ton Lumi court plus intelligemment. L'effet est fort. Seulement en cas de pluie, de neige, de vent fort, de chaleur, d'électricité statique ou de poussière.",
        ["os.racer_card_after_the_flash_story"] = "Les flaques se souvenaient. Il a continué.",

        ["os.racer_card_bright_idea_name"] = "Idée Lumineuse",
        ["os.racer_card_bright_idea_short"] = "Court plus malin en virage",
        ["os.racer_card_bright_idea_cond"] = "Dans un virage.",
        ["os.racer_card_bright_idea_desc"] = "Dans les virages, ton Lumi court plus intelligemment. Il trouve plus de passages pour doubler les autres coureurs. Il trébuche aussi moins souvent.",
        ["os.racer_card_bright_idea_exact"] = "Agit chaque fois que ton Lumi court dans un virage. Ton Lumi court plus intelligemment. L'effet est moyen.",
        ["os.racer_card_bright_idea_story"] = "Il a vu un passage entre les gouttes.",

        ["os.racer_card_catch_the_spark_name"] = "Saisir l'Étincelle",
        ["os.racer_card_catch_the_spark_short"] = "Sprinte après un faux pas",
        ["os.racer_card_catch_the_spark_cond"] = "Juste après un faux pas.",
        ["os.racer_card_catch_the_spark_desc"] = "Juste après un faux pas, ton Lumi sprinte pour repartir. La route devant lui doit être droite.",
        ["os.racer_card_catch_the_spark_exact"] = "Agit une fois par course. Ton Lumi sprinte pendant 0,5 seconde. Cela lui coûte 1% de son énergie. Seulement dans les 2 secondes après la fin d'un faux pas. Cela peut arriver de peu après le départ jusqu'à peu avant l'arrivée.",
        ["os.racer_card_catch_the_spark_story"] = "Il n'était pas trop tard pour le remarquer.",

        ["os.racer_card_featherlight_steps_name"] = "Pas de Plume",
        ["os.racer_card_featherlight_steps_short"] = "Se fatigue moins au début",
        ["os.racer_card_featherlight_steps_cond"] = "Dans le premier tiers de la course.",
        ["os.racer_card_featherlight_steps_desc"] = "Dans le premier tiers de la course, ton Lumi se fatigue moins vite. Il lui reste plus d'énergie pour plus tard dans la course.",
        ["os.racer_card_featherlight_steps_exact"] = "Agit dans le premier tiers de la course. Ton Lumi se fatigue environ 3,8% de moins.",
        ["os.racer_card_featherlight_steps_story"] = "L'herbe a à peine senti son passage.",

        ["os.racer_card_leeward_path_name"] = "Le Sentier Abrité",
        ["os.racer_card_leeward_path_short"] = "Se fatigue moins par vent fort",
        ["os.racer_card_leeward_path_cond"] = "Pendant toute la course. Seulement par vent fort.",
        ["os.racer_card_leeward_path_desc"] = "Par vent fort, ton Lumi se fatigue moins vite pendant toute la course. Il lui reste plus d'énergie près de l'arrivée.",
        ["os.racer_card_leeward_path_exact"] = "Agit pendant toute la course. Ton Lumi se fatigue environ 4,8% de moins. Seulement par vent fort.",
        ["os.racer_card_leeward_path_story"] = "La colline gardait un peu de calme de ce côté.",

        ["os.racer_card_thread_the_gust_name"] = "Enfiler la Rafale",
        ["os.racer_card_thread_the_gust_short"] = "Accélère une fois débloqué",
        ["os.racer_card_thread_the_gust_cond"] = "Juste après que ton Lumi n'est plus bloqué, pendant qu'un coureur est encore devant.",
        ["os.racer_card_thread_the_gust_desc"] = "Au milieu de la course, juste après que ton Lumi n'est plus bloqué par un autre coureur, il court plus vite un instant.",
        ["os.racer_card_thread_the_gust_exact"] = "Agit une fois par course, au milieu de la course. La vitesse de pointe de ton Lumi est 9% plus haute pendant 1,5 seconde. Cela lui coûte 1% de son énergie. Seulement dans la première seconde après que ton Lumi n'est plus bloqué. Un coureur doit être devant.",
        ["os.racer_card_thread_the_gust_story"] = "La brise a laissé juste assez de place.",

        ["os.racer_card_lift_together_name"] = "Élan Partagé",
        ["os.racer_card_lift_together_short"] = "Récupère de l'énergie en suivant",
        ["os.racer_card_lift_together_cond"] = "Quand ton Lumi court juste derrière un autre coureur.",
        ["os.racer_card_lift_together_desc"] = "Au milieu de la course, ton Lumi récupère un peu d'énergie. Il doit courir juste derrière un autre coureur, pas sur le côté.",
        ["os.racer_card_lift_together_exact"] = "Agit une fois par course. Ton Lumi récupère 4% de son énergie. Seulement quand ton Lumi court juste derrière un autre coureur. Cela peut arriver au milieu de la course.",
        ["os.racer_card_lift_together_story"] = "Le courage voyageait sur la même brise.",

        ["os.racer_card_ribbon_weather_name"] = "Ciel de Rubans",
        ["os.racer_card_ribbon_weather_short"] = "Court plus malin par ciel dégagé",
        ["os.racer_card_ribbon_weather_cond"] = "Pendant toute la course. Seulement par ciel dégagé.",
        ["os.racer_card_ribbon_weather_desc"] = "Par ciel dégagé, ton Lumi court plus intelligemment pendant toute la course. Il trouve plus de passages pour doubler les autres coureurs. Il trébuche aussi moins souvent.",
        ["os.racer_card_ribbon_weather_exact"] = "Agit pendant toute la course. Ton Lumi court plus intelligemment. L'effet est faible. Seulement par ciel dégagé.",
        ["os.racer_card_ribbon_weather_story"] = "Un seul frémissement lui a suffi comme avertissement.",

        ["os.racer_card_long_glide_name"] = "Le Long Vol Plané",
        ["os.racer_card_long_glide_short"] = "Se fatigue moins par ciel dégagé",
        ["os.racer_card_long_glide_cond"] = "Pendant toute la course. Seulement par ciel dégagé.",
        ["os.racer_card_long_glide_desc"] = "Par ciel dégagé, ton Lumi se fatigue moins vite pendant toute la course. Il lui reste plus d'énergie près de l'arrivée.",
        ["os.racer_card_long_glide_exact"] = "Agit pendant toute la course. Ton Lumi se fatigue environ 2,7% de moins. Seulement par ciel dégagé.",
        ["os.racer_card_long_glide_story"] = "Il y avait le temps de laisser l'air faire sa part.",

        ["os.racer_card_pocket_of_calm_name"] = "Poche de Calme",
        ["os.racer_card_pocket_of_calm_short"] = "Court plus malin en groupe",
        ["os.racer_card_pocket_of_calm_cond"] = "Quand d'autres coureurs sont proches.",
        ["os.racer_card_pocket_of_calm_desc"] = "Quand au moins 2 autres coureurs sont proches, ton Lumi court plus intelligemment. Il trouve plus de passages pour les doubler.",
        ["os.racer_card_pocket_of_calm_exact"] = "Agit chaque fois qu'au moins 2 autres coureurs sont proches. Ton Lumi court plus intelligemment. L'effet est moyen.",
        ["os.racer_card_pocket_of_calm_story"] = "Il a fait de la place pour une respiration tranquille.",

        ["os.racer_card_borrowed_wings_name"] = "Ailes Empruntées",
        ["os.racer_card_borrowed_wings_short"] = "Faux pas tardif plus court",
        ["os.racer_card_borrowed_wings_cond"] = "Quand ton Lumi trébuche.",
        ["os.racer_card_borrowed_wings_desc"] = "Dans la seconde moitié de la course, cette carte fait finir un faux pas plus tôt.",
        ["os.racer_card_borrowed_wings_exact"] = "Agit une fois par course. Le faux pas de ton Lumi finit jusqu'à 0,35 seconde plus tôt. Seulement quand ton Lumi trébuche. Cela peut arriver dans la seconde moitié de la course.",
        ["os.racer_card_borrowed_wings_story"] = "Le souffle suivant était déjà en route.",

        ["os.racer_card_home_on_the_breeze_name"] = "Retour par la Brise",
        ["os.racer_card_home_on_the_breeze_short"] = "Plus rapide par mauvais temps",
        ["os.racer_card_home_on_the_breeze_cond"] = "Pendant toute la course. Seulement en cas de pluie, de neige, de vent fort, de chaleur, d'électricité statique ou de poussière.",
        ["os.racer_card_home_on_the_breeze_desc"] = "Par mauvais temps, ton Lumi court un tout petit peu plus vite pendant toute la course.",
        ["os.racer_card_home_on_the_breeze_exact"] = "Agit pendant toute la course. La vitesse de pointe de ton Lumi est un peu plus haute. Sur une longue course, cela peut lui donner jusqu'à environ 0,43 longueur d'avance en plus. Seulement en cas de pluie, de neige, de vent fort, de chaleur, d'électricité statique ou de poussière.",
        ["os.racer_card_home_on_the_breeze_story"] = "Il reconnaissait le jardin à sa façon de respirer.",

        ["os.racer_card_quiet_footing_name"] = "Pas Silencieux",
        ["os.racer_card_quiet_footing_short"] = "Court plus malin en virage serré",
        ["os.racer_card_quiet_footing_cond"] = "Dans un virage serré.",
        ["os.racer_card_quiet_footing_desc"] = "Dans les virages serrés, ton Lumi court plus intelligemment. Il trouve plus de passages pour doubler les autres coureurs. Il trébuche aussi moins souvent.",
        ["os.racer_card_quiet_footing_exact"] = "Agit chaque fois que ton Lumi court dans un virage serré. Ton Lumi court plus intelligemment. L'effet est fort.",
        ["os.racer_card_quiet_footing_story"] = "Le givre a fait de la place aux pas prudents.",

        ["os.racer_card_winter_reprieve_name"] = "Répit d'Hiver",
        ["os.racer_card_winter_reprieve_short"] = "Récupère de l'énergie s'il pleut ou neige",
        ["os.racer_card_winter_reprieve_cond"] = "Quand ton Lumi a peu d'énergie. Seulement sous la pluie ou la neige.",
        ["os.racer_card_winter_reprieve_desc"] = "Sous la pluie ou la neige, quand ton Lumi a peu d'énergie, il récupère un peu d'énergie. Elle peut agir tôt dans la course.",
        ["os.racer_card_winter_reprieve_exact"] = "Agit une fois par course. Ton Lumi récupère 5,5% de son énergie. Seulement s'il reste à ton Lumi 30% de son énergie ou moins. Seulement sous la pluie ou la neige. Cela peut arriver après le premier quart de la course, jusqu'à peu avant l'arrivée.",
        ["os.racer_card_winter_reprieve_story"] = "Le froid s'est arrêté un instant, par gentillesse.",

        ["os.racer_card_clear_reflection_name"] = "Reflet Limpide",
        ["os.racer_card_clear_reflection_short"] = "Démarre plus tôt par ciel dégagé",
        ["os.racer_card_clear_reflection_cond"] = "Au départ. Seulement par ciel dégagé.",
        ["os.racer_card_clear_reflection_desc"] = "Par ciel dégagé, ton Lumi quitte le départ plus tôt.",
        ["os.racer_card_clear_reflection_exact"] = "Agit au départ de la course. L'attente de ton Lumi au départ est 5% plus courte. Chaque Lumi attend quand même au moins 0,04 seconde. Seulement par ciel dégagé.",
        ["os.racer_card_clear_reflection_story"] = "Il écoutait avec les yeux.",

        ["os.racer_card_under_the_snow_name"] = "Sous la Neige",
        ["os.racer_card_under_the_snow_short"] = "Se fatigue moins sous la neige",
        ["os.racer_card_under_the_snow_cond"] = "Pendant toute la course. Seulement sous la neige.",
        ["os.racer_card_under_the_snow_desc"] = "Sous la neige, ton Lumi se fatigue moins vite pendant toute la course. Il lui reste plus d'énergie près de l'arrivée.",
        ["os.racer_card_under_the_snow_exact"] = "Agit pendant toute la course. Ton Lumi se fatigue environ 4,8% de moins. Seulement sous la neige.",
        ["os.racer_card_under_the_snow_story"] = "L'hiver gardait sa plus petite chambre au chaud.",

        ["os.racer_card_still_as_starlight_name"] = "Silence Étoilé",
        ["os.racer_card_still_as_starlight_short"] = "Court plus malin vers la fin par ciel dégagé",
        ["os.racer_card_still_as_starlight_cond"] = "En fin de course, jusqu'à l'arrivée. Seulement par ciel dégagé.",
        ["os.racer_card_still_as_starlight_desc"] = "Par ciel dégagé, ton Lumi court plus intelligemment en fin de course. Il trouve plus de passages pour doubler les autres coureurs. Il trébuche aussi moins souvent.",
        ["os.racer_card_still_as_starlight_exact"] = "Agit en fin de course, jusqu'à l'arrivée. Ton Lumi court plus intelligemment. L'effet est moyen. Seulement par ciel dégagé.",
        ["os.racer_card_still_as_starlight_story"] = "Même les étoiles semblaient baisser la voix.",

        ["os.racer_card_one_perfect_step_name"] = "Un Pas Parfait",
        ["os.racer_card_one_perfect_step_short"] = "Accélère après un virage",
        ["os.racer_card_one_perfect_step_cond"] = "Juste après un virage.",
        ["os.racer_card_one_perfect_step_desc"] = "Juste après un virage, ton Lumi court plus vite un instant.",
        ["os.racer_card_one_perfect_step_exact"] = "Agit une fois par course. La vitesse de pointe de ton Lumi est 8,5% plus haute pendant 1,4 seconde. Cela lui coûte 1% de son énergie. Seulement dans la première seconde après un virage. Cela peut arriver de peu après le départ jusqu'à peu avant l'arrivée.",
        ["os.racer_card_one_perfect_step_story"] = "Il a fait confiance au petit bout de sol dégagé.",

        ["os.racer_card_ring_the_frost_name"] = "Sonner le Givre",
        ["os.racer_card_ring_the_frost_short"] = "Faux pas plus court",
        ["os.racer_card_ring_the_frost_cond"] = "Quand ton Lumi trébuche.",
        ["os.racer_card_ring_the_frost_desc"] = "Presque à tout moment de la course, cette carte fait finir un faux pas plus tôt.",
        ["os.racer_card_ring_the_frost_exact"] = "Agit une fois par course. Le faux pas de ton Lumi finit jusqu'à 0,3 seconde plus tôt. Seulement quand ton Lumi trébuche. Cela peut arriver presque à tout moment de la course.",
        ["os.racer_card_ring_the_frost_story"] = "Une note claire a fait tomber l'inquiétude.",

        ["os.racer_card_soft_landing_name"] = "Atterrissage Doux",
        ["os.racer_card_soft_landing_short"] = "Court plus malin en descente",
        ["os.racer_card_soft_landing_cond"] = "En descente.",
        ["os.racer_card_soft_landing_desc"] = "En descente, ton Lumi court plus intelligemment. Il trouve plus de passages pour doubler les autres coureurs. Il trébuche aussi moins souvent.",
        ["os.racer_card_soft_landing_exact"] = "Agit chaque fois que ton Lumi court en descente. Ton Lumi court plus intelligemment. L'effet est fort.",
        ["os.racer_card_soft_landing_story"] = "La neige avait gardé cet endroit exprès.",

        ["os.racer_card_thaw_comes_slowly_name"] = "Dégel Lent",
        ["os.racer_card_thaw_comes_slowly_short"] = "Se fatigue moins vers la fin",
        ["os.racer_card_thaw_comes_slowly_cond"] = "En fin de course, jusqu'à l'arrivée.",
        ["os.racer_card_thaw_comes_slowly_desc"] = "En fin de course, ton Lumi se fatigue moins vite. Il lui reste plus d'énergie pour l'arrivée.",
        ["os.racer_card_thaw_comes_slowly_exact"] = "Agit en fin de course, jusqu'à l'arrivée. Ton Lumi se fatigue environ 4,8% de moins.",
        ["os.racer_card_thaw_comes_slowly_story"] = "Un peu de chaleur suffisait pour commencer.",

        ["os.racer_card_follow_the_flow_name"] = "Suivre le Courant",
        ["os.racer_card_follow_the_flow_short"] = "Se fatigue moins en ligne droite",
        ["os.racer_card_follow_the_flow_cond"] = "Sur une ligne droite.",
        ["os.racer_card_follow_the_flow_desc"] = "Sur les lignes droites, ton Lumi se fatigue moins vite. Il lui reste plus d'énergie pour la suite de la course.",
        ["os.racer_card_follow_the_flow_exact"] = "Agit chaque fois que ton Lumi court sur une ligne droite. Ton Lumi se fatigue environ 4,3% de moins.",
        ["os.racer_card_follow_the_flow_story"] = "Le courant connaissait un chemin plus doux.",

        ["os.racer_card_puddle_lessons_name"] = "Leçons de Flaques",
        ["os.racer_card_puddle_lessons_short"] = "Court plus malin après un faux pas",
        ["os.racer_card_puddle_lessons_cond"] = "Juste après un faux pas.",
        ["os.racer_card_puddle_lessons_desc"] = "Juste après un faux pas, ton Lumi court plus intelligemment pendant un court moment. Il trouve plus de passages pour doubler les autres coureurs. Il risque moins de trébucher à nouveau.",
        ["os.racer_card_puddle_lessons_exact"] = "Agit pendant les 2 secondes après la fin de chaque faux pas. Ton Lumi court plus intelligemment. L'effet est moyen.",
        ["os.racer_card_puddle_lessons_story"] = "Chaque flaque avait quelque chose de nouveau à dire.",

        ["os.racer_card_turning_tide_name"] = "La Marée Tourne",
        ["os.racer_card_turning_tide_short"] = "Récupère de l'énergie si fatigué",
        ["os.racer_card_turning_tide_cond"] = "Quand ton Lumi a peu d'énergie.",
        ["os.racer_card_turning_tide_desc"] = "À partir de la mi-course environ, quand ton Lumi a peu d'énergie, il récupère un peu d'énergie.",
        ["os.racer_card_turning_tide_exact"] = "Agit une fois par course. Ton Lumi récupère 4% de son énergie. Seulement s'il reste à ton Lumi 35% de son énergie ou moins. Cela peut arriver d'environ la mi-course jusqu'à peu avant l'arrivée.",
        ["os.racer_card_turning_tide_story"] = "L'eau proposait un autre passage.",

        ["os.racer_card_pearls_of_patience_name"] = "Perles de Patience",
        ["os.racer_card_pearls_of_patience_short"] = "Sprinte plus dans la seconde moitié",
        ["os.racer_card_pearls_of_patience_cond"] = "Dans la seconde moitié de la course.",
        ["os.racer_card_pearls_of_patience_desc"] = "Dans la seconde moitié de la course, ton Lumi lance ses propres sprints plus souvent.",
        ["os.racer_card_pearls_of_patience_exact"] = "Agit dans la seconde moitié de la course. Ton Lumi lance ses propres sprints 13% plus souvent.",
        ["os.racer_card_pearls_of_patience_story"] = "Il a laissé les bulles monter à leur rythme.",

        ["os.racer_card_over_the_water_name"] = "Par-dessus l'Eau",
        ["os.racer_card_over_the_water_short"] = "Sprinte pour rattraper la tête",
        ["os.racer_card_over_the_water_cond"] = "Quand ton Lumi est derrière le coureur en tête.",
        ["os.racer_card_over_the_water_desc"] = "Après le premier tiers de la course, ton Lumi sprinte pour rattraper le coureur en tête. La route devant lui doit être droite.",
        ["os.racer_card_over_the_water_exact"] = "Agit une fois par course. Ton Lumi sprinte pendant 0,65 seconde. Cela lui coûte 1% de son énergie. Le coureur en tête doit avoir au moins 0,8 longueur d'avance. Cela peut arriver après le premier tiers de la course, jusqu'à peu avant l'arrivée.",
        ["os.racer_card_over_the_water_story"] = "Il y avait juste assez de pierre pour être courageux.",

        ["os.racer_card_rain_on_glass_name"] = "Pluie sur Verre",
        ["os.racer_card_rain_on_glass_short"] = "Court plus malin en virage sous la pluie",
        ["os.racer_card_rain_on_glass_cond"] = "Dans un virage. Seulement sous la pluie.",
        ["os.racer_card_rain_on_glass_desc"] = "Dans les virages sous la pluie, ton Lumi court plus intelligemment. Il trouve plus de passages pour doubler les autres coureurs. Il trébuche aussi moins souvent.",
        ["os.racer_card_rain_on_glass_exact"] = "Agit chaque fois que ton Lumi court dans un virage. Ton Lumi court plus intelligemment. L'effet est fort. Seulement sous la pluie.",
        ["os.racer_card_rain_on_glass_story"] = "Il comptait les pauses entre les gouttes.",

        ["os.racer_card_ripple_returned_name"] = "Retour de l'Onde",
        ["os.racer_card_ripple_returned_short"] = "Récupère de l'énergie après un faux pas",
        ["os.racer_card_ripple_returned_cond"] = "Juste après un faux pas.",
        ["os.racer_card_ripple_returned_desc"] = "Juste après un faux pas, ton Lumi récupère un peu d'énergie.",
        ["os.racer_card_ripple_returned_exact"] = "Agit une fois par course. Ton Lumi récupère 5% de son énergie. Seulement dans les 2 secondes après la fin d'un faux pas. Cela peut arriver de peu après le départ jusqu'à peu avant l'arrivée.",
        ["os.racer_card_ripple_returned_story"] = "La deuxième vague l'a trouvé prêt.",

        ["os.racer_card_low_tide_friends_name"] = "Amis de Marée Basse",
        ["os.racer_card_low_tide_friends_short"] = "Court plus malin derrière un coureur",
        ["os.racer_card_low_tide_friends_cond"] = "Quand ton Lumi suit un autre coureur de près.",
        ["os.racer_card_low_tide_friends_desc"] = "Quand ton Lumi suit un autre coureur de près, il court plus intelligemment. Il trouve plus de passages pour doubler les autres coureurs. Il trébuche aussi moins souvent.",
        ["os.racer_card_low_tide_friends_exact"] = "Agit chaque fois que ton Lumi suit un autre coureur de près. Ton Lumi court plus intelligemment. L'effet est fort.",
        ["os.racer_card_low_tide_friends_story"] = "Certains voyages sont plus doux à allure de discussion.",

        ["os.racer_card_smooth_pebble_promise_name"] = "Promesse du Galet",
        ["os.racer_card_smooth_pebble_promise_short"] = "Plus rapide par ciel dégagé",
        ["os.racer_card_smooth_pebble_promise_cond"] = "Pendant toute la course. Seulement par ciel dégagé.",
        ["os.racer_card_smooth_pebble_promise_desc"] = "Par ciel dégagé, ton Lumi court un tout petit peu plus vite pendant toute la course.",
        ["os.racer_card_smooth_pebble_promise_exact"] = "Agit pendant toute la course. La vitesse de pointe de ton Lumi est un peu plus haute. Sur une longue course, cela peut lui donner jusqu'à environ 0,35 longueur d'avance en plus. Seulement par ciel dégagé.",
        ["os.racer_card_smooth_pebble_promise_story"] = "Il a rapporté la petite chose jusqu'à la maison.",

        ["os.racer_card_stand_together_name"] = "Debout Ensemble",
        ["os.racer_card_stand_together_short"] = "Récupère de l'énergie en groupe",
        ["os.racer_card_stand_together_cond"] = "Quand d'autres coureurs sont proches.",
        ["os.racer_card_stand_together_desc"] = "Au milieu de la course, ton Lumi récupère un peu d'énergie. Au moins 2 autres coureurs doivent être proches.",
        ["os.racer_card_stand_together_exact"] = "Agit une fois par course. Ton Lumi récupère 4% de son énergie. Seulement quand au moins 2 autres coureurs sont proches. Cela peut arriver au milieu de la course.",
        ["os.racer_card_stand_together_story"] = "Il se tenait un peu plus droit à côté d'un ami.",

        ["os.racer_card_roots_remember_name"] = "Mémoire des Racines",
        ["os.racer_card_roots_remember_short"] = "Court plus malin en montée",
        ["os.racer_card_roots_remember_cond"] = "En montée.",
        ["os.racer_card_roots_remember_desc"] = "En montée, ton Lumi court plus intelligemment. Il trouve plus de passages pour doubler les autres coureurs. Il trébuche aussi moins souvent.",
        ["os.racer_card_roots_remember_exact"] = "Agit chaque fois que ton Lumi court en montée. Ton Lumi court plus intelligemment. L'effet est fort.",
        ["os.racer_card_roots_remember_story"] = "Le plus vieux sentier connaissait encore son nom.",

        ["os.racer_card_patient_path_name"] = "Le Sentier Patient",
        ["os.racer_card_patient_path_short"] = "Se fatigue moins au début par ciel dégagé",
        ["os.racer_card_patient_path_cond"] = "Dans la première moitié de la course. Seulement par ciel dégagé.",
        ["os.racer_card_patient_path_desc"] = "Par ciel dégagé, ton Lumi se fatigue moins vite dans la première moitié de la course. Il lui reste plus d'énergie pour la suite.",
        ["os.racer_card_patient_path_exact"] = "Agit dans la première moitié de la course. Ton Lumi se fatigue environ 5,2% de moins. Seulement par ciel dégagé.",
        ["os.racer_card_patient_path_story"] = "Les petits pas le menaient quand même quelque part.",

        ["os.racer_card_mossbound_shelter_name"] = "Abri de Mousse",
        ["os.racer_card_mossbound_shelter_short"] = "Se fatigue moins dans la poussière",
        ["os.racer_card_mossbound_shelter_cond"] = "Pendant toute la course. Seulement dans la poussière.",
        ["os.racer_card_mossbound_shelter_desc"] = "Dans la poussière, ton Lumi se fatigue moins vite pendant toute la course. Il lui reste plus d'énergie près de l'arrivée.",
        ["os.racer_card_mossbound_shelter_exact"] = "Agit pendant toute la course. Ton Lumi se fatigue environ 4,8% de moins. Seulement dans la poussière.",
        ["os.racer_card_mossbound_shelter_story"] = "La pierre avait gardé un coin sec exprès pour ça.",

        ["os.racer_card_little_ballast_name"] = "Un Peu de Lest",
        ["os.racer_card_little_ballast_short"] = "Démarre plus tôt par mauvais temps",
        ["os.racer_card_little_ballast_cond"] = "Au départ. Seulement en cas de pluie, de neige, de vent fort, de chaleur, d'électricité statique ou de poussière.",
        ["os.racer_card_little_ballast_desc"] = "Par mauvais temps, ton Lumi quitte le départ plus tôt.",
        ["os.racer_card_little_ballast_exact"] = "Agit au départ de la course. L'attente de ton Lumi au départ est 5,5% plus courte. Chaque Lumi attend quand même au moins 0,04 seconde. Seulement en cas de pluie, de neige, de vent fort, de chaleur, d'électricité statique ou de poussière.",
        ["os.racer_card_little_ballast_story"] = "Un petit poids a aidé le monde à se sentir stable.",

        ["os.racer_card_hold_the_hill_name"] = "Tenir la Colline",
        ["os.racer_card_hold_the_hill_short"] = "Accélère après une montée",
        ["os.racer_card_hold_the_hill_cond"] = "Juste après la fin d'une montée.",
        ["os.racer_card_hold_the_hill_desc"] = "Juste après la fin d'une montée, ton Lumi court plus vite un instant.",
        ["os.racer_card_hold_the_hill_exact"] = "Agit une fois par course. La vitesse de pointe de ton Lumi est 10% plus haute pendant 1,6 seconde. Cela lui coûte 1% de son énergie. Seulement dans la première seconde après la fin d'une montée. Cela peut arriver de peu après le départ jusqu'à peu avant l'arrivée.",
        ["os.racer_card_hold_the_hill_story"] = "La pente a demandé. Il a répondu par un effort de plus.",

        ["os.racer_card_kindly_ground_name"] = "Sol Bienveillant",
        ["os.racer_card_kindly_ground_short"] = "Se fatigue moins après un faux pas",
        ["os.racer_card_kindly_ground_cond"] = "Juste après un faux pas.",
        ["os.racer_card_kindly_ground_desc"] = "Juste après un faux pas, ton Lumi se fatigue moins vite pendant un court moment.",
        ["os.racer_card_kindly_ground_exact"] = "Agit pendant les 2 secondes après la fin de chaque faux pas. Ton Lumi se fatigue environ 9,1% de moins.",
        ["os.racer_card_kindly_ground_story"] = "La terre ne voyait pas d'inconvénient à un instant de repos.",

        ["os.racer_card_mountain_answers_name"] = "La Montagne Répond",
        ["os.racer_card_mountain_answers_short"] = "Faux pas précoce plus court",
        ["os.racer_card_mountain_answers_cond"] = "Quand ton Lumi trébuche.",
        ["os.racer_card_mountain_answers_desc"] = "Dans la première moitié de la course, cette carte fait finir un faux pas plus tôt.",
        ["os.racer_card_mountain_answers_exact"] = "Agit une fois par course. Le faux pas de ton Lumi finit jusqu'à 0,4 seconde plus tôt. Seulement quand ton Lumi trébuche. Cela peut arriver dans la première moitié de la course.",
        ["os.racer_card_mountain_answers_story"] = "Sa petite note courageuse a trouvé un très grand écho.",

        ["os.racer_card_home_in_a_shell_name"] = "Chez Soi en Coquille",
        ["os.racer_card_home_in_a_shell_short"] = "Se fatigue moins s'il est fatigué",
        ["os.racer_card_home_in_a_shell_cond"] = "Quand ton Lumi a peu d'énergie.",
        ["os.racer_card_home_in_a_shell_desc"] = "Quand ton Lumi a peu d'énergie, il se fatigue moins vite. Elle arrête d'aider une fois que son énergie remonte.",
        ["os.racer_card_home_in_a_shell_exact"] = "Agit chaque fois qu'il reste à ton Lumi 35% de son énergie ou moins. Ton Lumi se fatigue environ 6,5% de moins.",
        ["os.racer_card_home_in_a_shell_story"] = "Il avait emporté la part tranquille de la maison.",

        ["os.racer_hand_pick_prompt"] = "{0} : touche une carte ci-dessous.",
        ["os.racer_album_off"] = "Les cartes de course sont désactivées pour le moment.",
        ["os.racer_pack_accessory"] = "Accessoire",
        ["os.racer_pack_colour"] = "Couleur",
        ["os.racer_card_move_silver"] = "Déplacer dans l'emplacement Argent {0}",
        ["os.racer_hand_explain"] = "Les cartes de course donnent des bonus à ton {0} pendant les courses. Une carte Or est une carte active que {0} utilise de lui-même. Les cartes Argent sont des bonus passifs de différents types. Choisis tes cartes.",
        ["os.racer_hand_enter_the_cup"] = "Participer à la coupe",
        ["os.racer_hand_none_gold"] = "Tu n'as pas encore de cartes Or. Les paquets de récompenses peuvent t'en donner.",
        ["os.racer_hand_none_silver"] = "Tu n'as pas encore de cartes Argent. Les paquets de récompenses peuvent t'en donner.",
        ["os.racer_cards_per_row_1"] = "Afficher une carte par ligne",
        ["os.racer_cards_per_row_2"] = "Afficher deux cartes par ligne",
        ["os.racer_cards_per_row_3"] = "Afficher trois cartes par ligne",
        ["os.racer_inspect_levels"] = "Niveaux",
        ["os.racer_inspect_level_bonus"] = "{0}% de bonus en plus",
        ["os.racer_inspect_level_default"] = "Bonus normal de la carte",
        ["os.racer_hand_lumi"] = "Lumi",
        ["os.racer_hand_info_close"] = "Fermer",
    };
}
