// <auto-generated> by tools/racing/cards/build_card_strings.py. Edit the script or its JSON sources, not this file. </auto-generated>
#nullable enable
using System.Collections.Generic;

namespace AetherOS.Apps.Racer.Localization;

/// <summary>Which shared guard text (<c>os.racer_card_guard_n</c>) a racing card shows under "How it works".
/// Cards of one operation kind share a guard, so the table maps a catalogue id to that guard's index.</summary>
public static class RaceCardGuards
{
    public const string KeyPrefix = "os.racer_card_guard_";

    private static readonly IReadOnlyDictionary<string, int> IndexByCardId = new Dictionary<string, int>
    {
        ["core.second-sunrise"] = 6,
        ["core.banked-embers"] = 1,
        ["core.lantern-vigil"] = 2,
        ["core.warm-footing"] = 2,
        ["core.cinder-leap"] = 9,
        ["core.slow-burn"] = 1,
        ["core.sheltered-spark"] = 3,
        ["core.home-by-firelight"] = 4,
        ["core.last-light"] = 9,
        ["core.storm-whispers"] = 2,
        ["core.borrowed-thunder"] = 9,
        ["core.paper-promises"] = 5,
        ["core.blink-of-brilliance"] = 8,
        ["core.quiet-charge"] = 3,
        ["core.copper-company"] = 1,
        ["core.after-the-flash"] = 2,
        ["core.bright-idea"] = 2,
        ["core.catch-the-spark"] = 9,
        ["core.featherlight-steps"] = 1,
        ["core.leeward-path"] = 1,
        ["core.thread-the-gust"] = 8,
        ["core.lift-together"] = 6,
        ["core.ribbon-weather"] = 2,
        ["core.long-glide"] = 1,
        ["core.pocket-of-calm"] = 2,
        ["core.borrowed-wings"] = 7,
        ["core.home-on-the-breeze"] = 4,
        ["core.quiet-footing"] = 2,
        ["core.winter-reprieve"] = 6,
        ["core.clear-reflection"] = 5,
        ["core.under-the-snow"] = 1,
        ["core.still-as-starlight"] = 2,
        ["core.one-perfect-step"] = 8,
        ["core.ring-the-frost"] = 7,
        ["core.soft-landing"] = 2,
        ["core.thaw-comes-slowly"] = 1,
        ["core.follow-the-flow"] = 1,
        ["core.puddle-lessons"] = 2,
        ["core.turning-tide"] = 6,
        ["core.pearls-of-patience"] = 3,
        ["core.over-the-water"] = 9,
        ["core.rain-on-glass"] = 2,
        ["core.ripple-returned"] = 6,
        ["core.low-tide-friends"] = 2,
        ["core.smooth-pebble-promise"] = 4,
        ["core.stand-together"] = 6,
        ["core.roots-remember"] = 2,
        ["core.patient-path"] = 1,
        ["core.mossbound-shelter"] = 1,
        ["core.little-ballast"] = 5,
        ["core.hold-the-hill"] = 8,
        ["core.kindly-ground"] = 1,
        ["core.mountain-answers"] = 7,
        ["core.home-in-a-shell"] = 1,
    };

    /// <summary>The localization key of the card's guard text, or null for an id the catalogue does not carry.</summary>
    public static string? KeyFor(string cardId)
    {
        return IndexByCardId.TryGetValue(cardId, out var index) ? KeyPrefix + index : null;
    }
}
