using System.Collections.Generic;

namespace AetherOS.Apps.Eordle.Localization;

/// <summary>The Eordle app's own UI strings, merged into the central tables at app registration.</summary>
public static class AppStrings
{
    private static readonly IReadOnlyDictionary<string, string> En = new Dictionary<string, string>
    {
        // added after update 2.3.3 (eordle)
        ["os.eordle_subtitle"] = "Every word you solve hands you the next.",
        ["os.eordle_help"] = "How to play",
        ["os.eordle_help_correct"] = "Right letter, right place",
        ["os.eordle_help_present"] = "In the word, wrong place",
        ["os.eordle_help_absent"] = "Not in the word at all",
        ["os.eordle_help_rule1"] = "Six guesses for a five-letter word.",
        ["os.eordle_help_rule2"] = "Solve one and the next is dealt at once.",
        ["os.eordle_help_rule3"] = "The run ends when a word beats you.",
        ["os.eordle_help_close"] = "Got it",
        ["os.eordle_play"] = "Play",
        ["os.eordle_high_scores"] = "High scores",
        ["os.eordle_best"] = "Best {0}",
        ["os.eordle_score"] = "Score {0}",
        ["os.eordle_words"] = "Words {0}",
        ["os.eordle_word_lang"] = "Word list",
        ["os.eordle_paused"] = "Paused",
        ["os.eordle_resume"] = "Resume",
        ["os.eordle_not_word"] = "Not in the word list",
        ["os.eordle_hint_type"] = "Write a 5 letter word on the screen",
        ["os.eordle_quit"] = "End run",
        ["os.eordle_quit_confirm"] = "Sure?",
        ["os.eordle_too_short"] = "Not enough letters",
        ["os.eordle_solved"] = "Word solved!",
        ["os.eordle_points"] = "+{0} points",
        ["os.eordle_guesses_used"] = "Guesses: {0}",
        ["os.eordle_next_word"] = "Next word",
        ["os.eordle_game_over"] = "Run over",
        ["os.eordle_new_record"] = "New record!",
        ["os.eordle_answer_was"] = "The word was {0}",
        ["os.eordle_solved_count"] = "Words solved: {0}",
        ["os.eordle_fewest"] = "Fewest guesses: {0}",
        ["os.eordle_play_again"] = "Play again",
        ["os.eordle_menu"] = "Menu",
        ["os.eordle_no_scores"] = "No scores yet. Go get one!",
    };

    private static readonly IReadOnlyDictionary<string, string> De = new Dictionary<string, string>
    {
        // added after update 2.3.3 (eordle)
        ["os.eordle_subtitle"] = "Jedes gelöste Wort bringt das nächste.",
        ["os.eordle_help"] = "So wird gespielt",
        ["os.eordle_help_correct"] = "Richtiger Buchstabe, richtige Stelle",
        ["os.eordle_help_present"] = "Im Wort, aber falsche Stelle",
        ["os.eordle_help_absent"] = "Gar nicht im Wort",
        ["os.eordle_help_rule1"] = "Sechs Versuche für ein Wort aus fünf Buchstaben.",
        ["os.eordle_help_rule2"] = "Gelöst? Das nächste kommt sofort.",
        ["os.eordle_help_rule3"] = "Der Lauf endet, wenn ein Wort dich schlägt.",
        ["os.eordle_help_close"] = "Alles klar",
        ["os.eordle_play"] = "Spielen",
        ["os.eordle_high_scores"] = "Bestenliste",
        ["os.eordle_best"] = "Beste {0}",
        ["os.eordle_score"] = "Punkte {0}",
        ["os.eordle_words"] = "Wörter {0}",
        ["os.eordle_word_lang"] = "Wortliste",
        ["os.eordle_paused"] = "Pause",
        ["os.eordle_resume"] = "Weiter",
        ["os.eordle_not_word"] = "Steht nicht in der Wortliste",
        ["os.eordle_hint_type"] = "Schreib ein Wort aus 5 Buchstaben",
        ["os.eordle_quit"] = "Lauf beenden",
        ["os.eordle_quit_confirm"] = "Sicher?",
        ["os.eordle_too_short"] = "Zu wenige Buchstaben",
        ["os.eordle_solved"] = "Wort gelöst!",
        ["os.eordle_points"] = "+{0} Punkte",
        ["os.eordle_guesses_used"] = "Versuche: {0}",
        ["os.eordle_next_word"] = "Nächstes Wort",
        ["os.eordle_game_over"] = "Lauf vorbei",
        ["os.eordle_new_record"] = "Neuer Rekord!",
        ["os.eordle_answer_was"] = "Das Wort war {0}",
        ["os.eordle_solved_count"] = "Gelöste Wörter: {0}",
        ["os.eordle_fewest"] = "Wenigste Versuche: {0}",
        ["os.eordle_play_again"] = "Nochmal",
        ["os.eordle_menu"] = "Menü",
        ["os.eordle_no_scores"] = "Noch keine Punkte. Auf geht's!",
    };

    private static readonly IReadOnlyDictionary<string, string> Es = new Dictionary<string, string>
    {
        // added after update 2.3.3 (eordle)
        ["os.eordle_subtitle"] = "Cada palabra resuelta te trae la siguiente.",
        ["os.eordle_help"] = "Cómo se juega",
        ["os.eordle_help_correct"] = "Letra correcta, lugar correcto",
        ["os.eordle_help_present"] = "Está en la palabra, en otro lugar",
        ["os.eordle_help_absent"] = "No está en la palabra",
        ["os.eordle_help_rule1"] = "Seis intentos para una palabra de cinco letras.",
        ["os.eordle_help_rule2"] = "Si la resuelves, llega la siguiente al momento.",
        ["os.eordle_help_rule3"] = "La partida acaba cuando una palabra te gana.",
        ["os.eordle_help_close"] = "Entendido",
        ["os.eordle_play"] = "Jugar",
        ["os.eordle_high_scores"] = "Mejores puntuaciones",
        ["os.eordle_best"] = "Mejor {0}",
        ["os.eordle_score"] = "Puntos {0}",
        ["os.eordle_words"] = "Palabras {0}",
        ["os.eordle_word_lang"] = "Lista de palabras",
        ["os.eordle_paused"] = "En pausa",
        ["os.eordle_resume"] = "Continuar",
        ["os.eordle_not_word"] = "No está en la lista",
        ["os.eordle_hint_type"] = "Escribe una palabra de 5 letras",
        ["os.eordle_quit"] = "Terminar",
        ["os.eordle_quit_confirm"] = "Seguro?",
        ["os.eordle_too_short"] = "Faltan letras",
        ["os.eordle_solved"] = "¡Palabra resuelta!",
        ["os.eordle_points"] = "+{0} puntos",
        ["os.eordle_guesses_used"] = "Intentos: {0}",
        ["os.eordle_next_word"] = "Siguiente palabra",
        ["os.eordle_game_over"] = "Partida terminada",
        ["os.eordle_new_record"] = "¡Nuevo récord!",
        ["os.eordle_answer_was"] = "La palabra era {0}",
        ["os.eordle_solved_count"] = "Palabras resueltas: {0}",
        ["os.eordle_fewest"] = "Menos intentos: {0}",
        ["os.eordle_play_again"] = "Jugar de nuevo",
        ["os.eordle_menu"] = "Menú",
        ["os.eordle_no_scores"] = "Aún no hay puntuaciones. ¡A por una!",
    };

    private static readonly IReadOnlyDictionary<string, string> Fr = new Dictionary<string, string>
    {
        // added after update 2.3.3 (eordle)
        ["os.eordle_subtitle"] = "Chaque mot trouvé amène le suivant.",
        ["os.eordle_help"] = "Comment jouer",
        ["os.eordle_help_correct"] = "Bonne lettre, bonne place",
        ["os.eordle_help_present"] = "Dans le mot, mais ailleurs",
        ["os.eordle_help_absent"] = "Pas dans le mot",
        ["os.eordle_help_rule1"] = "Six essais pour un mot de cinq lettres.",
        ["os.eordle_help_rule2"] = "Un mot trouvé, le suivant arrive aussitôt.",
        ["os.eordle_help_rule3"] = "La partie s’arrête quand un mot vous résiste.",
        ["os.eordle_help_close"] = "Compris",
        ["os.eordle_play"] = "Jouer",
        ["os.eordle_high_scores"] = "Meilleurs scores",
        ["os.eordle_best"] = "Record {0}",
        ["os.eordle_score"] = "Score {0}",
        ["os.eordle_words"] = "Mots {0}",
        ["os.eordle_word_lang"] = "Liste de mots",
        ["os.eordle_paused"] = "En pause",
        ["os.eordle_resume"] = "Reprendre",
        ["os.eordle_not_word"] = "Absent de la liste",
        ["os.eordle_hint_type"] = "Ecris un mot de 5 lettres",
        ["os.eordle_quit"] = "Terminer",
        ["os.eordle_quit_confirm"] = "Certain ?",
        ["os.eordle_too_short"] = "Pas assez de lettres",
        ["os.eordle_solved"] = "Mot trouvé !",
        ["os.eordle_points"] = "+{0} points",
        ["os.eordle_guesses_used"] = "Essais : {0}",
        ["os.eordle_next_word"] = "Mot suivant",
        ["os.eordle_game_over"] = "Partie terminée",
        ["os.eordle_new_record"] = "Nouveau record !",
        ["os.eordle_answer_was"] = "Le mot était {0}",
        ["os.eordle_solved_count"] = "Mots trouvés : {0}",
        ["os.eordle_fewest"] = "Le moins d'essais : {0}",
        ["os.eordle_play_again"] = "Rejouer",
        ["os.eordle_menu"] = "Menu",
        ["os.eordle_no_scores"] = "Pas encore de score. À toi de jouer !",
    };

    private static readonly IReadOnlyDictionary<string, string> Pt = new Dictionary<string, string>
    {
        // added after update 2.3.3 (eordle)
        ["os.eordle_subtitle"] = "Cada palavra resolvida traz a seguinte.",
        ["os.eordle_help"] = "Como se joga",
        ["os.eordle_help_correct"] = "Letra certa, lugar certo",
        ["os.eordle_help_present"] = "Está na palavra, noutro lugar",
        ["os.eordle_help_absent"] = "Não está na palavra",
        ["os.eordle_help_rule1"] = "Seis tentativas para uma palavra de cinco letras.",
        ["os.eordle_help_rule2"] = "Resolve uma e a seguinte chega logo.",
        ["os.eordle_help_rule3"] = "A partida acaba quando uma palavra te vence.",
        ["os.eordle_help_close"] = "Percebi",
        ["os.eordle_play"] = "Jogar",
        ["os.eordle_high_scores"] = "Melhores pontuações",
        ["os.eordle_best"] = "Melhor {0}",
        ["os.eordle_score"] = "Pontos {0}",
        ["os.eordle_words"] = "Palavras {0}",
        ["os.eordle_word_lang"] = "Lista de palavras",
        ["os.eordle_paused"] = "Em pausa",
        ["os.eordle_resume"] = "Continuar",
        ["os.eordle_not_word"] = "Não está na lista",
        ["os.eordle_hint_type"] = "Escreve uma palavra de 5 letras",
        ["os.eordle_quit"] = "Terminar",
        ["os.eordle_quit_confirm"] = "De certeza?",
        ["os.eordle_too_short"] = "Faltam letras",
        ["os.eordle_solved"] = "Palavra resolvida!",
        ["os.eordle_points"] = "+{0} pontos",
        ["os.eordle_guesses_used"] = "Tentativas: {0}",
        ["os.eordle_next_word"] = "Palavra seguinte",
        ["os.eordle_game_over"] = "Fim da partida",
        ["os.eordle_new_record"] = "Novo recorde!",
        ["os.eordle_answer_was"] = "A palavra era {0}",
        ["os.eordle_solved_count"] = "Palavras resolvidas: {0}",
        ["os.eordle_fewest"] = "Menos tentativas: {0}",
        ["os.eordle_play_again"] = "Jogar de novo",
        ["os.eordle_menu"] = "Menu",
        ["os.eordle_no_scores"] = "Ainda sem pontuações. Vai buscar uma!",
    };

    private static readonly IReadOnlyDictionary<string, string> Ru = new Dictionary<string, string>
    {
        // added after update 2.3.3 (eordle)
        ["os.eordle_subtitle"] = "Каждое угаданное слово ведёт к следующему.",
        ["os.eordle_help"] = "Как играть",
        ["os.eordle_help_correct"] = "Нужная буква на нужном месте",
        ["os.eordle_help_present"] = "Буква в слове, но не здесь",
        ["os.eordle_help_absent"] = "Такой буквы в слове нет",
        ["os.eordle_help_rule1"] = "Шесть попыток на слово из пяти букв.",
        ["os.eordle_help_rule2"] = "Угадал, и сразу приходит следующее.",
        ["os.eordle_help_rule3"] = "Забег кончается, когда слово тебя обыграет.",
        ["os.eordle_help_close"] = "Понятно",
        ["os.eordle_play"] = "Играть",
        ["os.eordle_high_scores"] = "Рекорды",
        ["os.eordle_best"] = "Рекорд {0}",
        ["os.eordle_score"] = "Очки {0}",
        ["os.eordle_words"] = "Слов {0}",
        ["os.eordle_word_lang"] = "Список слов",
        ["os.eordle_paused"] = "Пауза",
        ["os.eordle_resume"] = "Продолжить",
        ["os.eordle_not_word"] = "Такого слова нет в списке",
        ["os.eordle_hint_type"] = "Набери слово из 5 букв",
        ["os.eordle_quit"] = "Закончить",
        ["os.eordle_quit_confirm"] = "Точно?",
        ["os.eordle_too_short"] = "Слишком мало букв",
        ["os.eordle_solved"] = "Слово угадано!",
        ["os.eordle_points"] = "+{0} очков",
        ["os.eordle_guesses_used"] = "Попытки: {0}",
        ["os.eordle_next_word"] = "Следующее слово",
        ["os.eordle_game_over"] = "Забег окончен",
        ["os.eordle_new_record"] = "Новый рекорд!",
        ["os.eordle_answer_was"] = "Загаданное слово: {0}",
        ["os.eordle_solved_count"] = "Угадано слов: {0}",
        ["os.eordle_fewest"] = "Меньше всего попыток: {0}",
        ["os.eordle_play_again"] = "Ещё раз",
        ["os.eordle_menu"] = "Меню",
        ["os.eordle_no_scores"] = "Рекордов пока нет. Пора это исправить!",
    };

    public static readonly IReadOnlyDictionary<string, IReadOnlyDictionary<string, string>> Packs =
        new Dictionary<string, IReadOnlyDictionary<string, string>>
        {
            ["en"] = En,
            ["de"] = De,
            ["es"] = Es,
            ["fr"] = Fr,
            ["pt"] = Pt,
            ["ru"] = Ru,
        };
}
