using System.Collections.Generic;

namespace AetherOS.Apps.Clock;

internal static class AppStrings
{
    public static readonly Dictionary<string, string> En = new()
    {
        ["os.clock_local"] = "Local",
        ["os.clock_server"] = "Server (UTC)",
        ["os.clock_eorzea"] = "Eorzea",
        // added after update 2.0.0.0 (timers)
        ["os.clock_tab_clock"] = "Clock",
        ["os.clock_tab_timers"] = "Timers",
        ["os.clock_new_timer"] = "New timer",
        ["os.clock_hours"] = "Hours",
        ["os.clock_minutes"] = "Minutes",
        ["os.clock_seconds"] = "Seconds",
        ["os.clock_label_hint"] = "Label (optional)",
        ["os.clock_start"] = "Start",
        ["os.clock_invalid_duration"] = "Set a duration first",
        ["os.clock_alarm_sound"] = "Alarm sound",
        ["os.clock_preview"] = "Preview",
        ["os.clock_notify_chat"] = "Announce in game chat",
        ["os.clock_auto_off"] = "Auto-stop",
        ["os.clock_auto_off_off"] = "Off",
        ["os.clock_auto_off_1"] = "1 min",
        ["os.clock_auto_off_3"] = "3 min",
        ["os.clock_auto_off_5"] = "5 min",
        ["os.clock_active"] = "Active timers",
        ["os.clock_no_timers"] = "No timers yet",
        ["os.clock_cancel"] = "Cancel",
        ["os.clock_ringing"] = "Time's up",
        ["os.clock_dismiss"] = "Dismiss",
        ["os.clock_dismiss_all"] = "Dismiss all",
        ["os.clock_untitled"] = "Timer",
        ["os.clock_tab_alarms"] = "Alarms",
        ["os.clock_current_time"] = "Current time",
        ["os.clock_new_alarm"] = "New alarm",
        ["os.clock_set_alarm"] = "Set alarm",
        ["os.clock_active_alarms"] = "Active alarms",
        ["os.clock_no_alarms"] = "No alarms yet",
        ["os.clock_rings_at"] = "Rings at {0}",
    };

    public static readonly Dictionary<string, string> De = new()
    {
        ["os.clock_local"] = "Lokal",
        ["os.clock_server"] = "Server (UTC)",
        ["os.clock_eorzea"] = "Eorzea",
        // added after update 2.0.0.0 (timers)
        ["os.clock_tab_clock"] = "Uhr",
        ["os.clock_tab_timers"] = "Timer",
        ["os.clock_new_timer"] = "Neuer Timer",
        ["os.clock_hours"] = "Stunden",
        ["os.clock_minutes"] = "Minuten",
        ["os.clock_seconds"] = "Sekunden",
        ["os.clock_label_hint"] = "Bezeichnung (optional)",
        ["os.clock_start"] = "Starten",
        ["os.clock_invalid_duration"] = "Zuerst eine Dauer festlegen",
        ["os.clock_alarm_sound"] = "Alarmton",
        ["os.clock_preview"] = "Anhören",
        ["os.clock_notify_chat"] = "Im Spielchat ansagen",
        ["os.clock_auto_off"] = "Auto-Stopp",
        ["os.clock_auto_off_off"] = "Aus",
        ["os.clock_auto_off_1"] = "1 Min.",
        ["os.clock_auto_off_3"] = "3 Min.",
        ["os.clock_auto_off_5"] = "5 Min.",
        ["os.clock_active"] = "Aktive Timer",
        ["os.clock_no_timers"] = "Noch keine Timer",
        ["os.clock_cancel"] = "Abbrechen",
        ["os.clock_ringing"] = "Zeit ist um",
        ["os.clock_dismiss"] = "Schließen",
        ["os.clock_dismiss_all"] = "Alle schließen",
        ["os.clock_untitled"] = "Timer",
        ["os.clock_tab_alarms"] = "Wecker",
        ["os.clock_current_time"] = "Aktuelle Zeit",
        ["os.clock_new_alarm"] = "Neuer Wecker",
        ["os.clock_set_alarm"] = "Wecker stellen",
        ["os.clock_active_alarms"] = "Aktive Wecker",
        ["os.clock_no_alarms"] = "Noch keine Wecker",
        ["os.clock_rings_at"] = "Klingelt um {0}",
    };

    public static readonly Dictionary<string, string> Es = new()
    {
        ["os.clock_local"] = "Local",
        ["os.clock_server"] = "Servidor (UTC)",
        ["os.clock_eorzea"] = "Eorzea",
        // added after update 2.0.0.0 (timers)
        ["os.clock_tab_clock"] = "Reloj",
        ["os.clock_tab_timers"] = "Temporizadores",
        ["os.clock_new_timer"] = "Nuevo temporizador",
        ["os.clock_hours"] = "Horas",
        ["os.clock_minutes"] = "Minutos",
        ["os.clock_seconds"] = "Segundos",
        ["os.clock_label_hint"] = "Etiqueta (opcional)",
        ["os.clock_start"] = "Iniciar",
        ["os.clock_invalid_duration"] = "Primero fija una duración",
        ["os.clock_alarm_sound"] = "Sonido de alarma",
        ["os.clock_preview"] = "Escuchar",
        ["os.clock_notify_chat"] = "Anunciar en el chat del juego",
        ["os.clock_auto_off"] = "Parada automática",
        ["os.clock_auto_off_off"] = "No",
        ["os.clock_auto_off_1"] = "1 min",
        ["os.clock_auto_off_3"] = "3 min",
        ["os.clock_auto_off_5"] = "5 min",
        ["os.clock_active"] = "Temporizadores activos",
        ["os.clock_no_timers"] = "Aún no hay temporizadores",
        ["os.clock_cancel"] = "Cancelar",
        ["os.clock_ringing"] = "Se acabó el tiempo",
        ["os.clock_dismiss"] = "Descartar",
        ["os.clock_dismiss_all"] = "Descartar todos",
        ["os.clock_untitled"] = "Temporizador",
        ["os.clock_tab_alarms"] = "Alarmas",
        ["os.clock_current_time"] = "Hora actual",
        ["os.clock_new_alarm"] = "Nueva alarma",
        ["os.clock_set_alarm"] = "Poner alarma",
        ["os.clock_active_alarms"] = "Alarmas activas",
        ["os.clock_no_alarms"] = "Aún no hay alarmas",
        ["os.clock_rings_at"] = "Suena a las {0}",
    };

    public static readonly Dictionary<string, string> Fr = new()
    {
        ["os.clock_local"] = "Locale",
        ["os.clock_server"] = "Serveur (UTC)",
        ["os.clock_eorzea"] = "Éorzéa",
        // added after update 2.0.0.0 (timers)
        ["os.clock_tab_clock"] = "Horloge",
        ["os.clock_tab_timers"] = "Minuteurs",
        ["os.clock_new_timer"] = "Nouveau minuteur",
        ["os.clock_hours"] = "Heures",
        ["os.clock_minutes"] = "Minutes",
        ["os.clock_seconds"] = "Secondes",
        ["os.clock_label_hint"] = "Nom (facultatif)",
        ["os.clock_start"] = "Démarrer",
        ["os.clock_invalid_duration"] = "Définissez d'abord une durée",
        ["os.clock_alarm_sound"] = "Son d'alarme",
        ["os.clock_preview"] = "Écouter",
        ["os.clock_notify_chat"] = "Annoncer dans le chat du jeu",
        ["os.clock_auto_off"] = "Arrêt auto",
        ["os.clock_auto_off_off"] = "Non",
        ["os.clock_auto_off_1"] = "1 min",
        ["os.clock_auto_off_3"] = "3 min",
        ["os.clock_auto_off_5"] = "5 min",
        ["os.clock_active"] = "Minuteurs actifs",
        ["os.clock_no_timers"] = "Aucun minuteur",
        ["os.clock_cancel"] = "Annuler",
        ["os.clock_ringing"] = "C'est l'heure",
        ["os.clock_dismiss"] = "Ignorer",
        ["os.clock_dismiss_all"] = "Tout ignorer",
        ["os.clock_untitled"] = "Minuteur",
        ["os.clock_tab_alarms"] = "Alarmes",
        ["os.clock_current_time"] = "Heure actuelle",
        ["os.clock_new_alarm"] = "Nouvelle alarme",
        ["os.clock_set_alarm"] = "Régler l'alarme",
        ["os.clock_active_alarms"] = "Alarmes actives",
        ["os.clock_no_alarms"] = "Aucune alarme",
        ["os.clock_rings_at"] = "Sonne à {0}",
    };

    public static readonly Dictionary<string, string> Pt = new()
    {
        ["os.clock_local"] = "Local",
        ["os.clock_server"] = "Servidor (UTC)",
        ["os.clock_eorzea"] = "Eorzea",
        // added after update 2.0.0.0 (timers)
        ["os.clock_tab_clock"] = "Relógio",
        ["os.clock_tab_timers"] = "Timers",
        ["os.clock_new_timer"] = "Novo timer",
        ["os.clock_hours"] = "Horas",
        ["os.clock_minutes"] = "Minutos",
        ["os.clock_seconds"] = "Segundos",
        ["os.clock_label_hint"] = "Nome (opcional)",
        ["os.clock_start"] = "Iniciar",
        ["os.clock_invalid_duration"] = "Defina uma duração primeiro",
        ["os.clock_alarm_sound"] = "Som do alarme",
        ["os.clock_preview"] = "Ouvir",
        ["os.clock_notify_chat"] = "Anunciar no chat do jogo",
        ["os.clock_auto_off"] = "Parada automática",
        ["os.clock_auto_off_off"] = "Não",
        ["os.clock_auto_off_1"] = "1 min",
        ["os.clock_auto_off_3"] = "3 min",
        ["os.clock_auto_off_5"] = "5 min",
        ["os.clock_active"] = "Timers ativos",
        ["os.clock_no_timers"] = "Nenhum timer ainda",
        ["os.clock_cancel"] = "Cancelar",
        ["os.clock_ringing"] = "Acabou o tempo",
        ["os.clock_dismiss"] = "Descartar",
        ["os.clock_dismiss_all"] = "Descartar todos",
        ["os.clock_untitled"] = "Timer",
        ["os.clock_tab_alarms"] = "Alarmes",
        ["os.clock_current_time"] = "Hora atual",
        ["os.clock_new_alarm"] = "Novo alarme",
        ["os.clock_set_alarm"] = "Definir alarme",
        ["os.clock_active_alarms"] = "Alarmes ativos",
        ["os.clock_no_alarms"] = "Nenhum alarme ainda",
        ["os.clock_rings_at"] = "Toca às {0}",
    };

    public static readonly Dictionary<string, string> Ru = new()
    {
        ["os.clock_local"] = "Местное",
        ["os.clock_server"] = "Сервер (UTC)",
        ["os.clock_eorzea"] = "Эорзея",
        // added after update 2.0.0.0 (timers)
        ["os.clock_tab_clock"] = "Часы",
        ["os.clock_tab_timers"] = "Таймеры",
        ["os.clock_new_timer"] = "Новый таймер",
        ["os.clock_hours"] = "Часы",
        ["os.clock_minutes"] = "Минуты",
        ["os.clock_seconds"] = "Секунды",
        ["os.clock_label_hint"] = "Название (необязательно)",
        ["os.clock_start"] = "Запустить",
        ["os.clock_invalid_duration"] = "Сначала задайте длительность",
        ["os.clock_alarm_sound"] = "Звук будильника",
        ["os.clock_preview"] = "Прослушать",
        ["os.clock_notify_chat"] = "Объявлять в игровом чате",
        ["os.clock_auto_off"] = "Автостоп",
        ["os.clock_auto_off_off"] = "Выкл.",
        ["os.clock_auto_off_1"] = "1 мин",
        ["os.clock_auto_off_3"] = "3 мин",
        ["os.clock_auto_off_5"] = "5 мин",
        ["os.clock_active"] = "Активные таймеры",
        ["os.clock_no_timers"] = "Таймеров пока нет",
        ["os.clock_cancel"] = "Отменить",
        ["os.clock_ringing"] = "Время вышло",
        ["os.clock_dismiss"] = "Закрыть",
        ["os.clock_dismiss_all"] = "Закрыть все",
        ["os.clock_untitled"] = "Таймер",
        ["os.clock_tab_alarms"] = "Будильники",
        ["os.clock_current_time"] = "Текущее время",
        ["os.clock_new_alarm"] = "Новый будильник",
        ["os.clock_set_alarm"] = "Поставить будильник",
        ["os.clock_active_alarms"] = "Активные будильники",
        ["os.clock_no_alarms"] = "Будильников пока нет",
        ["os.clock_rings_at"] = "Прозвонит в {0}",
    };

    public static readonly IReadOnlyDictionary<string, IReadOnlyDictionary<string, string>> Packs = new Dictionary<string, IReadOnlyDictionary<string, string>>
    {
        ["en"] = En,
        ["de"] = De,
        ["es"] = Es,
        ["fr"] = Fr,
        ["pt"] = Pt,
        ["ru"] = Ru,
    };
}
