<Project Sdk="Dalamud.NET.Sdk/15.0.0">
  <PropertyGroup>
    <RootNamespace>AetherOS.Apps.Camera</RootNamespace>
    <AssemblyName>AetherOS.Apps.Camera</AssemblyName>
    <Use_DalamudPackager>false</Use_DalamudPackager>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="Dalamud.Bindings.ImGui" Private="false" />
    <ProjectReference Include="..\AetherOS.Sdk\AetherOS.Sdk.csproj" />
  </ItemGroup>
</Project>
