<Project Sdk="Dalamud.NET.Sdk/15.0.0">
  <PropertyGroup>
    <RootNamespace>AetherLove</RootNamespace>
    <AssemblyName>AetherLove.AppKit</AssemblyName>
    <Use_DalamudPackager>false</Use_DalamudPackager>
  </PropertyGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="AetherLovePlugin" />
    <InternalsVisibleTo Include="AetherLove.Core" />
    <InternalsVisibleTo Include="AetherOS.Shell" />
    <InternalsVisibleTo Include="AetherOS.Apps.Hangouts" />
    <InternalsVisibleTo Include="AetherOS.Apps.Places" />
    <InternalsVisibleTo Include="AetherOS.Apps.Levemetes" />
    <InternalsVisibleTo Include="AetherOS.Apps.Settings" />
    <InternalsVisibleTo Include="AetherOS.Apps.News" />
    <InternalsVisibleTo Include="AetherOS.Apps.Feedback" />
    <InternalsVisibleTo Include="AetherOS.Apps.Love" />
    <InternalsVisibleTo Include="AetherOS.Apps.Messenger" />
    <InternalsVisibleTo Include="AetherOS.Apps.Market" />
    <InternalsVisibleTo Include="AetherOS.Apps.Realtor" />
    <InternalsVisibleTo Include="AetherOS.Apps.Store" />
    <InternalsVisibleTo Include="AetherOS.Apps.Wallet" />
    <InternalsVisibleTo Include="AetherOS.Apps.Wayfinder" />
    <InternalsVisibleTo Include="AetherOS.Apps.Yapper" />
    <InternalsVisibleTo Include="AetherOS.Apps.Groove" />
    <InternalsVisibleTo Include="AetherOS.Apps.EchoVidya" />
    <InternalsVisibleTo Include="AetherOS.Apps.Aetherling" />
    <InternalsVisibleTo Include="AetherOS.Apps.Notes" />
    <InternalsVisibleTo Include="AetherOS.Apps.Calculator" />
    <InternalsVisibleTo Include="AetherOS.Apps.Timers" />
    <InternalsVisibleTo Include="AetherOS.Apps.Together" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.SignalR.Client" Version="10.0.10" />
    <PackageReference Include="NAudio" Version="2.2.1" />
    <PackageReference Include="NAudio.Vorbis" Version="1.5.0" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\AetherLove.Shared\AetherLove.Shared.csproj" />
    <ProjectReference Include="..\AetherOS.Sdk\AetherOS.Sdk.csproj" />
  </ItemGroup>
</Project>
