using System.Collections.Generic;

namespace AetherOS.Apps.Groove.Localization;

/// <summary>The Groove app's own UI strings, merged into the central tables at app registration.</summary>
public static class AppStrings
{
    private static readonly IReadOnlyDictionary<string, string> En = new Dictionary<string, string>
    {
        // added after update 2.2.3 (groove)
        ["os.groove_empty_title"] = "Nothing playing",
        ["os.groove_empty_body"] = "Start some music on your PC and it shows up here.",
        ["os.groove_menu_sources"] = "Sources",
        ["os.groove_menu_settings"] = "Settings",
        ["os.groove_sources_title"] = "Sources",
        ["os.groove_sources_auto"] = "Automatic",
        ["os.groove_sources_auto_hint"] = "Follows whatever your PC is controlling",
        ["os.groove_tt_play"] = "Play",
        ["os.groove_tt_pause"] = "Pause",
        ["os.groove_tt_next"] = "Next",
        ["os.groove_tt_prev"] = "Previous",
        ["os.groove_tt_shuffle"] = "Shuffle",
        ["os.groove_tt_repeat"] = "Repeat",
        ["os.groove_reduced_banner"] = "Limited controls on this platform.",
        ["os.groove_tt_mute"] = "Mute",
        ["os.groove_tt_unmute"] = "Unmute",
        ["os.groove_set_section_audio"] = "Game audio",
        ["os.groove_set_automute"] = "Mute game music while playing",
        ["os.groove_set_automute_hint"] = "Silences the game's background music whenever your PC is playing something, and brings it back when the music stops. Your own mute stays yours.",
        ["os.groove_bridge_title"] = "Can't reach your music",
        ["os.groove_bridge_body"] = "On Linux, Groove talks to your player through playerctl. Install it on your system and try again; the rest of the phone works normally.",
        ["os.groove_unavailable_body"] = "Windows didn't hand over its media controls. Start a player, then try again; the rest of the phone works normally.",
        ["os.groove_bridge_retry"] = "Try again",
        ["os.groove_back"] = "Back",
        ["os.groove_set_widget"] = "Home widget",
        ["os.groove_set_widget_hint"] = "Show the current track on the home screen's widget page.",
        ["os.groove_set_shade"] = "Quick controls",
        ["os.groove_set_shade_hint"] = "Show a media card in the pull-down shade.",
        ["os.groove_set_dtr"] = "Server bar",
        ["os.groove_set_dtr_hint"] = "Show the current track in the game's server info bar.",
        ["os.groove_set_section_surfaces"] = "Where it shows up",
        ["os.groove_game_volumes"] = "Game volumes",
        ["os.groove_vol_app"] = "App volume",
        ["os.groove_vol_master"] = "Game master volume",
        ["os.groove_vol_bgm"] = "Game background music",
    };

    private static readonly IReadOnlyDictionary<string, string> De = new Dictionary<string, string>
    {
        // added after update 2.2.3 (groove)
        ["os.groove_empty_title"] = "Nichts in Wiedergabe",
        ["os.groove_empty_body"] = "Starte Musik auf deinem PC und sie taucht hier auf.",
        ["os.groove_menu_sources"] = "Quellen",
        ["os.groove_menu_settings"] = "Einstellungen",
        ["os.groove_sources_title"] = "Quellen",
        ["os.groove_sources_auto"] = "Automatisch",
        ["os.groove_sources_auto_hint"] = "Folgt dem, was dein PC gerade steuert",
        ["os.groove_tt_play"] = "Abspielen",
        ["os.groove_tt_pause"] = "Pause",
        ["os.groove_tt_next"] = "Weiter",
        ["os.groove_tt_prev"] = "Zurück",
        ["os.groove_tt_shuffle"] = "Zufallswiedergabe",
        ["os.groove_tt_repeat"] = "Wiederholen",
        ["os.groove_reduced_banner"] = "Eingeschränkte Steuerung auf dieser Plattform.",
        ["os.groove_tt_mute"] = "Stummschalten",
        ["os.groove_tt_unmute"] = "Ton an",
        ["os.groove_set_section_audio"] = "Spiel-Audio",
        ["os.groove_set_automute"] = "Spielmusik beim Abspielen stummschalten",
        ["os.groove_set_automute_hint"] = "Schaltet die Hintergrundmusik des Spiels stumm, solange dein PC etwas abspielt, und holt sie zurück, sobald die Musik endet. Deine eigene Stummschaltung bleibt unangetastet.",
        ["os.groove_bridge_title"] = "Keine Verbindung zur Musik",
        ["os.groove_bridge_body"] = "Unter Linux spricht Groove über playerctl mit deinem Player. Installiere es auf deinem System und versuch es erneut; der Rest des Telefons funktioniert normal.",
        ["os.groove_unavailable_body"] = "Windows hat seine Mediensteuerung nicht freigegeben. Starte einen Player und versuche es erneut; der Rest des Telefons funktioniert normal.",
        ["os.groove_bridge_retry"] = "Erneut versuchen",
        ["os.groove_back"] = "Zurück",
        ["os.groove_set_widget"] = "Home-Widget",
        ["os.groove_set_widget_hint"] = "Den aktuellen Titel auf der Widget-Seite des Homescreens anzeigen.",
        ["os.groove_set_shade"] = "Schnellsteuerung",
        ["os.groove_set_shade_hint"] = "Eine Medienkarte in der ausklappbaren Leiste anzeigen.",
        ["os.groove_set_dtr"] = "Serverleiste",
        ["os.groove_set_dtr_hint"] = "Den aktuellen Titel in der Server-Infoleiste des Spiels anzeigen.",
        ["os.groove_set_section_surfaces"] = "Wo es auftaucht",
        ["os.groove_game_volumes"] = "Spiel-Lautstärke",
        ["os.groove_vol_app"] = "App-Lautstärke",
        ["os.groove_vol_master"] = "Gesamtlautstärke des Spiels",
        ["os.groove_vol_bgm"] = "Hintergrundmusik des Spiels",
    };

    private static readonly IReadOnlyDictionary<string, string> Es = new Dictionary<string, string>
    {
        // added after update 2.2.3 (groove)
        ["os.groove_empty_title"] = "No suena nada",
        ["os.groove_empty_body"] = "Pon música en tu PC y aparecerá aquí.",
        ["os.groove_menu_sources"] = "Fuentes",
        ["os.groove_menu_settings"] = "Ajustes",
        ["os.groove_sources_title"] = "Fuentes",
        ["os.groove_sources_auto"] = "Automático",
        ["os.groove_sources_auto_hint"] = "Sigue lo que tu PC esté controlando",
        ["os.groove_tt_play"] = "Reproducir",
        ["os.groove_tt_pause"] = "Pausar",
        ["os.groove_tt_next"] = "Siguiente",
        ["os.groove_tt_prev"] = "Anterior",
        ["os.groove_tt_shuffle"] = "Aleatorio",
        ["os.groove_tt_repeat"] = "Repetir",
        ["os.groove_reduced_banner"] = "Controles limitados en esta plataforma.",
        ["os.groove_tt_mute"] = "Silenciar",
        ["os.groove_tt_unmute"] = "Activar sonido",
        ["os.groove_set_section_audio"] = "Audio del juego",
        ["os.groove_set_automute"] = "Silenciar la música del juego al reproducir",
        ["os.groove_set_automute_hint"] = "Silencia la música de fondo del juego mientras tu PC reproduce algo y la devuelve cuando la música para. Tu propio silencio sigue siendo tuyo.",
        ["os.groove_bridge_title"] = "No llegamos a tu música",
        ["os.groove_bridge_body"] = "En Linux, Groove habla con tu reproductor a través de playerctl. Instálalo en tu sistema e inténtalo de nuevo; el resto del teléfono funciona con normalidad.",
        ["os.groove_unavailable_body"] = "Windows no ha cedido sus controles multimedia. Abre un reproductor y vuelve a intentarlo; el resto del teléfono funciona con normalidad.",
        ["os.groove_bridge_retry"] = "Reintentar",
        ["os.groove_back"] = "Atrás",
        ["os.groove_set_widget"] = "Widget de inicio",
        ["os.groove_set_widget_hint"] = "Mostrar la canción actual en la página de widgets de la pantalla de inicio.",
        ["os.groove_set_shade"] = "Controles rápidos",
        ["os.groove_set_shade_hint"] = "Mostrar una tarjeta multimedia en el panel desplegable.",
        ["os.groove_set_dtr"] = "Barra del servidor",
        ["os.groove_set_dtr_hint"] = "Mostrar la canción actual en la barra de información del servidor del juego.",
        ["os.groove_set_section_surfaces"] = "Dónde aparece",
        ["os.groove_game_volumes"] = "Volumen del juego",
        ["os.groove_vol_app"] = "Volumen de la app",
        ["os.groove_vol_master"] = "Volumen general del juego",
        ["os.groove_vol_bgm"] = "Música de fondo del juego",
    };

    private static readonly IReadOnlyDictionary<string, string> Fr = new Dictionary<string, string>
    {
        // added after update 2.2.3 (groove)
        ["os.groove_empty_title"] = "Rien en lecture",
        ["os.groove_empty_body"] = "Lancez de la musique sur votre PC et elle apparaîtra ici.",
        ["os.groove_menu_sources"] = "Sources",
        ["os.groove_menu_settings"] = "Paramètres",
        ["os.groove_sources_title"] = "Sources",
        ["os.groove_sources_auto"] = "Automatique",
        ["os.groove_sources_auto_hint"] = "Suit ce que votre PC contrôle",
        ["os.groove_tt_play"] = "Lecture",
        ["os.groove_tt_pause"] = "Pause",
        ["os.groove_tt_next"] = "Suivant",
        ["os.groove_tt_prev"] = "Précédent",
        ["os.groove_tt_shuffle"] = "Aléatoire",
        ["os.groove_tt_repeat"] = "Répéter",
        ["os.groove_reduced_banner"] = "Commandes limitées sur cette plateforme.",
        ["os.groove_tt_mute"] = "Couper le son",
        ["os.groove_tt_unmute"] = "Rétablir le son",
        ["os.groove_set_section_audio"] = "Audio du jeu",
        ["os.groove_set_automute"] = "Couper la musique du jeu pendant la lecture",
        ["os.groove_set_automute_hint"] = "Coupe la musique de fond du jeu tant que ton PC joue quelque chose, puis la rétablit quand la musique s'arrête. Ta propre coupure reste la tienne.",
        ["os.groove_bridge_title"] = "Musique introuvable",
        ["os.groove_bridge_body"] = "Sous Linux, Groove communique avec votre lecteur via playerctl. Installez-le sur votre système et réessayez ; le reste du téléphone fonctionne normalement.",
        ["os.groove_unavailable_body"] = "Windows n'a pas transmis ses commandes multimédia. Lance un lecteur puis réessaie ; le reste du téléphone fonctionne normalement.",
        ["os.groove_bridge_retry"] = "Réessayer",
        ["os.groove_back"] = "Retour",
        ["os.groove_set_widget"] = "Widget d'accueil",
        ["os.groove_set_widget_hint"] = "Afficher le morceau en cours sur la page des widgets de l'écran d'accueil.",
        ["os.groove_set_shade"] = "Commandes rapides",
        ["os.groove_set_shade_hint"] = "Afficher une carte multimédia dans le volet déroulant.",
        ["os.groove_set_dtr"] = "Barre serveur",
        ["os.groove_set_dtr_hint"] = "Afficher le morceau en cours dans la barre d'infos serveur du jeu.",
        ["os.groove_set_section_surfaces"] = "Où cela apparaît",
        ["os.groove_game_volumes"] = "Volumes du jeu",
        ["os.groove_vol_app"] = "Volume de l'application",
        ["os.groove_vol_master"] = "Volume général du jeu",
        ["os.groove_vol_bgm"] = "Musique de fond du jeu",
    };

    private static readonly IReadOnlyDictionary<string, string> Pt = new Dictionary<string, string>
    {
        // added after update 2.2.3 (groove)
        ["os.groove_empty_title"] = "Nada tocando",
        ["os.groove_empty_body"] = "Toque uma música no seu PC e ela aparece aqui.",
        ["os.groove_menu_sources"] = "Fontes",
        ["os.groove_menu_settings"] = "Configurações",
        ["os.groove_sources_title"] = "Fontes",
        ["os.groove_sources_auto"] = "Automático",
        ["os.groove_sources_auto_hint"] = "Segue o que o seu PC estiver controlando",
        ["os.groove_tt_play"] = "Tocar",
        ["os.groove_tt_pause"] = "Pausar",
        ["os.groove_tt_next"] = "Próxima",
        ["os.groove_tt_prev"] = "Anterior",
        ["os.groove_tt_shuffle"] = "Aleatório",
        ["os.groove_tt_repeat"] = "Repetir",
        ["os.groove_reduced_banner"] = "Controles limitados nesta plataforma.",
        ["os.groove_tt_mute"] = "Silenciar",
        ["os.groove_tt_unmute"] = "Ativar som",
        ["os.groove_set_section_audio"] = "Áudio do jogo",
        ["os.groove_set_automute"] = "Silenciar a música do jogo ao reproduzir",
        ["os.groove_set_automute_hint"] = "Silencia a música de fundo do jogo enquanto o teu PC estiver a reproduzir algo e traz-la de volta quando a música parar. O teu próprio silêncio continua a ser teu.",
        ["os.groove_bridge_title"] = "Não achamos a sua música",
        ["os.groove_bridge_body"] = "No Linux, o Groove conversa com o seu player pelo playerctl. Instale-o no sistema e tente de novo; o resto do telefone funciona normalmente.",
        ["os.groove_unavailable_body"] = "O Windows não entregou os controlos de multimédia. Abre um leitor e tenta de novo; o resto do telemóvel funciona normalmente.",
        ["os.groove_bridge_retry"] = "Tentar de novo",
        ["os.groove_back"] = "Voltar",
        ["os.groove_set_widget"] = "Widget da tela inicial",
        ["os.groove_set_widget_hint"] = "Mostrar a faixa atual na página de widgets da tela inicial.",
        ["os.groove_set_shade"] = "Controles rápidos",
        ["os.groove_set_shade_hint"] = "Mostrar um cartão de mídia no painel suspenso.",
        ["os.groove_set_dtr"] = "Barra do servidor",
        ["os.groove_set_dtr_hint"] = "Mostrar a faixa atual na barra de informações do servidor do jogo.",
        ["os.groove_set_section_surfaces"] = "Onde aparece",
        ["os.groove_game_volumes"] = "Volumes do jogo",
        ["os.groove_vol_app"] = "Volume do app",
        ["os.groove_vol_master"] = "Volume geral do jogo",
        ["os.groove_vol_bgm"] = "Música de fundo do jogo",
    };

    private static readonly IReadOnlyDictionary<string, string> Ru = new Dictionary<string, string>
    {
        // added after update 2.2.3 (groove)
        ["os.groove_empty_title"] = "Ничего не играет",
        ["os.groove_empty_body"] = "Включи музыку на компьютере, и она появится здесь.",
        ["os.groove_menu_sources"] = "Источники",
        ["os.groove_menu_settings"] = "Настройки",
        ["os.groove_sources_title"] = "Источники",
        ["os.groove_sources_auto"] = "Автоматически",
        ["os.groove_sources_auto_hint"] = "Следует за тем, чем управляет компьютер",
        ["os.groove_tt_play"] = "Воспроизвести",
        ["os.groove_tt_pause"] = "Пауза",
        ["os.groove_tt_next"] = "Дальше",
        ["os.groove_tt_prev"] = "Назад",
        ["os.groove_tt_shuffle"] = "Перемешать",
        ["os.groove_tt_repeat"] = "Повтор",
        ["os.groove_reduced_banner"] = "На этой платформе управление ограничено.",
        ["os.groove_tt_mute"] = "Выключить звук",
        ["os.groove_tt_unmute"] = "Включить звук",
        ["os.groove_set_section_audio"] = "Звук игры",
        ["os.groove_set_automute"] = "Глушить музыку игры во время воспроизведения",
        ["os.groove_set_automute_hint"] = "Приглушает фоновую музыку игры, пока на компьютере что-то играет, и возвращает её, когда музыка закончится. Если ты выключил музыку сам, всё останется как есть.",
        ["os.groove_bridge_title"] = "Не удаётся найти музыку",
        ["os.groove_bridge_body"] = "На Linux Groove общается с плеером через playerctl. Установи его в систему и попробуй ещё раз; остальные приложения телефона работают как обычно.",
        ["os.groove_unavailable_body"] = "Windows не отдал управление медиа. Запусти плеер и попробуй снова, остальной телефон работает как обычно.",
        ["os.groove_bridge_retry"] = "Попробовать снова",
        ["os.groove_back"] = "Назад",
        ["os.groove_set_widget"] = "Виджет на главном",
        ["os.groove_set_widget_hint"] = "Показывать текущий трек на странице виджетов главного экрана.",
        ["os.groove_set_shade"] = "Быстрое управление",
        ["os.groove_set_shade_hint"] = "Показывать карточку плеера в шторке уведомлений.",
        ["os.groove_set_dtr"] = "Серверная строка",
        ["os.groove_set_dtr_hint"] = "Показывать текущий трек в информационной строке сервера.",
        ["os.groove_set_section_surfaces"] = "Где показывать",
        ["os.groove_game_volumes"] = "Громкость игры",
        ["os.groove_vol_app"] = "Громкость приложения",
        ["os.groove_vol_master"] = "Общая громкость игры",
        ["os.groove_vol_bgm"] = "Фоновая музыка игры",
    };

    public static readonly IReadOnlyDictionary<string, IReadOnlyDictionary<string, string>> Packs =
        new Dictionary<string, IReadOnlyDictionary<string, string>>
        {
            ["en"] = En,
            ["de"] = De,
            ["es"] = Es,
            ["fr"] = Fr,
            ["pt"] = Pt,
            ["ru"] = Ru,
        };
}
