using System.Collections.Generic;

namespace AetherOS.Apps.Groove.Localization;

/// <summary>The Groove app's own UI strings, merged into the central tables at app registration.</summary>
public static class AppStrings
{
    private static readonly IReadOnlyDictionary<string, string> En = new Dictionary<string, string>
    {
        // added after update 2.2.3 (groove)
        ["os.groove_empty_title"] = "Nothing playing",
        ["os.groove_empty_body"] = "Start some music on your PC and it shows up here.",
        ["os.groove_menu_sources"] = "Sources",
        ["os.groove_menu_settings"] = "Settings",
        ["os.groove_sources_title"] = "Sources",
        ["os.groove_sources_auto"] = "Automatic",
        ["os.groove_sources_auto_hint"] = "Follows whatever your PC is controlling",
        ["os.groove_tt_play"] = "Play",
        ["os.groove_tt_pause"] = "Pause",
        ["os.groove_tt_next"] = "Next",
        ["os.groove_tt_prev"] = "Previous",
        ["os.groove_tt_shuffle"] = "Shuffle",
        ["os.groove_tt_repeat"] = "Repeat",
        ["os.groove_reduced_banner"] = "Limited controls on this platform.",
        ["os.groove_tt_mute"] = "Mute",
        ["os.groove_tt_unmute"] = "Unmute",
        ["os.groove_set_section_audio"] = "Game audio",
        ["os.groove_set_automute"] = "Mute game music while playing",
        ["os.groove_set_automute_hint"] = "Silences the game's background music whenever your PC is playing something, and brings it back when the music stops. Your own mute stays yours.",
        ["os.groove_bridge_title"] = "Can't reach your music",
        ["os.groove_bridge_body"] = "On Linux, Groove talks to your player through playerctl. Install it on your system and try again; the rest of the phone works normally.",
        ["os.groove_unavailable_body"] = "Windows didn't hand over its media controls. Start a player, then try again; the rest of the phone works normally.",
        ["os.groove_bridge_retry"] = "Try again",
        ["os.groove_back"] = "Back",
        ["os.groove_ob_what_title"] = "Your music, on your phone",
        ["os.groove_ob_what_sub"] = "Read from this computer, and nowhere else",
        ["os.groove_ob_what_body"] = "Groove shows whatever your Windows PC is playing: the track, the artist, the album and its cover, with controls to skip and pause. It reads the same media info Windows itself shows on your lock screen.",
        ["os.groove_ob_what_f1"] = "It reads only from this computer, while the game is running.",
        ["os.groove_ob_what_f2"] = "Nothing is sent anywhere. The AetherOS team never sees what you play.",
        ["os.groove_ob_what_f3"] = "No account, no history, nothing saved between sessions.",
        ["os.groove_ob_optout"] = "If you would rather AetherOS did not read your media at all, remove this app from your home screen. Nothing else in the phone reads it.",
        ["os.groove_ob_next"] = "Next",
        ["os.groove_ob_controls_title"] = "Control selection",
        ["os.groove_ob_controls_sub"] = "Where Groove is allowed to appear",
        ["os.groove_ob_controls_body"] = "Groove can show what is playing in a few places around the phone. Pick the ones you want; they are all on to begin with.",
        ["os.groove_ob_controls_later"] = "You can change any of this later in the app's settings.",
        ["os.groove_ob_finish"] = "Start listening",
        ["os.groove_set_widget"] = "Home widget",
        ["os.groove_set_widget_hint"] = "Show the current track on the home screen's widget page.",
        ["os.groove_set_shade"] = "Quick controls",
        ["os.groove_set_shade_hint"] = "Show a media card in the pull-down shade.",
        ["os.groove_set_dtr"] = "Server bar",
        ["os.groove_set_dtr_hint"] = "Show the current track in the game's server info bar.",
        ["os.groove_set_mini"] = "Mini phone",
        ["os.groove_set_mini_hint"] = "Show the transport on the minimised phone instead of the logo.",
        ["os.groove_set_section_surfaces"] = "Where it shows up",
        ["os.groove_game_volumes"] = "Game volumes",
        ["os.groove_vol_app"] = "App volume",
        ["os.groove_vol_master"] = "Game master volume",
        ["os.groove_vol_bgm"] = "Game background music",
    };

    private static readonly IReadOnlyDictionary<string, string> De = new Dictionary<string, string>
    {
        // added after update 2.2.3 (groove)
        ["os.groove_empty_title"] = "Nichts in Wiedergabe",
        ["os.groove_empty_body"] = "Starte Musik auf deinem PC und sie taucht hier auf.",
        ["os.groove_menu_sources"] = "Quellen",
        ["os.groove_menu_settings"] = "Einstellungen",
        ["os.groove_sources_title"] = "Quellen",
        ["os.groove_sources_auto"] = "Automatisch",
        ["os.groove_sources_auto_hint"] = "Folgt dem, was dein PC gerade steuert",
        ["os.groove_tt_play"] = "Abspielen",
        ["os.groove_tt_pause"] = "Pause",
        ["os.groove_tt_next"] = "Weiter",
        ["os.groove_tt_prev"] = "Zurück",
        ["os.groove_tt_shuffle"] = "Zufallswiedergabe",
        ["os.groove_tt_repeat"] = "Wiederholen",
        ["os.groove_reduced_banner"] = "Eingeschränkte Steuerung auf dieser Plattform.",
        ["os.groove_tt_mute"] = "Stummschalten",
        ["os.groove_tt_unmute"] = "Ton an",
        ["os.groove_set_section_audio"] = "Spiel-Audio",
        ["os.groove_set_automute"] = "Spielmusik beim Abspielen stummschalten",
        ["os.groove_set_automute_hint"] = "Schaltet die Hintergrundmusik des Spiels stumm, solange dein PC etwas abspielt, und holt sie zurück, sobald die Musik endet. Deine eigene Stummschaltung bleibt unangetastet.",
        ["os.groove_bridge_title"] = "Keine Verbindung zur Musik",
        ["os.groove_bridge_body"] = "Unter Linux spricht Groove über playerctl mit deinem Player. Installiere es auf deinem System und versuch es erneut; der Rest des Telefons funktioniert normal.",
        ["os.groove_unavailable_body"] = "Windows hat seine Mediensteuerung nicht freigegeben. Starte einen Player und versuche es erneut; der Rest des Telefons funktioniert normal.",
        ["os.groove_bridge_retry"] = "Erneut versuchen",
        ["os.groove_back"] = "Zurück",
        ["os.groove_ob_what_title"] = "Deine Musik, auf deinem Telefon",
        ["os.groove_ob_what_sub"] = "Von diesem Computer gelesen, sonst nirgendwo",
        ["os.groove_ob_what_body"] = "Groove zeigt, was dein Windows-PC gerade spielt: Titel, Interpret, Album und Cover, dazu Tasten zum Überspringen und Pausieren. Es liest dieselben Medieninfos, die Windows selbst auf dem Sperrbildschirm zeigt.",
        ["os.groove_ob_what_f1"] = "Gelesen wird nur auf diesem Computer, während das Spiel läuft.",
        ["os.groove_ob_what_f2"] = "Nichts wird irgendwohin gesendet. Das AetherOS-Team sieht nie, was du hörst.",
        ["os.groove_ob_what_f3"] = "Kein Konto, kein Verlauf, nichts wird über die Sitzung hinaus gespeichert.",
        ["os.groove_ob_optout"] = "Wenn AetherOS deine Medien gar nicht lesen soll, entferne diese App vom Homescreen. Nichts anderes im Telefon liest sie.",
        ["os.groove_ob_next"] = "Weiter",
        ["os.groove_ob_controls_title"] = "Anzeige wählen",
        ["os.groove_ob_controls_sub"] = "Wo Groove erscheinen darf",
        ["os.groove_ob_controls_body"] = "Groove kann an mehreren Stellen im Telefon zeigen, was läuft. Such dir aus, was du möchtest; zu Beginn ist alles an.",
        ["os.groove_ob_controls_later"] = "Das lässt sich später jederzeit in den Einstellungen der App ändern.",
        ["os.groove_ob_finish"] = "Los geht's",
        ["os.groove_set_widget"] = "Home-Widget",
        ["os.groove_set_widget_hint"] = "Den aktuellen Titel auf der Widget-Seite des Homescreens anzeigen.",
        ["os.groove_set_shade"] = "Schnellsteuerung",
        ["os.groove_set_shade_hint"] = "Eine Medienkarte in der ausklappbaren Leiste anzeigen.",
        ["os.groove_set_dtr"] = "Serverleiste",
        ["os.groove_set_dtr_hint"] = "Den aktuellen Titel in der Server-Infoleiste des Spiels anzeigen.",
        ["os.groove_set_mini"] = "Mini-Telefon",
        ["os.groove_set_mini_hint"] = "Zeigt die Steuerung auf dem verkleinerten Telefon statt des Logos.",
        ["os.groove_set_section_surfaces"] = "Wo es auftaucht",
        ["os.groove_game_volumes"] = "Spiel-Lautstärke",
        ["os.groove_vol_app"] = "App-Lautstärke",
        ["os.groove_vol_master"] = "Gesamtlautstärke des Spiels",
        ["os.groove_vol_bgm"] = "Hintergrundmusik des Spiels",
    };

    private static readonly IReadOnlyDictionary<string, string> Es = new Dictionary<string, string>
    {
        // added after update 2.2.3 (groove)
        ["os.groove_empty_title"] = "No suena nada",
        ["os.groove_empty_body"] = "Pon música en tu PC y aparecerá aquí.",
        ["os.groove_menu_sources"] = "Fuentes",
        ["os.groove_menu_settings"] = "Ajustes",
        ["os.groove_sources_title"] = "Fuentes",
        ["os.groove_sources_auto"] = "Automático",
        ["os.groove_sources_auto_hint"] = "Sigue lo que tu PC esté controlando",
        ["os.groove_tt_play"] = "Reproducir",
        ["os.groove_tt_pause"] = "Pausar",
        ["os.groove_tt_next"] = "Siguiente",
        ["os.groove_tt_prev"] = "Anterior",
        ["os.groove_tt_shuffle"] = "Aleatorio",
        ["os.groove_tt_repeat"] = "Repetir",
        ["os.groove_reduced_banner"] = "Controles limitados en esta plataforma.",
        ["os.groove_tt_mute"] = "Silenciar",
        ["os.groove_tt_unmute"] = "Activar sonido",
        ["os.groove_set_section_audio"] = "Audio del juego",
        ["os.groove_set_automute"] = "Silenciar la música del juego al reproducir",
        ["os.groove_set_automute_hint"] = "Silencia la música de fondo del juego mientras tu PC reproduce algo y la devuelve cuando la música para. Tu propio silencio sigue siendo tuyo.",
        ["os.groove_bridge_title"] = "No llegamos a tu música",
        ["os.groove_bridge_body"] = "En Linux, Groove habla con tu reproductor a través de playerctl. Instálalo en tu sistema e inténtalo de nuevo; el resto del teléfono funciona con normalidad.",
        ["os.groove_unavailable_body"] = "Windows no ha cedido sus controles multimedia. Abre un reproductor y vuelve a intentarlo; el resto del teléfono funciona con normalidad.",
        ["os.groove_bridge_retry"] = "Reintentar",
        ["os.groove_back"] = "Atrás",
        ["os.groove_ob_what_title"] = "Tu música, en tu teléfono",
        ["os.groove_ob_what_sub"] = "Leída de este ordenador y de ningún otro sitio",
        ["os.groove_ob_what_body"] = "Groove muestra lo que esté sonando en tu PC con Windows: la pista, el artista, el álbum y su portada, con controles para saltar y pausar. Lee la misma información multimedia que Windows enseña en tu pantalla de bloqueo.",
        ["os.groove_ob_what_f1"] = "Solo lee de este ordenador, mientras el juego está abierto.",
        ["os.groove_ob_what_f2"] = "No se envía nada a ninguna parte. El equipo de AetherOS nunca ve lo que escuchas.",
        ["os.groove_ob_what_f3"] = "Sin cuenta, sin historial, nada guardado entre sesiones.",
        ["os.groove_ob_optout"] = "Si prefieres que AetherOS no lea tus medios en absoluto, quita esta app de tu pantalla de inicio. Nada más en el teléfono los lee.",
        ["os.groove_ob_next"] = "Siguiente",
        ["os.groove_ob_controls_title"] = "Elegir controles",
        ["os.groove_ob_controls_sub"] = "Dónde puede aparecer Groove",
        ["os.groove_ob_controls_body"] = "Groove puede mostrar lo que suena en varios sitios del teléfono. Elige los que quieras; al principio están todos activados.",
        ["os.groove_ob_controls_later"] = "Puedes cambiar todo esto después en los ajustes de la app.",
        ["os.groove_ob_finish"] = "Empezar a escuchar",
        ["os.groove_set_widget"] = "Widget de inicio",
        ["os.groove_set_widget_hint"] = "Mostrar la canción actual en la página de widgets de la pantalla de inicio.",
        ["os.groove_set_shade"] = "Controles rápidos",
        ["os.groove_set_shade_hint"] = "Mostrar una tarjeta multimedia en el panel desplegable.",
        ["os.groove_set_dtr"] = "Barra del servidor",
        ["os.groove_set_dtr_hint"] = "Mostrar la canción actual en la barra de información del servidor del juego.",
        ["os.groove_set_mini"] = "Teléfono mini",
        ["os.groove_set_mini_hint"] = "Muestra los controles en el teléfono minimizado en vez del logo.",
        ["os.groove_set_section_surfaces"] = "Dónde aparece",
        ["os.groove_game_volumes"] = "Volumen del juego",
        ["os.groove_vol_app"] = "Volumen de la app",
        ["os.groove_vol_master"] = "Volumen general del juego",
        ["os.groove_vol_bgm"] = "Música de fondo del juego",
    };

    private static readonly IReadOnlyDictionary<string, string> Fr = new Dictionary<string, string>
    {
        // added after update 2.2.3 (groove)
        ["os.groove_empty_title"] = "Rien en lecture",
        ["os.groove_empty_body"] = "Lancez de la musique sur votre PC et elle apparaîtra ici.",
        ["os.groove_menu_sources"] = "Sources",
        ["os.groove_menu_settings"] = "Paramètres",
        ["os.groove_sources_title"] = "Sources",
        ["os.groove_sources_auto"] = "Automatique",
        ["os.groove_sources_auto_hint"] = "Suit ce que votre PC contrôle",
        ["os.groove_tt_play"] = "Lecture",
        ["os.groove_tt_pause"] = "Pause",
        ["os.groove_tt_next"] = "Suivant",
        ["os.groove_tt_prev"] = "Précédent",
        ["os.groove_tt_shuffle"] = "Aléatoire",
        ["os.groove_tt_repeat"] = "Répéter",
        ["os.groove_reduced_banner"] = "Commandes limitées sur cette plateforme.",
        ["os.groove_tt_mute"] = "Couper le son",
        ["os.groove_tt_unmute"] = "Rétablir le son",
        ["os.groove_set_section_audio"] = "Audio du jeu",
        ["os.groove_set_automute"] = "Couper la musique du jeu pendant la lecture",
        ["os.groove_set_automute_hint"] = "Coupe la musique de fond du jeu tant que ton PC joue quelque chose, puis la rétablit quand la musique s'arrête. Ta propre coupure reste la tienne.",
        ["os.groove_bridge_title"] = "Musique introuvable",
        ["os.groove_bridge_body"] = "Sous Linux, Groove communique avec votre lecteur via playerctl. Installez-le sur votre système et réessayez ; le reste du téléphone fonctionne normalement.",
        ["os.groove_unavailable_body"] = "Windows n'a pas transmis ses commandes multimédia. Lance un lecteur puis réessaie ; le reste du téléphone fonctionne normalement.",
        ["os.groove_bridge_retry"] = "Réessayer",
        ["os.groove_back"] = "Retour",
        ["os.groove_ob_what_title"] = "Votre musique, sur votre téléphone",
        ["os.groove_ob_what_sub"] = "Lue depuis cet ordinateur, et nulle part ailleurs",
        ["os.groove_ob_what_body"] = "Groove affiche ce que joue votre PC Windows : le titre, l'artiste, l'album et sa pochette, avec de quoi passer et mettre en pause. Il lit les mêmes informations multimédias que Windows affiche sur votre écran de verrouillage.",
        ["os.groove_ob_what_f1"] = "La lecture se fait uniquement sur cet ordinateur, pendant que le jeu tourne.",
        ["os.groove_ob_what_f2"] = "Rien n'est envoyé nulle part. L'équipe AetherOS ne voit jamais ce que vous écoutez.",
        ["os.groove_ob_what_f3"] = "Aucun compte, aucun historique, rien de conservé d'une session à l'autre.",
        ["os.groove_ob_optout"] = "Si vous préférez qu'AetherOS ne lise pas du tout vos médias, retirez cette appli de votre écran d'accueil. Rien d'autre dans le téléphone ne les lit.",
        ["os.groove_ob_next"] = "Suivant",
        ["os.groove_ob_controls_title"] = "Choix des affichages",
        ["os.groove_ob_controls_sub"] = "Où Groove a le droit d'apparaître",
        ["os.groove_ob_controls_body"] = "Groove peut afficher ce qui joue à plusieurs endroits du téléphone. Choisissez ceux que vous voulez ; tout est activé au départ.",
        ["os.groove_ob_controls_later"] = "Vous pourrez changer tout cela plus tard dans les réglages de l'appli.",
        ["os.groove_ob_finish"] = "Commencer à écouter",
        ["os.groove_set_widget"] = "Widget d'accueil",
        ["os.groove_set_widget_hint"] = "Afficher le morceau en cours sur la page des widgets de l'écran d'accueil.",
        ["os.groove_set_shade"] = "Commandes rapides",
        ["os.groove_set_shade_hint"] = "Afficher une carte multimédia dans le volet déroulant.",
        ["os.groove_set_dtr"] = "Barre serveur",
        ["os.groove_set_dtr_hint"] = "Afficher le morceau en cours dans la barre d'infos serveur du jeu.",
        ["os.groove_set_mini"] = "Téléphone réduit",
        ["os.groove_set_mini_hint"] = "Affiche les commandes sur le téléphone réduit au lieu du logo.",
        ["os.groove_set_section_surfaces"] = "Où cela apparaît",
        ["os.groove_game_volumes"] = "Volumes du jeu",
        ["os.groove_vol_app"] = "Volume de l'application",
        ["os.groove_vol_master"] = "Volume général du jeu",
        ["os.groove_vol_bgm"] = "Musique de fond du jeu",
    };

    private static readonly IReadOnlyDictionary<string, string> Pt = new Dictionary<string, string>
    {
        // added after update 2.2.3 (groove)
        ["os.groove_empty_title"] = "Nada tocando",
        ["os.groove_empty_body"] = "Toque uma música no seu PC e ela aparece aqui.",
        ["os.groove_menu_sources"] = "Fontes",
        ["os.groove_menu_settings"] = "Configurações",
        ["os.groove_sources_title"] = "Fontes",
        ["os.groove_sources_auto"] = "Automático",
        ["os.groove_sources_auto_hint"] = "Segue o que o seu PC estiver controlando",
        ["os.groove_tt_play"] = "Tocar",
        ["os.groove_tt_pause"] = "Pausar",
        ["os.groove_tt_next"] = "Próxima",
        ["os.groove_tt_prev"] = "Anterior",
        ["os.groove_tt_shuffle"] = "Aleatório",
        ["os.groove_tt_repeat"] = "Repetir",
        ["os.groove_reduced_banner"] = "Controles limitados nesta plataforma.",
        ["os.groove_tt_mute"] = "Silenciar",
        ["os.groove_tt_unmute"] = "Ativar som",
        ["os.groove_set_section_audio"] = "Áudio do jogo",
        ["os.groove_set_automute"] = "Silenciar a música do jogo ao reproduzir",
        ["os.groove_set_automute_hint"] = "Silencia a música de fundo do jogo enquanto o teu PC estiver a reproduzir algo e traz-la de volta quando a música parar. O teu próprio silêncio continua a ser teu.",
        ["os.groove_bridge_title"] = "Não achamos a sua música",
        ["os.groove_bridge_body"] = "No Linux, o Groove conversa com o seu player pelo playerctl. Instale-o no sistema e tente de novo; o resto do telefone funciona normalmente.",
        ["os.groove_unavailable_body"] = "O Windows não entregou os controlos de multimédia. Abre um leitor e tenta de novo; o resto do telemóvel funciona normalmente.",
        ["os.groove_bridge_retry"] = "Tentar de novo",
        ["os.groove_back"] = "Voltar",
        ["os.groove_ob_what_title"] = "Sua música, no seu telefone",
        ["os.groove_ob_what_sub"] = "Lida deste computador e de mais lugar nenhum",
        ["os.groove_ob_what_body"] = "O Groove mostra o que o seu PC com Windows está tocando: a faixa, o artista, o álbum e a capa, com controles para pular e pausar. Ele lê as mesmas informações de mídia que o próprio Windows mostra na tela de bloqueio.",
        ["os.groove_ob_what_f1"] = "Lê apenas deste computador, enquanto o jogo está aberto.",
        ["os.groove_ob_what_f2"] = "Nada é enviado para lugar nenhum. A equipe do AetherOS nunca vê o que você ouve.",
        ["os.groove_ob_what_f3"] = "Sem conta, sem histórico, nada guardado entre sessões.",
        ["os.groove_ob_optout"] = "Se preferir que o AetherOS não leia sua mídia de jeito nenhum, tire este app da tela inicial. Mais nada no telefone lê isso.",
        ["os.groove_ob_next"] = "Avançar",
        ["os.groove_ob_controls_title"] = "Escolher os controles",
        ["os.groove_ob_controls_sub"] = "Onde o Groove pode aparecer",
        ["os.groove_ob_controls_body"] = "O Groove pode mostrar o que está tocando em alguns lugares do telefone. Escolha os que quiser; no começo estão todos ligados.",
        ["os.groove_ob_controls_later"] = "Dá para mudar tudo isso depois nas configurações do app.",
        ["os.groove_ob_finish"] = "Começar a ouvir",
        ["os.groove_set_widget"] = "Widget da tela inicial",
        ["os.groove_set_widget_hint"] = "Mostrar a faixa atual na página de widgets da tela inicial.",
        ["os.groove_set_shade"] = "Controles rápidos",
        ["os.groove_set_shade_hint"] = "Mostrar um cartão de mídia no painel suspenso.",
        ["os.groove_set_dtr"] = "Barra do servidor",
        ["os.groove_set_dtr_hint"] = "Mostrar a faixa atual na barra de informações do servidor do jogo.",
        ["os.groove_set_mini"] = "Telefone reduzido",
        ["os.groove_set_mini_hint"] = "Mostra os controlos no telefone reduzido em vez do logótipo.",
        ["os.groove_set_section_surfaces"] = "Onde aparece",
        ["os.groove_game_volumes"] = "Volumes do jogo",
        ["os.groove_vol_app"] = "Volume do app",
        ["os.groove_vol_master"] = "Volume geral do jogo",
        ["os.groove_vol_bgm"] = "Música de fundo do jogo",
    };

    private static readonly IReadOnlyDictionary<string, string> Ru = new Dictionary<string, string>
    {
        // added after update 2.2.3 (groove)
        ["os.groove_empty_title"] = "Ничего не играет",
        ["os.groove_empty_body"] = "Включи музыку на компьютере, и она появится здесь.",
        ["os.groove_menu_sources"] = "Источники",
        ["os.groove_menu_settings"] = "Настройки",
        ["os.groove_sources_title"] = "Источники",
        ["os.groove_sources_auto"] = "Автоматически",
        ["os.groove_sources_auto_hint"] = "Следует за тем, чем управляет компьютер",
        ["os.groove_tt_play"] = "Воспроизвести",
        ["os.groove_tt_pause"] = "Пауза",
        ["os.groove_tt_next"] = "Дальше",
        ["os.groove_tt_prev"] = "Назад",
        ["os.groove_tt_shuffle"] = "Перемешать",
        ["os.groove_tt_repeat"] = "Повтор",
        ["os.groove_reduced_banner"] = "На этой платформе управление ограничено.",
        ["os.groove_tt_mute"] = "Выключить звук",
        ["os.groove_tt_unmute"] = "Включить звук",
        ["os.groove_set_section_audio"] = "Звук игры",
        ["os.groove_set_automute"] = "Глушить музыку игры во время воспроизведения",
        ["os.groove_set_automute_hint"] = "Приглушает фоновую музыку игры, пока на компьютере что-то играет, и возвращает её, когда музыка закончится. Если ты выключил музыку сам, всё останется как есть.",
        ["os.groove_bridge_title"] = "Не удаётся найти музыку",
        ["os.groove_bridge_body"] = "На Linux Groove общается с плеером через playerctl. Установи его в систему и попробуй ещё раз; остальные приложения телефона работают как обычно.",
        ["os.groove_unavailable_body"] = "Windows не отдал управление медиа. Запусти плеер и попробуй снова, остальной телефон работает как обычно.",
        ["os.groove_bridge_retry"] = "Попробовать снова",
        ["os.groove_back"] = "Назад",
        ["os.groove_ob_what_title"] = "Ваша музыка на телефоне",
        ["os.groove_ob_what_sub"] = "Читается с этого компьютера и больше ниоткуда",
        ["os.groove_ob_what_body"] = "Groove показывает то, что играет на вашем ПК с Windows: трек, исполнителя, альбом и обложку, а также кнопки для паузы и переключения. Он читает те же данные о медиа, которые Windows сама показывает на экране блокировки.",
        ["os.groove_ob_what_f1"] = "Читает только с этого компьютера и только пока игра запущена.",
        ["os.groove_ob_what_f2"] = "Никуда ничего не отправляется. Команда AetherOS никогда не видит, что вы слушаете.",
        ["os.groove_ob_what_f3"] = "Ни аккаунта, ни истории: между сеансами ничего не сохраняется.",
        ["os.groove_ob_optout"] = "Если вы вообще не хотите, чтобы AetherOS читала ваши медиа, уберите это приложение с домашнего экрана. Больше в телефоне их никто не читает.",
        ["os.groove_ob_next"] = "Далее",
        ["os.groove_ob_controls_title"] = "Выбор отображения",
        ["os.groove_ob_controls_sub"] = "Где Groove может появляться",
        ["os.groove_ob_controls_body"] = "Groove может показывать играющий трек в нескольких местах телефона. Выберите нужные: поначалу включено всё.",
        ["os.groove_ob_controls_later"] = "Всё это можно изменить позже в настройках приложения.",
        ["os.groove_ob_finish"] = "Начать слушать",
        ["os.groove_set_widget"] = "Виджет на главном",
        ["os.groove_set_widget_hint"] = "Показывать текущий трек на странице виджетов главного экрана.",
        ["os.groove_set_shade"] = "Быстрое управление",
        ["os.groove_set_shade_hint"] = "Показывать карточку плеера в шторке уведомлений.",
        ["os.groove_set_dtr"] = "Серверная строка",
        ["os.groove_set_dtr_hint"] = "Показывать текущий трек в информационной строке сервера.",
        ["os.groove_set_mini"] = "Мини-телефон",
        ["os.groove_set_mini_hint"] = "Показывает управление на свёрнутом телефоне вместо логотипа.",
        ["os.groove_set_section_surfaces"] = "Где показывать",
        ["os.groove_game_volumes"] = "Громкость игры",
        ["os.groove_vol_app"] = "Громкость приложения",
        ["os.groove_vol_master"] = "Общая громкость игры",
        ["os.groove_vol_bgm"] = "Фоновая музыка игры",
    };

    public static readonly IReadOnlyDictionary<string, IReadOnlyDictionary<string, string>> Packs =
        new Dictionary<string, IReadOnlyDictionary<string, string>>
        {
            ["en"] = En,
            ["de"] = De,
            ["es"] = Es,
            ["fr"] = Fr,
            ["pt"] = Pt,
            ["ru"] = Ru,
        };
}
