namespace AetherLove.Emoji;

internal static class EmojiCategories
{
    internal sealed record Category(string Id, string Label, string[] Names);

    internal static readonly Category[] All =
    [
        new("smileys", "Smileys & Emotion",
        [
            // positive faces
            "grinning", "smile", "smiley", "laughing", "joy", "rofl", "blush", "wink",
            "slight_smile", "upside_down", "relaxed",
            "kissing_heart", "kissing", "kissing_smiling_eyes", "kissing_closed_eyes",
            "heart_eyes", "smiling_face_with_3_hearts", "star_struck", "sunglasses", "nerd",
            "hugging", "partying_face", "cowboy", "money_mouth",
            "thinking", "face_with_raised_eyebrow", "face_with_monocle",
            "face_with_hand_over_mouth", "shushing_face", "zipper_mouth",
            "innocent", "angel",
            // neutral / tired
            "sweat_smile", "sweat", "cold_sweat", "drooling_face", "yum",
            "stuck_out_tongue", "stuck_out_tongue_winking_eye", "stuck_out_tongue_closed_eyes",
            "lying_face", "rolling_eyes", "expressionless", "neutral_face", "unamused", "no_mouth",
            "slight_frown", "pensive", "confused", "worried",
            "sleeping", "sleepy", "zzz", "yawning_face",
            // negative / sad
            "persevere", "weary", "anguished", "frowning", "frowning2",
            "disappointed", "disappointed_relieved", "fearful", "scream", "rage", "triumph",
            "angry", "grimacing", "face_with_symbols_over_mouth",
            "cry", "sob", "tired_face",
            // physical / sick
            "open_mouth", "hushed", "astonished", "flushed", "exploding_head",
            "cold_face", "hot_face", "thermometer_face", "head_bandage",
            "nauseated_face", "face_vomiting", "sneezing_face", "woozy_face",
            // fun / fantastical faces
            "smirk", "clown", "zany_face", "mask", "imp", "smiling_imp",
            "japanese_goblin", "japanese_ogre", "ghost", "alien", "robot", "poop",
            "skull", "skull_crossbones",
            // three wise monkeys
            "see_no_evil", "hear_no_evil", "speak_no_evil",
            // cat faces
            "joy_cat", "smiley_cat", "smile_cat", "heart_eyes_cat", "kissing_cat",
            "smirk_cat", "crying_cat_face", "pouting_cat", "scream_cat",
            // hearts
            "heart", "yellow_heart", "green_heart", "blue_heart", "purple_heart",
            "orange_heart", "brown_heart", "black_heart", "white_heart",
            "broken_heart", "two_hearts", "revolving_hearts",
            "heartbeat", "heartpulse", "sparkling_heart",
            "cupid", "gift_heart", "heart_decoration", "heart_exclamation",
            // emotion effects / symbols
            "boom", "anger", "anger_right", "dash", "dizzy",
            "speech_balloon", "speech_left", "thought_balloon",
        ]),

        new("people", "People & Body",
        [
            // hand gestures
            "wave", "raised_hand", "raised_back_of_hand", "raised_hands",
            "open_hands", "palms_up_together", "clap", "pray",
            "thumbsup", "thumbsdown", "ok_hand", "pinching_hand",
            "point_up", "point_up_2", "point_down", "point_left", "point_right",
            "fingers_crossed", "vulcan", "metal", "v", "love_you_gesture",
            "call_me", "fist", "punch", "left_facing_fist", "right_facing_fist",
            "handshake", "muscle",
            "middle_finger", "hand_splayed",
            // body parts
            "writing_hand", "selfie", "nail_care",
            "eye", "eyes", "ear", "ear_with_hearing_aid", "nose", "lips", "tongue", "tooth",
            "brain", "foot", "leg", "mechanical_arm", "mechanical_leg",
            "footprints", "mouth (open_mouth)", "bust_in_silhouette", "busts_in_silhouette",
            "speaking_head",
            // people — basic
            "baby", "child", "boy", "girl",
            "adult", "man", "woman",
            "older_adult", "older_man", "older_woman",
            "bearded_person",
            "man_bald", "woman_bald",
            "man_red_haired", "woman_red_haired",
            "man_curly_haired", "woman_curly_haired",
            "man_white_haired", "woman_white_haired",
            "blond_haired_person", "blond_haired_man", "blond_haired_woman",
            // people — standing / posture
            "person_standing", "man_standing", "woman_standing",
            "person_kneeling", "man_kneeling", "woman_kneeling",
            "person_walking", "man_walking", "woman_walking",
            "person_running", "man_running", "woman_running",
            "person_bowing", "man_bowing", "woman_bowing",
            "person_facepalming", "man_facepalming", "woman_facepalming",
            "person_shrugging", "man_shrugging", "woman_shrugging",
            "person_gesturing_no", "man_gesturing_no", "woman_gesturing_no",
            "person_gesturing_ok", "man_gesturing_ok", "woman_gesturing_ok",
            "person_tipping_hand", "man_tipping_hand", "woman_tipping_hand",
            "person_raising_hand", "man_raising_hand", "woman_raising_hand",
            "person_pouting", "man_pouting", "woman_pouting",
            "person_frowning", "man_frowning", "woman_frowning",
            // people — life events
            "pregnant_woman", "breast_feeding",
            "bride_with_veil", "man_in_tuxedo",
            "prince", "princess",
            "santa", "mrs_claus",
            // people — accessibility
            "man_with_probing_cane", "woman_with_probing_cane",
            "man_in_manual_wheelchair", "woman_in_manual_wheelchair",
            "man_in_motorized_wheelchair", "woman_in_motorized_wheelchair",
            "deaf_person", "deaf_man", "deaf_woman",
            "probing_cane",
            // people — professions
            "construction_worker", "man_construction_worker", "woman_construction_worker",
            "police_officer", "man_police_officer", "woman_police_officer",
            "guard", "man_guard", "woman_guard",
            "detective", "man_detective", "woman_detective",
            "man_health_worker", "woman_health_worker",
            "man_cook", "woman_cook",
            "man_student", "woman_student",
            "man_teacher", "woman_teacher",
            "man_judge", "woman_judge",
            "man_farmer", "woman_farmer",
            "man_mechanic", "woman_mechanic",
            "man_factory_worker", "woman_factory_worker",
            "man_office_worker", "woman_office_worker",
            "man_scientist", "woman_scientist",
            "man_technologist", "woman_technologist",
            "man_artist", "woman_artist",
            "man_pilot", "woman_pilot",
            "man_astronaut", "woman_astronaut",
            "man_firefighter", "woman_firefighter",
            "man_singer", "woman_singer",
            // people — activities (gendered)
            "man_dancing", "dancer",
            "man_in_steamy_room", "woman_in_steamy_room", "person_in_steamy_room",
            "man_in_lotus_position", "woman_in_lotus_position", "person_in_lotus_position",
            "man_getting_face_massage", "woman_getting_face_massage", "person_getting_massage",
            "man_getting_haircut", "woman_getting_haircut", "person_getting_haircut",
            "person_climbing", "man_climbing", "woman_climbing",
            "person_doing_cartwheel", "man_cartwheeling", "woman_cartwheeling",
            "person_juggling", "man_juggling", "woman_juggling",
            "person_golfing", "man_golfing", "woman_golfing",
            "person_lifting_weights", "man_lifting_weights", "woman_lifting_weights",
            "person_biking", "man_biking", "woman_biking",
            "person_mountain_biking", "man_mountain_biking", "woman_mountain_biking",
            "person_surfing", "man_surfing", "woman_surfing",
            "person_swimming", "man_swimming", "woman_swimming",
            "person_rowing_boat", "man_rowing_boat", "woman_rowing_boat",
            "person_bouncing_ball", "man_bouncing_ball", "woman_bouncing_ball",
            "person_fencing",
            "person_playing_handball", "man_playing_handball", "woman_playing_handball",
            "person_playing_water_polo", "man_playing_water_polo", "woman_playing_water_polo",
            "man_with_chinese_cap", "woman_with_headscarf", "person_wearing_turban",
            "man_wearing_turban", "woman_wearing_turban",
            // people — fantasy / special
            "levitate",
            "superhero", "man_superhero", "woman_superhero",
            "supervillain", "man_supervillain", "woman_supervillain",
            "mage", "man_mage", "woman_mage",
            "fairy", "man_fairy", "woman_fairy",
            "elf", "man_elf", "woman_elf",
            "vampire", "man_vampire", "woman_vampire",
            "zombie", "man_zombie", "woman_zombie",
            "genie", "man_genie", "woman_genie",
            "mermaid", "merman", "merperson",
            "bellhop",
            // couples & families
            "couple", "couple_with_heart", "couple_with_heart_woman_man",
            "couple_mm", "couple_ww",
            "couplekiss", "kiss_woman_man", "kiss_mm", "kiss_ww",
            "two_men_holding_hands", "two_women_holding_hands", "people_holding_hands",
            "handshake",
            "family", "family_man_woman_boy",
            "family_man_boy", "family_man_boy_boy",
            "family_man_girl", "family_man_girl_boy", "family_man_girl_girl",
            "family_woman_boy", "family_woman_boy_boy",
            "family_woman_girl", "family_woman_girl_boy", "family_woman_girl_girl",
            "family_mmb", "family_mmbb", "family_mmg", "family_mmgb", "family_mmgg",
            "family_mwbb", "family_mwg", "family_mwgb", "family_mwgg",
            "family_wwb", "family_wwbb", "family_wwg", "family_wwgb", "family_wwgg",
            "people_with_bunny_ears_partying", "men_with_bunny_ears_partying", "women_with_bunny_ears_partying",
        ]),

        new("animals", "Animals & Nature",
        [
            // domestic animals
            "dog", "dog2", "cat", "cat2", "rabbit", "rabbit2",
            "hamster", "mouse", "mouse2", "rat",
            "bear", "panda_face", "koala", "teddy_bear",
            "fox", "wolf", "raccoon", "badger", "hedgehog", "chipmunk",
            // farm animals
            "pig", "pig2", "pig_nose", "cow", "cow2", "ox", "water_buffalo",
            "horse", "goat", "ram", "sheep", "rooster", "chicken",
            "turkey", "duck",
            // big cats
            "tiger", "tiger2", "lion_face", "leopard",
            // large wild animals
            "elephant", "hippopotamus", "rhino", "giraffe", "camel", "dromedary_camel",
            "kangaroo", "gorilla", "orangutan", "boar", "llama",
            // small animals
            "sloth", "otter", "skunk",
            // reptiles & amphibians
            "snake", "lizard", "crocodile", "frog", "turtle",
            // dinosaurs & fantasy
            "sauropod", "t_rex", "dragon", "dragon_face", "unicorn",
            // birds
            "bird", "eagle", "dove", "owl", "parrot",
            "flamingo", "peacock", "penguin", "swan",
            "hatched_chick", "hatching_chick", "baby_chick",
            // sea creatures
            "fish", "tropical_fish", "blowfish", "octopus",
            "dolphin", "whale", "whale2", "shark",
            "lobster", "crab", "shrimp", "squid", "oyster",
            "snail", "otter",
            // insects
            "ant", "bee", "beetle", "butterfly", "bug", "mosquito",
            "spider", "spider_web", "scorpion",
            // other animals
            "bat", "feet",
            "guide_dog", "service_dog",
            // flowers
            "rose", "wilted_rose", "sunflower", "blossom", "hibiscus",
            "cherry_blossom", "tulip", "white_flower", "bouquet",
            // plants & nature
            "seedling", "herb", "leaves", "fallen_leaf", "maple_leaf",
            "four_leaf_clover", "shamrock", "bamboo", "cactus",
            "palm_tree", "deciduous_tree", "evergreen_tree",
            "mushroom", "ear_of_rice", "shell", "chestnut",
            // weather
            "sunny", "partly_sunny", "cloud", "cloud_rain", "cloud_snow",
            "cloud_lightning", "cloud_tornado", "fog", "rainbow",
            "snowflake", "snowman", "snowman2",
            "fire", "droplet", "sweat_drops", "ocean",
            "cyclone", "thunder_cloud_rain",
            "wind_blowing_face",
            "white_sun_small_cloud", "white_sun_cloud", "white_sun_rain_cloud",
            // sky & space
            "sunny", "sun_with_face",
            "full_moon", "new_moon", "crescent_moon",
            "first_quarter_moon", "last_quarter_moon",
            "waxing_crescent_moon", "waxing_gibbous_moon",
            "waning_crescent_moon", "waning_gibbous_moon",
            "full_moon_with_face", "new_moon_with_face",
            "first_quarter_moon_with_face", "last_quarter_moon_with_face",
            "ringed_planet", "comet", "milky_way",
            "earth_africa", "earth_americas", "earth_asia",
            "night_with_stars",
            "rainbow", "foggy",
            "sunrise", "sunrise_over_mountains",
        ]),

        new("food", "Food & Drink",
        [
            // fruit
            "apple", "green_apple", "pear", "tangerine", "lemon", "banana",
            "watermelon", "grapes", "strawberry", "melon", "cherries", "peach",
            "mango", "pineapple", "coconut", "kiwi", "avocado", "blueberries",
            // vegetables
            "tomato", "eggplant", "corn", "hot_pepper", "cucumber", "carrot",
            "garlic", "onion", "potato", "sweet_potato", "broccoli",
            "leafy_green", "peanuts",
            // grains / bread
            "bread", "croissant", "french_bread", "bagel", "pretzel",
            "rice", "rice_ball", "rice_cracker", "bento", "dumpling", "dango",
            "stuffed_flatbread",
            // meat / protein
            "egg", "bacon", "cut_of_meat", "poultry_leg", "meat_on_bone",
            "fish_cake", "fried_shrimp", "sushi", "oden",
            // prepared food
            "hamburger", "hotdog", "pizza", "sandwich", "taco", "burrito",
            "spaghetti", "ramen", "curry", "stew", "falafel",
            "waffle", "pancakes", "shallow_pan_of_food",
            "salad", "bowl_with_spoon", "takeout_box", "canned_food",
            "moon_cake", "fortune_cookie", "pie",
            // sweets / snacks
            "cake", "birthday", "cupcake", "cookie", "candy", "chocolate_bar",
            "lollipop", "ice_cream", "icecream", "shaved_ice", "custard",
            "honey_pot", "doughnut", "popcorn",
            // condiments
            "salt", "butter",
            // drinks
            "coffee", "tea", "milk", "beverage_box", "mate", "baby_bottle",
            "wine_glass", "cocktail", "tropical_drink", "beer", "beers",
            "sake", "champagne", "champagne_glass", "tumbler_glass",
            "cup_with_straw", "ice_cube",
            // kitchen / dining
            "fork_and_knife", "fork_knife_plate", "spoon", "chopsticks",
            "cooking",
        ]),

        new("travel", "Travel & Places",
        [
            // ground vehicles
            "red_car", "blue_car", "oncoming_automobile",
            "taxi", "oncoming_taxi",
            "bus", "oncoming_bus", "trolleybus", "minibus",
            "tram", "train", "train2", "monorail",
            "bullettrain_side", "bullettrain_front", "steam_locomotive",
            "light_rail", "metro", "suspension_railway",
            "mountain_railway", "railway_car", "railway_track",
            "tractor", "truck", "articulated_lorry",
            "auto_rickshaw", "bike", "motor_scooter", "motorcycle", "scooter",
            "race_car",
            "ambulance", "fire_engine",
            "police_car", "oncoming_police_car",
            "construction_site",
            // water vehicles
            "ship", "cruise_ship", "ferry", "motorboat", "sailboat", "canoe", "speedboat",
            // air vehicles
            "airplane", "airplane_small", "airplane_arriving", "airplane_departure",
            "helicopter", "rocket", "flying_saucer", "parachute",
            "aerial_tramway", "mountain_cableway",
            // infrastructure
            "traffic_light", "vertical_traffic_light", "motorway",
            "fuelpump", "busstop", "station",
            "baggage_claim", "left_luggage", "passport_control", "customs",
            // buildings & places
            "house", "house_with_garden", "house_abandoned", "homes",
            "school", "office", "department_store", "convenience_store",
            "factory", "hospital", "hotel", "bank",
            "church", "mosque", "synagogue", "hindu_temple", "shinto_shrine",
            "classical_building", "european_castle", "japanese_castle",
            "european_post_office", "post_office", "love_hotel",
            // landmarks & scenes
            "map", "japan", "mount_fuji", "tokyo_tower",
            "statue_of_liberty", "moyai",
            "fountain", "park", "island",
            "beach", "beach_umbrella",
            "desert", "volcano",
            "mountain", "mountain_snow",
            "camping", "tent",
            "globe_with_meridians",
            // skylines / scenes
            "cityscape", "city_dusk", "city_sunset",
            "foggy", "bridge_at_night", "rice_scene",
            "kaaba", "place_of_worship",
        ]),

        new("activities", "Activities",
        [
            // popular ball sports
            "soccer", "basketball", "football", "baseball", "tennis",
            "volleyball", "rugby_football", "softball", "ping_pong",
            "badminton", "cricket_game", "field_hockey", "lacrosse",
            "bowling", "golf", "goal",
            // combat & fitness
            "boxing_glove", "martial_arts_uniform",
            "people_wrestling", "men_wrestling", "women_wrestling",
            "person_lifting_weights", "man_lifting_weights", "woman_lifting_weights",
            "running_shirt_with_sash",
            // wheeled / board sports
            "skateboard",
            // water sports
            "diving_mask",
            // winter sports
            "ice_skate", "ski", "snowboarder", "sled", "curling_stone",
            // equestrian / extreme
            "horse_racing",
            // archery & throwing
            "bow_and_arrow", "dart", "flying_disc",
            // target & precision
            "fishing_pole_and_fish",
            // games
            "video_game", "space_invader", "joystick",
            "game_die", "slot_machine", "chess_pawn",
            "black_joker", "mahjong", "flower_playing_cards",
            "spades", "clubs", "diamonds", "hearts",
            "jigsaw", "kite", "yo_yo", "crystal_ball",
            "8ball",
            // music
            "musical_note", "notes", "musical_score",
            "microphone", "microphone2", "guitar", "musical_keyboard",
            "saxophone", "violin", "trumpet", "banjo", "drum",
            // arts & performance
            "art", "paintbrush", "performing_arts", "clapper",
            "film_frames", "cinema",
            // celebration & events
            "tada", "confetti_ball", "balloon", "gift",
            "fireworks", "firecracker", "sparkler",
            "christmas_tree", "jack_o_lantern", "tanabata_tree",
            "wind_chime", "dolls",
            // awards
            "trophy", "medal", "military_medal",
            "first_place", "second_place", "third_place",
            "ticket", "tickets",
            // circus
            "circus_tent", "carousel_horse",
            "ferris_wheel", "roller_coaster",
            // wedding / occasion
            "wedding",
        ]),

        new("objects", "Objects",
        [
            // technology
            "computer", "desktop", "iphone", "keyboard", "trackball",
            "mouse_three_button", "printer", "fax",
            "telephone", "telephone_receiver", "pager",
            "tv", "video_camera", "camera", "camera_with_flash", "movie_camera",
            "projector", "vhs", "cd", "dvd", "floppy_disk", "minidisc",
            "battery", "electric_plug", "headphones",
            "joystick", "radio", "satellite", "satellite_orbital",
            // office / writing
            "file_folder", "open_file_folder", "card_index", "card_box",
            "file_cabinet", "clipboard", "notebook",
            "notebook_with_decorative_cover", "notepad_spiral",
            "ledger", "scroll", "bookmark", "bookmark_tabs",
            "book", "books", "closed_book",
            "blue_book", "green_book", "orange_book",
            "straight_ruler", "triangular_ruler", "scissors",
            "pushpin", "round_pushpin", "paperclip", "paperclips",
            "pen_fountain", "pen_ballpoint", "pencil", "pencil2",
            "black_nib", "crayon", "label", "dividers",
            // mail
            "envelope", "envelope_with_arrow", "incoming_envelope", "e_mail",
            "mailbox", "mailbox_with_mail", "mailbox_with_no_mail", "mailbox_closed",
            "inbox_tray", "outbox_tray", "package", "postbox", "postal_horn",
            "red_envelope",
            // money
            "moneybag", "credit_card", "receipt",
            // tools & hardware
            "hammer", "wrench", "nut_and_bolt", "gear", "toolbox", "tools",
            "hammer_pick", "axe", "pick", "dagger", "knife",
            "shield", "chains", "compression", "link",
            "lock", "lock_with_ink_pen", "unlock",
            "key", "key2",
            // household
            "door", "bed", "couch", "chair",
            "bath", "bathtub", "shower", "toilet",
            "wastebasket", "broom", "sponge", "soap",
            "basket", "roll_of_paper", "safety_pin", "thread", "yarn",
            "razor", "safety_vest",
            // lighting & time
            "candle", "diya_lamp", "izakaya_lantern", "flashlight", "bulb",
            "alarm_clock", "clock", "hourglass", "hourglass_flowing_sand",
            "stopwatch", "watch", "timer",
            "clock1", "clock130", "clock2", "clock230", "clock3", "clock330",
            "clock4", "clock430", "clock5", "clock530", "clock6", "clock630",
            "clock7", "clock730", "clock8", "clock830", "clock9", "clock930",
            "clock10", "clock1030", "clock11", "clock1130", "clock12", "clock1230",
            // audio
            "bell", "no_bell", "loudspeaker", "speaker", "mega", "mute",
            "sound", "loud_sound",
            // clothing & accessories
            "shirt", "jeans", "socks", "kimono", "sari",
            "bikini", "dress", "one_piece_swimsuit", "briefs", "shorts",
            "ballet_shoes", "athletic_shoe", "high_heel", "sandal",
            "boot", "hiking_boot", "gloves", "coat", "scarf", "necktie",
            "lab_coat", "goggles", "tophat", "billed_cap", "mortar_board",
            "crown", "ring", "lipstick", "nail_care",
            "handbag", "purse", "pouch", "luggage", "briefcase",
            "school_satchel", "shopping_bags", "shopping_cart",
            "backpack", "womans_clothes", "womans_hat", "womans_flat_shoe",
            "mans_shoe",
            // medical
            "syringe", "pill", "stethoscope", "adhesive_bandage",
            "drop_of_blood", "manual_wheelchair", "motorized_wheelchair",
            // science
            "alembic", "microscope", "test_tube", "petri_dish",
            "dna", "telescope", "magnet", "thermometer",
            // household misc
            "mag", "mag_right", "bomb", "gun",
            "coffin", "urn", "amphora", "moyai",
            "prayer_beads", "nazar_amulet",
            "oil", "abacus",
            "rotating_light",
            "level_slider", "control_knobs",
            "joystick", "frame_photo",
            "bar_chart",
            "map", "compass",
            "telescope", "satellite_orbital",
            "iphone", "calling", "mobile_phone_off",
            "hole", "gem",
            "trident",
            "izakaya_lantern", "wind_chime",
            "bricks", "barber",
            "moyai",
            "squeeze_bottle", "sponge", "soap",
        ]),

        new("symbols", "Symbols",
        [
            // media controls
            "arrow_forward", "arrow_backward",
            "fast_forward", "rewind",
            "play_pause", "pause_button", "stop_button", "record_button", "eject",
            "track_next", "track_previous",
            "repeat", "repeat_one", "twisted_rightwards_arrows",
            // arrows
            "arrow_up", "arrow_down", "arrow_left", "arrow_right",
            "arrow_up_down", "left_right_arrow",
            "arrow_up_small", "arrow_down_small",
            "arrow_double_up", "arrow_double_down",
            "arrow_upper_left", "arrow_upper_right",
            "arrow_lower_left", "arrow_lower_right",
            "arrows_clockwise", "arrows_counterclockwise",
            "arrow_heading_up", "arrow_heading_down",
            "arrow_right_hook", "leftwards_arrow_with_hook",
            "back", "end", "on", "soon", "top", "up",
            "loop", "curly_loop",
            // numbers
            "zero", "one", "two", "three", "four", "five",
            "six", "seven", "eight", "nine", "keycap_ten",
            "1234", "hash", "asterisk",
            "100",
            // letters / tags
            "a", "b", "m", "o", "o2",
            "cl", "cool", "free", "id", "ng", "ok", "new", "vs",
            "sos", "wc", "sa",
            "up", "on", "back", "end", "soon", "top",
            // Japanese / CJK
            "u5272", "u5408", "u55b6", "u6307", "u6708", "u6709",
            "u6e80", "u7121", "u7533", "u7981", "u7a7a",
            "koko", "ideograph_advantage", "secret", "congratulations",
            // zodiac
            "aries", "taurus", "gemini", "cancer", "leo", "virgo",
            "libra", "scorpius", "sagittarius", "capricorn", "aquarius",
            "pisces", "ophiuchus",
            // religious / cultural
            "cross", "orthodox_cross", "star_of_david", "star_and_crescent",
            "wheel_of_dharma", "yin_yang", "om_symbol", "menorah",
            "six_pointed_star", "fleur_de_lis", "peace",
            "place_of_worship",
            // signs / prohibitions
            "no_entry", "no_entry_sign", "warning", "radioactive", "biohazard",
            "children_crossing", "no_smoking", "no_bicycles", "no_pedestrians",
            "do_not_litter", "non_potable_water", "potable_water",
            "put_litter_in_its_place", "recycle",
            "baby_symbol", "restroom", "mens", "womens", "underage",
            "parking", "atm", "sos",
            "signal_strength", "vibration_mode", "mobile_phone_off",
            "information_source", "name_badge",
            "baggage_claim", "left_luggage", "passport_control", "customs",
            "construction",
            // math / marks
            "heavy_plus_sign", "heavy_minus_sign",
            "heavy_multiplication_x", "heavy_division_sign",
            "infinity", "heavy_check_mark", "negative_squared_cross_mark",
            "white_check_mark", "heavy_dollar_sign",
            "currency_exchange", "dollar", "yen", "euro", "pound",
            "money_with_wings",
            "bangbang", "interrobang", "exclamation", "question",
            "grey_exclamation", "grey_question",
            "wavy_dash", "part_alternation_mark",
            // geometric
            "red_circle", "orange_circle", "yellow_circle", "green_circle",
            "blue_circle", "purple_circle", "brown_circle", "white_circle",
            "black_circle",
            "red_square", "orange_square", "yellow_square", "green_square",
            "blue_square", "purple_square", "brown_square",
            "white_large_square", "black_large_square",
            "white_medium_square", "black_medium_square",
            "white_medium_small_square", "black_medium_small_square",
            "white_small_square", "black_small_square",
            "white_square_button", "black_square_button",
            "large_blue_diamond", "large_orange_diamond",
            "small_blue_diamond", "small_orange_diamond",
            "small_red_triangle", "small_red_triangle_down",
            "diamond_shape_with_a_dot_inside",
            // stars
            "star", "star2", "stars", "sparkles", "sparkle",
            "eight_pointed_black_star", "eight_spoked_asterisk",
            "dizzy",
            // other symbols
            "atom", "symbols",
            "radio_button", "ballot_box", "ballot_box_with_check",
            "beginner", "eye_in_speech_bubble",
            "high_brightness", "low_brightness",
            "male_sign", "female_sign",
            "medical_symbol", "scales",
            "recycle", "wheel_of_dharma",
            "rosette", "reminder_ribbon", "ribbon",
            "fleur_de_lis", "trident",
            "om_symbol", "yin_yang",
            "chart", "chart_with_upwards_trend", "chart_with_downwards_trend",
            "bar_chart",
            "date", "calendar", "calendar_spiral",
            "fast_forward", "rewind",
        ]),

        new("flags", "Flags",
        [
            // common regional + special
            "flag_us", "flag_gb", "flag_de", "flag_fr", "flag_jp",
            "flag_cn", "flag_ru", "flag_es", "flag_br", "flag_in",
            "flag_au", "flag_ca", "flag_it", "flag_kr", "flag_nl",
            "flag_pl", "flag_se", "flag_no", "flag_fi", "flag_dk",
            "flag_be", "flag_ch", "flag_at", "flag_pt", "flag_nz",
            "flag_mx", "flag_ar", "flag_za", "flag_eg", "flag_ng",
            "flag_tr", "flag_sa", "flag_ae", "flag_il", "flag_gr",
            "flag_ua", "flag_cz", "flag_hu", "flag_ro", "flag_sk",
            "flag_bg", "flag_hr", "flag_rs", "flag_si",
            "england", "scotland", "wales",
            "rainbow_flag", "pirate_flag",
            "flags", "crossed_flags", "triangular_flag_on_post", "checkered_flag",
            "united_nations",
            // all remaining country flags alphabetically
            "flag_ac", "flag_ad", "flag_af", "flag_ag", "flag_ai",
            "flag_al", "flag_am", "flag_ao", "flag_aq", "flag_as",
            "flag_aw", "flag_ax", "flag_az", "flag_ba", "flag_bb",
            "flag_bd", "flag_bf", "flag_bh", "flag_bi", "flag_bj",
            "flag_bl", "flag_black", "flag_bm", "flag_bn", "flag_bo",
            "flag_bq", "flag_bs", "flag_bt", "flag_bv", "flag_bw",
            "flag_by", "flag_bz", "flag_cc", "flag_cd", "flag_cf",
            "flag_cg", "flag_ci", "flag_ck", "flag_cl", "flag_cm",
            "flag_co", "flag_cp", "flag_cr", "flag_cu", "flag_cv",
            "flag_cw", "flag_cx", "flag_cy", "flag_dg", "flag_dj",
            "flag_dk", "flag_dm", "flag_do", "flag_dz", "flag_ea",
            "flag_ec", "flag_ee", "flag_eh", "flag_er", "flag_et",
            "flag_eu", "flag_fj", "flag_fk", "flag_fm", "flag_fo",
            "flag_ga", "flag_gd", "flag_ge", "flag_gf", "flag_gg",
            "flag_gh", "flag_gi", "flag_gl", "flag_gm", "flag_gn",
            "flag_gp", "flag_gq", "flag_gs", "flag_gt", "flag_gu",
            "flag_gw", "flag_gy", "flag_hk", "flag_hm", "flag_hn",
            "flag_ht", "flag_ic", "flag_id", "flag_ie", "flag_im",
            "flag_io", "flag_iq", "flag_ir", "flag_is", "flag_je",
            "flag_jm", "flag_jo", "flag_ke", "flag_kg", "flag_kh",
            "flag_ki", "flag_km", "flag_kn", "flag_kp", "flag_kw",
            "flag_ky", "flag_kz", "flag_la", "flag_lb", "flag_lc",
            "flag_li", "flag_lk", "flag_lr", "flag_ls", "flag_lt",
            "flag_lu", "flag_lv", "flag_ly", "flag_ma", "flag_mc",
            "flag_md", "flag_me", "flag_mf", "flag_mg", "flag_mh",
            "flag_mk", "flag_ml", "flag_mm", "flag_mn", "flag_mo",
            "flag_mp", "flag_mq", "flag_mr", "flag_ms", "flag_mt",
            "flag_mu", "flag_mv", "flag_mw", "flag_my", "flag_mz",
            "flag_na", "flag_nc", "flag_ne", "flag_nf", "flag_ni",
            "flag_np", "flag_nr", "flag_nu", "flag_om", "flag_pa",
            "flag_pe", "flag_pf", "flag_pg", "flag_ph", "flag_pk",
            "flag_pm", "flag_pn", "flag_pr", "flag_ps", "flag_pw",
            "flag_py", "flag_qa", "flag_re", "flag_rw", "flag_sb",
            "flag_sc", "flag_sd", "flag_sg", "flag_sh", "flag_sj",
            "flag_sl", "flag_sm", "flag_sn", "flag_so", "flag_sr",
            "flag_ss", "flag_st", "flag_sv", "flag_sx", "flag_sy",
            "flag_sz", "flag_ta", "flag_tc", "flag_td", "flag_tf",
            "flag_tg", "flag_th", "flag_tj", "flag_tk", "flag_tl",
            "flag_tm", "flag_tn", "flag_to", "flag_tt", "flag_tv",
            "flag_tw", "flag_tz", "flag_ug", "flag_um", "flag_uy",
            "flag_uz", "flag_va", "flag_vc", "flag_ve", "flag_vg",
            "flag_vi", "flag_vn", "flag_vu", "flag_wf", "flag_white",
            "flag_ws", "flag_xk", "flag_ye", "flag_yt", "flag_zm", "flag_zw",
        ]),
    ];
}
