namespace AetherLove.Services.Localization;

internal static class OnboardingEn
{
    public static readonly System.Collections.Generic.Dictionary<string, string> Strings = new()
    {
        // Header / navigation (OnboardingScreen.cs)
        ["onboarding.header_welcome"] = "Welcome!",
        ["onboarding.header_how_it_works"] = "How It Works",
        ["onboarding.header_terms_of_service"] = "Terms of Service",
        ["onboarding.header_sign_in"] = "Sign In",
        ["onboarding.header_secure_messages"] = "Secure Your Messages",
        ["onboarding.header_your_profile"] = "Your Profile",
        ["onboarding.header_profile_picture"] = "Profile Picture",
        ["onboarding.header_your_photos"] = "Your Photos",
        ["onboarding.header_optional_details"] = "Optional Details",
        ["onboarding.header_match_preferences"] = "Match Preferences",
        ["onboarding.header_make_it_yours"] = "Make It Yours",
        ["onboarding.header_all_set"] = "You're All Set!",
        ["onboarding.header_default"] = "AetherLove",

        ["onboarding.back"] = "← Back",
        ["onboarding.saving"] = "Saving…",
        ["onboarding.start_swiping"] = "Start Swiping →",
        ["onboarding.finish"] = "Finish →",
        ["onboarding.retry"] = "Retry →",
        ["onboarding.next"] = "Next",
        ["onboarding.could_not_assemble"] = "Could not assemble {0}: {1}",
        ["onboarding.select_photo"] = "Select Photo",
        ["onboarding.image_files"] = "Image files",
        ["onboarding.crop_avatar"] = "Crop Avatar",
        ["onboarding.crop_main_photo"] = "Crop Main Photo",
        ["onboarding.crop_extra_photo"] = "Crop Extra Photo {0}",

        // Step 2 - How It Works
        ["onboarding.how_intro"] = "Here's how AetherLove works: from building your profile to chatting with your first match.",
        ["onboarding.how1_title"] = "Build Your Profile",
        ["onboarding.how1_body"] = "Tell us about your character: your race, server, languages, and what you're looking for. Upload a portrait photo. This is your calling card.",
        ["onboarding.how2_title"] = "Browse the Deck",
        ["onboarding.how2_body"] = "Every time you open the deck you'll see a stack of profile cards. Swipe right (or tap ♥) to express interest. Swipe left (or tap X) to pass.",
        ["onboarding.how3_title"] = "Set Your Preferences",
        ["onboarding.how3_body"] = "Choose the race, region, languages, and interests you'd like to find in a match. The more specific you are, the better the matches you'll be shown.",
        ["onboarding.how4_title"] = "Match!",
        ["onboarding.how4_body"] = "You get a Match when you and another player swipe right on each other. AetherLove sends you a notification and opens a private chat.",
        ["onboarding.how5_title"] = "Chat In-Game",
        ["onboarding.how5_body"] = "Send messages directly through the plugin, no external app needed. Your conversations are end-to-end encrypted, so not even the AetherLove developers can read your chats.",
        ["onboarding.how6_title"] = "Stay In Control",
        ["onboarding.how6_body"] = "Update your profile, adjust your preferences, or unmatch at any time from the Settings screen. AetherLove will NEVER share your full player name, location, or account information with other players.",
        ["onboarding.how_ready"] = "Ready to get started? Click Next to continue.",

        // Step 2 - Terms of Service
        ["onboarding.tos_p1"] = "AetherLove is a social matchmaking plugin for Final Fantasy XIV intended for adult users. By continuing, you confirm that you are at least 18 years of age and consent to participate in an adult social platform.",
        ["onboarding.tos_p2"] = "I understand that profile information I provide (including my display name, bio, home server, character details, and any photos I upload) may be visible to other AetherLove users. I am responsible for the accuracy of my profile and for ensuring that any photos I upload are appropriate and that I have the right to share them.",
        ["onboarding.tos_ownership"] = "The characters shown in any photos I upload must be my own. If another player's character appears in an image, I confirm that I have that player's permission to share it. I will not upload screenshots or poses of characters that are not mine without the owner's consent.",
        ["onboarding.tos_p3"] = "I agree to interact respectfully with all other users. Harassment, unsolicited explicit content, hate speech, or any form of abuse toward other users is strictly prohibited. Violation of these terms may result in removal from the platform without notice or appeal.",
        ["onboarding.tos_nsfl"] = "NSFL (\"Not Suitable For Life\") content is never permitted on AetherLove under any circumstances. This includes any image or message depicting real or simulated gore, death, graphic violence, mutilation, serious injury, animal cruelty, or self-harm, along with any other shocking or sickening material. This is entirely separate from the NSFW opt-in: marking something NSFW never makes NSFL content acceptable. We enforce a strict zero-tolerance policy. Posting NSFL content results in an immediate and permanent account ban, issued without warning and with no right to appeal.",
        ["onboarding.tos_p4"] = "I understand that AetherLove is an unofficial, community-made plugin and is not affiliated with or endorsed by Square Enix Co., Ltd. It is provided as-is, with no guarantees of availability, data security, or fitness for any purpose. The plugin developers are not responsible for the actions of other users or for any consequences arising from use of this plugin.",
        ["onboarding.tos_p5"] = "Moderation decisions (including warnings, temporary suspensions, and permanent bans) are made at the sole discretion of the AetherLove staff. Staff have the final say in all moderation matters. Decisions need not be explained or justified to the affected user, and are not subject to appeal unless explicitly stated otherwise by staff.",
        ["onboarding.tos_p6"] = "We love and enjoy Lalafell characters as much as anyone, but adult and NSFW features are not available to players whose character race is Lalafell. Because Lalafells are child-like in appearance, we make no case-by-case distinction and apply this policy uniformly to every Lalafell account. The 18+ Roleplaying option, the NSFW opt-in, and NSFW photo uploads are all disabled while your race is set to Lalafell. Attempting to bypass this restriction is grounds for account removal.",
        ["onboarding.tos_ai"] = "AI-assisted moderation: I agree that OpenAI's moderation APIs automatically review my profile text and my profile images. This helps detect content that breaks these rules and keeps AetherLove safe for everyone. I also agree that a second OpenAI model checks my profile images. It checks that the image shows my own Final Fantasy XIV character, and not fan art, an AI-generated image, or unrelated content. It also checks whether the image is SFW or NSFW. My profile text and images are sent to OpenAI for moderation only. They are never used to train OpenAI's models. I understand that AetherLove's human staff make every final moderation decision. AI alone is never responsible for a moderation action.",
        ["onboarding.tos_p7"] = "I acknowledge that these terms may be updated at any time. Continued use of AetherLove after an update constitutes acceptance of the revised terms.",
        ["onboarding.tos_read_carefully"] = "READ CAREFULLY",
        ["onboarding.tos_accepted"] = "Terms accepted. Press Next to continue.",
        ["onboarding.tos_timer"] = "Please read carefully. Agree button available in {0}s",
        ["onboarding.tos_scroll_bottom"] = "Scroll to the bottom to accept.",
        ["onboarding.tos_i_agree"] = "I Agree",

        // Step 3 - XIVAuth
        ["onboarding.auth_signin_with_xivauth"] = "Sign in with XIVAuth",
        ["onboarding.auth_intro"] = "AetherLove uses XIVAuth to verify your identity as an active Final Fantasy XIV player. No password is required: authentication is handled securely through your game client.",
        ["onboarding.auth_contacting"] = "Contacting AetherLove",
        ["onboarding.auth_dont_have_xivauth"] = "Don't have XIVAuth?",
        ["onboarding.auth_xivauth_explainer"] = "XIVAuth is a free, community-run single sign-on for Final Fantasy XIV tools. It confirms you're a real FFXIV player by linking your Lodestone character, without ever sharing your Square Enix password. Signing up takes only a minute.",
        ["onboarding.auth_create_account"] = "Create a XIVAuth account",
        ["onboarding.auth_complete_in_browser"] = "Complete sign-in in your browser",
        ["onboarding.auth_browser_opened"] = "A browser window has opened. Finish signing in with XIVAuth and return here. This step will continue automatically.",
        ["onboarding.auth_open_browser_again"] = "Open browser again",
        ["onboarding.auth_cancel"] = "Cancel",
        ["onboarding.auth_loading_profile"] = "Signed in! Loading your profile",
        ["onboarding.auth_signed_in"] = "Signed in!",
        ["onboarding.auth_welcome_back"] = "Welcome back!",
        ["onboarding.auth_welcome_back_named"] = "Welcome back, {0}!",
        ["onboarding.auth_details_loaded"] = "We've loaded your details. You can start swiping right away.",
        ["onboarding.auth_timeout"] = "Sign-in took too long. Please try again.",
        ["onboarding.auth_failed"] = "Sign-in failed.",
        ["onboarding.auth_try_again"] = "Try again",

        // Step 3a - Passphrase
        ["onboarding.pass_heading"] = "Secure your messages",
        ["onboarding.pass_intro"] = "AetherLove staff cannot read your private messages: not now, not ever. That is because we encrypt every message with a key only YOU know. Your passphrase is that key. You set it on the next screen. A passphrase works like a password, but you must remember it and save it yourself. There is no \"forgot my passphrase\" button. Write it down or store it in a password manager. Treat it like any critical password.",
        ["onboarding.pass_warning"] = "You need this passphrase again on any other computer, or on a new one. Without it, nobody can read your chats, not even you.",
        ["onboarding.pass_label"] = "Passphrase",
        ["onboarding.pass_confirm_label"] = "Confirm passphrase",
        ["onboarding.pass_err_empty"] = "Please enter a passphrase.",
        ["onboarding.pass_err_too_short"] = "Passphrase must be at least {0} characters.",
        ["onboarding.pass_err_confirm_empty"] = "Please confirm your passphrase.",
        ["onboarding.pass_err_mismatch"] = "Passphrases don't match.",
        ["onboarding.pass_ack"] = "I understand my chat history cannot be recovered if I forget this passphrase.",
        ["onboarding.pass_securing"] = "Securing your keys…",
        ["onboarding.pass_set_title"] = "Set your passphrase",
        ["onboarding.pass_show_title"] = "Save your passphrase",
        ["onboarding.pass_show_sub"] = "We show your passphrase this one time only. Copy it into a password manager, or another safe place. We can't recover it for you.",
        ["onboarding.pass_copied_ack"] = "I have copied my passphrase somewhere safe.",
        ["onboarding.pass_copy"] = "Copy",
        ["onboarding.pass_strength_too_weak"] = "Too weak",
        ["onboarding.pass_strength_weak"] = "Weak",
        ["onboarding.pass_strength_ok"] = "OK",
        ["onboarding.pass_strength_good"] = "Good",
        ["onboarding.pass_strength_strong"] = "Strong",

        // Step 4 - Profile (data labels)
        ["onboarding.region_na"] = "North America (NA)",
        ["onboarding.region_eu"] = "Europe (EU)",
        ["onboarding.region_oceania"] = "Oceania",
        ["onboarding.region_japan"] = "Japan",
        ["onboarding.race_hyur"] = "Hyur",
        ["onboarding.race_elezen"] = "Elezen",
        ["onboarding.race_lalafell"] = "Lalafell",
        ["onboarding.race_miqote"] = "Miqo'te",
        ["onboarding.race_roegadyn"] = "Roegadyn",
        ["onboarding.race_au_ra"] = "Au Ra",
        ["onboarding.race_hrothgar"] = "Hrothgar",
        ["onboarding.race_viera"] = "Viera",
        ["onboarding.gender_male"] = "Male",
        ["onboarding.gender_female"] = "Female",
        ["onboarding.gender_other"] = "Other",
        ["onboarding.content_housing"] = "Housing & decoration",
        ["onboarding.content_music_bard"] = "Music & Bard performance",
        ["onboarding.content_rp_venues"] = "Visiting Roleplaying Venues",
        ["onboarding.content_club_venues"] = "Visiting Club Venues",
        ["onboarding.content_gpose"] = "Gpose",
        ["onboarding.content_story_lore"] = "Story & Lore",
        ["onboarding.content_roulettes"] = "Roulettes",
        ["onboarding.content_regular"] = "Regular content",
        ["onboarding.content_extreme_trials"] = "Extreme Trials",
        ["onboarding.content_savage"] = "Savage raiding",
        ["onboarding.content_pvp"] = "PvP",
        ["onboarding.content_blue_mage"] = "Blue Mage",
        ["onboarding.content_triple_triad"] = "Triple Triad",
        ["onboarding.content_mahjong"] = "Mahjong",
        ["onboarding.content_treasure_hunts"] = "Treasure Hunts",
        ["onboarding.content_crafting_gathering"] = "Crafting & Gathering",
        ["onboarding.content_fishing"] = "Fishing",
        ["onboarding.content_achievement_hunting"]= "Achievement Hunting",
        ["onboarding.lf_chatting"] = "Chatting to new people",
        ["onboarding.lf_casual_buddies"] = "Casual play buddies",
        ["onboarding.lf_gpose_glamour"] = "GPose and glamour partners",
        ["onboarding.lf_romance"] = "An in-game romance",
        ["onboarding.lf_long_term"] = "A long-term in-game relationship",
        ["onboarding.lf_rp_partners"] = "Roleplaying partners",
        ["onboarding.lf_erp"] = "18+ Roleplaying (ERP)",

        // Step 4 - Profile (body)
        ["onboarding.profile_intro"] = "These fields appear on your public profile card and are used to suggest matches.",
        ["onboarding.profile_identity"] = "Identity",
        ["onboarding.profile_display_name"] = "Display Name",
        ["onboarding.profile_display_name_tip"] = "The name other users see. Use your first name or an alias.\nNo spaces allowed.",
        ["onboarding.profile_display_name_hint"] = "First name or alias, no spaces, at least 3 characters.",
        ["onboarding.profile_about_me"] = "About me",
        ["onboarding.profile_about_me_tip"] = "Write a short intro. What do you enjoy?\nWhat kind of connections are you looking for?",
        ["onboarding.profile_char_count"] = "{0} / 500 characters",
        ["onboarding.profile_preview"] = "Preview",
        ["onboarding.profile_bio_placeholder"] = "Your bio will appear here…",
        ["onboarding.profile_location"] = "Location",
        ["onboarding.profile_server_region"] = "Server Region",
        ["onboarding.profile_server_region_tip"] = "Select your Final Fantasy XIV region.\nThis helps match you with nearby players.",
        ["onboarding.profile_character"] = "Character",
        ["onboarding.profile_race"] = "Race",
        ["onboarding.profile_gender"] = "Gender",
        ["onboarding.profile_languages_speak"] = "Languages I Speak",
        ["onboarding.profile_languages_hint"] = "Select every language you are comfortable chatting in.",
        ["onboarding.profile_content_heading"] = "I Enjoy the Following Content",
        ["onboarding.profile_content_hint"] = "Select everything that applies. This appears on your profile card.",
        ["onboarding.profile_looking_for_heading"]= "I Am Looking For",
        ["onboarding.profile_looking_for_hint"] = "Select everything that applies (at least one is required). Being honest helps find better matches.",
        ["onboarding.profile_erp_enables_nsfw"] = "    Selecting this automatically enables NSFW for your profile.",
        ["onboarding.profile_nsfw_heading"] = "NSFW",
        ["onboarding.profile_nsfw_lalafell"] = "Adult and NSFW features are not available while your race is set to Lalafell. See the Terms of Service for details.",
        ["onboarding.profile_nsfw_explainer"] = "NSFW means nudity or sexual themes. Turning this on lets you match with players whose profiles have NSFW photos. Those photos stay blurred until you choose to reveal them.",
        ["onboarding.profile_nsfw_checkbox"] = "I want to see profiles with NSFW content",
        ["onboarding.profile_nsfw_learn_more"] = "What does this mean?",
        ["onboarding.profile_nsfw_locked"] = "Locked on because you selected 18+ Roleplaying (ERP). Uncheck that to change this setting.",
        ["onboarding.profile_timezone"] = "Timezone",
        ["onboarding.profile_timezone_hint"] = "Shown to potential matches so they know when you're active.",

        // Step 5 - Avatar
        ["onboarding.avatar_heading"] = "Your Profile Picture",
        ["onboarding.avatar_intro"] = "Your profile picture is shown in the chat and during matching. We require a square image that contains a picture of your FFXIV character's face.",
        ["onboarding.avatar_tip"] = "Tip: a close-up portrait G-Pose screenshot works best.",
        ["onboarding.avatar_sfw_warning"] = "Your main profile picture MUST be SFW. We can delete your account if you upload an NSFW picture.",
        ["onboarding.avatar_browse"] = "Browse…",
        ["onboarding.avatar_crop_hint"] = "The crop editor opened in a separate window.\nClick \"Use this crop\" there to confirm your avatar.",
        ["onboarding.avatar_no_image"] = "No image selected yet.",
        ["onboarding.avatar_set"] = "Profile picture set!",
        ["onboarding.avatar_change_photo"] = "Change photo",
        ["onboarding.avatar_its_a_match"] = "It's a Match!",
        ["onboarding.avatar_match_preview_caption"] = "Preview: how your avatar appears on match cards",

        // Step 5 - Image Disclaimer
        ["onboarding.disclaimer_intro"] = "AetherLove is built for Final Fantasy XIV players. Before uploading any images, please read the following guidelines carefully.",
        ["onboarding.disclaimer_moderation"] = "All uploads are subject to both automated and manual moderation.",
        ["onboarding.disclaimer_general_heading"] = "General",
        ["onboarding.disclaimer_general_body"] = "All images uploaded to AetherLove must depict your Final Fantasy XIV character. Images unrelated to Final Fantasy XIV characters will be rejected without notice.",
        ["onboarding.disclaimer_profile_images_heading"] = "Profile Images",
        ["onboarding.disclaimer_profile_images_body"] = "Images on your profile must be screenshots or G-Poses of your own Final Fantasy XIV character.",
        ["onboarding.disclaimer_not_allowed"] = "NOT ALLOWED:",
        ["onboarding.disclaimer_na_fan_art"] = "Fan art",
        ["onboarding.disclaimer_na_3d_renders"] = "Custom 3D renders",
        ["onboarding.disclaimer_na_ai"] = "AI-generated images",
        ["onboarding.disclaimer_na_real_photos"] = "Photographs of real people or places",
        ["onboarding.disclaimer_na_unrelated"] = "Any image unrelated to your FFXIV character",
        ["onboarding.disclaimer_profile_images_consent"] = "Only upload images of your own character. If another player's character appears in a shot, make sure you have their permission first. Please do not upload screenshots or poses of someone else's character without their consent.",
        ["onboarding.disclaimer_nsfw_heading"] = "NSFW Content",
        ["onboarding.disclaimer_nsfw_body1"] = "Your primary avatar and your main profile picture must be Safe For Work (SFW). Use a picture you would be happy to show a manager or a colleague.",
        ["onboarding.disclaimer_nsfw_body2"] = "Your extra profile photos are allowed to contain NSFW content. You must mark each one NSFW when you upload it. We strongly encourage you to keep as many photos SFW as you can.",
        ["onboarding.disclaimer_nsfl_heading"] = "NSFL Content: Never Allowed",
        ["onboarding.disclaimer_nsfl_body"] = "NSFL means \"Not Suitable For Life\". This content is never allowed in any image, whether you mark it SFW or NSFW. That includes real or simulated gore, death, graphic violence, mutilation, serious injury, animal cruelty, or self-harm. It also includes anything else meant to shock, disturb, or sicken. The NSFL rule is separate from the NSFW rules above. Marking a photo NSFW allows suggestive content. It never allows NSFL content.",
        ["onboarding.disclaimer_nsfl_zero_tolerance"] = "Zero tolerance: uploading NSFL content is an immediate and permanent account ban, with no warning and no appeal.",
        ["onboarding.disclaimer_ai_heading"] = "AI-Assisted Moderation",
        ["onboarding.disclaimer_ai_body"] = "OpenAI's moderation API and a second OpenAI model check every image you upload. They check that the image shows your own FFXIV character. It must not be fan art, an AI-generated image, or something unrelated. They also check whether the image is SFW or NSFW. We send your images to OpenAI for moderation only. OpenAI never uses your images to train its models. AetherLove's human staff make every final moderation decision. AI never acts against your account on its own.",
        ["onboarding.disclaimer_rules_heading"] = "What Happens If an Image Breaks the Rules?",
        ["onboarding.disclaimer_rules_body1"] = "You get a notification if one of your images breaks these guidelines. We remove that image. Your profile then goes on hold (shadowbanned) until you fix the problem.",
        ["onboarding.disclaimer_rules_body2"] = "Uploading content that is harmful, exploitative, or illegal will result in:",
        ["onboarding.disclaimer_permanent_ban"] = "A permanent account ban.",
        ["onboarding.disclaimer_continue"] = "I understand, continue",

        // Step 6 - Photos
        ["onboarding.photos_heading"] = "Profile photos",
        ["onboarding.photos_intro"] = "Add portrait photos to your profile (10:16 aspect ratio). The first slot is required; slots 2–4 are optional. For best results use images at least 480 × 768 px.",
        ["onboarding.photos_main_thumb"] = "Main",
        ["onboarding.photos_tap_slot"] = "Tap a slot above to add or manage a photo.",
        ["onboarding.photos_main_photo"] = "Main photo",
        ["onboarding.photos_extra_photo"] = "Extra photo {0}",
        ["onboarding.photos_main_sfw_warning"] = "Your main profile picture MUST be SFW. Uploading an NSFW picture is grounds for account suspension or deletion.",
        ["onboarding.photos_sfw_nsfw_question"] = "Is this picture SFW or NSFW?",
        ["onboarding.photos_decl_sfw"] = "SFW",
        ["onboarding.photos_decl_nsfw"] = "NSFW (18+)",
        ["onboarding.img_rules_title"] = "Photo rules",
        ["onboarding.img_rules_intro"] = "A few quick rules before you add photos. Please scroll through them.",
        ["onboarding.img_rules_character"] = "Photos must be your own Final Fantasy XIV character, captured in-game. No fan art, 3D renders, AI-generated images, or real-life photos.",
        ["onboarding.img_rules_sfw"] = "Keep it safe-for-work by default. If a photo has nudity or sexual themes, mark it NSFW so it stays blurred until someone reveals it.",
        ["onboarding.img_rules_illegal"] = "Never upload illegal or extreme content: real gore, anything involving minors, or hateful imagery. This is an instant, permanent ban.",
        ["onboarding.img_rules_consent"] = "By uploading, you confirm these images are yours to share. Every photo is reviewed, and anything breaking these rules is removed.",
        ["onboarding.img_scroll_hint"] = "Please scroll to the bottom of the rules",
        ["onboarding.photos_mismatch_warning"] = "We hold your photo for moderation if our system finds NSFW content you marked as SFW. You also risk account suspension.",
        ["onboarding.photos_previously_uploaded"] = "Previously uploaded.",
        ["onboarding.photos_confirmed"] = "Photo confirmed.",
        ["onboarding.photos_remove"] = "Remove",
        ["onboarding.photos_browse"] = "Browse…",
        ["onboarding.photos_crop_hint"] = "The crop editor opened in a separate window.\nClick \"Use this crop\" there to confirm the photo.",
        ["onboarding.photos_required"] = "This photo is required.",
        ["onboarding.photos_optional"] = "This photo is optional.",

        // Step 7 - Optional
        ["onboarding.expansion_none"] = "(None)",
        ["onboarding.opt_heading"] = "Tell us more about yourself",
        ["onboarding.opt_intro"] = "All fields on this page are optional. Fill in as much or as little as you like. These details appear on your profile card and help others find you.",
        ["onboarding.opt_fav_job"] = "Favourite Job",
        ["onboarding.opt_fav_job_tip"] = "The job or role you enjoy the most.\nType to filter.",
        ["onboarding.opt_fav_location"] = "Favourite Location",
        ["onboarding.opt_fav_location_tip"] = "A place in Eorzea you love to visit.\nType to filter.",
        ["onboarding.opt_location_unavailable"] = "(location data unavailable)",
        ["onboarding.opt_location_none"] = "(None)",
        ["onboarding.opt_fav_expansion"] = "Favourite Expansion",
        ["onboarding.opt_fav_expansion_tip"] = "Your all-time favourite FFXIV expansion.",
        ["onboarding.opt_music_heading"] = "Favourite song",
        ["onboarding.opt_music_tip"] = "Paste a link from Spotify, SoundCloud, Apple Music, or YouTube Music.\nThe song name is fetched automatically.",
        ["onboarding.opt_fav_spotify"] = "Spotify",
        ["onboarding.opt_fav_soundcloud"] = "SoundCloud",
        ["onboarding.opt_fav_apple"] = "Apple Music",
        ["onboarding.opt_fav_youtube"] = "YouTube Music",
        ["onboarding.opt_fav_movie"] = "Favourite Movie",
        ["onboarding.opt_fav_movie_tip"] = "Your all-time favourite film, any genre.",
        ["onboarding.opt_fav_anime"] = "Favourite Anime",
        ["onboarding.opt_fav_anime_tip"] = "Your favourite anime series or film.",
        ["onboarding.opt_fav_ff_character"] = "Favourite Final Fantasy Character",
        ["onboarding.opt_fav_ff_character_tip"] = "Any character from the Final Fantasy universe.",
        ["onboarding.opt_weekday_playtimes"] = "Weekday Playtimes (Mon–Fri)",
        ["onboarding.opt_weekday_playtimes_tip"] = "Click the hours you're typically online on weekdays.\nHover a bar to see the time.\nPlease choose your local time.",
        ["onboarding.opt_weekend_playtimes"] = "Weekend Playtimes (Sat–Sun)",
        ["onboarding.opt_weekend_playtimes_tip"] = "Click the hours you're typically online on weekends.\nHover a bar to see the time.\nPlease choose your local time.",
        ["onboarding.opt_sync_tool"] = "Sync tool used",
        ["onboarding.opt_sync_tool_tip"] = "Sync tools like Lightless or Honsefarm let matched users\nshare mod appearances automatically.",
        ["onboarding.time_am"] = "AM",
        ["onboarding.time_pm"] = "PM",

        // Step 8 - Filters
        ["onboarding.filters_intro"] = "Tell us who you'd like to match with. These preferences help us surface the right people for you. You can adjust them at any time in Settings.",
        ["onboarding.filters_heading"] = "I Wish to Match With",
        ["onboarding.filters_race"] = "Race",
        ["onboarding.filters_gender"] = "Gender",
        ["onboarding.filters_region"] = "Region",
        ["onboarding.filters_spoken_language"] = "Spoken Language",
        ["onboarding.filters_language_tip"] = "Leave all unchecked to match regardless of language spoken.",
        ["onboarding.filters_all"] = "All",
        ["onboarding.filters_none"] = "None",
        ["onboarding.filters_clear"] = "Clear",
        ["onboarding.filters_any_race"] = "  No selection (any race)",
        ["onboarding.filters_any_gender"] = "  No selection (any gender)",
        ["onboarding.filters_any_region"] = "  No selection (any region)",
        ["onboarding.filters_any_language"] = "  No selection (no language preference)",

        // Step 9 - Finished
        ["onboarding.finished_heading"] = "You're All Set!",
        ["onboarding.finished_intro"] = "Your profile has been created and your match preferences saved. You're ready to start connecting with other Final Fantasy XIV players.",
        ["onboarding.finished_verification_heading"] = "Profile Verification",
        ["onboarding.finished_verification_body"] = "Your profile will be reviewed by our moderation team within 24 hours. During this time your profile is fully active: you can browse, match, and chat right away.",
        ["onboarding.finished_verification_note"] = "We will only reach out if there is an issue with your profile or images.",
        ["onboarding.finished_swiping_heading"] = "Start Swiping",
        ["onboarding.finished_swiping_body"] = "Head to the Deck to browse profiles. Tap ♥ on someone you're interested in. When they tap ♥ back, it's a Match! A private chat opens automatically.",
        ["onboarding.finished_rejected_heading"] = "If an Image Is Rejected",
        ["onboarding.finished_rejected_body"] = "If any of your images violate our guidelines during review, you'll receive a notification. The image will be removed and you'll be asked to replace it. Your profile remains active in the meantime.",
        ["onboarding.finished_good_luck"] = "Good luck out there. AetherLove is rooting for you! ♥",

        // Step 10 - Preferences
        ["onboarding.prefs_intro"] = "Make AetherLove yours: pick a colour theme and a phone size. You can change both any time in Settings.",
        ["onboarding.prefs_theme"] = "Theme",
        ["onboarding.prefs_phone_size"] = "Phone size",

        // added after update (1.3.1)
        ["onboarding.content_ultimate_raiding"] = "Ultimate raiding",
        ["onboarding.content_deep_dungeons"] = "Deep dungeons",
        ["onboarding.content_variant_criterion"] = "Variant / Criterion dungeons",
        ["onboarding.content_field_operations"] = "Field operations (Bozja, Eureka)",
        ["onboarding.race_gender_warning"] = "Please choose your FFXIV character's race and gender, not your gender in real life!",
        ["onboarding.tos_race_gender"] = "I agree to choose the correct race and gender for my Final Fantasy XIV character during onboarding, and I understand that my main profile picture must reflect that character.",
        // two-onboarding split (added after update 1.5.1)
        ["onboarding.welcome_title"] = "Welcome to AetherLove",
        ["onboarding.welcome_intro"] = "Time to create your dating profile. It only takes a minute, and you can change everything later.",
        ["onboarding.welcome_step_profile"] = "Tell us about yourself",
        ["onboarding.welcome_step_photos"] = "Add a photo or two",
        ["onboarding.welcome_step_prefs"] = "Set who you'd like to meet",
        ["onboarding.welcome_footer"] = "Your profile is only shown to other AetherLove players.",
        ["onboarding.avatar_use_os"] = "Use my AetherOS photo",
        // dating onboarding split into focused pages (added after update 1.5.1)
        ["onboarding.hero_welcome_title"] = "Create your profile",
        ["onboarding.hero_welcome_sub"] = "A few quick steps to set up your AetherLove dating profile. You can change anything later.",
        ["onboarding.hero_name_title"] = "What's your name?",
        ["onboarding.hero_name_sub"] = "This is the name other players see on your profile.",
        ["onboarding.hero_bio_title"] = "Write a short bio",
        ["onboarding.hero_bio_sub"] = "A sentence or two about you. Optional, but it helps you stand out.",
        ["onboarding.hero_character_title"] = "Your character",
        ["onboarding.hero_character_sub"] = "Tell us about your Warrior of Light: race, gender, and home region.",
        ["onboarding.hero_languages_title"] = "Languages you speak",
        ["onboarding.hero_languages_sub"] = "Pick every language you're happy to chat in.",
        ["onboarding.hero_interests_title"] = "What do you enjoy?",
        ["onboarding.hero_interests_sub"] = "Choose the content you love in FFXIV. All optional.",
        ["onboarding.hero_lookingfor_title"] = "What are you here for?",
        ["onboarding.hero_lookingfor_sub"] = "Let others know what kind of connection you're after.",
        ["onboarding.hero_avatar_title"] = "Add a profile picture",
        ["onboarding.hero_avatar_sub"] = "A clear, safe-for-work picture of your character. It's the first thing people see.",
        ["onboarding.hero_photos_title"] = "Show yourself off",
        ["onboarding.hero_photos_sub"] = "Add up to four portrait photos of your character.",
        ["onboarding.hero_extras_title"] = "A little more about you",
        ["onboarding.hero_extras_sub"] = "All optional, but the more you share, the better your matches. Skip anything you like.",
        ["onboarding.hero_filters_title"] = "Who would you like to meet?",
        ["onboarding.hero_filters_sub"] = "Set your match preferences. You can fine-tune these any time.",
        ["onboarding.hero_done_title"] = "You're all set!",
        ["onboarding.hero_done_sub"] = "Your profile is ready. Time to start swiping.",
        ["onboarding.opt_section_favourites"] = "FFXIV favourites",
        ["onboarding.opt_section_availability"] = "When you're around",
    };
}
