namespace AetherLove.Services.Localization;

internal static class OsEn
{
    public static readonly System.Collections.Generic.Dictionary<string, string> Strings = new()
    {
        // added after update 1.5.1
        // App names
        ["os.app_clock"] = "Clock",
        ["os.app_snake"] = "Snake",
        ["os.app_doom"] = "DOOM",
        ["os.app_sudoku"] = "Sudoku",
        ["os.app_stacker"] = "Stacker",
        ["os.app_breaker"] = "Breaker",
        ["os.app_meteor"] = "Meteor Command",
        ["os.app_invaders"] = "Void Invaders",
        ["os.app_muncher"] = "Maze Muncher",
        ["os.app_camera"] = "Camera",

        // Notification shade
        ["os.notifications"] = "Notifications",
        ["os.notifications_empty"] = "No notifications",
        ["os.notifications_clear"] = "Clear all",
        ["os.notif_remove"] = "Remove",
        ["os.time_now"] = "now",
        ["os.qt_notifications"] = "Notifications",
        ["os.qt_sounds"] = "Notification sounds",
        ["os.qt_lock"] = "Lock phone position",
        ["os.qt_theme"] = "Next theme",
        ["os.qt_wallpaper"] = "Next wallpaper",

        // Home screen
        ["os.edit_done"] = "Done",
        ["os.greeting_morning"] = "Good morning",
        ["os.greeting_afternoon"] = "Good afternoon",
        ["os.greeting_evening"] = "Good evening",
        ["os.greeting_night"] = "Up late?",
        ["os.widget_eorzea"] = "Eorzea",
        ["os.widget_status"] = "Connection",
        ["os.widget_connected"] = "Connected",
        ["os.widget_offline"] = "Offline",
        ["os.widget_unread"] = "{0} unread",

        // OS settings
        ["os.group_appearance"] = "Appearance",
        ["os.group_wallpaper"] = "Homescreen & Wallpaper",
        ["os.group_home"] = "Home screen",
        ["os.group_apps"] = "App specific settings",
        ["os.group_about"] = "About",
        ["os.wallpaper_gradient"] = "Theme",
        ["os.wallpaper_custom"] = "Yours",
        ["os.wallpaper_upload"] = "Upload image…",
        ["os.wallpaper_dim"] = "Darken wallpaper",
        ["os.home_edit_hint"] = "Hold an icon on the home screen to rearrange it. Drag icons into the dock or between pages.",
        ["os.home_reset"] = "Reset layout",

        // Love settings hub after the appearance move
        ["settings.menu_language"] = "Language & Time",

        // Weatherman app
        ["os.app_weather"] = "Weather",

        // Messenger app
        ["os.app_messenger"] = "Messenger",

        // Photos app
        ["os.app_photos"] = "Photos",

        // Home screen app launcher
        ["os.add_apps"] = "Add apps",
        ["os.add_apps_title"] = "Add apps",
        ["os.add_apps_hint"] = "Bring back an app you removed, or pin another installed Dalamud plugin.",
        ["os.add_apps_none"] = "No other plugins expose a main window.",
        ["os.add_apps_add"] = "Add",
        ["os.add_apps_added"] = "Added",
        ["os.add_apps_search"] = "Search apps...",
        ["os.remove_app_title"] = "Remove app",
        ["os.remove_app_body"] = "Remove {0} from your home screen?",
        ["os.remove_app_confirm"] = "Remove",
        // added after update 1.5.1
        ["os_onboarding.header_welcome"] = "Welcome",
        ["os_onboarding.header_design"] = "Make it yours",
        ["os_onboarding.header_name"] = "Your name",
        ["os_onboarding.header_terms"] = "Terms of Service",
        ["os_onboarding.welcome_title"] = "Welcome to AetherOS",
        ["os_onboarding.welcome_body"] = "This is your phone. Let's set it up: pick a look, choose a name, and agree to the ground rules. It only takes a moment.",
        ["os_onboarding.design_title"] = "Pick a design",
        ["os_onboarding.name_title"] = "What should we call you?",
        ["os_onboarding.name_body"] = "This name is used across AetherOS. You can pick a different display name for each app later.",
        ["os_onboarding.name_hint"] = "Name",
        ["os_onboarding.terms_title"] = "The ground rules",
        ["os_onboarding.terms_agree"] = "I agree to the Terms of Service",
        ["os_onboarding.finish"] = "Finish",
        ["os_onboarding.header_signin"] = "Sign in",
        ["os_onboarding.header_passphrase"] = "Passphrase",
        ["os_onboarding.tos_1"] = "AetherOS is a fan-made plugin, provided as-is with no warranty of any kind. It may break, lose data, or stop working at any time, and it is used entirely at your own risk.",
        ["os_onboarding.tos_2"] = "AetherOS is not affiliated with, endorsed by, or sponsored by Square Enix.",
        ["os_onboarding.tos_3"] = "FINAL FANTASY and FINAL FANTASY XIV are registered trademarks of Square Enix Holdings Co., Ltd. All other trademarks are the property of their respective owners.",
        ["os_onboarding.tos_4"] = "By continuing, you accept these terms.",
        // OS account avatar (added after update 1.5.1)
        ["os_onboarding.header_avatar"] = "Avatar",
        ["os_onboarding.avatar_title"] = "Add a photo",
        ["os_onboarding.avatar_body"] = "Pick a picture for your AetherOS profile. It's optional and only you see it; you can change it any time.",
        ["os_onboarding.avatar_choose"] = "Choose photo",
        ["os_onboarding.avatar_change"] = "Change photo",
        // two-onboarding split (added after update 1.5.1)
        ["os_onboarding.header_done"] = "All set",
        ["os_onboarding.done_title"] = "You're all set!",
        ["os_onboarding.done_body"] = "Your AetherOS account is ready. Enjoy your new phone!",
        ["os_onboarding.done_start"] = "Start using the plugin",
        ["os_onboarding.design_language"] = "Language",
        // combined OS profile step (added after update 1.5.1)
        ["os_onboarding.header_profile"] = "Your profile",
        ["os_onboarding.profile_name_label"] = "Your name",
        ["os_onboarding.profile_photo_label"] = "Your photo",
        // home button tooltip (added after update 1.5.1)
        ["os.home"] = "Home",
        // settings-consolidation categories + reset-home confirm + profile edit (added after update 1.5.1)
        ["os.cat_general"] = "General",
        ["os.cat_appearance"] = "Appearance",
        ["os.cat_other"] = "Other",
        ["os.menu_general"] = "General",
        ["os.menu_appearance"] = "Phone appearance",
        ["os.menu_reset_home"] = "Reset home screen",
        ["os.reset_home_confirm_title"] = "Reset home screen?",
        ["os.reset_home_confirm_body"] = "This clears your custom icon layout and dock, restoring the default arrangement. Your apps and settings are not affected.",
        ["os.edit_profile"] = "Edit",
        // Daily Eorzean news app (added after update 1.5.1)
        ["os.app_news"] = "Daily Eorzean",
        ["os.news_notifications"] = "News notifications",
        ["os.news_tagline"] = "Est. · All the realm's news",
        ["os.news_latest"] = "Latest",
        ["os.news_more"] = "More stories",
        ["os.news_edition"] = "Edition · {0}",
        ["os.news_refresh"] = "Refresh",
        ["os.news_new"] = "New",
        // Feedback app (added after update 1.5.1)
        ["os.app_feedback"] = "Feedback",
        ["os.feedback_app_label"] = "Which app is this about?",
        ["os.feedback_general"] = "General",
        ["os.feedback_send_another"] = "Send more feedback",
        // generic share system (added after update 1.5.1)
        ["os.share_sheet_title"] = "Share to",
        // home grid + folders
        ["os.settings_home_screen"] = "Home screen",
        ["os.settings_home_grid_caption"] = "Icons rearrange automatically to fit the new grid.",
        ["os.new_folder"] = "New folder",
        ["os.folder_name_hint"] = "Folder name…",
        ["os.folder_default_name"] = "Folder",
        ["os.folder_arcade"] = "Arcade",
        ["os.folder_media"] = "Media",
        ["os.folder_edit"] = "Edit",
        ["os.folder_empty"] = "No apps yet. Drag an icon onto this folder to add it.",
        // photo filters + screenshot import
        ["os.filter_original"] = "Original",
        ["os.filter_mono"] = "Mono",
        ["os.filter_noir"] = "Noir",
        ["os.filter_sepia"] = "Sepia",
        ["os.filter_retro"] = "Retro",
        ["os.filter_cool"] = "Cool",
        ["os.filter_vivid"] = "Vivid",
        ["os.filter_fade"] = "Fade",
        ["os.filter_applying"] = "Applying…",
        ["os.screenshots_album"] = "Printscreens",
        // calendar app
        ["os.app_calendar"] = "Calendar",
        ["os.edit_filters"] = "Filters",
        ["os.edit_adjust"] = "Adjust",
        ["os.edit_brightness"] = "Brightness",
        ["os.edit_contrast"] = "Contrast",
        ["os.edit_hue"] = "Hue",
        ["os.edit_tint"] = "Tint",
        // guided OS tour
        ["os.settings_tour"] = "Take the tour",
        ["os.tour_next"] = "Next",
        ["os.tour_back"] = "Back",
        ["os.tour_skip"] = "Skip",
        ["os.tour_finish"] = "Done",
        ["os.tour_welcome_title"] = "Welcome to AetherOS",
        ["os.tour_welcome_body"] = "This is your phone: a home screen full of apps, with AetherLove as just one of them. Let's take a quick look around, it only takes a minute.",
        ["os.tour_homebtn_title"] = "Your home button",
        ["os.tour_homebtn_body"] = "You can always get back to the home screen with your home button, the one glowing at the bottom of the phone.",
        ["os.tour_pages_title"] = "Your home screen",
        ["os.tour_pages_body"] = "Your apps live on the home screen. Swipe left and right to move between pages; the highlighted dots show which page you're on.",
        ["os.tour_widgets_title"] = "The widgets page",
        ["os.tour_widgets_body"] = "We just slid over to the widgets page for you. It sits to the left of your apps and shows the clock with Eorzea time, your connection status and your latest notification.",
        ["os.tour_statusbar_title"] = "The status bar",
        ["os.tour_statusbar_body"] = "The highlighted strip at the very top shows the time, your connection to the AetherLove servers, how many notifications are waiting and the battery. A red warning icon appears there when the connection drops.",
        ["os.tour_shade_title"] = "Notifications",
        ["os.tour_shade_body"] = "Tap the top of the phone (or drag it down) to see your notifications, just like we did now. You also get quick settings and a brightness slider here. Tap a notification to open it, swipe it away to dismiss it.",
        ["os.tour_fake_notif_title"] = "Hello there!",
        ["os.tour_fake_notif_body"] = "This is what a notification looks like.",
        ["os.tour_badges_title"] = "Badges",
        ["os.tour_badges_body"] = "App icons show a little counter when something is waiting for you, like unread messages or new matches. Opening the app clears it. (Don't worry, you don't really have 67 of them.)",
        ["os.tour_edit_title"] = "Make it yours",
        ["os.tour_edit_body"] = "Click and hold an icon and everything starts to wiggle, like right now. Drag icons wherever you like: another spot, another page, or the bottom row. Tap the highlighted Done button when you're happy.",
        ["os.tour_dock_title"] = "The dock",
        ["os.tour_dock_body"] = "The bottom row stays visible on every page. It holds up to four favourites; drag icons in and out while rearranging.",
        ["os.tour_folders_title"] = "Folders",
        ["os.tour_folders_body"] = "Icons can be grouped into folders, like the example that just appeared. Make your own from the + tile, then drag icons onto it to tidy up. Tap a folder to open it, rename it or take apps back out.",
        ["os.tour_addapps_title"] = "More apps",
        ["os.tour_addapps_body"] = "The + tile at the end of your apps opens this list. Here you can create folders and even add your other Dalamud plugins to the home screen. Remove them again with the X while rearranging.",
        ["os.tour_share_title"] = "Sharing",
        ["os.tour_share_body"] = "You can share venues, hangouts and more with your matches and friends. Sharing works between the different apps: pick what to share, choose where it goes, and it arrives as a tappable card.",
        ["os.tour_look_title"] = "Looks and layout",
        ["os.tour_look_body"] = "In the highlighted Settings app you can pick a phone theme, change the wallpaper (or upload your own), resize the home grid and tweak the phone size itself.",
        ["os.tour_offline_title"] = "Offline",
        ["os.tour_offline_body"] = "You can keep using this phone even when AetherLove or any of the built-in apps are unavailable. Apps that need the servers dim slightly and get a small marker; everything else keeps working normally.",
        ["os.tour_done_title"] = "That's the tour!",
        ["os.tour_done_body"] = "You can replay it any time from Settings. Now go explore the apps, and have fun out there.",
        ["os.tour_demo_folder"] = "Example",
        ["os.photos_search_hint"] = "Search by name or location…",
        ["os.folder_eject_title"] = "Remove from folder?",
        ["os.folder_eject_body"] = "{0} will move back to your home screen.",
        ["os.tt_prev"] = "Previous",
        ["os.tt_next"] = "Next",
        ["os.tt_edit"] = "Edit",
        ["os.tt_move"] = "Move to album",
        ["os.tt_share"] = "Share",
        ["os.tt_open_folder"] = "Open folder on disk",
        ["os.share_wallpaper"] = "Wallpaper",
        ["os.profile_edit_title"] = "Edit profile",
        ["os.profile_save"] = "Save",
        // home right-click menu (added after update 2.0.0)
        ["os.home_menu_adjust"] = "Adjust icons",
        ["os.home_menu_wallpaper"] = "Change wallpaper",
        // news app tile rename (added after update 2.0.0)
        ["os.app_news_tile"] = "News",

        // battery easter egg (added after update 2.0.1)
        ["os.battery_grass_body"] = "We care about your health, don't forget to go out, hydrate and touch some grass ;-)",
        ["os.battery_grass_hint"] = "Please touch grass below to continue",
        ["os.settings_hide_battery_grass"] = "Hide the touch grass notification after empty battery",
        // levemetes (added after update 2.0.1)
        ["os.app_levemetes"] = "Levemetes",
        ["os.battery_grass_settings_hint"] = "(You can disable this joke under General in the Settings app)",

        // added after update 2.0.1
        ["os.menu_audio"] = "Audio settings",
        ["os.app_market"] = "Market",
        ["os.app_realtor"] = "Realtor",

        // added after update 2.1.3
        ["os.app_wayfinder"] = "Wayfinder",
        ["os.app_yapper"] = "Yapper",
        ["os.arcade_leaderboard"] = "Leaderboard",
        ["os.arcade_tab_weekly"] = "This week",
        ["os.arcade_tab_alltime"] = "All time",
        ["os.arcade_loading"] = "Loading...",
        ["os.arcade_empty"] = "No scores yet. Be the first!",
        ["os.arcade_error"] = "Couldn't load the leaderboard.",
        ["os.arcade_you"] = "You",
        ["os.arcade_back"] = "Back",

        // wallet app (added after update 2.2.1)
        ["os.app_wallet"] = "Wallet",

        // plappy birb (added after update 2.2.3)
        ["os.app_plappy"] = "Plappy Birb",

        // removable first-party apps (added after update 2.2.3)
        ["os.add_apps_section_removed"] = "Removed apps",
        ["os.add_apps_section_plugins"] = "Other plugins",

        // groove app (added after update 2.2.3)
        ["os.app_groove"] = "Groove",

        // store (added after update 2.2.3)
        ["os.app_store"] = "Store",
        ["os.store_preview_caption"] = "Preview only, not yet yours",
        ["os.store_preview_close"] = "Close the preview",
        ["os.store_preview_loading"] = "Loading the preview…",
        ["os.store_preview_failed"] = "Couldn't load the preview.",

        // added after update 2.2.3 (echo)
        ["os.app_echo"] = "Echo",
        // player and transport
        ["echo.play"] = "Play",
        ["echo.pause"] = "Pause",
        ["echo.mute"] = "Mute",
        ["echo.unmute"] = "Unmute",
        ["echo.skip"] = "Skip",
        ["echo.skip_tip"] = "Skip this video for everyone",
        ["echo.buffering"] = "Buffering…",
        ["echo.solo_idle"] = "Paste a link to start watching",
        ["echo.unavailable"] = "Unavailable",
        ["echo.close"] = "Close",
        // playlist
        ["echo.add"] = "Add",
        ["echo.add_hint"] = "Paste a YouTube link",
        ["echo.added_by"] = "Added by {0}",
        ["echo.added_by_unknown"] = "Added by someone who left",
        ["echo.remove"] = "Remove",
        ["echo.queue_empty"] = "Nothing queued yet",
        ["echo.playlist_full"] = "The queue is full",
        ["echo.bad_link"] = "That is not a YouTube link",
        // room
        ["echo.room_code"] = "Room code",
        ["echo.copy_code"] = "Copy code",
        ["echo.copied"] = "Copied",
        ["echo.host_only"] = "Host only",
        ["echo.host_only_hint"] = "Only the host can control playback",
        ["echo.host_only_tip"] = "The host has locked the controls",
        ["echo.kick"] = "Remove",
        ["echo.kick_confirm"] = "Remove them from the room?",
        ["echo.leave_room"] = "Leave room",
        ["echo.end_room"] = "End room",
        ["echo.end_room_confirm"] = "End the room for everyone?",
        ["echo.you"] = "{0} (you)",
        ["echo.tab_playlist"] = "Playlist",
        ["echo.tab_members"] = "Members",
        ["echo.tab_chat"] = "Chat",
        ["echo.toggle_panel"] = "Show or hide the side panel",
        ["echo.new_messages"] = "{0} new messages",
        // room ended
        ["echo.room_ended_title"] = "Room ended",
        ["echo.room_ended_owner"] = "The host closed the room",
        ["echo.room_ended_owner_left"] = "The host disconnected",
        ["echo.room_ended_empty"] = "Everybody left",
        ["echo.room_ended_moderation"] = "This room was closed by moderation",
        ["echo.kicked_title"] = "Removed from the room",
        ["echo.kicked_body"] = "You were removed from {0}",
        // runtime and errors
        ["echo.runtime_title"] = "Echo needs its player",
        ["echo.runtime_body"] = "Video playback needs a small player component. It downloads once, and after that Echo is ready to play every time you open it.",
        ["echo.runtime_install"] = "Download it",
        ["echo.installing_title"] = "Getting Echo ready",
        ["echo.install_downloading"] = "Downloading…",
        ["echo.install_verifying"] = "Verifying…",
        ["echo.install_extracting"] = "Extracting…",
        ["echo.install_failed_title"] = "Download failed",
        ["echo.reinstall"] = "Reinstall",
        ["echo.retry"] = "Try again",
        ["echo.host_failed_title"] = "The player stopped",
        ["echo.host_failed_body"] = "It could not be restarted. Please try again.",
        ["echo.protocol_title"] = "Player version mismatch",
        ["echo.protocol_body"] = "Reinstall the Echo player to continue.",
        ["echo.embed_blocked_title"] = "This video cannot be embedded",
        ["echo.embed_blocked_body"] = "Its owner does not allow playback outside YouTube.",
        ["echo.video_gone_title"] = "Video unavailable",
        ["echo.video_gone_body"] = "It was removed or made private.",
        ["echo.bad_id_title"] = "Bad link",
        ["echo.bad_id_body"] = "That video id does not look right.",
        ["echo.player_error_title"] = "Playback failed",
        ["echo.player_error_body"] = "Something went wrong loading this video.",

        // avatar rings (added after update 2.2.3)
        ["rings.section_title"] = "Avatar ring",
        ["rings.picker_title"] = "Avatar ring",
        ["rings.none"] = "No ring",
        ["rings.none_owned_title"] = "No rings yet",
        ["rings.none_owned_body"] = "Avatar rings are decorative frames drawn around your picture, visible to everyone. Buy them with Sparks in the Store.",
        ["rings.open_store"] = "Open the Store",
        ["rings.preview_hint"] = "Everyone sees your ring wherever your picture shows.",

        // aetherling (added after update 2.2.3)
        ["os.app_aetherling"] = "???",

        // echo playback settings (added after update 2.2.3)
        ["echo.settings_tip"] = "Playback settings",
        ["echo.settings_quality"] = "Video quality",
        ["echo.quality_auto"] = "Auto",
        ["echo.quality_720"] = "720p",
        ["echo.quality_1080"] = "1080p",
        ["echo.settings_captions"] = "Subtitles",
        ["echo.settings_autoplay"] = "Play the next video automatically",
    };
}
