namespace AetherLove.Services.Localization;

internal static class ChatDe
{
    public static readonly System.Collections.Generic.Dictionary<string, string> Strings = new()
    {
        // Chat
        ["chat.no_conversation_selected"] = "Kein Gespräch ausgewählt.",
        ["chat.unreadable_message"] = "[unlesbare Nachricht]",
        ["chat.report_submitted_toast"] = "Meldung eingereicht. Unser Moderationsteam wird sie prüfen.",
        ["chat.view_profile"] = "Profil ansehen",
        ["chat.back_to_matches"] = "Zurück zu den Matches",
        ["chat.menu_open_profile"] = "Profil öffnen",
        ["chat.menu_copy_message"] = "Nachricht kopieren",
        ["chat.menu_pin"] = "Chat anheften",
        ["chat.menu_unpin"] = "Chat lösen",
        ["chat.menu_unmatch"] = "Match auflösen",
        ["chat.menu_block"] = "Blockieren",
        ["chat.menu_report_user"] = "Nutzer melden",
        ["chat.unmatch_title"] = "Match auflösen",
        ["chat.unmatch_body"] = "Wenn du das Match mit diesem Spieler auflöst, wird der Chat für beide Personen ausgeblendet. Wenn ihr euch später erneut matcht, erscheint euer Verlauf wieder.",
        ["chat.unmatch_confirm"] = "Match auflösen",
        ["chat.block_title"] = "Nutzer blockieren",
        ["chat.block_body"] = "Wenn du jemanden blockierst, wird der Chat für euch beide ausgeblendet. Diese Person erscheint dann nicht mehr in deinen Matches.",
        ["chat.block_confirm"] = "Blockieren",
        ["chat.cancel"] = "Abbrechen",
        ["chat.loading_messages"] = "Nachrichten werden geladen…",
        ["chat.e2e_self_broken"] = "Die Verschlüsselung für dieses Profil ist auf diesem Gerät noch nicht eingerichtet, daher können hier keine Nachrichten gesendet oder gelesen werden.",
        ["chat.e2e_setup_button"] = "Verschlüsselung einrichten",
        ["chat.seen_suffix"] = " · gesehen",
        ["chat.send"] = "Senden",
        ["chat.emoji_button"] = ":)",
        ["chat.system_notice_line1"] = "Dies ist ein privater Chat zwischen dir und {0}. Dieser Chat ist Ende-zu-Ende-verschlüsselt. Das AetherLove-Team kann deine Nachrichten nicht lesen. Über das Menü oben rechts kannst du das Match auflösen, blockieren oder melden.",
        ["chat.system_notice_line2"] = "Denk daran: {0} kennt deinen vollständigen Namen oder deinen Standort nicht, bis du sie mit ihm teilst. Achte auf deine eigene Privatsphäre und teile nur mehr, wenn du bereit bist.",
        ["chat.i_understand"] = "Ich verstehe",
        ["chat.report_title"] = "Nutzer melden",
        ["chat.report_reason_prompt"] = "Bitte beschreibe den Grund für deine Meldung:",
        ["chat.report_agree"] = "Ich stimme zu, eine Meldung gegen {0} einzureichen",
        ["chat.report_agree_contents"] = "Ich stimme zu, den Inhalt dieses Gesprächs an das AetherLove-Team zu senden",
        ["chat.submitting"] = "Wird eingereicht…",
        ["chat.submit"] = "Einreichen",

        // Verify encryption
        ["verify.title"] = "Verschlüsselung überprüfen",
        ["verify.intro"] = "AetherLove verschlüsselt diesen Chat Ende-zu-Ende: Nur du und {0} könnt ihn lesen, nicht einmal unser Team. Das gewebte Muster unten wird aus euren beiden Verschlüsselungsschlüsseln erzeugt.",
        ["verify.unavailable"] = "Die Überprüfung ist noch nicht bereit. Sie steht zur Verfügung, sobald ihr beide die Verschlüsselung eingerichtet und die Schlüssel ausgetauscht habt.",
        ["verify.how"] = "Vergleiche dieses Muster und diesen Code mit {0} per Sprachchat oder persönlich. Stimmen sie überein, hört niemand euren Chat mit. Stimmen sie nicht überein, teile nichts Sensibles mehr und kontaktiere den Support.",
        ["verify.your_key"] = "Dein öffentlicher Schlüssel",
        ["verify.their_key"] = "Öffentlicher Schlüssel von {0}",
        ["verify.keys_explain"] = "Öffentliche Schlüssel können gefahrlos geteilt werden; so erkennen sich eure Apps gegenseitig. Die zugehörigen privaten Schlüssel verlassen niemals eure Geräte, daher kann kein Server (auch unserer nicht) eure Nachrichten lesen.",
        ["verify.back"] = "Zurück zum Chat",

        // ChatListScreen
        ["chat.preview_me_prefix"] = "Ich: ",
        ["chat.preview_venue"] = "Hat eine Venue geteilt",
        ["chat.matches_title"] = "Matches",
        ["chat.show_search"] = "Suche anzeigen",
        ["chat.hide_search"] = "Suche ausblenden",
        ["chat.search_hint"] = "Name oder Nachricht",
        ["chat.searching"] = "Suche läuft…",
        ["chat.search_no_results"] = "Keine Treffer gefunden",
        ["chat.matches_load_error"] = "Matches konnten nicht geladen werden: {0}",
        ["chat.connectivity_error"] = "Wir konnten den AetherLove-Server nicht erreichen. Versuche es bitte erneut oder schau auf Discord nach dem Serverstatus.",
        ["chat.empty_state"] = "Du hast noch keine Matches, aber das ändert sich bald. Wische weiter!",
        ["chat.new_match"] = "neues Match",
        ["chat.say_hi"] = "Ihr habt gematcht, sag Hallo!",
        ["chat.time_ago_minutes"] = "vor {0} Min.",
        ["chat.time_ago_hours"] = "vor {0} Std.",
        ["chat.time_ago_days"] = "vor {0} T.",

        // added after update (1.3.1)
        ["chat.you"] = "Du",
        ["chat.reply"] = "Antworten",
        ["chat.pin_message"] = "Nachricht anheften",
        ["chat.unpin_message"] = "Nachricht lösen",
        ["chat.pinned_messages"] = "Angeheftete Nachrichten",
        ["chat.pinned_messages_menu"] = "Angeheftete Nachrichten ({0})",
        ["chat.quote_unavailable"] = "(Originalnachricht nicht verfügbar)",
        ["chat.quote_generic"] = "(Nachricht)",
        ["chat.replying_to"] = "Antwort an {0}",
        ["chat.reaction_remove_hint"] = "zum Entfernen klicken",
        ["chat.jump"] = "Springen",
        ["chat.unpin"] = "Lösen",

        // added after update 1.4.3
        ["chat.menu_search"] = "Nachrichten durchsuchen",
        ["chat.search_messages_hint"] = "Diesen Chat durchsuchen...",
        ["chat.category_new"] = "Neue Kategorie",
        ["chat.category_edit"] = "Kategorie bearbeiten",
        ["chat.category_delete"] = "Kategorie löschen",
        ["chat.category_delete_body"] = "Möchtest du {0} wirklich löschen? Die Chats darin wandern zurück in deine Match-Liste.",
        ["chat.category_delete_confirm"] = "Löschen",
        ["chat.category_name_hint"] = "Kategoriename",
        ["chat.category_create"] = "Erstellen",
        ["chat.category_save"] = "Speichern",
        ["chat.menu_move_to_category"] = "In Kategorie verschieben",
        ["chat.menu_remove_from_category"] = "Aus Kategorie entfernen",
        ["chat.category_empty"] = "Noch keine Chats in dieser Kategorie. Zieh einen Chat hierher oder wähle per Rechtsklick \"In Kategorie verschieben\".",
        ["chat.category_count"] = "Chats: {0}",
        ["chat.category_archive_default"] = "Archiv",
        ["chat.all_categorized"] = "Alle deine Chats sind in Kategorien einsortiert",

        // added after update 1.5.1
        ["chat.menu_view_blocked"] = "Blockierte anzeigen",
        ["blocked.title"] = "Blockierte Nutzer",
        ["blocked.intro_body"] = "Du kannst hier jede Person aus der Liste entsperren. Durch das Entsperren kommt das Match nicht zurück. Ihr könnt euch aber wieder im Deck sehen.",
        ["blocked.empty"] = "Du hast niemanden blockiert.",
        ["blocked.loading"] = "Lade...",
        ["blocked.since"] = "Blockiert am {0}",
        ["blocked.unblock"] = "Entsperren",
        ["blocked.confirm_title"] = "{0} entsperren?",
        ["blocked.confirm_body"] = "Es entsteht kein automatisches Match, aber ihr könnt euch wieder im Deck begegnen.",
        // generic share system (added after update 1.5.1)
        ["chat.news_card_label"] = "Neuigkeiten",
        ["chat.news_card_view"] = "Diesen Artikel lesen",
        ["chat.news_card_unavailable"] = "Dieser Artikel ist nicht mehr verfügbar",
        ["chat.preview_news"] = "Hat einen Artikel geteilt",

        // Messenger invite bridge (added after update 1.5.1)
        ["chat.menu_invite_messenger"] = "Zum Messenger einladen",
        ["chat.msgr_card_title"] = "Messenger-Einladung",
        ["chat.msgr_card_hint"] = "Tippe, um den Code zu deinen Kontakten hinzuzufügen",
        ["chat.preview_messenger"] = "Hat eine Messenger-Einladung gesendet",
        // Key reset notices (added after update 1.5.1)
        ["chat.keys_reset_peer"] = "{0} hat die E2E-Verschlüsselungsschlüssel zurückgesetzt",
        ["chat.keys_reset_you"] = "Du hast deine Verschlüsselungsschlüssel zurückgesetzt. Ältere Nachrichten kannst du nicht mehr lesen.",
        // calendar event share
        ["chat.preview_calevent"] = "Hat ein Ereignis geteilt",
        ["chat.preview_location"] = "Hat einen Standort geteilt",
        ["chat.calevent_rsvp"] = "Zusagen",
        ["chat.calevent_add"] = "Zum Kalender hinzufügen",
        // levemetes (added after update 2.0.1)
        ["chat.preview_levemete"] = "Kleinanzeige geteilt",
        ["chat.preview_market"] = "Hat einen Marktfund geteilt",
        ["chat.market_card_label"] = "Markt",
        ["chat.market_card_view"] = "Am Marktbrett ansehen",
        ["chat.leve_kind_looking"] = "Suche",
        ["chat.leve_kind_offering"] = "Biete",
        ["chat.leve_cat_1"] = "Hausdekoration",
        ["chat.leve_cat_2"] = "Gposing",
        ["chat.leve_cat_3"] = "Auftragsarbeiten",
        ["chat.leve_cat_4"] = "DJs",
        ["chat.leve_cat_5"] = "Venue-Personal",
        ["chat.leve_cat_6"] = "Barden & Bands",
        ["chat.leve_cat_7"] = "Söldnerdienste",
        ["chat.leve_cat_8"] = "Handwerk & Sammeln",
        ["chat.leve_cat_9"] = "18+ Angebote",
        ["chat.leve_cat_unknown"] = "Sonstiges",
        ["chat.leve_card_view"] = "Anzeige öffnen",
        ["chat.leve_card_loading"] = "Anzeige wird geladen...",
        ["chat.leve_card_unavailable"] = "Diese Anzeige ist nicht mehr verfügbar.",
        // user notes (added after update 2.0.1)
        ["chat.menu_user_note"] = "Notiz zur Person",
        ["chat.note_hint"] = "Nur du kannst diese Notiz sehen. Sie wird auf diesem Computer gespeichert und nie irgendwohin gesendet.",
        ["chat.note_save"] = "Notiz speichern",
        ["chat.note_tooltip"] = "Deine Notiz:",
        // added after update 2.0.0.0 (message delete)
        ["chat.delete_message"] = "Nachricht löschen",
        ["chat.delete_message_body"] = "Diese Nachricht für alle löschen? An ihrer Stelle steht dann ein Hinweis, dass du sie gelöscht hast.",
        ["chat.delete_message_confirm"] = "Löschen",
        ["chat.deleted_by_author"] = "Diese Nachricht wurde vom Verfasser gelöscht.",
        // added after update 2.2.3 (echo)
        ["chat.preview_echo"] = "Hat einen Echo-Raum geteilt",
        ["chat.echo_card_label"] = "Echo-Raum",
        ["chat.echo_card_host"] = "Host: {0}",
        ["chat.echo_card_members"] = "{0} schauen zu",
        ["chat.echo_card_idle"] = "Läuft noch nichts",
        ["chat.echo_card_view"] = "Diesem Raum beitreten",
        ["chat.echo_card_loading"] = "Raum wird geladen...",
        ["chat.echo_card_unavailable"] = "Dieser Raum ist beendet",
        ["chat.party_card_title"] = "Gruppe von {0}",
        ["chat.party_card_members"] = "{0} von {1} dabei",
        ["chat.party_card_join"] = "Tippen, um beizutreten",
        ["chat.party_card_over"] = "Diese Gruppe gibt es nicht mehr",
        ["chat.party_card_loading"] = "Gruppe wird geladen...",
        // chat images and the messenger invite (added after update 2.4.0)
        ["chat.attach_selfie"] = "Selfie senden",
        ["chat.image_send_title"] = "Dieses Selfie senden?",
        ["chat.image_moderation_note"] = "Deine Nachrichten sind Ende-zu-Ende-verschlüsselt, Bilder aber nicht. Wir prüfen jedes Bild vor dem Senden. Die Person, der du es schickst, kann es melden.",
        ["chat.image_expiry_label"] = "Verschwindet nach",
        ["chat.image_expiry_hours"] = "{0} Std.",
        ["chat.image_expiry_days"] = "{0} Tg.",
        ["chat.image_expiry_supporter"] = "Länger als drei Tage ist ein Supporter-Extra.",
        ["chat.image_send"] = "Senden",
        ["chat.image_cancel"] = "Abbrechen",
        ["chat.image_loading"] = "Lädt...",
        ["chat.image_gone"] = "Dieses Bild ist weg",
        ["chat.image_view"] = "In voller Größe ansehen",
        ["chat.image_delete"] = "Dieses Bild löschen",
        ["chat.image_report"] = "Dieses Bild melden",
        ["chat.image_report_title"] = "Dieses Bild melden",
        ["chat.image_report_hint"] = "Sag uns, was daran nicht stimmt. Ein Moderator sieht das Bild und deinen Grund.",
        ["chat.image_report_send"] = "Meldung senden",
        ["chat.image_err_rejected"] = "Dieses Bild kann nicht gesendet werden.",
        ["chat.image_err_full"] = "Dein Bildspeicher ist voll. Ältere Bilder geben Platz frei, sobald sie ablaufen.",
        ["chat.image_err_large"] = "Dieses Bild ist zu groß.",
        ["chat.image_err_generic"] = "Das hat nicht geklappt. Versuch es gleich noch einmal.",
        ["chat.msgr_request_sent"] = "Messenger-Anfrage gesendet",
        ["chat.image_storage"] = "Speicher: {0} / {1} MB",
        ["chat.image_sending"] = "Wird gesendet…",
        ["chat.image_expired"] = "Bild abgelaufen",
        ["chat.image_expires"] = "noch {0} T",
        ["chat.image_viewer"] = "Bild",
        ["chat.preview_image"] = "Hat ein Bild gesendet",
        ["chat.attach_photos"] = "Fotos",
        ["chat.attach_file"] = "Aus einer Datei",
    };
}
