namespace AetherLove.Services.Localization;

internal static class OsRu
{
    public static readonly System.Collections.Generic.Dictionary<string, string> Strings = new()
    {
        // added after update 1.5.1
        // App names
        ["os.app_clock"] = "Часы",
        ["os.app_snake"] = "Змейка",
        ["os.app_doom"] = "DOOM",
        ["os.app_sudoku"] = "Sudoku",
        ["os.app_stacker"] = "Блоки",
        ["os.app_breaker"] = "Кирпичи",
        ["os.app_meteor"] = "Метеоры",
        ["os.app_invaders"] = "Захватчики",
        ["os.app_muncher"] = "Лабиринт",
        ["os.app_camera"] = "Камера",

        // Notification shade
        ["os.notifications"] = "Уведомления",
        ["os.notifications_empty"] = "Нет уведомлений",
        ["os.notifications_clear"] = "Очистить всё",
        ["os.notif_remove"] = "Убрать",
        ["os.time_now"] = "сейчас",
        ["os.qt_notifications"] = "Уведомления",
        ["os.qt_sounds"] = "Звуки уведомлений",
        ["os.qt_lock"] = "Закрепить положение телефона",
        ["os.qt_theme"] = "Следующая тема",
        ["os.qt_wallpaper"] = "Следующие обои",

        // Home screen
        ["os.greeting_morning"] = "Доброе утро",
        ["os.greeting_afternoon"] = "Добрый день",
        ["os.greeting_evening"] = "Добрый вечер",
        ["os.greeting_night"] = "Не спится?",
        ["os.widget_eorzea"] = "Эорзея",
        ["os.widget_status"] = "Подключение",
        ["os.widget_connected"] = "Подключено",
        ["os.widget_offline"] = "Не в сети",
        ["os.widget_unread"] = "Непрочитанные: {0}",

        // OS settings
        ["os.group_appearance"] = "Внешний вид",
        ["os.group_wallpaper"] = "Домашний экран и обои",
        ["os.group_home"] = "Главный экран",
        ["os.group_apps"] = "Настройки приложений",
        ["os.group_about"] = "О системе",
        ["os.wallpaper_gradient"] = "Тема",
        ["os.wallpaper_custom"] = "Свои",
        ["os.wallpaper_upload"] = "Загрузить изображение…",
        ["os.wallpaper_dim"] = "Затемнить обои",
        ["os.home_edit_hint"] = "Удерживайте значок на главном экране, чтобы переставить его. Перетаскивайте значки в док или между страницами.",
        ["os.home_reset"] = "Сбросить расположение",

        // Love settings hub after the appearance move
        ["settings.menu_language"] = "Язык и время",

        // Weatherman app
        ["os.app_weather"] = "Погода",

        // Messenger app
        ["os.app_messenger"] = "Messenger",

        // Photos app
        ["os.app_photos"] = "Фото",

        // Home screen app launcher
        ["os.add_apps"] = "Добавить приложения",
        ["os.add_apps_title"] = "Добавить приложения",
        ["os.add_apps_hint"] = "Верните убранное приложение или закрепите другой установленный плагин Dalamud.",
        ["os.add_apps_none"] = "Другие плагины не предоставляют главное окно.",
        ["os.add_apps_add"] = "Добавить",
        ["os.add_apps_added"] = "Добавлено",
        ["os.add_apps_search"] = "Поиск приложений...",
        ["os.remove_app_title"] = "Удалить приложение",
        ["os.remove_app_body"] = "Убрать {0} с главного экрана?",
        ["os.remove_app_confirm"] = "Убрать",
        // added after update 1.5.1
        ["os_onboarding.header_welcome"] = "Добро пожаловать",
        ["os_onboarding.header_design"] = "Настрой под себя",
        ["os_onboarding.header_name"] = "Твоё имя",
        ["os_onboarding.header_terms"] = "Условия использования",
        ["os_onboarding.welcome_title"] = "Добро пожаловать в AetherOS",
        ["os_onboarding.welcome_body"] = "Это твой телефон. Давай настроим его: выбери оформление, имя и прими основные правила. Это займёт всего минуту.",
        ["os_onboarding.design_title"] = "Выбери оформление",
        ["os_onboarding.name_title"] = "Как нам тебя называть?",
        ["os_onboarding.name_body"] = "Это имя используется во всём AetherOS. Для каждого приложения позже можно выбрать своё отображаемое имя.",
        ["os_onboarding.name_hint"] = "Имя",
        ["os_onboarding.terms_title"] = "Основные правила",
        ["os_onboarding.terms_agree"] = "Я принимаю условия использования",
        ["os_onboarding.finish"] = "Готово",
        ["os_onboarding.header_signin"] = "Вход",
        ["os_onboarding.header_passphrase"] = "Кодовая фраза",
        ["os_onboarding.tos_1"] = "Фанатский плагин AetherOS предоставляется «как есть», без каких-либо гарантий. Он может сломаться, потерять данные или перестать работать в любой момент, и вы используете его на свой страх и риск.",
        ["os_onboarding.tos_2"] = "AetherOS не связан со Square Enix и не одобрен и не спонсируется ею.",
        ["os_onboarding.tos_3"] = "FINAL FANTASY и FINAL FANTASY XIV являются зарегистрированными товарными знаками Square Enix Holdings Co., Ltd. Все прочие товарные знаки принадлежат их владельцам.",
        ["os_onboarding.tos_4"] = "Продолжая, вы принимаете эти условия.",
        // OS account avatar (added after update 1.5.1)
        ["os_onboarding.header_avatar"] = "Аватар",
        ["os_onboarding.avatar_title"] = "Добавьте фото",
        ["os_onboarding.avatar_body"] = "Выберите изображение для профиля AetherOS. Это необязательно, и его видите только вы; можно изменить в любой момент.",
        ["os_onboarding.avatar_choose"] = "Выбрать фото",
        ["os_onboarding.avatar_change"] = "Изменить фото",
        // two-onboarding split (added after update 1.5.1)
        ["os_onboarding.header_done"] = "Готово",
        ["os_onboarding.done_title"] = "Всё готово!",
        ["os_onboarding.done_body"] = "Ваш аккаунт AetherOS настроен. Пользуйтесь новым телефоном!",
        ["os_onboarding.done_start"] = "Начать пользоваться плагином",
        ["os_onboarding.design_language"] = "Язык",
        // combined OS profile step (added after update 1.5.1)
        ["os_onboarding.header_profile"] = "Ваш профиль",
        ["os_onboarding.profile_name_label"] = "Ваше имя",
        ["os_onboarding.profile_photo_label"] = "Ваше фото",
        // home button tooltip (added after update 1.5.1)
        ["os.home"] = "Домой",
        ["os.mini_open"] = "Открыть полный вид",
        ["os.mini_power"] = "Выключить телефон",
        // settings-consolidation categories + reset-home confirm + profile edit (added after update 1.5.1)
        ["os.cat_general"] = "Общие",
        ["os.cat_appearance"] = "Оформление",
        ["os.cat_other"] = "Прочее",
        ["os.menu_general"] = "Общие",
        ["os.menu_appearance"] = "Оформление телефона",
        ["os.menu_reset_home"] = "Сбросить главный экран",
        ["os.reset_home_confirm_title"] = "Сбросить главный экран?",
        ["os.reset_home_confirm_body"] = "Это удалит вашу расстановку значков и панель и восстановит расположение по умолчанию. Ваши приложения и настройки не будут затронуты.",
        ["os.edit_profile"] = "Изменить",
        // Daily Eorzean news app (added after update 1.5.1)
        ["os.app_news"] = "Эорзейский вестник",
        ["os.news_notifications"] = "Уведомления новостей",
        ["os.news_tagline"] = "Осн. · Все новости королевства",
        ["os.news_latest"] = "Свежее",
        ["os.news_more"] = "Больше новостей",
        ["os.news_edition"] = "Выпуск · {0}",
        ["os.news_refresh"] = "Обновить",
        ["os.news_new"] = "Новое",
        // Feedback app (added after update 1.5.1)
        ["os.app_feedback"] = "Отзывы",
        ["os.feedback_app_label"] = "О каком приложении отзыв?",
        ["os.feedback_general"] = "Общее",
        ["os.feedback_send_another"] = "Отправить ещё отзыв",
        // generic share system (added after update 1.5.1)
        ["os.share_sheet_title"] = "Поделиться через",
        // home grid + folders
        ["os.settings_home_screen"] = "Домашний экран",
        ["os.settings_home_grid_caption"] = "Иконки перестраиваются автоматически под новую сетку.",
        ["os.new_folder"] = "Новая папка",
        ["os.folder_create"] = "Создать",
        ["os.folder_name_hint"] = "Название папки…",
        ["os.folder_default_name"] = "Папка",
        ["os.folder_arcade"] = "Аркады",
        ["os.folder_media"] = "Медиа",
        ["os.folder_empty"] = "Пока пусто. Перетащите иконку на папку, чтобы добавить приложение.",
        // photo filters + screenshot import
        ["os.filter_original"] = "Оригинал",
        ["os.filter_mono"] = "Моно",
        ["os.filter_noir"] = "Нуар",
        ["os.filter_sepia"] = "Сепия",
        ["os.filter_retro"] = "Ретро",
        ["os.filter_cool"] = "Холодный",
        ["os.filter_vivid"] = "Яркий",
        ["os.filter_fade"] = "Выцветший",
        ["os.filter_applying"] = "Применяем…",
        ["os.screenshots_album"] = "Скриншоты",
        // calendar app
        ["os.app_calendar"] = "Календарь",
        ["os.edit_filters"] = "Фильтры",
        ["os.edit_adjust"] = "Коррекция",
        ["os.edit_brightness"] = "Яркость",
        ["os.edit_contrast"] = "Контраст",
        ["os.edit_hue"] = "Оттенок",
        ["os.edit_tint"] = "Заливка",
        // guided OS tour
        ["os.settings_tour"] = "Пройти экскурсию",
        ["os.tour_next"] = "Далее",
        ["os.tour_back"] = "Назад",
        ["os.tour_skip"] = "Пропустить",
        ["os.tour_finish"] = "Готово",
        ["os.tour_welcome_title"] = "Добро пожаловать в AetherOS",
        ["os.tour_welcome_body"] = "Это ваш телефон: домашний экран с приложениями, и AetherLove лишь одно из них. Давайте быстро осмотримся, это займёт всего минуту.",
        ["os.tour_homebtn_title"] = "Кнопка «Домой»",
        ["os.tour_homebtn_body"] = "Вернуться на домашний экран можно в любой момент с помощью кнопки «Домой», она сейчас подсвечена внизу телефона.",
        ["os.tour_pages_title"] = "Домашний экран",
        ["os.tour_pages_body"] = "Здесь живут ваши приложения, разложенные по страницам. Листайте влево и вправо, а точки показывают, где вы сейчас. Если поднести иконку к краю экрана, страница перелистнётся вместе с ней.",
        ["os.tour_widgets_title"] = "Страница виджетов",
        ["os.tour_widgets_body"] = "Мы только что пролистнули на страницу виджетов за вас. Она находится слева от приложений и показывает часы со временем Эорзеи, статус подключения и последнее уведомление.",
        ["os.tour_statusbar_title"] = "Строка состояния",
        ["os.tour_statusbar_body"] = "Подсвеченная полоса в самом верху показывает время, подключение к серверам AetherLove, число ожидающих уведомлений и заряд батареи. Если связь пропадёт, там появится красный значок.",
        ["os.tour_shade_title"] = "Уведомления",
        ["os.tour_shade_body"] = "Нажмите на верх телефона (или потяните его вниз), чтобы увидеть уведомления, как мы сделали только что. Здесь же находятся быстрые переключатели и регулятор яркости. Нажмите на уведомление, чтобы открыть его, или смахните, чтобы убрать.",
        ["os.tour_fake_notif_title"] = "Привет!",
        ["os.tour_fake_notif_body"] = "Вот так выглядит уведомление.",
        ["os.tour_badges_title"] = "Бейджи",
        ["os.tour_badges_body"] = "На иконках приложений появляется небольшой счётчик, когда вас что-то ждёт, например непрочитанные сообщения или новые пары. Он исчезает после открытия приложения. (Не волнуйтесь, на самом деле их у вас не 67.)",
        ["os.tour_dock_title"] = "Док-панель",
        ["os.tour_dock_body"] = "Нижний ряд остаётся на месте на любой странице. Там лежит то, чем пользуетесь чаще всего: перетащите иконку туда, и она будет в одном касании с любой страницы, а обратно — когда передумаете.",
        ["os.tour_folders_title"] = "Папки",
        ["os.tour_folders_body"] = "Отпустите одну иконку поверх другой, и получится папка. Нажмите, чтобы открыть, переименуйте когда угодно, а чтобы вернуть приложение на домашний экран, вытащите его за пределы окна папки. Пустая папка исчезает сама.",
        ["os.tour_addapps_title"] = "Больше приложений",
        ["os.tour_addapps_body"] = "Всё, что вы убрали, никуда не делось и лежит здесь, вместе с другими вашими плагинами Dalamud: их тоже можно держать на домашнем экране, как обычные приложения.",
        ["os.tour_share_title"] = "Делитесь",
        ["os.tour_share_body"] = "Вы можете делиться заведениями, встречами и многим другим с парами и друзьями. Делиться можно между разными приложениями: выберите, чем и куда поделиться, и контент придёт интерактивной карточкой.",
        ["os.tour_look_title"] = "Внешний вид",
        ["os.tour_look_body"] = "В подсвеченном приложении «Настройки» можно выбрать тему телефона, сменить обои (или загрузить свои), изменить размер сетки и даже самого телефона.",
        ["os.tour_offline_title"] = "Оффлайн",
        ["os.tour_offline_body"] = "Телефоном можно пользоваться, даже если AetherLove или другие встроенные приложения недоступны. Приложения, которым нужны серверы, слегка затемняются и получают пометку, а всё остальное продолжает работать как обычно.",
        ["os.tour_arrange_title"] = "Двигайте как удобно",
        ["os.tour_arrange_body"] = "Иконки перетаскиваются в любой момент, никакой режим редактирования включать не нужно. Возьмите иконку, отнесите в другую ячейку, на другую страницу или в нижний ряд и отпустите.",
        ["os.tour_tilemenu_title"] = "Правый клик по иконке",
        ["os.tour_tilemenu_body"] = "Всё остальное — в одном правом клике: положить в папку, достать обратно, отметить как просмотренное или убрать с домашнего экрана. Убрать всегда можно без сожалений: вернуть получится в любой момент.",
        ["os.tour_homemenu_title"] = "Правый клик по обоям",
        ["os.tour_homemenu_body"] = "Правый клик по свободному месту даёт остальное: добавить приложения, создать папку, отметить все новые приложения разом или сходить сменить обои.",
        ["os.tour_newapps_title"] = "Новые приложения",
        ["os.tour_newapps_body"] = "Когда обновление приносит новые приложения, их предлагают, а не высыпают на экран: вы получаете список, выбираете нужное, а остальное спокойно ждёт, пока вы за ним не придёте. Новая иконка носит небольшую отметку, пока вы её не откроете.",
        ["os.tour_done_title"] = "Вот и вся экскурсия!",
        ["os.tour_done_body"] = "Повторить её можно в любой момент из настроек. А теперь исследуйте приложения и приятного общения!",
        ["os.photos_search_hint"] = "Поиск по названию или месту…",
        ["os.tt_prev"] = "Назад",
        ["os.tt_next"] = "Вперёд",
        ["os.tt_edit"] = "Редактировать",
        ["os.tt_move"] = "Переместить в альбом",
        ["os.tt_share"] = "Поделиться",
        ["os.tt_open_folder"] = "Открыть папку на диске",
        ["os.share_wallpaper"] = "Обои",
        ["os.profile_edit_title"] = "Редактировать профиль",
        ["os.profile_save"] = "Сохранить",
        // home right-click menu (added after update 2.0.0)
        ["os.home_menu_wallpaper"] = "Сменить обои",
        // news app tile rename (added after update 2.0.0)
        ["os.app_news_tile"] = "Новости",

        // battery easter egg (added after update 2.0.1)
        ["os.battery_grass_body"] = "Нам важно ваше здоровье: не забывайте выходить на улицу, пить воду и трогать травку ;-)",
        ["os.battery_grass_hint"] = "Потрогайте травку внизу, чтобы продолжить",
        ["os.settings_hide_battery_grass"] = "Скрывать напоминание про травку при разряженной батарее",
        // levemetes (added after update 2.0.1)
        ["os.app_levemetes"] = "Levemetes",
        ["os.battery_grass_settings_hint"] = "(Эту шутку можно отключить в разделе «Общие» приложения «Настройки»)",

        // added after update 2.0.1
        ["os.menu_audio"] = "Настройки звука",
        ["os.app_market"] = "Маркет",
        ["os.app_realtor"] = "Риелтор",

        // added after update 2.1.3
        ["os.app_wayfinder"] = "Wayfinder",
        ["os.app_yapper"] = "Yapper",
        ["os.arcade_leaderboard"] = "Таблица лидеров",
        ["os.arcade_tab_weekly"] = "За неделю",
        ["os.arcade_tab_alltime"] = "За всё время",
        ["os.arcade_loading"] = "Загрузка...",
        ["os.arcade_empty"] = "Пока нет результатов. Станьте первым!",
        ["os.arcade_error"] = "Не удалось загрузить таблицу лидеров.",
        ["os.arcade_you"] = "Вы",
        ["os.arcade_back"] = "Назад",

        // wallet app (added after update 2.2.1)
        ["os.app_wallet"] = "Кошелёк",

        // plappy birb (added after update 2.2.3)
        ["os.app_plappy"] = "Плаппи",

        // removable first-party apps (added after update 2.2.3)
        ["os.add_apps_section_removed"] = "Убранные приложения",
        ["os.add_apps_section_plugins"] = "Другие плагины",

        // groove app (added after update 2.2.3)
        ["os.app_groove"] = "Groove",

        // store (added after update 2.2.3)
        ["os.app_store"] = "Магазин",
        ["os.store_preview_caption"] = "Просто примерка, пока не твоё",
        ["os.store_preview_close"] = "Закрыть примерку",
        ["os.store_preview_loading"] = "Загружаем примерку…",
        ["os.store_preview_failed"] = "Не удалось загрузить примерку.",

        // added after update 2.2.3 (echo)
        ["os.app_echo"] = "Echo",
        // player and transport
        ["echo.play"] = "Воспроизвести",
        ["echo.pause"] = "Пауза",
        ["echo.mute"] = "Выключить звук",
        ["echo.unmute"] = "Включить звук",
        ["echo.skip"] = "Пропустить",
        ["echo.skip_tip"] = "Пропустить это видео для всех",
        ["echo.buffering"] = "Буферизация…",
        ["echo.solo_idle"] = "Вставьте ссылку, чтобы начать просмотр",
        ["echo.unavailable"] = "Недоступно",
        ["echo.close"] = "Закрыть",
        // playlist
        ["echo.add"] = "Добавить",
        ["echo.add_hint"] = "Вставьте ссылку на YouTube",
        ["echo.added_by"] = "Добавлено: {0}",
        ["echo.added_by_unknown"] = "Добавлено участником, который уже вышел",
        ["echo.remove"] = "Убрать",
        ["echo.queue_empty"] = "В очереди пока пусто",
        ["echo.playlist_full"] = "Очередь заполнена",
        ["echo.bad_link"] = "Это не ссылка на YouTube",
        // room
        ["echo.room_code"] = "Код комнаты",
        ["echo.copy_code"] = "Скопировать код",
        ["echo.copied"] = "Скопировано",
        ["echo.host_only"] = "Только хост",
        ["echo.host_only_hint"] = "Управлять воспроизведением может только хост",
        ["echo.host_only_tip"] = "Хост заблокировал управление",
        ["echo.kick"] = "Исключить",
        ["echo.kick_confirm"] = "Убрать этого участника из комнаты?",
        ["echo.leave_room"] = "Покинуть комнату",
        ["echo.end_room"] = "Закрыть комнату",
        ["echo.end_room_confirm"] = "Закрыть комнату для всех?",
        ["echo.you"] = "{0} (вы)",
        ["echo.tab_playlist"] = "Плейлист",
        ["echo.tab_members"] = "Участники",
        ["echo.tab_chat"] = "Чат",
        ["echo.toggle_panel"] = "Показать или скрыть боковую панель",
        ["echo.new_messages"] = "Новых сообщений: {0}",
        // room ended
        ["echo.room_ended_title"] = "Комната закрыта",
        ["echo.room_ended_owner"] = "Хост закрыл комнату",
        ["echo.room_ended_owner_left"] = "Хост отключился",
        ["echo.room_ended_empty"] = "Все вышли",
        ["echo.room_ended_moderation"] = "Эту комнату закрыла модерация",
        ["echo.kicked_title"] = "Вас убрали из комнаты",
        ["echo.kicked_body"] = "Вас убрали из «{0}»",
        // runtime and errors
        ["echo.runtime_title"] = "Echo нужен свой плеер",
        ["echo.runtime_body"] = "Для видео нужен небольшой компонент плеера. Он скачивается один раз, а дальше Echo готов к просмотру при каждом запуске.",
        ["echo.runtime_install"] = "Скачать",
        ["echo.installing_title"] = "Готовим Echo",
        ["echo.install_downloading"] = "Скачивание…",
        ["echo.install_verifying"] = "Проверка…",
        ["echo.install_extracting"] = "Распаковка…",
        ["echo.install_failed_title"] = "Не удалось скачать",
        ["echo.reinstall"] = "Переустановить",
        ["echo.retry"] = "Повторить",
        ["echo.host_failed_title"] = "Плеер остановился",
        ["echo.host_failed_body"] = "Перезапустить его не вышло. Попробуйте ещё раз.",
        ["echo.protocol_title"] = "Версия плеера не совпадает",
        ["echo.protocol_body"] = "Переустановите плеер Echo, чтобы продолжить.",
        ["echo.embed_blocked_title"] = "Это видео нельзя встроить",
        ["echo.embed_blocked_body"] = "Владелец запретил воспроизведение за пределами YouTube.",
        ["echo.video_gone_title"] = "Видео недоступно",
        ["echo.video_gone_body"] = "Его удалили или сделали приватным.",
        ["echo.bad_id_title"] = "Неверная ссылка",
        ["echo.bad_id_body"] = "Этот идентификатор видео выглядит неправильно.",
        ["echo.player_error_title"] = "Не удалось воспроизвести",
        ["echo.player_error_body"] = "При загрузке этого видео что-то пошло не так.",

        // avatar rings (added after update 2.2.3)
        ["rings.section_title"] = "Кольцо аватара",
        ["rings.picker_title"] = "Кольцо аватара",
        ["rings.none"] = "Без кольца",
        ["rings.none_owned_title"] = "Колец пока нет",
        ["rings.none_owned_body"] = "Кольца аватара - это декоративные рамки вокруг вашего фото, которые видят все. Их можно купить за Спарки в Store.",
        ["rings.open_store"] = "Открыть Store",
        ["rings.preview_hint"] = "Ваше кольцо видят все, где бы ни показывалось ваше фото.",

        // aetherling (added after update 2.2.3)
        ["os.app_aetherling"] = "???",

        // added after update 2.3.3
        ["os.app_notes"] = "Заметки",
        ["os.app_calculator"] = "Калькулятор",
        ["os.folder_utilities"] = "Утилиты",
        ["os.app_timers"] = "Таймеры",
        ["os.app_racooner"] = "Енот",
        ["os.app_skyswarm"] = "Небесный рой",
        ["os.app_eordle"] = "Эордл",

        // echo playback settings (added after update 2.2.3)
        ["echo.settings_tip"] = "Настройки воспроизведения",
        ["echo.settings_quality"] = "Качество видео",
        ["echo.quality_auto"] = "Авто",
        ["echo.quality_720"] = "720p",
        ["echo.quality_1080"] = "1080p",
        ["echo.settings_captions"] = "Субтитры",
        ["echo.settings_autoplay"] = "Автоматически включать следующее видео",
        ["echo.settings_software_render"] = "Программный рендеринг",

        // home screen management (added after update 2.3.4)
        ["os.home_menu_add_app"] = "Добавить приложение",
        ["os.home_menu_add_folder"] = "Добавить папку",
        ["os.tile_menu_remove_app"] = "Убрать приложение",
        ["os.tile_menu_mark_seen"] = "Отметить как просмотренное",
        ["os.home_menu_mark_seen"] = "Отметить все приложения просмотренными",
        ["os.tile_menu_take_out"] = "Вынуть из папки",
        ["os.tile_menu_move_to_folder"] = "Переместить в папку",
        ["os.tile_menu_remove_folder"] = "Убрать папку",
        ["os.folder_delete_title"] = "Убрать папку",
        ["os.folder_delete_body"] = "Убрать «{0}» вместе с приложениями ({1} шт.) или оставить их и вернуть на главный экран?",
        ["os.folder_delete_remove"] = "Убрать папку и приложения",
        ["os.folder_delete_keep"] = "Оставить приложения",

        // new app offer (added after update 2.3.4)
        ["os.new_apps_title"] = "Появились новые приложения",
        ["os.new_apps_body"] = "С этим обновлением приехали новые приложения. Отметь те, что хочешь видеть на главном экране, а остальные всегда можно добавить позже через меню главного экрана.",
        ["os.new_apps_continue"] = "Продолжить",
        ["os.app_levemetes_about"] = "Объявления Эорзеи: выкладывай своё и смотри, что ищут другие.",
        ["os.app_market_about"] = "Цены с Universalis, история продаж и оповещения по предметам, за которыми следишь.",
        ["os.app_realtor_about"] = "Свободные участки на всех мирах, список обновляется, как только что-то освобождается.",
        ["os.app_wayfinder_about"] = "Ищи путевые точки по миру и получай искры за находки.",
        ["os.app_yapper_about"] = "Короткие посты и картинки, подписки, ответы и личные сообщения.",
        ["os.app_wallet_about"] = "Твои искры и все валюты персонажа вместе с их лимитами.",
        ["os.app_store_about"] = "Трать искры на темы, рамки аватара и прочие мелочи.",
        ["os.app_groove_about"] = "Пульт для всего, что играет на твоём ПК, плюс громкость самой игры.",
        ["os.app_echo_about"] = "Смотрите видео вместе с друзьями, секунда в секунду.",
        ["os.app_notes_about"] = "Заметки и списки, которые остаются только на этом компьютере.",
        ["os.app_calculator_about"] = "Графический калькулятор со всей клавиатурой.",
        ["os.app_timers_about"] = "Морская рыбалка, Кактпот и другие часы, за которыми стоит следить.",
        ["os.app_aetherling_about"] = "Никто не говорит, что это такое.",
        ["os.app_snake_about"] = "Та самая. Ешь, расти и не кусай себя.",
        ["os.app_stacker_about"] = "Складывай блоки, убирай линии и вини последнюю фигуру.",
        ["os.app_breaker_about"] = "Отбивай мяч в кирпичи, пока кирпичи не закончатся.",
        ["os.app_meteor_about"] = "Сбивай всё, что падает, пока оно не добралось до городов.",
        ["os.app_invaders_about"] = "Сверху спускаются ряды пришельцев. У тебя одна пушка.",
        ["os.app_muncher_about"] = "Очисти лабиринт, уходи от призраков и гоняйся за ними, пока получается.",
        ["os.app_plappy_about"] = "Нажимай, чтобы махать крыльями. Трубы жалости не знают.",
        ["os.app_doom_about"] = "Шутер 1993 года прямо в телефоне.",
        ["os.app_sudoku_about"] = "Девять на девять, новая сетка когда угодно.",
        ["os.app_racooner_about"] = "Лови то, что падает, и тащи добычу по норам.",
        ["os.app_skyswarm_about"] = "Лети сквозь рой столько, сколько продержишься.",
        ["os.app_eordle_about"] = "Одно эорзейское слово в день и шесть попыток.",
    };
}
