namespace AetherLove.Services.Localization;

internal static class ProfileEs
{
    public static readonly System.Collections.Generic.Dictionary<string, string> Strings = new()
    {
        ["profile.load_failed"] = "No se pudo cargar el perfil: {0}",
        ["profile.none_loaded"] = "Ningún perfil cargado.",

        ["profile.about"] = "Sobre mí",
        ["profile.flairs"] = "Distintivos",
        ["profile.looking_for"] = "Busco",
        ["profile.content_interests"] = "Preferencias de contenido",
        ["profile.info"] = "Información",
        ["profile.gender"] = "Género",
        ["profile.languages"] = "Idiomas",
        ["profile.timezone"] = "Zona horaria",
        ["profile.favourite_job"] = "Trabajo favorito",
        ["profile.favourite_location"] = "Lugar favorito",
        ["profile.favourite_expansion"] = "Expansión favorita",
        ["profile.favourite_song"] = "Canción favorita",
        ["music.fetching"] = "Obteniendo el nombre de la canción…",
        ["music.saved"] = "Enlace guardado (nombre pendiente)",
        ["music.invalid"] = "No se pudo leer ese enlace. Pega un enlace de canción de Spotify, SoundCloud, Apple Music o YouTube Music.",
        ["music.open_tooltip"] = "Haz clic para abrir",
        ["profile.favourite_movie"] = "Película favorita",
        ["profile.favourite_anime"] = "Anime favorito",
        ["profile.favourite_ff_character"] = "Personaje favorito de FF",
        ["profile.sync_tool"] = "Herramienta de sincronización",
        ["profile.weekday_playtimes"] = "Horarios de juego entre semana  (lun–vie)",
        ["profile.weekend_playtimes"] = "Horarios de juego en fin de semana  (sáb–dom)",
        ["profile.timezone_value"] = "{0} (hora actual: {1})",

        ["profile.nsfw_reveal"] = "Haz clic para mostrar la imagen NSFW",

        ["profile.back_to_chat"] = "Volver al chat",
        ["profile.back_to_swiping"] = "Volver a deslizar",

        ["profile.report_profile"] = "Denunciar perfil",
        ["profile.report_warning"] = "Las denuncias falsas o malintencionadas conllevan advertencias en tu propia cuenta, y el abuso reiterado puede dar lugar a una suspensión. Denuncia solo los perfiles que realmente infrinjan las reglas.",
        ["profile.report_prompt"] = "Dile a nuestros moderadores qué pasa con {0}:",
        ["profile.this_profile"] = "este perfil",
        ["profile.report_agree"] = "Entiendo que las denuncias falsas pueden conllevar advertencias contra mi cuenta.",
        ["profile.submitting"] = "Enviando…",
        ["profile.cancel"] = "Cancelar",
        ["profile.submit_report"] = "Enviar denuncia",
        ["profile.report_submitted"] = "Denuncia enviada",
        ["profile.report_thanks"] = "Gracias, nuestros moderadores lo revisarán. Este perfil ya no volverá a aparecer en tu mazo.",
        ["profile.closing"] = "Cerrando…",
        ["profile.closing_in"] = "Cerrando en {0} segundos",
        ["profile.close"] = "Cerrar",

        // ProfileScreen - copy profile text (viewing others only)
        ["profile.copy_text"] = "Copiar texto del perfil",
        ["profile.copy_warning_title"] = "Advertencia",
        ["profile.copy_warning_body"] = "Has copiado el texto de otra persona. Ten cuidado con los enlaces que contenga. Los sigues bajo tu propia responsabilidad.",
        ["profile.copy_warning_agree"] = "Lo entiendo y estoy de acuerdo",

        // MyProfileScreen hub: stats + menu
        ["profile.section_myprofile"] = "Mi perfil",
        ["profile.section_service"] = "Servicio",
        ["profile.menu_view"] = "Ver mi perfil",
        ["profile.menu_edit"] = "Modificar perfil",
        ["profile.menu_images"] = "Fotos de perfil",
        ["profile.stat_loves_you"] = "te quieren",
        ["profile.stat_matches"] = "Matches",
        ["profile.stat_match_rate"] = "% de match",
        ["profile.back_to_my"] = "← Volver",

        ["profile.load_profile_failed"] = "No se pudo cargar tu perfil: {0}",
        ["profile.retry"] = "Reintentar",
        ["profile.saving"] = "Guardando…",
        ["profile.saved"] = "Guardado  ✓",
        ["profile.save_changes"] = "Guardar cambios",

        ["profile.heading_character"] = "Personaje",
        ["profile.heading_location"] = "Ubicación",
        ["profile.heading_languages"] = "Idiomas que hablo",
        ["profile.heading_content"] = "Disfruto del siguiente contenido",
        ["profile.heading_looking_for"] = "Estoy buscando",
        ["profile.heading_nsfw"] = "NSFW",
        ["profile.heading_optional"] = "Opcional",
        ["profile.heading_playtime"] = "Horario de juego",
        ["profile.heading_timezone"] = "Zona horaria",
        ["profile.heading_sync_tool"] = "Herramienta de sincronización",
        ["profile.heading_match_prefs"] = "Preferencias de coincidencia",

        ["profile.display_name"] = "Nombre visible",
        ["profile.about_me"] = "Sobre mí",
        ["profile.char_count"] = "{0} / 500 caracteres",
        ["profile.preview"] = "Vista previa",
        ["profile.bio_placeholder"] = "Tu biografía aparecerá aquí…",
        ["profile.race"] = "Raza",
        ["profile.region"] = "Región",
        ["profile.languages_hint"] = "Selecciona todos los idiomas en los que te sientas cómodo chateando.",
        ["profile.content_hint"] = "Selecciona todo lo que aplique.",
        ["profile.looking_for_hint"] = "Ser sincero ayuda a encontrar mejores coincidencias.",
        ["profile.nsfw_lalafell"] = "Las funciones para adultos y NSFW no están disponibles mientras tu raza esté fijada como Lalafell. Consulta los Términos del servicio para más detalles.",
        ["profile.nsfw_explainer"] = "NSFW significa \"Not Safe For Work\" (no apto para el trabajo). El contenido NSFW tiene desnudos o temática sexual. Actívalo para ver perfiles NSFW y hacer match con ellos.",
        ["profile.nsfw_optin"] = "Perfiles NSFW: SÍ",
        ["profile.favourite_job_tooltip"] = "El trabajo o rol que más disfrutas. Escribe para filtrar.",
        ["profile.favourite_ff_character_full"] = "Personaje favorito de Final Fantasy",
        ["profile.weekday_playtimes_edit"] = "Horarios de juego entre semana (lun–vie)",
        ["profile.weekend_playtimes_edit"] = "Horarios de juego en fin de semana (sáb–dom)",
        ["profile.sync_tool_hint"] = "Las herramientas de sincronización permiten a los usuarios emparejados compartir apariencias de mods.",
        ["profile.match_prefs_body"] = "Cuéntanos con quién te gustaría coincidir. Estas preferencias ayudan a mostrarte a las personas adecuadas.",
        ["profile.all"] = "Todos",
        ["profile.none"] = "Ninguno",
        ["profile.clear"] = "Limpiar",
        ["profile.filter_any_race"] = "  Sin selección: cualquier raza",
        ["profile.filter_any_gender"] = "  Sin selección: cualquier género",
        ["profile.filter_any_region"] = "  Sin selección: cualquier región",
        ["profile.filter_any_language"] = "  Sin selección: sin preferencia de idioma",
        ["profile.spoken_language"] = "Idioma hablado",
        ["profile.spoken_language_tooltip"] = "Déjalo todo sin marcar para coincidir sin importar el idioma.",
        ["profile.load_photos_failed"] = "No se pudieron cargar tus fotos: {0}",
        ["profile.profile_picture"] = "Foto de perfil",
        ["profile.profile_picture_desc"] = "Tu foto de perfil se muestra en la lista de chats y en las tarjetas de coincidencia. Usa un retrato cuadrado en primer plano de tu personaje de FFXIV.",
        ["profile.profile_photos"] = "Fotos de perfil",
        ["profile.profile_photos_desc"] = "Añade fotos de retrato a tu perfil (relación 10:16). La primera ranura es obligatoria; las ranuras 2–4 son opcionales.",
        ["profile.declare_before_save"] = "Marca cada foto adicional como SFW o NSFW antes de guardar.",

        ["profile.new_photo_ready"] = "Foto nueva lista, aún sin guardar.",
        ["profile.change_photo"] = "Cambiar foto",
        ["profile.profile_picture_set"] = "Foto de perfil: Establecida  ✓",
        ["profile.no_profile_picture"] = "No hay foto de perfil establecida.",
        ["profile.upload_avatar"] = "Subir avatar…",

        ["profile.slot_main"] = "Principal",
        ["profile.tap_slot"] = "Toca una ranura de arriba para añadir o cambiar una foto.",
        ["profile.main_photo"] = "Foto principal",
        ["profile.extra_photo"] = "Foto adicional {0}",
        ["profile.photo_will_be_removed"] = "La foto se eliminará.",
        ["profile.undo"] = "Deshacer",
        ["profile.main_must_be_sfw"] = "Tu foto de perfil principal DEBE ser SFW. Subir una foto NSFW es motivo de suspensión o eliminación de la cuenta.",
        ["profile.sfw_or_nsfw"] = "¿Esta foto es SFW o NSFW?",
        ["profile.sfw_mismatch_warning"] = "Nuestro sistema revisa cada foto. Si marcas como SFW una foto NSFW, la retenemos para moderación. También podemos suspender tu cuenta.",
        ["profile.photo_ready"] = "Foto lista, aún sin guardar.",
        ["profile.replace"] = "Reemplazar",
        ["profile.photo_set"] = "Foto establecida  ✓",
        ["profile.currently_nsfw"] = "Actualmente: NSFW",
        ["profile.currently_sfw"] = "Actualmente: SFW",
        ["profile.remove"] = "Eliminar",
        ["profile.photo_required"] = "Esta foto es obligatoria.",
        ["profile.photo_optional"] = "Esta foto es opcional.",
        ["profile.upload_photo"] = "Subir foto…",

        ["profile.select_image"] = "Seleccionar imagen",
        ["profile.image_files_filter"] = "Archivos de imagen",
        ["profile.crop_avatar"] = "Recortar avatar",
        ["profile.crop_main_photo"] = "Recortar foto principal",
        ["profile.crop_extra_photo"] = "Recortar foto adicional {0}",

        // added after update 1.4.3
        ["profile.menu_rp"] = "Mis perfiles de rol",
        ["profile.rp_intro_title"] = "Mis perfiles de rol",
        ["profile.rp_intro"] = "Añade tus OCs de FFXIV (personajes originales) a tu perfil. Cada personaje tiene un nombre, una breve historia y una imagen opcional, y aparecerán en tu perfil para que otros los descubran.",
        ["profile.characters"] = "Personajes",
        ["profile.rp_add"] = "Añadir personaje",
        ["profile.rp_empty"] = "Aún no hay personajes. ¡Añade tu primer OC abajo!",
        ["profile.rp_limit_reached"] = "Puedes añadir hasta {0} personajes.",
        ["profile.rp_name"] = "Nombre / Título",
        ["profile.rp_bio"] = "Sobre este personaje",
        ["profile.rp_delete"] = "Eliminar",
        ["profile.rp_delete_confirm"] = "¿Eliminar de verdad?",
        ["profile.rp_move_up"] = "Subir",
        ["profile.rp_move_down"] = "Bajar",
        ["profile.rp_image"] = "Imagen",
        ["profile.rp_upload_image"] = "Subir imagen",
        ["profile.rp_replace_image"] = "Reemplazar imagen",
        ["profile.rp_remove_image"] = "Quitar imagen",
        ["profile.rp_image_ready"] = "Imagen lista para guardar",
        ["profile.rp_image_nsfw"] = "Esta imagen es NSFW",
        ["profile.rp_image_expand"] = "Ver a tamaño completo",
        ["profile.rp_image_back"] = "Volver al perfil",
        ["profile.rp_crop_image"] = "Recortar imagen del personaje",
        ["profile.rp_back"] = "Volver",
        ["profile.rp_details"] = "Detalles del personaje:",

        // added after update 1.5.1
        ["profile.slot_locked"] = "Este espacio de foto requiere una suscripción de colaborador activa. Puedes quitar la foto o volver a suscribirte para usarlo de nuevo.",
        ["profile.rp_extra_image"] = "Imagen extra {0} (colaborador)",
        ["profile.section_supporter"] = "Colaborador",
        ["profile.menu_sup_vanity"] = "Diseños de estilo",
        ["profile.menu_sup_stats"] = "Estadísticas extra",
        ["profile.sup_intro"] = "¡Gracias por apoyar AetherLove! Elige un estilo para tu nombre y si quieres mostrar la insignia de colaborador. Todos pueden verlos.",
        ["profile.sup_name_style"] = "Estilo del nombre",
        ["profile.sup_show_badge"] = "Mostrar mi estado de colaborador",
        ["profile.sup_badge_hint"] = "Desactívalo y nadie verá tu estrella ni tu insignia de colaborador. Quedan ocultas en tus perfiles, en los chats, en los hangouts y en tu propia vista previa del perfil. Tus ventajas de colaborador siguen funcionando. Esta opción se aplica a toda tu cuenta.",
        ["profile.sup_stats_intro"] = "Información exclusiva para colaboradores sobre cómo le va a tu perfil por todo el reino.",
        ["profile.sup_stat_likes_received"] = "Likes recibidos",
        ["profile.sup_stat_superlikes"] = "Superlikes recibidos",
        ["profile.sup_stat_views"] = "Visitas al perfil",
        ["profile.sup_stat_impressions"] = "Apariciones en mazos",
        ["profile.sup_stat_likes_given"] = "Likes dados",
        ["profile.sup_stat_passes_given"] = "Rechazos dados",
        ["profile.sup_stat_matches"] = "Matches",
        ["profile.sup_stat_like_rate"] = "Tu tasa de likes",
        ["profile.sup_stat_match_rate"] = "Tu tasa de match",
        ["profile.style_none"] = "Predeterminado",
        ["profile.style_crimson"] = "Carmesí",
        ["profile.style_gold"] = "Dorado",
        ["profile.style_emerald"] = "Esmeralda",
        ["profile.style_sapphire"] = "Zafiro",
        ["profile.style_violet"] = "Violeta",
        ["profile.style_rose"] = "Rosa",
        ["profile.style_rainbow"] = "Arcoíris (animado)",
        ["profile.style_shimmer"] = "Brillo dorado (animado)",
        ["profile.style_pulse"] = "Pulso rosa (animado)",

        // added after update 2.0.1
        ["profile.more_options"] = "Más opciones",
        ["profile.menu_hide"] = "Ocultar este perfil",
        ["profile.menu_report"] = "Denunciar este perfil",
        ["profile.hide_title"] = "¿Ocultar este perfil?",
        ["profile.hide_body"] = "No volverás a ver este perfil en tu mazo nunca más. Esto no se puede deshacer.",
        ["profile.hide_confirm"] = "Ocultar para siempre",
        // holiday mode (added after update 2.0.1)
        ["profile.menu_holiday"] = "Modo vacaciones",
        ["profile.holiday_toggle"] = "Modo vacaciones activado",
        ["profile.holiday_msg_label"] = "Mensaje de vacaciones",
        ["profile.holiday_msg_hint"] = "El modo vacaciones muestra un aviso de ausencia con tu mensaje a quien vea tu perfil. Tus matches también ven un indicador de ausencia en tu foto.",
        ["profile.holiday_save"] = "Guardar",
        ["profile.holiday_saved"] = "¡Guardado!",
        ["profile.holiday_active_banner"] = "MODO VACACIONES ACTIVO",
        ["profile.holiday_banner"] = "Este jugador tiene el modo vacaciones activado: {0}",
        ["profile.holiday_banner_short"] = "Este jugador tiene el modo vacaciones activado.",

        // added after update 2.4.0
        ["profile.region_min_hint"] = "Elige al menos una región.",
    };
}
