namespace AetherLove.Services.Localization;

internal static class OsFr
{
    public static readonly System.Collections.Generic.Dictionary<string, string> Strings = new()
    {
        // added after update 1.5.1
        // App names
        ["os.app_clock"] = "Horloge",
        ["os.app_snake"] = "Snake",
        ["os.app_doom"] = "DOOM",
        ["os.app_sudoku"] = "Sudoku",
        ["os.app_stacker"] = "Stacker",
        ["os.app_breaker"] = "Breaker",
        ["os.app_meteor"] = "Meteor Command",
        ["os.app_invaders"] = "Void Invaders",
        ["os.app_muncher"] = "Maze Muncher",
        ["os.app_camera"] = "Appareil photo",

        // Notification shade
        ["os.notifications"] = "Notifications",
        ["os.notifications_empty"] = "Aucune notification",
        ["os.notifications_clear"] = "Tout effacer",
        ["os.notif_remove"] = "Retirer",
        ["os.time_now"] = "maintenant",
        ["os.qt_notifications"] = "Notifications",
        ["os.qt_sounds"] = "Sons de notification",
        ["os.qt_lock"] = "Verrouiller la position du téléphone",
        ["os.qt_theme"] = "Thème suivant",
        ["os.qt_wallpaper"] = "Fond d'écran suivant",

        // Home screen
        ["os.edit_done"] = "Terminé",
        ["os.greeting_morning"] = "Bonjour",
        ["os.greeting_afternoon"] = "Bon après-midi",
        ["os.greeting_evening"] = "Bonsoir",
        ["os.greeting_night"] = "Encore debout ?",
        ["os.widget_eorzea"] = "Éorzéa",
        ["os.widget_status"] = "Connexion",
        ["os.widget_connected"] = "Connecté",
        ["os.widget_offline"] = "Hors ligne",
        ["os.widget_unread"] = "{0} non lus",

        // OS settings
        ["os.group_appearance"] = "Apparence",
        ["os.group_wallpaper"] = "Écran d'accueil et fond d'écran",
        ["os.group_home"] = "Écran d'accueil",
        ["os.group_apps"] = "Réglages par appli",
        ["os.group_about"] = "À propos",
        ["os.wallpaper_gradient"] = "Thème",
        ["os.wallpaper_custom"] = "Le vôtre",
        ["os.wallpaper_upload"] = "Importer une image…",
        ["os.wallpaper_dim"] = "Assombrir le fond d'écran",
        ["os.home_edit_hint"] = "Maintenez une icône de l'écran d'accueil pour la réorganiser. Faites glisser les icônes vers le dock ou entre les pages.",
        ["os.home_reset"] = "Réinitialiser la disposition",

        // Love settings hub after the appearance move
        ["settings.menu_language"] = "Langue et heure",

        // Weatherman app
        ["os.app_weather"] = "Météo",

        // Messenger app
        ["os.app_messenger"] = "Messenger",

        // Photos app
        ["os.app_photos"] = "Photos",

        // Home screen app launcher
        ["os.add_apps"] = "Ajouter des applications",
        ["os.add_apps_title"] = "Ajouter des applications",
        ["os.add_apps_hint"] = "Récupérez une application retirée ou épinglez un autre plugin Dalamud installé.",
        ["os.add_apps_none"] = "Aucun autre plugin ne propose de fenêtre principale.",
        ["os.add_apps_add"] = "Ajouter",
        ["os.add_apps_added"] = "Ajoutée",
        ["os.add_apps_search"] = "Rechercher des applis...",
        ["os.remove_app_title"] = "Retirer l'appli",
        ["os.remove_app_body"] = "Voulez-vous retirer {0} de votre écran d'accueil ?",
        ["os.remove_app_confirm"] = "Retirer",
        // added after update 1.5.1
        ["os_onboarding.header_welcome"] = "Bienvenue",
        ["os_onboarding.header_design"] = "Personnalise-le",
        ["os_onboarding.header_name"] = "Ton nom",
        ["os_onboarding.header_terms"] = "Conditions d'utilisation",
        ["os_onboarding.welcome_title"] = "Bienvenue sur AetherOS",
        ["os_onboarding.welcome_body"] = "Voici ton téléphone. Configurons-le : choisis un style, un nom et accepte les règles de base. Ça ne prend qu'un instant.",
        ["os_onboarding.design_title"] = "Choisis un design",
        ["os_onboarding.name_title"] = "Comment doit-on t'appeler ?",
        ["os_onboarding.name_body"] = "Ce nom est utilisé dans tout AetherOS. Tu pourras choisir un nom différent pour chaque appli plus tard.",
        ["os_onboarding.name_hint"] = "Nom",
        ["os_onboarding.terms_title"] = "Les règles de base",
        ["os_onboarding.terms_agree"] = "J'accepte les conditions d'utilisation",
        ["os_onboarding.finish"] = "Terminer",
        ["os_onboarding.header_signin"] = "Connexion",
        ["os_onboarding.header_passphrase"] = "Phrase secrète",
        ["os_onboarding.tos_1"] = "AetherOS est un plugin créé par des fans, fourni tel quel, sans aucune garantie. Il peut planter, perdre des données ou cesser de fonctionner à tout moment, et son utilisation se fait à tes propres risques.",
        ["os_onboarding.tos_2"] = "AetherOS n'est ni affilié à Square Enix, ni approuvé ou sponsorisé par Square Enix.",
        ["os_onboarding.tos_3"] = "FINAL FANTASY et FINAL FANTASY XIV sont des marques déposées de Square Enix Holdings Co., Ltd. Toutes les autres marques appartiennent à leurs propriétaires respectifs.",
        ["os_onboarding.tos_4"] = "En continuant, tu acceptes ces conditions.",
        // OS account avatar (added after update 1.5.1)
        ["os_onboarding.header_avatar"] = "Avatar",
        ["os_onboarding.avatar_title"] = "Ajoute une photo",
        ["os_onboarding.avatar_body"] = "Choisis une image pour ton profil AetherOS. C'est facultatif et toi seul la vois ; tu peux la changer à tout moment.",
        ["os_onboarding.avatar_choose"] = "Choisir une photo",
        ["os_onboarding.avatar_change"] = "Changer de photo",
        // two-onboarding split (added after update 1.5.1)
        ["os_onboarding.header_done"] = "Terminé",
        ["os_onboarding.done_title"] = "Tout est prêt !",
        ["os_onboarding.done_body"] = "Ton compte AetherOS est prêt. Profite bien de ton nouveau téléphone !",
        ["os_onboarding.done_start"] = "Commencer à utiliser le plugin",
        ["os_onboarding.design_language"] = "Langue",
        // combined OS profile step (added after update 1.5.1)
        ["os_onboarding.header_profile"] = "Ton profil",
        ["os_onboarding.profile_name_label"] = "Ton nom",
        ["os_onboarding.profile_photo_label"] = "Ta photo",
        // home button tooltip (added after update 1.5.1)
        ["os.home"] = "Accueil",
        // settings-consolidation categories + reset-home confirm + profile edit (added after update 1.5.1)
        ["os.cat_general"] = "Général",
        ["os.cat_appearance"] = "Apparence",
        ["os.cat_other"] = "Autre",
        ["os.menu_general"] = "Général",
        ["os.menu_appearance"] = "Apparence du téléphone",
        ["os.menu_reset_home"] = "Réinitialiser l'écran d'accueil",
        ["os.reset_home_confirm_title"] = "Réinitialiser l'écran d'accueil ?",
        ["os.reset_home_confirm_body"] = "Cela efface votre disposition d'icônes et votre dock personnalisés et rétablit la disposition par défaut. Vos applications et réglages ne sont pas affectés.",
        ["os.edit_profile"] = "Modifier",
        // Daily Eorzean news app (added after update 1.5.1)
        ["os.app_news"] = "Le Quotidien d'Éorzéa",
        ["os.news_notifications"] = "Notifications d'actualités",
        ["os.news_tagline"] = "Fond. · Toute l'actualité du royaume",
        ["os.news_latest"] = "À la une",
        ["os.news_more"] = "Plus d'articles",
        ["os.news_edition"] = "Édition · {0}",
        ["os.news_refresh"] = "Actualiser",
        ["os.news_new"] = "Nouveau",
        // Feedback app (added after update 1.5.1)
        ["os.app_feedback"] = "Commentaires",
        ["os.feedback_app_label"] = "De quelle application s'agit-il ?",
        ["os.feedback_general"] = "Général",
        ["os.feedback_send_another"] = "Envoyer d'autres commentaires",
        // generic share system (added after update 1.5.1)
        ["os.share_sheet_title"] = "Partager avec",
        // home grid + folders
        ["os.settings_home_screen"] = "Écran d'accueil",
        ["os.settings_home_grid_caption"] = "Les icônes se réorganisent automatiquement selon la nouvelle grille.",
        ["os.new_folder"] = "Nouveau dossier",
        ["os.folder_name_hint"] = "Nom du dossier…",
        ["os.folder_default_name"] = "Dossier",
        ["os.folder_arcade"] = "Arcade",
        ["os.folder_media"] = "Médias",
        ["os.folder_edit"] = "Modifier",
        ["os.folder_empty"] = "Pas encore d'applis. Faites glisser une icône sur ce dossier pour l'ajouter.",
        // photo filters + screenshot import
        ["os.filter_original"] = "Original",
        ["os.filter_mono"] = "Mono",
        ["os.filter_noir"] = "Noir",
        ["os.filter_sepia"] = "Sépia",
        ["os.filter_retro"] = "Rétro",
        ["os.filter_cool"] = "Froid",
        ["os.filter_vivid"] = "Vif",
        ["os.filter_fade"] = "Délavé",
        ["os.filter_applying"] = "Application…",
        ["os.screenshots_album"] = "Captures",
        // calendar app
        ["os.app_calendar"] = "Calendrier",
        ["os.edit_filters"] = "Filtres",
        ["os.edit_adjust"] = "Réglages",
        ["os.edit_brightness"] = "Luminosité",
        ["os.edit_contrast"] = "Contraste",
        ["os.edit_hue"] = "Teinte",
        ["os.edit_tint"] = "Intensité",
        // guided OS tour
        ["os.settings_tour"] = "Faire la visite",
        ["os.tour_next"] = "Suivant",
        ["os.tour_back"] = "Retour",
        ["os.tour_skip"] = "Passer",
        ["os.tour_finish"] = "Terminé",
        ["os.tour_welcome_title"] = "Bienvenue sur AetherOS",
        ["os.tour_welcome_body"] = "Voici votre téléphone : un écran d'accueil rempli d'applis, et AetherLove n'en est qu'une parmi d'autres. Faisons un petit tour, cela ne prend qu'une minute.",
        ["os.tour_homebtn_title"] = "Votre bouton d'accueil",
        ["os.tour_homebtn_body"] = "Vous pouvez toujours revenir à l'écran d'accueil avec le bouton d'accueil, celui qui brille en bas du téléphone.",
        ["os.tour_pages_title"] = "Votre écran d'accueil",
        ["os.tour_pages_body"] = "Vos applis vivent sur l'écran d'accueil. Balayez vers la gauche ou la droite pour changer de page ; les points mis en avant indiquent la page où vous êtes.",
        ["os.tour_widgets_title"] = "La page des widgets",
        ["os.tour_widgets_body"] = "Nous venons de glisser vers la page des widgets pour vous. Elle se trouve à gauche de vos applis et affiche l'horloge avec l'heure d'Éorzéa, l'état de la connexion et votre dernière notification.",
        ["os.tour_statusbar_title"] = "La barre d'état",
        ["os.tour_statusbar_body"] = "La bande mise en avant tout en haut affiche l'heure, la connexion aux serveurs AetherLove, le nombre de notifications en attente et la batterie. Une icône rouge y apparaît si la connexion est perdue.",
        ["os.tour_shade_title"] = "Notifications",
        ["os.tour_shade_body"] = "Touchez le haut du téléphone (ou faites-le glisser vers le bas) pour voir vos notifications, comme nous venons de le faire. Vous y trouverez aussi des réglages rapides et un curseur de luminosité. Touchez une notification pour l'ouvrir, balayez-la pour l'ignorer.",
        ["os.tour_fake_notif_title"] = "Bonjour !",
        ["os.tour_fake_notif_body"] = "Voici à quoi ressemble une notification.",
        ["os.tour_badges_title"] = "Pastilles",
        ["os.tour_badges_body"] = "Les icônes affichent un petit compteur quand quelque chose vous attend, comme des messages non lus ou de nouveaux matchs. Il disparaît à l'ouverture de l'appli. (Rassurez-vous, vous n'en avez pas vraiment 67.)",
        ["os.tour_edit_title"] = "Personnalisez tout",
        ["os.tour_edit_body"] = "Cliquez sur une icône et maintenez-la : tout se met à trembler, comme en ce moment. Glissez les icônes où vous voulez : ailleurs, sur une autre page ou dans la rangée du bas. Touchez le bouton Terminé mis en avant quand tout vous plaît.",
        ["os.tour_dock_title"] = "Le dock",
        ["os.tour_dock_body"] = "La rangée du bas reste visible sur toutes les pages. Elle accueille jusqu'à quatre favoris ; glissez-y des icônes pendant le réagencement.",
        ["os.tour_folders_title"] = "Dossiers",
        ["os.tour_folders_body"] = "Les icônes peuvent être regroupées en dossiers, comme l'exemple qui vient d'apparaître. Créez les vôtres depuis la tuile +, puis glissez des icônes dessus pour ranger. Touchez un dossier pour l'ouvrir, le renommer ou ressortir des applis.",
        ["os.tour_addapps_title"] = "Plus d'applis",
        ["os.tour_addapps_body"] = "La tuile + à la fin de vos applis ouvre cette liste. Vous pouvez y créer des dossiers et même ajouter vos autres plugins Dalamud à l'écran d'accueil. Retirez-les avec le X pendant le réagencement.",
        ["os.tour_share_title"] = "Partage",
        ["os.tour_share_body"] = "Vous pouvez partager établissements, rencontres et bien plus avec vos matchs et vos amis. Le partage fonctionne entre les différentes applis : choisissez quoi partager et vers où, et cela arrive sous forme de carte interactive.",
        ["os.tour_look_title"] = "Apparence",
        ["os.tour_look_body"] = "Dans l'appli Réglages mise en avant, choisissez un thème, changez le fond d'écran (ou importez le vôtre), ajustez la taille de la grille et même celle du téléphone.",
        ["os.tour_offline_title"] = "Hors ligne",
        ["os.tour_offline_body"] = "Vous pouvez continuer à utiliser le téléphone même si AetherLove ou d'autres applis intégrées sont indisponibles. Les applis qui ont besoin des serveurs s'assombrissent avec un petit marqueur, mais tout le reste continue de fonctionner normalement.",
        ["os.tour_done_title"] = "Fin de la visite !",
        ["os.tour_done_body"] = "Vous pouvez la revoir à tout moment depuis les Réglages. Maintenant, explorez les applis et amusez-vous bien.",
        ["os.tour_demo_folder"] = "Exemple",
        ["os.photos_search_hint"] = "Rechercher par nom ou lieu…",
        ["os.folder_eject_title"] = "Retirer du dossier ?",
        ["os.folder_eject_body"] = "{0} retournera sur votre écran d'accueil.",
        ["os.tt_prev"] = "Précédent",
        ["os.tt_next"] = "Suivant",
        ["os.tt_edit"] = "Modifier",
        ["os.tt_move"] = "Déplacer vers un album",
        ["os.tt_share"] = "Partager",
        ["os.tt_open_folder"] = "Ouvrir le dossier sur le disque",
        ["os.share_wallpaper"] = "Fond d'écran",
        ["os.profile_edit_title"] = "Modifier le profil",
        ["os.profile_save"] = "Enregistrer",
        // home right-click menu (added after update 2.0.0)
        ["os.home_menu_adjust"] = "Ajuster les icônes",
        ["os.home_menu_wallpaper"] = "Changer le fond d'écran",
        // news app tile rename (added after update 2.0.0)
        ["os.app_news_tile"] = "Actualités",

        // battery easter egg (added after update 2.0.1)
        ["os.battery_grass_body"] = "Votre santé compte pour nous : n'oubliez pas de sortir, de vous hydrater et de toucher un peu d'herbe ;-)",
        ["os.battery_grass_hint"] = "Touchez l'herbe ci-dessous pour continuer",
        ["os.settings_hide_battery_grass"] = "Masquer le message sur l'herbe quand la batterie est vide",
        // levemetes (added after update 2.0.1)
        ["os.app_levemetes"] = "Levemetes",
        ["os.battery_grass_settings_hint"] = "(Vous pouvez désactiver cette blague dans Général, dans l'app Réglages)",

        // added after update 2.0.1
        ["os.menu_audio"] = "Paramètres audio",
        ["os.app_market"] = "Marché",
        ["os.app_realtor"] = "Immobilier",

        // added after update 2.1.3
        ["os.app_wayfinder"] = "Wayfinder",
        ["os.app_yapper"] = "Yapper",
        ["os.arcade_leaderboard"] = "Classement",
        ["os.arcade_tab_weekly"] = "Cette semaine",
        ["os.arcade_tab_alltime"] = "Tous les temps",
        ["os.arcade_loading"] = "Chargement...",
        ["os.arcade_empty"] = "Pas encore de scores. Soyez le premier !",
        ["os.arcade_error"] = "Impossible de charger le classement.",
        ["os.arcade_you"] = "Vous",
        ["os.arcade_back"] = "Retour",

        // wallet app (added after update 2.2.1)
        ["os.app_wallet"] = "Portefeuille",

        // plappy birb (added after update 2.2.3)
        ["os.app_plappy"] = "Plappy Birb",

        // removable first-party apps (added after update 2.2.3)
        ["os.add_apps_section_removed"] = "Applications retirées",
        ["os.add_apps_section_plugins"] = "Autres plugins",

        // groove app (added after update 2.2.3)
        ["os.app_groove"] = "Groove",

        // store (added after update 2.2.3)
        ["os.app_store"] = "Boutique",
        ["os.store_preview_caption"] = "Aperçu seulement, pas encore à vous",
        ["os.store_preview_close"] = "Fermer l'aperçu",
        ["os.store_preview_loading"] = "Chargement de l'aperçu…",
        ["os.store_preview_failed"] = "Impossible de charger l'aperçu.",

        // added after update 2.2.3 (echo)
        ["os.app_echo"] = "Echo",
        // player and transport
        ["echo.play"] = "Lecture",
        ["echo.pause"] = "Pause",
        ["echo.mute"] = "Couper le son",
        ["echo.unmute"] = "Rétablir le son",
        ["echo.skip"] = "Passer",
        ["echo.skip_tip"] = "Passer cette vidéo pour tout le monde",
        ["echo.buffering"] = "Chargement…",
        ["echo.solo_idle"] = "Collez un lien pour commencer à regarder",
        ["echo.unavailable"] = "Indisponible",
        ["echo.close"] = "Fermer",
        // playlist
        ["echo.add"] = "Ajouter",
        ["echo.add_hint"] = "Collez un lien YouTube",
        ["echo.added_by"] = "Ajoutée par {0}",
        ["echo.added_by_unknown"] = "Ajoutée par quelqu'un qui est déjà parti",
        ["echo.remove"] = "Retirer",
        ["echo.queue_empty"] = "Rien dans la file pour l'instant",
        ["echo.playlist_full"] = "La file est pleine",
        ["echo.bad_link"] = "Ce n'est pas un lien YouTube",
        // room
        ["echo.room_code"] = "Code du salon",
        ["echo.copy_code"] = "Copier le code",
        ["echo.copied"] = "Copié",
        ["echo.host_only"] = "Hôte uniquement",
        ["echo.host_only_hint"] = "Seul l'hôte peut contrôler la lecture",
        ["echo.host_only_tip"] = "L'hôte a verrouillé les commandes",
        ["echo.kick"] = "Exclure",
        ["echo.kick_confirm"] = "Retirer cette personne du salon ?",
        ["echo.leave_room"] = "Quitter le salon",
        ["echo.end_room"] = "Fermer le salon",
        ["echo.end_room_confirm"] = "Fermer le salon pour tout le monde ?",
        ["echo.you"] = "{0} (vous)",
        ["echo.tab_playlist"] = "Playlist",
        ["echo.tab_members"] = "Membres",
        ["echo.tab_chat"] = "Chat",
        ["echo.toggle_panel"] = "Afficher ou masquer le panneau latéral",
        ["echo.new_messages"] = "{0} nouveaux messages",
        // room ended
        ["echo.room_ended_title"] = "Salon terminé",
        ["echo.room_ended_owner"] = "L'hôte a fermé le salon",
        ["echo.room_ended_owner_left"] = "L'hôte s'est déconnecté",
        ["echo.room_ended_empty"] = "Tout le monde est parti",
        ["echo.room_ended_moderation"] = "Ce salon a été fermé par la modération",
        ["echo.kicked_title"] = "Exclu du salon",
        ["echo.kicked_body"] = "Vous avez été retiré de {0}",
        // runtime and errors
        ["echo.runtime_title"] = "Echo a besoin de son lecteur",
        ["echo.runtime_body"] = "La lecture vidéo nécessite un petit composant de lecture. Il se télécharge une seule fois, puis Echo est prêt à chaque ouverture.",
        ["echo.runtime_install"] = "Le télécharger",
        ["echo.installing_title"] = "Préparation d'Echo",
        ["echo.install_downloading"] = "Téléchargement…",
        ["echo.install_verifying"] = "Vérification…",
        ["echo.install_extracting"] = "Extraction…",
        ["echo.install_failed_title"] = "Échec du téléchargement",
        ["echo.reinstall"] = "Réinstaller",
        ["echo.retry"] = "Réessayer",
        ["echo.host_failed_title"] = "Le lecteur s'est arrêté",
        ["echo.host_failed_body"] = "Impossible de le redémarrer. Veuillez réessayer.",
        ["echo.protocol_title"] = "Version du lecteur incompatible",
        ["echo.protocol_body"] = "Réinstallez le lecteur Echo pour continuer.",
        ["echo.embed_blocked_title"] = "Cette vidéo ne peut pas être intégrée",
        ["echo.embed_blocked_body"] = "Son propriétaire n'autorise pas la lecture en dehors de YouTube.",
        ["echo.video_gone_title"] = "Vidéo indisponible",
        ["echo.video_gone_body"] = "Elle a été supprimée ou rendue privée.",
        ["echo.bad_id_title"] = "Lien invalide",
        ["echo.bad_id_body"] = "Cet identifiant de vidéo ne semble pas correct.",
        ["echo.player_error_title"] = "Échec de la lecture",
        ["echo.player_error_body"] = "Une erreur est survenue lors du chargement de cette vidéo.",

        // avatar rings (added after update 2.2.3)
        ["rings.section_title"] = "Anneau d'avatar",
        ["rings.picker_title"] = "Anneau d'avatar",
        ["rings.none"] = "Aucun anneau",
        ["rings.none_owned_title"] = "Pas encore d'anneaux",
        ["rings.none_owned_body"] = "Les anneaux d'avatar sont des cadres décoratifs autour de votre photo, visibles par tous. Achetez-les avec des Sparks dans la Store.",
        ["rings.open_store"] = "Ouvrir la Store",
        ["rings.preview_hint"] = "Tout le monde voit votre anneau partout où votre photo apparaît.",

        // aetherling (added after update 2.2.3)
        ["os.app_aetherling"] = "???",

        // echo playback settings (added after update 2.2.3)
        ["echo.settings_tip"] = "Réglages de lecture",
        ["echo.settings_quality"] = "Qualité vidéo",
        ["echo.quality_auto"] = "Auto",
        ["echo.quality_720"] = "720p",
        ["echo.quality_1080"] = "1080p",
        ["echo.settings_captions"] = "Sous-titres",
        ["echo.settings_autoplay"] = "Lancer la vidéo suivante automatiquement",
        ["echo.settings_software_render"] = "Rendu logiciel (corrige certaines saccades)",
    };
}
