namespace AetherLove.Services.Localization;

internal static class OnboardingFr
{
    public static readonly System.Collections.Generic.Dictionary<string, string> Strings = new()
    {
        // Onboarding
        ["onboarding.header_welcome"] = "Bienvenue !",
        ["onboarding.header_how_it_works"] = "Comment ça marche",
        ["onboarding.header_terms_of_service"] = "Conditions d'utilisation",
        ["onboarding.header_sign_in"] = "Connexion",
        ["onboarding.header_secure_messages"] = "Sécurisez vos messages",
        ["onboarding.header_your_profile"] = "Votre profil",
        ["onboarding.header_profile_picture"] = "Photo de profil",
        ["onboarding.header_your_photos"] = "Vos photos",
        ["onboarding.header_optional_details"] = "Détails facultatifs",
        ["onboarding.header_match_preferences"] = "Préférences de correspondance",
        ["onboarding.header_make_it_yours"] = "Personnalisez-le",
        ["onboarding.header_all_set"] = "Tout est prêt !",
        ["onboarding.header_default"] = "AetherLove",

        ["onboarding.back"] = "← Retour",
        ["onboarding.saving"] = "Enregistrement…",
        ["onboarding.start_swiping"] = "Commencer à swiper →",
        ["onboarding.finish"] = "Terminer →",
        ["onboarding.retry"] = "Réessayer →",
        ["onboarding.next"] = "Suivant",
        ["onboarding.could_not_assemble"] = "Impossible d'assembler {0} : {1}",
        ["onboarding.select_photo"] = "Sélectionner une photo",
        ["onboarding.image_files"] = "Fichiers image",
        ["onboarding.crop_avatar"] = "Recadrer l'avatar",
        ["onboarding.crop_main_photo"] = "Recadrer la photo principale",
        ["onboarding.crop_extra_photo"] = "Recadrer la photo supplémentaire {0}",

        // Step 2 - How It Works
        ["onboarding.how_intro"] = "Voici comment fonctionne AetherLove : de la création de votre profil jusqu'à la discussion avec votre première correspondance.",
        ["onboarding.how1_title"] = "Créez votre profil",
        ["onboarding.how1_body"] = "Parlez-nous de votre personnage : votre race, votre serveur, vos langues et ce que vous recherchez. Envoyez un portrait. C'est votre carte de visite.",
        ["onboarding.how2_title"] = "Parcourez le deck",
        ["onboarding.how2_body"] = "Chaque fois que vous ouvrez le deck, vous voyez une pile de fiches de profil. Swipez vers la droite (ou touchez ♥) pour exprimer votre intérêt. Swipez vers la gauche (ou touchez X) pour passer.",
        ["onboarding.how3_title"] = "Définissez vos préférences",
        ["onboarding.how3_body"] = "Choisissez la race, la région, les langues et les centres d'intérêt que vous aimeriez trouver chez une correspondance. Plus vous êtes précis, meilleures seront les correspondances proposées.",
        ["onboarding.how4_title"] = "Match !",
        ["onboarding.how4_body"] = "Vous obtenez un match quand un autre joueur swipe à droite sur vous et que vous faites de même. AetherLove vous envoie une notification et ouvre un chat privé.",
        ["onboarding.how5_title"] = "Discutez en jeu",
        ["onboarding.how5_body"] = "Envoyez des messages directement via le plugin : aucune application externe nécessaire. Vos conversations sont chiffrées de bout en bout, de sorte que même les développeurs d'AetherLove ne peuvent pas lire vos discussions.",
        ["onboarding.how6_title"] = "Gardez le contrôle",
        ["onboarding.how6_body"] = "Mettez à jour votre profil, ajustez vos préférences ou annulez une correspondance à tout moment depuis l'écran des paramètres. AetherLove ne partagera JAMAIS votre nom de joueur complet, votre localisation ou les informations de votre compte avec d'autres joueurs.",
        ["onboarding.how_ready"] = "Prêt à commencer ? Cliquez sur Suivant pour continuer.",

        // Step 2 - Terms of Service
        ["onboarding.tos_p1"] = "AetherLove est un plugin de mise en relation sociale pour Final Fantasy XIV destiné à un public adulte. En continuant, vous confirmez que vous avez au moins 18 ans et consentez à participer à une plateforme sociale pour adultes.",
        ["onboarding.tos_p2"] = "Je comprends que les informations de profil que je fournis (y compris mon nom affiché, ma bio, mon serveur d'origine, les détails de mon personnage et toutes les photos que j'envoie) peuvent être visibles par d'autres utilisateurs d'AetherLove. Je suis responsable de l'exactitude de mon profil et je dois m'assurer que toutes les photos que j'envoie sont appropriées et que j'ai le droit de les partager.",
        ["onboarding.tos_ownership"] = "Les personnages figurant sur les photos que j'envoie doivent être les miens. Si le personnage d'un autre joueur apparaît sur une image, je confirme avoir sa permission pour la partager. Je n'enverrai pas de captures d'écran ou de poses de personnages qui ne sont pas les miens sans le consentement de leur propriétaire.",
        ["onboarding.tos_p3"] = "Je m'engage à interagir respectueusement avec tous les autres utilisateurs. Le harcèlement, le contenu explicite non sollicité, les propos haineux ou toute forme d'abus envers d'autres utilisateurs sont strictement interdits. Toute violation de ces conditions peut entraîner une exclusion de la plateforme sans préavis ni recours.",
        ["onboarding.tos_nsfl"] = "Le contenu NSFL (\"Not Suitable For Life\") n'est jamais autorisé sur AetherLove, en aucune circonstance. Cela inclut toute image ou tout message représentant des scènes sanglantes réelles ou simulées, la mort, des violences graphiques, des mutilations, des blessures graves, de la cruauté envers les animaux ou de l'automutilation, ainsi que tout autre contenu choquant ou écœurant. Cela est totalement distinct de l'option NSFW : marquer un contenu comme NSFW ne rend jamais le contenu NSFL acceptable. Nous appliquons une stricte politique de tolérance zéro. Publier du contenu NSFL entraîne un bannissement immédiat et permanent du compte, sans avertissement ni possibilité de recours.",
        ["onboarding.tos_p4"] = "Je comprends qu'AetherLove est un plugin non officiel, créé par la communauté, et qu'il n'est ni affilié à Square Enix Co., Ltd. ni approuvé par celle-ci. Il est fourni tel quel, sans aucune garantie de disponibilité, de sécurité des données ou d'adéquation à un usage particulier. Les développeurs du plugin ne sont pas responsables des actions des autres utilisateurs ni des conséquences découlant de l'utilisation de ce plugin.",
        ["onboarding.tos_p5"] = "Les décisions de modération (y compris les avertissements, les suspensions temporaires et les bannissements permanents) sont prises à la seule discrétion de l'équipe d'AetherLove. L'équipe a le dernier mot sur toutes les questions de modération. Les décisions n'ont pas à être expliquées ou justifiées auprès de l'utilisateur concerné et ne sont pas susceptibles de recours, sauf indication contraire explicite de l'équipe.",
        ["onboarding.tos_p6"] = "Nous aimons et apprécions les personnages Lalafell autant que quiconque, mais les fonctionnalités pour adultes et NSFW ne sont pas disponibles pour les joueurs dont la race du personnage est Lalafell. Comme les Lalafells ont une apparence enfantine, nous ne faisons aucune distinction au cas par cas et appliquons cette politique de manière uniforme à chaque compte Lalafell. L'option Jeu de rôle 18+, l'activation du NSFW et l'envoi de photos NSFW sont tous désactivés tant que votre race est définie sur Lalafell. Toute tentative de contourner cette restriction constitue un motif de suppression de compte.",
        ["onboarding.tos_ai"] = "Modération assistée par IA : j'accepte que les API de modération d'OpenAI examinent automatiquement le texte et les images de mon profil. Cela aide à détecter les contenus qui enfreignent ces règles et garde AetherLove sûr pour tout le monde. J'accepte aussi qu'un second modèle OpenAI vérifie les images de mon profil. Il vérifie que l'image montre mon propre personnage Final Fantasy XIV, et non du fan art, une image générée par IA ou un contenu sans rapport. Il vérifie aussi si l'image est SFW ou NSFW. Le texte et les images de mon profil sont envoyés à OpenAI uniquement pour la modération. Ils ne servent jamais à entraîner les modèles d'OpenAI. Je comprends que l'équipe humaine d'AetherLove prend toutes les décisions finales de modération. L'IA seule n'est jamais responsable d'une action de modération.",
        ["onboarding.tos_p7"] = "Je reconnais que ces conditions peuvent être mises à jour à tout moment. La poursuite de l'utilisation d'AetherLove après une mise à jour vaut acceptation des conditions révisées.",
        ["onboarding.tos_read_carefully"] = "À LIRE ATTENTIVEMENT",
        ["onboarding.tos_accepted"] = "Conditions acceptées. Appuyez sur Suivant pour continuer.",
        ["onboarding.tos_timer"] = "Veuillez lire attentivement : le bouton d'acceptation sera disponible dans {0} s",
        ["onboarding.tos_scroll_bottom"] = "Faites défiler jusqu'en bas pour accepter.",
        ["onboarding.tos_i_agree"] = "J'accepte",

        // Step 3 - XIVAuth
        ["onboarding.auth_signin_with_xivauth"] = "Se connecter avec XIVAuth",
        ["onboarding.auth_intro"] = "AetherLove utilise XIVAuth pour vérifier votre identité en tant que joueur actif de Final Fantasy XIV. Aucun mot de passe n'est requis : l'authentification est gérée de manière sécurisée via votre client de jeu.",
        ["onboarding.auth_contacting"] = "Contact d'AetherLove",
        ["onboarding.auth_dont_have_xivauth"] = "Vous n'avez pas de XIVAuth ?",
        ["onboarding.auth_xivauth_explainer"] = "XIVAuth est un système d'authentification unique gratuit, géré par la communauté, pour les outils Final Fantasy XIV. Il confirme que vous êtes un véritable joueur de FFXIV en liant votre personnage Lodestone, sans jamais partager votre mot de passe Square Enix. L'inscription ne prend qu'une minute.",
        ["onboarding.auth_create_account"] = "Créer un compte XIVAuth",
        ["onboarding.auth_complete_in_browser"] = "Terminez la connexion dans votre navigateur",
        ["onboarding.auth_browser_opened"] = "Une fenêtre de navigateur s'est ouverte. Terminez la connexion avec XIVAuth puis revenez ici. Cette étape se poursuivra automatiquement.",
        ["onboarding.auth_open_browser_again"] = "Rouvrir le navigateur",
        ["onboarding.auth_cancel"] = "Annuler",
        ["onboarding.auth_loading_profile"] = "Connecté ! Chargement de votre profil",
        ["onboarding.auth_signed_in"] = "Connecté !",
        ["onboarding.auth_welcome_back"] = "Content de vous revoir !",
        ["onboarding.auth_welcome_back_named"] = "Content de vous revoir, {0} !",
        ["onboarding.auth_details_loaded"] = "Nous avons chargé vos informations, vous pouvez commencer à swiper tout de suite.",
        ["onboarding.auth_timeout"] = "La connexion a pris trop de temps. Veuillez réessayer.",
        ["onboarding.auth_failed"] = "Échec de la connexion.",
        ["onboarding.auth_try_again"] = "Réessayer",

        // Step 3a - Passphrase
        ["onboarding.pass_heading"] = "Sécurisez vos messages",
        ["onboarding.pass_intro"] = "L'équipe d'AetherLove ne peut pas lire vos messages privés : ni maintenant, ni jamais. C'est parce que nous chiffrons chaque message avec une clé que VOUS êtes le seul à connaître. Votre phrase secrète est cette clé. Vous la définissez sur l'écran suivant. Une phrase secrète fonctionne comme un mot de passe, mais vous devez la retenir et la conserver vous-même. Il n'y a pas de bouton « phrase secrète oubliée ». Notez-la ou enregistrez-la dans un gestionnaire de mots de passe. Traitez-la comme un mot de passe critique.",
        ["onboarding.pass_warning"] = "Vous aurez besoin de cette phrase secrète sur tout autre ordinateur, ou sur un ordinateur neuf. Sans elle, personne ne peut lire vos discussions, pas même vous.",
        ["onboarding.pass_label"] = "Phrase secrète",
        ["onboarding.pass_confirm_label"] = "Confirmer la phrase secrète",
        ["onboarding.pass_err_empty"] = "Veuillez saisir une phrase secrète.",
        ["onboarding.pass_err_too_short"] = "La phrase secrète doit comporter au moins {0} caractères.",
        ["onboarding.pass_err_confirm_empty"] = "Veuillez confirmer votre phrase secrète.",
        ["onboarding.pass_err_mismatch"] = "Les phrases secrètes ne correspondent pas.",
        ["onboarding.pass_ack"] = "Je comprends que mon historique de discussion ne pourra pas être récupéré si j'oublie cette phrase secrète.",
        ["onboarding.pass_securing"] = "Sécurisation de vos clés…",
        ["onboarding.pass_set_title"] = "Définis ta phrase secrète",
        ["onboarding.pass_show_title"] = "Sauvegarde ta phrase secrète",
        ["onboarding.pass_show_sub"] = "Nous t'affichons ta phrase secrète cette seule fois. Copie-la dans un gestionnaire de mots de passe, ou dans un autre endroit sûr. Nous ne pouvons pas la récupérer pour toi.",
        ["onboarding.pass_copied_ack"] = "J'ai copié ma phrase secrète dans un endroit sûr.",
        ["onboarding.pass_copy"] = "Copier",
        ["onboarding.pass_strength_too_weak"] = "Trop faible",
        ["onboarding.pass_strength_weak"] = "Faible",
        ["onboarding.pass_strength_ok"] = "Correcte",
        ["onboarding.pass_strength_good"] = "Bonne",
        ["onboarding.pass_strength_strong"] = "Forte",

        // Step 4 - Profile (data labels)
        ["onboarding.region_na"] = "Amérique du Nord (NA)",
        ["onboarding.region_eu"] = "Europe (EU)",
        ["onboarding.region_oceania"] = "Océanie",
        ["onboarding.region_japan"] = "Japon",
        ["onboarding.race_hyur"] = "Hyur",
        ["onboarding.race_elezen"] = "Elezen",
        ["onboarding.race_lalafell"] = "Lalafell",
        ["onboarding.race_miqote"] = "Miqo'te",
        ["onboarding.race_roegadyn"] = "Roegadyn",
        ["onboarding.race_au_ra"] = "Au Ra",
        ["onboarding.race_hrothgar"] = "Hrothgar",
        ["onboarding.race_viera"] = "Viera",
        ["onboarding.gender_male"] = "Homme",
        ["onboarding.gender_female"] = "Femme",
        ["onboarding.gender_other"] = "Autre",
        ["onboarding.content_housing"] = "Logement et décoration",
        ["onboarding.content_music_bard"] = "Musique et performances de Barde",
        ["onboarding.content_rp_venues"] = "Visite de lieux de jeu de rôle",
        ["onboarding.content_club_venues"] = "Visite de clubs",
        ["onboarding.content_gpose"] = "Gpose",
        ["onboarding.content_story_lore"] = "Histoire et lore",
        ["onboarding.content_roulettes"] = "Roulettes",
        ["onboarding.content_regular"] = "Contenu normal",
        ["onboarding.content_extreme_trials"] = "Défis extrêmes",
        ["onboarding.content_savage"] = "Raids sadiques",
        ["onboarding.content_pvp"] = "JcJ",
        ["onboarding.content_blue_mage"] = "Mage bleu",
        ["onboarding.content_triple_triad"] = "Triple Triad",
        ["onboarding.content_mahjong"] = "Mah-jong",
        ["onboarding.content_treasure_hunts"] = "Chasses au trésor",
        ["onboarding.content_crafting_gathering"] = "Artisanat et récolte",
        ["onboarding.content_fishing"] = "Pêche",
        ["onboarding.content_achievement_hunting"]= "Chasse aux hauts faits",
        ["onboarding.lf_chatting"] = "Discuter avec de nouvelles personnes",
        ["onboarding.lf_casual_buddies"] = "Des camarades de jeu décontractés",
        ["onboarding.lf_gpose_glamour"] = "Des partenaires de GPose et de glamour",
        ["onboarding.lf_romance"] = "Une romance en jeu",
        ["onboarding.lf_long_term"] = "Une relation durable en jeu",
        ["onboarding.lf_rp_partners"] = "Des partenaires de jeu de rôle",
        ["onboarding.lf_erp"] = "Jeu de rôle 18+ (ERP)",

        // Step 4 - Profile (body)
        ["onboarding.profile_intro"] = "Ces champs apparaissent sur votre fiche de profil publique et servent à suggérer des correspondances.",
        ["onboarding.profile_identity"] = "Identité",
        ["onboarding.profile_display_name"] = "Nom affiché",
        ["onboarding.profile_display_name_tip"] = "Le nom que les autres utilisateurs voient. Utilisez votre prénom ou un pseudonyme.\nLes espaces ne sont pas autorisés.",
        ["onboarding.profile_display_name_hint"] = "Prénom ou pseudonyme, sans espaces, au moins 3 caractères.",
        ["onboarding.profile_about_me"] = "À propos de moi",
        ["onboarding.profile_about_me_tip"] = "Rédigez une courte présentation. Qu'est-ce que vous aimez ?\nQuel genre de relations recherchez-vous ?",
        ["onboarding.profile_char_count"] = "{0} / 500 caractères",
        ["onboarding.profile_preview"] = "Aperçu",
        ["onboarding.profile_bio_placeholder"] = "Votre bio apparaîtra ici…",
        ["onboarding.profile_location"] = "Localisation",
        ["onboarding.profile_server_region"] = "Région du serveur",
        ["onboarding.profile_server_region_tip"] = "Sélectionnez votre région Final Fantasy XIV.\nCela aide à vous mettre en relation avec des joueurs proches.",
        ["onboarding.profile_character"] = "Personnage",
        ["onboarding.profile_race"] = "Race",
        ["onboarding.profile_gender"] = "Sexe",
        ["onboarding.profile_languages_speak"] = "Langues que je parle",
        ["onboarding.profile_languages_hint"] = "Sélectionnez toutes les langues dans lesquelles vous êtes à l'aise pour discuter.",
        ["onboarding.profile_content_heading"] = "J'apprécie le contenu suivant",
        ["onboarding.profile_content_hint"] = "Sélectionnez tout ce qui s'applique, cela apparaît sur votre fiche de profil.",
        ["onboarding.profile_looking_for_heading"]= "Je recherche",
        ["onboarding.profile_looking_for_hint"] = "Sélectionnez tout ce qui s'applique (au moins un choix est requis). Être honnête aide à trouver de meilleures correspondances.",
        ["onboarding.profile_erp_enables_nsfw"] = "    Cocher cette option active automatiquement le NSFW pour votre profil.",
        ["onboarding.profile_nsfw_heading"] = "NSFW",
        ["onboarding.profile_nsfw_lalafell"] = "Les fonctionnalités pour adultes et NSFW ne sont pas disponibles tant que votre race est définie sur Lalafell. Consultez les conditions d'utilisation pour plus de détails.",
        ["onboarding.profile_nsfw_explainer"] = "NSFW signifie « Not Safe For Work » : du contenu comportant de la nudité ou des thèmes sexuels. Souhaitez-vous activer les profils NSFW ? Cela entraînera des correspondances potentielles avec des joueurs ayant envoyé des photos NSFW sur leur profil. Ces images sont toujours floutées jusqu'à ce que vous choisissiez de les révéler.",
        ["onboarding.profile_nsfw_checkbox"] = "Je veux voir les profils avec du contenu NSFW",
        ["onboarding.profile_nsfw_learn_more"] = "Qu'est-ce que ça veut dire ?",
        ["onboarding.profile_nsfw_locked"] = "Activé en permanence parce que vous avez sélectionné Jeu de rôle 18+ (ERP). Décochez cette option pour modifier ce paramètre.",
        ["onboarding.profile_timezone"] = "Fuseau horaire",
        ["onboarding.profile_timezone_hint"] = "Indiqué aux correspondances potentielles pour qu'elles sachent quand vous êtes actif.",

        // Step 5 - Avatar
        ["onboarding.avatar_heading"] = "Votre photo de profil",
        ["onboarding.avatar_intro"] = "Votre photo de profil est affichée dans le chat et lors des correspondances. Nous exigeons une image carrée représentant le visage de votre personnage FFXIV.",
        ["onboarding.avatar_tip"] = "Astuce : un portrait G-Pose en gros plan fonctionne le mieux.",
        ["onboarding.avatar_sfw_warning"] = "Votre photo de profil principale DOIT être SFW. Nous pouvons supprimer votre compte si vous envoyez une photo NSFW.",
        ["onboarding.avatar_browse"] = "Parcourir…",
        ["onboarding.avatar_crop_hint"] = "L'éditeur de recadrage s'est ouvert dans une fenêtre séparée.\nCliquez sur « Utiliser ce recadrage » pour confirmer votre avatar.",
        ["onboarding.avatar_no_image"] = "Aucune image sélectionnée pour le moment.",
        ["onboarding.avatar_set"] = "Photo de profil définie !",
        ["onboarding.avatar_change_photo"] = "Changer de photo",
        ["onboarding.avatar_its_a_match"] = "C'est un match !",
        ["onboarding.avatar_match_preview_caption"] = "Aperçu : comment votre avatar apparaît sur les fiches de match",

        // Step 5 - Image Disclaimer
        ["onboarding.disclaimer_intro"] = "AetherLove est conçu pour les joueurs de Final Fantasy XIV. Avant d'envoyer des images, veuillez lire attentivement les consignes suivantes.",
        ["onboarding.disclaimer_moderation"] = "Tous les envois sont soumis à une modération automatisée et manuelle.",
        ["onboarding.disclaimer_general_heading"] = "Général",
        ["onboarding.disclaimer_general_body"] = "Toutes les images envoyées sur AetherLove doivent représenter votre personnage Final Fantasy XIV. Les images sans rapport avec des personnages de Final Fantasy XIV seront rejetées sans préavis.",
        ["onboarding.disclaimer_profile_images_heading"] = "Images de profil",
        ["onboarding.disclaimer_profile_images_body"] = "Les images de votre profil doivent être des captures d'écran ou des G-Poses de votre propre personnage Final Fantasy XIV.",
        ["onboarding.disclaimer_not_allowed"] = "NON AUTORISÉS :",
        ["onboarding.disclaimer_na_fan_art"] = "Fan art",
        ["onboarding.disclaimer_na_3d_renders"] = "Rendus 3D personnalisés",
        ["onboarding.disclaimer_na_ai"] = "Images générées par IA",
        ["onboarding.disclaimer_na_real_photos"] = "Photographies de personnes ou de lieux réels",
        ["onboarding.disclaimer_na_unrelated"] = "Toute image sans rapport avec votre personnage FFXIV",
        ["onboarding.disclaimer_profile_images_consent"] = "N'envoyez que des images de votre propre personnage. Si le personnage d'un autre joueur apparaît sur une capture, assurez-vous d'abord d'avoir sa permission. Merci de ne pas envoyer de captures ou de poses du personnage de quelqu'un d'autre sans son consentement.",
        ["onboarding.disclaimer_nsfw_heading"] = "Contenu NSFW",
        ["onboarding.disclaimer_nsfw_body1"] = "Votre avatar principal et votre photo de profil principale doivent être Safe For Work (SFW). Choisissez une image que vous montreriez sans gêne à votre responsable ou à un collègue.",
        ["onboarding.disclaimer_nsfw_body2"] = "Vos autres photos de profil peuvent contenir du contenu NSFW. Vous devez marquer chacune d'elles comme NSFW au moment de l'envoi. Nous vous encourageons vivement à garder autant de photos SFW que possible.",
        ["onboarding.disclaimer_nsfl_heading"] = "Contenu NSFL : jamais autorisé",
        ["onboarding.disclaimer_nsfl_body"] = "NSFL signifie \"Not Suitable For Life\". Ce contenu n'est jamais autorisé dans une image, que vous la marquiez SFW ou NSFW. Cela comprend les scènes sanglantes réelles ou simulées, la mort, la violence graphique, la mutilation, les blessures graves, la cruauté envers les animaux et l'automutilation. Cela comprend aussi tout ce qui vise à choquer, perturber ou écœurer. La règle NSFL est distincte des règles NSFW ci-dessus. Un marquage NSFW autorise du contenu suggestif. Il n'autorise jamais du contenu NSFL.",
        ["onboarding.disclaimer_nsfl_zero_tolerance"] = "Tolérance zéro : envoyer du contenu NSFL entraîne un bannissement immédiat et permanent du compte, sans avertissement ni recours.",
        ["onboarding.disclaimer_ai_heading"] = "Modération assistée par IA",
        ["onboarding.disclaimer_ai_body"] = "L'API de modération d'OpenAI et un second modèle OpenAI vérifient chaque image que vous envoyez. Ils vérifient que l'image montre votre propre personnage FFXIV. Il ne doit s'agir ni de fan art, ni d'une image générée par IA, ni d'un contenu sans rapport. Ils vérifient aussi si l'image est SFW ou NSFW. Nous envoyons vos images à OpenAI uniquement pour la modération. OpenAI n'utilise jamais vos images pour entraîner ses modèles. L'équipe humaine d'AetherLove prend toutes les décisions finales de modération. L'IA n'agit jamais seule contre votre compte.",
        ["onboarding.disclaimer_rules_heading"] = "Que se passe-t-il si une image enfreint les règles ?",
        ["onboarding.disclaimer_rules_body1"] = "Vous recevez une notification si l'une de vos images enfreint ces consignes. Nous retirons cette image. Votre profil est ensuite mis en attente (shadowban) jusqu'à ce que vous corrigiez le problème.",
        ["onboarding.disclaimer_rules_body2"] = "L'envoi de contenu nuisible, abusif ou illégal entraînera :",
        ["onboarding.disclaimer_permanent_ban"] = "Un bannissement permanent du compte.",
        ["onboarding.disclaimer_continue"] = "J'ai compris, continuer",

        // Step 6 - Photos
        ["onboarding.photos_heading"] = "Photos de profil",
        ["onboarding.photos_intro"] = "Ajoutez des portraits à votre profil (format 10:16). Le premier emplacement est obligatoire ; les emplacements 2 à 4 sont facultatifs. Pour de meilleurs résultats, utilisez des images d'au moins 480 × 768 px.",
        ["onboarding.photos_main_thumb"] = "Principale",
        ["onboarding.photos_tap_slot"] = "Touchez un emplacement ci-dessus pour ajouter ou gérer une photo.",
        ["onboarding.photos_main_photo"] = "Photo principale",
        ["onboarding.photos_extra_photo"] = "Photo supplémentaire {0}",
        ["onboarding.photos_main_sfw_warning"] = "Votre photo de profil principale DOIT être SFW. Envoyer une photo NSFW est un motif de suspension ou de suppression de compte.",
        ["onboarding.photos_sfw_nsfw_question"] = "Cette photo est-elle SFW ou NSFW ?",
        ["onboarding.photos_decl_sfw"] = "SFW",
        ["onboarding.photos_decl_nsfw"] = "NSFW (18+)",
        ["onboarding.img_rules_title"] = "Règles des photos",
        ["onboarding.img_rules_intro"] = "Quelques règles rapides avant d'ajouter des photos. Fais-les défiler jusqu'au bout.",
        ["onboarding.img_rules_character"] = "Les photos doivent représenter ton propre personnage Final Fantasy XIV, prises en jeu. Pas de fan art, de rendus 3D, d'images générées par IA ni de photos réelles.",
        ["onboarding.img_rules_sfw"] = "Tout public par défaut. Si une photo contient de la nudité ou des thèmes sexuels, marque-la NSFW pour qu'elle reste floutée jusqu'à ce qu'on la révèle.",
        ["onboarding.img_rules_illegal"] = "Ne publie jamais de contenu illégal ou extrême : gore réel, tout ce qui implique des mineurs, ou des images haineuses. C'est un bannissement immédiat et permanent.",
        ["onboarding.img_rules_consent"] = "En publiant, tu confirmes que ces images sont les tiennes à partager. Chaque photo est vérifiée, et tout ce qui enfreint ces règles est supprimé.",
        ["onboarding.img_scroll_hint"] = "Fais défiler jusqu'en bas des règles",
        ["onboarding.photos_mismatch_warning"] = "Nous mettons votre photo en attente de modération si notre système trouve du contenu NSFW que vous avez marqué SFW. Vous risquez aussi une suspension de compte.",
        ["onboarding.photos_previously_uploaded"] = "Précédemment envoyée.",
        ["onboarding.photos_confirmed"] = "Photo confirmée.",
        ["onboarding.photos_remove"] = "Supprimer",
        ["onboarding.photos_browse"] = "Parcourir…",
        ["onboarding.photos_crop_hint"] = "L'éditeur de recadrage s'est ouvert dans une fenêtre distincte.\nCliquez sur « Utiliser ce recadrage » pour confirmer la photo.",
        ["onboarding.photos_required"] = "Cette photo est obligatoire.",
        ["onboarding.photos_optional"] = "Cette photo est facultative.",

        // Step 7 - Optional
        ["onboarding.expansion_none"] = "(Aucune)",
        ["onboarding.opt_heading"] = "Parlez-nous davantage de vous",
        ["onboarding.opt_intro"] = "Tous les champs de cette page sont facultatifs. Remplissez-en autant ou aussi peu que vous le souhaitez. Ces détails apparaissent sur votre fiche de profil et aident les autres à vous trouver.",
        ["onboarding.opt_fav_job"] = "Job favori",
        ["onboarding.opt_fav_job_tip"] = "Le job ou le rôle que vous appréciez le plus.\nTapez pour filtrer.",
        ["onboarding.opt_fav_location"] = "Lieu favori",
        ["onboarding.opt_fav_location_tip"] = "Un endroit d'Eorzea que vous adorez visiter.\nTapez pour filtrer.",
        ["onboarding.opt_location_unavailable"] = "(données de lieu indisponibles)",
        ["onboarding.opt_location_none"] = "(Aucun)",
        ["onboarding.opt_fav_expansion"] = "Extension favorite",
        ["onboarding.opt_fav_expansion_tip"] = "Votre extension FFXIV préférée de tous les temps.",
        ["onboarding.opt_music_heading"] = "Chanson favorite",
        ["onboarding.opt_music_tip"] = "Collez un lien Spotify, SoundCloud, Apple Music ou YouTube Music.\nLe nom du titre est récupéré automatiquement.",
        ["onboarding.opt_fav_spotify"] = "Spotify",
        ["onboarding.opt_fav_soundcloud"] = "SoundCloud",
        ["onboarding.opt_fav_apple"] = "Apple Music",
        ["onboarding.opt_fav_youtube"] = "YouTube Music",
        ["onboarding.opt_fav_movie"] = "Film favori",
        ["onboarding.opt_fav_movie_tip"] = "Votre film préféré de tous les temps, tous genres confondus.",
        ["onboarding.opt_fav_anime"] = "Anime favori",
        ["onboarding.opt_fav_anime_tip"] = "Votre série ou film d'animation préféré.",
        ["onboarding.opt_fav_ff_character"] = "Personnage de Final Fantasy favori",
        ["onboarding.opt_fav_ff_character_tip"] = "N'importe quel personnage de l'univers Final Fantasy.",
        ["onboarding.opt_weekday_playtimes"] = "Heures de jeu en semaine (lun.–ven.)",
        ["onboarding.opt_weekday_playtimes_tip"] = "Cliquez sur les heures où vous êtes généralement en ligne en semaine.\nSurvolez une barre pour voir l'heure.\nVeuillez choisir votre heure locale.",
        ["onboarding.opt_weekend_playtimes"] = "Heures de jeu le week-end (sam.–dim.)",
        ["onboarding.opt_weekend_playtimes_tip"] = "Cliquez sur les heures où vous êtes généralement en ligne le week-end.\nSurvolez une barre pour voir l'heure.\nVeuillez choisir votre heure locale.",
        ["onboarding.opt_sync_tool"] = "Outil de synchronisation utilisé",
        ["onboarding.opt_sync_tool_tip"] = "Les outils de synchronisation comme Lightless ou Honsefarm permettent aux utilisateurs en correspondance\nde partager automatiquement les apparences de mods.",
        ["onboarding.time_am"] = "AM",
        ["onboarding.time_pm"] = "PM",

        // Step 8 - Filters
        ["onboarding.filters_intro"] = "Dites-nous avec qui vous aimeriez correspondre. Ces préférences nous aident à vous présenter les bonnes personnes. Vous pouvez les ajuster à tout moment dans les paramètres.",
        ["onboarding.filters_heading"] = "Je souhaite correspondre avec",
        ["onboarding.filters_race"] = "Race",
        ["onboarding.filters_gender"] = "Sexe",
        ["onboarding.filters_region"] = "Région",
        ["onboarding.filters_spoken_language"] = "Langue parlée",
        ["onboarding.filters_language_tip"] = "Ne cochez rien pour correspondre quelle que soit la langue parlée.",
        ["onboarding.filters_all"] = "Tout",
        ["onboarding.filters_none"] = "Aucun",
        ["onboarding.filters_clear"] = "Effacer",
        ["onboarding.filters_any_race"] = "  Aucune sélection : toutes les races",
        ["onboarding.filters_any_gender"] = "  Aucune sélection : tous les sexes",
        ["onboarding.filters_any_region"] = "  Aucune sélection : toutes les régions",
        ["onboarding.filters_any_language"] = "  Aucune sélection : aucune préférence de langue",

        // Step 9 - Finished
        ["onboarding.finished_heading"] = "Tout est prêt !",
        ["onboarding.finished_intro"] = "Votre profil a été créé et vos préférences de correspondance ont été enregistrées. Vous êtes prêt à entrer en contact avec d'autres joueurs de Final Fantasy XIV.",
        ["onboarding.finished_verification_heading"] = "Vérification du profil",
        ["onboarding.finished_verification_body"] = "Votre profil sera examiné par notre équipe de modération sous 24 heures. Pendant ce temps, votre profil est pleinement actif : vous pouvez parcourir, correspondre et discuter dès maintenant.",
        ["onboarding.finished_verification_note"] = "Nous ne vous contacterons qu'en cas de problème avec votre profil ou vos images.",
        ["onboarding.finished_swiping_heading"] = "Commencez à swiper",
        ["onboarding.finished_swiping_body"] = "Rendez-vous sur le deck pour parcourir les profils. Touchez ♥ sur une personne qui vous intéresse. Quand elle touche ♥ en retour, c'est un match ! Un chat privé s'ouvre automatiquement.",
        ["onboarding.finished_rejected_heading"] = "Si une image est rejetée",
        ["onboarding.finished_rejected_body"] = "Si l'une de vos images enfreint nos consignes lors de l'examen, vous recevrez une notification. L'image sera supprimée et il vous sera demandé de la remplacer. Votre profil reste actif entre-temps.",
        ["onboarding.finished_good_luck"] = "Bonne chance, AetherLove croit en vous ! ♥",

        // Step 10 - Preferences
        ["onboarding.prefs_intro"] = "Personnalisez AetherLove : choisissez un thème de couleur et une taille de téléphone. Vous pouvez modifier les deux à tout moment dans les paramètres.",
        ["onboarding.prefs_theme"] = "Thème",
        ["onboarding.prefs_phone_size"] = "Taille du téléphone",

        // added after update (1.3.1)
        ["onboarding.content_ultimate_raiding"] = "Raids fatals",
        ["onboarding.content_deep_dungeons"] = "Donjons sans fond",
        ["onboarding.content_variant_criterion"] = "Donjons variants / critères",
        ["onboarding.content_field_operations"] = "Opérations sur le terrain (Bozja, Eureka)",
        ["onboarding.race_gender_warning"] = "Veuillez choisir la race et le genre de votre personnage FFXIV, et non votre genre dans la vie réelle !",
        ["onboarding.tos_race_gender"] = "J'accepte de choisir la race et le genre corrects pour mon personnage Final Fantasy XIV lors de la configuration, et je comprends que ma photo de profil principale doit représenter ce personnage.",
        // two-onboarding split (added after update 1.5.1)
        ["onboarding.welcome_title"] = "Bienvenue sur AetherLove",
        ["onboarding.welcome_intro"] = "Il est temps de créer ton profil de rencontre. Cela ne prend qu'une minute, et tu peux tout modifier plus tard.",
        ["onboarding.welcome_step_profile"] = "Parle-nous de toi",
        ["onboarding.welcome_step_photos"] = "Ajoute une photo ou deux",
        ["onboarding.welcome_step_prefs"] = "Choisis qui tu aimerais rencontrer",
        ["onboarding.welcome_footer"] = "Ton profil n'est montré qu'aux autres joueurs d'AetherLove.",
        ["onboarding.avatar_use_os"] = "Utiliser ma photo AetherOS",
        // dating onboarding split into focused pages (added after update 1.5.1)
        ["onboarding.hero_welcome_title"] = "Crée ton profil",
        ["onboarding.hero_welcome_sub"] = "Quelques étapes rapides pour créer ton profil de rencontre AetherLove. Tu pourras tout modifier plus tard.",
        ["onboarding.hero_name_title"] = "Comment t'appelles-tu ?",
        ["onboarding.hero_name_sub"] = "C'est le nom que les autres joueurs voient sur ton profil.",
        ["onboarding.hero_bio_title"] = "Écris une courte bio",
        ["onboarding.hero_bio_sub"] = "Une phrase ou deux sur toi. Facultatif, mais ça aide à te démarquer.",
        ["onboarding.hero_character_title"] = "Ton personnage",
        ["onboarding.hero_character_sub"] = "Parle-nous de ton Guerrier de la Lumière : race, genre et région d'origine.",
        ["onboarding.hero_languages_title"] = "Langues que tu parles",
        ["onboarding.hero_languages_sub"] = "Choisis toutes les langues dans lesquelles tu aimes discuter.",
        ["onboarding.hero_interests_title"] = "Qu'est-ce que tu aimes ?",
        ["onboarding.hero_interests_sub"] = "Choisis le contenu que tu adores dans FFXIV. Tout est facultatif.",
        ["onboarding.hero_lookingfor_title"] = "Que cherches-tu ici ?",
        ["onboarding.hero_lookingfor_sub"] = "Fais savoir aux autres quel type de relation tu recherches.",
        ["onboarding.hero_avatar_title"] = "Ajoute une photo de profil",
        ["onboarding.hero_avatar_sub"] = "Une image nette et tout public de ton personnage. C'est la première chose que les autres voient.",
        ["onboarding.hero_photos_title"] = "Mets-toi en valeur",
        ["onboarding.hero_photos_sub"] = "Ajoute jusqu'à quatre photos portrait de ton personnage.",
        ["onboarding.hero_extras_title"] = "Encore un peu sur toi",
        ["onboarding.hero_extras_sub"] = "Tout est facultatif, mais plus tu partages, meilleurs sont tes matchs. Passe ce que tu veux.",
        ["onboarding.hero_filters_title"] = "Qui aimerais-tu rencontrer ?",
        ["onboarding.hero_filters_sub"] = "Définis tes préférences de match. Tu peux les ajuster à tout moment.",
        ["onboarding.hero_done_title"] = "Tout est prêt !",
        ["onboarding.hero_done_sub"] = "Ton profil est prêt. C'est parti pour swiper.",
        ["onboarding.opt_section_favourites"] = "Favoris FFXIV",
        ["onboarding.opt_section_availability"] = "Quand tu es dispo",
    };
}
