namespace AetherLove.Services.Localization;

internal static class SettingsRu
{
    public static readonly System.Collections.Generic.Dictionary<string, string> Strings = new()
    {
        ["settings.section_plugin_settings"] = "Настройки плагина",
        ["settings.section_phone_size"] = "Размер телефона",
        ["settings.section_plugin_language"] = "Язык плагина",
        ["settings.section_general"] = "Общие настройки",
        ["settings.section_notifications"] = "Уведомления",
        ["settings.section_other"] = "Прочее",
        ["settings.section_danger_zone"] = "Опасная зона",
        ["settings.menu_language_theme"] = "Язык и тема",
        ["settings.menu_appearance"] = "Внешний вид телефона",
        ["settings.menu_chat_colors"] = "Оформление чата",
        ["settings.section_theme"] = "Тема",
        ["settings.back_arrow"] = "← Назад",
        ["settings.chat_own_bg"] = "Фон ваших сообщений",
        ["settings.chat_own_fg"] = "Текст ваших сообщений",
        ["settings.chat_peer_bg"] = "Фон сообщений собеседника",
        ["settings.chat_peer_fg"] = "Текст сообщений собеседника",
        ["settings.chat_reset"] = "Сбросить",

        ["settings.phone_size_small"] = "Маленький",
        ["settings.phone_size_medium"] = "Средний",
        ["settings.phone_size_large"] = "Большой",
        ["settings.phone_size_xl"] = "XL",
        ["settings.phone_size_xxl"] = "XXL",
        ["settings.phone_size_caption"] = "Масштабирует весь телефон. XS подойдёт для небольших экранов и оконного режима; размеры побольше рассчитаны на экраны с высоким разрешением, а XL и XXL - на 4K.",
        ["settings.section_mini_phone_size"] = "Размер мини-телефона",
        ["settings.mini_phone_size_caption"] = "Размер свёрнутого пузырька-виджета (показывается, когда телефон свёрнут). Предпросмотр ниже показывает выбранный размер.",

        ["settings.confirm_before_close"] = "Запрашивать подтверждение перед закрытием телефона",

        ["settings.view_changelog"] = "Просмотреть список изменений",
        ["settings.send_feedback"] = "Обратная связь",
        ["settings.terms_of_service"] = "Условия использования",
        ["settings.cancel"] = "Отмена",

        ["settings.always_blur_nsfw"] = "Всегда размывать NSFW",
        ["settings.always_blur_nsfw_tooltip"] = "Когда включено, NSFW-помеченные дополнительные фото в других профилях размыты, пока вы не нажмёте, чтобы показать каждое. Аватары и главные портреты всегда safe-for-work независимо от этого. Отключение показывает каждое фото как есть.",
        ["settings.nsfw_profile"] = "Мой профиль NSFW (18+)",
        ["settings.nsfw_profile_tooltip"] = "Помечает ваш профиль как для взрослых/NSFW, чтобы его видели только те, у кого включён NSFW. Включается автоматически, когда вы добавляете NSFW-фото или выбираете ролевую игру 18+, и остаётся включённым, пока вы их не уберёте.",
        ["settings.nsfw_profile_locked"] = "Вы не можете отключить это, пока у вас есть NSFW-фото или выбрана ролевая игра 18+ (ERP). Сначала удалите свои NSFW-изображения и снимите выбор ролевой игры 18+.",

        ["settings.enable_notifications"] = "Включить уведомления",
        ["settings.enable_notifications_tooltip"] = "Главный параметр от всех уведомлений. Отключите, чтобы заглушить все игровые объявления в чате, всплывающие окна и звуки ниже.",
        ["settings.enable_notification_sounds"] = "Включить звуки уведомлений",
        ["settings.enable_notification_sounds_tooltip"] = "Звуки уведомлений будут воспроизводиться, только если звук игры и звук спецэффектов не отключены. Громкость регулируется через громкость Windows.",
        ["settings.announce_messages_chat"] = "Объявлять о новых сообщениях в игровом чате",
        ["settings.announce_matches_chat"] = "Объявлять о новых парах в игровом чате",
        ["settings.popup_messages"] = "Показывать всплывающее окно для новых сообщений",
        ["settings.popup_matches"] = "Показывать всплывающее окно для новых пар",
        ["settings.hide_notifications_in_combat"] = "Скрывать уведомления в бою",
        ["settings.hide_notifications_in_combat_tooltip"] = "Когда включено, вы не будете получать никаких уведомлений (объявлений в игровом чате, всплывающих окон и звуков), пока находитесь в бою.",
        ["settings.auto_open_minimized"] = "Открывать свёрнутым автоматически при входе в игру",
        ["settings.pulse_optout"] = "Получайте потрясающие сообщения от команды Aethernet, напоминающие проверить анкеты",
        ["settings.pulse_optout_tooltip"] = "Время от времени AetherLove может оставлять шутливое сообщение в игровом чате. Отключите, чтобы они больше не появлялись.",
        ["settings.combat_behavior"] = "В бою",
        ["settings.combat_behavior_hide"] = "Скрыть телефон",
        ["settings.combat_behavior_minimize"] = "Свернуть в виджет",
        ["settings.combat_behavior_leave_open"] = "Оставить открытым",
        ["settings.notification_sound"] = "Звук уведомления",
        ["settings.play"] = "Воспроизвести",

        ["settings.delete_bullet_matches"] = "Все ваши пары будут удалены.",
        ["settings.delete_bullet_preferences"] = "Ваши предпочтения для пар будут удалены.",
        ["settings.delete_bullet_pictures"] = "Ваши фотографии профиля будут удалены.",
        ["settings.delete_previous_failed"] = "Предыдущая попытка не удалась: {0}",

        ["settings.deleting_title"] = "Удаление аккаунта",
        ["settings.deleting_body"] = "Удаление ваших данных и отказ от пар с контактами",

        ["settings.warnings_title"] = "Предупреждения для аккаунта",
        ["settings.no_warnings"] = "Предупреждений нет.",

        // Moderator messages
        ["settings.modmsg_title"] = "Сообщения от модераторов",
        ["settings.no_modmsg"] = "Сообщений нет.",
        ["settings.back_to_settings_arrow"] = "← Назад к настройкам",

        ["settings.back_to_settings"] = "Назад к настройкам",
        ["settings.feedback_thanks"] = "Спасибо! Ваш отзыв отправлен команде AetherLove.",
        ["settings.feedback_intro"] = "Нашли баг, есть идея или хотите что-то предложить? Дайте нам знать.",
        ["settings.feedback_note"] = "Обратите внимание: форму для обратной связи нельзя использовать для обжалования блокировки или предупреждения.",
        ["settings.feedback_type"] = "Тип",
        ["settings.feedback_kind_bug"] = "Баг",
        ["settings.feedback_kind_improvement"] = "Улучшение",
        ["settings.feedback_kind_other"] = "Другое",
        ["settings.feedback_your_message"] = "Ваше сообщение",
        ["settings.sending"] = "Отправка…",
        ["settings.submit"] = "Отправить",
        ["settings.feedback_rate_limited"] = "Вы можете отправлять отзыв только {0} раз в час. Пожалуйста, попробуйте позже.",
        ["settings.feedback_send_failed"] = "Не удалось отправить ваш отзыв. Пожалуйста, попробуйте снова.",

        ["settings.contributors"] = "Участники",
        ["settings.contributors_thanks_title"] = "Спасибо",
        ["settings.contributors_intro"] = "AetherLove был бы невозможен без:",
        ["settings.contributors_leads"] = "Руководители проекта: Astraea & Nihal",
        ["settings.contributors_council"] = "The Chon-Chon Council",
        ["settings.contributors_moderation"] = "Модерация: Su",
        ["settings.contributors_translators"] = "Переводчики: Tears, Mufami, Terashi, Su, Astraea",
        ["settings.contributors_xivauth"] = "XIVAuth by KazWolfe",
        ["settings.contributors_punish"] = "Puni.sh",
        ["settings.contributors_dalamud"] = "The Dalamud project",
        ["settings.contributors_vavenn"] = "Vavenn (современный режим Stacker)",
        ["settings.contributors_testers"] = "Всем замечательным бета-тестерам по всей Эорзее.",

        // added after update 1.4.0
        ["settings.lock_position"] = "Зафиксировать положение",
        ["settings.lock_position_caption"] = "Зафиксировав положение, вы не сможете перемещать телефон (окно приложения и виджет): они останутся на месте.",

        // added after update 1.4.3
        ["settings.show_during_gpose"] = "Показывать телефон во время GPose",
        ["settings.show_during_gpose_tooltip"] = "Оставляет телефон видимым во время GPose (/gpose) и переопределяет настройку Dalamud'а, скрывающую окна плагинов во время GPose.",
        ["settings.hide_during_cutscene"] = "Показывать телефон во время катсцен",
        ["settings.hide_during_cutscene_tooltip"] = "Оставляет телефон видимым во время катсцены. При отключении телефон скрывается во время катсцен (по умолчанию).",
        ["settings.tomestone_emote"] = "Показывать эмоцию чтения при использовании приложения",
        ["settings.tomestone_emote_tooltip"] = "Пока телефон открыт, персонаж проигрывает эмоцию /tomescroll, будто читает его. Срабатывает только в безопасной зоне и никогда не прерывает другую эмоцию.",

        // added after update 1.5.0
        ["settings.menu_supporter"] = "Поддержать проект",
        ["settings.supporter_link_button"] = "Привязать аккаунт Patreon",
        ["settings.supporter_contacting"] = "Подключение к серверу...",
        ["settings.supporter_awaiting_browser"] = "Завершите привязку в браузере, затем вернитесь сюда.",
        ["settings.supporter_open_again"] = "Открыть браузер снова",
        ["settings.supporter_cancel"] = "Отмена",
        ["settings.supporter_you_are_title"] = "Вы спонсор.",
        ["settings.supporter_you_are_body"] = "Ваш аккаунт Patreon успешно привязан, и статус поддержавшего включён.",
        ["settings.supporter_nomember_title"] = "Подписка не найдена",
        ["settings.supporter_nomember_body"] = "Ваш аккаунт Patreon привязан, но активная подписка не найдена. Если вы только что оформили её, статус поддержавшего будет выдан автоматически в течение нескольких часов. Вы также можете отвязать аккаунт и попробовать снова, когда подписка на Patreon станет активной.",
        ["settings.supporter_not_entitled"] = "Активная подписка пока не найдена. Если вы только что оформили подписку, роль будет выдана автоматически в течение нескольких часов.",
        ["settings.supporter_unlink_button"] = "Отвязать Patreon",
        ["settings.supporter_unlink_confirm"] = "Отвязать этот аккаунт Patreon? Ваша роль спонсора будет удалена.",
        ["settings.supporter_failed"] = "Не удалось выполнить привязку. Попробуйте ещё раз.",
        ["settings.supporter_retry"] = "Попробовать снова",
        ["settings.supporter_unavailable"] = "Привязка поддержавших сейчас недоступна. Загляните позже.",
        ["settings.supporter_link_expired"] = "Время запроса на привязку истекло. Попробуйте ещё раз.",

        // added after update 1.5.1
        ["settings.supporter_linked"] = "Привязано",
        ["settings.supporter_title"] = "Станьте поддержавшим",
        ["settings.supporter_intro"] = "Вы можете финансово поддержать проект через наш Patreon. Все функции AetherLove доступны бесплатно для всех, и ничто не находится и никогда не будет скрыто за оплатой. Спонсоры получают в благодарность за поддержку: небольшое расширение лимитов и пару «светяшек». Это наш способ сказать, что без вас мы бы не справились.",
        ["settings.supporter_perks_header"] = "Привилегии AetherLove",
        ["settings.supporter_msgr_perks_header"] = "Привилегии мессенджера",
        ["settings.supporter_perk_msgr_groups_title"] = "Большие групповые чаты",
        ["settings.supporter_perk_msgr_groups_body"] = "Добавляй сколько угодно друзей по коду, веди до 10 групповых чатов одновременно и собирай до 15 человек в каждом.",
        ["settings.supporter_perk_msgr_storage_title"] = "Больше места в мессенджере",
        ["settings.supporter_perk_msgr_storage_body"] = "Больше места для селфи и картинок, которыми делишься, и увеличенный срок хранения, прежде чем они исчезнут.",
        ["settings.supporter_perk_profiles_title"] = "Два профиля",
        ["settings.supporter_perk_profiles_body"] = "Веди сразу два профиля AetherLove: удобно для нескольких персонажей или чтобы разделять ролевую и обычную стороны.",
        ["settings.supporter_perk_photos_title"] = "Больше места, чтобы блистать",
        ["settings.supporter_perk_photos_body"] = "До 5 дополнительных фото профиля и ещё 2 на каждого RP-персонажа.",
        ["settings.supporter_perk_superlike_title"] = "Суперлайк",
        ["settings.supporter_perk_superlike_body"] = "Возможность кому-то дать понять, что этот профиль вам очень нравится. Он получит уведомление о вашем суперлайке, и если ответит взаимностью, пара создастся сразу.",
        ["settings.supporter_perk_rewinds_title"] = "5 возвратов в день",
        ["settings.supporter_perk_rewinds_body"] = "Передумали? Поспешили с решением? Отматывайте назад до 5 раз в день вместо одного.",
        ["settings.supporter_perk_analytics_title"] = "Более расширенная аналитика",
        ["settings.supporter_perk_analytics_body"] = "Дополнительная аналитика и статистика о том, кто вас любит и как на самом деле работает ваш профиль.",
        ["settings.supporter_perk_colors_title"] = "Живые цвета",
        ["settings.supporter_perk_colors_body"] = "Ваше имя переливается как радуга, медленно меняя цвета, мимо которых невозможно пролистать.",
        ["settings.supporter_perk_badge_title"] = "Знак спонсора",
        ["settings.supporter_perk_badge_body"] = "Метка спонсора и маленькая звёздочка рядом с вашим именем. Тот самый тихий значок, заслуженный.",
        ["settings.supporter_how_heading"] = "Как это работает",
        ["settings.supporter_how_intro"] = "У нас есть три уровня по разной цене. Выберите тот, что пожелаете. И все они открывают ровно одни и те же бонусы. Ни один уровень не даёт больше другого.",
        ["settings.supporter_step1_title"] = "1. Оформите подписку на Patreon",
        ["settings.supporter_step1_body"] = "Создайте аккаунт Patreon и оформите подписку на любой из наших спонсорских уровней, все они открывают одни и те же бонусы.",
        ["settings.supporter_step2_title"] = "2. Привяжите к AetherLove",
        ["settings.supporter_step2_body"] = "Привяжите свой аккаунт Patreon, нажав кнопку ниже. Если у вас есть активная подписка, ваш аккаунт сразу станет премиальным.",
        ["settings.supporter_become"] = "Стать спонсором на Patreon",
        ["settings.supporter_data_note"] = "Только идентификатор пользователя Patreon используется для идентификации поддержавших. Мы никогда не храним ваше имя, почту или социальные аккаунты.",
        ["settings.sup_learn_title"] = "Поддержите AetherLove",
        ["settings.sup_learn_body"] = "Этот пользователь поддерживает AetherLove. Хотите узнать, что даёт поддержка проекта? Дополнительные фото, суперлайки, стили имени, бонусная статистика и многое другое.",
        ["settings.sup_learn_more"] = "Подробнее",

        ["settings.sup_thanks_title"] = "Вы теперь спонсор!",
        ["settings.sup_thanks_sub"] = "Спасибо за поддержку AetherLove!",
        ["settings.sup_thanks_body"] = "Ваша поддержка помогает серверам работать. Наслаждайтесь новыми бонусами!",
        ["settings.sup_thanks_continue"] = "Продолжить",
        // AetherLove-app notification master (added after update 1.5.1)
        ["settings.enable_aetherlove_notifications"] = "Включить уведомления AetherLove",
        ["settings.menu_nsfw"] = "Настройки NSFW",
        // DTR server-info-bar entries (added after update 1.5.1)
        ["dtr.chats"] = "Чаты",
        ["dtr.matches"] = "Пары",
        ["dtr.news"] = "Новости",
        ["settings.show_dtr_count"] = "Показывать счётчики непрочитанного в строке информации о сервере",
        ["settings.show_dtr_count_tooltip"] = "Добавляет записи AetherLove (чаты, пары, новости) в игровую строку информации о сервере, рядом с FPS и пингом. Каждая показывает счётчик непрочитанного и скрывается, когда ничего нового нет. Отдельные записи также можно скрыть в настройках строки информации о сервере Dalamud.",

        // Multi-profile: the profile picker, switching, and delete-profile (added after update 1.5.1)
        ["settings.menu_switch_profile"] = "Сменить профиль",
        ["settings.delete_profile"] = "Удалить профиль",
        ["settings.delete_profile_warning_intro"] = "Удаление этого профиля AetherLove необратимо. Прежде чем продолжить, вот что именно произойдёт:",
        ["settings.delete_bullet_profile"] = "Этот профиль знакомств будет удалён без возможности восстановления.",
        ["settings.delete_profile_account_stays"] = "Ваш аккаунт AetherOS и остальные приложения не пострадают. Вы можете создать новый профиль в любой момент.",
        ["picker.title"] = "Выбор профиля",
        ["picker.subtitle"] = "Кто сегодня свайпает?",
        ["picker.current"] = "Текущий профиль",
        ["picker.banned"] = "Заблокирован",
        ["picker.finish_setup"] = "Завершить настройку",
        ["picker.locked"] = "Слот для саппортеров",
        ["picker.create"] = "Новый профиль",
        ["picker.create_sub"] = "Создать новый профиль знакомств",
        ["picker.create_secondary"] = "Создать второй профиль",
        ["picker.create_supporter_pitch"] = "Второй профиль AetherLove доступен саппортерам. Поддержите проект, чтобы открыть ещё одну личность для знакомств со своими совпадениями и чатами, полностью отдельную от первой.",
        ["picker.locked_supporter_pitch"] = "Этот профиль занимает слот для саппортеров. Продлите статус саппортера, чтобы снова открыть его; ничего не удалено, профиль лишь заблокирован.",
        ["picker.switching"] = "Смена профиля...",
        ["picker.switch_failed"] = "Не удалось сменить профиль. Попробуйте ещё раз.",
        ["picker.share_as_title"] = "Поделиться как...",
        ["picker.share_as_body"] = "От какого профиля поделиться?",
        ["picker.share_as_current"] = "{0} (текущий)",

        // Messenger (added after update 1.5.1)
        ["dtr.messenger"] = "Messenger",

        // added after update 2.0.0.0
        ["settings.section_time_format"] = "Формат времени",
        ["settings.time_24h"] = "24-часовой",
        ["settings.time_12h"] = "12-часовой",

        // added after update 2.0.1
        ["settings.audio_sounds_off"] = "Звуки уведомлений сейчас отключены.",
        ["settings.audio_sounds_enable"] = "Включить звуки уведомлений",
        ["settings.audio_volume"] = "Громкость уведомлений",
        ["settings.audio_device"] = "Устройство вывода",
        ["settings.audio_device_default"] = "Системное по умолчанию",
        ["settings.audio_test"] = "Проиграть тестовый звук",
        ["settings.audio_test_ok"] = "Играет! Если ничего не слышно, попробуйте другое устройство вывода выше.",
        ["settings.font_header"] = "Шрифт",
        ["settings.font_caption"] = "Применяется ко всему тексту на телефоне. Символы, которых нет в шрифте, отображаются стандартным шрифтом.",
        ["settings.font_default"] = "Стандартный",
        ["settings.phone_size_header"] = "Размер телефона",
        ["settings.mini_phone_size_header"] = "Размер миниатюры",

        // added after update 2.1.3
        ["settings.staff_notices_title"] = "Сообщения от команды",
        ["settings.staff_notices_empty"] = "От команды пока ничего нет.",
        ["settings.staff_warnings_section"] = "Предупреждения",
        ["settings.staff_messages_section"] = "Сообщения",

        // added after update 2.2.3
        ["settings.premium_themes"] = "Премиум-темы",
        ["settings.premium_refresh"] = "Обновить тему",
        ["settings.premium_backgrounds"] = "Премиум-обои",
        ["settings.premium_enable_failed"] = "Не удалось сменить",
        ["settings.phone_size_xs"] = "XS",
        ["settings.supporter_store_perks_header"] = "В магазине",
        ["settings.supporter_perk_store_title"] = "Скидка 10% в магазине",
        ["settings.supporter_perk_store_body"] = "Спонсоры платят на 10% меньше за каждую покупку в магазине, и это вдобавок к текущим распродажам.",

        // Timers (added after update 2.3.3)
        ["dtr.timers"] = "{0} {1}",
        // text translation (added after update 2.4.0)
        ["settings.section_translation"] = "Перевод текстов",
        ["settings.translation_enable"] = "Включить перевод",
        ["settings.translation_language"] = "Переводить на",
        ["settings.translation_search"] = "Поиск языков...",
    };
}
