namespace AetherLove.Services.Localization;

internal static class HubErrorsEn
{
    public static readonly System.Collections.Generic.Dictionary<string, string> Strings = new()
    {
        ["huberror.generic"] = "An unexpected server error occurred.",
        ["huberror.generic_detail"] = "An error has occurred: {0}",
        ["huberror.invalid_request"] = "The server rejected the request. If this keeps happening, please update the plugin.",
        ["huberror.unauthenticated"] = "Your session is no longer valid. Please log in again.",
        ["huberror.banned"] = "This AetherLove profile is banned.",
        ["huberror.account_banned"] = "Your account has been banned.",
        ["huberror.rate_limited"] = "You're doing that too often. Please try again shortly.",
        ["huberror.profile_not_found"] = "Profile not found.",
        ["huberror.profile_not_visible"] = "This profile is not available.",
        ["huberror.deck_expired"] = "This profile is no longer in your deck. Refresh your deck and try again.",
        ["huberror.no_active_match"] = "You are no longer matched with this player.",
        ["huberror.peer_keys_missing"] = "This user has not set up E2E encryption yet and can't chat, please try again later.",
        ["huberror.key_bundle_exists"] = "Encryption keys are already set up for this account.",
        ["huberror.message_too_large"] = "This message is too long to send.",
        ["huberror.bio_too_long"] = "Your bio exceeds the {0}-character limit.",
        ["huberror.lalafell_erp"] = "Adult roleplay is not available for Lalafell characters.",
        ["huberror.lalafell_nsfw"] = "NSFW features are not available for Lalafell characters.",
        ["huberror.lalafell_nsfw_photo"] = "NSFW photos are not available for Lalafell characters.",
        ["huberror.nsfw_disable_blocked"] = "Remove your NSFW photos and turn off 18+ roleplay before disabling NSFW.",
        ["huberror.img_too_large"] = "Image is too large ({0} MB). Max is {1} MB.",
        ["huberror.img_dimensions_too_large"] = "Image is too large ({0}×{1}). The longest side may be {2}px.",
        ["huberror.img_crop_too_small"] = "The crop area is too small (min {0}px per side).",
        ["huberror.img_decode_failed"] = "Could not read the image. Supported formats: PNG, JPEG, WebP, GIF.",
        ["huberror.img_payload_invalid"] = "The photo could not be uploaded. Please pick the image again.",
        ["huberror.report_self"] = "You cannot report yourself.",
        ["huberror.report_reason_required"] = "Please describe the problem.",
        ["huberror.report_reason_too_long"] = "The reason is too long (max {0} characters).",
        ["huberror.report_target_gone"] = "That profile no longer exists.",
        ["huberror.report_duplicate"] = "You've already reported this user recently. Our team is reviewing it.",
        ["huberror.feedback_required"] = "Please enter a message before sending.",
        // added after update (1.3.1)
        ["huberror.reswipe_nothing_to_undo"] = "There's nothing to undo.",
        ["huberror.reswipe_already_matched"] = "You cannot reswipe on a matched profile.",
        ["huberror.reswipe_quota_exhausted"] = "You've used your reswipe for today.",
        ["huberror.superlike_quota_exhausted"] = "You're out of superlikes for today.",

        // added after update 1.4.3
        ["huberror.character_limit_reached"] = "You can have at most {0} RP characters.",
        ["huberror.character_name_invalid"] = "Character names must be 3-50 characters.",
        ["huberror.character_not_found"] = "That character no longer exists. Reload and try again.",

        // added after update 1.5.0
        ["huberror.patreon_disabled"] = "Patreon linking is currently unavailable.",
        ["huberror.patreon_already_linked"] = "A Patreon account is already linked to your profile.",
        ["huberror.patreon_not_linked"] = "No Patreon account is linked to your profile.",
        ["huberror.patreon_account_taken"] = "That Patreon account is already linked to another AetherLove account.",
        ["huberror.patreon_link_failed"] = "We couldn't complete the Patreon link. Please try again.",
        ["huberror.places_disabled"] = "Places is currently unavailable.",
        ["huberror.venue_not_found"] = "This venue no longer exists.",
        ["huberror.venue_limit_reached"] = "You've reached the limit of {0} venues.",
        ["huberror.venue_name_invalid"] = "The venue name must be 3 to 60 characters.",
        ["huberror.venue_description_too_long"] = "The description exceeds the {0}-character limit.",
        ["huberror.venue_times_invalid"] = "One of the opening times is invalid.",
        ["huberror.venue_times_too_many"] = "A venue can have at most {0} opening times.",
        ["huberror.venue_review_own"] = "You can't review your own venue.",
        ["huberror.venue_review_too_long"] = "Your review exceeds the {0}-character limit.",
        ["huberror.venue_review_rating_invalid"] = "Pick a rating from 1 to 5 stars.",
        ["huberror.venue_rsvp_invalid"] = "That opening is no longer available for RSVPs.",

        // Multi-profile (added after update 1.5.1)
        ["huberror.profile_locked"] = "This profile is in a supporter slot and is currently locked.",
        ["huberror.profile_limit_reached"] = "You have reached your profile limit.",

        // Messenger (added after update 1.5.1)
        ["huberror.messenger_disabled"] = "The messenger is currently unavailable.",
        ["huberror.msgr_code_not_found"] = "No user with that code was found.",
        ["huberror.msgr_self"] = "That is your own code.",
        ["huberror.msgr_already_contact"] = "You are already contacts.",
        ["huberror.msgr_request_pending"] = "Your request is still pending.",
        ["huberror.msgr_contact_limit"] = "You have reached your contact limit of {0}.",
        ["huberror.msgr_pending_limit"] = "You have too many pending requests (max {0}).",
        ["huberror.msgr_not_contact"] = "You are not contacts with this user.",
        ["huberror.msgr_group_limit"] = "You can own at most {0} groups.",
        ["huberror.msgr_group_full"] = "Groups can have at most {0} members.",
        ["huberror.msgr_not_owner"] = "Only the group owner can do that.",
        ["huberror.msgr_not_member"] = "You are not a member of this group.",
        ["huberror.msgr_group_name_invalid"] = "That group name cannot be used.",
        ["huberror.msgr_adds_disabled"] = "This user does not accept contact requests.",
        ["huberror.msgr_keys_missing"] = "Encryption keys are out of date; please try again in a moment.",
        ["huberror.msgr_image_rejected"] = "That image can't be sent. Please choose a different image, or contact support if you think this is a mistake.",
        ["huberror.msgr_storage_full"] = "Your image storage is full. Delete some images or wait for older ones to expire, then try again.",
        ["huberror.msgr_image_too_large"] = "That image is too large.",
        ["huberror.msgr_image_invalid"] = "That image couldn't be read.",
        // levemetes (added after update 2.0.1)
        ["huberror.levemetes_disabled"] = "Levemetes is currently disabled.",
        ["huberror.leve_not_found"] = "This listing no longer exists.",
        ["huberror.leve_invalid"] = "The ad could not be saved. Please check your entries.",
        ["huberror.leve_limit_reached"] = "You already have {0} ads. Delete one or let one expire first.",
        ["huberror.leve_too_long"] = "That text is too long (max {0} characters).",
        ["huberror.leve_image_rejected"] = "This picture can't be uploaded. Pick a different one, or contact support if you believe this is a mistake.",
        ["huberror.leve_review_own"] = "You can't review your own ad.",
        ["huberror.leve_review_too_long"] = "Your review is too long (max {0} characters).",
        ["huberror.leve_review_rating_invalid"] = "Pick a star rating between 1 and 5.",
        ["huberror.leve_reviews_disabled"] = "The poster has turned off reviews on this ad.",
        ["huberror.leve_renew_too_soon"] = "This ad was renewed recently. Try again later.",
        // wayfinder (added after update 2.1.3)
        ["huberror.wayfinder_disabled"] = "Wayfinder is currently disabled.",
        ["huberror.wayfinder_no_challenges"] = "No challenges are available right now. Check back soon!",
        ["huberror.wayfinder_no_reachable"] = "Every challenge left is in a zone you haven't unlocked yet. Attune to more aetherytes and come back!",
        ["huberror.wayfinder_daily_limit"] = "You've used all {0} starts for today.",
        ["huberror.wayfinder_active_exists"] = "You already have a challenge in progress.",
        ["huberror.wayfinder_no_active"] = "This challenge is no longer active.",
        ["huberror.wayfinder_expired"] = "Time's up! This challenge has expired.",
        ["huberror.wayfinder_not_scout"] = "You don't have permission to add waypoints.",
        ["huberror.wayfinder_invalid"] = "The waypoint could not be saved. Please check your entries.",
        ["huberror.wayfinder_image_rejected"] = "This picture can't be uploaded. Take a different one, or contact support if you believe this is a mistake.",
        // holiday mode (added after update 2.0.1)
        ["huberror.holiday_message_too_long"] = "Your holiday message is too long (max {0} characters).",
        ["huberror.holiday_message_invalid"] = "This holiday message can't be used. Please reword it.",
        // yapper (added after update 2.1.3)
        ["huberror.yapper_disabled"] = "Yapper is currently disabled.",
        ["huberror.yapper_no_profile"] = "Set up your Yapper profile first.",
        ["huberror.yapper_banned"] = "You can't post right now. Contact support if you think this is a mistake.",
        ["huberror.yapper_handle_taken"] = "That handle is already taken.",
        ["huberror.yapper_handle_invalid"] = "Handles are 3-20 characters: letters, numbers and underscores.",
        ["huberror.yapper_handle_rejected"] = "That handle can't be used. Please pick another.",
        ["huberror.yapper_profile_rejected"] = "That text can't be used on your profile. Please reword it.",
        ["huberror.yapper_rename_too_soon"] = "You changed your handle recently. Try again in {0} days.",
        ["huberror.yapper_blocked"] = "You can't interact with this user.",
        ["huberror.yap_not_found"] = "This yap no longer exists.",
        ["huberror.yap_too_long"] = "That yap is too long (max {0} characters).",
        ["huberror.yap_too_many_images"] = "A yap can have at most {0} pictures.",
        ["huberror.yap_image_rejected"] = "That picture can't be posted. Pick a different one, or contact support if you believe this is a mistake.",
        ["huberror.yap_image_too_large"] = "That picture is too large.",
        ["huberror.yap_image_invalid"] = "That picture couldn't be read.",
        ["huberror.yap_embed_invalid"] = "The shared content is no longer available.",
        ["huberror.yap_edit_window_closed"] = "The edit window for this yap has closed.",
        ["huberror.yap_nsfw_mismatch"] = "Your content rating doesn't allow that.",
        ["huberror.yap_invalid"] = "The yap could not be saved. Please check your entries.",
        ["huberror.yap_dm_not_allowed"] = "This user can't receive your messages.",
        ["huberror.yap_dm_keys_missing"] = "@{0} still needs to finish setting up. Try messaging them again in a little while.",

        // store (added after update 2.2.3)
        ["huberror.store_disabled"] = "The store is closed for maintenance right now.",
        ["huberror.store_product_not_found"] = "That item no longer exists.",
        ["huberror.store_product_unavailable"] = "That item isn't for sale right now.",
        ["huberror.store_insufficient_sparks"] = "Not enough sparks: this costs {0} and you have {1}.",
        ["huberror.store_limit_reached"] = "You already own the maximum ({0}) of this item.",
        ["huberror.store_quantity_invalid"] = "That quantity isn't allowed.",
        ["huberror.store_conflict"] = "The store hiccuped mid-purchase. Nothing was charged twice; just try again.",
        ["huberror.aetherling_disabled"] = "It is not listening right now.",
        ["huberror.aetherling_exists"] = "There is already one of these.",
        ["huberror.aetherling_none"] = "There is nothing here to give it to.",
        ["huberror.aetherling_insufficient"] = "Not enough sparks: it wants {0}, you have {1}.",
        ["huberror.aetherling_gated"] = "Not yet. Something has to happen first. Try again in {0} minutes.",
        ["huberror.aetherling_complete"] = "It will not take any more.",
        ["huberror.aetherling_unready"] = "Not yet. It is not ready for that.",
        ["huberror.aetherling_named"] = "It already has its name.",
        ["huberror.aetherling_name_invalid"] = "That name will not do. Try another.",

        // echo (added after update 2.2.3)
        ["huberror.echo_disabled"] = "Watching together is switched off right now.",
        ["huberror.echo_room_not_found"] = "That watch party has already ended.",
        ["huberror.echo_room_full"] = "This room is full ({0} people).",
        ["huberror.echo_not_member"] = "You aren't in that room.",
        ["huberror.echo_not_owner"] = "Only whoever started the room can do that.",
        ["huberror.echo_host_only"] = "The host is driving playback right now.",
        ["huberror.echo_kicked"] = "You were removed from that room.",
        ["huberror.echo_playlist_full"] = "The queue is full ({0} videos).",
        ["huberror.echo_live_room_exists"] = "You already have a room running. End it to start another one.",
        ["huberror.echo_invalid_video"] = "That doesn't look like a YouTube link.",
        ["huberror.echo_name_invalid"] = "That room name can't be used.",
        ["huberror.hangout_watch_room_invalid"] = "That watch party isn't available any more.",
    };
}
