namespace AetherLove.Services.Localization;

internal static class ChatFr
{
    public static readonly System.Collections.Generic.Dictionary<string, string> Strings = new()
    {
        // Chat
        ["chat.no_conversation_selected"] = "Aucune conversation sélectionnée.",
        ["chat.unreadable_message"] = "[message illisible]",
        ["chat.report_submitted_toast"] = "Signalement envoyé. Notre équipe de modération l'examinera.",
        ["chat.view_profile"] = "Voir le profil",
        ["chat.back_to_matches"] = "Retour aux correspondances",
        ["chat.menu_open_profile"] = "Ouvrir le profil",
        ["chat.menu_copy_message"] = "Copier le message",
        ["chat.menu_pin"] = "Épingler le chat",
        ["chat.menu_unpin"] = "Désépingler le chat",
        ["chat.menu_unmatch"] = "Annuler la correspondance",
        ["chat.menu_block"] = "Bloquer",
        ["chat.menu_report_user"] = "Signaler l'utilisateur",
        ["chat.unmatch_title"] = "Annuler la correspondance",
        ["chat.unmatch_body"] = "Lorsque vous annulez la correspondance avec ce joueur, le chat sera masqué pour les deux personnes. Si vous correspondez à nouveau plus tard, votre historique réapparaîtra.",
        ["chat.unmatch_confirm"] = "Annuler la correspondance",
        ["chat.block_title"] = "Bloquer l'utilisateur",
        ["chat.block_body"] = "Lorsque vous bloquez quelqu'un, le chat est masqué pour vous deux. Cette personne n'apparaîtra plus dans vos correspondances.",
        ["chat.block_confirm"] = "Bloquer",
        ["chat.cancel"] = "Annuler",
        ["chat.loading_messages"] = "Chargement des messages…",
        ["chat.e2e_self_broken"] = "Le chiffrement de ce profil n'est pas encore configuré sur cet appareil, les messages ne peuvent donc pas être envoyés ni lus ici.",
        ["chat.e2e_setup_button"] = "Configurer le chiffrement",
        ["chat.seen_suffix"] = " · vu",
        ["chat.send"] = "Envoyer",
        ["chat.emoji_button"] = ":)",
        ["chat.system_notice_line1"] = "Ceci est un chat privé entre vous et {0}. Ce chat est chiffré de bout en bout. L'équipe d'AetherLove ne peut pas lire vos messages. Le menu en haut à droite vous permet d'annuler la correspondance, de la bloquer ou de la signaler.",
        ["chat.system_notice_line2"] = "N'oubliez pas : {0} ne connaît pas votre nom complet ni votre localisation tant que vous ne les partagez pas. Prenez soin de votre vie privée et ne partagez davantage que lorsque vous êtes prêt.",
        ["chat.i_understand"] = "J'ai compris",
        ["chat.report_title"] = "Signaler l'utilisateur",
        ["chat.report_reason_prompt"] = "Veuillez décrire la raison de votre signalement :",
        ["chat.report_agree"] = "J'accepte de soumettre un signalement à l'encontre de {0}",
        ["chat.report_agree_contents"] = "J'accepte d'envoyer le contenu de cette conversation à l'équipe d'AetherLove",
        ["chat.submitting"] = "Envoi…",
        ["chat.submit"] = "Envoyer",

        // Verify encryption
        ["verify.title"] = "Vérifier le chiffrement",
        ["verify.intro"] = "AetherLove chiffre cette conversation de bout en bout : vous seul et {0} pouvez la lire, pas même notre équipe. Le motif tissé ci-dessous est généré à partir de vos deux clés de chiffrement.",
        ["verify.unavailable"] = "La vérification n'est pas encore prête. Elle sera disponible une fois que vous aurez tous les deux configuré le chiffrement et échangé vos clés.",
        ["verify.how"] = "Comparez ce motif et ce code avec {0} par chat vocal ou en personne. S'ils correspondent, personne n'intercepte votre conversation. S'ils ne correspondent pas, ne partagez plus rien de sensible et contactez le support.",
        ["verify.your_key"] = "Votre clé publique",
        ["verify.their_key"] = "Clé publique de {0}",
        ["verify.keys_explain"] = "Les clés publiques peuvent être partagées sans risque ; c'est ainsi que vos applications se reconnaissent. Les clés privées correspondantes ne quittent jamais vos appareils, donc aucun serveur (pas même le nôtre) ne peut lire vos messages.",
        ["verify.back"] = "Retour au chat",

        // ChatListScreen
        ["chat.preview_me_prefix"] = "Moi : ",
        ["chat.preview_venue"] = "A partagé un établissement",
        ["chat.matches_title"] = "Correspondances",
        ["chat.show_search"] = "Afficher la recherche",
        ["chat.hide_search"] = "Masquer la recherche",
        ["chat.search_hint"] = "Nom ou message",
        ["chat.searching"] = "Recherche en cours…",
        ["chat.search_no_results"] = "Aucun résultat trouvé",
        ["chat.matches_load_error"] = "Impossible de charger les correspondances : {0}",
        ["chat.connectivity_error"] = "Nous n'avons pas pu nous connecter au serveur AetherLove. Veuillez réessayer ou consulter l'état du serveur sur Discord.",
        ["chat.empty_state"] = "Vous n'avez pas encore de correspondances, mais cela changera bientôt. Continuez à swiper !",
        ["chat.new_match"] = "nouvelle correspondance",
        ["chat.say_hi"] = "Vous avez un match, dites bonjour !",
        ["chat.time_ago_minutes"] = "il y a {0} min",
        ["chat.time_ago_hours"] = "il y a {0} h",
        ["chat.time_ago_days"] = "il y a {0} j",

        // added after update (1.3.1)
        ["chat.you"] = "Vous",
        ["chat.reply"] = "Répondre",
        ["chat.pin_message"] = "Épingler le message",
        ["chat.unpin_message"] = "Détacher le message",
        ["chat.pinned_messages"] = "Messages épinglés",
        ["chat.pinned_messages_menu"] = "Messages épinglés ({0})",
        ["chat.quote_unavailable"] = "(message d'origine indisponible)",
        ["chat.quote_generic"] = "(message)",
        ["chat.replying_to"] = "Réponse à {0}",
        ["chat.reaction_remove_hint"] = "cliquez pour retirer",
        ["chat.jump"] = "Aller",
        ["chat.unpin"] = "Détacher",

        // added after update 1.4.3
        ["chat.menu_search"] = "Rechercher des messages",
        ["chat.search_messages_hint"] = "Rechercher dans cette conversation...",
        ["chat.category_new"] = "Nouvelle catégorie",
        ["chat.category_edit"] = "Modifier la catégorie",
        ["chat.category_delete"] = "Supprimer la catégorie",
        ["chat.category_delete_body"] = "Voulez-vous vraiment supprimer {0} ? Les conversations qu'elle contient reviendront dans votre liste de correspondances.",
        ["chat.category_delete_confirm"] = "Supprimer",
        ["chat.category_name_hint"] = "Nom de la catégorie",
        ["chat.category_create"] = "Créer",
        ["chat.category_save"] = "Enregistrer",
        ["chat.menu_move_to_category"] = "Déplacer vers une catégorie",
        ["chat.menu_remove_from_category"] = "Retirer de la catégorie",
        ["chat.category_empty"] = "Aucune conversation dans cette catégorie pour l'instant. Glissez-y une conversation ou faites un clic droit sur une conversation et choisissez Déplacer vers une catégorie.",
        ["chat.category_count"] = "Conversations : {0}",
        ["chat.category_archive_default"] = "Archives",
        ["chat.all_categorized"] = "Toutes vos conversations sont rangées dans des catégories",

        // added after update 1.5.1
        ["chat.menu_view_blocked"] = "Voir les bloqués",
        ["blocked.title"] = "Utilisateurs bloqués",
        ["blocked.intro_body"] = "Vous pouvez débloquer n'importe qui dans cette liste. Le déblocage ne recrée pas le match. Vous pourrez à nouveau vous croiser dans le deck.",
        ["blocked.empty"] = "Vous n'avez bloqué personne.",
        ["blocked.loading"] = "Chargement...",
        ["blocked.since"] = "Bloqué le {0}",
        ["blocked.unblock"] = "Débloquer",
        ["blocked.confirm_title"] = "Débloquer {0} ?",
        ["blocked.confirm_body"] = "Aucun match automatique ne sera recréé, mais vous pourrez à nouveau vous croiser dans le deck.",
        // generic share system (added after update 1.5.1)
        ["chat.news_card_label"] = "Actualités",
        ["chat.news_card_view"] = "Lire cet article",
        ["chat.news_card_unavailable"] = "Cet article n'est plus disponible",
        ["chat.preview_news"] = "A partagé une actualité",

        // Messenger invite bridge (added after update 1.5.1)
        ["chat.menu_invite_messenger"] = "Inviter sur Messenger",
        ["chat.msgr_card_title"] = "Invitation Messenger",
        ["chat.msgr_card_hint"] = "Touchez pour ajouter ce code à vos contacts",
        ["chat.preview_messenger"] = "A envoyé une invitation Messenger",
        // Key reset notices (added after update 1.5.1)
        ["chat.keys_reset_peer"] = "{0} a réinitialisé ses clés de chiffrement E2E",
        ["chat.keys_reset_you"] = "Vous avez réinitialisé vos clés de chiffrement. Vous ne pouvez plus lire les messages antérieurs.",
        // calendar event share
        ["chat.preview_calevent"] = "A partagé un événement",
        ["chat.preview_location"] = "A partagé une position",
        ["chat.calevent_rsvp"] = "J'y serai",
        ["chat.calevent_add"] = "Ajouter au calendrier",
        // levemetes (added after update 2.0.1)
        ["chat.preview_levemete"] = "Annonce partagée",
        ["chat.preview_market"] = "A partagé une trouvaille du marché",
        ["chat.market_card_label"] = "Marché",
        ["chat.market_card_view"] = "Voir sur le marché",
        ["chat.leve_kind_looking"] = "Recherche",
        ["chat.leve_kind_offering"] = "Propose",
        ["chat.leve_cat_1"] = "Décoration de maison",
        ["chat.leve_cat_2"] = "Gposing",
        ["chat.leve_cat_3"] = "Commissions",
        ["chat.leve_cat_4"] = "DJs",
        ["chat.leve_cat_5"] = "Personnel de venue",
        ["chat.leve_cat_6"] = "Bardes & groupes",
        ["chat.leve_cat_7"] = "Services mercenaires",
        ["chat.leve_cat_8"] = "Artisanat & récolte",
        ["chat.leve_cat_9"] = "Services 18+",
        ["chat.leve_cat_unknown"] = "Autre",
        ["chat.leve_card_view"] = "Ouvrir l'annonce",
        ["chat.leve_card_loading"] = "Chargement de l'annonce...",
        ["chat.leve_card_unavailable"] = "Cette annonce n'est plus disponible.",
        // user notes (added after update 2.0.1)
        ["chat.menu_user_note"] = "Note sur la personne",
        ["chat.note_hint"] = "Vous seul pouvez voir cette note. Elle est enregistrée sur cet ordinateur et n'est jamais envoyée nulle part.",
        ["chat.note_save"] = "Enregistrer la note",
        ["chat.note_tooltip"] = "Votre note :",
        // added after update 2.0.0.0 (message delete)
        ["chat.delete_message"] = "Supprimer le message",
        ["chat.delete_message_body"] = "Supprimer ce message pour tout le monde ? Une mention prend sa place et indique que vous l'avez supprimé.",
        ["chat.delete_message_confirm"] = "Supprimer",
        ["chat.deleted_by_author"] = "Ce message a été supprimé par son auteur.",
        // added after update 2.2.3 (echo)
        ["chat.preview_echo"] = "A partagé un salon Echo",
        ["chat.echo_card_label"] = "Salon Echo",
        ["chat.echo_card_host"] = "Hôte : {0}",
        ["chat.echo_card_members"] = "{0} spectateurs",
        ["chat.echo_card_idle"] = "Rien en cours pour l'instant",
        ["chat.echo_card_view"] = "Rejoindre ce salon",
        ["chat.echo_card_loading"] = "Chargement du salon...",
        ["chat.echo_card_unavailable"] = "Ce salon est terminé",
        ["chat.party_card_title"] = "Groupe de {0}",
        ["chat.party_card_members"] = "{0} sur {1} ensemble",
        ["chat.party_card_join"] = "Touchez pour rejoindre le groupe",
        ["chat.party_card_over"] = "Ce groupe est terminé",
        ["chat.party_card_loading"] = "Chargement du groupe...",
        // chat images and the messenger invite (added after update 2.4.0)
        ["chat.attach_selfie"] = "Envoyer un selfie",
        ["chat.image_send_title"] = "Envoyer ce selfie ?",
        ["chat.image_moderation_note"] = "Vos messages sont chiffrés de bout en bout, mais pas les images. Nous vérifions chaque image avant l'envoi. La personne à qui vous l'envoyez peut la signaler.",
        ["chat.image_expiry_label"] = "Disparaît après",
        ["chat.image_expiry_hours"] = "{0} h",
        ["chat.image_expiry_days"] = "{0} j",
        ["chat.image_expiry_supporter"] = "Au-delà de trois jours, c'est un avantage de soutien.",
        ["chat.image_send"] = "Envoyer",
        ["chat.image_cancel"] = "Annuler",
        ["chat.image_loading"] = "Chargement...",
        ["chat.image_gone"] = "Cette image n'existe plus",
        ["chat.image_view"] = "Voir en grand",
        ["chat.image_delete"] = "Supprimer cette image",
        ["chat.image_report"] = "Signaler cette image",
        ["chat.image_report_title"] = "Signaler cette image",
        ["chat.image_report_hint"] = "Dites-nous ce qui ne va pas. Un modérateur verra l'image et votre motif.",
        ["chat.image_report_send"] = "Envoyer le signalement",
        ["chat.image_err_rejected"] = "Cette image ne peut pas être envoyée.",
        ["chat.image_err_full"] = "Votre espace d'images est plein. Les plus anciennes le libèrent en expirant.",
        ["chat.image_err_large"] = "Cette image est trop lourde.",
        ["chat.image_err_generic"] = "Ça n'a pas marché. Réessayez dans un instant.",
        ["chat.msgr_request_sent"] = "Demande Messenger envoyée",
        ["chat.image_storage"] = "Stockage : {0} / {1} Mo",
        ["chat.image_sending"] = "Envoi…",
        ["chat.image_expired"] = "Image expirée",
        ["chat.image_expires"] = "{0} j restants",
        ["chat.image_viewer"] = "Image",
        ["chat.preview_image"] = "A envoyé une photo",
        ["chat.attach_photos"] = "Photos",
        ["chat.attach_file"] = "Depuis un fichier",
    };
}
