namespace AetherLove.Services.Localization;

internal static class HubErrorsFr
{
    public static readonly System.Collections.Generic.Dictionary<string, string> Strings = new()
    {
        ["huberror.generic"] = "Une erreur serveur inattendue s'est produite.",
        ["huberror.generic_detail"] = "Une erreur s'est produite : {0}",
        ["huberror.invalid_request"] = "Le serveur a rejeté la requête. Si cela se reproduit, mettez à jour le plugin.",
        ["huberror.unauthenticated"] = "Votre session n'est plus valide. Veuillez vous reconnecter.",
        ["huberror.banned"] = "Ce profil AetherLove est banni.",
        ["huberror.account_banned"] = "Votre compte a été banni.",
        ["huberror.server_closed"] = "Le serveur est fermé pour le moment. {0}",
        ["huberror.rate_limited"] = "Vous faites cela trop souvent. Veuillez réessayer dans un instant.",
        ["huberror.profile_not_found"] = "Profil introuvable.",
        ["huberror.profile_not_visible"] = "Ce profil n'est pas disponible.",
        ["huberror.deck_expired"] = "Ce profil n'est plus dans votre deck. Actualisez votre deck et réessayez.",
        ["huberror.no_active_match"] = "Vous n'êtes plus en match avec ce joueur.",
        ["huberror.peer_keys_missing"] = "Cet utilisateur n'a pas encore configuré le chiffrement E2E et ne peut pas discuter, réessayez plus tard.",
        ["huberror.key_bundle_exists"] = "Les clés de chiffrement sont déjà configurées pour ce compte.",
        ["huberror.message_too_large"] = "Ce message est trop long pour être envoyé.",
        ["huberror.bio_too_long"] = "Votre bio dépasse la limite de {0} caractères.",
        ["huberror.lalafell_erp"] = "Le roleplay adulte n'est pas disponible pour les personnages Lalafell.",
        ["huberror.lalafell_nsfw"] = "Les fonctionnalités NSFW ne sont pas disponibles pour les personnages Lalafell.",
        ["huberror.lalafell_nsfw_photo"] = "Les photos NSFW ne sont pas disponibles pour les personnages Lalafell.",
        ["huberror.nsfw_disable_blocked"] = "Retirez vos photos NSFW et désactivez le roleplay 18+ avant de désactiver le NSFW.",
        ["huberror.img_too_large"] = "L'image est trop volumineuse ({0} Mo). Le maximum est de {1} Mo.",
        ["huberror.img_dimensions_too_large"] = "L'image est trop grande ({0}×{1}). Le côté le plus long ne peut dépasser {2}px.",
        ["huberror.img_crop_too_small"] = "La zone de recadrage est trop petite (min {0}px par côté).",
        ["huberror.img_decode_failed"] = "Impossible de lire l'image. Formats pris en charge : PNG, JPEG, WebP, GIF.",
        ["huberror.img_payload_invalid"] = "La photo n'a pas pu être envoyée. Veuillez resélectionner l'image.",
        ["huberror.report_self"] = "Vous ne pouvez pas vous signaler vous-même.",
        ["huberror.report_reason_required"] = "Veuillez décrire le problème.",
        ["huberror.report_reason_too_long"] = "Cette description est trop longue (max {0} caractères).",
        ["huberror.report_target_gone"] = "Ce profil n'existe plus.",
        ["huberror.report_duplicate"] = "Vous avez déjà signalé cet utilisateur récemment. Notre équipe examine le cas.",
        ["huberror.feedback_required"] = "Veuillez saisir un message avant d'envoyer.",
        // added after update (1.3.1)
        ["huberror.reswipe_nothing_to_undo"] = "Il n'y a rien à annuler.",
        ["huberror.reswipe_already_matched"] = "Vous ne pouvez pas annuler sur un profil avec lequel vous avez déjà un match.",
        ["huberror.reswipe_quota_exhausted"] = "Vous avez déjà utilisé votre annulation pour aujourd'hui.",
        ["huberror.superlike_quota_exhausted"] = "Vous n'avez plus de superlikes pour aujourd'hui.",

        // added after update 1.4.3
        ["huberror.character_limit_reached"] = "Vous pouvez avoir au maximum {0} personnages RP.",
        ["huberror.character_name_invalid"] = "Les noms de personnage doivent comporter entre 3 et 50 caractères.",
        ["huberror.character_not_found"] = "Ce personnage n'existe plus. Rechargez et réessayez.",

        // added after update 1.5.0
        ["huberror.patreon_disabled"] = "La liaison Patreon est actuellement indisponible.",
        ["huberror.patreon_already_linked"] = "Un compte Patreon est déjà lié à votre profil.",
        ["huberror.patreon_not_linked"] = "Aucun compte Patreon n'est lié à votre profil.",
        ["huberror.patreon_account_taken"] = "Ce compte Patreon est déjà lié à un autre compte AetherLove.",
        ["huberror.patreon_link_failed"] = "Nous n'avons pas pu finaliser la liaison Patreon. Veuillez réessayer.",
        ["huberror.places_disabled"] = "Les Lieux sont actuellement indisponibles.",
        ["huberror.venue_not_found"] = "Cet établissement n'existe plus.",
        ["huberror.venue_limit_reached"] = "Vous avez atteint la limite de {0} établissements.",
        ["huberror.venue_name_invalid"] = "Le nom de l'établissement doit comporter de 3 à 60 caractères.",
        ["huberror.venue_description_too_long"] = "La description dépasse la limite de {0} caractères.",
        ["huberror.venue_times_invalid"] = "L'un des horaires d'ouverture n'est pas valide.",
        ["huberror.venue_times_too_many"] = "Un établissement peut avoir au maximum {0} horaires d'ouverture.",
        ["huberror.venue_review_own"] = "Vous ne pouvez pas laisser d'avis sur votre propre établissement.",
        ["huberror.venue_review_too_long"] = "Votre avis dépasse la limite de {0} caractères.",
        ["huberror.venue_review_rating_invalid"] = "Choisissez une note de 1 à 5 étoiles.",
        ["huberror.venue_rsvp_invalid"] = "Cette ouverture n'accepte plus de participations.",

        // Multi-profile (added after update 1.5.1)
        ["huberror.profile_locked"] = "Ce profil occupe un emplacement supporter et est actuellement verrouillé.",
        ["huberror.profile_limit_reached"] = "Vous avez atteint votre limite de profils.",

        // Messenger (added after update 1.5.1)
        ["huberror.messenger_disabled"] = "Le messenger est actuellement indisponible.",
        ["huberror.msgr_code_not_found"] = "Aucun utilisateur trouvé avec ce code.",
        ["huberror.msgr_self"] = "C'est votre propre code.",
        ["huberror.msgr_already_contact"] = "Vous êtes déjà contacts.",
        ["huberror.msgr_request_pending"] = "Votre demande est toujours en attente.",
        ["huberror.msgr_contact_limit"] = "Vous avez atteint votre limite de {0} contacts.",
        ["huberror.msgr_pending_limit"] = "Vous avez trop de demandes en attente (max. {0}).",
        ["huberror.msgr_not_contact"] = "Vous n'êtes pas contacts.",
        ["huberror.msgr_group_limit"] = "Vous pouvez posséder au plus {0} groupes.",
        ["huberror.msgr_group_full"] = "Les groupes peuvent avoir au plus {0} membres.",
        ["huberror.msgr_not_owner"] = "Seul le propriétaire du groupe peut faire cela.",
        ["huberror.msgr_not_member"] = "Vous n'êtes pas membre de ce groupe.",
        ["huberror.msgr_group_name_invalid"] = "Ce nom de groupe ne peut pas être utilisé.",
        ["huberror.msgr_adds_disabled"] = "Cet utilisateur n'accepte pas les demandes de contact.",
        ["huberror.msgr_keys_missing"] = "Les clés de chiffrement sont obsolètes ; réessayez dans un instant.",
        ["huberror.msgr_image_rejected"] = "Cette image ne peut pas être envoyée. Choisis une autre image ou contacte le support si tu penses que c'est une erreur.",
        ["huberror.msgr_storage_full"] = "Ton espace de stockage d'images est plein. Supprime des images ou attends que les plus anciennes expirent, puis réessaie.",
        ["huberror.msgr_image_too_large"] = "Cette image est trop volumineuse.",
        ["huberror.msgr_image_invalid"] = "Cette image n'a pas pu être lue.",
        // levemetes (added after update 2.0.1)
        ["huberror.levemetes_disabled"] = "Levemetes est désactivé pour le moment.",
        ["huberror.leve_not_found"] = "Cette annonce n'existe plus.",
        ["huberror.leve_invalid"] = "L'annonce n'a pas pu être enregistrée. Vérifiez vos saisies.",
        ["huberror.leve_limit_reached"] = "Vous avez déjà {0} annonces. Supprimez-en une ou laissez-en expirer une.",
        ["huberror.leve_too_long"] = "Le texte est trop long (max. {0} caractères).",
        ["huberror.leve_image_rejected"] = "Cette image ne peut pas être envoyée. Choisissez-en une autre ou contactez le support si vous pensez qu'il s'agit d'une erreur.",
        ["huberror.leve_review_own"] = "Vous ne pouvez pas évaluer votre propre annonce.",
        ["huberror.leve_review_too_long"] = "Votre avis est trop long (max. {0} caractères).",
        ["huberror.leve_review_rating_invalid"] = "Choisissez une note entre 1 et 5 étoiles.",
        ["huberror.leve_reviews_disabled"] = "L'auteur a désactivé les avis sur cette annonce.",
        ["huberror.leve_renew_too_soon"] = "Cette annonce a été renouvelée récemment. Réessayez plus tard.",
        // holiday mode (added after update 2.0.1)
        // wayfinder (added after update 2.1.3)
        ["huberror.wayfinder_disabled"] = "Wayfinder est désactivé pour le moment.",
        ["huberror.wayfinder_no_challenges"] = "Aucun défi disponible pour le moment. Revenez bientôt !",
        ["huberror.wayfinder_no_reachable"] = "Tous les défis restants se trouvent dans des zones que vous n'avez pas encore débloquées. Syntonisez d'autres éthérytes et revenez !",
        ["huberror.wayfinder_daily_limit"] = "Vous avez utilisé vos {0} départs du jour.",
        ["huberror.wayfinder_active_exists"] = "Vous avez déjà un défi en cours.",
        ["huberror.wayfinder_no_active"] = "Ce défi n'est plus actif.",
        ["huberror.wayfinder_expired"] = "Temps écoulé ! Ce défi a expiré.",
        ["huberror.wayfinder_not_scout"] = "Vous n'avez pas la permission d'ajouter des points de repère.",
        ["huberror.wayfinder_invalid"] = "Le point de repère n'a pas pu être enregistré. Vérifiez vos saisies.",
        ["huberror.wayfinder_image_rejected"] = "Cette photo ne peut pas être envoyée. Prenez-en une autre, ou contactez le support si vous pensez qu'il s'agit d'une erreur.",
        ["huberror.holiday_message_too_long"] = "Votre message de vacances est trop long (max. {0} caractères).",
        ["huberror.holiday_message_invalid"] = "Ce message de vacances ne peut pas être utilisé. Merci de le reformuler.",
        // yapper (added after update 2.1.3)
        ["huberror.yapper_disabled"] = "Yapper est désactivé pour le moment.",
        ["huberror.yapper_no_profile"] = "Configurez d'abord votre profil Yapper.",
        ["huberror.yapper_banned"] = "Vous ne pouvez pas publier pour le moment. Contactez le support si vous pensez qu'il s'agit d'une erreur.",
        ["huberror.yapper_handle_taken"] = "Ce pseudo est déjà pris.",
        ["huberror.yapper_handle_invalid"] = "Les pseudos font 3 à 20 caractères : lettres, chiffres et tirets bas.",
        ["huberror.yapper_handle_rejected"] = "Ce pseudo ne peut pas être utilisé. Choisissez-en un autre.",
        ["huberror.yapper_profile_rejected"] = "Ce texte ne peut pas être utilisé sur votre profil. Merci de le reformuler.",
        ["huberror.yapper_rename_too_soon"] = "Vous avez changé de pseudo récemment. Réessayez dans {0} jours.",
        ["huberror.yapper_blocked"] = "Vous ne pouvez pas interagir avec cet utilisateur.",
        ["huberror.yap_not_found"] = "Ce yap n'existe plus.",
        ["huberror.yap_too_long"] = "Ce yap est trop long (max. {0} caractères).",
        ["huberror.yap_too_many_images"] = "Un yap peut contenir au plus {0} images.",
        ["huberror.yap_image_rejected"] = "Cette image ne peut pas être publiée. Choisissez-en une autre ou contactez le support si vous pensez qu'il s'agit d'une erreur.",
        ["huberror.yap_image_too_large"] = "Cette image est trop volumineuse.",
        ["huberror.yap_image_invalid"] = "Cette image n'a pas pu être lue.",
        ["huberror.yap_embed_invalid"] = "Le contenu partagé n'est plus disponible.",
        ["huberror.yap_edit_window_closed"] = "La fenêtre de modification de ce yap est fermée.",
        ["huberror.yap_nsfw_mismatch"] = "Votre classification de contenu ne le permet pas.",
        ["huberror.yap_invalid"] = "Le yap n'a pas pu être enregistré. Vérifiez vos saisies.",
        ["huberror.yap_dm_not_allowed"] = "Cet utilisateur ne peut pas recevoir vos messages.",
        ["huberror.yap_dm_keys_missing"] = "@{0} doit encore terminer sa configuration. Réessayez dans un moment.",

        // store (added after update 2.2.3)
        ["huberror.store_disabled"] = "La boutique est fermée pour maintenance.",
        ["huberror.store_product_not_found"] = "Cet article n'existe plus.",
        ["huberror.store_product_unavailable"] = "Cet article n'est pas en vente pour le moment.",
        ["huberror.store_insufficient_sparks"] = "Pas assez de sparks : cela coûte {0} et tu en as {1}.",
        ["huberror.store_limit_reached"] = "Tu possèdes déjà le maximum ({0}) de cet article.",
        ["huberror.store_quantity_invalid"] = "Cette quantité n'est pas autorisée.",
        ["huberror.store_conflict"] = "La boutique a eu un raté. Rien n'a été débité deux fois ; réessaie simplement.",
        ["huberror.aetherling_disabled"] = "Ça n'écoute pas pour le moment.",
        ["huberror.aetherling_exists"] = "Il y en a déjà un.",
        ["huberror.aetherling_none"] = "Il n'y a rien ici à qui le donner.",
        ["huberror.aetherling_insufficient"] = "Pas assez de sparks : il en veut {0} et tu en as {1}.",
        ["huberror.aetherling_gated"] = "Pas encore. Il faut que quelque chose arrive d'abord. Réessaie dans {0} minutes.",
        ["huberror.aetherling_complete"] = "Il n'en prendra pas davantage.",
        ["huberror.aetherling_unready"] = "Pas encore. Il n'est pas prêt pour ça.",
        ["huberror.aetherling_named"] = "Il a déjà son nom.",
        ["huberror.aetherling_name_invalid"] = "Ce nom ne passe pas. Essaie autre chose.",

        // echo (added after update 2.2.3)
        ["huberror.echo_disabled"] = "Le visionnage à plusieurs est désactivé pour le moment.",
        ["huberror.echo_room_not_found"] = "Cette séance est déjà terminée.",
        ["huberror.echo_room_full"] = "Ce salon est plein ({0} personnes).",
        ["huberror.echo_not_member"] = "Tu n'es pas dans ce salon.",
        ["huberror.echo_not_owner"] = "Seule la personne qui a lancé le salon peut faire ça.",
        ["huberror.echo_host_only"] = "L'hôte pilote la lecture en ce moment.",
        ["huberror.echo_kicked"] = "Tu as été retiré de ce salon.",
        ["huberror.echo_playlist_full"] = "La file d'attente est pleine ({0} vidéos).",
        ["huberror.echo_live_room_exists"] = "Tu as déjà un salon en cours. Ferme-le pour en ouvrir un autre.",
        ["huberror.echo_invalid_video"] = "Ça ne ressemble pas à un lien YouTube.",
        ["huberror.echo_name_invalid"] = "Ce nom de salon ne passe pas.",
        ["huberror.hangout_watch_room_invalid"] = "Cette séance n'est plus disponible.",

        // aetherling growth (added after update 2.3.4)
        ["huberror.aetherling_no_crystal"] = "Il n'y a plus de cristal de ce genre à lui donner.",
        ["huberror.aetherling_full"] = "Il est bien rassasié. Il aura de nouveau faim demain.",
        ["huberror.aetherling_not_owned"] = "Il n'a pas ça à porter.",
    };
}
