namespace AetherLove.Services.Localization;

internal static class ProfileDe
{
    public static readonly System.Collections.Generic.Dictionary<string, string> Strings = new()
    {
        // Profile
        // ProfileScreen - load / empty states
        ["profile.load_failed"] = "Profil konnte nicht geladen werden: {0}",
        ["profile.none_loaded"] = "Kein Profil geladen.",

        // ProfileScreen - sections
        ["profile.about"] = "Über",
        ["profile.flairs"] = "Abzeichen",
        ["profile.looking_for"] = "Sucht nach",
        ["profile.content_interests"] = "Bevorzugte Inhalte",
        ["profile.info"] = "Info",
        ["profile.gender"] = "Geschlecht",
        ["profile.languages"] = "Sprachen",
        ["profile.timezone"] = "Zeitzone",
        ["profile.favourite_job"] = "Lieblingsjob",
        ["profile.favourite_location"] = "Lieblingsort",
        ["profile.favourite_expansion"] = "Lieblingserweiterung",
        ["profile.favourite_song"] = "Lieblingslied",
        ["music.fetching"] = "Songname wird abgerufen…",
        ["music.saved"] = "Link gespeichert (Name ausstehend)",
        ["music.invalid"] = "Dieser Link konnte nicht gelesen werden. Füge einen Songlink von Spotify, SoundCloud, Apple Music oder YouTube Music ein.",
        ["music.open_tooltip"] = "Zum Öffnen klicken",
        ["profile.favourite_movie"] = "Lieblingsfilm",
        ["profile.favourite_anime"] = "Lieblings-Anime",
        ["profile.favourite_ff_character"] = "Lieblings-FF-Charakter",
        ["profile.sync_tool"] = "Sync-Tool",
        ["profile.weekday_playtimes"] = "Spielzeiten unter der Woche  (Mo–Fr)",
        ["profile.weekend_playtimes"] = "Spielzeiten am Wochenende  (Sa–So)",
        ["profile.timezone_value"] = "{0} (aktuelle Zeit: {1})",

        // ProfileScreen - Spotify / NSFW pill
        ["profile.nsfw_reveal"] = "Klicken, um NSFW-Bild anzuzeigen",

        // ProfileScreen - back pill
        ["profile.back_to_chat"] = "Zurück zum Chat",
        ["profile.back_to_swiping"] = "Zurück zum Wischen",

        // ProfileScreen - report flow
        ["profile.report_profile"] = "Profil melden",
        ["profile.report_warning"] = "Falsche oder böswillige Meldungen führen zu Verwarnungen für dein eigenes Konto, und wiederholter Missbrauch kann zu einer Sperrung führen. Melde nur Profile, die tatsächlich gegen die Regeln verstoßen.",
        ["profile.report_prompt"] = "Sag unseren Moderatoren, was mit {0} nicht stimmt:",
        ["profile.this_profile"] = "diesem Profil",
        ["profile.report_agree"] = "Mir ist bewusst, dass falsche Meldungen zu Verwarnungen gegen mein Konto führen können.",
        ["profile.submitting"] = "Wird eingereicht…",
        ["profile.cancel"] = "Abbrechen",
        ["profile.submit_report"] = "Meldung einreichen",
        ["profile.report_submitted"] = "Meldung eingereicht",
        ["profile.report_thanks"] = "Danke, unsere Moderatoren sehen sich das an. Dieses Profil erscheint nicht mehr in deinem Deck.",
        ["profile.closing"] = "Wird geschlossen…",
        ["profile.closing_in"] = "Schließt in {0} Sekunden",
        ["profile.close"] = "Schließen",

        // ProfileScreen - copy profile text (viewing others only)
        ["profile.copy_text"] = "Profiltext kopieren",
        ["profile.copy_warning_title"] = "Warnung",
        ["profile.copy_warning_body"] = "Du hast den Text einer anderen Person kopiert. Sei vorsichtig, wenn du darin enthaltene Links anklickst oder ihnen folgst. Das geschieht auf eigene Gefahr.",
        ["profile.copy_warning_agree"] = "Ich habe verstanden und stimme zu",

        // MyProfileScreen hub: stats + menu
        ["profile.section_myprofile"] = "Mein Profil",
        ["profile.section_service"] = "Service",
        ["profile.menu_view"] = "Mein Profil ansehen",
        ["profile.menu_edit"] = "Profil ändern",
        ["profile.menu_images"] = "Profilbilder",
        ["profile.stat_loves_you"] = "lieben dich",
        ["profile.stat_matches"] = "Matches",
        ["profile.stat_match_rate"] = "Match-Rate",
        ["profile.back_to_my"] = "← Zurück",

        // MyProfileScreen - edit tab load / save
        ["profile.load_profile_failed"] = "Dein Profil konnte nicht geladen werden: {0}",
        ["profile.retry"] = "Erneut versuchen",
        ["profile.saving"] = "Wird gespeichert…",
        ["profile.saved"] = "Gespeichert  ✓",
        ["profile.save_changes"] = "Änderungen speichern",

        // MyProfileScreen - edit form section headings
        ["profile.heading_character"] = "Charakter",
        ["profile.heading_location"] = "Standort",
        ["profile.heading_languages"] = "Sprachen, die ich spreche",
        ["profile.heading_content"] = "Folgende Inhalte machen mir Spaß",
        ["profile.heading_looking_for"] = "Ich suche nach",
        ["profile.heading_nsfw"] = "NSFW",
        ["profile.heading_optional"] = "Optional",
        ["profile.heading_playtime"] = "Spielzeit",
        ["profile.heading_timezone"] = "Zeitzone",
        ["profile.heading_sync_tool"] = "Sync-Tool",
        ["profile.heading_match_prefs"] = "Match-Einstellungen",

        // MyProfileScreen - edit form labels / hints
        ["profile.display_name"] = "Anzeigename",
        ["profile.about_me"] = "Über mich",
        ["profile.char_count"] = "{0} / 500 Zeichen",
        ["profile.preview"] = "Vorschau",
        ["profile.bio_placeholder"] = "Deine Biografie erscheint hier…",
        ["profile.race"] = "Rasse",
        ["profile.region"] = "Region",
        ["profile.languages_hint"] = "Wähle jede Sprache, in der du dich beim Chatten wohlfühlst.",
        ["profile.content_hint"] = "Wähle alles aus, was zutrifft.",
        ["profile.looking_for_hint"] = "Ehrlichkeit hilft, bessere Matches zu finden.",
        ["profile.nsfw_lalafell"] = "Erwachsenen- und NSFW-Funktionen stehen nicht zur Verfügung, solange deine Rasse auf Lalafell eingestellt ist. Details findest du in den Nutzungsbedingungen.",
        ["profile.nsfw_explainer"] = "NSFW steht für \"Not Safe For Work\": Inhalte mit Nacktheit oder sexuellen Themen. Aktiviere dies, um NSFW-Profile zu sehen und mit ihnen gematcht zu werden.",
        ["profile.nsfw_optin"] = "NSFW-Profile: JA",
        ["profile.favourite_job_tooltip"] = "Der Job oder die Rolle, die dir am meisten Spaß macht. Tippe zum Filtern.",
        ["profile.favourite_ff_character_full"] = "Lieblings-Final-Fantasy-Charakter",
        ["profile.weekday_playtimes_edit"] = "Spielzeiten unter der Woche (Mo–Fr)",
        ["profile.weekend_playtimes_edit"] = "Spielzeiten am Wochenende (Sa–So)",
        ["profile.sync_tool_hint"] = "Mit Sync-Tools können gematchte Nutzer Mod-Erscheinungsbilder teilen.",
        ["profile.match_prefs_body"] = "Sag uns, mit wem du dich matchen möchtest. Diese Einstellungen helfen, die richtigen Leute für dich anzuzeigen.",
        ["profile.all"] = "Alle",
        ["profile.none"] = "Keine",
        ["profile.clear"] = "Zurücksetzen",
        ["profile.filter_any_race"] = "  Keine Auswahl: beliebige Rasse",
        ["profile.filter_any_gender"] = "  Keine Auswahl: beliebiges Geschlecht",
        ["profile.filter_any_region"] = "  Keine Auswahl: beliebige Region",
        ["profile.filter_any_language"] = "  Keine Auswahl: keine Sprachpräferenz",
        ["profile.spoken_language"] = "Gesprochene Sprache",
        ["profile.spoken_language_tooltip"] = "Lass alles deaktiviert, um unabhängig von der Sprache zu matchen.",

        // MyProfileScreen.Images - tab text
        ["profile.load_photos_failed"] = "Deine Fotos konnten nicht geladen werden: {0}",
        ["profile.profile_picture"] = "Profilbild",
        ["profile.profile_picture_desc"] = "Dein Profilbild wird in der Chatliste und auf Match-Karten angezeigt. Verwende ein quadratisches Nahaufnahme-Porträt deines FFXIV-Charakters.",
        ["profile.profile_photos"] = "Profilfotos",
        ["profile.profile_photos_desc"] = "Füge deinem Profil Porträtfotos hinzu (Verhältnis 10:16). Der erste Platz ist erforderlich; die Plätze 2–4 sind optional.",
        ["profile.declare_before_save"] = "Kennzeichne jedes Zusatzfoto vor dem Speichern als SFW oder NSFW.",

        // MyProfileScreen.Images - avatar section
        ["profile.new_photo_ready"] = "Neues Foto bereit, noch nicht gespeichert.",
        ["profile.change_photo"] = "Foto ändern",
        ["profile.profile_picture_set"] = "Profilbild: Festgelegt  ✓",
        ["profile.no_profile_picture"] = "Kein Profilbild festgelegt.",
        ["profile.upload_avatar"] = "Avatar hochladen…",

        // MyProfileScreen.Images - slot grid + active slot controls
        ["profile.slot_main"] = "Haupt",
        ["profile.tap_slot"] = "Tippe oben auf einen Platz, um ein Foto hinzuzufügen oder zu ändern.",
        ["profile.main_photo"] = "Hauptfoto",
        ["profile.extra_photo"] = "Zusatzfoto {0}",
        ["profile.photo_will_be_removed"] = "Foto wird entfernt.",
        ["profile.undo"] = "Rückgängig",
        ["profile.main_must_be_sfw"] = "Dein Hauptprofilbild MUSS SFW sein. Das Hochladen eines NSFW-Bildes ist ein Grund für die Sperrung oder Löschung des Kontos.",
        ["profile.sfw_or_nsfw"] = "Ist dieses Bild SFW oder NSFW?",
        ["profile.sfw_mismatch_warning"] = "Wenn unser System feststellt, dass du NSFW hochgeladen hast, während SFW ausgewählt ist, wird dein Foto zur Moderation zurückgehalten und du riskierst eine Kontosperrung.",
        ["profile.photo_ready"] = "Foto bereit, noch nicht gespeichert.",
        ["profile.replace"] = "Ersetzen",
        ["profile.photo_set"] = "Foto festgelegt  ✓",
        ["profile.currently_nsfw"] = "Aktuell: NSFW",
        ["profile.currently_sfw"] = "Aktuell: SFW",
        ["profile.remove"] = "Entfernen",
        ["profile.photo_required"] = "Dieses Foto ist erforderlich.",
        ["profile.photo_optional"] = "Dieses Foto ist optional.",
        ["profile.upload_photo"] = "Foto hochladen…",

        // MyProfileScreen.Images - file picker / crop popup
        ["profile.select_image"] = "Bild auswählen",
        ["profile.image_files_filter"] = "Bilddateien",
        ["profile.crop_avatar"] = "Avatar zuschneiden",
        ["profile.crop_main_photo"] = "Hauptfoto zuschneiden",
        ["profile.crop_extra_photo"] = "Zusatzfoto {0} zuschneiden",

        // added after update 1.4.3
        ["profile.menu_rp"] = "Meine RP-Profile",
        ["profile.rp_intro_title"] = "Meine RP-Profile",
        ["profile.rp_intro"] = "Füge deine FFXIV-OCs (eigene Charaktere) zu deinem Profil hinzu. Jeder Charakter bekommt einen Namen, eine kurze Geschichte und optional ein Bild, und sie erscheinen auf deinem Profil, damit andere sie entdecken können.",
        ["profile.characters"] = "Charaktere",
        ["profile.rp_add"] = "Charakter hinzufügen",
        ["profile.rp_empty"] = "Noch keine Charaktere. Füge unten deinen ersten OC hinzu!",
        ["profile.rp_limit_reached"] = "Du kannst bis zu {0} Charaktere hinzufügen.",
        ["profile.rp_name"] = "Name / Titel",
        ["profile.rp_bio"] = "Über diesen Charakter",
        ["profile.rp_delete"] = "Löschen",
        ["profile.rp_delete_confirm"] = "Wirklich löschen?",
        ["profile.rp_move_up"] = "Nach oben",
        ["profile.rp_move_down"] = "Nach unten",
        ["profile.rp_image"] = "Bild",
        ["profile.rp_upload_image"] = "Bild hochladen",
        ["profile.rp_replace_image"] = "Bild ersetzen",
        ["profile.rp_remove_image"] = "Bild entfernen",
        ["profile.rp_image_ready"] = "Bild bereit zum Speichern",
        ["profile.rp_image_nsfw"] = "Dieses Bild ist NSFW",
        ["profile.rp_image_expand"] = "In voller Größe ansehen",
        ["profile.rp_image_back"] = "Zurück zum Profil",
        ["profile.rp_crop_image"] = "Charakterbild zuschneiden",
        ["profile.rp_back"] = "Zurück",
        ["profile.rp_details"] = "Charakterdetails:",

        // added after update 1.5.1
        ["profile.slot_locked"] = "Dieser Foto-Slot erfordert ein aktives Supporter-Abo. Du kannst das Foto entfernen oder erneut abonnieren, um den Slot wieder zu nutzen.",
        ["profile.rp_extra_image"] = "Zusatzbild {0} (Supporter)",
        ["profile.section_supporter"] = "Supporter",
        ["profile.menu_sup_vanity"] = "Vanity-Designs",
        ["profile.menu_sup_stats"] = "Extra-Statistiken",
        ["profile.sup_intro"] = "Danke, dass du AetherLove unterstützt! Wähle einen Stil für deinen Namen und ob du das Supporter-Abzeichen zeigen willst. Beides ist für alle sichtbar.",
        ["profile.sup_name_style"] = "Namensstil",
        ["profile.sup_show_badge"] = "Meinen Supporter-Status anzeigen",
        ["profile.sup_badge_hint"] = "Wenn aus, sieht niemand deinen Supporter-Stern oder dein Abzeichen: weder auf deinen Profilen noch in Chats oder Hangouts, und auch deine eigene Profilvorschau blendet sie aus. Deine Supporter-Vorteile funktionieren weiter. Gilt für dein ganzes Konto.",
        ["profile.sup_stats_intro"] = "Exklusive Supporter-Einblicke, wie dein Profil im ganzen Reich ankommt.",
        ["profile.sup_stat_likes_received"] = "Erhaltene Likes",
        ["profile.sup_stat_superlikes"] = "Erhaltene Superlikes",
        ["profile.sup_stat_views"] = "Profilaufrufe",
        ["profile.sup_stat_impressions"] = "Deck-Einblendungen",
        ["profile.sup_stat_likes_given"] = "Vergebene Likes",
        ["profile.sup_stat_passes_given"] = "Vergebene Passes",
        ["profile.sup_stat_matches"] = "Matches",
        ["profile.sup_stat_like_rate"] = "Deine Like-Quote",
        ["profile.sup_stat_match_rate"] = "Deine Match-Quote",
        ["profile.style_none"] = "Standard",
        ["profile.style_crimson"] = "Karmesinrot",
        ["profile.style_gold"] = "Gold",
        ["profile.style_emerald"] = "Smaragd",
        ["profile.style_sapphire"] = "Saphir",
        ["profile.style_violet"] = "Violett",
        ["profile.style_rose"] = "Rosé",
        ["profile.style_rainbow"] = "Regenbogen (animiert)",
        ["profile.style_shimmer"] = "Goldschimmer (animiert)",
        ["profile.style_pulse"] = "Rosé-Puls (animiert)",

        // added after update 2.0.1
        ["profile.more_options"] = "Weitere Optionen",
        ["profile.menu_hide"] = "Dieses Profil ausblenden",
        ["profile.menu_report"] = "Dieses Profil melden",
        ["profile.hide_title"] = "Profil ausblenden?",
        ["profile.hide_body"] = "Du siehst dieses Profil nie wieder in deinem Deck. Das lässt sich nicht rückgängig machen.",
        ["profile.hide_confirm"] = "Dauerhaft ausblenden",
        // holiday mode (added after update 2.0.1)
        ["profile.menu_holiday"] = "Urlaubsmodus",
        ["profile.holiday_toggle"] = "Urlaubsmodus aktiv",
        ["profile.holiday_msg_label"] = "Urlaubsnachricht",
        ["profile.holiday_msg_hint"] = "Solange der Urlaubsmodus aktiv ist, sehen alle Besucher deines Profils ein Abwesenheitsbanner mit deiner Nachricht, und deine Matches sehen eine Abwesenheitsmarkierung auf deinem Bild.",
        ["profile.holiday_save"] = "Speichern",
        ["profile.holiday_saved"] = "Gespeichert!",
        ["profile.holiday_active_banner"] = "URLAUBSMODUS AKTIV",
        ["profile.holiday_banner"] = "Diese Person hat den Urlaubsmodus aktiviert: {0}",
        ["profile.holiday_banner_short"] = "Diese Person hat den Urlaubsmodus aktiviert.",
    };
}
