namespace AetherLove.Services.Localization;

internal static class OsRu
{
    public static readonly System.Collections.Generic.Dictionary<string, string> Strings = new()
    {
        // added after update 1.5.1
        // App names
        ["os.app_clock"] = "Часы",
        ["os.app_snake"] = "Змейка",
        ["os.app_stacker"] = "Блоки",
        ["os.app_breaker"] = "Кирпичи",
        ["os.app_meteor"] = "Метеоры",
        ["os.app_invaders"] = "Захватчики",
        ["os.app_muncher"] = "Лабиринт",
        ["os.app_camera"] = "Камера",

        // Notification shade
        ["os.notifications"] = "Уведомления",
        ["os.notifications_empty"] = "Нет уведомлений",
        ["os.notifications_clear"] = "Очистить всё",
        ["os.notif_remove"] = "Убрать",
        ["os.time_now"] = "сейчас",
        ["os.qt_notifications"] = "Уведомления",
        ["os.qt_sounds"] = "Звуки уведомлений",
        ["os.qt_lock"] = "Закрепить положение телефона",
        ["os.qt_theme"] = "Следующая тема",
        ["os.qt_wallpaper"] = "Следующие обои",

        // Home screen
        ["os.edit_done"] = "Готово",
        ["os.greeting_morning"] = "Доброе утро",
        ["os.greeting_afternoon"] = "Добрый день",
        ["os.greeting_evening"] = "Добрый вечер",
        ["os.greeting_night"] = "Не спится?",
        ["os.widget_eorzea"] = "Эорзея",
        ["os.widget_status"] = "Подключение",
        ["os.widget_connected"] = "Подключено",
        ["os.widget_offline"] = "Не в сети",
        ["os.widget_unread"] = "Непрочитанные: {0}",

        // OS settings
        ["os.group_appearance"] = "Внешний вид",
        ["os.group_wallpaper"] = "Домашний экран и обои",
        ["os.group_home"] = "Главный экран",
        ["os.group_apps"] = "Настройки приложений",
        ["os.group_about"] = "О системе",
        ["os.wallpaper_gradient"] = "Тема",
        ["os.wallpaper_custom"] = "Свои",
        ["os.wallpaper_upload"] = "Загрузить изображение…",
        ["os.wallpaper_dim"] = "Затемнить обои",
        ["os.home_edit_hint"] = "Удерживайте значок на главном экране, чтобы переставить его. Перетаскивайте значки в док или между страницами.",
        ["os.home_reset"] = "Сбросить расположение",

        // Love settings hub after the appearance move
        ["settings.menu_language"] = "Язык и время",

        // Weatherman app
        ["os.app_weather"] = "Погода",

        // Messenger app
        ["os.app_messenger"] = "Messenger",

        // Photos app
        ["os.app_photos"] = "Фото",

        // Home screen app launcher
        ["os.add_apps"] = "Добавить приложения",
        ["os.add_apps_title"] = "Добавить приложения",
        ["os.add_apps_hint"] = "Закрепите другие установленные плагины Dalamud на главном экране.",
        ["os.add_apps_none"] = "Другие плагины не предоставляют главное окно.",
        ["os.add_apps_add"] = "Добавить",
        ["os.add_apps_added"] = "Добавлено",
        ["os.add_apps_search"] = "Поиск приложений...",
        ["os.remove_app_title"] = "Удалить приложение",
        ["os.remove_app_body"] = "Убрать {0} с главного экрана?",
        ["os.remove_app_confirm"] = "Убрать",
        // added after update 1.5.1
        ["os_onboarding.header_welcome"] = "Добро пожаловать",
        ["os_onboarding.header_design"] = "Настрой под себя",
        ["os_onboarding.header_name"] = "Твоё имя",
        ["os_onboarding.header_terms"] = "Условия использования",
        ["os_onboarding.welcome_title"] = "Добро пожаловать в AetherOS",
        ["os_onboarding.welcome_body"] = "Это твой телефон. Давай настроим его: выбери оформление, имя и прими основные правила. Это займёт всего минуту.",
        ["os_onboarding.design_title"] = "Выбери оформление",
        ["os_onboarding.name_title"] = "Как нам тебя называть?",
        ["os_onboarding.name_body"] = "Это имя используется во всём AetherOS. Для каждого приложения позже можно выбрать своё отображаемое имя.",
        ["os_onboarding.name_hint"] = "Имя",
        ["os_onboarding.terms_title"] = "Основные правила",
        ["os_onboarding.terms_agree"] = "Я принимаю условия использования",
        ["os_onboarding.finish"] = "Готово",
        ["os_onboarding.header_signin"] = "Вход",
        ["os_onboarding.header_passphrase"] = "Кодовая фраза",
        ["os_onboarding.tos_1"] = "Фанатский плагин AetherOS предоставляется «как есть», без каких-либо гарантий. Он может сломаться, потерять данные или перестать работать в любой момент, и вы используете его на свой страх и риск.",
        ["os_onboarding.tos_2"] = "AetherOS не связан со Square Enix и не одобрен и не спонсируется ею.",
        ["os_onboarding.tos_3"] = "FINAL FANTASY и FINAL FANTASY XIV являются зарегистрированными товарными знаками Square Enix Holdings Co., Ltd. Все прочие товарные знаки принадлежат их владельцам.",
        ["os_onboarding.tos_4"] = "Продолжая, вы принимаете эти условия.",
        // OS account avatar (added after update 1.5.1)
        ["os_onboarding.header_avatar"] = "Аватар",
        ["os_onboarding.avatar_title"] = "Добавьте фото",
        ["os_onboarding.avatar_body"] = "Выберите изображение для профиля AetherOS. Это необязательно, и его видите только вы; можно изменить в любой момент.",
        ["os_onboarding.avatar_choose"] = "Выбрать фото",
        ["os_onboarding.avatar_change"] = "Изменить фото",
        // two-onboarding split (added after update 1.5.1)
        ["os_onboarding.header_done"] = "Готово",
        ["os_onboarding.done_title"] = "Всё готово!",
        ["os_onboarding.done_body"] = "Ваш аккаунт AetherOS настроен. Пользуйтесь новым телефоном!",
        ["os_onboarding.done_start"] = "Начать пользоваться плагином",
        ["os_onboarding.design_language"] = "Язык",
        // combined OS profile step (added after update 1.5.1)
        ["os_onboarding.header_profile"] = "Ваш профиль",
        ["os_onboarding.profile_name_label"] = "Ваше имя",
        ["os_onboarding.profile_photo_label"] = "Ваше фото",
        // home button tooltip (added after update 1.5.1)
        ["os.home"] = "Домой",
        // settings-consolidation categories + reset-home confirm + profile edit (added after update 1.5.1)
        ["os.cat_general"] = "Общие",
        ["os.cat_appearance"] = "Оформление",
        ["os.cat_other"] = "Прочее",
        ["os.menu_general"] = "Общие",
        ["os.menu_appearance"] = "Оформление телефона",
        ["os.menu_reset_home"] = "Сбросить главный экран",
        ["os.reset_home_confirm_title"] = "Сбросить главный экран?",
        ["os.reset_home_confirm_body"] = "Это удалит вашу расстановку значков и панель и восстановит расположение по умолчанию. Ваши приложения и настройки не будут затронуты.",
        ["os.edit_profile"] = "Изменить",
        // Daily Eorzean news app (added after update 1.5.1)
        ["os.app_news"] = "Эорзейский вестник",
        ["os.news_notifications"] = "Уведомления новостей",
        ["os.news_tagline"] = "Осн. · Все новости королевства",
        ["os.news_latest"] = "Свежее",
        ["os.news_more"] = "Больше новостей",
        ["os.news_edition"] = "Выпуск · {0}",
        ["os.news_refresh"] = "Обновить",
        ["os.news_new"] = "Новое",
        // Feedback app (added after update 1.5.1)
        ["os.app_feedback"] = "Отзывы",
        ["os.feedback_app_label"] = "О каком приложении отзыв?",
        ["os.feedback_general"] = "Общее",
        ["os.feedback_send_another"] = "Отправить ещё отзыв",
        // generic share system (added after update 1.5.1)
        ["os.share_sheet_title"] = "Поделиться через",
        // home grid + folders
        ["os.settings_home_screen"] = "Домашний экран",
        ["os.settings_home_grid_caption"] = "Иконки перестраиваются автоматически под новую сетку.",
        ["os.new_folder"] = "Новая папка",
        ["os.folder_name_hint"] = "Название папки…",
        ["os.folder_default_name"] = "Папка",
        ["os.folder_arcade"] = "Аркады",
        ["os.folder_edit"] = "Изменить",
        ["os.folder_empty"] = "Пока пусто. Перетащите иконку на папку, чтобы добавить приложение.",
        // photo filters + screenshot import
        ["os.filter_original"] = "Оригинал",
        ["os.filter_mono"] = "Моно",
        ["os.filter_noir"] = "Нуар",
        ["os.filter_sepia"] = "Сепия",
        ["os.filter_retro"] = "Ретро",
        ["os.filter_cool"] = "Холодный",
        ["os.filter_vivid"] = "Яркий",
        ["os.filter_fade"] = "Выцветший",
        ["os.filter_applying"] = "Применяем…",
        ["os.screenshots_album"] = "Скриншоты",
        // calendar app
        ["os.app_calendar"] = "Календарь",
        ["os.edit_filters"] = "Фильтры",
        ["os.edit_adjust"] = "Коррекция",
        ["os.edit_brightness"] = "Яркость",
        ["os.edit_contrast"] = "Контраст",
        ["os.edit_hue"] = "Оттенок",
        ["os.edit_tint"] = "Заливка",
        // guided OS tour
        ["os.settings_tour"] = "Пройти экскурсию",
        ["os.tour_next"] = "Далее",
        ["os.tour_back"] = "Назад",
        ["os.tour_skip"] = "Пропустить",
        ["os.tour_finish"] = "Готово",
        ["os.tour_welcome_title"] = "Добро пожаловать в AetherOS",
        ["os.tour_welcome_body"] = "Это ваш телефон: домашний экран с приложениями, и AetherLove лишь одно из них. Давайте быстро осмотримся, это займёт всего минуту.",
        ["os.tour_homebtn_title"] = "Кнопка «Домой»",
        ["os.tour_homebtn_body"] = "Вернуться на домашний экран можно в любой момент с помощью кнопки «Домой», она сейчас подсвечена внизу телефона.",
        ["os.tour_pages_title"] = "Домашний экран",
        ["os.tour_pages_body"] = "Ваши приложения живут на домашнем экране. Листайте влево и вправо, чтобы переключаться между страницами; подсвеченные точки показывают, на какой странице вы находитесь.",
        ["os.tour_widgets_title"] = "Страница виджетов",
        ["os.tour_widgets_body"] = "Мы только что пролистнули на страницу виджетов за вас. Она находится слева от приложений и показывает часы со временем Эорзеи, статус подключения и последнее уведомление.",
        ["os.tour_statusbar_title"] = "Строка состояния",
        ["os.tour_statusbar_body"] = "Подсвеченная полоса в самом верху показывает время, подключение к серверам AetherLove, число ожидающих уведомлений и заряд батареи. Если связь пропадёт, там появится красный значок.",
        ["os.tour_shade_title"] = "Уведомления",
        ["os.tour_shade_body"] = "Нажмите на верх телефона (или потяните его вниз), чтобы увидеть уведомления, как мы сделали только что. Здесь же находятся быстрые переключатели и регулятор яркости. Нажмите на уведомление, чтобы открыть его, или смахните, чтобы убрать.",
        ["os.tour_fake_notif_title"] = "Привет!",
        ["os.tour_fake_notif_body"] = "Вот так выглядит уведомление.",
        ["os.tour_badges_title"] = "Бейджи",
        ["os.tour_badges_body"] = "На иконках приложений появляется небольшой счётчик, когда вас что-то ждёт, например непрочитанные сообщения или новые пары. Он исчезает после открытия приложения. (Не волнуйтесь, на самом деле их у вас не 67.)",
        ["os.tour_edit_title"] = "Настройте под себя",
        ["os.tour_edit_body"] = "Нажмите на иконку и удерживайте, и всё начнёт покачиваться, как сейчас. Перетаскивайте иконки куда угодно: на другое место, другую страницу или в нижний ряд. Когда всё устроит, нажмите подсвеченную кнопку «Готово».",
        ["os.tour_dock_title"] = "Док-панель",
        ["os.tour_dock_body"] = "Нижний ряд виден на каждой странице. В него помещается до четырёх любимых приложений; перетаскивайте иконки туда и обратно при перестановке.",
        ["os.tour_folders_title"] = "Папки",
        ["os.tour_folders_body"] = "Иконки можно собирать в папки, как в примере, который только что появился. Создавайте свои через плитку «+», а затем перетаскивайте на них иконки, чтобы навести порядок. Нажмите на папку, чтобы открыть её, переименовать или вытащить приложения обратно.",
        ["os.tour_addapps_title"] = "Больше приложений",
        ["os.tour_addapps_body"] = "Плитка «+» в конце списка приложений открывает этот список. Здесь можно создавать папки и даже добавлять другие плагины Dalamud на домашний экран. Убрать их можно крестиком при перестановке.",
        ["os.tour_share_title"] = "Делитесь",
        ["os.tour_share_body"] = "Вы можете делиться заведениями, встречами и многим другим с парами и друзьями. Делиться можно между разными приложениями: выберите, чем и куда поделиться, и контент придёт интерактивной карточкой.",
        ["os.tour_look_title"] = "Внешний вид",
        ["os.tour_look_body"] = "В подсвеченном приложении «Настройки» можно выбрать тему телефона, сменить обои (или загрузить свои), изменить размер сетки и даже самого телефона.",
        ["os.tour_offline_title"] = "Оффлайн",
        ["os.tour_offline_body"] = "Телефоном можно пользоваться, даже если AetherLove или другие встроенные приложения недоступны. Приложения, которым нужны серверы, слегка затемняются и получают пометку, а всё остальное продолжает работать как обычно.",
        ["os.tour_done_title"] = "Вот и вся экскурсия!",
        ["os.tour_done_body"] = "Повторить её можно в любой момент из настроек. А теперь исследуйте приложения и приятного общения!",
        ["os.tour_demo_folder"] = "Пример",
        ["os.photos_search_hint"] = "Поиск по названию или месту…",
        ["os.folder_eject_title"] = "Убрать из папки?",
        ["os.folder_eject_body"] = "{0} вернётся на домашний экран.",
        ["os.tt_prev"] = "Назад",
        ["os.tt_next"] = "Вперёд",
        ["os.tt_edit"] = "Редактировать",
        ["os.tt_move"] = "Переместить в альбом",
        ["os.tt_share"] = "Поделиться",
        ["os.tt_open_folder"] = "Открыть папку на диске",
        ["os.share_wallpaper"] = "Обои",
        ["os.profile_edit_title"] = "Редактировать профиль",
        ["os.profile_save"] = "Сохранить",
        // home right-click menu (added after update 2.0.0)
        ["os.home_menu_adjust"] = "Настроить значки",
        ["os.home_menu_wallpaper"] = "Сменить обои",
        // news app tile rename (added after update 2.0.0)
        ["os.app_news_tile"] = "Новости",

        // battery easter egg (added after update 2.0.1)
        ["os.battery_grass_body"] = "Нам важно ваше здоровье: не забывайте выходить на улицу, пить воду и трогать травку ;-)",
        ["os.battery_grass_hint"] = "Потрогайте травку внизу, чтобы продолжить",
        ["os.settings_hide_battery_grass"] = "Скрывать напоминание про травку при разряженной батарее",
        // levemetes (added after update 2.0.1)
        ["os.app_levemetes"] = "Levemetes",
        ["os.battery_grass_settings_hint"] = "(Эту шутку можно отключить в разделе «Общие» приложения «Настройки»)",

        // added after update 2.0.1
        ["os.menu_audio"] = "Настройки звука",
        ["os.app_market"] = "Маркет",
        ["os.app_realtor"] = "Риелтор",

        // added after update 2.1.3
        ["os.app_wayfinder"] = "Wayfinder",
        ["os.app_yapper"] = "Yapper",
        ["os.arcade_leaderboard"] = "Таблица лидеров",
        ["os.arcade_tab_weekly"] = "За неделю",
        ["os.arcade_tab_alltime"] = "За всё время",
        ["os.arcade_loading"] = "Загрузка...",
        ["os.arcade_empty"] = "Пока нет результатов. Станьте первым!",
        ["os.arcade_error"] = "Не удалось загрузить таблицу лидеров.",
        ["os.arcade_you"] = "Вы",
        ["os.arcade_back"] = "Назад",
    };
}
