namespace AetherLove.Services.Localization;

internal static class ChatPt
{
    public static readonly System.Collections.Generic.Dictionary<string, string> Strings = new()
    {
        ["chat.no_conversation_selected"] = "Nenhuma conversa selecionada.",
        ["chat.unreadable_message"] = "[mensagem ilegível]",
        ["chat.report_submitted_toast"] = "Denúncia enviada. Nossa equipa de moderação vai analisá-la.",
        ["chat.view_profile"] = "Ver perfil",
        ["chat.back_to_matches"] = "Voltar aos matches",
        ["chat.menu_open_profile"] = "Abrir perfil",
        ["chat.menu_copy_message"] = "Copiar mensagem",
        ["chat.menu_pin"] = "Fixar conversa",
        ["chat.menu_unpin"] = "Desafixar conversa",
        ["chat.menu_unmatch"] = "Desfazer match",
        ["chat.menu_block"] = "Bloquear",
        ["chat.menu_report_user"] = "Denunciar Usuário",
        ["chat.unmatch_title"] = "Desfazer match",
        ["chat.unmatch_body"] = "Quando você desfaz o match com este jogador, a conversa fica oculta para os dois. Se vocês derem match de novo mais tarde, o histórico reaparece.",
        ["chat.unmatch_confirm"] = "Desfazer match",
        ["chat.block_title"] = "Bloquear Usuário",
        ["chat.block_body"] = "Quando você bloqueia alguém, a conversa fica oculta para os dois. Essa pessoa não vai mais aparecer nos seus matches.",
        ["chat.block_confirm"] = "Bloquear",
        ["chat.cancel"] = "Cancelar",
        ["chat.loading_messages"] = "Carregando mensagens…",
        ["chat.e2e_self_broken"] = "A criptografia deste perfil ainda não está configurada neste dispositivo, então não é possível enviar nem ler mensagens aqui.",
        ["chat.e2e_setup_button"] = "Configurar criptografia",
        ["chat.seen_suffix"] = " · visto",
        ["chat.send"] = "Enviar",
        ["chat.emoji_button"] = ":)",
        ["chat.system_notice_line1"] = "Este é um chat privado entre você e {0}. Este chat é criptografado de ponta a ponta. A equipe do AetherLove não consegue ler suas mensagens. O menu no canto superior direito permite desfazer o match, bloquear ou denunciar.",
        ["chat.system_notice_line2"] = "Lembra: {0} não sabe o teu nome completo nem a tua localização até ser compartilhado entre os dois. Cuida da Tua própria privacidade e só compartilha mais quando estiver pronto.",
        ["chat.i_understand"] = "Eu entendi",
        ["chat.report_title"] = "Denunciar Usuário",
        ["chat.report_reason_prompt"] = "Por favor, descreva o motivo da sua denúncia:",
        ["chat.report_agree"] = "Eu concordo em enviar uma denúncia contra {0}",
        ["chat.report_agree_contents"] = "Eu concordo em enviar o conteúdo desta conversa para a equipe do AetherLove",
        ["chat.submitting"] = "Enviando…",
        ["chat.submit"] = "Enviar",

        // Verify encryption
        ["verify.title"] = "Verificar a criptografia",
        ["verify.intro"] = "O AetherLove criptografa este chat de ponta a ponta: somente você e {0} podem lê-lo, nem mesmo nossa equipe. O padrão entrelaçado abaixo é gerado a partir das chaves de criptografia de vocês dois.",
        ["verify.unavailable"] = "A verificação ainda não está pronta. Ela ficará disponível assim que vocês dois tiverem configurado a criptografia e trocado as chaves.",
        ["verify.how"] = "Compare este padrão e este código com {0} por chat de voz ou pessoalmente. Se forem iguais, ninguém está interceptando o chat de vocês. Se não forem, pare de compartilhar qualquer coisa sensível e contate o suporte.",
        ["verify.your_key"] = "Sua chave pública",
        ["verify.their_key"] = "Chave pública de {0}",
        ["verify.keys_explain"] = "As chaves públicas podem ser compartilhadas com segurança; é assim que os aplicativos de vocês se reconhecem. As chaves privadas correspondentes nunca saem dos seus aparelhos, então nenhum servidor (nem mesmo o nosso) pode ler suas mensagens.",
        ["verify.back"] = "Voltar ao chat",

        // ChatListScreen
        ["chat.preview_me_prefix"] = "Eu: ",
        ["chat.preview_venue"] = "Compartilhou um local",
        ["chat.matches_title"] = "Matches",
        ["chat.show_search"] = "Mostrar busca",
        ["chat.hide_search"] = "Ocultar busca",
        ["chat.search_hint"] = "Nome ou mensagem",
        ["chat.searching"] = "Buscando…",
        ["chat.search_no_results"] = "Nenhum resultado encontrado",
        ["chat.matches_load_error"] = "Não foi possível carregar os matches: {0}",
        ["chat.connectivity_error"] = "Não conseguimos conectar ao servidor do AetherLove. Tente novamente ou veja o status do servidor no Discord.",
        ["chat.empty_state"] = "Você ainda não tem matches, mas isso vai mudar logo. Continue deslizando!",
        ["chat.new_match"] = "novo match",
        ["chat.say_hi"] = "Vocês deram match, diz olá!",
        ["chat.time_ago_minutes"] = "há {0}min",
        ["chat.time_ago_hours"] = "há {0}h",
        ["chat.time_ago_days"] = "há {0}d",

        // added after update (1.3.1)
        ["chat.you"] = "Você",
        ["chat.reply"] = "Responder",
        ["chat.pin_message"] = "Fixar mensagem",
        ["chat.unpin_message"] = "Desafixar mensagem",
        ["chat.pinned_messages"] = "Mensagens fixadas",
        ["chat.pinned_messages_menu"] = "Mensagens fixadas ({0})",
        ["chat.quote_unavailable"] = "(mensagem original indisponível)",
        ["chat.quote_generic"] = "(mensagem)",
        ["chat.replying_to"] = "Respondendo a {0}",
        ["chat.reaction_remove_hint"] = "clique para remover",
        ["chat.jump"] = "Ir",
        ["chat.unpin"] = "Desafixar",

        // added after update 1.4.3
        ["chat.menu_search"] = "Procurar mensagens",
        ["chat.search_messages_hint"] = "Procurar nesta conversa...",
        ["chat.category_new"] = "Nova categoria",
        ["chat.category_edit"] = "Editar categoria",
        ["chat.category_delete"] = "Eliminar categoria",
        ["chat.category_delete_body"] = "Tens a certeza de que queres eliminar {0}? As conversas lá dentro voltam para a tua lista de matches.",
        ["chat.category_delete_confirm"] = "Eliminar",
        ["chat.category_name_hint"] = "Nome da categoria",
        ["chat.category_create"] = "Criar",
        ["chat.category_save"] = "Guardar",
        ["chat.menu_move_to_category"] = "Mover para categoria",
        ["chat.menu_remove_from_category"] = "Remover da categoria",
        ["chat.category_empty"] = "Ainda não há conversas nesta categoria. Arrasta uma conversa para aqui ou clica com o botão direito numa conversa e escolhe Mover para categoria.",
        ["chat.category_count"] = "Conversas: {0}",
        ["chat.category_archive_default"] = "Arquivo",
        ["chat.all_categorized"] = "Todas as tuas conversas estão organizadas em categorias",

        // added after update 1.5.1
        ["chat.menu_view_blocked"] = "Ver bloqueados",
        ["blocked.title"] = "Usuários bloqueados",
        ["blocked.intro_body"] = "Você pode desbloquear qualquer pessoa desta lista. Desbloquear não traz o match de volta. Vocês podem voltar a se ver no deck.",
        ["blocked.empty"] = "Você não bloqueou ninguém.",
        ["blocked.loading"] = "Carregando...",
        ["blocked.since"] = "Bloqueado em {0}",
        ["blocked.unblock"] = "Desbloquear",
        ["blocked.confirm_title"] = "Desbloquear {0}?",
        ["blocked.confirm_body"] = "Não haverá match automático, mas vocês podem voltar a se ver no deck.",
        // generic share system (added after update 1.5.1)
        ["chat.news_card_label"] = "Notícias",
        ["chat.news_card_view"] = "Ler este artigo",
        ["chat.news_card_unavailable"] = "Este artigo não está mais disponível",
        ["chat.preview_news"] = "Compartilhou uma notícia",

        // Messenger invite bridge (added after update 1.5.1)
        ["chat.menu_invite_messenger"] = "Convidar para o Messenger",
        ["chat.msgr_card_title"] = "Convite do Messenger",
        ["chat.msgr_card_hint"] = "Toque para adicionar este código aos seus contatos",
        ["chat.preview_messenger"] = "Enviou um convite do Messenger",
        // Key reset notices (added after update 1.5.1)
        ["chat.keys_reset_peer"] = "{0} redefiniu as chaves de criptografia E2E",
        ["chat.keys_reset_you"] = "Você redefiniu suas chaves de criptografia. Você não consegue ler as mensagens anteriores.",
        // calendar event share
        ["chat.preview_calevent"] = "Compartilhou um evento",
        ["chat.preview_location"] = "Partilhou uma localização",
        ["chat.calevent_rsvp"] = "Vou",
        ["chat.calevent_add"] = "Adicionar ao calendário",
        // levemetes (added after update 2.0.1)
        ["chat.preview_levemete"] = "Partilhou um anúncio",
        ["chat.preview_market"] = "Compartilhou um achado do mercado",
        ["chat.market_card_label"] = "Mercado",
        ["chat.market_card_view"] = "Ver no mercado",
        ["chat.leve_kind_looking"] = "Procuro",
        ["chat.leve_kind_offering"] = "Ofereço",
        ["chat.leve_cat_1"] = "Decoração de casas",
        ["chat.leve_cat_2"] = "Gposing",
        ["chat.leve_cat_3"] = "Comissões",
        ["chat.leve_cat_4"] = "DJs",
        ["chat.leve_cat_5"] = "Equipa de venues",
        ["chat.leve_cat_6"] = "Bardos & bandas",
        ["chat.leve_cat_7"] = "Serviços mercenários",
        ["chat.leve_cat_8"] = "Criação & coleta",
        ["chat.leve_cat_9"] = "Serviços 18+",
        ["chat.leve_cat_unknown"] = "Outros",
        ["chat.leve_card_view"] = "Abrir o anúncio",
        ["chat.leve_card_loading"] = "A carregar anúncio...",
        ["chat.leve_card_unavailable"] = "Este anúncio já não está disponível.",
        // user notes (added after update 2.0.1)
        ["chat.menu_user_note"] = "Nota sobre a pessoa",
        ["chat.note_hint"] = "Só tu podes ver esta nota. Fica guardada neste computador e nunca é enviada para lado nenhum.",
        ["chat.note_save"] = "Guardar nota",
        ["chat.note_tooltip"] = "A tua nota:",
        // added after update 2.0.0.0 (message delete)
        ["chat.delete_message"] = "Eliminar mensagem",
        ["chat.delete_message_body"] = "Eliminar esta mensagem para todos? No lugar dela fica um aviso a dizer que a eliminaste.",
        ["chat.delete_message_confirm"] = "Eliminar",
        ["chat.deleted_by_author"] = "Esta mensagem foi eliminada pelo autor.",
        // added after update 2.2.3 (echo)
        ["chat.preview_echo"] = "Partilhou uma sala do Echo",
        ["chat.echo_card_label"] = "Sala do Echo",
        ["chat.echo_card_host"] = "Anfitrião: {0}",
        ["chat.echo_card_members"] = "{0} a ver",
        ["chat.echo_card_idle"] = "Ainda não está a passar nada",
        ["chat.echo_card_view"] = "Entrar nesta sala",
        ["chat.echo_card_loading"] = "A carregar sala...",
        ["chat.echo_card_unavailable"] = "Esta sala já terminou",
        ["chat.party_card_title"] = "Grupo de {0}",
        ["chat.party_card_members"] = "{0} de {1} juntos",
        ["chat.party_card_join"] = "Toque para entrar no grupo",
        ["chat.party_card_over"] = "Este grupo terminou",
        ["chat.party_card_loading"] = "Carregando grupo...",
        // chat images and the messenger invite (added after update 2.4.0)
        ["chat.attach_selfie"] = "Enviar uma selfie",
        ["chat.image_send_title"] = "Enviar esta selfie?",
        ["chat.image_moderation_note"] = "As tuas mensagens são cifradas de ponta a ponta, mas as imagens não. Verificamos cada imagem antes de ser enviada. A pessoa a quem a envias pode denunciá-la.",
        ["chat.image_expiry_label"] = "Desaparece após",
        ["chat.image_expiry_hours"] = "{0} h",
        ["chat.image_expiry_days"] = "{0} d",
        ["chat.image_expiry_supporter"] = "Mais de três dias é uma vantagem de apoiante.",
        ["chat.image_send"] = "Enviar",
        ["chat.image_cancel"] = "Cancelar",
        ["chat.image_loading"] = "A carregar...",
        ["chat.image_gone"] = "Esta imagem já não existe",
        ["chat.image_view"] = "Ver em tamanho real",
        ["chat.image_delete"] = "Apagar esta imagem",
        ["chat.image_report"] = "Denunciar esta imagem",
        ["chat.image_report_title"] = "Denunciar esta imagem",
        ["chat.image_report_hint"] = "Diz-nos o que está errado. Um moderador vê a imagem e o teu motivo.",
        ["chat.image_report_send"] = "Enviar denúncia",
        ["chat.image_err_rejected"] = "Essa imagem não pode ser enviada.",
        ["chat.image_err_full"] = "O teu armazenamento de imagens está cheio. As mais antigas libertam espaço ao expirar.",
        ["chat.image_err_large"] = "Essa imagem é demasiado grande.",
        ["chat.image_err_generic"] = "Não resultou. Tenta outra vez daqui a pouco.",
        ["chat.msgr_request_sent"] = "Pedido de Messenger enviado",
        ["chat.image_storage"] = "Armazenamento: {0} / {1} MB",
        ["chat.image_sending"] = "A enviar…",
        ["chat.image_expired"] = "Imagem expirada",
        ["chat.image_expires"] = "faltam {0} d",
        ["chat.image_viewer"] = "Imagem",
        ["chat.preview_image"] = "Enviou uma foto",
        ["chat.attach_photos"] = "Fotos",
        ["chat.attach_file"] = "De um ficheiro",
    };
}
