namespace AetherLove.Services.Localization;

internal static class ProfileRu
{
    public static readonly System.Collections.Generic.Dictionary<string, string> Strings = new()
    {
        ["profile.load_failed"] = "Не удалось загрузить профиль: {0}",
        ["profile.none_loaded"] = "Профиль не загружен.",

        ["profile.about"] = "О себе",
        ["profile.flairs"] = "Значки",
        ["profile.looking_for"] = "Ищу",
        ["profile.content_interests"] = "Предпочтения по контенту",
        ["profile.info"] = "Сведения",
        ["profile.gender"] = "Пол",
        ["profile.languages"] = "Языки",
        ["profile.timezone"] = "Часовой пояс",
        ["profile.favourite_job"] = "Любимая профессия",
        ["profile.favourite_location"] = "Любимое место",
        ["profile.favourite_expansion"] = "Любимое дополнение",
        ["profile.favourite_song"] = "Любимая песня",
        ["music.fetching"] = "Получение названия песни…",
        ["music.saved"] = "Ссылка сохранена (название ожидается)",
        ["music.invalid"] = "Не удалось распознать ссылку. Вставьте ссылку на песню из Spotify, SoundCloud, Apple Music или YouTube Music.",
        ["music.open_tooltip"] = "Нажмите, чтобы открыть",
        ["profile.favourite_movie"] = "Любимый фильм",
        ["profile.favourite_anime"] = "Любимое аниме",
        ["profile.favourite_ff_character"] = "Любимый персонаж FF",
        ["profile.sync_tool"] = "Плагин для синхронизации",
        ["profile.weekday_playtimes"] = "Время игры в будни  (Пн–Пт)",
        ["profile.weekend_playtimes"] = "Время игры в выходные  (Сб–Вс)",
        ["profile.timezone_value"] = "{0} (текущее время: {1})",

        ["profile.nsfw_reveal"] = "Нажмите, чтобы показать NSFW-изображение",

        ["profile.back_to_chat"] = "Назад в чат",
        ["profile.back_to_swiping"] = "Назад к анкетам",

        ["profile.report_profile"] = "Пожаловаться на профиль",
        ["profile.report_warning"] = "⚠  Ложные или недобросовестные жалобы приводят к предупреждениям на вашем собственном аккаунте, повторные нарушения могут привести к приостановке аккаунта. Пожалуйста, отправляйте жалобы только на профили, которые действительно нарушают правила.",
        ["profile.report_prompt"] = "Расскажите нашим модераторам, что не так с {0}:",
        ["profile.this_profile"] = "этим профилем",
        ["profile.report_agree"] = "Я понимаю, что ложные/недобросовестные жалобы могут привести к предупреждениям на моём аккаунте.",
        ["profile.submitting"] = "Отправка…",
        ["profile.cancel"] = "Отмена",
        ["profile.submit_report"] = "Отправить жалобу",
        ["profile.report_submitted"] = "Жалоба отправлена",
        ["profile.report_thanks"] = "Спасибо, модераторы всё проверят. Этот профиль больше не появится в вашей колоде.",
        ["profile.closing"] = "Закрытие…",
        ["profile.closing_in"] = "Закрытие через {0} секунд",
        ["profile.close"] = "Закрыть",

        // ProfileScreen - copy profile text (viewing others only)
        ["profile.copy_text"] = "Скопировать текст профиля",
        ["profile.copy_warning_title"] = "Предупреждение",
        ["profile.copy_warning_body"] = "Вы скопировали чужой текст. Будьте осторожны со ссылками в нём. Вы переходите по ним на свой страх и риск.",
        ["profile.copy_warning_agree"] = "Я понимаю и соглашаюсь",

        // MyProfileScreen hub: stats + menu
        ["profile.section_myprofile"] = "Мой профиль",
        ["profile.section_service"] = "Сервис",
        ["profile.menu_view"] = "Мой профиль",
        ["profile.menu_edit"] = "Изменить профиль",
        ["profile.menu_images"] = "Фото профиля",
        ["profile.stat_loves_you"] = "любят вас",
        ["profile.stat_matches"] = "Пары",
        ["profile.stat_match_rate"] = "Доля пар",
        ["profile.back_to_my"] = "← Назад",

        ["profile.load_profile_failed"] = "Не удалось загрузить ваш профиль: {0}",
        ["profile.retry"] = "Повторить",
        ["profile.saving"] = "Сохранение…",
        ["profile.saved"] = "Сохранено  ✓",
        ["profile.save_changes"] = "Сохранить изменения",

        ["profile.heading_character"] = "Персонаж",
        ["profile.heading_location"] = "Местоположение",
        ["profile.heading_languages"] = "Языки, на которых я говорю",
        ["profile.heading_content"] = "Мне нравится следующий контент",
        ["profile.heading_looking_for"] = "Я ищу",
        ["profile.heading_nsfw"] = "NSFW",
        ["profile.heading_optional"] = "Необязательно",
        ["profile.heading_playtime"] = "Время игры",
        ["profile.heading_timezone"] = "Часовой пояс",
        ["profile.heading_sync_tool"] = "Плагин для синхронизации",
        ["profile.heading_match_prefs"] = "Предпочтения для пар",

        ["profile.display_name"] = "Отображаемое имя",
        ["profile.about_me"] = "Обо мне",
        ["profile.char_count"] = "{0} / 500 символов",
        ["profile.preview"] = "Предпросмотр",
        ["profile.bio_placeholder"] = "Здесь появится ваше описание…",
        ["profile.race"] = "Раса",
        ["profile.region"] = "Регион",
        ["profile.languages_hint"] = "Выберите все языки, на которых вам комфортно общаться.",
        ["profile.content_hint"] = "Выберите всё подходящее.",
        ["profile.looking_for_hint"] = "Честность помогает находить лучше пары.",
        ["profile.nsfw_lalafell"] = "Взрослые и NSFW-функции недоступны, пока вашего персонажа - лалафель. Подробнее см. в 'Условиях использования'.",
        ["profile.nsfw_explainer"] = "NSFW означает «Not Safe For Work». В NSFW-контенте есть нагота или сексуальные темы. Включите, чтобы видеть NSFW-профили и находить с ними пары.",
        ["profile.nsfw_optin"] = "NSFW-профили: ДА",
        ["profile.favourite_job_tooltip"] = "Профессия или роль, которая вам нравится больше всего. Введите, чтобы отфильтровать.",
        ["profile.favourite_ff_character_full"] = "Любимый персонаж Final Fantasy",
        ["profile.weekday_playtimes_edit"] = "Время игры в будни (Пн–Пт)",
        ["profile.weekend_playtimes_edit"] = "Время игры в выходные (Сб–Вс)",
        ["profile.sync_tool_hint"] = "Плагины для синхронизации позволяют парам делиться модифицированным внешним видом.",
        ["profile.match_prefs_body"] = "Расскажите, кого бы вы хотели найти. Выбранные предпочтения улучшат поиск.",
        ["profile.all"] = "Все",
        ["profile.none"] = "Ничего",
        ["profile.clear"] = "Очистить",
        ["profile.filter_any_race"] = "  Нет выбора: любая раса",
        ["profile.filter_any_gender"] = "  Нет выбора: любой пол",
        ["profile.filter_any_region"] = "  Нет выбора: любой регион",
        ["profile.filter_any_language"] = "  Нет выбора: нет предпочтений по языку",
        ["profile.spoken_language"] = "Разговорный язык",
        ["profile.spoken_language_tooltip"] = "Если выбрано ничего, вам будет предложены анкеты всех доступных языков.",

        ["profile.load_photos_failed"] = "Не удалось загрузить ваши фотографии: {0}",
        ["profile.profile_picture"] = "Фото профиля",
        ["profile.profile_picture_desc"] = "Ваше фото профиля показывается в списке чатов и на карточках анкет. Используйте квадратный крупный портрет вашего персонажа FFXIV.",
        ["profile.profile_photos"] = "Фотографии профиля",
        ["profile.profile_photos_desc"] = "Добавьте портретные фотографии в профиль (соотношение 10:16). Первый слот обязателен; слоты 2–4 необязательны.",
        ["profile.declare_before_save"] = "Отметьте каждое дополнительное фото как SFW или NSFW перед сохранением.",

        ["profile.new_photo_ready"] = "Новое фото готово, ещё не сохранено.",
        ["profile.change_photo"] = "Сменить фото",
        ["profile.profile_picture_set"] = "Фото профиля: установлено  ✓",
        ["profile.no_profile_picture"] = "Фото профиля не установлено.",
        ["profile.upload_avatar"] = "Загрузить аватар…",

        ["profile.slot_main"] = "Главное",
        ["profile.tap_slot"] = "Нажмите на фото выше, чтобы добавить или сменить фото.",
        ["profile.main_photo"] = "Главное фото",
        ["profile.extra_photo"] = "Дополнительное фото {0}",
        ["profile.photo_will_be_removed"] = "Фото будет удалено.",
        ["profile.undo"] = "Отменить",
        ["profile.main_must_be_sfw"] = "Ваше главное фото профиля ДОЛЖНО быть SFW. Загрузка NSFW-изображения является основанием для приостановки или удаления аккаунта.",
        ["profile.sfw_or_nsfw"] = "Это изображение SFW или NSFW?",
        ["profile.sfw_mismatch_warning"] = "Наша система проверяет каждое фото. Если вы пометите NSFW-фото как SFW, мы отправим его на модерацию. Мы также можем приостановить ваш аккаунт.",
        ["profile.photo_ready"] = "Фото готово, ещё не сохранено.",
        ["profile.replace"] = "Заменить",
        ["profile.photo_set"] = "Фото установлено  ✓",
        ["profile.currently_nsfw"] = "Сейчас: NSFW",
        ["profile.currently_sfw"] = "Сейчас: SFW",
        ["profile.remove"] = "Удалить",
        ["profile.photo_required"] = "Это фото обязательно.",
        ["profile.photo_optional"] = "Это фото необязательно.",
        ["profile.upload_photo"] = "Загрузить фото…",

        ["profile.select_image"] = "Выбрать изображение",
        ["profile.image_files_filter"] = "Файлы изображений",
        ["profile.crop_avatar"] = "Обрезать аватар",
        ["profile.crop_main_photo"] = "Обрезать главное фото",
        ["profile.crop_extra_photo"] = "Обрезать дополнительное фото {0}",

        // added after update 1.4.3
        ["profile.menu_rp"] = "Мои RP-профили",
        ["profile.rp_intro_title"] = "Мои RP-профили",
        ["profile.rp_intro"] = "Добавьте своих OC (оригинальных персонажей) из FFXIV в профиль. У каждого персонажа есть имя, короткая предыстория и необязательное изображение, и они появятся в вашем профиле, чтобы другие могли их увидеть.",
        ["profile.characters"] = "Персонажи",
        ["profile.rp_add"] = "Добавить персонажа",
        ["profile.rp_empty"] = "Персонажей пока нет. Добавьте своего первого OC ниже!",
        ["profile.rp_limit_reached"] = "Можно добавить до {0} персонажей.",
        ["profile.rp_name"] = "Имя / Титул",
        ["profile.rp_bio"] = "Об этом персонаже",
        ["profile.rp_delete"] = "Удалить",
        ["profile.rp_delete_confirm"] = "Точно удалить?",
        ["profile.rp_move_up"] = "Выше",
        ["profile.rp_move_down"] = "Ниже",
        ["profile.rp_image"] = "Изображение",
        ["profile.rp_upload_image"] = "Загрузить изображение",
        ["profile.rp_replace_image"] = "Заменить изображение",
        ["profile.rp_remove_image"] = "Убрать изображение",
        ["profile.rp_image_ready"] = "Изображение готово к сохранению",
        ["profile.rp_image_nsfw"] = "Это изображение NSFW",
        ["profile.rp_image_expand"] = "Открыть в полном размере",
        ["profile.rp_image_back"] = "Назад к профилю",
        ["profile.rp_crop_image"] = "Обрезать изображение персонажа",
        ["profile.rp_back"] = "Назад",
        ["profile.rp_details"] = "Детали персонажа:",

        // added after update 1.5.1
        ["profile.slot_locked"] = "Для этого слота фото нужна активная подписка поддержки. Вы можете удалить фото или вновь оформить подписку, чтобы использовать слот.",
        ["profile.rp_extra_image"] = "Дополнительное изображение {0} (поддержавший)",
        ["profile.section_supporter"] = "Для поддержавших",
        ["profile.menu_sup_vanity"] = "Оформление профиля",
        ["profile.menu_sup_stats"] = "Расширенная статистика",
        ["profile.sup_intro"] = "Спасибо за поддержку AetherLove! Выберите стиль имени и видимость значка поддержки: они будут видны всем.",
        ["profile.sup_name_style"] = "Стиль имени",
        ["profile.sup_show_badge"] = "Показывать статус поддержки",
        ["profile.sup_badge_hint"] = "Выключите это, и никто не увидит вашу звезду или значок поддержки. Они будут скрыты в ваших профилях, в чатах, в хэнгаутах и в предпросмотре вашего собственного профиля. Все преимущества поддержки продолжают работать. Эта настройка действует на весь аккаунт.",
        ["profile.sup_stats_intro"] = "Эксклюзивная статистика для поддержавших: как ваш профиль показывает себя по всему миру.",
        ["profile.sup_stat_likes_received"] = "Полученные лайки",
        ["profile.sup_stat_superlikes"] = "Полученные суперлайки",
        ["profile.sup_stat_views"] = "Просмотрели ваш профиль",
        ["profile.sup_stat_impressions"] = "Показы в колодах",
        ["profile.sup_stat_likes_given"] = "Лайков поставлено",
        ["profile.sup_stat_passes_given"] = "Анкет пропущено",
        ["profile.sup_stat_matches"] = "Пары",
        ["profile.sup_stat_like_rate"] = "Ваша доля лайков",
        ["profile.sup_stat_match_rate"] = "Ваша доля пар",
        ["profile.style_none"] = "Обычный",
        ["profile.style_crimson"] = "Багровый",
        ["profile.style_gold"] = "Золотой",
        ["profile.style_emerald"] = "Изумрудный",
        ["profile.style_sapphire"] = "Сапфировый",
        ["profile.style_violet"] = "Фиолетовый",
        ["profile.style_rose"] = "Розовый",
        ["profile.style_rainbow"] = "Радуга (анимация)",
        ["profile.style_shimmer"] = "Золотое мерцание (анимация)",
        ["profile.style_pulse"] = "Розовый пульс (анимация)",

        // added after update 2.0.1
        ["profile.more_options"] = "Другие действия",
        ["profile.menu_hide"] = "Скрыть этот профиль",
        ["profile.menu_report"] = "Пожаловаться на этот профиль",
        ["profile.hide_title"] = "Скрыть профиль?",
        ["profile.hide_body"] = "Этот профиль больше никогда не появится в вашей колоде. Отменить это не получится.",
        ["profile.hide_confirm"] = "Скрыть навсегда",
        // holiday mode (added after update 2.0.1)
        ["profile.menu_holiday"] = "Режим отпуска",
        ["profile.holiday_toggle"] = "Режим отпуска включён",
        ["profile.holiday_msg_label"] = "Сообщение об отпуске",
        ["profile.holiday_msg_hint"] = "Режим отпуска показывает баннер с вашим сообщением всем, кто открывает ваш профиль. Ваши пары также видят значок отсутствия на вашем фото.",
        ["profile.holiday_save"] = "Сохранить",
        ["profile.holiday_saved"] = "Сохранено!",
        ["profile.holiday_active_banner"] = "РЕЖИМ ОТПУСКА ВКЛЮЧЁН",
        ["profile.holiday_banner"] = "У этого игрока включён режим отпуска: {0}",
        ["profile.holiday_banner_short"] = "У этого игрока включён режим отпуска.",

        // added after update 2.4.0
        ["profile.region_min_hint"] = "Выберите хотя бы один регион.",
    };
}
