namespace AetherLove.Services.Localization;

internal static class ChatRu
{
    public static readonly System.Collections.Generic.Dictionary<string, string> Strings = new()
    {
        ["chat.no_conversation_selected"] = "Чат не выбран.",
        ["chat.unreadable_message"] = "[нечитаемое сообщение]",
        ["chat.report_submitted_toast"] = "Жалоба отправлена. Команда модераторов рассмотрит её.",
        ["chat.view_profile"] = "Открыть профиль",
        ["chat.back_to_matches"] = "Назад к парам",
        ["chat.menu_open_profile"] = "Открыть профиль",
        ["chat.menu_copy_message"] = "Скопировать сообщение",
        ["chat.menu_pin"] = "Закрепить чат",
        ["chat.menu_unpin"] = "Открепить чат",
        ["chat.menu_unmatch"] = "Отменить пару",
        ["chat.menu_block"] = "Заблокировать",
        ["chat.menu_report_user"] = "Пожаловаться на пользователя",
        ["chat.unmatch_title"] = "Отменить пару",
        ["chat.unmatch_body"] = "При отмене пары с этим игроком, чат будет скрыт у обоих. При появлении пары в будущем, ваша история появится вновь.",
        ["chat.unmatch_confirm"] = "Отменить пару",
        ["chat.block_title"] = "Заблокировать пользователя",
        ["chat.block_body"] = "Когда вы кого-то блокируете, чат скрывается у вас обоих. Этот человек больше не появится в ваших парах.",
        ["chat.block_confirm"] = "Заблокировать",
        ["chat.cancel"] = "Отмена",
        ["chat.loading_messages"] = "Загрузка сообщений…",
        ["chat.e2e_self_broken"] = "Шифрование для этого профиля ещё не настроено на этом устройстве, поэтому здесь нельзя отправлять и читать сообщения.",
        ["chat.e2e_setup_button"] = "Настроить шифрование",
        ["chat.seen_suffix"] = " · просмотрено",
        ["chat.send"] = "Отправить",
        ["chat.emoji_button"] = ":)",
        ["chat.system_notice_line1"] = "Это приватный чат между вами и {0}. Чат защищён сквозным шифрованием. Администрация AetherLove не может читать ваши сообщения. В меню справа вверху можно отменить пару, заблокировать её или пожаловаться.",
        ["chat.system_notice_line2"] = "Помните: {0} не знает вашего полного имени или местоположения, до тех пор, пока вы сами не поделитесь этим. Будьте осторожны с чувствительной/конфиденциальной информацией и делитесь этим, только когда будете уверены в этом.",
        ["chat.i_understand"] = "Понятно",
        ["chat.report_title"] = "Пожаловаться на пользователя",
        ["chat.report_reason_prompt"] = "Пожалуйста, опишите причину вашей жалобы:",
        ["chat.report_agree"] = "Я согласен(а) подать жалобу на {0}",
        ["chat.report_agree_contents"] = "Я согласен(а) отправить содержимое этого чата администрации AetherLove",
        ["chat.submitting"] = "Отправка…",
        ["chat.submit"] = "Отправить",

        // Verify encryption
        ["verify.title"] = "Проверить шифрование",
        ["verify.intro"] = "AetherLove шифрует этот чат сквозным шифрованием: доступ к нему есть только у вас и {0}. Администрация не имеет доступа к сообщениям. Сплетённый узор ниже создаётся из ваших двух ключей шифрования.",
        ["verify.unavailable"] = "Проверка пока недоступна. Она появится, как только у обеих сторон произойдет настройка шифрования и обмен ключами.",
        ["verify.how"] = "Сравните этот узор и код с {0} в голосовом чате или лично. Если они совпадают, ваш чат никто не перехватывает. Если не совпадают, не передавайте ничего важного и обратитесь в поддержку.",
        ["verify.your_key"] = "Ваш открытый ключ",
        ["verify.their_key"] = "Открытый ключ {0}",
        ["verify.keys_explain"] = "Открытыми ключами можно безопасно делиться; они служат публичными идентификаторами для ваших приложений. Соответствующие закрытые ключи никогда не покидают ваши устройства, поэтому ни один сервер (даже наш) не может прочитать ваши сообщения.",
        ["verify.back"] = "Назад к чату",

        // ChatListScreen
        ["chat.preview_me_prefix"] = "Я: ",
        ["chat.preview_venue"] = "Поделились заведением",
        ["chat.matches_title"] = "Пары",
        ["chat.show_search"] = "Показать поиск",
        ["chat.hide_search"] = "Скрыть поиск",
        ["chat.search_hint"] = "Имя или сообщение",
        ["chat.searching"] = "Поиск…",
        ["chat.search_no_results"] = "Ничего не найдено",
        ["chat.matches_load_error"] = "Не удалось загрузить пары: {0}",
        ["chat.connectivity_error"] = "Не удалось подключиться к серверу AetherLove. Попробуйте ещё раз или посмотрите статус сервера в Discord.",
        ["chat.empty_state"] = "У вас пока нет пар, но скоро это изменится. Продолжайте листать!",
        ["chat.new_match"] = "новая пара",
        ["chat.say_hi"] = "У Вас пара! Скажите привет!",
        ["chat.time_ago_minutes"] = "{0} мин назад",
        ["chat.time_ago_hours"] = "{0} ч назад",
        ["chat.time_ago_days"] = "{0} дн назад",

        // added after update (1.3.1)
        ["chat.you"] = "Вы",
        ["chat.reply"] = "Ответить",
        ["chat.pin_message"] = "Закрепить сообщение",
        ["chat.unpin_message"] = "Открепить сообщение",
        ["chat.pinned_messages"] = "Закреплённые сообщения",
        ["chat.pinned_messages_menu"] = "Закреплённые сообщения ({0})",
        ["chat.quote_unavailable"] = "(исходное сообщение недоступно)",
        ["chat.quote_generic"] = "(сообщение)",
        ["chat.replying_to"] = "Ответ для {0}",
        ["chat.reaction_remove_hint"] = "нажмите, чтобы убрать",
        ["chat.jump"] = "Перейти",
        ["chat.unpin"] = "Открепить",

        // added after update 1.4.3
        ["chat.menu_search"] = "Поиск сообщений",
        ["chat.search_messages_hint"] = "Искать в этом чате...",
        ["chat.category_new"] = "Новая категория",
        ["chat.category_edit"] = "Изменить категорию",
        ["chat.category_delete"] = "Удалить категорию",
        ["chat.category_delete_body"] = "Удалить {0}? Чаты из этой категории вернутся в общий список пар.",
        ["chat.category_delete_confirm"] = "Удалить",
        ["chat.category_name_hint"] = "Название категории",
        ["chat.category_create"] = "Создать",
        ["chat.category_save"] = "Сохранить",
        ["chat.menu_move_to_category"] = "Переместить в категорию",
        ["chat.menu_remove_from_category"] = "Убрать из категории",
        ["chat.category_empty"] = "В этой категории пока нет чатов. Перетащите чат сюда или щёлкните по чату правой кнопкой и выберите «Переместить в категорию».",
        ["chat.category_count"] = "Чаты: {0}",
        ["chat.category_archive_default"] = "Архив",
        ["chat.all_categorized"] = "Все ваши чаты разложены по категориям",

        // added after update 1.5.1
        ["chat.menu_view_blocked"] = "Заблокированные",
        ["blocked.title"] = "Заблокированные пользователи",
        ["blocked.intro_body"] = "Здесь можно разблокировать любого из списка. Разблокировка не возвращает пару. Зато вы снова можете увидеть друг друга в колоде.",
        ["blocked.empty"] = "Вы никого не заблокировали.",
        ["blocked.loading"] = "Загрузка...",
        ["blocked.since"] = "Заблокирован {0}",
        ["blocked.unblock"] = "Разблокировать",
        ["blocked.confirm_title"] = "Разблокировать {0}?",
        ["blocked.confirm_body"] = "Пара не восстановится автоматически, но вы снова сможете увидеть друг друга в колоде.",
        // generic share system (added after update 1.5.1)
        ["chat.news_card_label"] = "Новости",
        ["chat.news_card_view"] = "Читать статью",
        ["chat.news_card_unavailable"] = "Эта статья больше недоступна",
        ["chat.preview_news"] = "Поделился новостью",

        // Messenger invite bridge (added after update 1.5.1)
        ["chat.menu_invite_messenger"] = "Пригласить в Messenger",
        ["chat.msgr_card_title"] = "Приглашение в Messenger",
        ["chat.msgr_card_hint"] = "Нажмите, чтобы добавить этот код в контакты",
        ["chat.preview_messenger"] = "Отправил(а) приглашение в Messenger",
        // Key reset notices (added after update 1.5.1)
        ["chat.keys_reset_peer"] = "{0} сбросил(а) свои ключи сквозного шифрования",
        ["chat.keys_reset_you"] = "Вы сбросили ключи шифрования. Старые сообщения вы больше не прочитаете.",
        // calendar event share
        ["chat.preview_calevent"] = "Поделились событием",
        ["chat.preview_location"] = "Поделились местоположением",
        ["chat.calevent_rsvp"] = "Пойду",
        ["chat.calevent_add"] = "Добавить в календарь",
        // levemetes (added after update 2.0.1)
        ["chat.preview_levemete"] = "Поделились объявлением",
        ["chat.preview_market"] = "Поделился находкой с маркета",
        ["chat.market_card_label"] = "Маркет",
        ["chat.market_card_view"] = "Открыть в маркете",
        ["chat.leve_kind_looking"] = "Ищу",
        ["chat.leve_kind_offering"] = "Предлагаю",
        ["chat.leve_cat_1"] = "Оформление домов",
        ["chat.leve_cat_2"] = "Gpose-съёмка",
        ["chat.leve_cat_3"] = "Комиссии",
        ["chat.leve_cat_4"] = "Диджеи",
        ["chat.leve_cat_5"] = "Персонал для венью",
        ["chat.leve_cat_6"] = "Барды и группы",
        ["chat.leve_cat_7"] = "Услуги наёмников",
        ["chat.leve_cat_8"] = "Крафт и сбор",
        ["chat.leve_cat_9"] = "Услуги 18+",
        ["chat.leve_cat_unknown"] = "Другое",
        ["chat.leve_card_view"] = "Открыть объявление",
        ["chat.leve_card_loading"] = "Загружаем объявление...",
        ["chat.leve_card_unavailable"] = "Это объявление больше недоступно.",
        // user notes (added after update 2.0.1)
        ["chat.menu_user_note"] = "Заметка о собеседнике",
        ["chat.note_hint"] = "Эту заметку видите только вы. Она хранится на этом компьютере и никуда не отправляется.",
        ["chat.note_save"] = "Сохранить заметку",
        ["chat.note_tooltip"] = "Ваша заметка:",
        // added after update 2.0.0.0 (message delete)
        ["chat.delete_message"] = "Удалить сообщение",
        ["chat.delete_message_body"] = "Удалить это сообщение у всех? На его месте появится пометка о том, что вы его удалили.",
        ["chat.delete_message_confirm"] = "Удалить",
        ["chat.deleted_by_author"] = "Это сообщение удалено автором.",
        // added after update 2.2.3 (echo)
        ["chat.preview_echo"] = "Поделился комнатой Echo",
        ["chat.echo_card_label"] = "Комната Echo",
        ["chat.echo_card_host"] = "Хост: {0}",
        ["chat.echo_card_members"] = "смотрят: {0}",
        ["chat.echo_card_idle"] = "Пока ничего не играет",
        ["chat.echo_card_view"] = "Присоединиться к комнате",
        ["chat.echo_card_loading"] = "Загружаем комнату...",
        ["chat.echo_card_unavailable"] = "Эта комната уже закрыта",
        ["chat.party_card_title"] = "Отряд игрока {0}",
        ["chat.party_card_members"] = "{0} из {1} вместе",
        ["chat.party_card_join"] = "Нажмите, чтобы войти в отряд",
        ["chat.party_card_over"] = "Этого отряда больше нет",
        ["chat.party_card_loading"] = "Загрузка отряда...",
        // chat images and the messenger invite (added after update 2.4.0)
        ["chat.attach_selfie"] = "Отправить селфи",
        ["chat.image_send_title"] = "Отправить это селфи?",
        ["chat.image_moderation_note"] = "Ваши сообщения защищены сквозным шифрованием, а картинки нет. Мы проверяем каждую картинку перед отправкой. Получатель может пожаловаться на неё.",
        ["chat.image_expiry_label"] = "Исчезнет через",
        ["chat.image_expiry_hours"] = "{0} ч",
        ["chat.image_expiry_days"] = "{0} дн.",
        ["chat.image_expiry_supporter"] = "Больше трёх дней доступно спонсорам.",
        ["chat.image_send"] = "Отправить",
        ["chat.image_cancel"] = "Отмена",
        ["chat.image_loading"] = "Загрузка...",
        ["chat.image_gone"] = "Этой картинки больше нет",
        ["chat.image_view"] = "Открыть во весь экран",
        ["chat.image_delete"] = "Удалить эту картинку",
        ["chat.image_report"] = "Пожаловаться на картинку",
        ["chat.image_report_title"] = "Жалоба на картинку",
        ["chat.image_report_hint"] = "Расскажи, что с ней не так. Модератор увидит картинку и твою причину.",
        ["chat.image_report_send"] = "Отправить жалобу",
        ["chat.image_err_rejected"] = "Эту картинку отправить нельзя.",
        ["chat.image_err_full"] = "Хранилище картинок заполнено. Старые освободят место, когда истечёт срок.",
        ["chat.image_err_large"] = "Эта картинка слишком большая.",
        ["chat.image_err_generic"] = "Не получилось. Попробуй ещё раз через минуту.",
        ["chat.msgr_request_sent"] = "Запрос в Messenger отправлен",
        ["chat.image_storage"] = "Хранилище: {0} / {1} МБ",
        ["chat.image_sending"] = "Отправляем…",
        ["chat.image_expired"] = "Фото удалено",
        ["chat.image_expires"] = "осталось {0} дн.",
        ["chat.image_viewer"] = "Изображение",
        ["chat.preview_image"] = "Отправили фото",
        ["chat.attach_photos"] = "Фото",
        ["chat.attach_file"] = "Из файла",
    };
}
