namespace AetherLove.Services.Localization;

internal static class OsPt
{
    public static readonly System.Collections.Generic.Dictionary<string, string> Strings = new()
    {
        // added after update 1.5.1
        // App names
        ["os.app_clock"] = "Relógio",
        ["os.app_camera"] = "Câmera",

        // Notification shade
        ["os.notifications"] = "Notificações",
        ["os.notifications_empty"] = "Sem notificações",
        ["os.notifications_clear"] = "Limpar tudo",
        ["os.notif_remove"] = "Remover",
        ["os.time_now"] = "agora",
        ["os.qt_notifications"] = "Notificações",
        ["os.qt_sounds"] = "Sons de notificação",
        ["os.qt_lock"] = "Bloquear posição do telefone",
        ["os.qt_theme"] = "Próximo tema",
        ["os.qt_wallpaper"] = "Próximo papel de parede",

        // Home screen
        ["os.edit_done"] = "Concluído",
        ["os.greeting_morning"] = "Bom dia",
        ["os.greeting_afternoon"] = "Boa tarde",
        ["os.greeting_evening"] = "Boa noite",
        ["os.greeting_night"] = "Ainda de pé?",
        ["os.widget_eorzea"] = "Eorzea",
        ["os.widget_status"] = "Conexão",
        ["os.widget_connected"] = "Conectado",
        ["os.widget_offline"] = "Offline",
        ["os.widget_unread"] = "{0} não lidas",

        // OS settings
        ["os.group_appearance"] = "Aparência",
        ["os.group_wallpaper"] = "Tela inicial e papel de parede",
        ["os.group_home"] = "Tela inicial",
        ["os.group_apps"] = "Configurações de cada app",
        ["os.group_about"] = "Sobre",
        ["os.wallpaper_gradient"] = "Tema",
        ["os.wallpaper_custom"] = "Seu",
        ["os.wallpaper_upload"] = "Enviar imagem…",
        ["os.wallpaper_dim"] = "Escurecer papel de parede",
        ["os.home_edit_hint"] = "Segure um ícone na tela inicial para reorganizá-lo. Arraste ícones para o dock ou entre páginas.",
        ["os.home_reset"] = "Redefinir layout",
        ["os.about_demo"] = "Demo da interface do AetherOS",

        // Love settings hub after the appearance move
        ["settings.menu_language"] = "Idioma e hora",

        // Weatherman app
        ["os.app_weather"] = "Meteorologia",

        // Messenger app
        ["os.app_messenger"] = "Messenger",

        // Photos app
        ["os.app_photos"] = "Fotos",

        // Home screen app launcher
        ["os.add_apps"] = "Adicionar apps",
        ["os.add_apps_title"] = "Adicionar apps",
        ["os.add_apps_hint"] = "Fixe outros plugins do Dalamud instalados na sua tela inicial.",
        ["os.add_apps_none"] = "Nenhum outro plugin oferece uma janela principal.",
        ["os.add_apps_add"] = "Adicionar",
        ["os.add_apps_added"] = "Adicionado",
        ["os.add_apps_search"] = "Buscar apps...",
        ["os.remove_app_title"] = "Remover app",
        ["os.remove_app_body"] = "Quer remover {0} da sua tela inicial?",
        ["os.remove_app_confirm"] = "Remover",
        // added after update 1.5.1
        ["os_onboarding.header_welcome"] = "Bem-vindo",
        ["os_onboarding.header_design"] = "Deixe do seu jeito",
        ["os_onboarding.header_name"] = "Seu nome",
        ["os_onboarding.header_terms"] = "Termos de serviço",
        ["os_onboarding.welcome_title"] = "Bem-vindo ao AetherOS",
        ["os_onboarding.welcome_body"] = "Este é o seu telefone. Vamos configurá-lo: escolha um visual, um nome e aceite as regras básicas. Leva só um instante.",
        ["os_onboarding.design_title"] = "Escolha um design",
        ["os_onboarding.name_title"] = "Como devemos te chamar?",
        ["os_onboarding.name_body"] = "Este nome é usado em todo o AetherOS. Você pode escolher um nome diferente para cada app depois.",
        ["os_onboarding.name_hint"] = "Nome",
        ["os_onboarding.terms_title"] = "As regras básicas",
        ["os_onboarding.terms_agree"] = "Aceito os Termos de serviço",
        ["os_onboarding.finish"] = "Concluir",
        ["os_onboarding.header_signin"] = "Entrar",
        ["os_onboarding.header_passphrase"] = "Frase-senha",
        ["os_onboarding.tos_1"] = "O AetherOS é um plugin feito por fãs, fornecido como está, sem qualquer garantia. Ele pode falhar, perder dados ou parar de funcionar a qualquer momento, e o uso é por sua conta e risco.",
        ["os_onboarding.tos_2"] = "O AetherOS não é afiliado, endossado ou patrocinado pela Square Enix.",
        ["os_onboarding.tos_3"] = "FINAL FANTASY e FINAL FANTASY XIV são marcas registradas da Square Enix Holdings Co., Ltd. Todas as outras marcas pertencem aos seus respectivos donos.",
        ["os_onboarding.tos_4"] = "Ao continuar, você aceita estes termos.",
        // OS account avatar (added after update 1.5.1)
        ["os_onboarding.header_avatar"] = "Avatar",
        ["os_onboarding.avatar_title"] = "Adicione uma foto",
        ["os_onboarding.avatar_body"] = "Escolha uma imagem para o seu perfil do AetherOS. É opcional e só você a vê; pode mudá-la quando quiser.",
        ["os_onboarding.avatar_choose"] = "Escolher foto",
        ["os_onboarding.avatar_change"] = "Alterar foto",
        // two-onboarding split (added after update 1.5.1)
        ["os_onboarding.header_done"] = "Pronto",
        ["os_onboarding.done_title"] = "Tudo pronto!",
        ["os_onboarding.done_body"] = "Sua conta AetherOS está pronta. Aproveite seu novo telefone!",
        ["os_onboarding.done_start"] = "Começar a usar o plugin",
        ["os_onboarding.design_language"] = "Idioma",
        // combined OS profile step (added after update 1.5.1)
        ["os_onboarding.header_profile"] = "Seu perfil",
        ["os_onboarding.profile_name_label"] = "Seu nome",
        ["os_onboarding.profile_photo_label"] = "Sua foto",
        // home button tooltip (added after update 1.5.1)
        ["os.home"] = "Início",
        // settings-consolidation categories + reset-home confirm + profile edit (added after update 1.5.1)
        ["os.cat_general"] = "Geral",
        ["os.cat_appearance"] = "Aparência",
        ["os.cat_other"] = "Outros",
        ["os.menu_general"] = "Geral",
        ["os.menu_appearance"] = "Aparência do telemóvel",
        ["os.menu_reset_home"] = "Repor ecrã inicial",
        ["os.reset_home_confirm_title"] = "Repor o ecrã inicial?",
        ["os.reset_home_confirm_body"] = "Isto limpa a tua disposição de ícones e a dock personalizadas, restaurando a disposição predefinida. As tuas apps e definições não são afetadas.",
        ["os.edit_profile"] = "Editar",
        // Daily Eorzean news app (added after update 1.5.1)
        ["os.app_news"] = "O Diário de Eorzea",
        ["os.news_notifications"] = "Notificações de notícias",
        ["os.news_tagline"] = "Est. · Todas as notícias do reino",
        ["os.news_latest"] = "Recente",
        ["os.news_more"] = "Mais notícias",
        ["os.news_edition"] = "Edição · {0}",
        ["os.news_refresh"] = "Atualizar",
        ["os.news_new"] = "Novo",
        // Feedback app (added after update 1.5.1)
        ["os.app_feedback"] = "Comentários",
        ["os.feedback_app_label"] = "Sobre qual aplicativo é?",
        ["os.feedback_general"] = "Geral",
        ["os.feedback_send_another"] = "Enviar mais comentários",
        // generic share system (added after update 1.5.1)
        ["os.share_sheet_title"] = "Compartilhar com",
        // home grid + folders
        ["os.settings_home_screen"] = "Tela inicial",
        ["os.settings_home_grid_caption"] = "Os ícones se reorganizam automaticamente para caber na nova grade.",
        ["os.new_folder"] = "Nova pasta",
        ["os.folder_name_hint"] = "Nome da pasta…",
        ["os.folder_default_name"] = "Pasta",
        ["os.folder_edit"] = "Editar",
        ["os.folder_empty"] = "Nenhum app ainda. Arraste um ícone para esta pasta para adicioná-lo.",
        // photo filters + screenshot import
        ["os.filter_original"] = "Original",
        ["os.filter_mono"] = "Mono",
        ["os.filter_noir"] = "Noir",
        ["os.filter_sepia"] = "Sépia",
        ["os.filter_retro"] = "Retrô",
        ["os.filter_cool"] = "Frio",
        ["os.filter_vivid"] = "Vívido",
        ["os.filter_fade"] = "Desbotado",
        ["os.filter_applying"] = "Aplicando…",
        ["os.screenshots_album"] = "Capturas",
        // calendar app
        ["os.app_calendar"] = "Calendário",
        ["os.edit_filters"] = "Filtros",
        ["os.edit_adjust"] = "Ajustes",
        ["os.edit_brightness"] = "Brilho",
        ["os.edit_contrast"] = "Contraste",
        ["os.edit_hue"] = "Matiz",
        ["os.edit_tint"] = "Intensidade",
        // guided OS tour
        ["os.settings_tour"] = "Fazer o tour",
        ["os.tour_next"] = "Avançar",
        ["os.tour_back"] = "Voltar",
        ["os.tour_skip"] = "Pular",
        ["os.tour_finish"] = "Pronto",
        ["os.tour_welcome_title"] = "Bem-vindo ao AetherOS",
        ["os.tour_welcome_body"] = "Este é o seu telefone: uma tela inicial cheia de apps, e o AetherLove é só um deles. Vamos dar uma olhada rápida, leva só um minuto.",
        ["os.tour_homebtn_title"] = "Seu botão de início",
        ["os.tour_homebtn_body"] = "Você sempre pode voltar à tela inicial com o botão de início, aquele que está brilhando na parte de baixo do telefone.",
        ["os.tour_pages_title"] = "Sua tela inicial",
        ["os.tour_pages_body"] = "Seus apps ficam na tela inicial. Deslize para os lados para trocar de página; os pontos destacados mostram em qual página você está.",
        ["os.tour_widgets_title"] = "A página de widgets",
        ["os.tour_widgets_body"] = "Acabamos de deslizar até a página de widgets por você. Ela fica à esquerda dos seus apps e mostra o relógio com a hora de Eorzea, o status da conexão e sua notificação mais recente.",
        ["os.tour_statusbar_title"] = "A barra de status",
        ["os.tour_statusbar_body"] = "A faixa destacada lá no topo mostra a hora, a conexão com os servidores do AetherLove, quantas notificações esperam e a bateria. Um ícone vermelho aparece ali se a conexão cair.",
        ["os.tour_shade_title"] = "Notificações",
        ["os.tour_shade_body"] = "Toque no topo do telefone (ou arraste-o para baixo) para ver suas notificações, como fizemos agora. Ali também ficam os atalhos rápidos e o controle de brilho. Toque em uma notificação para abrir, deslize para dispensar.",
        ["os.tour_fake_notif_title"] = "Olá!",
        ["os.tour_fake_notif_body"] = "É assim que uma notificação aparece.",
        ["os.tour_badges_title"] = "Selos",
        ["os.tour_badges_body"] = "Os ícones mostram um contadorzinho quando algo espera por você, como mensagens não lidas ou novos matches. Ele some ao abrir o app. (Calma, você não tem 67 de verdade.)",
        ["os.tour_edit_title"] = "Deixe do seu jeito",
        ["os.tour_edit_body"] = "Clique e segure um ícone e tudo começa a tremer, como agora. Arraste os ícones para onde quiser: outro lugar, outra página ou a fileira de baixo. Toque no botão Pronto destacado quando terminar.",
        ["os.tour_dock_title"] = "O dock",
        ["os.tour_dock_body"] = "A fileira de baixo fica visível em todas as páginas. Cabem até quatro favoritos; arraste ícones para dentro e para fora ao reorganizar.",
        ["os.tour_folders_title"] = "Pastas",
        ["os.tour_folders_body"] = "Os ícones podem ser agrupados em pastas, como o exemplo que acabou de aparecer. Crie as suas pelo bloco + e arraste ícones sobre elas para organizar. Toque numa pasta para abrir, renomear ou tirar apps.",
        ["os.tour_addapps_title"] = "Mais apps",
        ["os.tour_addapps_body"] = "O bloco + no fim dos seus apps abre esta lista. Aqui dá para criar pastas e até adicionar seus outros plugins do Dalamud à tela inicial. Remova com o X ao reorganizar.",
        ["os.tour_share_title"] = "Compartilhar",
        ["os.tour_share_body"] = "Você pode compartilhar locais, encontros e muito mais com seus matches e amigos. O compartilhamento funciona entre os diferentes apps: escolha o que compartilhar e para onde vai, e chega como um cartão interativo.",
        ["os.tour_look_title"] = "Aparência",
        ["os.tour_look_body"] = "No app de Configurações destacado você escolhe um tema, troca o papel de parede (ou envia o seu), ajusta o tamanho da grade e até o do próprio telefone.",
        ["os.tour_offline_title"] = "Offline",
        ["os.tour_offline_body"] = "Você pode continuar usando o telefone mesmo quando o AetherLove ou outros apps integrados estiverem indisponíveis. Apps que precisam dos servidores ficam levemente escurecidos com uma marquinha, mas todo o resto continua funcionando normalmente.",
        ["os.tour_done_title"] = "Fim do tour!",
        ["os.tour_done_body"] = "Você pode repeti-lo quando quiser nas Configurações. Agora explore os apps e divirta-se.",
        ["os.tour_demo_folder"] = "Exemplo",
        ["os.photos_search_hint"] = "Buscar por nome ou lugar…",
        ["os.folder_eject_title"] = "Remover da pasta?",
        ["os.folder_eject_body"] = "{0} voltará para a sua tela inicial.",
        ["os.tt_prev"] = "Anterior",
        ["os.tt_next"] = "Próxima",
        ["os.tt_edit"] = "Editar",
        ["os.tt_move"] = "Mover para um álbum",
        ["os.tt_share"] = "Compartilhar",
        ["os.tt_open_folder"] = "Abrir pasta no disco",
        ["os.share_wallpaper"] = "Papel de parede",
        ["os.profile_edit_title"] = "Editar perfil",
        ["os.profile_save"] = "Salvar",
        // home right-click menu (added after update 2.0.0)
        ["os.home_menu_adjust"] = "Ajustar ícones",
        ["os.home_menu_wallpaper"] = "Alterar papel de parede",
        // news app tile rename (added after update 2.0.0)
        ["os.app_news_tile"] = "Notícias",
    };
}
