namespace AetherLove.Services.Localization;

internal static class OsPt
{
    public static readonly System.Collections.Generic.Dictionary<string, string> Strings = new()
    {
        // added after update 1.5.1
        // App names
        ["os.app_clock"] = "Relógio",
        ["os.app_snake"] = "Snake",
        ["os.app_doom"] = "DOOM",
        ["os.app_sudoku"] = "Sudoku",
        ["os.app_stacker"] = "Stacker",
        ["os.app_breaker"] = "Breaker",
        ["os.app_meteor"] = "Meteor Command",
        ["os.app_invaders"] = "Void Invaders",
        ["os.app_muncher"] = "Maze Muncher",
        ["os.app_camera"] = "Câmera",

        // Notification shade
        ["os.notifications"] = "Notificações",
        ["os.notifications_empty"] = "Sem notificações",
        ["os.notifications_clear"] = "Limpar tudo",
        ["os.notif_remove"] = "Remover",
        ["os.time_now"] = "agora",
        ["os.qt_notifications"] = "Notificações",
        ["os.qt_sounds"] = "Sons de notificação",
        ["os.qt_lock"] = "Bloquear posição do telefone",
        ["os.qt_theme"] = "Próximo tema",
        ["os.qt_wallpaper"] = "Próximo papel de parede",

        // Home screen
        ["os.greeting_morning"] = "Bom dia",
        ["os.greeting_afternoon"] = "Boa tarde",
        ["os.greeting_evening"] = "Boa noite",
        ["os.greeting_night"] = "Ainda de pé?",
        ["os.widget_eorzea"] = "Eorzea",
        ["os.widget_status"] = "Conexão",
        ["os.widget_connected"] = "Conectado",
        ["os.widget_offline"] = "Offline",
        ["os.widget_unread"] = "{0} não lidas",

        // OS settings
        ["os.group_appearance"] = "Aparência",
        ["os.group_wallpaper"] = "Tela inicial e papel de parede",
        ["os.group_home"] = "Tela inicial",
        ["os.group_apps"] = "Configurações de cada app",
        ["os.group_about"] = "Sobre",
        ["os.wallpaper_gradient"] = "Tema",
        ["os.wallpaper_custom"] = "Seu",
        ["os.wallpaper_upload"] = "Enviar imagem…",
        ["os.wallpaper_dim"] = "Escurecer papel de parede",
        ["os.home_edit_hint"] = "Segure um ícone na tela inicial para reorganizá-lo. Arraste ícones para o dock ou entre páginas.",
        ["os.home_reset"] = "Redefinir layout",

        // Love settings hub after the appearance move
        ["settings.menu_language"] = "Idioma e hora",

        // Weatherman app
        ["os.app_weather"] = "Meteorologia",

        // Messenger app
        ["os.app_messenger"] = "Messenger",

        // Photos app
        ["os.app_photos"] = "Fotos",

        // Home screen app launcher
        ["os.add_apps"] = "Adicionar apps",
        ["os.add_apps_title"] = "Adicionar apps",
        ["os.add_apps_hint"] = "Traga de volta um app que removeu ou fixe outro plugin do Dalamud instalado.",
        ["os.add_apps_none"] = "Nenhum outro plugin oferece uma janela principal.",
        ["os.add_apps_add"] = "Adicionar",
        ["os.add_apps_added"] = "Adicionado",
        ["os.add_apps_search"] = "Buscar apps...",
        ["os.remove_app_title"] = "Remover app",
        ["os.remove_app_body"] = "Quer remover {0} da sua tela inicial?",
        ["os.remove_app_confirm"] = "Remover",
        // added after update 1.5.1
        ["os_onboarding.header_welcome"] = "Bem-vindo",
        ["os_onboarding.header_design"] = "Deixe do seu jeito",
        ["os_onboarding.header_name"] = "Seu nome",
        ["os_onboarding.header_terms"] = "Termos de serviço",
        ["os_onboarding.welcome_title"] = "Bem-vindo ao AetherOS",
        ["os_onboarding.welcome_body"] = "Este é o seu telefone. Vamos configurá-lo: escolha um visual, um nome e aceite as regras básicas. Leva só um instante.",
        ["os_onboarding.design_title"] = "Escolha um design",
        ["os_onboarding.name_title"] = "Como devemos te chamar?",
        ["os_onboarding.name_body"] = "Este nome é usado em todo o AetherOS. Você pode escolher um nome diferente para cada app depois.",
        ["os_onboarding.name_hint"] = "Nome",
        ["os_onboarding.terms_title"] = "As regras básicas",
        ["os_onboarding.terms_agree"] = "Aceito os Termos de serviço",
        ["os_onboarding.finish"] = "Concluir",
        ["os_onboarding.header_signin"] = "Entrar",
        ["os_onboarding.header_passphrase"] = "Frase-senha",
        ["os_onboarding.tos_1"] = "O AetherOS é um plugin feito por fãs, fornecido como está, sem qualquer garantia. Ele pode falhar, perder dados ou parar de funcionar a qualquer momento, e o uso é por sua conta e risco.",
        ["os_onboarding.tos_2"] = "O AetherOS não é afiliado, endossado ou patrocinado pela Square Enix.",
        ["os_onboarding.tos_3"] = "FINAL FANTASY e FINAL FANTASY XIV são marcas registradas da Square Enix Holdings Co., Ltd. Todas as outras marcas pertencem aos seus respectivos donos.",
        ["os_onboarding.tos_4"] = "Ao continuar, você aceita estes termos.",
        // OS account avatar (added after update 1.5.1)
        ["os_onboarding.header_avatar"] = "Avatar",
        ["os_onboarding.avatar_title"] = "Adicione uma foto",
        ["os_onboarding.avatar_body"] = "Escolha uma imagem para o seu perfil do AetherOS. É opcional e só você a vê; pode mudá-la quando quiser.",
        ["os_onboarding.avatar_choose"] = "Escolher foto",
        ["os_onboarding.avatar_change"] = "Alterar foto",
        // two-onboarding split (added after update 1.5.1)
        ["os_onboarding.header_done"] = "Pronto",
        ["os_onboarding.done_title"] = "Tudo pronto!",
        ["os_onboarding.done_body"] = "Sua conta AetherOS está pronta. Aproveite seu novo telefone!",
        ["os_onboarding.done_start"] = "Começar a usar o plugin",
        ["os_onboarding.design_language"] = "Idioma",
        // combined OS profile step (added after update 1.5.1)
        ["os_onboarding.header_profile"] = "Seu perfil",
        ["os_onboarding.profile_name_label"] = "Seu nome",
        ["os_onboarding.profile_photo_label"] = "Sua foto",
        // home button tooltip (added after update 1.5.1)
        ["os.home"] = "Início",
        ["os.mini_open"] = "Abrir vista completa",
        ["os.mini_power"] = "Desligar o telefone",
        // settings-consolidation categories + reset-home confirm + profile edit (added after update 1.5.1)
        ["os.cat_general"] = "Geral",
        ["os.cat_appearance"] = "Aparência",
        ["os.cat_other"] = "Outros",
        ["os.menu_general"] = "Geral",
        ["os.menu_appearance"] = "Aparência do telemóvel",
        ["os.menu_reset_home"] = "Repor ecrã inicial",
        ["os.reset_home_confirm_title"] = "Repor o ecrã inicial?",
        ["os.reset_home_confirm_body"] = "Isto limpa a tua disposição de ícones e a dock personalizadas, restaurando a disposição predefinida. As tuas apps e definições não são afetadas.",
        ["os.edit_profile"] = "Editar",
        // Daily Eorzean news app (added after update 1.5.1)
        ["os.app_news"] = "O Diário de Eorzea",
        ["os.news_notifications"] = "Notificações de notícias",
        ["os.news_tagline"] = "Est. · Todas as notícias do reino",
        ["os.news_latest"] = "Recente",
        ["os.news_more"] = "Mais notícias",
        ["os.news_edition"] = "Edição · {0}",
        ["os.news_refresh"] = "Atualizar",
        ["os.news_new"] = "Novo",
        // Feedback app (added after update 1.5.1)
        ["os.app_feedback"] = "Comentários",
        ["os.feedback_app_label"] = "Sobre qual aplicativo é?",
        ["os.feedback_general"] = "Geral",
        ["os.feedback_send_another"] = "Enviar mais comentários",
        // generic share system (added after update 1.5.1)
        ["os.share_sheet_title"] = "Compartilhar com",
        // home grid + folders
        ["os.settings_home_screen"] = "Tela inicial",
        ["os.settings_home_grid_caption"] = "Os ícones se reorganizam automaticamente para caber na nova grade.",
        ["os.new_folder"] = "Nova pasta",
        ["os.folder_create"] = "Criar",
        ["os.folder_name_hint"] = "Nome da pasta…",
        ["os.folder_default_name"] = "Pasta",
        ["os.folder_arcade"] = "Arcade",
        ["os.folder_media"] = "Multimédia",
        ["os.folder_empty"] = "Nenhum app ainda. Arraste um ícone para esta pasta para adicioná-lo.",
        // photo filters + screenshot import
        ["os.filter_original"] = "Original",
        ["os.filter_mono"] = "Mono",
        ["os.filter_noir"] = "Noir",
        ["os.filter_sepia"] = "Sépia",
        ["os.filter_retro"] = "Retrô",
        ["os.filter_cool"] = "Frio",
        ["os.filter_vivid"] = "Vívido",
        ["os.filter_fade"] = "Desbotado",
        ["os.filter_applying"] = "Aplicando…",
        ["os.screenshots_album"] = "Capturas",
        // calendar app
        ["os.app_calendar"] = "Calendário",
        ["os.edit_filters"] = "Filtros",
        ["os.edit_adjust"] = "Ajustes",
        ["os.edit_brightness"] = "Brilho",
        ["os.edit_contrast"] = "Contraste",
        ["os.edit_hue"] = "Matiz",
        ["os.edit_tint"] = "Intensidade",
        // guided OS tour
        ["os.settings_tour"] = "Fazer o tour",
        ["os.tour_next"] = "Avançar",
        ["os.tour_back"] = "Voltar",
        ["os.tour_skip"] = "Pular",
        ["os.tour_finish"] = "Pronto",
        ["os.tour_welcome_title"] = "Bem-vindo ao AetherOS",
        ["os.tour_welcome_body"] = "Este é o seu telefone: uma tela inicial cheia de apps, e o AetherLove é só um deles. Vamos dar uma olhada rápida, leva só um minuto.",
        ["os.tour_homebtn_title"] = "Seu botão de início",
        ["os.tour_homebtn_body"] = "Você sempre pode voltar à tela inicial com o botão de início, aquele que está brilhando na parte de baixo do telefone.",
        ["os.tour_pages_title"] = "Sua tela inicial",
        ["os.tour_pages_body"] = "Seus apps ficam aqui, espalhados por páginas. Deslize para os lados para trocar; os pontos mostram onde você está. Levar um ícone até a beirada da tela vira a página junto.",
        ["os.tour_widgets_title"] = "A página de widgets",
        ["os.tour_widgets_body"] = "Acabamos de deslizar até a página de widgets por você. Ela fica à esquerda dos seus apps e mostra o relógio com a hora de Eorzea, o status da conexão e sua notificação mais recente.",
        ["os.tour_statusbar_title"] = "A barra de status",
        ["os.tour_statusbar_body"] = "A faixa destacada lá no topo mostra a hora, a conexão com os servidores do AetherLove, quantas notificações esperam e a bateria. Um ícone vermelho aparece ali se a conexão cair.",
        ["os.tour_shade_title"] = "Notificações",
        ["os.tour_shade_body"] = "Toque no topo do telefone (ou arraste-o para baixo) para ver suas notificações, como fizemos agora. Ali também ficam os atalhos rápidos e o controle de brilho. Toque em uma notificação para abrir, deslize para dispensar.",
        ["os.tour_fake_notif_title"] = "Olá!",
        ["os.tour_fake_notif_body"] = "É assim que uma notificação aparece.",
        ["os.tour_badges_title"] = "Selos",
        ["os.tour_badges_body"] = "Os ícones mostram um contadorzinho quando algo espera por você, como mensagens não lidas ou novos matches. Ele some ao abrir o app. (Calma, você não tem 67 de verdade.)",
        ["os.tour_dock_title"] = "O dock",
        ["os.tour_dock_body"] = "A fileira de baixo fica no lugar em todas as páginas. É onde ficam seus favoritos: arraste um ícone para dentro e ele fica a um toque de distância em qualquer página, e arraste de volta quando mudar de ideia.",
        ["os.tour_folders_title"] = "Pastas",
        ["os.tour_folders_body"] = "Solte um ícone em cima de outro e os dois viram uma pasta. Toque para abrir, renomeie quando quiser e arraste um app para fora do painel para devolvê-lo à tela inicial. Uma pasta vazia some sozinha.",
        ["os.tour_addapps_title"] = "Mais apps",
        ["os.tour_addapps_body"] = "Tudo o que você tirou continua aqui, junto com seus outros plugins do Dalamud, que podem ficar na tela inicial como qualquer outro app.",
        ["os.tour_share_title"] = "Compartilhar",
        ["os.tour_share_body"] = "Você pode compartilhar locais, encontros e muito mais com seus matches e amigos. O compartilhamento funciona entre os diferentes apps: escolha o que compartilhar e para onde vai, e chega como um cartão interativo.",
        ["os.tour_look_title"] = "Aparência",
        ["os.tour_look_body"] = "No app de Configurações destacado você escolhe um tema, troca o papel de parede (ou envia o seu), ajusta o tamanho da grade e até o do próprio telefone.",
        ["os.tour_offline_title"] = "Offline",
        ["os.tour_offline_body"] = "Você pode continuar usando o telefone mesmo quando o AetherLove ou outros apps integrados estiverem indisponíveis. Apps que precisam dos servidores ficam levemente escurecidos com uma marquinha, mas todo o resto continua funcionando normalmente.",
        ["os.tour_arrange_title"] = "Mova as coisas",
        ["os.tour_arrange_body"] = "Os ícones podem ser arrastados a qualquer momento; não há modo de edição para ligar antes. Pegue um, leve para outra célula, outra página ou a fileira de baixo, e solte.",
        ["os.tour_tilemenu_title"] = "Clique com o direito num ícone",
        ["os.tour_tilemenu_body"] = "Todo o resto está a um clique com o direito: colocar numa pasta, tirar de volta, marcar como visto ou tirar da tela inicial. Tirar nunca é definitivo, dá para colocar de volta quando quiser.",
        ["os.tour_homemenu_title"] = "Clique com o direito no papel de parede",
        ["os.tour_homemenu_body"] = "Clique com o direito num espaço livre para o resto: adicionar apps, criar uma pasta, marcar todos os apps novos como vistos de uma vez ou ir trocar o papel de parede.",
        ["os.tour_newapps_title"] = "Apps novos",
        ["os.tour_newapps_body"] = "Quando uma atualização traz apps novos, eles são oferecidos em vez de simplesmente aparecerem: você recebe uma lista, escolhe o que quiser, e o resto fica de lado até você pedir. Um ícone novo carrega uma marquinha até ser aberto uma vez.",
        ["os.tour_done_title"] = "Fim do tour!",
        ["os.tour_done_body"] = "Você pode repeti-lo quando quiser nas Configurações. Agora explore os apps e divirta-se.",
        ["os.photos_search_hint"] = "Buscar por nome ou lugar…",
        ["os.tt_prev"] = "Anterior",
        ["os.tt_next"] = "Próxima",
        ["os.tt_edit"] = "Editar",
        ["os.tt_move"] = "Mover para um álbum",
        ["os.tt_share"] = "Compartilhar",
        ["os.tt_open_folder"] = "Abrir pasta no disco",
        ["os.share_wallpaper"] = "Papel de parede",
        ["os.profile_edit_title"] = "Editar perfil",
        ["os.profile_save"] = "Salvar",
        // home right-click menu (added after update 2.0.0)
        ["os.home_menu_wallpaper"] = "Alterar papel de parede",
        // news app tile rename (added after update 2.0.0)
        ["os.app_news_tile"] = "Notícias",

        // battery easter egg (added after update 2.0.1)
        ["os.battery_grass_body"] = "A tua saúde importa-nos: não te esqueças de sair, hidratar-te e tocar na relva ;-)",
        ["os.battery_grass_hint"] = "Toca na relva abaixo para continuar",
        ["os.settings_hide_battery_grass"] = "Ocultar o aviso da relva quando a bateria acabar",
        // levemetes (added after update 2.0.1)
        ["os.app_levemetes"] = "Levemetes",
        ["os.battery_grass_settings_hint"] = "(Podes desativar esta piada em Geral, na app Definições)",

        // added after update 2.0.1
        ["os.menu_audio"] = "Definições de áudio",
        ["os.app_market"] = "Mercado",
        ["os.app_realtor"] = "Imobiliária",

        // added after update 2.1.3
        ["os.app_wayfinder"] = "Wayfinder",
        ["os.app_yapper"] = "Yapper",
        ["os.arcade_leaderboard"] = "Classificação",
        ["os.arcade_tab_weekly"] = "Esta semana",
        ["os.arcade_tab_alltime"] = "Desde sempre",
        ["os.arcade_loading"] = "A carregar...",
        ["os.arcade_empty"] = "Ainda não há pontuações. Sê o primeiro!",
        ["os.arcade_error"] = "Não foi possível carregar a classificação.",
        ["os.arcade_you"] = "Tu",
        ["os.arcade_back"] = "Voltar",

        // wallet app (added after update 2.2.1)
        ["os.app_wallet"] = "Carteira",

        // plappy birb (added after update 2.2.3)
        ["os.app_plappy"] = "Plappy Birb",

        // removable first-party apps (added after update 2.2.3)
        ["os.add_apps_section_removed"] = "Apps removidos",
        ["os.add_apps_section_plugins"] = "Outros plugins",

        // groove app (added after update 2.2.3)
        ["os.app_groove"] = "Groove",

        // store (added after update 2.2.3)
        ["os.app_store"] = "Loja",
        ["os.store_preview_caption"] = "Só pré-visualização, ainda não é teu",
        ["os.store_preview_close"] = "Fechar a pré-visualização",
        ["os.store_preview_loading"] = "A carregar a pré-visualização…",
        ["os.store_preview_failed"] = "Não foi possível carregar a pré-visualização.",

        // added after update 2.2.3 (echo)
        ["os.app_echo"] = "Echo",
        // player and transport
        ["echo.play"] = "Reproduzir",
        ["echo.pause"] = "Pausa",
        ["echo.mute"] = "Silenciar",
        ["echo.unmute"] = "Ativar som",
        ["echo.skip"] = "Saltar",
        ["echo.skip_tip"] = "Saltar este vídeo para toda a gente",
        ["echo.buffering"] = "A carregar…",
        ["echo.solo_idle"] = "Cola um link para começares a ver",
        ["echo.unavailable"] = "Indisponível",
        ["echo.close"] = "Fechar",
        // playlist
        ["echo.add"] = "Adicionar",
        ["echo.add_hint"] = "Cola um link do YouTube",
        ["echo.added_by"] = "Adicionado por {0}",
        ["echo.added_by_unknown"] = "Adicionado por alguém que já saiu",
        ["echo.remove"] = "Remover",
        ["echo.queue_empty"] = "Ainda não há nada na fila",
        ["echo.playlist_full"] = "A fila está cheia",
        ["echo.bad_link"] = "Isso não é um link do YouTube",
        // room
        ["echo.room_code"] = "Código da sala",
        ["echo.copy_code"] = "Copiar código",
        ["echo.copied"] = "Copiado",
        ["echo.host_only"] = "Só o anfitrião",
        ["echo.host_only_hint"] = "Só o anfitrião controla a reprodução",
        ["echo.host_only_tip"] = "O anfitrião bloqueou os controlos",
        ["echo.kick"] = "Expulsar",
        ["echo.kick_confirm"] = "Remover esta pessoa da sala?",
        ["echo.leave_room"] = "Sair da sala",
        ["echo.end_room"] = "Fechar a sala",
        ["echo.end_room_confirm"] = "Fechar a sala para toda a gente?",
        ["echo.you"] = "{0} (tu)",
        ["echo.tab_playlist"] = "Lista",
        ["echo.tab_members"] = "Membros",
        ["echo.tab_chat"] = "Chat",
        ["echo.toggle_panel"] = "Mostrar ou ocultar o painel lateral",
        ["echo.new_messages"] = "{0} mensagens novas",
        // room ended
        ["echo.room_ended_title"] = "Sala encerrada",
        ["echo.room_ended_owner"] = "O anfitrião fechou a sala",
        ["echo.room_ended_owner_left"] = "O anfitrião perdeu a ligação",
        ["echo.room_ended_empty"] = "Saíram todos",
        ["echo.room_ended_moderation"] = "Esta sala foi fechada pela moderação",
        ["echo.kicked_title"] = "Foste removido da sala",
        ["echo.kicked_body"] = "Foste removido de {0}",
        // runtime and errors
        ["echo.runtime_title"] = "O Echo precisa do seu leitor",
        ["echo.runtime_body"] = "A reprodução de vídeo precisa de um pequeno componente de leitura. É transferido uma única vez e, a partir daí, o Echo fica pronto sempre que o abres.",
        ["echo.runtime_install"] = "Transferir",
        ["echo.installing_title"] = "A preparar o Echo",
        ["echo.install_downloading"] = "A transferir…",
        ["echo.install_verifying"] = "A verificar…",
        ["echo.install_extracting"] = "A extrair…",
        ["echo.install_failed_title"] = "A transferência falhou",
        ["echo.reinstall"] = "Reinstalar",
        ["echo.retry"] = "Tentar de novo",
        ["echo.host_failed_title"] = "O leitor parou",
        ["echo.host_failed_body"] = "Não foi possível reiniciá-lo. Tenta de novo.",
        ["echo.protocol_title"] = "Versão do leitor não coincide",
        ["echo.protocol_body"] = "Reinstala o leitor do Echo para continuar.",
        ["echo.embed_blocked_title"] = "Este vídeo não pode ser incorporado",
        ["echo.embed_blocked_body"] = "O dono não permite a reprodução fora do YouTube.",
        ["echo.video_gone_title"] = "Vídeo indisponível",
        ["echo.video_gone_body"] = "Foi removido ou tornado privado.",
        ["echo.bad_id_title"] = "Link inválido",
        ["echo.bad_id_body"] = "Esse id de vídeo não parece correto.",
        ["echo.player_error_title"] = "A reprodução falhou",
        ["echo.player_error_body"] = "Algo correu mal ao carregar este vídeo.",

        // avatar rings (added after update 2.2.3)
        ["rings.section_title"] = "Anel de avatar",
        ["rings.picker_title"] = "Anel de avatar",
        ["rings.none"] = "Sem anel",
        ["rings.none_owned_title"] = "Ainda sem anéis",
        ["rings.none_owned_body"] = "Os anéis de avatar são molduras decorativas à volta da tua foto, visíveis para todos. Compra-os com Sparks na Store.",
        ["rings.open_store"] = "Abrir a Store",
        ["rings.preview_hint"] = "Todos veem o teu anel onde quer que a tua foto apareça.",

        // aetherling (added after update 2.2.3)
        ["os.app_aetherling"] = "???",

        // added after update 2.3.3
        ["os.app_notes"] = "Notas",
        ["os.app_calculator"] = "Calculadora",
        ["os.folder_utilities"] = "Utilitários",
        ["os.app_timers"] = "Timers",
        ["os.app_racooner"] = "Racooner",
        ["os.app_skyswarm"] = "Sky Swarm",
        ["os.app_eordle"] = "Eordle",

        // echo playback settings (added after update 2.2.3)
        ["echo.settings_tip"] = "Definições de reprodução",
        ["echo.settings_quality"] = "Qualidade do vídeo",
        ["echo.quality_auto"] = "Auto",
        ["echo.quality_720"] = "720p",
        ["echo.quality_1080"] = "1080p",
        ["echo.settings_captions"] = "Legendas",
        ["echo.settings_autoplay"] = "Reproduzir o vídeo seguinte automaticamente",
        ["echo.settings_software_render"] = "Renderização por software",

        // home screen management (added after update 2.3.4)
        ["os.home_menu_add_app"] = "Adicionar app",
        ["os.home_menu_add_folder"] = "Adicionar pasta",
        ["os.tile_menu_remove_app"] = "Remover app",
        ["os.tile_menu_mark_seen"] = "Marcar como visto",
        ["os.home_menu_mark_seen"] = "Marcar todos os apps como vistos",
        ["os.tile_menu_take_out"] = "Tirar da pasta",
        ["os.tile_menu_move_to_folder"] = "Mover para uma pasta",
        ["os.tile_menu_remove_folder"] = "Remover pasta",
        ["os.folder_delete_title"] = "Remover pasta",
        ["os.folder_delete_body"] = "Remover \"{0}\" junto com os {1} apps dentro dela, ou manter os apps e devolvê-los à tela inicial?",
        ["os.folder_delete_remove"] = "Remover pasta e apps",
        ["os.folder_delete_keep"] = "Manter apps",

        // new app offer (added after update 2.3.4)
        ["os.new_apps_title"] = "Novas apps disponíveis",
        ["os.new_apps_body"] = "Esta atualização trouxe apps novas. Escolhe as que queres no ecrã inicial; as restantes podem ser adicionadas depois pelo menu do ecrã inicial.",
        ["os.new_apps_continue"] = "Continuar",
        ["os.app_levemetes_about"] = "Anúncios classificados de Eorzea: publica o que ofereces e vê o que os outros procuram.",
        ["os.app_market_about"] = "Preços do Universalis, histórico de vendas e alertas para os itens que segues.",
        ["os.app_realtor_about"] = "Terrenos livres em todos os mundos, atualizados assim que ficam disponíveis.",
        ["os.app_wayfinder_about"] = "Procura pontos de referência pelo mundo e ganha faíscas por cada descoberta.",
        ["os.app_yapper_about"] = "Publicações curtas e imagens, seguidores, respostas e mensagens privadas.",
        ["os.app_wallet_about"] = "As tuas faíscas e todas as moedas que a tua personagem carrega, com o limite à vista.",
        ["os.app_store_about"] = "Gasta faíscas em temas, anéis de avatar e outras miudezas.",
        ["os.app_groove_about"] = "Um comando para o que o teu PC estiver a tocar, com os volumes do jogo à mão.",
        ["os.app_echo_about"] = "Vejam vídeos juntos, todos ao mesmo segundo.",
        ["os.app_notes_about"] = "Notas e listas que ficam só nesta máquina.",
        ["os.app_calculator_about"] = "Uma calculadora gráfica, teclado e tudo.",
        ["os.app_timers_about"] = "Pesca no alto-mar, o Cactopote e os outros relógios que vale a pena vigiar.",
        ["os.app_aetherling_about"] = "Ninguém diz o que isto é.",
        ["os.app_snake_about"] = "O clássico. Comer, crescer e não se morder.",
        ["os.app_stacker_about"] = "Empilha as peças, limpa as linhas e culpa a última.",
        ["os.app_breaker_about"] = "Faz a bola saltar nos tijolos até não sobrar nenhum.",
        ["os.app_meteor_about"] = "Abate o que cai antes que atinja as tuas cidades.",
        ["os.app_invaders_about"] = "Descem filas de alienígenas. Tens um canhão.",
        ["os.app_muncher_about"] = "Limpa o labirinto, foge dos fantasmas e persegue-os enquanto podes.",
        ["os.app_plappy_about"] = "Toca para bater as asas. Os canos não têm pena nenhuma.",
        ["os.app_doom_about"] = "O jogo de tiros de 1993, a correr dentro do teu telefone.",
        ["os.app_sudoku_about"] = "Nove por nove, uma grelha nova sempre que quiseres.",
        ["os.app_racooner_about"] = "Apanha o que cai e leva-o até às tocas.",
        ["os.app_skyswarm_about"] = "Voa pelo enxame enquanto aguentares.",
        ["os.app_eordle_about"] = "Uma palavra eorzeana por dia, seis tentativas.",
    };
}
