namespace AetherLove.Services.Localization;

internal static class OsEs
{
    public static readonly System.Collections.Generic.Dictionary<string, string> Strings = new()
    {
        // added after update 1.5.1
        // App names
        ["os.app_clock"] = "Reloj",
        ["os.app_snake"] = "Snake",
        ["os.app_doom"] = "DOOM",
        ["os.app_sudoku"] = "Sudoku",
        ["os.app_stacker"] = "Stacker",
        ["os.app_breaker"] = "Breaker",
        ["os.app_meteor"] = "Meteor Command",
        ["os.app_invaders"] = "Void Invaders",
        ["os.app_muncher"] = "Maze Muncher",
        ["os.app_camera"] = "Cámara",

        // Notification shade
        ["os.notifications"] = "Notificaciones",
        ["os.notifications_empty"] = "Sin notificaciones",
        ["os.notifications_clear"] = "Borrar todo",
        ["os.notif_remove"] = "Quitar",
        ["os.time_now"] = "ahora",
        ["os.qt_notifications"] = "Notificaciones",
        ["os.qt_sounds"] = "Sonidos de notificación",
        ["os.qt_lock"] = "Bloquear posición del teléfono",
        ["os.qt_theme"] = "Siguiente tema",
        ["os.qt_wallpaper"] = "Siguiente fondo",

        // Home screen
        ["os.greeting_morning"] = "Buenos días",
        ["os.greeting_afternoon"] = "Buenas tardes",
        ["os.greeting_evening"] = "Buenas noches",
        ["os.greeting_night"] = "¿Sigues en pie?",
        ["os.widget_eorzea"] = "Eorzea",
        ["os.widget_status"] = "Conexión",
        ["os.widget_connected"] = "Conectado",
        ["os.widget_offline"] = "Sin conexión",
        ["os.widget_unread"] = "{0} sin leer",

        // OS settings
        ["os.group_appearance"] = "Apariencia",
        ["os.group_wallpaper"] = "Pantalla de inicio y fondo",
        ["os.group_home"] = "Pantalla de inicio",
        ["os.group_apps"] = "Ajustes de cada app",
        ["os.group_about"] = "Acerca de",
        ["os.wallpaper_gradient"] = "Tema",
        ["os.wallpaper_custom"] = "Tuyo",
        ["os.wallpaper_upload"] = "Subir imagen…",
        ["os.wallpaper_dim"] = "Oscurecer fondo",
        ["os.home_edit_hint"] = "Mantén pulsado un icono en la pantalla de inicio para reordenarlo. Arrastra iconos al dock o entre páginas.",
        ["os.home_reset"] = "Restablecer diseño",

        // Love settings hub after the appearance move
        ["settings.menu_language"] = "Idioma y hora",

        // Weatherman app
        ["os.app_weather"] = "Tiempo",

        // Messenger app
        ["os.app_messenger"] = "Messenger",

        // Photos app
        ["os.app_photos"] = "Fotos",

        // Home screen app launcher
        ["os.add_apps"] = "Añadir apps",
        ["os.add_apps_title"] = "Añadir apps",
        ["os.add_apps_hint"] = "Recupera una app que quitaste o fija otro plugin de Dalamud instalado.",
        ["os.add_apps_none"] = "Ningún otro plugin ofrece una ventana principal.",
        ["os.add_apps_add"] = "Añadir",
        ["os.add_apps_added"] = "Añadida",
        ["os.add_apps_search"] = "Buscar apps...",
        ["os.remove_app_title"] = "Quitar app",
        ["os.remove_app_body"] = "¿Quieres quitar {0} de tu pantalla de inicio?",
        ["os.remove_app_confirm"] = "Quitar",
        // added after update 1.5.1
        ["os_onboarding.header_welcome"] = "Bienvenida",
        ["os_onboarding.header_design"] = "Hazlo tuyo",
        ["os_onboarding.header_name"] = "Tu nombre",
        ["os_onboarding.header_terms"] = "Términos del servicio",
        ["os_onboarding.welcome_title"] = "Bienvenida a AetherOS",
        ["os_onboarding.welcome_body"] = "Este es tu teléfono. Vamos a configurarlo: elige un estilo, un nombre y acepta las normas básicas. Solo lleva un momento.",
        ["os_onboarding.design_title"] = "Elige un diseño",
        ["os_onboarding.name_title"] = "¿Cómo te llamamos?",
        ["os_onboarding.name_body"] = "Este nombre se usa en todo AetherOS. Más adelante puedes elegir un nombre distinto para cada app.",
        ["os_onboarding.name_hint"] = "Nombre",
        ["os_onboarding.terms_title"] = "Las normas básicas",
        ["os_onboarding.terms_agree"] = "Acepto los Términos del servicio",
        ["os_onboarding.finish"] = "Finalizar",
        ["os_onboarding.header_signin"] = "Iniciar sesión",
        ["os_onboarding.header_passphrase"] = "Frase de contraseña",
        ["os_onboarding.tos_1"] = "AetherOS es un plugin hecho por fans, proporcionado tal cual, sin ninguna garantía. Puede fallar, perder datos o dejar de funcionar en cualquier momento, y se usa bajo tu propia responsabilidad.",
        ["os_onboarding.tos_2"] = "AetherOS no está afiliado a Square Enix ni cuenta con su respaldo o patrocinio.",
        ["os_onboarding.tos_3"] = "FINAL FANTASY y FINAL FANTASY XIV son marcas registradas de Square Enix Holdings Co., Ltd. Todas las demás marcas pertenecen a sus respectivos propietarios.",
        ["os_onboarding.tos_4"] = "Al continuar, aceptas estos términos.",
        // OS account avatar (added after update 1.5.1)
        ["os_onboarding.header_avatar"] = "Avatar",
        ["os_onboarding.avatar_title"] = "Añade una foto",
        ["os_onboarding.avatar_body"] = "Elige una imagen para tu perfil de AetherOS. Es opcional y solo tú la ves; puedes cambiarla cuando quieras.",
        ["os_onboarding.avatar_choose"] = "Elegir foto",
        ["os_onboarding.avatar_change"] = "Cambiar foto",
        // two-onboarding split (added after update 1.5.1)
        ["os_onboarding.header_done"] = "Listo",
        ["os_onboarding.done_title"] = "¡Todo listo!",
        ["os_onboarding.done_body"] = "Tu cuenta de AetherOS está lista. ¡Disfruta de tu nuevo teléfono!",
        ["os_onboarding.done_start"] = "Empezar a usar el plugin",
        ["os_onboarding.design_language"] = "Idioma",
        // combined OS profile step (added after update 1.5.1)
        ["os_onboarding.header_profile"] = "Tu perfil",
        ["os_onboarding.profile_name_label"] = "Tu nombre",
        ["os_onboarding.profile_photo_label"] = "Tu foto",
        // home button tooltip (added after update 1.5.1)
        ["os.home"] = "Inicio",
        ["os.mini_open"] = "Abrir vista completa",
        ["os.mini_power"] = "Apagar el teléfono",
        // settings-consolidation categories + reset-home confirm + profile edit (added after update 1.5.1)
        ["os.cat_general"] = "General",
        ["os.cat_appearance"] = "Apariencia",
        ["os.cat_other"] = "Otros",
        ["os.menu_general"] = "General",
        ["os.menu_appearance"] = "Apariencia del teléfono",
        ["os.menu_reset_home"] = "Restablecer pantalla de inicio",
        ["os.reset_home_confirm_title"] = "¿Restablecer la pantalla de inicio?",
        ["os.reset_home_confirm_body"] = "Esto borra tu disposición de iconos y el dock personalizados y restaura la disposición predeterminada. Tus apps y ajustes no se ven afectados.",
        ["os.edit_profile"] = "Editar",
        // Daily Eorzean news app (added after update 1.5.1)
        ["os.app_news"] = "El Diario de Eorzea",
        ["os.news_notifications"] = "Notificaciones de noticias",
        ["os.news_tagline"] = "Est. · Todas las noticias del reino",
        ["os.news_latest"] = "Lo último",
        ["os.news_more"] = "Más noticias",
        ["os.news_edition"] = "Edición · {0}",
        ["os.news_refresh"] = "Actualizar",
        ["os.news_new"] = "Nuevo",
        // Feedback app (added after update 1.5.1)
        ["os.app_feedback"] = "Comentarios",
        ["os.feedback_app_label"] = "¿Sobre qué aplicación es?",
        ["os.feedback_general"] = "General",
        ["os.feedback_send_another"] = "Enviar más comentarios",
        // generic share system (added after update 1.5.1)
        ["os.share_sheet_title"] = "Compartir con",
        // home grid + folders
        ["os.settings_home_screen"] = "Pantalla de inicio",
        ["os.settings_home_grid_caption"] = "Los iconos se reorganizan automáticamente para ajustarse a la nueva cuadrícula.",
        ["os.new_folder"] = "Nueva carpeta",
        ["os.folder_create"] = "Crear",
        ["os.folder_name_hint"] = "Nombre de la carpeta…",
        ["os.folder_default_name"] = "Carpeta",
        ["os.folder_arcade"] = "Arcade",
        ["os.folder_media"] = "Multimedia",
        ["os.folder_empty"] = "Aún no hay apps. Arrastra un icono sobre esta carpeta para añadirlo.",
        // photo filters + screenshot import
        ["os.filter_original"] = "Original",
        ["os.filter_mono"] = "Mono",
        ["os.filter_noir"] = "Noir",
        ["os.filter_sepia"] = "Sepia",
        ["os.filter_retro"] = "Retro",
        ["os.filter_cool"] = "Frío",
        ["os.filter_vivid"] = "Vívido",
        ["os.filter_fade"] = "Desvaído",
        ["os.filter_applying"] = "Aplicando…",
        ["os.screenshots_album"] = "Capturas",
        // calendar app
        ["os.app_calendar"] = "Calendario",
        ["os.edit_filters"] = "Filtros",
        ["os.edit_adjust"] = "Ajustes",
        ["os.edit_brightness"] = "Brillo",
        ["os.edit_contrast"] = "Contraste",
        ["os.edit_hue"] = "Tono",
        ["os.edit_tint"] = "Intensidad",
        // guided OS tour
        ["os.settings_tour"] = "Hacer el recorrido",
        ["os.tour_next"] = "Siguiente",
        ["os.tour_back"] = "Atrás",
        ["os.tour_skip"] = "Omitir",
        ["os.tour_finish"] = "Listo",
        ["os.tour_welcome_title"] = "Bienvenido a AetherOS",
        ["os.tour_welcome_body"] = "Este es tu teléfono: una pantalla de inicio llena de apps, y AetherLove es solo una de ellas. Demos una vuelta rápida, solo toma un minuto.",
        ["os.tour_homebtn_title"] = "Tu botón de inicio",
        ["os.tour_homebtn_body"] = "Siempre puedes volver a la pantalla de inicio con el botón de inicio, el que brilla en la parte de abajo del teléfono.",
        ["os.tour_pages_title"] = "Tu pantalla de inicio",
        ["os.tour_pages_body"] = "Aquí viven tus apps, repartidas en páginas. Desliza a izquierda y derecha para pasar de una a otra. Los puntos indican en qué página estás. Arrastra un icono hasta el borde de la pantalla. La página cambia y el icono se va con ella.",
        ["os.tour_widgets_title"] = "La página de widgets",
        ["os.tour_widgets_body"] = "Acabamos de deslizarnos a la página de widgets por ti. Está a la izquierda de tus apps. Muestra el reloj con la hora de Eorzea, el estado de la conexión y tu última notificación. Puedes mantener pulsada una tarjeta y arrastrarla hacia arriba o hacia abajo.",
        ["os.tour_statusbar_title"] = "La barra de estado",
        ["os.tour_statusbar_body"] = "La franja resaltada de arriba del todo muestra la hora, la batería y tu conexión con los servidores de AetherLove. También muestra cuántas notificaciones están esperando. Si se pierde la conexión, ahí aparece un icono rojo de aviso.",
        ["os.tour_shade_title"] = "Notificaciones",
        ["os.tour_shade_body"] = "Toca la parte de arriba del teléfono (o arrástrala hacia abajo) para ver tus notificaciones, como acabamos de hacer. Ahí también tienes ajustes rápidos y un control de brillo. Toca una notificación para abrirla o deslízala para descartarla.",
        ["os.tour_fake_notif_title"] = "¡Hola!",
        ["os.tour_fake_notif_body"] = "Así es como se ve una notificación.",
        ["os.tour_badges_title"] = "Insignias",
        ["os.tour_badges_body"] = "Los iconos muestran un pequeño contador cuando algo te espera, como mensajes sin leer o nuevos matches. Se borra al abrir la app. (Tranquilo, no tienes 67 de verdad.)",
        ["os.tour_dock_title"] = "El dock",
        ["os.tour_dock_body"] = "La fila de abajo se mantiene en todas las páginas. Ahí van tus apps favoritas. Arrastra un icono dentro para tenerlo a un toque. Sácalo de nuevo cuando cambies de idea.",
        ["os.tour_folders_title"] = "Carpetas",
        ["os.tour_folders_body"] = "Suelta un icono encima de otro y se convierten en una carpeta. Toca la carpeta para abrirla. Cámbiale el nombre cuando quieras. Arrastra una app fuera de la carpeta para devolverla a la pantalla de inicio. Una carpeta vacía desaparece sola.",
        ["os.tour_addapps_title"] = "Más apps",
        ["os.tour_addapps_body"] = "Todas las apps que has quitado siguen aquí. Tus otros plugins de Dalamud también están aquí. Pueden estar en la pantalla de inicio como cualquier otra app.",
        ["os.tour_share_title"] = "Compartir",
        ["os.tour_share_body"] = "Puedes compartir locales, quedadas y mucho más con tus matches y amigos. Compartir funciona de una app a otra. Elige qué compartir y luego a dónde va. Llega como una tarjeta que puedes tocar.",
        ["os.tour_look_title"] = "Apariencia y diseño",
        ["os.tour_look_body"] = "La app de Ajustes resaltada es donde cambias el aspecto del teléfono. Puedes elegir un tema, cambiar el fondo o subir el tuyo. También puedes cambiar el tamaño de la cuadrícula y del propio teléfono.",
        ["os.tour_offline_title"] = "Sin conexión",
        ["os.tour_offline_body"] = "Puedes seguir usando el teléfono aunque AetherLove o alguna de sus apps esté sin conexión. Una app que necesita los servidores se ve atenuada y muestra una pequeña marca. Las demás apps siguen funcionando.",
        ["os.tour_arrange_title"] = "Mueve lo que quieras",
        ["os.tour_arrange_body"] = "Puedes arrastrar un icono en cualquier momento. No hay ningún modo de edición que activar antes. Coge uno, llévalo a un sitio nuevo y suéltalo. Ese sitio puede estar en cualquier página o en la fila de abajo.",
        ["os.tour_tilemenu_title"] = "Clic derecho en un icono",
        ["os.tour_tilemenu_body"] = "Lo demás está a un clic derecho: meterlo en una carpeta, sacarlo, marcarlo como visto o quitarlo de la pantalla de inicio. Quitar nunca es definitivo, siempre puedes devolverlo.",
        ["os.tour_homemenu_title"] = "Clic derecho en el fondo",
        ["os.tour_homemenu_body"] = "Clic derecho en cualquier hueco libre para el resto: añadir apps, crear una carpeta, marcar de golpe todas las apps nuevas como vistas o ir a cambiar el fondo.",
        ["os.tour_newapps_title"] = "Apps nuevas",
        ["os.tour_newapps_body"] = "Cuando una actualización trae apps nuevas, recibes una lista. Eliges las que quieras. Las apps que dejas fuera no llegan a la pantalla de inicio hasta que las pidas. Un icono nuevo lleva una pequeña etiqueta roja que pone \"new\" hasta que lo abres una vez.",
        ["os.tour_done_title"] = "¡Fin del recorrido!",
        ["os.tour_done_body"] = "Puedes repetirlo cuando quieras desde Ajustes. Ahora explora las apps y pásalo bien.",
        ["os.photos_search_hint"] = "Buscar por nombre o lugar…",
        ["os.tt_prev"] = "Anterior",
        ["os.tt_next"] = "Siguiente",
        ["os.tt_edit"] = "Editar",
        ["os.tt_move"] = "Mover a un álbum",
        ["os.tt_share"] = "Compartir",
        ["os.tt_open_folder"] = "Abrir carpeta en el disco",
        ["os.share_wallpaper"] = "Fondo de pantalla",
        ["os.profile_edit_title"] = "Editar perfil",
        ["os.profile_save"] = "Guardar",
        // home right-click menu (added after update 2.0.0)
        ["os.home_menu_lock_icons"] = "Bloquear iconos",
        ["os.home_menu_unlock_icons"] = "Desbloquear iconos",
        ["os.home_menu_wallpaper"] = "Cambiar fondo",
        // news app tile rename (added after update 2.0.0)
        ["os.app_news_tile"] = "Noticias",

        // battery easter egg (added after update 2.0.1)
        ["os.battery_grass_body"] = "Nos importa tu salud: no olvides salir, hidratarte y tocar un poco de hierba ;-)",
        ["os.battery_grass_hint"] = "Toca la hierba de abajo para continuar",
        ["os.settings_hide_battery_grass"] = "Ocultar el aviso de tocar hierba cuando se agote la batería",
        // levemetes (added after update 2.0.1)
        ["os.app_levemetes"] = "Levemetes",
        ["os.battery_grass_settings_hint"] = "(Puedes desactivar esta broma en General, dentro de la app de Ajustes)",

        // added after update 2.0.1
        ["os.menu_audio"] = "Ajustes de audio",
        ["os.app_market"] = "Mercado",
        ["os.app_realtor"] = "Inmobiliaria",

        // added after update 2.1.3
        ["os.app_wayfinder"] = "Wayfinder",
        ["os.app_yapper"] = "Yapper",
        ["os.arcade_leaderboard"] = "Clasificación",
        ["os.arcade_tab_weekly"] = "Esta semana",
        ["os.arcade_tab_alltime"] = "Histórico",
        ["os.arcade_loading"] = "Cargando...",
        ["os.arcade_empty"] = "Aún no hay puntuaciones. ¡Sé el primero!",
        ["os.arcade_error"] = "No se pudo cargar la clasificación.",
        ["os.arcade_you"] = "Tú",
        ["os.arcade_back"] = "Volver",

        // wallet app (added after update 2.2.1)
        ["os.app_wallet"] = "Cartera",

        // plappy birb (added after update 2.2.3)
        ["os.app_plappy"] = "Plappy Birb",

        // removable first-party apps (added after update 2.2.3)
        ["os.add_apps_section_removed"] = "Apps quitadas",
        ["os.add_apps_section_plugins"] = "Otros plugins",

        // groove app (added after update 2.2.3)
        ["os.app_groove"] = "Groove",

        // store (added after update 2.2.3)
        ["os.app_store"] = "Tienda",
        ["os.store_preview_caption"] = "Solo vista previa, aún no es tuyo",
        ["os.store_preview_close"] = "Cerrar la vista previa",
        ["os.store_preview_loading"] = "Cargando la vista previa…",
        ["os.store_preview_failed"] = "No se pudo cargar la vista previa.",

        // added after update 2.2.3 (echo)
        ["os.app_echo"] = "Echo",
        // player and transport
        ["echo.play"] = "Reproducir",
        ["echo.pause"] = "Pausa",
        ["echo.mute"] = "Silenciar",
        ["echo.unmute"] = "Activar sonido",
        ["echo.skip"] = "Saltar",
        ["echo.skip_tip"] = "Saltar este vídeo para todos",
        ["echo.buffering"] = "Cargando…",
        ["echo.solo_idle"] = "Pega un enlace para empezar a ver",
        ["echo.unavailable"] = "No disponible",
        ["echo.close"] = "Cerrar",
        // playlist
        ["echo.add"] = "Añadir",
        ["echo.add_hint"] = "Pega un enlace de YouTube o Twitch",
        ["echo.added_by"] = "Añadido por {0}",
        ["echo.added_by_unknown"] = "Añadido por alguien que ya se fue",
        ["echo.remove"] = "Quitar",
        ["echo.queue_empty"] = "Aún no hay nada en la cola",
        ["echo.playlist_full"] = "La cola está llena",
        ["echo.bad_link"] = "Eso no es un enlace de YouTube",
        // room
        ["echo.room_code"] = "Código de la sala",
        ["echo.copy_code"] = "Copiar código",
        ["echo.copied"] = "Copiado",
        ["echo.host_only"] = "Solo el anfitrión",
        ["echo.host_only_hint"] = "Solo el anfitrión controla la reproducción",
        ["echo.host_only_tip"] = "El anfitrión ha bloqueado los controles",
        ["echo.kick"] = "Expulsar",
        ["echo.kick_confirm"] = "¿Sacar a esta persona de la sala?",
        ["echo.leave_room"] = "Salir de la sala",
        ["echo.end_room"] = "Cerrar la sala",
        ["echo.end_room_confirm"] = "¿Cerrar la sala para todos?",
        ["echo.you"] = "{0} (tú)",
        ["echo.tab_playlist"] = "Lista",
        ["echo.tab_members"] = "Miembros",
        ["echo.tab_chat"] = "Chat",
        ["echo.toggle_panel"] = "Mostrar u ocultar el panel lateral",
        ["echo.new_messages"] = "{0} mensajes nuevos",
        // room ended
        ["echo.room_ended_title"] = "Sala cerrada",
        ["echo.room_ended_owner"] = "El anfitrión cerró la sala",
        ["echo.room_ended_owner_left"] = "El anfitrión se desconectó",
        ["echo.room_ended_empty"] = "Se fue todo el mundo",
        ["echo.room_ended_moderation"] = "La moderación cerró esta sala",
        ["echo.kicked_title"] = "Te han sacado de la sala",
        ["echo.kicked_body"] = "Te han sacado de {0}",
        // runtime and errors
        ["echo.runtime_title"] = "Echo necesita su reproductor",
        ["echo.runtime_body"] = "Para ver vídeo hace falta un pequeño componente de reproducción. Se descarga una sola vez y, a partir de ahí, Echo está listo cada vez que lo abras.",
        ["echo.runtime_install"] = "Descargarlo",
        ["echo.installing_title"] = "Preparando Echo",
        ["echo.install_downloading"] = "Descargando…",
        ["echo.install_verifying"] = "Verificando…",
        ["echo.install_extracting"] = "Extrayendo…",
        ["echo.install_failed_title"] = "Falló la descarga",
        ["echo.reinstall"] = "Reinstalar",
        ["echo.retry"] = "Reintentar",
        ["echo.host_failed_title"] = "El reproductor se detuvo",
        ["echo.host_failed_body"] = "No se pudo reiniciar. Inténtalo de nuevo.",
        ["echo.protocol_title"] = "La versión del reproductor no coincide",
        ["echo.protocol_body"] = "Reinstala el reproductor de Echo para continuar.",
        ["echo.embed_blocked_title"] = "Este vídeo no se puede incrustar",
        ["echo.embed_blocked_body"] = "Su propietario no permite la reproducción fuera de YouTube.",
        ["echo.video_gone_title"] = "Vídeo no disponible",
        ["echo.video_gone_body"] = "Se eliminó o se hizo privado.",
        ["echo.bad_id_title"] = "Enlace incorrecto",
        ["echo.bad_id_body"] = "Ese id de vídeo no tiene buena pinta.",
        ["echo.player_error_title"] = "Fallo en la reproducción",
        ["echo.player_error_body"] = "Algo salió mal al cargar este vídeo.",

        // avatar rings (added after update 2.2.3)
        ["rings.section_title"] = "Anillo de avatar",
        ["rings.picker_title"] = "Anillo de avatar",
        ["rings.none"] = "Sin anillo",
        ["rings.none_owned_title"] = "Aún no tienes anillos",
        ["rings.none_owned_body"] = "Los anillos de avatar son marcos decorativos alrededor de tu foto, visibles para todos. Cómpralos con Sparks en la Store.",
        ["rings.open_store"] = "Abrir la Store",
        ["rings.preview_hint"] = "Todos ven tu anillo allí donde aparece tu foto.",

        // aetherling (added after update 2.2.3)
        ["os.app_aetherling"] = "Aetherling",

        // added after update 2.3.3
        ["os.app_notes"] = "Notas",
        ["os.app_together"] = "AetherParty",
        ["os.app_calculator"] = "Calculadora",
        ["os.folder_utilities"] = "Utilidades",
        ["os.app_timers"] = "Temporizadores",
        ["os.app_racooner"] = "Racooner",
        ["os.app_skyswarm"] = "Sky Swarm",
        ["os.app_eordle"] = "Eordle",
        ["os.app_racer"] = "Lumi Racer",

        // echo playback settings (added after update 2.2.3)
        ["echo.settings_tip"] = "Ajustes de reproducción",
        ["echo.settings_quality"] = "Calidad de vídeo",
        ["echo.quality_auto"] = "Auto",
        ["echo.quality_720"] = "720p",
        ["echo.quality_1080"] = "1080p",
        ["echo.settings_captions"] = "Subtítulos",
        ["echo.settings_autoplay"] = "Reproducir el siguiente vídeo automáticamente",
        ["echo.settings_software_render"] = "Renderizado por software",

        // home screen management (added after update 2.3.4)
        ["os.home_menu_add_app"] = "Añadir app",
        ["os.home_menu_add_folder"] = "Añadir carpeta",
        ["os.tile_menu_remove_app"] = "Quitar app",
        ["os.tile_menu_mark_seen"] = "Marcar como visto",
        ["os.home_menu_mark_seen"] = "Marcar todas las apps como vistas",
        ["os.tile_menu_take_out"] = "Sacar de la carpeta",
        ["os.tile_menu_move_to_folder"] = "Mover a una carpeta",
        ["os.tile_menu_remove_folder"] = "Quitar carpeta",
        ["os.folder_delete_title"] = "Quitar carpeta",
        ["os.folder_delete_body"] = "¿Quitar \"{0}\" con las {1} apps que tiene dentro, o conservarlas y devolverlas a la pantalla de inicio?",
        ["os.folder_delete_remove"] = "Quitar carpeta y apps",
        ["os.folder_delete_keep"] = "Conservar apps",

        // new app offer (added after update 2.3.4)
        ["os.new_apps_title"] = "Nuevas apps disponibles",
        ["os.new_apps_body"] = "Esta actualización trae apps nuevas. Elige cuáles quieres en tu pantalla de inicio. Las demás puedes añadirlas luego desde el menú de la pantalla de inicio.",
        ["os.new_apps_continue"] = "Continuar",
        ["os.app_levemetes_about"] = "Anuncios clasificados de Eorzea: publica lo que ofreces y mira lo que buscan los demás.",
        ["os.app_market_about"] = "Precios de Universalis, historial de ventas y alertas de los objetos que vigilas.",
        ["os.app_realtor_about"] = "Parcelas libres en todos los mundos, actualizadas en cuanto quedan disponibles.",
        ["os.app_wayfinder_about"] = "Encuentra puntos de referencia por el mundo y gana chispas por hallarlos.",
        ["os.app_yapper_about"] = "Publicaciones cortas e imágenes, seguidores, respuestas y mensajes privados.",
        ["os.app_wallet_about"] = "Tus chispas y todas las monedas que lleva tu personaje, con su límite a la vista.",
        ["os.app_store_about"] = "Gasta chispas en temas, anillos de avatar y otros caprichos.",
        ["os.app_groove_about"] = "Un mando para lo que suene en tu PC, con los controles de volumen del juego incluidos.",
        ["os.app_echo_about"] = "Ved vídeos juntos y sincronizados con tus amistades.",
        ["os.app_notes_about"] = "Notas y listas que se quedan en este equipo y en ningún otro sitio.",
        ["os.app_together_about"] = "Crea un grupo o únete a uno, invita a amigos y gana más sparks jugando juntos.",
        ["os.app_calculator_about"] = "Una calculadora gráfica, con su teclado y todo.",
        ["os.app_timers_about"] = "Pesca de altura, la Lotocactus y los demás relojes que conviene mirar.",
        ["os.app_aetherling_about"] = "Sintoniza un Aethercore y cría lo que salga de él.",
        ["os.app_snake_about"] = "La de siempre. Come, crece y no te muerdas.",
        ["os.app_stacker_about"] = "Apila las piezas, limpia las líneas y échale la culpa a la última.",
        ["os.app_breaker_about"] = "Rebota la bola contra los ladrillos hasta que no quede ninguno.",
        ["os.app_meteor_about"] = "Derriba lo que cae antes de que alcance tus ciudades.",
        ["os.app_invaders_about"] = "Bajan filas de alienígenas. Tú tienes un cañón.",
        ["os.app_muncher_about"] = "Vacía el laberinto, esquiva a los fantasmas y persíguelos cuando puedas.",
        ["os.app_plappy_about"] = "Toca para aletear. Las tuberías no perdonan.",
        ["os.app_doom_about"] = "El shooter de 1993, funcionando dentro de tu móvil.",
        ["os.app_sudoku_about"] = "Nueve por nueve, una cuadrícula nueva cuando te apetezca.",
        ["os.app_racooner_about"] = "Atrapa lo que cae y llévalo a las madrigueras.",
        ["os.app_skyswarm_about"] = "Vuela entre el enjambre todo lo que aguantes.",
        ["os.app_eordle_about"] = "Una palabra eorzea al día, seis intentos.",
        ["os.app_racer_about"] = "Apunta a tu Lumi a carreras y gana sparks y premios.",

        // together mode (added after update 2.4.0)
        ["os.party_title"] = "AetherParty",
        ["os.party_members"] = "{0}/{1}",
        ["os.party_start"] = "Crear grupo",
        ["os.party_join"] = "Unirse",
        ["os.party_join_hint"] = "Código del grupo",
        ["os.party_code"] = "Código {0}",
        ["os.party_copied"] = "¡Copiado!",
        ["os.party_leave"] = "Salir del grupo",
        ["os.party_end"] = "Cerrar el grupo",
        ["os.party_ended"] = "El grupo ha terminado.",
        ["os.party_dismiss"] = "Vale",
        ["os.party_invite"] = "Invitar",
        ["os.party_error_full"] = "Ese grupo está lleno.",
        ["os.party_error_kicked"] = "Te expulsaron de ese grupo.",
        ["os.party_error_in_party"] = "Ya estás en un grupo.",
        ["os.party_error_not_found"] = "No hay ningún grupo con ese código.",
        ["os.party_error_generic"] = "No ha funcionado. Inténtalo de nuevo.",
        ["os.party_invite_message"] = "¡{0} te invita a un grupo! Abre la página de widgets del teléfono y únete con el código {1}.",
        ["os.party_activity_echo"] = "Watch party en curso",
        ["os.party_activity_wayfinder"] = "Cacería en grupo en curso",
        ["os.party_activity_racer"] = "Carrera de Lumis en curso",
        ["os.party_activity_generic"] = "Actividad en curso",
        ["os.party_activity_open"] = "Abrir",
        ["os.party_chat_title"] = "Chat del grupo",
        ["os.party_chat_hint"] = "Escribe a tu grupo...",
        ["os.party_chat_empty"] = "Aún no hay mensajes. ¡Saluda!",
        // message translation (added after update 2.4.0)
        ["os.translate"] = "Traducir",
        ["os.translate_retry"] = "Traducir de nuevo",
        ["os.translate_pending"] = "Traduciendo...",
        ["os.translate_show_original"] = "Mostrar original",
        ["os.translate_settings"] = "Ajustes de traducción",
        ["os.translate_consent_title"] = "¿Traducir mensajes?",
        ["os.translate_consent_body"] = "Las traducciones vienen de Google Translate. El texto que traduces se envía por internet a Google, un tercero. No se envía nada más. No se traduce nada si no lo pides.",
        ["os.translate_consent_enable"] = "Activar traducciones",
        ["os.translate_consent_cancel"] = "Ahora no",
        // translation onboarding + offer (added after update 2.4.0)
        ["os.translate_demo_source"] = "Bonjour ! On part explorer ensemble ?",
        ["os.translate_demo_result"] = "¡Hola! ¿Vamos a explorar juntos?",
        ["os.translate_offer_title"] = "Traduce cualquier mensaje",
        ["os.translate_offer_body"] = "Esta actualización añade traducciones. Haz clic derecho en cualquier mensaje, bio de perfil o publicación y elige Traducir.",
        ["os.translate_offer_enable_go"] = "Activar y continuar",
        ["os.translate_offer_skip_go"] = "Continuar sin traducciones",
        ["os_onboarding.translate_title"] = "Entiende a todo el mundo",
        ["os_onboarding.translate_body"] = "Puedes traducir chats, perfiles y publicaciones a tu idioma. Haz clic derecho en cualquier texto y elige Traducir.",
        ["os_onboarding.translate_later"] = "Todo esto se puede cambiar luego en Ajustes, en la sección de idiomas.",

        // together onboarding (added after update 2.4.0)
        ["os.party_intro_title_0"] = "Hacer cosas juntos",
        ["os.party_intro_body_0"] = "Un grupo te reúne con hasta tres amigos en la misma pantalla. Comparte el código y ellos entran. Cuando uno de vosotros empieza una fiesta de visionado o una cacería de Wayfinder, los demás pueden unirse.",
        ["os.party_intro_title_1"] = "Chatear juntos",
        ["os.party_intro_body_1"] = "El chat del grupo está en una barra pequeña junto al teléfono. Los mensajes nuevos aparecen ahí sin que abras nada.",
        ["os.party_intro_title_2"] = "Trae a tu Aetherling",
        ["os.party_intro_body_2"] = "El modo grupo te deja compartir tu Aetherling y ver los Aetherlings de tu grupo. Todo es opcional.",
        ["os.party_intro_pets_show"] = "Mostrar los Aetherlings de los miembros del grupo",
        ["os.party_intro_pets_share"] = "Permitir que el grupo vea el mío",
        ["os.party_intro_pets_size"] = "¿De qué tamaño los quieres?",
        ["os.party_intro_f0_code"] = "Un código invita a todos: compártelo y entran.",
        ["os.party_intro_f0_activity"] = "Cuando uno de vosotros empieza una fiesta de visionado o una cacería de Wayfinder, los demás pueden unirse.",
        ["os.party_intro_f0_size"] = "Hasta cuatro a la vez.",
        ["os.party_intro_f1_widget"] = "Gestiona el grupo desde su tarjeta en la página de widgets del teléfono.",
        ["os.party_intro_f1_dock"] = "Los miembros se colocan junto al teléfono: ves de un vistazo quién anda cerca.",
        ["os.party_intro_f1_chat"] = "Chatea con tus amigos aunque estén en otros servidores o centros de datos.",
        ["os.party_intro_pets_show_hint"] = "Sus Aetherlings se reúnen alrededor del tuyo en la pantalla.",
        ["os.party_intro_pets_share_hint"] = "Los miembros de tus grupos ven tu Aetherling junto al suyo.",
        ["os.party_in_party"] = "Ahora mismo en un grupo · {0}",
        ["os.party_intro_next"] = "Sigue",
        ["os.party_intro_start"] = "Empezar",
        ["os.party_pet_size_0"] = "XS",
        ["os.party_pet_size_1"] = "S",
        ["os.party_pet_size_2"] = "M",
        ["os.party_pet_size_3"] = "L",
        ["os.party_pet_size_4"] = "XL",

        // widget page (added after update 2.4.0)
        ["os.widget_add_new"] = "Añadir un widget",
        ["os.widget_settings"] = "Ajustes del widget",
        ["os.widget_remove"] = "Quitar este widget",
        ["os.widget_clock"] = "Reloj",
        ["os.widget_status"] = "Estado",
        ["os.widget_notifications"] = "Notificaciones",
        ["os.widget_party"] = "AetherParty",

        // screenshot import consent (added after update 2.4.0)
        ["os.photos_screenshots_offer"] = "¿Añadir tus capturas del juego a Fotos? Toca aquí para decidir.",
        ["os.party_settings"] = "Ajustes de AetherParty",
        ["os.party_kick_tip"] = "Sacar a {0} del grupo",
        ["os.party_kick_title"] = "¿Sacar del grupo?",
        ["os.party_kick_body"] = "{0} saldrá del grupo y no podrá volver a entrar en este.",
        ["os.party_kick_go"] = "Sacar",
        ["os.party_chat_joined"] = "{0} se unió al grupo",
        ["os.party_chat_wayfinder"] = "{0} empezó una búsqueda de Wayfinder. Toca para unirte.",
        ["os.party_chat_racer"] = "{0} inició una carrera de Lumis. Toca para unirte.",
        ["os.party_chat_echo"] = "{0} abrió una sala de Echo. Toca para entrar.",

        // listing boosts (added after update 2.5.2)
        ["os.boost_boosted"] = "Impulsado",
        ["os.boost_featured"] = "Destacados",
        ["os.boost_left"] = "Impulsado, queda {0}",
        ["os.boost_left_count"] = "Te quedan {0}.",
        ["os.boost_none"] = "No tienes impulsos. Consigue uno en la Tienda.",
        ["os.boost_go"] = "Impulsar",
        ["os.boost_confirm_venue"] = "¿Impulsar este local?",
        ["os.boost_confirm_ad"] = "¿Impulsar este anuncio?",
        ["os.boost_confirm_body"] = "Sube arriba del todo en la lista durante 5 días. Elige el efecto que lleva.",
        ["os.boost_confirm_extend"] = "Le queda {0} de impulso. Esto suma 5 días más. Elige el efecto que lleva.",
        ["os.boost_style_0"] = "Aurora",
        ["os.boost_style_1"] = "Ascua",
        ["os.boost_style_2"] = "Prisma",
        ["os.boost_style_3"] = "Luz estelar",
        ["os.boost_venue_action"] = "Impulsar este local",
        ["os.boost_ad_action"] = "Impulsar este anuncio",
        ["os.boost_get"] = "Consigue un impulso",
        ["os.boost_shelf"] = "Tus impulsos",
        ["os.boost_pick"] = "Elige qué impulsar",
        ["os.boost_no_targets"] = "Todavía no tienes ningún local ni anuncio activo que impulsar.",
        ["os.boost_done"] = "Impulsado durante {0}.",
        ["os.boost_venues"] = "Locales",
        ["os.boost_ads"] = "Anuncios",

        // echo playlist import (added after update 2.5.3)
        ["echo.playlist_confirm"] = "¿Añadir los {0} vídeos de esta lista?",
        ["echo.playlist_capped"] = "Esta lista tiene {0} vídeos. ¿Añadir los primeros {1}?",
        ["echo.playlist_add_all"] = "Añadir todos",
        ["echo.playlist_add_one"] = "Solo este vídeo",
        ["echo.playlist_reading"] = "Leyendo la lista...",
        ["echo.playlist_failed"] = "Echo no pudo leer esa lista. Prueba con el enlace del vídeo.",
        ["echo.playlist_added"] = "Se añadieron {0} vídeos.",
        ["os.echo_home_watch_playlist"] = "Las listas solo funcionan en una sala. Crea o entra en una sala primero.",

        // phone shell menu (added after update 2.5.3)
        ["os.phone_menu_exit"] = "Apagar el teléfono",
        ["os.phone_menu_minimize"] = "Minimizar el teléfono",
        ["os.phone_menu_open"] = "Abrir el teléfono",
        ["os.phone_menu_lock"] = "Bloquear la posición",
        ["os.phone_menu_unlock"] = "Desbloquear la posición",
        // echo live streams (added after update 2.5.3)
        ["echo.live"] = "EN VIVO",
        ["echo.live_needs_player_title"] = "Las emisiones en vivo necesitan un reproductor más nuevo",
        ["echo.live_needs_player_body"] = "Este reproductor no puede reproducir emisiones en vivo. Los vídeos normales siguen funcionando.",
        ["echo.live_needs_player_update"] = "Hay un reproductor más nuevo. Instálalo para ver emisiones en vivo.",
        // added after update 2.6.0 (echo minimize)
        ["echo.minimize"] = "Minimizar",
        ["echo.restore"] = "Abrir Echo",
    };
}
