namespace AetherLove.Services.Localization;

internal static class ChatEs
{
    public static readonly System.Collections.Generic.Dictionary<string, string> Strings = new()
    {
        ["chat.no_conversation_selected"] = "No hay ninguna conversación seleccionada.",
        ["chat.unreadable_message"] = "[mensaje ilegible]",
        ["chat.report_submitted_toast"] = "Denuncia enviada. Nuestro equipo de moderación la revisará.",
        ["chat.view_profile"] = "Ver perfil",
        ["chat.back_to_matches"] = "Volver a las coincidencias",
        ["chat.menu_open_profile"] = "Abrir perfil",
        ["chat.menu_copy_message"] = "Copiar mensaje",
        ["chat.menu_pin"] = "Fijar chat",
        ["chat.menu_unpin"] = "Dejar de fijar chat",
        ["chat.menu_unmatch"] = "Deshacer coincidencia",
        ["chat.menu_block"] = "Bloquear",
        ["chat.menu_report_user"] = "Denunciar usuario",
        ["chat.unmatch_title"] = "Deshacer coincidencia",
        ["chat.unmatch_body"] = "Cuando deshaces la coincidencia con este jugador, el chat quedará oculto para ambas personas. Si volvéis a coincidir más adelante, vuestro historial reaparecerá.",
        ["chat.unmatch_confirm"] = "Deshacer coincidencia",
        ["chat.block_title"] = "Bloquear usuario",
        ["chat.block_body"] = "Cuando bloqueas a un usuario, el chat quedará oculto para ambas personas y no volverá a aparecer en tus coincidencias en el futuro.",
        ["chat.block_confirm"] = "Bloquear",
        ["chat.cancel"] = "Cancelar",
        ["chat.loading_messages"] = "Cargando mensajes…",
        ["chat.e2e_self_broken"] = "Algo va mal con tu configuración E2E, ponte en contacto con el soporte.",
        ["chat.seen_suffix"] = " · visto",
        ["chat.send"] = "Enviar",
        ["chat.emoji_button"] = ":)",
        ["chat.system_notice_line1"] = "Este es un chat privado entre tú y {0}. Este chat está cifrado de extremo a extremo, el equipo de AetherLove no puede leer tus mensajes. Arriba a la derecha encontrarás un menú para deshacer la coincidencia, bloquear o denunciar a tu coincidencia.",
        ["chat.system_notice_line2"] = "Recuerda: {0} no conoce tu nombre completo ni tu ubicación hasta que se los compartas. Cuida tu propia privacidad y comparte más solo si te sientes preparado.",
        ["chat.i_understand"] = "Entiendo",
        ["chat.report_title"] = "Denunciar usuario",
        ["chat.report_reason_prompt"] = "Por favor, describe el motivo de tu denuncia:",
        ["chat.report_agree"] = "Acepto presentar una denuncia contra {0}",
        ["chat.report_agree_contents"] = "Acepto enviar el contenido de esta conversación al equipo de AetherLove",
        ["chat.submitting"] = "Enviando…",
        ["chat.submit"] = "Enviar",

        // Verify encryption
        ["verify.title"] = "Verificar el cifrado",
        ["verify.intro"] = "AetherLove cifra este chat de extremo a extremo: solo tú y {0} podéis leerlo, ni siquiera nuestro equipo. El patrón entrelazado de abajo se genera a partir de vuestras dos claves de cifrado.",
        ["verify.unavailable"] = "La verificación aún no está lista. Estará disponible cuando ambos hayáis configurado el cifrado e intercambiado las claves.",
        ["verify.how"] = "Si {0} ve exactamente el mismo patrón y el mismo código en su pantalla, nadie está interceptando vuestro chat. Compáralos por chat de voz o en persona. Si no coinciden, deja de compartir información sensible y contacta con soporte.",
        ["verify.your_key"] = "Tu clave pública",
        ["verify.their_key"] = "Clave pública de {0}",
        ["verify.keys_explain"] = "Las claves públicas se pueden compartir sin riesgo; así es como vuestras apps se reconocen entre sí. Las claves privadas correspondientes nunca salen de vuestros dispositivos, por lo que ningún servidor (ni siquiera el nuestro) puede leer vuestros mensajes.",
        ["verify.back"] = "Volver al chat",

        // ChatListScreen
        ["chat.preview_me_prefix"] = "Yo: ",
        ["chat.preview_venue"] = "Compartió un local",
        ["chat.matches_title"] = "Coincidencias",
        ["chat.show_search"] = "Mostrar búsqueda",
        ["chat.hide_search"] = "Ocultar búsqueda",
        ["chat.search_hint"] = "Nombre o mensaje",
        ["chat.searching"] = "Buscando…",
        ["chat.search_no_results"] = "No se encontraron resultados",
        ["chat.matches_load_error"] = "No se pudieron cargar las coincidencias: {0}",
        ["chat.connectivity_error"] = "No se pudo conectar al servidor de AetherLove. Inténtalo de nuevo o visita Discord para ver el estado del servidor.",
        ["chat.empty_state"] = "Aún no tienes coincidencias, pero eso cambiará pronto. ¡Sigue deslizando!",
        ["chat.new_match"] = "coincidencia nueva",
        ["chat.say_hi"] = "Habéis coincidido. ¡Saluda!",
        ["chat.time_ago_minutes"] = "hace {0} min",
        ["chat.time_ago_hours"] = "hace {0} h",
        ["chat.time_ago_days"] = "hace {0} d",

        // added after update (1.3.1)
        ["chat.you"] = "Tú",
        ["chat.reply"] = "Responder",
        ["chat.pin_message"] = "Fijar mensaje",
        ["chat.unpin_message"] = "Dejar de fijar",
        ["chat.pinned_messages"] = "Mensajes fijados",
        ["chat.pinned_messages_menu"] = "Mensajes fijados ({0})",
        ["chat.quote_unavailable"] = "(mensaje original no disponible)",
        ["chat.quote_generic"] = "(mensaje)",
        ["chat.replying_to"] = "Respondiendo a {0}",
        ["chat.reaction_remove_hint"] = "haz clic para quitar",
        ["chat.jump"] = "Ir",
        ["chat.unpin"] = "Quitar",

        // added after update 1.4.3
        ["chat.menu_search"] = "Buscar mensajes",
        ["chat.search_messages_hint"] = "Buscar en este chat...",
        ["chat.category_new"] = "Nueva categoría",
        ["chat.category_edit"] = "Editar categoría",
        ["chat.category_delete"] = "Eliminar categoría",
        ["chat.category_delete_body"] = "¿Seguro que quieres eliminar {0}? Los chats que contiene volverán a tu lista de coincidencias.",
        ["chat.category_delete_confirm"] = "Eliminar",
        ["chat.category_name_hint"] = "Nombre de la categoría",
        ["chat.category_create"] = "Crear",
        ["chat.category_save"] = "Guardar",
        ["chat.menu_move_to_category"] = "Mover a categoría",
        ["chat.menu_remove_from_category"] = "Quitar de la categoría",
        ["chat.category_empty"] = "Aún no hay chats en esta categoría. Arrastra un chat hasta aquí o haz clic derecho en un chat y elige Mover a categoría.",
        ["chat.category_count"] = "Chats: {0}",
        ["chat.category_archive_default"] = "Archivo",
        ["chat.all_categorized"] = "Todos tus chats están guardados en categorías",

        // added after update 1.5.1
        ["chat.menu_view_blocked"] = "Ver bloqueados",
        ["blocked.title"] = "Usuarios bloqueados",
        ["blocked.intro_body"] = "Aquí puedes desbloquear perfiles que bloqueaste en el pasado. Al desbloquear a alguien no habrá match automático, pero podríais volver a veros en el mazo.",
        ["blocked.empty"] = "No has bloqueado a nadie.",
        ["blocked.loading"] = "Cargando...",
        ["blocked.since"] = "Bloqueado el {0}",
        ["blocked.unblock"] = "Desbloquear",
        ["blocked.confirm_title"] = "¿Desbloquear a {0}?",
        ["blocked.confirm_body"] = "No habrá match automático, pero podríais volver a veros en el mazo.",
        // generic share system (added after update 1.5.1)
        ["chat.news_card_label"] = "Noticias",
        ["chat.news_card_view"] = "Leer este artículo",
        ["chat.news_card_unavailable"] = "Este artículo ya no está disponible",
        ["chat.preview_news"] = "Compartió una noticia",

        // Messenger invite bridge (added after update 1.5.1)
        ["chat.menu_invite_messenger"] = "Invitar a Messenger",
        ["chat.msgr_card_title"] = "Invitación de Messenger",
        ["chat.msgr_card_hint"] = "Toca para añadir este código a tus contactos",
        ["chat.preview_messenger"] = "Envió una invitación de Messenger",
        // Key reset notices (added after update 1.5.1)
        ["chat.keys_reset_peer"] = "{0} ha restablecido sus claves de cifrado E2E",
        ["chat.keys_reset_you"] = "Restableciste tus claves de cifrado E2E; los mensajes anteriores ya no se pueden leer",
        // calendar event share
        ["chat.preview_calevent"] = "Compartió un evento",
        ["chat.preview_location"] = "Compartió una ubicación",
        ["chat.calevent_rsvp"] = "Asistiré",
        ["chat.calevent_add"] = "Añadir al calendario",
        // levemetes (added after update 2.0.1)
        ["chat.preview_levemete"] = "Compartió un anuncio",
        ["chat.preview_market"] = "Compartió un hallazgo del mercado",
        ["chat.market_card_label"] = "Mercado",
        ["chat.market_card_view"] = "Ver en el mercado",
        ["chat.leve_kind_looking"] = "Busco",
        ["chat.leve_kind_offering"] = "Ofrezco",
        ["chat.leve_cat_1"] = "Decoración de casas",
        ["chat.leve_cat_2"] = "Gposing",
        ["chat.leve_cat_3"] = "Comisiones",
        ["chat.leve_cat_4"] = "DJs",
        ["chat.leve_cat_5"] = "Personal de locales",
        ["chat.leve_cat_6"] = "Bardos y bandas",
        ["chat.leve_cat_7"] = "Servicios mercenarios",
        ["chat.leve_cat_8"] = "Artesanía y recolección",
        ["chat.leve_cat_9"] = "Servicios 18+",
        ["chat.leve_cat_unknown"] = "Otros",
        ["chat.leve_card_view"] = "Abrir el anuncio",
        ["chat.leve_card_loading"] = "Cargando anuncio...",
        ["chat.leve_card_unavailable"] = "Este anuncio ya no está disponible.",
        // user notes (added after update 2.0.1)
        ["chat.menu_user_note"] = "Nota sobre la persona",
        ["chat.note_hint"] = "Solo tú puedes ver esta nota. Se guarda en este equipo y nunca se envía a ninguna parte.",
        ["chat.note_save"] = "Guardar nota",
        ["chat.note_tooltip"] = "Tu nota:",
        // added after update 2.0.0.0 (message delete)
        ["chat.delete_message"] = "Eliminar mensaje",
        ["chat.delete_message_body"] = "¿Eliminar este mensaje para todos? En su lugar quedará un aviso de que lo has eliminado.",
        ["chat.delete_message_confirm"] = "Eliminar",
        ["chat.deleted_by_author"] = "Este mensaje fue eliminado por su autor.",
        // added after update 2.2.3 (echo)
        ["chat.preview_echo"] = "Compartió una sala de Echo",
        ["chat.echo_card_label"] = "Sala de Echo",
        ["chat.echo_card_host"] = "Anfitrión: {0}",
        ["chat.echo_card_members"] = "{0} viendo",
        ["chat.echo_card_idle"] = "Todavía no se reproduce nada",
        ["chat.echo_card_view"] = "Unirse a esta sala",
        ["chat.echo_card_loading"] = "Cargando sala...",
        ["chat.echo_card_unavailable"] = "Esta sala ya ha terminado",
    };
}
