namespace AetherLove.Services.Localization;

internal static class OsDe
{
    public static readonly System.Collections.Generic.Dictionary<string, string> Strings = new()
    {
        // added after update 1.5.1
        // App names
        ["os.app_clock"] = "Uhr",
        ["os.app_snake"] = "Snake",
        ["os.app_doom"] = "DOOM",
        ["os.app_sudoku"] = "Sudoku",
        ["os.app_stacker"] = "Stacker",
        ["os.app_breaker"] = "Breaker",
        ["os.app_meteor"] = "Meteor Command",
        ["os.app_invaders"] = "Void Invaders",
        ["os.app_muncher"] = "Maze Muncher",
        ["os.app_camera"] = "Kamera",

        // Notification shade
        ["os.notifications"] = "Benachrichtigungen",
        ["os.notifications_empty"] = "Keine Benachrichtigungen",
        ["os.notifications_clear"] = "Alle löschen",
        ["os.notif_remove"] = "Entfernen",
        ["os.time_now"] = "jetzt",
        ["os.qt_notifications"] = "Benachrichtigungen",
        ["os.qt_sounds"] = "Benachrichtigungstöne",
        ["os.qt_lock"] = "Handy-Position sperren",
        ["os.qt_theme"] = "Nächstes Design",
        ["os.qt_wallpaper"] = "Nächster Hintergrund",

        // Home screen
        ["os.greeting_morning"] = "Guten Morgen",
        ["os.greeting_afternoon"] = "Guten Tag",
        ["os.greeting_evening"] = "Guten Abend",
        ["os.greeting_night"] = "Noch wach?",
        ["os.widget_eorzea"] = "Eorzea",
        ["os.widget_status"] = "Verbindung",
        ["os.widget_connected"] = "Verbunden",
        ["os.widget_offline"] = "Offline",
        ["os.widget_unread"] = "{0} ungelesen",

        // OS settings
        ["os.group_appearance"] = "Darstellung",
        ["os.group_wallpaper"] = "Homescreen & Hintergrund",
        ["os.group_home"] = "Startbildschirm",
        ["os.group_apps"] = "App-spezifische Einstellungen",
        ["os.group_about"] = "Über",
        ["os.wallpaper_gradient"] = "Design",
        ["os.wallpaper_custom"] = "Deins",
        ["os.wallpaper_upload"] = "Bild hochladen…",
        ["os.wallpaper_dim"] = "Hintergrund abdunkeln",
        ["os.home_edit_hint"] = "Halte ein Symbol auf dem Startbildschirm gedrückt, um es zu verschieben. Ziehe Symbole ins Dock oder zwischen Seiten.",
        ["os.home_reset"] = "Layout zurücksetzen",

        // Love settings hub after the appearance move
        ["settings.menu_language"] = "Sprache & Zeit",

        // Weatherman app
        ["os.app_weather"] = "Wetter",

        // Messenger app
        ["os.app_messenger"] = "Messenger",

        // Photos app
        ["os.app_photos"] = "Fotos",

        // Home screen app launcher
        ["os.add_apps"] = "Apps hinzufügen",
        ["os.add_apps_title"] = "Apps hinzufügen",
        ["os.add_apps_hint"] = "Hol dir eine entfernte App zurück oder hefte ein anderes installiertes Dalamud-Plugin an.",
        ["os.add_apps_none"] = "Keine anderen Plugins bieten ein Hauptfenster an.",
        ["os.add_apps_add"] = "Hinzufügen",
        ["os.add_apps_added"] = "Hinzugefügt",
        ["os.add_apps_search"] = "Apps suchen...",
        ["os.remove_app_title"] = "App entfernen",
        ["os.remove_app_body"] = "Willst du {0} vom Startbildschirm entfernen?",
        ["os.remove_app_confirm"] = "Entfernen",
        // added after update 1.5.1
        ["os_onboarding.header_welcome"] = "Willkommen",
        ["os_onboarding.header_design"] = "Mach es zu deinem",
        ["os_onboarding.header_name"] = "Dein Name",
        ["os_onboarding.header_terms"] = "Nutzungsbedingungen",
        ["os_onboarding.welcome_title"] = "Willkommen bei AetherOS",
        ["os_onboarding.welcome_body"] = "Das ist dein Handy. Richten wir es ein: Wähle einen Look, einen Namen und stimme den Grundregeln zu. Dauert nur einen Moment.",
        ["os_onboarding.design_title"] = "Wähle ein Design",
        ["os_onboarding.name_title"] = "Wie sollen wir dich nennen?",
        ["os_onboarding.name_body"] = "Dieser Name wird in ganz AetherOS verwendet. Für jede App kannst du später einen eigenen Anzeigenamen wählen.",
        ["os_onboarding.name_hint"] = "Name",
        ["os_onboarding.terms_title"] = "Die Grundregeln",
        ["os_onboarding.terms_agree"] = "Ich stimme den Nutzungsbedingungen zu",
        ["os_onboarding.finish"] = "Fertig",
        ["os_onboarding.header_signin"] = "Anmelden",
        ["os_onboarding.header_passphrase"] = "Passphrase",
        ["os_onboarding.tos_1"] = "AetherOS ist ein von Fans erstelltes Plugin, ohne jegliche Gewährleistung bereitgestellt. Es kann jederzeit ausfallen, Daten verlieren oder aufhören zu funktionieren, und die Nutzung erfolgt auf eigene Gefahr.",
        ["os_onboarding.tos_2"] = "AetherOS steht in keiner Verbindung zu Square Enix und wird von Square Enix weder unterstützt noch gefördert.",
        ["os_onboarding.tos_3"] = "FINAL FANTASY und FINAL FANTASY XIV sind eingetragene Marken der Square Enix Holdings Co., Ltd. Alle anderen Marken sind Eigentum ihrer jeweiligen Inhaber.",
        ["os_onboarding.tos_4"] = "Wenn du fortfährst, akzeptierst du diese Bedingungen.",
        // OS account avatar (added after update 1.5.1)
        ["os_onboarding.header_avatar"] = "Avatar",
        ["os_onboarding.avatar_title"] = "Foto hinzufügen",
        ["os_onboarding.avatar_body"] = "Wähle ein Bild für dein AetherOS-Profil. Es ist optional und nur du siehst es. Du kannst es jederzeit ändern.",
        ["os_onboarding.avatar_choose"] = "Foto wählen",
        ["os_onboarding.avatar_change"] = "Foto ändern",
        // two-onboarding split (added after update 1.5.1)
        ["os_onboarding.header_done"] = "Fertig",
        ["os_onboarding.done_title"] = "Alles bereit!",
        ["os_onboarding.done_body"] = "Dein AetherOS-Konto ist eingerichtet. Viel Spaß mit deinem neuen Handy!",
        ["os_onboarding.done_start"] = "Plugin starten",
        ["os_onboarding.design_language"] = "Sprache",
        // combined OS profile step (added after update 1.5.1)
        ["os_onboarding.header_profile"] = "Dein Profil",
        ["os_onboarding.profile_name_label"] = "Dein Name",
        ["os_onboarding.profile_photo_label"] = "Dein Foto",
        // home button tooltip (added after update 1.5.1)
        ["os.home"] = "Startbildschirm",
        ["os.mini_open"] = "Vollansicht öffnen",
        ["os.mini_power"] = "Telefon ausschalten",
        // settings-consolidation categories + reset-home confirm + profile edit (added after update 1.5.1)
        ["os.cat_general"] = "Allgemein",
        ["os.cat_appearance"] = "Darstellung",
        ["os.cat_other"] = "Sonstiges",
        ["os.menu_general"] = "Allgemein",
        ["os.menu_appearance"] = "Handy-Darstellung",
        ["os.menu_reset_home"] = "Startbildschirm zurücksetzen",
        ["os.reset_home_confirm_title"] = "Startbildschirm zurücksetzen?",
        ["os.reset_home_confirm_body"] = "Dadurch werden deine eigene Symbolanordnung und das Dock gelöscht und die Standardanordnung wiederhergestellt. Deine Apps und Einstellungen bleiben unberührt.",
        ["os.edit_profile"] = "Bearbeiten",
        // Daily Eorzean news app (added after update 1.5.1)
        ["os.app_news"] = "Eorzäer Tagblatt",
        ["os.news_notifications"] = "Nachrichten-Benachrichtigungen",
        ["os.news_tagline"] = "Gegr. · Alle Neuigkeiten des Reichs",
        ["os.news_latest"] = "Aktuell",
        ["os.news_more"] = "Weitere Meldungen",
        ["os.news_edition"] = "Ausgabe · {0}",
        ["os.news_refresh"] = "Aktualisieren",
        ["os.news_new"] = "Neu",
        // Feedback app (added after update 1.5.1)
        ["os.app_feedback"] = "Feedback",
        ["os.feedback_app_label"] = "Um welche App geht es?",
        ["os.feedback_general"] = "Allgemein",
        ["os.feedback_send_another"] = "Weiteres Feedback senden",
        // generic share system (added after update 1.5.1)
        ["os.share_sheet_title"] = "Teilen mit",
        // home grid + folders
        ["os.settings_home_screen"] = "Startbildschirm",
        ["os.settings_home_grid_caption"] = "Die Symbole ordnen sich automatisch an das neue Raster an.",
        ["os.new_folder"] = "Neuer Ordner",
        ["os.folder_create"] = "Erstellen",
        ["os.folder_name_hint"] = "Ordnername…",
        ["os.folder_default_name"] = "Ordner",
        ["os.folder_arcade"] = "Arcade",
        ["os.folder_media"] = "Medien",
        ["os.folder_empty"] = "Noch keine Apps. Zieh ein Symbol auf diesen Ordner, um es hinzuzufügen.",
        // photo filters + screenshot import
        ["os.filter_original"] = "Original",
        ["os.filter_mono"] = "Mono",
        ["os.filter_noir"] = "Noir",
        ["os.filter_sepia"] = "Sepia",
        ["os.filter_retro"] = "Retro",
        ["os.filter_cool"] = "Kühl",
        ["os.filter_vivid"] = "Kräftig",
        ["os.filter_fade"] = "Verblasst",
        ["os.filter_applying"] = "Wird angewendet…",
        ["os.screenshots_album"] = "Screenshots",
        // calendar app
        ["os.app_calendar"] = "Kalender",
        ["os.edit_filters"] = "Filter",
        ["os.edit_adjust"] = "Anpassen",
        ["os.edit_brightness"] = "Helligkeit",
        ["os.edit_contrast"] = "Kontrast",
        ["os.edit_hue"] = "Farbton",
        ["os.edit_tint"] = "Tönung",
        // guided OS tour
        ["os.settings_tour"] = "Tour ansehen",
        ["os.tour_next"] = "Weiter",
        ["os.tour_back"] = "Zurück",
        ["os.tour_skip"] = "Überspringen",
        ["os.tour_finish"] = "Fertig",
        ["os.tour_welcome_title"] = "Willkommen bei AetherOS",
        ["os.tour_welcome_body"] = "Das ist dein Telefon: ein Homescreen voller Apps, und AetherLove ist nur eine davon. Schauen wir uns kurz um, das dauert nur eine Minute.",
        ["os.tour_homebtn_title"] = "Dein Home-Button",
        ["os.tour_homebtn_body"] = "Mit dem Home-Button kommst du jederzeit zurück zum Homescreen. Er leuchtet gerade unten am Telefon auf.",
        ["os.tour_pages_title"] = "Dein Homescreen",
        ["os.tour_pages_body"] = "Hier leben deine Apps, verteilt auf Seiten. Wische nach links und rechts, um zwischen ihnen zu wechseln. Die Punkte zeigen, auf welcher Seite du bist. Zieh ein Symbol an den Bildschirmrand. Die Seite blättert um und das Symbol kommt mit.",
        ["os.tour_widgets_title"] = "Die Widget-Seite",
        ["os.tour_widgets_body"] = "Wir sind gerade für dich zur Widget-Seite gewischt. Sie liegt links neben deinen Apps. Sie zeigt die Uhr mit Eorzea-Zeit, deinen Verbindungsstatus und deine neueste Benachrichtigung. Du kannst eine Karte halten und nach oben oder unten ziehen.",
        ["os.tour_statusbar_title"] = "Die Statusleiste",
        ["os.tour_statusbar_body"] = "Der hervorgehobene Streifen ganz oben zeigt die Uhrzeit, den Akku und deine Verbindung zu den AetherLove-Servern. Er zeigt auch, wie viele Benachrichtigungen warten. Bricht die Verbindung ab, erscheint dort ein rotes Warnsymbol.",
        ["os.tour_shade_title"] = "Benachrichtigungen",
        ["os.tour_shade_body"] = "Tippe oben auf das Telefon (oder zieh es herunter), um deine Benachrichtigungen zu sehen, genau wie wir es gerade gemacht haben. Hier findest du auch Schnelleinstellungen und einen Helligkeitsregler. Antippen öffnet eine Benachrichtigung, Wegwischen verwirft sie.",
        ["os.tour_fake_notif_title"] = "Hallo!",
        ["os.tour_fake_notif_body"] = "So sieht eine Benachrichtigung aus.",
        ["os.tour_badges_title"] = "Badges",
        ["os.tour_badges_body"] = "App-Symbole zeigen einen kleinen Zähler, wenn etwas auf dich wartet, etwa ungelesene Nachrichten oder neue Matches. Beim Öffnen der App verschwindet er. (Keine Sorge, du hast nicht wirklich 67 davon.)",
        ["os.tour_dock_title"] = "Das Dock",
        ["os.tour_dock_body"] = "Die untere Reihe bleibt auf jeder Seite gleich. Dort liegen deine Lieblings-Apps. Zieh ein Symbol hinein, dann erreichst du es mit einem Tipp. Zieh es wieder heraus, wenn du es dir anders überlegst.",
        ["os.tour_folders_title"] = "Ordner",
        ["os.tour_folders_body"] = "Lass ein Symbol auf einem anderen los, und beide werden zu einem Ordner. Tippe den Ordner an, um ihn zu öffnen. Benenne ihn um, wann immer du willst. Zieh eine App aus dem Ordner heraus, um sie zurück auf den Homescreen zu legen. Ein leerer Ordner verschwindet von selbst.",
        ["os.tour_addapps_title"] = "Mehr Apps",
        ["os.tour_addapps_body"] = "Jede App, die du entfernt hast, liegt weiterhin hier. Deine anderen Dalamud-Plugins liegen ebenfalls hier. Sie dürfen auf dem Homescreen stehen wie jede andere App.",
        ["os.tour_share_title"] = "Teilen",
        ["os.tour_share_body"] = "Du kannst Venues, Treffen und mehr mit deinen Matches und Freunden teilen. Das Teilen funktioniert von einer App in eine andere. Wähle aus, was du teilen willst, und dann, wohin es geht. Es kommt als Karte an, die du antippen kannst.",
        ["os.tour_look_title"] = "Aussehen und Layout",
        ["os.tour_look_body"] = "In der hervorgehobenen Einstellungen-App änderst du das Aussehen des Telefons. Du kannst ein Design wählen, das Hintergrundbild wechseln oder ein eigenes hochladen. Du kannst außerdem das Raster und das Telefon selbst in der Größe ändern.",
        ["os.tour_offline_title"] = "Offline",
        ["os.tour_offline_body"] = "Du kannst das Telefon weiter benutzen, auch wenn AetherLove oder eine seiner Apps offline ist. Eine App, die die Server braucht, wird abgedunkelt und bekommt eine kleine Markierung. Jede andere App funktioniert weiter.",
        ["os.tour_arrange_title"] = "Alles verschiebbar",
        ["os.tour_arrange_body"] = "Du kannst ein Symbol jederzeit ziehen. Es gibt keinen Bearbeitungsmodus, den du vorher einschalten musst. Nimm eines auf, trag es an einen neuen Platz und lass los. Dieser Platz kann auf jeder Seite oder in der unteren Reihe liegen.",
        ["os.tour_tilemenu_title"] = "Rechtsklick auf ein Symbol",
        ["os.tour_tilemenu_body"] = "Alles Weitere ist einen Rechtsklick entfernt: in einen Ordner legen, wieder herausnehmen, als gesehen markieren oder ganz vom Homescreen nehmen. Entfernen ist nie endgültig, du kannst es jederzeit zurückholen.",
        ["os.tour_homemenu_title"] = "Rechtsklick auf den Hintergrund",
        ["os.tour_homemenu_body"] = "Rechtsklick auf eine freie Stelle bringt den Rest: Apps hinzufügen, einen Ordner anlegen, alle neuen Apps auf einmal als gesehen markieren oder das Hintergrundbild wechseln.",
        ["os.tour_newapps_title"] = "Neue Apps",
        ["os.tour_newapps_body"] = "Bringt ein Update neue Apps, bekommst du eine Liste. Du wählst die aus, die du haben willst. Die Apps, die du auslässt, bleiben vom Homescreen weg, bis du nach ihnen fragst. Ein neues Symbol trägt eine kleine rote Markierung mit \"new\", bis du es einmal öffnest.",
        ["os.tour_done_title"] = "Das war die Tour!",
        ["os.tour_done_body"] = "Du kannst sie jederzeit in den Einstellungen erneut starten. Und jetzt viel Spaß beim Entdecken der Apps!",
        ["os.photos_search_hint"] = "Nach Name oder Ort suchen…",
        ["os.tt_prev"] = "Zurück",
        ["os.tt_next"] = "Weiter",
        ["os.tt_edit"] = "Bearbeiten",
        ["os.tt_move"] = "In Album verschieben",
        ["os.tt_share"] = "Teilen",
        ["os.tt_open_folder"] = "Ordner auf der Festplatte öffnen",
        ["os.share_wallpaper"] = "Hintergrundbild",
        ["os.profile_edit_title"] = "Profil bearbeiten",
        ["os.profile_save"] = "Speichern",
        // home right-click menu (added after update 2.0.0)
        ["os.home_menu_wallpaper"] = "Hintergrund ändern",
        // news app tile rename (added after update 2.0.0)
        ["os.app_news_tile"] = "Nachrichten",

        // battery easter egg (added after update 2.0.1)
        ["os.battery_grass_body"] = "Uns liegt deine Gesundheit am Herzen: Vergiss nicht rauszugehen, zu trinken und mal echtes Gras anzufassen ;-)",
        ["os.battery_grass_hint"] = "Bitte fasse unten das Gras an, um fortzufahren",
        ["os.settings_hide_battery_grass"] = "Gras-Hinweis bei leerem Akku ausblenden",
        // levemetes (added after update 2.0.1)
        ["os.app_levemetes"] = "Levemetes",
        ["os.battery_grass_settings_hint"] = "(Du kannst diesen Scherz in der Einstellungen-App unter Allgemein deaktivieren)",

        // added after update 2.0.1
        ["os.menu_audio"] = "Audio-Einstellungen",
        ["os.app_market"] = "Markt",
        ["os.app_realtor"] = "Makler",

        // added after update 2.1.3
        ["os.app_wayfinder"] = "Wayfinder",
        ["os.app_yapper"] = "Yapper",
        ["os.arcade_leaderboard"] = "Bestenliste",
        ["os.arcade_tab_weekly"] = "Diese Woche",
        ["os.arcade_tab_alltime"] = "Allzeit",
        ["os.arcade_loading"] = "Lädt...",
        ["os.arcade_empty"] = "Noch keine Ergebnisse. Hol dir den ersten Platz!",
        ["os.arcade_error"] = "Bestenliste konnte nicht geladen werden.",
        ["os.arcade_you"] = "Du",
        ["os.arcade_back"] = "Zurück",

        // wallet app (added after update 2.2.1)
        ["os.app_wallet"] = "Wallet",

        // plappy birb (added after update 2.2.3)
        ["os.app_plappy"] = "Plappy Birb",

        // removable first-party apps (added after update 2.2.3)
        ["os.add_apps_section_removed"] = "Entfernte Apps",
        ["os.add_apps_section_plugins"] = "Andere Plugins",

        // groove app (added after update 2.2.3)
        ["os.app_groove"] = "Groove",

        // store (added after update 2.2.3)
        ["os.app_store"] = "Store",
        ["os.store_preview_caption"] = "Nur Vorschau, noch nicht deins",
        ["os.store_preview_close"] = "Vorschau schließen",
        ["os.store_preview_loading"] = "Vorschau wird geladen…",
        ["os.store_preview_failed"] = "Vorschau konnte nicht geladen werden.",

        // added after update 2.2.3 (echo)
        ["os.app_echo"] = "Echo",
        // player and transport
        ["echo.play"] = "Abspielen",
        ["echo.pause"] = "Pause",
        ["echo.mute"] = "Stummschalten",
        ["echo.unmute"] = "Ton an",
        ["echo.skip"] = "Überspringen",
        ["echo.skip_tip"] = "Dieses Video für alle überspringen",
        ["echo.buffering"] = "Puffert…",
        ["echo.solo_idle"] = "Füg einen Link ein, um loszuschauen",
        ["echo.unavailable"] = "Nicht verfügbar",
        ["echo.close"] = "Schließen",
        // playlist
        ["echo.add"] = "Hinzufügen",
        ["echo.add_hint"] = "YouTube-Link einfügen",
        ["echo.added_by"] = "Hinzugefügt von {0}",
        ["echo.added_by_unknown"] = "Hinzugefügt von jemandem, der schon weg ist",
        ["echo.remove"] = "Entfernen",
        ["echo.queue_empty"] = "Noch nichts in der Warteschlange",
        ["echo.playlist_full"] = "Die Warteschlange ist voll",
        ["echo.bad_link"] = "Das ist kein YouTube-Link",
        // room
        ["echo.room_code"] = "Raumcode",
        ["echo.copy_code"] = "Code kopieren",
        ["echo.copied"] = "Kopiert",
        ["echo.host_only"] = "Nur Host",
        ["echo.host_only_hint"] = "Nur der Host kann die Wiedergabe steuern",
        ["echo.host_only_tip"] = "Der Host hat die Steuerung gesperrt",
        ["echo.kick"] = "Entfernen",
        ["echo.kick_confirm"] = "Diese Person aus dem Raum entfernen?",
        ["echo.leave_room"] = "Raum verlassen",
        ["echo.end_room"] = "Raum schließen",
        ["echo.end_room_confirm"] = "Den Raum für alle schließen?",
        ["echo.you"] = "{0} (du)",
        ["echo.tab_playlist"] = "Playlist",
        ["echo.tab_members"] = "Mitglieder",
        ["echo.tab_chat"] = "Chat",
        ["echo.toggle_panel"] = "Seitenleiste ein- oder ausblenden",
        ["echo.new_messages"] = "{0} neue Nachrichten",
        // room ended
        ["echo.room_ended_title"] = "Raum beendet",
        ["echo.room_ended_owner"] = "Der Host hat den Raum geschlossen",
        ["echo.room_ended_owner_left"] = "Die Verbindung des Hosts wurde getrennt",
        ["echo.room_ended_empty"] = "Alle haben den Raum verlassen",
        ["echo.room_ended_moderation"] = "Dieser Raum wurde von der Moderation geschlossen",
        ["echo.kicked_title"] = "Aus dem Raum entfernt",
        ["echo.kicked_body"] = "Du wurdest aus {0} entfernt",
        // runtime and errors
        ["echo.runtime_title"] = "Echo braucht seinen Player",
        ["echo.runtime_body"] = "Für die Videowiedergabe wird eine kleine Player-Komponente gebraucht. Sie wird einmalig heruntergeladen, danach ist Echo bei jedem Öffnen sofort startklar.",
        ["echo.runtime_install"] = "Herunterladen",
        ["echo.installing_title"] = "Echo wird vorbereitet",
        ["echo.install_downloading"] = "Wird heruntergeladen…",
        ["echo.install_verifying"] = "Wird geprüft…",
        ["echo.install_extracting"] = "Wird entpackt…",
        ["echo.install_failed_title"] = "Download fehlgeschlagen",
        ["echo.reinstall"] = "Neu installieren",
        ["echo.retry"] = "Erneut versuchen",
        ["echo.host_failed_title"] = "Der Player wurde beendet",
        ["echo.host_failed_body"] = "Er ließ sich nicht neu starten. Versuch es bitte noch einmal.",
        ["echo.protocol_title"] = "Player-Version passt nicht",
        ["echo.protocol_body"] = "Installiere den Echo-Player neu, um fortzufahren.",
        ["echo.embed_blocked_title"] = "Dieses Video lässt sich nicht einbetten",
        ["echo.embed_blocked_body"] = "Der Rechteinhaber erlaubt keine Wiedergabe außerhalb von YouTube.",
        ["echo.video_gone_title"] = "Video nicht verfügbar",
        ["echo.video_gone_body"] = "Es wurde entfernt oder auf privat gestellt.",
        ["echo.bad_id_title"] = "Ungültiger Link",
        ["echo.bad_id_body"] = "Diese Video-ID sieht nicht richtig aus.",
        ["echo.player_error_title"] = "Wiedergabe fehlgeschlagen",
        ["echo.player_error_body"] = "Beim Laden dieses Videos ist etwas schiefgelaufen.",

        // avatar rings (added after update 2.2.3)
        ["rings.section_title"] = "Avatar-Ring",
        ["rings.picker_title"] = "Avatar-Ring",
        ["rings.none"] = "Kein Ring",
        ["rings.none_owned_title"] = "Noch keine Ringe",
        ["rings.none_owned_body"] = "Avatar-Ringe sind dekorative Rahmen um dein Bild, sichtbar für alle. Kaufe sie mit Sparks im Store.",
        ["rings.open_store"] = "Store öffnen",
        ["rings.preview_hint"] = "Alle sehen deinen Ring, wo immer dein Bild angezeigt wird.",

        // aetherling (added after update 2.2.3)
        ["os.app_aetherling"] = "Aetherling",

        // added after update 2.3.3
        ["os.app_notes"] = "Notizen",
        ["os.app_together"] = "AetherParty",
        ["os.app_calculator"] = "Rechner",
        ["os.folder_utilities"] = "Werkzeuge",
        ["os.app_timers"] = "Timer",
        ["os.app_racooner"] = "Racooner",
        ["os.app_skyswarm"] = "Sky Swarm",
        ["os.app_eordle"] = "Eordle",

        // echo playback settings (added after update 2.2.3)
        ["echo.settings_tip"] = "Wiedergabe-Einstellungen",
        ["echo.settings_quality"] = "Videoqualität",
        ["echo.quality_auto"] = "Auto",
        ["echo.quality_720"] = "720p",
        ["echo.quality_1080"] = "1080p",
        ["echo.settings_captions"] = "Untertitel",
        ["echo.settings_autoplay"] = "Nächstes Video automatisch abspielen",
        ["echo.settings_software_render"] = "Software-Rendering",

        // home screen management (added after update 2.3.4)
        ["os.home_menu_add_app"] = "App hinzufügen",
        ["os.home_menu_add_folder"] = "Ordner hinzufügen",
        ["os.tile_menu_remove_app"] = "App entfernen",
        ["os.tile_menu_mark_seen"] = "Als gesehen markieren",
        ["os.home_menu_mark_seen"] = "Alle Apps als gesehen markieren",
        ["os.tile_menu_take_out"] = "Aus dem Ordner nehmen",
        ["os.tile_menu_move_to_folder"] = "In Ordner verschieben",
        ["os.tile_menu_remove_folder"] = "Ordner entfernen",
        ["os.folder_delete_title"] = "Ordner entfernen",
        ["os.folder_delete_body"] = "\"{0}\" samt der {1} Apps darin entfernen, oder die Apps behalten und zurück auf den Startbildschirm legen?",
        ["os.folder_delete_remove"] = "Ordner und Apps entfernen",
        ["os.folder_delete_keep"] = "Apps behalten",

        // new app offer (added after update 2.3.4)
        ["os.new_apps_title"] = "Neue Apps verfügbar",
        ["os.new_apps_body"] = "Dieses Update bringt neue Apps mit. Wähle aus, welche davon auf deinen Homescreen sollen. Den Rest kannst du später über das Homescreen-Menü hinzufügen.",
        ["os.new_apps_continue"] = "Weiter",
        ["os.app_levemetes_about"] = "Kleinanzeigen für Eorzea: biete etwas an oder schau, was andere suchen.",
        ["os.app_market_about"] = "Universalis-Preise, Verkaufsverlauf und Alarme für die Gegenstände, die du im Blick hast.",
        ["os.app_realtor_about"] = "Freie Grundstücke auf allen Welten, aktualisiert sobald eines frei wird.",
        ["os.app_wayfinder_about"] = "Spüre Wegpunkte in der Welt auf und verdiene Funken dafür.",
        ["os.app_yapper_about"] = "Kurze Beiträge und Bilder, Follows, Antworten und private Nachrichten.",
        ["os.app_wallet_about"] = "Deine Funken und jede Währung deines Charakters, samt Abstand zum Limit.",
        ["os.app_store_about"] = "Gib Funken für Designs, Avatarringe und andere Kleinigkeiten aus.",
        ["os.app_groove_about"] = "Eine Fernbedienung für alles, was dein PC gerade abspielt, samt der Lautstärkeregler des Spiels.",
        ["os.app_echo_about"] = "Schaut Videos gemeinsam mit Freunden, synchron.",
        ["os.app_notes_about"] = "Notizen und Listen, die nur auf diesem Rechner bleiben.",
        ["os.app_together_about"] = "Starte eine Gruppe oder tritt bei, lade Freunde ein und verdiene zusammen mehr Sparks.",
        ["os.app_calculator_about"] = "Ein Grafikrechner, Tastenfeld inklusive.",
        ["os.app_timers_about"] = "Hochseefischen, das Kaktrott-Los und die anderen Uhren, die sich lohnen.",
        ["os.app_aetherling_about"] = "Stimme einen Aetherkern ab und zieh groß, was daraus schlüpft.",
        ["os.app_snake_about"] = "Der Klassiker. Fressen, wachsen, sich nicht selbst beißen.",
        ["os.app_stacker_about"] = "Blöcke stapeln, Reihen räumen, den letzten Stein verfluchen.",
        ["os.app_breaker_about"] = "Lass den Ball in die Steine springen, bis keine mehr da sind.",
        ["os.app_meteor_about"] = "Schieße ab, was herabfällt, bevor es deine Städte trifft.",
        ["os.app_invaders_about"] = "Reihen von Aliens kommen herunter. Du hast eine Kanone.",
        ["os.app_muncher_about"] = "Räum das Labyrinth leer, weich den Geistern aus, jage sie, solange du kannst.",
        ["os.app_plappy_about"] = "Tippen zum Flattern. Die Röhren kennen kein Mitleid.",
        ["os.app_doom_about"] = "Der Shooter von 1993, direkt auf deinem Handy.",
        ["os.app_sudoku_about"] = "Neun mal neun, ein frisches Gitter wann immer du willst.",
        ["os.app_racooner_about"] = "Fang auf, was herunterfällt, und bring es heim in die Baue.",
        ["os.app_skyswarm_about"] = "Flieg durch den Schwarm, so lange du durchhältst.",
        ["os.app_eordle_about"] = "Ein eorzäisches Wort pro Tag, sechs Versuche.",

        // together mode (added after update 2.4.0)
        ["os.party_title"] = "AetherParty",
        ["os.party_members"] = "{0}/{1}",
        ["os.party_start"] = "Gruppe starten",
        ["os.party_join"] = "Beitreten",
        ["os.party_join_hint"] = "Gruppencode",
        ["os.party_code"] = "Code {0}",
        ["os.party_copied"] = "Kopiert!",
        ["os.party_leave"] = "Gruppe verlassen",
        ["os.party_end"] = "Gruppe beenden",
        ["os.party_ended"] = "Die Gruppe wurde beendet.",
        ["os.party_dismiss"] = "Okay",
        ["os.party_invite"] = "Einladen",
        ["os.party_error_full"] = "Diese Gruppe ist voll.",
        ["os.party_error_kicked"] = "Du wurdest aus dieser Gruppe entfernt.",
        ["os.party_error_in_party"] = "Du bist schon in einer Gruppe.",
        ["os.party_error_not_found"] = "Keine Gruppe mit diesem Code gefunden.",
        ["os.party_error_generic"] = "Das hat nicht geklappt. Versuch es nochmal.",
        ["os.party_invite_message"] = "{0} lädt dich in eine Gruppe ein! Öffne die Widget-Seite des Handys und tritt mit dem Code {1} bei.",
        ["os.party_activity_echo"] = "Watch-Party läuft",
        ["os.party_activity_wayfinder"] = "Gruppenjagd läuft",
        ["os.party_activity_generic"] = "Aktivität läuft",
        ["os.party_activity_open"] = "Öffnen",
        ["os.party_chat_title"] = "Gruppenchat",
        ["os.party_chat_hint"] = "Schreib deiner Gruppe...",
        ["os.party_chat_empty"] = "Noch keine Nachrichten. Sag doch hallo!",
        // message translation (added after update 2.4.0)
        ["os.translate"] = "Übersetzen",
        ["os.translate_retry"] = "Erneut übersetzen",
        ["os.translate_pending"] = "Wird übersetzt...",
        ["os.translate_show_original"] = "Original anzeigen",
        ["os.translate_settings"] = "Übersetzungseinstellungen",
        ["os.translate_consent_title"] = "Nachrichten übersetzen?",
        ["os.translate_consent_body"] = "Übersetzungen kommen von Google Translate. Der Text, den du übersetzt, wird über das Internet an Google geschickt, einen Drittanbieter. Es wird nichts anderes gesendet. Es wird nichts übersetzt, solange du nicht danach fragst.",
        ["os.translate_consent_enable"] = "Übersetzungen aktivieren",
        ["os.translate_consent_cancel"] = "Jetzt nicht",
        // translation onboarding + offer (added after update 2.4.0)
        ["os.translate_demo_source"] = "Bonjour ! On part explorer ensemble ?",
        ["os.translate_demo_result"] = "Hallo! Wollen wir zusammen auf Entdeckung gehen?",
        ["os.translate_offer_title"] = "Jede Nachricht übersetzen",
        ["os.translate_offer_body"] = "Dieses Update bringt Übersetzungen. Klicke mit rechts auf eine Chatnachricht, eine Profil-Bio oder einen Beitrag und wähle Übersetzen.",
        ["os.translate_offer_enable_go"] = "Aktivieren und weiter",
        ["os.translate_offer_skip_go"] = "Ohne Übersetzungen weiter",
        ["os_onboarding.translate_title"] = "Versteh einfach alle",
        ["os_onboarding.translate_body"] = "Du kannst Chats, Profile und Beiträge in deine Sprache übersetzen. Klicke mit rechts auf einen Text und wähle Übersetzen.",
        ["os_onboarding.translate_later"] = "Alles davon kannst du später in den Einstellungen unter Sprachen ändern.",

        // together onboarding (added after update 2.4.0)
        ["os.party_intro_title_0"] = "Gemeinsam unterwegs",
        ["os.party_intro_body_0"] = "Eine Gruppe bringt dich und bis zu drei Freunde auf einen Bildschirm. Teile den Code, dann treten sie bei. Startet eine Person eine Watch-Party oder eine Wayfinder-Jagd, können alle anderen mitmachen.",
        ["os.party_intro_title_1"] = "Gemeinsam chatten",
        ["os.party_intro_body_1"] = "Der Gruppenchat sitzt auf einer schmalen Leiste neben dem Handy. Neue Nachrichten erscheinen dort, ohne dass du etwas öffnest.",
        ["os.party_intro_title_2"] = "Nimm dein Aetherling mit",
        ["os.party_intro_body_2"] = "Im Gruppenmodus kannst du deinen Aetherling teilen und die Aetherlinge deiner Gruppe sehen. Alles ist freiwillig.",
        ["os.party_intro_pets_show"] = "Aetherlinge aller Gruppenmitglieder zeigen",
        ["os.party_intro_pets_share"] = "Gruppenmitglieder dürfen meines sehen",
        ["os.party_intro_pets_size"] = "Wie groß sollen sie sein?",
        ["os.party_intro_f0_code"] = "Ein Code lädt alle ein: teile ihn, sie treten bei.",
        ["os.party_intro_f0_activity"] = "Startet eine Person eine Watch-Party oder eine Wayfinder-Jagd, können alle anderen mitmachen.",
        ["os.party_intro_f0_size"] = "Bis zu vier von euch auf einmal.",
        ["os.party_intro_f1_widget"] = "Verwalte die Gruppe über ihre Karte auf der Widget-Seite des Handys.",
        ["os.party_intro_f1_dock"] = "Die Mitglieder stehen neben dem Handy, du siehst auf einen Blick, wer da ist.",
        ["os.party_intro_f1_chat"] = "Chatte mit deinen Freunden, auch wenn sie auf anderen Servern oder Datenzentren sind.",
        ["os.party_intro_pets_show_hint"] = "Ihre Aetherlinge scharen sich draußen um deines.",
        ["os.party_intro_pets_share_hint"] = "Mitglieder deiner Gruppen sehen dein Aetherling neben ihrem.",
        ["os.party_in_party"] = "Gerade in einer Gruppe · {0}",
        ["os.party_intro_next"] = "Weiter",
        ["os.party_intro_start"] = "Los",
        ["os.party_pet_size_0"] = "XS",
        ["os.party_pet_size_1"] = "S",
        ["os.party_pet_size_2"] = "M",
        ["os.party_pet_size_3"] = "L",
        ["os.party_pet_size_4"] = "XL",

        // widget page (added after update 2.4.0)
        ["os.widget_add_new"] = "Neues Widget hinzufügen",
        ["os.widget_settings"] = "Widget-Einstellungen",
        ["os.widget_remove"] = "Dieses Widget entfernen",
        ["os.widget_clock"] = "Uhr",
        ["os.widget_status"] = "Status",
        ["os.widget_notifications"] = "Benachrichtigungen",
        ["os.widget_party"] = "AetherParty",

        // screenshot import consent (added after update 2.4.0)
        ["os.photos_screenshots_offer"] = "Deine Spiel-Screenshots zu Fotos hinzufügen? Tippe hier, um das festzulegen.",
        ["os.party_settings"] = "AetherParty-Einstellungen",
        ["os.party_kick_tip"] = "{0} aus der Gruppe entfernen",
        ["os.party_kick_title"] = "Aus der Gruppe entfernen?",
        ["os.party_kick_body"] = "{0} wird aus der Gruppe entfernt und kann dieser Gruppe nicht erneut beitreten.",
        ["os.party_kick_go"] = "Entfernen",
        ["os.party_chat_joined"] = "{0} ist der Gruppe beigetreten",
        ["os.party_chat_wayfinder"] = "{0} hat eine Wayfinder-Jagd gestartet. Tippe, um mitzumachen.",
        ["os.party_chat_echo"] = "{0} hat einen Echo-Raum eröffnet. Tippe, um beizutreten.",
    };
}
