namespace AetherLove.Services.Localization;

internal static class OsFr
{
    public static readonly System.Collections.Generic.Dictionary<string, string> Strings = new()
    {
        // added after update 1.5.1
        // App names
        ["os.app_clock"] = "Horloge",
        ["os.app_snake"] = "Snake",
        ["os.app_doom"] = "DOOM",
        ["os.app_sudoku"] = "Sudoku",
        ["os.app_stacker"] = "Stacker",
        ["os.app_breaker"] = "Breaker",
        ["os.app_meteor"] = "Meteor Command",
        ["os.app_invaders"] = "Void Invaders",
        ["os.app_muncher"] = "Maze Muncher",
        ["os.app_camera"] = "Appareil photo",

        // Notification shade
        ["os.notifications"] = "Notifications",
        ["os.notifications_empty"] = "Aucune notification",
        ["os.notifications_clear"] = "Tout effacer",
        ["os.notif_remove"] = "Retirer",
        ["os.time_now"] = "maintenant",
        ["os.qt_notifications"] = "Notifications",
        ["os.qt_sounds"] = "Sons de notification",
        ["os.qt_lock"] = "Verrouiller la position du téléphone",
        ["os.qt_theme"] = "Thème suivant",
        ["os.qt_wallpaper"] = "Fond d'écran suivant",

        // Home screen
        ["os.greeting_morning"] = "Bonjour",
        ["os.greeting_afternoon"] = "Bon après-midi",
        ["os.greeting_evening"] = "Bonsoir",
        ["os.greeting_night"] = "Encore debout ?",
        ["os.widget_eorzea"] = "Éorzéa",
        ["os.widget_status"] = "Connexion",
        ["os.widget_connected"] = "Connecté",
        ["os.widget_offline"] = "Hors ligne",
        ["os.widget_unread"] = "{0} non lus",

        // OS settings
        ["os.group_appearance"] = "Apparence",
        ["os.group_wallpaper"] = "Écran d'accueil et fond d'écran",
        ["os.group_home"] = "Écran d'accueil",
        ["os.group_apps"] = "Réglages par appli",
        ["os.group_about"] = "À propos",
        ["os.wallpaper_gradient"] = "Thème",
        ["os.wallpaper_custom"] = "Le vôtre",
        ["os.wallpaper_upload"] = "Importer une image…",
        ["os.wallpaper_dim"] = "Assombrir le fond d'écran",
        ["os.home_edit_hint"] = "Maintenez une icône de l'écran d'accueil pour la réorganiser. Faites glisser les icônes vers le dock ou entre les pages.",
        ["os.home_reset"] = "Réinitialiser la disposition",

        // Love settings hub after the appearance move
        ["settings.menu_language"] = "Langue et heure",

        // Weatherman app
        ["os.app_weather"] = "Météo",

        // Messenger app
        ["os.app_messenger"] = "Messenger",

        // Photos app
        ["os.app_photos"] = "Photos",

        // Home screen app launcher
        ["os.add_apps"] = "Ajouter des applications",
        ["os.add_apps_title"] = "Ajouter des applications",
        ["os.add_apps_hint"] = "Récupérez une application retirée ou épinglez un autre plugin Dalamud installé.",
        ["os.add_apps_none"] = "Aucun autre plugin ne propose de fenêtre principale.",
        ["os.add_apps_add"] = "Ajouter",
        ["os.add_apps_added"] = "Ajoutée",
        ["os.add_apps_search"] = "Rechercher des applis...",
        ["os.remove_app_title"] = "Retirer l'appli",
        ["os.remove_app_body"] = "Voulez-vous retirer {0} de votre écran d'accueil ?",
        ["os.remove_app_confirm"] = "Retirer",
        // added after update 1.5.1
        ["os_onboarding.header_welcome"] = "Bienvenue",
        ["os_onboarding.header_design"] = "Personnalise-le",
        ["os_onboarding.header_name"] = "Ton nom",
        ["os_onboarding.header_terms"] = "Conditions d'utilisation",
        ["os_onboarding.welcome_title"] = "Bienvenue sur AetherOS",
        ["os_onboarding.welcome_body"] = "Voici ton téléphone. Configurons-le : choisis un style, un nom et accepte les règles de base. Ça ne prend qu'un instant.",
        ["os_onboarding.design_title"] = "Choisis un design",
        ["os_onboarding.name_title"] = "Comment doit-on t'appeler ?",
        ["os_onboarding.name_body"] = "Ce nom est utilisé dans tout AetherOS. Tu pourras choisir un nom différent pour chaque appli plus tard.",
        ["os_onboarding.name_hint"] = "Nom",
        ["os_onboarding.terms_title"] = "Les règles de base",
        ["os_onboarding.terms_agree"] = "J'accepte les conditions d'utilisation",
        ["os_onboarding.finish"] = "Terminer",
        ["os_onboarding.header_signin"] = "Connexion",
        ["os_onboarding.header_passphrase"] = "Phrase secrète",
        ["os_onboarding.tos_1"] = "AetherOS est un plugin créé par des fans, fourni tel quel, sans aucune garantie. Il peut planter, perdre des données ou cesser de fonctionner à tout moment, et son utilisation se fait à tes propres risques.",
        ["os_onboarding.tos_2"] = "AetherOS n'est ni affilié à Square Enix, ni approuvé ou sponsorisé par Square Enix.",
        ["os_onboarding.tos_3"] = "FINAL FANTASY et FINAL FANTASY XIV sont des marques déposées de Square Enix Holdings Co., Ltd. Toutes les autres marques appartiennent à leurs propriétaires respectifs.",
        ["os_onboarding.tos_4"] = "En continuant, tu acceptes ces conditions.",
        // OS account avatar (added after update 1.5.1)
        ["os_onboarding.header_avatar"] = "Avatar",
        ["os_onboarding.avatar_title"] = "Ajoute une photo",
        ["os_onboarding.avatar_body"] = "Choisis une image pour ton profil AetherOS. C'est facultatif et toi seul la vois ; tu peux la changer à tout moment.",
        ["os_onboarding.avatar_choose"] = "Choisir une photo",
        ["os_onboarding.avatar_change"] = "Changer de photo",
        // two-onboarding split (added after update 1.5.1)
        ["os_onboarding.header_done"] = "Terminé",
        ["os_onboarding.done_title"] = "Tout est prêt !",
        ["os_onboarding.done_body"] = "Ton compte AetherOS est prêt. Profite bien de ton nouveau téléphone !",
        ["os_onboarding.done_start"] = "Commencer à utiliser le plugin",
        ["os_onboarding.design_language"] = "Langue",
        // combined OS profile step (added after update 1.5.1)
        ["os_onboarding.header_profile"] = "Ton profil",
        ["os_onboarding.profile_name_label"] = "Ton nom",
        ["os_onboarding.profile_photo_label"] = "Ta photo",
        // home button tooltip (added after update 1.5.1)
        ["os.home"] = "Accueil",
        ["os.mini_open"] = "Ouvrir la vue complète",
        ["os.mini_power"] = "Éteindre le téléphone",
        // settings-consolidation categories + reset-home confirm + profile edit (added after update 1.5.1)
        ["os.cat_general"] = "Général",
        ["os.cat_appearance"] = "Apparence",
        ["os.cat_other"] = "Autre",
        ["os.menu_general"] = "Général",
        ["os.menu_appearance"] = "Apparence du téléphone",
        ["os.menu_reset_home"] = "Réinitialiser l'écran d'accueil",
        ["os.reset_home_confirm_title"] = "Réinitialiser l'écran d'accueil ?",
        ["os.reset_home_confirm_body"] = "Cela efface votre disposition d'icônes et votre dock personnalisés et rétablit la disposition par défaut. Vos applications et réglages ne sont pas affectés.",
        ["os.edit_profile"] = "Modifier",
        // Daily Eorzean news app (added after update 1.5.1)
        ["os.app_news"] = "Le Quotidien d'Éorzéa",
        ["os.news_notifications"] = "Notifications d'actualités",
        ["os.news_tagline"] = "Fond. · Toute l'actualité du royaume",
        ["os.news_latest"] = "À la une",
        ["os.news_more"] = "Plus d'articles",
        ["os.news_edition"] = "Édition · {0}",
        ["os.news_refresh"] = "Actualiser",
        ["os.news_new"] = "Nouveau",
        // Feedback app (added after update 1.5.1)
        ["os.app_feedback"] = "Commentaires",
        ["os.feedback_app_label"] = "De quelle application s'agit-il ?",
        ["os.feedback_general"] = "Général",
        ["os.feedback_send_another"] = "Envoyer d'autres commentaires",
        // generic share system (added after update 1.5.1)
        ["os.share_sheet_title"] = "Partager avec",
        // home grid + folders
        ["os.settings_home_screen"] = "Écran d'accueil",
        ["os.settings_home_grid_caption"] = "Les icônes se réorganisent automatiquement selon la nouvelle grille.",
        ["os.new_folder"] = "Nouveau dossier",
        ["os.folder_create"] = "Créer",
        ["os.folder_name_hint"] = "Nom du dossier…",
        ["os.folder_default_name"] = "Dossier",
        ["os.folder_arcade"] = "Arcade",
        ["os.folder_media"] = "Médias",
        ["os.folder_empty"] = "Pas encore d'applis. Faites glisser une icône sur ce dossier pour l'ajouter.",
        // photo filters + screenshot import
        ["os.filter_original"] = "Original",
        ["os.filter_mono"] = "Mono",
        ["os.filter_noir"] = "Noir",
        ["os.filter_sepia"] = "Sépia",
        ["os.filter_retro"] = "Rétro",
        ["os.filter_cool"] = "Froid",
        ["os.filter_vivid"] = "Vif",
        ["os.filter_fade"] = "Délavé",
        ["os.filter_applying"] = "Application…",
        ["os.screenshots_album"] = "Captures",
        // calendar app
        ["os.app_calendar"] = "Calendrier",
        ["os.edit_filters"] = "Filtres",
        ["os.edit_adjust"] = "Réglages",
        ["os.edit_brightness"] = "Luminosité",
        ["os.edit_contrast"] = "Contraste",
        ["os.edit_hue"] = "Teinte",
        ["os.edit_tint"] = "Intensité",
        // guided OS tour
        ["os.settings_tour"] = "Faire la visite",
        ["os.tour_next"] = "Suivant",
        ["os.tour_back"] = "Retour",
        ["os.tour_skip"] = "Passer",
        ["os.tour_finish"] = "Terminé",
        ["os.tour_welcome_title"] = "Bienvenue sur AetherOS",
        ["os.tour_welcome_body"] = "Voici votre téléphone : un écran d'accueil rempli d'applis, et AetherLove n'en est qu'une parmi d'autres. Faisons un petit tour, cela ne prend qu'une minute.",
        ["os.tour_homebtn_title"] = "Votre bouton d'accueil",
        ["os.tour_homebtn_body"] = "Vous pouvez toujours revenir à l'écran d'accueil avec le bouton d'accueil, celui qui brille en bas du téléphone.",
        ["os.tour_pages_title"] = "Votre écran d'accueil",
        ["os.tour_pages_body"] = "Vos applis vivent ici, réparties sur plusieurs pages. Balayez à gauche et à droite pour passer de l'une à l'autre. Les points indiquent sur quelle page vous êtes. Amenez une icône au bord de l'écran. La page tourne et l'icône part avec elle.",
        ["os.tour_widgets_title"] = "La page des widgets",
        ["os.tour_widgets_body"] = "Nous venons de glisser vers la page des widgets pour vous. Elle se trouve à gauche de vos applis. Elle affiche l'horloge avec l'heure d'Éorzéa, l'état de la connexion et votre dernière notification. Vous pouvez maintenir une carte et la faire glisser vers le haut ou vers le bas.",
        ["os.tour_statusbar_title"] = "La barre d'état",
        ["os.tour_statusbar_body"] = "La bande mise en avant tout en haut affiche l'heure, la batterie et votre connexion aux serveurs AetherLove. Elle affiche aussi le nombre de notifications en attente. Une icône rouge y apparaît quand la connexion est perdue.",
        ["os.tour_shade_title"] = "Notifications",
        ["os.tour_shade_body"] = "Touchez le haut du téléphone (ou faites-le glisser vers le bas) pour voir vos notifications, comme nous venons de le faire. Vous y trouverez aussi des réglages rapides et un curseur de luminosité. Touchez une notification pour l'ouvrir, balayez-la pour l'ignorer.",
        ["os.tour_fake_notif_title"] = "Bonjour !",
        ["os.tour_fake_notif_body"] = "Voici à quoi ressemble une notification.",
        ["os.tour_badges_title"] = "Pastilles",
        ["os.tour_badges_body"] = "Les icônes affichent un petit compteur quand quelque chose vous attend, comme des messages non lus ou de nouveaux matchs. Il disparaît à l'ouverture de l'appli. (Rassurez-vous, vous n'en avez pas vraiment 67.)",
        ["os.tour_dock_title"] = "Le dock",
        ["os.tour_dock_body"] = "La rangée du bas reste sur toutes les pages. Elle accueille vos applis préférées. Glissez-y une icône pour l'avoir à portée d'un geste. Ressortez-la quand vous changez d'avis.",
        ["os.tour_folders_title"] = "Dossiers",
        ["os.tour_folders_body"] = "Lâchez une icône sur une autre et elles deviennent un dossier. Touchez le dossier pour l'ouvrir. Renommez-le quand vous voulez. Faites glisser une appli hors du dossier pour la remettre sur l'écran d'accueil. Un dossier vide disparaît tout seul.",
        ["os.tour_addapps_title"] = "Plus d'applis",
        ["os.tour_addapps_body"] = "Chaque appli que vous avez retirée est toujours ici. Vos autres plugins Dalamud sont ici aussi. Ils peuvent occuper l'écran d'accueil comme n'importe quelle autre appli.",
        ["os.tour_share_title"] = "Partage",
        ["os.tour_share_body"] = "Vous pouvez partager établissements, rencontres et bien plus avec vos matchs et vos amis. Le partage fonctionne d'une appli à une autre. Choisissez quoi partager, puis choisissez où cela va. Cela arrive sous forme de carte que vous pouvez toucher.",
        ["os.tour_look_title"] = "Apparence",
        ["os.tour_look_body"] = "L'appli Réglages mise en avant sert à changer l'apparence du téléphone. Vous pouvez choisir un thème, changer le fond d'écran ou importer le vôtre. Vous pouvez aussi redimensionner la grille et le téléphone lui-même.",
        ["os.tour_offline_title"] = "Hors ligne",
        ["os.tour_offline_body"] = "Vous pouvez continuer à utiliser le téléphone même quand AetherLove ou l'une de ses applis est hors ligne. Une appli qui a besoin des serveurs s'assombrit et porte un petit marqueur. Toutes les autres applis continuent de fonctionner.",
        ["os.tour_arrange_title"] = "Déplacez tout",
        ["os.tour_arrange_body"] = "Vous pouvez glisser une icône à tout moment. Il n'y a pas de mode édition à activer d'abord. Prenez-en une, portez-la à un nouvel endroit et lâchez. Cet endroit peut être sur n'importe quelle page ou dans la rangée du bas.",
        ["os.tour_tilemenu_title"] = "Clic droit sur une icône",
        ["os.tour_tilemenu_body"] = "Tout le reste tient dans un clic droit : la ranger dans un dossier, l'en ressortir, la marquer comme vue ou la retirer de l'écran d'accueil. Retirer n'est jamais définitif, vous pouvez toujours la remettre.",
        ["os.tour_homemenu_title"] = "Clic droit sur le fond",
        ["os.tour_homemenu_body"] = "Clic droit sur un espace libre pour la suite : ajouter des applis, créer un dossier, marquer d'un coup toutes les nouvelles applis comme vues, ou aller changer le fond d'écran.",
        ["os.tour_newapps_title"] = "Nouvelles applis",
        ["os.tour_newapps_body"] = "Quand une mise à jour apporte de nouvelles applis, vous recevez une liste. Vous choisissez celles que vous voulez. Les applis que vous laissez de côté restent hors de l'écran d'accueil jusqu'à ce que vous les demandiez. Une nouvelle icône porte une petite pastille rouge \"new\" jusqu'à sa première ouverture.",
        ["os.tour_done_title"] = "Fin de la visite !",
        ["os.tour_done_body"] = "Vous pouvez la revoir à tout moment depuis les Réglages. Maintenant, explorez les applis et amusez-vous bien.",
        ["os.photos_search_hint"] = "Rechercher par nom ou lieu…",
        ["os.tt_prev"] = "Précédent",
        ["os.tt_next"] = "Suivant",
        ["os.tt_edit"] = "Modifier",
        ["os.tt_move"] = "Déplacer vers un album",
        ["os.tt_share"] = "Partager",
        ["os.tt_open_folder"] = "Ouvrir le dossier sur le disque",
        ["os.share_wallpaper"] = "Fond d'écran",
        ["os.profile_edit_title"] = "Modifier le profil",
        ["os.profile_save"] = "Enregistrer",
        // home right-click menu (added after update 2.0.0)
        ["os.home_menu_lock_icons"] = "Verrouiller les icônes",
        ["os.home_menu_unlock_icons"] = "Déverrouiller les icônes",
        ["os.home_menu_wallpaper"] = "Changer le fond d'écran",
        // news app tile rename (added after update 2.0.0)
        ["os.app_news_tile"] = "Actualités",

        // battery easter egg (added after update 2.0.1)
        ["os.battery_grass_body"] = "Votre santé compte pour nous : n'oubliez pas de sortir, de vous hydrater et de toucher un peu d'herbe ;-)",
        ["os.battery_grass_hint"] = "Touchez l'herbe ci-dessous pour continuer",
        ["os.settings_hide_battery_grass"] = "Masquer le message sur l'herbe quand la batterie est vide",
        // levemetes (added after update 2.0.1)
        ["os.app_levemetes"] = "Levemetes",
        ["os.battery_grass_settings_hint"] = "(Vous pouvez désactiver cette blague dans Général, dans l'app Réglages)",

        // added after update 2.0.1
        ["os.menu_audio"] = "Paramètres audio",
        ["os.app_market"] = "Marché",
        ["os.app_realtor"] = "Immobilier",

        // added after update 2.1.3
        ["os.app_wayfinder"] = "Wayfinder",
        ["os.app_yapper"] = "Yapper",
        ["os.arcade_leaderboard"] = "Classement",
        ["os.arcade_tab_weekly"] = "Cette semaine",
        ["os.arcade_tab_alltime"] = "Tous les temps",
        ["os.arcade_loading"] = "Chargement...",
        ["os.arcade_empty"] = "Pas encore de scores. Soyez le premier !",
        ["os.arcade_error"] = "Impossible de charger le classement.",
        ["os.arcade_you"] = "Vous",
        ["os.arcade_back"] = "Retour",

        // wallet app (added after update 2.2.1)
        ["os.app_wallet"] = "Portefeuille",

        // plappy birb (added after update 2.2.3)
        ["os.app_plappy"] = "Plappy Birb",

        // removable first-party apps (added after update 2.2.3)
        ["os.add_apps_section_removed"] = "Applications retirées",
        ["os.add_apps_section_plugins"] = "Autres plugins",

        // groove app (added after update 2.2.3)
        ["os.app_groove"] = "Groove",

        // store (added after update 2.2.3)
        ["os.app_store"] = "Boutique",
        ["os.store_preview_caption"] = "Aperçu seulement, pas encore à vous",
        ["os.store_preview_close"] = "Fermer l'aperçu",
        ["os.store_preview_loading"] = "Chargement de l'aperçu…",
        ["os.store_preview_failed"] = "Impossible de charger l'aperçu.",

        // added after update 2.2.3 (echo)
        ["os.app_echo"] = "Echo",
        // player and transport
        ["echo.play"] = "Lecture",
        ["echo.pause"] = "Pause",
        ["echo.mute"] = "Couper le son",
        ["echo.unmute"] = "Rétablir le son",
        ["echo.skip"] = "Passer",
        ["echo.skip_tip"] = "Passer cette vidéo pour tout le monde",
        ["echo.buffering"] = "Chargement…",
        ["echo.solo_idle"] = "Collez un lien pour commencer à regarder",
        ["echo.unavailable"] = "Indisponible",
        ["echo.close"] = "Fermer",
        // playlist
        ["echo.add"] = "Ajouter",
        ["echo.add_hint"] = "Collez un lien YouTube ou Twitch",
        ["echo.added_by"] = "Ajoutée par {0}",
        ["echo.added_by_unknown"] = "Ajoutée par quelqu'un qui est déjà parti",
        ["echo.remove"] = "Retirer",
        ["echo.queue_empty"] = "Rien dans la file pour l'instant",
        ["echo.playlist_full"] = "La file est pleine",
        ["echo.bad_link"] = "Ce n'est pas un lien YouTube",
        // room
        ["echo.room_code"] = "Code du salon",
        ["echo.copy_code"] = "Copier le code",
        ["echo.copied"] = "Copié",
        ["echo.host_only"] = "Hôte uniquement",
        ["echo.host_only_hint"] = "Seul l'hôte peut contrôler la lecture",
        ["echo.host_only_tip"] = "L'hôte a verrouillé les commandes",
        ["echo.kick"] = "Exclure",
        ["echo.kick_confirm"] = "Retirer cette personne du salon ?",
        ["echo.leave_room"] = "Quitter le salon",
        ["echo.end_room"] = "Fermer le salon",
        ["echo.end_room_confirm"] = "Fermer le salon pour tout le monde ?",
        ["echo.you"] = "{0} (vous)",
        ["echo.tab_playlist"] = "Playlist",
        ["echo.tab_members"] = "Membres",
        ["echo.tab_chat"] = "Chat",
        ["echo.toggle_panel"] = "Afficher ou masquer le panneau latéral",
        ["echo.new_messages"] = "{0} nouveaux messages",
        // room ended
        ["echo.room_ended_title"] = "Salon terminé",
        ["echo.room_ended_owner"] = "L'hôte a fermé le salon",
        ["echo.room_ended_owner_left"] = "L'hôte s'est déconnecté",
        ["echo.room_ended_empty"] = "Tout le monde est parti",
        ["echo.room_ended_moderation"] = "Ce salon a été fermé par la modération",
        ["echo.kicked_title"] = "Exclu du salon",
        ["echo.kicked_body"] = "Vous avez été retiré de {0}",
        // runtime and errors
        ["echo.runtime_title"] = "Echo a besoin de son lecteur",
        ["echo.runtime_body"] = "La lecture vidéo nécessite un petit composant de lecture. Il se télécharge une seule fois, puis Echo est prêt à chaque ouverture.",
        ["echo.runtime_install"] = "Le télécharger",
        ["echo.installing_title"] = "Préparation d'Echo",
        ["echo.install_downloading"] = "Téléchargement…",
        ["echo.install_verifying"] = "Vérification…",
        ["echo.install_extracting"] = "Extraction…",
        ["echo.install_failed_title"] = "Échec du téléchargement",
        ["echo.reinstall"] = "Réinstaller",
        ["echo.retry"] = "Réessayer",
        ["echo.host_failed_title"] = "Le lecteur s'est arrêté",
        ["echo.host_failed_body"] = "Impossible de le redémarrer. Veuillez réessayer.",
        ["echo.protocol_title"] = "Version du lecteur incompatible",
        ["echo.protocol_body"] = "Réinstallez le lecteur Echo pour continuer.",
        ["echo.embed_blocked_title"] = "Cette vidéo ne peut pas être intégrée",
        ["echo.embed_blocked_body"] = "Son propriétaire n'autorise pas la lecture en dehors de YouTube.",
        ["echo.video_gone_title"] = "Vidéo indisponible",
        ["echo.video_gone_body"] = "Elle a été supprimée ou rendue privée.",
        ["echo.bad_id_title"] = "Lien invalide",
        ["echo.bad_id_body"] = "Cet identifiant de vidéo ne semble pas correct.",
        ["echo.player_error_title"] = "Échec de la lecture",
        ["echo.player_error_body"] = "Une erreur est survenue lors du chargement de cette vidéo.",

        // avatar rings (added after update 2.2.3)
        ["rings.section_title"] = "Anneau d'avatar",
        ["rings.picker_title"] = "Anneau d'avatar",
        ["rings.none"] = "Aucun anneau",
        ["rings.none_owned_title"] = "Pas encore d'anneaux",
        ["rings.none_owned_body"] = "Les anneaux d'avatar sont des cadres décoratifs autour de votre photo, visibles par tous. Achetez-les avec des Sparks dans la Store.",
        ["rings.open_store"] = "Ouvrir la Store",
        ["rings.preview_hint"] = "Tout le monde voit votre anneau partout où votre photo apparaît.",

        // aetherling (added after update 2.2.3)
        ["os.app_aetherling"] = "Aetherling",

        // added after update 2.3.3
        ["os.app_notes"] = "Notes",
        ["os.app_together"] = "AetherParty",
        ["os.app_calculator"] = "Calculatrice",
        ["os.folder_utilities"] = "Utilitaires",
        ["os.app_timers"] = "Minuteurs",
        ["os.app_racooner"] = "Racooner",
        ["os.app_skyswarm"] = "Sky Swarm",
        ["os.app_eordle"] = "Eordle",
        ["os.app_racer"] = "Lumi Racer",

        // echo playback settings (added after update 2.2.3)
        ["echo.settings_tip"] = "Réglages de lecture",
        ["echo.settings_quality"] = "Qualité vidéo",
        ["echo.quality_auto"] = "Auto",
        ["echo.quality_720"] = "720p",
        ["echo.quality_1080"] = "1080p",
        ["echo.settings_captions"] = "Sous-titres",
        ["echo.settings_autoplay"] = "Lancer la vidéo suivante automatiquement",
        ["echo.settings_software_render"] = "Rendu logiciel",

        // home screen management (added after update 2.3.4)
        ["os.home_menu_add_app"] = "Ajouter une app",
        ["os.home_menu_add_folder"] = "Ajouter un dossier",
        ["os.tile_menu_remove_app"] = "Retirer l'app",
        ["os.tile_menu_mark_seen"] = "Marquer comme vu",
        ["os.home_menu_mark_seen"] = "Marquer toutes les applis comme vues",
        ["os.tile_menu_take_out"] = "Sortir du dossier",
        ["os.tile_menu_move_to_folder"] = "Déplacer vers un dossier",
        ["os.tile_menu_remove_folder"] = "Retirer le dossier",
        ["os.folder_delete_title"] = "Retirer le dossier",
        ["os.folder_delete_body"] = "Retirer \"{0}\" et les {1} apps qu'il contient, ou garder les apps et les remettre sur l'écran d'accueil ?",
        ["os.folder_delete_remove"] = "Retirer le dossier et les apps",
        ["os.folder_delete_keep"] = "Garder les apps",

        // new app offer (added after update 2.3.4)
        ["os.new_apps_title"] = "Nouvelles applis disponibles",
        ["os.new_apps_body"] = "Cette mise à jour apporte de nouvelles applis. Choisissez celles que vous voulez sur votre écran d'accueil. Vous pourrez ajouter les autres plus tard depuis le menu de l'écran d'accueil.",
        ["os.new_apps_continue"] = "Continuer",
        ["os.app_levemetes_about"] = "Les petites annonces d'Éorzéa : proposez ce que vous avez, regardez ce que cherchent les autres.",
        ["os.app_market_about"] = "Les prix Universalis, l'historique des ventes et des alertes sur les objets que vous surveillez.",
        ["os.app_realtor_about"] = "Les parcelles libres sur tous les mondes, mises à jour dès qu'elles se libèrent.",
        ["os.app_wayfinder_about"] = "Retrouvez des points de repère dans le monde et gagnez des étincelles pour chaque trouvaille.",
        ["os.app_yapper_about"] = "Des messages courts et des photos, des abonnements, des réponses et des messages privés.",
        ["os.app_wallet_about"] = "Vos étincelles et toutes les monnaies de votre personnage, plafond compris.",
        ["os.app_store_about"] = "Dépensez vos étincelles en thèmes, anneaux d'avatar et autres babioles.",
        ["os.app_groove_about"] = "Une télécommande pour ce que joue votre PC, avec les volumes du jeu en prime.",
        ["os.app_echo_about"] = "Regardez des vidéos avec vos amis, tout le monde à la même seconde.",
        ["os.app_notes_about"] = "Des notes et des listes, qui ne quittent jamais cette machine.",
        ["os.app_together_about"] = "Créez ou rejoignez un groupe, invitez des amis et gagnez plus de sparks en jouant ensemble.",
        ["os.app_calculator_about"] = "Une calculatrice graphique, clavier compris.",
        ["os.app_timers_about"] = "La pêche en mer, le Cactpot et les autres horloges qui méritent un œil.",
        ["os.app_aetherling_about"] = "Accordez un Aethercore et élevez ce qui en éclot.",
        ["os.app_snake_about"] = "Le classique. Manger, grandir, ne pas se mordre.",
        ["os.app_stacker_about"] = "Empilez les blocs, videz les lignes, maudissez la dernière pièce.",
        ["os.app_breaker_about"] = "Faites rebondir la balle sur les briques jusqu'à la dernière.",
        ["os.app_meteor_about"] = "Abattez ce qui tombe avant que vos villes ne le reçoivent.",
        ["os.app_invaders_about"] = "Des rangées d'aliens descendent. Vous avez un canon.",
        ["os.app_muncher_about"] = "Videz le labyrinthe, évitez les fantômes, poursuivez-les quand vous le pouvez.",
        ["os.app_plappy_about"] = "Touchez pour battre des ailes. Les tuyaux ne pardonnent rien.",
        ["os.app_doom_about"] = "Le jeu de tir de 1993, tournant dans votre téléphone.",
        ["os.app_sudoku_about"] = "Neuf sur neuf, une grille fraîche quand vous voulez.",
        ["os.app_racooner_about"] = "Attrapez ce qui tombe et ramenez-le jusqu'aux terriers.",
        ["os.app_skyswarm_about"] = "Traversez l'essaim aussi longtemps que vous tenez.",
        ["os.app_eordle_about"] = "Un mot éorzéen par jour, six essais.",
        ["os.app_racer_about"] = "Inscris ton Lumi à des courses et gagne des sparks et des prix.",

        // together mode (added after update 2.4.0)
        ["os.party_title"] = "AetherParty",
        ["os.party_members"] = "{0}/{1}",
        ["os.party_start"] = "Créer un groupe",
        ["os.party_join"] = "Rejoindre",
        ["os.party_join_hint"] = "Code du groupe",
        ["os.party_code"] = "Code {0}",
        ["os.party_copied"] = "Copié !",
        ["os.party_leave"] = "Quitter le groupe",
        ["os.party_end"] = "Fermer le groupe",
        ["os.party_ended"] = "Le groupe est terminé.",
        ["os.party_dismiss"] = "D'accord",
        ["os.party_invite"] = "Inviter",
        ["os.party_error_full"] = "Ce groupe est complet.",
        ["os.party_error_kicked"] = "Vous avez été retiré de ce groupe.",
        ["os.party_error_in_party"] = "Vous êtes déjà dans un groupe.",
        ["os.party_error_not_found"] = "Aucun groupe avec ce code.",
        ["os.party_error_generic"] = "Cela n'a pas fonctionné. Réessayez.",
        ["os.party_invite_message"] = "{0} vous invite dans un groupe ! Ouvrez la page des widgets du téléphone et rejoignez avec le code {1}.",
        ["os.party_activity_echo"] = "Watch party en cours",
        ["os.party_activity_wayfinder"] = "Chasse de groupe en cours",
        ["os.party_activity_racer"] = "Course de Lumis en cours",
        ["os.party_activity_generic"] = "Activité en cours",
        ["os.party_activity_open"] = "Ouvrir",
        ["os.party_chat_title"] = "Chat du groupe",
        ["os.party_chat_hint"] = "Écrivez à votre groupe...",
        ["os.party_chat_empty"] = "Pas encore de messages. Dites bonjour !",
        // message translation (added after update 2.4.0)
        ["os.translate"] = "Traduire",
        ["os.translate_retry"] = "Traduire à nouveau",
        ["os.translate_pending"] = "Traduction...",
        ["os.translate_show_original"] = "Afficher l'original",
        ["os.translate_settings"] = "Paramètres de traduction",
        ["os.translate_consent_title"] = "Traduire les messages ?",
        ["os.translate_consent_body"] = "Les traductions viennent de Google Translate. Le texte que vous traduisez est envoyé par internet à Google, un tiers. Rien d'autre n'est envoyé. Rien n'est traduit sans votre demande.",
        ["os.translate_consent_enable"] = "Activer les traductions",
        ["os.translate_consent_cancel"] = "Pas maintenant",
        // translation onboarding + offer (added after update 2.4.0)
        ["os.translate_demo_source"] = "¡Hola! ¿Exploramos juntos?",
        ["os.translate_demo_result"] = "Salut ! On part explorer ensemble ?",
        ["os.translate_offer_title"] = "Traduisez n'importe quel message",
        ["os.translate_offer_body"] = "Cette mise à jour ajoute la traduction. Faites un clic droit sur un message, une bio de profil ou une publication, puis choisissez Traduire.",
        ["os.translate_offer_enable_go"] = "Activer et continuer",
        ["os.translate_offer_skip_go"] = "Continuer sans",
        ["os_onboarding.translate_title"] = "Comprenez tout le monde",
        ["os_onboarding.translate_body"] = "Vous pouvez traduire les chats, les profils et les publications dans votre langue. Faites un clic droit sur un texte et choisissez Traduire.",
        ["os_onboarding.translate_later"] = "Tout cela se change plus tard dans les paramètres, section Langues.",

        // together onboarding (added after update 2.4.0)
        ["os.party_intro_title_0"] = "Faire des choses ensemble",
        ["os.party_intro_body_0"] = "Un groupe vous réunit avec jusqu'à trois amis sur un même écran. Partagez le code et ils rejoignent. Quand l'un de vous lance une séance commune ou une chasse Wayfinder, tous les autres peuvent y entrer.",
        ["os.party_intro_title_1"] = "Discuter ensemble",
        ["os.party_intro_body_1"] = "Le chat du groupe s'installe sur une petite barre le long du téléphone. Les nouveaux messages y apparaissent sans rien ouvrir.",
        ["os.party_intro_title_2"] = "Emmenez votre Aetherling",
        ["os.party_intro_body_2"] = "Le mode groupe vous laisse partager votre Aetherling et voir ceux de votre groupe. Tout est sur consentement.",
        ["os.party_intro_pets_show"] = "Afficher les Aetherlings des membres du groupe",
        ["os.party_intro_pets_share"] = "Laisser le groupe voir le mien",
        ["os.party_intro_pets_size"] = "De quelle taille les voulez-vous ?",
        ["os.party_intro_f0_code"] = "Un seul code invite tout le monde : partagez-le, ils rejoignent.",
        ["os.party_intro_f0_activity"] = "Quand l'un de vous lance une séance commune ou une chasse Wayfinder, tous les autres peuvent y entrer.",
        ["os.party_intro_f0_size"] = "Jusqu'à quatre à la fois.",
        ["os.party_intro_f1_widget"] = "Gérez le groupe depuis sa carte sur la page des widgets du téléphone.",
        ["os.party_intro_f1_dock"] = "Les membres se tiennent à côté du téléphone : vous voyez d'un coup d'œil qui est là.",
        ["os.party_intro_f1_chat"] = "Discutez avec vos amis même s'ils sont sur d'autres serveurs ou centres de données.",
        ["os.party_intro_pets_show_hint"] = "Leurs Aetherlings se blottissent autour du vôtre, sur l'écran.",
        ["os.party_intro_pets_share_hint"] = "Les membres de vos groupes voient votre Aetherling à côté du leur.",
        ["os.party_in_party"] = "Actuellement dans un groupe · {0}",
        ["os.party_intro_next"] = "Continuer",
        ["os.party_intro_start"] = "Démarrer",
        ["os.party_pet_size_0"] = "XS",
        ["os.party_pet_size_1"] = "S",
        ["os.party_pet_size_2"] = "M",
        ["os.party_pet_size_3"] = "L",
        ["os.party_pet_size_4"] = "XL",

        // widget page (added after update 2.4.0)
        ["os.widget_add_new"] = "Ajouter un widget",
        ["os.widget_settings"] = "Réglages du widget",
        ["os.widget_remove"] = "Retirer ce widget",
        ["os.widget_clock"] = "Horloge",
        ["os.widget_status"] = "État",
        ["os.widget_notifications"] = "Notifications",
        ["os.widget_party"] = "AetherParty",

        // screenshot import consent (added after update 2.4.0)
        ["os.photos_screenshots_offer"] = "Ajouter vos captures d'écran du jeu à Photos ? Touchez ici pour choisir.",
        ["os.party_settings"] = "Paramètres AetherParty",
        ["os.party_kick_tip"] = "Retirer {0} du groupe",
        ["os.party_kick_title"] = "Retirer du groupe ?",
        ["os.party_kick_body"] = "{0} sera retiré du groupe et ne pourra plus rejoindre celui-ci.",
        ["os.party_kick_go"] = "Retirer",
        ["os.party_chat_joined"] = "{0} a rejoint le groupe",
        ["os.party_chat_wayfinder"] = "{0} a lancé une chasse Wayfinder. Touchez pour participer.",
        ["os.party_chat_racer"] = "{0} a lancé une course de Lumis. Touche pour rejoindre.",
        ["os.party_chat_echo"] = "{0} a ouvert un salon Echo. Touchez pour le rejoindre.",

        // listing boosts (added after update 2.5.2)
        ["os.boost_boosted"] = "Boosté",
        ["os.boost_featured"] = "À la une",
        ["os.boost_left"] = "Boosté, encore {0}",
        ["os.boost_left_count"] = "Il vous en reste {0}.",
        ["os.boost_none"] = "Vous n'avez aucun boost. Prenez-en un dans la Boutique.",
        ["os.boost_go"] = "Booster",
        ["os.boost_confirm_venue"] = "Booster ce lieu ?",
        ["os.boost_confirm_ad"] = "Booster cette annonce ?",
        ["os.boost_confirm_body"] = "Il passe tout en haut de la liste pendant 5 jours. Choisissez l'effet qu'il porte.",
        ["os.boost_confirm_extend"] = "Il est boosté encore {0}. Ceci ajoute 5 jours. Choisissez l'effet qu'il porte.",
        ["os.boost_style_0"] = "Aurore",
        ["os.boost_style_1"] = "Braise",
        ["os.boost_style_2"] = "Prisme",
        ["os.boost_style_3"] = "Lueur d'étoiles",
        ["os.boost_venue_action"] = "Booster ce lieu",
        ["os.boost_ad_action"] = "Booster cette annonce",
        ["os.boost_get"] = "Prendre un boost",
        ["os.boost_shelf"] = "Vos boosts",
        ["os.boost_pick"] = "Choisissez quoi booster",
        ["os.boost_no_targets"] = "Vous n'avez encore aucun lieu ni aucune annonce en ligne à booster.",
        ["os.boost_done"] = "Boosté pendant {0}.",
        ["os.boost_venues"] = "Lieux",
        ["os.boost_ads"] = "Annonces",

        // echo playlist import (added after update 2.5.3)
        ["echo.playlist_confirm"] = "Ajouter les {0} vidéos de cette playlist ?",
        ["echo.playlist_capped"] = "Cette playlist a {0} vidéos. Ajouter les {1} premières ?",
        ["echo.playlist_add_all"] = "Tout ajouter",
        ["echo.playlist_add_one"] = "Cette vidéo seulement",
        ["echo.playlist_reading"] = "Lecture de la playlist...",
        ["echo.playlist_failed"] = "Echo n'a pas pu lire cette playlist. Essayez le lien de la vidéo.",
        ["echo.playlist_added"] = "{0} vidéos ajoutées.",
        ["os.echo_home_watch_playlist"] = "Les playlists ne marchent que dans un salon. Créez ou rejoignez un salon d'abord.",

        // phone shell menu (added after update 2.5.3)
        ["os.phone_menu_exit"] = "Éteindre le téléphone",
        ["os.phone_menu_minimize"] = "Réduire le téléphone",
        ["os.phone_menu_open"] = "Ouvrir le téléphone",
        ["os.phone_menu_lock"] = "Verrouiller la position",
        ["os.phone_menu_unlock"] = "Déverrouiller la position",
        // echo live streams (added after update 2.5.3)
        ["echo.live"] = "EN DIRECT",
        ["echo.live_needs_player_title"] = "Les directs demandent un lecteur plus récent",
        ["echo.live_needs_player_body"] = "Ce lecteur ne peut pas lire les directs. Les vidéos normales fonctionnent toujours.",
        ["echo.live_needs_player_update"] = "Un lecteur plus récent est prêt. Installez-le pour regarder les directs.",
    };
}
