namespace AetherLove.Services.Localization;

internal static class SettingsFr
{
    public static readonly System.Collections.Generic.Dictionary<string, string> Strings = new()
    {
        // Settings

        ["settings.section_plugin_settings"] = "Paramètres du plugin",
        ["settings.section_phone_size"] = "Taille du téléphone",
        ["settings.section_plugin_language"] = "Langue du plugin",
        ["settings.section_general"] = "Paramètres généraux",
        ["settings.section_notifications"] = "Notifications",
        ["settings.section_other"] = "Autre",
        ["settings.section_danger_zone"] = "Zone de danger",
        ["settings.menu_language_theme"] = "Langue et thème",
        ["settings.menu_appearance"] = "Apparence du téléphone",
        ["settings.menu_chat_colors"] = "Apparence du chat",
        ["settings.section_theme"] = "Thème",
        ["settings.back_arrow"] = "← Retour",
        ["settings.chat_own_bg"] = "Fond de vos messages",
        ["settings.chat_own_fg"] = "Texte de vos messages",
        ["settings.chat_peer_bg"] = "Fond des messages du contact",
        ["settings.chat_peer_fg"] = "Texte des messages du contact",
        ["settings.chat_reset"] = "Réinitialiser",

        ["settings.phone_size_small"] = "Petite",
        ["settings.phone_size_medium"] = "Moyenne",
        ["settings.phone_size_large"] = "Grande",
        ["settings.phone_size_xl"] = "XL",
        ["settings.phone_size_xxl"] = "XXL",
        ["settings.phone_size_caption"] = "Met à l'échelle l'ensemble du téléphone. XS convient aux petits écrans et au mode fenêtré ; les grandes tailles conviennent aux écrans haute résolution, et XL et XXL sont prévus pour la 4K.",
        ["settings.section_mini_phone_size"] = "Taille du téléphone miniature",
        ["settings.mini_phone_size_caption"] = "Taille de la bulle réduite (affichée lorsque le téléphone est réduit). L'aperçu ci-dessous montre la taille sélectionnée.",

        ["settings.confirm_before_close"] = "Confirmer avant de fermer le téléphone",

        ["settings.view_changelog"] = "Voir le journal des modifications",
        ["settings.send_feedback"] = "Envoyer un commentaire",
        ["settings.terms_of_service"] = "Conditions d'utilisation",
        ["settings.cancel"] = "Annuler",

        ["settings.always_blur_nsfw"] = "Toujours flouter le NSFW",
        ["settings.always_blur_nsfw_tooltip"] = "Lorsque cette option est activée, les photos supplémentaires marquées NSFW dans les autres profils sont floutées jusqu'à ce que vous cliquiez pour les révéler une par une. Les avatars et les portraits principaux sont toujours safe-for-work, quoi qu'il arrive. Désactiver cette option affiche chaque photo telle quelle.",
        ["settings.nsfw_profile"] = "Mon profil est NSFW (18+)",
        ["settings.nsfw_profile_tooltip"] = "Marque votre profil comme adulte/NSFW afin qu'il ne soit visible que par les personnes ayant activé le NSFW. Il s'active automatiquement lorsque vous ajoutez des photos NSFW ou choisissez le roleplay 18+, et reste activé jusqu'à ce que vous les retiriez.",
        ["settings.nsfw_profile_locked"] = "Vous ne pouvez pas le désactiver tant que vous avez des photos NSFW ou le roleplay 18+ (ERP) sélectionné. Retirez d'abord vos images NSFW et désélectionnez le roleplay 18+.",

        ["settings.enable_notifications"] = "Activer les notifications",
        ["settings.enable_notifications_tooltip"] = "Interrupteur principal pour toutes les notifications. Désactivez-le pour faire taire toutes les annonces dans le chat de jeu, les fenêtres contextuelles et les sons ci-dessous.",
        ["settings.enable_notification_sounds"] = "Activer les sons de notification",
        ["settings.enable_notification_sounds_tooltip"] = "Les sons de notification ne seront diffusés que si l'audio de votre jeu et l'audio des effets spéciaux ne sont pas coupés. Le réglage du volume se fait via le volume de Windows.",
        ["settings.announce_messages_chat"] = "Annoncer les nouveaux messages dans le chat de jeu",
        ["settings.announce_matches_chat"] = "Annoncer les nouvelles correspondances dans le chat de jeu",
        ["settings.popup_messages"] = "Afficher une fenêtre contextuelle pour les nouveaux messages",
        ["settings.popup_matches"] = "Afficher une fenêtre contextuelle pour les nouvelles correspondances",
        ["settings.hide_notifications_in_combat"] = "Masquer les notifications en combat",
        ["settings.hide_notifications_in_combat_tooltip"] = "Lorsque cette option est activée, vous ne recevez aucune notification (annonces dans le chat de jeu, fenêtres contextuelles ou sons) tant que vous êtes en combat.",
        ["settings.auto_open_minimized"] = "Ouvrir automatiquement en mode réduit à la connexion",
        ["settings.pulse_optout"] = "Reçois d'incroyables messages de l'équipe Aethernet pour te rappeler de swiper",
        ["settings.pulse_optout_tooltip"] = "De temps en temps, AetherLove peut glisser un message amusant dans votre chat de jeu. Désactivez pour les arrêter.",
        ["settings.combat_behavior"] = "En combat",
        ["settings.combat_behavior_hide"] = "Masquer le téléphone",
        ["settings.combat_behavior_minimize"] = "Réduire en bulle",
        ["settings.combat_behavior_leave_open"] = "Laisser ouvert",
        ["settings.notification_sound"] = "Son de notification",
        ["settings.play"] = "Écouter",

        ["settings.delete_bullet_matches"] = "Toutes vos correspondances seront supprimées.",
        ["settings.delete_bullet_preferences"] = "Vos préférences de correspondance seront effacées.",
        ["settings.delete_bullet_pictures"] = "Vos photos de profil seront supprimées.",
        ["settings.delete_previous_failed"] = "La tentative précédente a échoué : {0}",

        ["settings.deleting_title"] = "Suppression du compte",
        ["settings.deleting_body"] = "Suppression de vos données et annulation des correspondances",

        ["settings.warnings_title"] = "Avertissements du compte",
        ["settings.no_warnings"] = "Aucun avertissement enregistré.",

        // Moderator messages
        ["settings.modmsg_title"] = "Messages du modérateur",
        ["settings.no_modmsg"] = "Aucun message enregistré.",
        ["settings.back_to_settings_arrow"] = "← Retour aux paramètres",

        ["settings.back_to_settings"] = "Retour aux paramètres",
        ["settings.feedback_thanks"] = "Merci ! Votre commentaire a été envoyé à l'équipe d'AetherLove.",
        ["settings.feedback_intro"] = "Vous avez trouvé un bug, vous avez une idée ou une suggestion ? Faites-le-nous savoir.",
        ["settings.feedback_note"] = "À noter : les commentaires ne peuvent pas servir à contester un bannissement ou un avertissement.",
        ["settings.feedback_type"] = "Type",
        ["settings.feedback_kind_bug"] = "Bug",
        ["settings.feedback_kind_improvement"] = "Amélioration",
        ["settings.feedback_kind_other"] = "Autre",
        ["settings.feedback_your_message"] = "Votre message",
        ["settings.sending"] = "Envoi…",
        ["settings.submit"] = "Envoyer",
        ["settings.feedback_rate_limited"] = "Vous ne pouvez envoyer un commentaire que {0} fois par heure. Veuillez réessayer plus tard.",
        ["settings.feedback_send_failed"] = "Impossible d'envoyer votre commentaire. Veuillez réessayer.",

        ["settings.contributors"] = "Contributeurs",
        ["settings.contributors_thanks_title"] = "Merci",
        ["settings.contributors_intro"] = "AetherLove ne serait pas possible sans :",
        ["settings.contributors_leads"] = "Responsables du projet : Astraea & Nihal",
        ["settings.contributors_council"] = "The Chon-Chon Council",
        ["settings.contributors_moderation"] = "Modération : Su",
        ["settings.contributors_translators"] = "Traducteurs : Tears, Mufami, Terashi, Su, Astraea",
        ["settings.contributors_xivauth"] = "XIVAuth by KazWolfe",
        ["settings.contributors_punish"] = "Puni.sh",
        ["settings.contributors_dalamud"] = "The Dalamud project",
        ["settings.contributors_testers"] = "Tous les merveilleux bêta-testeurs à travers Éorzéa.",

        // added after update 1.4.0
        ["settings.lock_position"] = "Verrouiller la position",
        ["settings.lock_position_caption"] = "En verrouillant la position, vous ne pourrez plus déplacer le téléphone (grand et mini) ; ils resteront figés en place.",

        // added after update 1.4.3
        ["settings.show_during_gpose"] = "Afficher le téléphone pendant la pose de groupe",
        ["settings.show_during_gpose_tooltip"] = "Garde le téléphone visible pendant la pose de groupe (/gpose) et remplace le réglage de Dalamud qui masque les fenêtres des plugins pendant la pose de groupe.",
        ["settings.hide_during_cutscene"] = "Afficher le téléphone pendant les cinématiques",
        ["settings.hide_during_cutscene_tooltip"] = "Garde le téléphone visible pendant une cinématique. Désactivé, il est masqué pendant les cinématiques (par défaut).",
        ["settings.tomestone_emote"] = "Afficher l'emote de tomestone en utilisant l'appli",
        ["settings.tomestone_emote_tooltip"] = "Tant que le téléphone est ouvert, ton personnage joue l'emote /tomescroll, comme s'il le lisait. Ne démarre qu'en zone sûre et n'interrompt jamais une autre emote.",

        // added after update 1.5.0
        ["settings.menu_supporter"] = "Soutien",
        ["settings.supporter_link_button"] = "Lier le compte Patreon",
        ["settings.supporter_contacting"] = "Connexion au serveur...",
        ["settings.supporter_awaiting_browser"] = "Terminez la liaison dans votre navigateur, puis revenez ici.",
        ["settings.supporter_open_again"] = "Rouvrir le navigateur",
        ["settings.supporter_cancel"] = "Annuler",
        ["settings.supporter_you_are_title"] = "Vous êtes Supporter",
        ["settings.supporter_you_are_body"] = "Votre compte Patreon a été lié avec succès et votre statut de Supporter est activé.",
        ["settings.supporter_nomember_title"] = "Aucun abonnement trouvé",
        ["settings.supporter_nomember_body"] = "Votre compte Patreon a été lié, mais aucun abonnement actif n'a été trouvé. Si vous venez de vous engager, votre statut de Supporter est accordé automatiquement en quelques heures. Vous pouvez aussi délier le compte et réessayer une fois votre abonnement actif sur Patreon.",
        ["settings.supporter_not_entitled"] = "Aucun abonnement actif trouvé pour l'instant. Si vous venez de vous abonner, votre rôle sera attribué automatiquement d'ici quelques heures.",
        ["settings.supporter_unlink_button"] = "Délier Patreon",
        ["settings.supporter_unlink_confirm"] = "Délier ce compte Patreon ? Votre rôle de Soutien sera retiré.",
        ["settings.supporter_failed"] = "La liaison a échoué. Veuillez réessayer.",
        ["settings.supporter_retry"] = "Réessayer",
        ["settings.supporter_unavailable"] = "La liaison de soutien est actuellement indisponible. Veuillez réessayer plus tard.",
        ["settings.supporter_link_expired"] = "La demande de liaison a expiré. Veuillez réessayer.",

        // added after update 1.5.1
        ["settings.supporter_linked"] = "Lié",
        ["settings.supporter_title"] = "Devenez un soutien",
        ["settings.supporter_intro"] = "Vous pouvez soutenir le projet financièrement via notre Patreon. Chaque fonctionnalité d'AetherLove est gratuite pour tout le monde, et rien n'est ni ne sera jamais bloqué derrière un paywall. Les soutiens reçoivent simplement un grand merci : des limites plus souples et quelques extras scintillants, notre façon de dire qu'on n'y arriverait pas sans vous.",
        ["settings.supporter_perks_header"] = "Avantages AetherLove",
        ["settings.supporter_msgr_perks_header"] = "Avantages Messenger",
        ["settings.supporter_perk_msgr_groups_title"] = "Grands chats de groupe",
        ["settings.supporter_perk_msgr_groups_body"] = "Ajoute des amis à l'infini par code, garde jusqu'à 10 chats de groupe en même temps et réunis jusqu'à 15 personnes dans chacun.",
        ["settings.supporter_perk_msgr_storage_title"] = "Plus de stockage Messenger",
        ["settings.supporter_perk_msgr_storage_body"] = "Plus de place pour les selfies et photos que tu partages, et des délais d'expiration plus longs avant leur suppression.",
        ["settings.supporter_perk_profiles_title"] = "Deux profils",
        ["settings.supporter_perk_profiles_body"] = "Utilise deux profils AetherLove en parallèle, idéal pour jongler entre plusieurs OC ou séparer ton RP et ton hors-RP.",
        ["settings.supporter_perk_photos_title"] = "Plus de place pour briller",
        ["settings.supporter_perk_photos_body"] = "Jusqu'à 5 photos de profil supplémentaires, et 2 de plus par personnage RP.",
        ["settings.supporter_perk_superlike_title"] = "Superlike",
        ["settings.supporter_perk_superlike_body"] = "Faites savoir à quelqu'un qu'il vous a vraiment tapé dans l'œil. La personne est notifiée que vous lui avez envoyé un Superlike, et si elle vous like en retour, vous matchez aussitôt.",
        ["settings.supporter_perk_rewinds_title"] = "5 retours par jour",
        ["settings.supporter_perk_rewinds_body"] = "Swipé trop vite ? Revenez en arrière jusqu'à 5 fois par jour au lieu d'une seule.",
        ["settings.supporter_perk_analytics_title"] = "Des statistiques plus poussées",
        ["settings.supporter_perk_analytics_body"] = "Des analyses et statistiques supplémentaires sur qui vous aime et comment votre profil performe vraiment.",
        ["settings.supporter_perk_colors_title"] = "Couleurs vivantes",
        ["settings.supporter_perk_colors_body"] = "Votre nom scintille comme un arc-en-ciel, changeant lentement de couleurs impossibles à ignorer.",
        ["settings.supporter_perk_badge_title"] = "Insigne de Soutien",
        ["settings.supporter_perk_badge_body"] = "Un badge Soutien et une petite étoile à côté de votre nom. Ce petit plus, mérité.",
        ["settings.supporter_how_heading"] = "Comment ça marche",
        ["settings.supporter_how_intro"] = "Nous proposons trois paliers à des prix différents pour que vous choisissiez ce qui vous convient, et chaque palier débloque exactement les mêmes avantages. Aucun palier n'en obtient plus qu'un autre.",
        ["settings.supporter_step1_title"] = "1. Abonnez-vous sur Patreon",
        ["settings.supporter_step1_body"] = "Créez un compte Patreon et abonnez-vous à l'un de nos paliers de soutien, ils débloquent tous les mêmes avantages.",
        ["settings.supporter_step2_title"] = "2. Liez-le à AetherLove",
        ["settings.supporter_step2_body"] = "Liez votre compte Patreon en cliquant sur le bouton ci-dessous. Si vous avez un abonnement actif, votre compte passe premium aussitôt.",
        ["settings.supporter_become"] = "Devenez un Soutien sur Patreon",
        ["settings.supporter_data_note"] = "Nous ne conservons que votre identifiant Patreon et le fait que vous êtes membre de notre campagne. Nous ne conservons jamais votre nom, votre e-mail ni vos comptes sociaux.",
        ["settings.sup_learn_title"] = "Soutenez AetherLove",
        ["settings.sup_learn_body"] = "Cette personne soutient AetherLove. Envie de voir ce que le soutien au projet vous apporte ? Photos supplémentaires, superlikes, styles de nom, statistiques bonus et plus encore.",
        ["settings.sup_learn_more"] = "Plus d'infos",

        ["settings.sup_thanks_title"] = "Vous êtes Supporter !",
        ["settings.sup_thanks_sub"] = "Merci de soutenir AetherLove !",
        ["settings.sup_thanks_body"] = "Votre soutien fait tourner les serveurs. Profitez de vos nouveaux avantages !",
        ["settings.sup_thanks_continue"] = "Continuer",
        // AetherLove-app notification master (added after update 1.5.1)
        ["settings.enable_aetherlove_notifications"] = "Activer les notifications AetherLove",
        ["settings.menu_nsfw"] = "Paramètres NSFW",
        // DTR server-info-bar entries (added after update 1.5.1)
        ["dtr.chats"] = "Messages",
        ["dtr.matches"] = "Matchs",
        ["dtr.news"] = "Actus",
        ["settings.show_dtr_count"] = "Afficher les compteurs de non-lus dans la barre d'info serveur",
        ["settings.show_dtr_count_tooltip"] = "Ajoute des entrées AetherLove (messages, matchs, actus) à la barre d'info serveur du jeu, à côté des FPS et du ping. Chacune affiche son nombre de non-lus et se masque quand il n'y a rien de nouveau. Vous pouvez aussi masquer des entrées individuelles dans les paramètres de la barre d'info serveur de Dalamud.",

        // Multi-profile: the profile picker, switching, and delete-profile (added after update 1.5.1)
        ["settings.menu_switch_profile"] = "Changer de profil",
        ["settings.delete_profile"] = "Supprimer le profil",
        ["settings.delete_profile_warning_intro"] = "La suppression de ce profil AetherLove est définitive. Avant de continuer, voici exactement ce qui se passe :",
        ["settings.delete_bullet_profile"] = "Ce profil de rencontre est supprimé et ne peut pas être restauré.",
        ["settings.delete_profile_account_stays"] = "Votre compte AetherOS et vos autres applications ne sont pas affectés. Vous pouvez créer un nouveau profil à tout moment.",
        ["picker.title"] = "Choisir un profil",
        ["picker.subtitle"] = "Qui swipe aujourd'hui ?",
        ["picker.current"] = "Profil actuel",
        ["picker.banned"] = "Banni",
        ["picker.finish_setup"] = "Terminer la configuration",
        ["picker.locked"] = "Emplacement supporter",
        ["picker.create"] = "Nouveau profil",
        ["picker.create_sub"] = "Commencer un nouveau profil de rencontre",
        ["picker.create_secondary"] = "Créer un profil secondaire",
        ["picker.create_supporter_pitch"] = "Un second profil AetherLove est un avantage supporter. Soutenez le projet pour débloquer une autre identité de rencontre, avec ses propres matchs et conversations, totalement séparée de la première.",
        ["picker.locked_supporter_pitch"] = "Ce profil occupe un emplacement supporter. Renouvelez votre statut de supporter pour le rouvrir ; rien n'a été supprimé, il est seulement verrouillé.",
        ["picker.switching"] = "Changement de profil...",
        ["picker.switch_failed"] = "Le changement de profil a échoué. Veuillez réessayer.",
        ["picker.share_as_title"] = "Partager en tant que...",
        ["picker.share_as_body"] = "Quel profil doit partager ceci ?",
        ["picker.share_as_current"] = "{0} (actuel)",

        // Messenger (added after update 1.5.1)
        ["dtr.messenger"] = "Messenger",

        // added after update 2.0.0.0
        ["settings.section_time_format"] = "Format de l'heure",
        ["settings.time_24h"] = "24 heures",
        ["settings.time_12h"] = "12 heures",

        // added after update 2.0.1
        ["settings.audio_sounds_off"] = "Les sons de notification sont actuellement désactivés.",
        ["settings.audio_sounds_enable"] = "Activer les sons de notification",
        ["settings.audio_volume"] = "Volume des notifications",
        ["settings.audio_device"] = "Périphérique de sortie",
        ["settings.audio_device_default"] = "Défaut du système",
        ["settings.audio_test"] = "Jouer un son de test",
        ["settings.audio_test_ok"] = "Lecture en cours ! Si vous n'entendez rien, essayez un autre périphérique de sortie ci-dessus.",
        ["settings.font_header"] = "Police",
        ["settings.font_caption"] = "S'applique à tout le texte du téléphone. Les caractères absents d'une police utilisent la police par défaut.",
        ["settings.font_default"] = "Par défaut",
        ["settings.phone_size_header"] = "Taille du téléphone",
        ["settings.mini_phone_size_header"] = "Taille miniature",

        // added after update 2.1.3
        ["settings.staff_notices_title"] = "Messages de l'équipe",
        ["settings.staff_notices_empty"] = "Rien de la part de l'équipe pour l'instant.",
        ["settings.staff_warnings_section"] = "Avertissements",
        ["settings.staff_messages_section"] = "Messages",

        // added after update 2.2.3
        ["settings.premium_themes"] = "Thèmes premium",
        ["settings.premium_refresh"] = "Recharger ce thème",
        ["settings.premium_backgrounds"] = "Fonds premium",
        ["settings.premium_enable_failed"] = "Changement impossible",
        ["settings.phone_size_xs"] = "XS",
        ["settings.supporter_store_perks_header"] = "Dans la boutique",
        ["settings.supporter_perk_store_title"] = "10% de réduction en boutique",
        ["settings.supporter_perk_store_body"] = "Les Supporters paient 10% de moins sur chaque achat en boutique, en plus des soldes en cours.",

        // Timers (added after update 2.3.3)
        ["dtr.timers"] = "{0} {1}",
    };
}
