namespace AetherLove.Services.Localization;

internal static class HubErrorsRu
{
    public static readonly System.Collections.Generic.Dictionary<string, string> Strings = new()
    {
        ["huberror.generic"] = "Произошла непредвиденная ошибка сервера.",
        ["huberror.generic_detail"] = "Произошла ошибка: {0}",
        ["huberror.invalid_request"] = "Сервер отклонил запрос. Если это повторяется, проверьте наличие обновления плагина.",
        ["huberror.unauthenticated"] = "Ваша сессия больше недействительна. Пожалуйста, войдите снова.",
        ["huberror.banned"] = "Этот профиль AetherLove заблокирован.",
        ["huberror.account_banned"] = "Ваш аккаунт заблокирован.",
        ["huberror.rate_limited"] = "Вы делаете это слишком часто. Попробуйте снова чуть позже.",
        ["huberror.profile_not_found"] = "Профиль не найден.",
        ["huberror.profile_not_visible"] = "Этот профиль недоступен.",
        ["huberror.deck_expired"] = "Этого профиля больше нет в вашей колоде. Обновите колоду и попробуйте снова.",
        ["huberror.no_active_match"] = "У вас больше нет пары с этим игроком.",
        ["huberror.peer_keys_missing"] = "Этот пользователь ещё не настроил E2E-шифрование и пока не может общаться в чате. Попробуйте позже.",
        ["huberror.key_bundle_exists"] = "Ключи шифрования для этого аккаунта уже настроены.",
        ["huberror.message_too_large"] = "Это сообщение слишком длинное для отправки.",
        ["huberror.bio_too_long"] = "Ваша анкета превышает лимит в {0} символов.",
        ["huberror.lalafell_erp"] = "Ролевые игры для взрослых недоступны для персонажей-лалафелей.",
        ["huberror.lalafell_nsfw"] = "Функции NSFW недоступны для персонажей-лалафелей.",
        ["huberror.lalafell_nsfw_photo"] = "Фотографии NSFW недоступны для персонажей-лалафелей.",
        ["huberror.nsfw_disable_blocked"] = "Удалите фотографии NSFW и отключите ролевые игры 18+, прежде чем отключать NSFW.",
        ["huberror.img_too_large"] = "Изображение слишком большое ({0} МБ). Максимум: {1} МБ.",
        ["huberror.img_dimensions_too_large"] = "Изображение слишком большое ({0}×{1}). Длинная сторона может быть не более {2}px.",
        ["huberror.img_crop_too_small"] = "Область обрезки слишком мала (минимум {0}px с каждой стороны).",
        ["huberror.img_decode_failed"] = "Не удалось прочитать изображение. Поддерживаемые форматы: PNG, JPEG, WebP, GIF.",
        ["huberror.img_payload_invalid"] = "Не удалось загрузить фотографию. Пожалуйста, выберите изображение ещё раз.",
        ["huberror.report_self"] = "Вы не можете пожаловаться на самого себя.",
        ["huberror.report_reason_required"] = "Пожалуйста, опишите проблему.",
        ["huberror.report_reason_too_long"] = "Причина слишком длинная (максимум {0} символов).",
        ["huberror.report_target_gone"] = "Этот профиль больше не существует.",
        ["huberror.report_duplicate"] = "Вы уже недавно жаловались на этого пользователя. Команда модераторов сейчас в процессе ее расмотра.",
        ["huberror.feedback_required"] = "Пожалуйста, введите сообщение перед отправкой.",
        // added after update (1.3.1)
        ["huberror.reswipe_nothing_to_undo"] = "Нечего отменять.",
        ["huberror.reswipe_already_matched"] = "Нельзя отменить свайп по профилю, с которым у вас уже есть пара.",
        ["huberror.reswipe_quota_exhausted"] = "Вы уже использовали отмену на сегодня.",
        ["huberror.superlike_quota_exhausted"] = "Вы уже использовали все суперлайки на сегодня.",

        // added after update 1.4.3
        ["huberror.character_limit_reached"] = "У вас может быть не более {0} RP-персонажей.",
        ["huberror.character_name_invalid"] = "Имя персонажа должно быть от 3 до 50 символов.",
        ["huberror.character_not_found"] = "Этот персонаж больше не существует. Обновите и попробуйте снова.",

        // added after update 1.5.0
        ["huberror.patreon_disabled"] = "Привязка Patreon сейчас недоступна.",
        ["huberror.patreon_already_linked"] = "К вашему профилю уже привязан аккаунт Patreon.",
        ["huberror.patreon_not_linked"] = "К вашему профилю не привязан аккаунт Patreon.",
        ["huberror.patreon_account_taken"] = "Этот аккаунт Patreon уже привязан к другому аккаунту AetherLove.",
        ["huberror.patreon_link_failed"] = "Не удалось завершить привязку Patreon. Попробуйте ещё раз.",
        ["huberror.places_disabled"] = "Раздел «Места» сейчас недоступен.",
        ["huberror.venue_not_found"] = "Это заведение больше не существует.",
        ["huberror.venue_limit_reached"] = "Вы достигли лимита в {0} заведений.",
        ["huberror.venue_name_invalid"] = "Название заведения должно содержать от 3 до 60 символов.",
        ["huberror.venue_description_too_long"] = "Описание превышает лимит в {0} символов.",
        ["huberror.venue_times_invalid"] = "Одно из расписаний работы недопустимо.",
        ["huberror.venue_times_too_many"] = "У заведения может быть не более {0} расписаний работы.",
        ["huberror.venue_review_own"] = "Нельзя оставить отзыв о собственном заведении.",
        ["huberror.venue_review_too_long"] = "Ваш отзыв превышает лимит в {0} символов.",
        ["huberror.venue_review_rating_invalid"] = "Выберите оценку от 1 до 5 звёзд.",
        ["huberror.venue_rsvp_invalid"] = "На это открытие больше нельзя записаться.",

        // Multi-profile (added after update 1.5.1)
        ["huberror.profile_locked"] = "Этот профиль занимает слот для саппортеров и сейчас заблокирован.",
        ["huberror.profile_limit_reached"] = "Вы достигли лимита профилей.",

        // Messenger (added after update 1.5.1)
        ["huberror.messenger_disabled"] = "Messenger временно недоступен.",
        ["huberror.msgr_code_not_found"] = "Пользователь с таким кодом не найден.",
        ["huberror.msgr_self"] = "Это ваш собственный код.",
        ["huberror.msgr_already_contact"] = "Вы уже в контактах друг у друга.",
        ["huberror.msgr_request_pending"] = "Ваша заявка ещё ожидает ответа.",
        ["huberror.msgr_contact_limit"] = "Вы достигли лимита контактов ({0}).",
        ["huberror.msgr_pending_limit"] = "Слишком много исходящих заявок (макс. {0}).",
        ["huberror.msgr_not_contact"] = "Вы не в контактах с этим пользователем.",
        ["huberror.msgr_group_limit"] = "Вы можете владеть не более чем {0} группами.",
        ["huberror.msgr_group_full"] = "В группе может быть не более {0} участников.",
        ["huberror.msgr_not_owner"] = "Это может сделать только владелец группы.",
        ["huberror.msgr_not_member"] = "Вы не участник этой группы.",
        ["huberror.msgr_group_name_invalid"] = "Это название группы нельзя использовать.",
        ["huberror.msgr_adds_disabled"] = "Этот пользователь не принимает заявки в контакты.",
        ["huberror.msgr_keys_missing"] = "Ключи шифрования устарели; повторите попытку через мгновение.",
        ["huberror.msgr_image_rejected"] = "Это изображение нельзя отправить. Выбери другое изображение или напиши в поддержку, если считаешь это ошибкой.",
        ["huberror.msgr_storage_full"] = "Хранилище изображений заполнено. Удали часть изображений или дождись, пока старые исчезнут, и попробуй снова.",
        ["huberror.msgr_image_too_large"] = "Это изображение слишком большое.",
        ["huberror.msgr_image_invalid"] = "Не удалось прочитать это изображение.",
        // levemetes (added after update 2.0.1)
        ["huberror.levemetes_disabled"] = "Levemetes сейчас отключён.",
        ["huberror.leve_not_found"] = "Это объявление больше не существует.",
        ["huberror.leve_invalid"] = "Не удалось сохранить объявление. Проверьте введённые данные.",
        ["huberror.leve_limit_reached"] = "У вас уже {0} объявлений. Удалите одно или дождитесь, пока какое-то истечёт.",
        ["huberror.leve_too_long"] = "Текст слишком длинный (не больше {0} символов).",
        ["huberror.leve_image_rejected"] = "Это изображение нельзя загрузить. Выберите другое или напишите в поддержку, если считаете это ошибкой.",
        ["huberror.leve_review_own"] = "Нельзя оставить отзыв на собственное объявление.",
        ["huberror.leve_review_too_long"] = "Ваш отзыв слишком длинный (не больше {0} символов).",
        ["huberror.leve_review_rating_invalid"] = "Выберите оценку от 1 до 5 звёзд.",
        ["huberror.leve_reviews_disabled"] = "Автор отключил отзывы в этом объявлении.",
        ["huberror.leve_renew_too_soon"] = "Это объявление недавно продлевали. Попробуйте позже.",
        // holiday mode (added after update 2.0.1)
        // wayfinder (added after update 2.1.3)
        ["huberror.wayfinder_disabled"] = "Wayfinder сейчас отключён.",
        ["huberror.wayfinder_no_challenges"] = "Сейчас испытаний нет. Загляните позже!",
        ["huberror.wayfinder_no_reachable"] = "Все оставшиеся испытания в зонах, которые вы ещё не открыли. Настройтесь на новые этериты и возвращайтесь!",
        ["huberror.wayfinder_daily_limit"] = "Вы использовали все {0} запусков на сегодня.",
        ["huberror.wayfinder_active_exists"] = "У вас уже есть активное испытание.",
        ["huberror.wayfinder_no_active"] = "Это испытание больше не активно.",
        ["huberror.wayfinder_expired"] = "Время вышло! Это испытание истекло.",
        ["huberror.wayfinder_not_scout"] = "У вас нет прав на добавление точек.",
        ["huberror.wayfinder_invalid"] = "Не удалось сохранить точку. Проверьте введённые данные.",
        ["huberror.wayfinder_image_rejected"] = "Это фото загрузить нельзя. Сделайте другое или напишите в поддержку, если считаете это ошибкой.",
        ["huberror.holiday_message_too_long"] = "Сообщение об отпуске слишком длинное (не больше {0} символов).",
        ["huberror.holiday_message_invalid"] = "Это сообщение нельзя использовать. Пожалуйста, перефразируйте его.",
        // yapper (added after update 2.1.3)
        ["huberror.yapper_disabled"] = "Yapper сейчас отключён.",
        ["huberror.yapper_no_profile"] = "Сначала настройте свой профиль Yapper.",
        ["huberror.yapper_banned"] = "Сейчас вы не можете публиковать записи. Свяжитесь с поддержкой, если считаете это ошибкой.",
        ["huberror.yapper_handle_taken"] = "Этот ник уже занят.",
        ["huberror.yapper_handle_invalid"] = "Ник должен содержать от 3 до 20 символов: буквы, цифры и нижнее подчёркивание.",
        ["huberror.yapper_handle_rejected"] = "Этот ник нельзя использовать. Пожалуйста, выберите другой.",
        ["huberror.yapper_profile_rejected"] = "Этот текст нельзя использовать в профиле. Пожалуйста, перефразируйте его.",
        ["huberror.yapper_rename_too_soon"] = "Вы недавно меняли ник. Попробуйте снова через {0} дн.",
        ["huberror.yapper_blocked"] = "Вы не можете взаимодействовать с этим пользователем.",
        ["huberror.yap_not_found"] = "Этот яп больше не существует.",
        ["huberror.yap_too_long"] = "Слишком длинный яп (не больше {0} символов).",
        ["huberror.yap_too_many_images"] = "В одном япе может быть не больше {0} картинок.",
        ["huberror.yap_image_rejected"] = "Эту картинку нельзя опубликовать. Выберите другую или свяжитесь с поддержкой, если считаете это ошибкой.",
        ["huberror.yap_image_too_large"] = "Эта картинка слишком большая.",
        ["huberror.yap_image_invalid"] = "Не удалось прочитать эту картинку.",
        ["huberror.yap_embed_invalid"] = "Этот контент больше недоступен.",
        ["huberror.yap_edit_window_closed"] = "Время редактирования этого япа истекло.",
        ["huberror.yap_nsfw_mismatch"] = "Ваш рейтинг контента не позволяет этого.",
        ["huberror.yap_invalid"] = "Не удалось сохранить яп. Проверьте введённые данные.",
        ["huberror.yap_dm_not_allowed"] = "Этот пользователь не может получать ваши сообщения.",
        ["huberror.yap_dm_keys_missing"] = "@{0} ещё не закончил настройку. Попробуйте написать чуть позже.",
    };
}
