namespace AetherLove.Services.Localization;

internal static class ChatEn
{
    public static readonly System.Collections.Generic.Dictionary<string, string> Strings = new()
    {
        ["chat.no_conversation_selected"] = "No conversation selected.",
        ["chat.unreadable_message"] = "[unreadable message]",
        ["chat.report_submitted_toast"] = "Report submitted. Our moderation team will review it.",
        ["chat.view_profile"] = "View profile",
        ["chat.back_to_matches"] = "Back to matches",
        ["chat.menu_open_profile"] = "Open profile",
        ["chat.menu_copy_message"] = "Copy message",
        ["chat.menu_pin"] = "Pin chat",
        ["chat.menu_unpin"] = "Unpin chat",
        ["chat.menu_unmatch"] = "Unmatch",
        ["chat.menu_block"] = "Block",
        ["chat.menu_report_user"] = "Report User",
        ["chat.unmatch_title"] = "Unmatch",
        ["chat.unmatch_body"] = "When you unmatch with this player, the chat will be hidden from both people. If you re-match later, your history will reappear.",
        ["chat.unmatch_confirm"] = "Unmatch",
        ["chat.block_title"] = "Block User",
        ["chat.block_body"] = "When you block a user, the chat will be hidden from both people and they will not appear in your matches in the future.",
        ["chat.block_confirm"] = "Block",
        ["chat.cancel"] = "Cancel",
        ["chat.loading_messages"] = "Loading messages…",
        ["chat.e2e_self_broken"] = "Something is wrong with your E2E setup, please contact support.",
        ["chat.seen_suffix"] = " · seen",
        ["chat.send"] = "Send",
        ["chat.emoji_button"] = ":)",
        ["chat.system_notice_line1"] = "This is a private chat between you and {0}. This chat is end-to-end encrypted, AetherLove staff cannot read your messages. In the top right you'll find a menu to unmatch, block, or report your match.",
        ["chat.system_notice_line2"] = "Remember: {0} does not know your full name or location until you share it with them. Take care of your own privacy and only share more if you're ready.",
        ["chat.i_understand"] = "I understand",
        ["chat.report_title"] = "Report User",
        ["chat.report_reason_prompt"] = "Please describe the reason for your report:",
        ["chat.report_agree"] = "I agree to submit a report against {0}",
        ["chat.report_agree_contents"] = "I agree to send the contents of this conversation to the AetherLove staff",
        ["chat.submitting"] = "Submitting…",
        ["chat.submit"] = "Submit",

        // Verify encryption
        ["verify.title"] = "Verify encryption",
        ["verify.intro"] = "AetherLove encrypts this chat end-to-end: only you and {0} can read it, not even our staff. The woven pattern below is built from both of your encryption keys.",
        ["verify.unavailable"] = "Verification isn't ready yet. It becomes available once both of you have set up encryption and exchanged keys.",
        ["verify.how"] = "If {0} sees the exact same pattern and code on their screen, no one is intercepting your chat. Compare them over voice chat or in person. If they don't match, stop sharing anything sensitive and contact support.",
        ["verify.your_key"] = "Your public key",
        ["verify.their_key"] = "{0}'s public key",
        ["verify.keys_explain"] = "Public keys are safe to share; they're how your apps recognise each other. The matching private keys never leave your devices, so no server (not even ours) can read your messages.",
        ["verify.back"] = "Back to chat",

        // ChatListScreen
        ["chat.preview_me_prefix"] = "Me: ",
        ["chat.preview_venue"] = "Shared a venue",
        ["chat.matches_title"] = "Matches",
        ["chat.show_search"] = "Show search",
        ["chat.hide_search"] = "Hide search",
        ["chat.search_hint"] = "Name or message",
        ["chat.searching"] = "Searching…",
        ["chat.search_no_results"] = "No matches found",
        ["chat.matches_load_error"] = "Couldn't load matches: {0}",
        ["chat.connectivity_error"] = "Could not connect to the AetherLove server, please try again, or visit Discord to see the status of the server.",
        ["chat.empty_state"] = "You have no matches yet, but that'll change soon. Keep swiping!",
        ["chat.new_match"] = "new match",
        ["chat.say_hi"] = "You matched. Say hi!",
        ["chat.time_ago_minutes"] = "{0}m ago",
        ["chat.time_ago_hours"] = "{0}h ago",
        ["chat.time_ago_days"] = "{0}d ago",

        // added after update (1.3.1)
        ["chat.you"] = "You",
        ["chat.reply"] = "Reply",
        ["chat.pin_message"] = "Pin message",
        ["chat.unpin_message"] = "Unpin message",
        ["chat.pinned_messages"] = "Pinned messages",
        ["chat.pinned_messages_menu"] = "Pinned messages ({0})",
        ["chat.quote_unavailable"] = "(original message unavailable)",
        ["chat.quote_generic"] = "(message)",
        ["chat.replying_to"] = "Replying to {0}",
        ["chat.reaction_remove_hint"] = "click to remove",
        ["chat.jump"] = "Jump",
        ["chat.unpin"] = "Unpin",

        // added after update 1.4.3
        ["chat.menu_search"] = "Search messages",
        ["chat.search_messages_hint"] = "Search this chat...",
        ["chat.category_new"] = "New category",
        ["chat.category_edit"] = "Edit category",
        ["chat.category_delete"] = "Delete category",
        ["chat.category_delete_body"] = "Are you sure you want to delete {0}? The chats inside it will move back to your main matches list.",
        ["chat.category_delete_confirm"] = "Delete",
        ["chat.category_name_hint"] = "Category name",
        ["chat.category_create"] = "Create",
        ["chat.category_save"] = "Save",
        ["chat.menu_move_to_category"] = "Move to category",
        ["chat.menu_remove_from_category"] = "Remove from category",
        ["chat.category_empty"] = "No chats in this category yet. Drag a chat onto it, or right-click a chat and choose Move to category.",
        ["chat.category_count"] = "Chats: {0}",
        ["chat.category_archive_default"] = "Archive",
        ["chat.all_categorized"] = "All your chats are tucked into categories",

        // added after update 1.5.1
        ["chat.menu_view_blocked"] = "View blocked",
        ["blocked.title"] = "Blocked users",
        ["blocked.intro_body"] = "You can unblock profiles here that you have blocked in the past. When you unblock a person you will not rematch automatically, but you have a chance at seeing each other in the deck again.",
        ["blocked.empty"] = "You haven't blocked anyone.",
        ["blocked.loading"] = "Loading...",
        ["blocked.since"] = "Blocked {0}",
        ["blocked.unblock"] = "Unblock",
        ["blocked.confirm_title"] = "Unblock {0}?",
        ["blocked.confirm_body"] = "You won't be rematched automatically, but you may see each other in the deck again.",
        // generic share system (added after update 1.5.1)
        ["chat.news_card_label"] = "News",
        ["chat.news_card_view"] = "Read this article",
        ["chat.news_card_unavailable"] = "This article is no longer available",
        ["chat.preview_news"] = "Shared a news article",

        // Messenger invite bridge (added after update 1.5.1)
        ["chat.menu_invite_messenger"] = "Invite to Messenger",
        ["chat.msgr_card_title"] = "Messenger invite",
        ["chat.msgr_card_hint"] = "Tap to add this code to your contacts",
        ["chat.preview_messenger"] = "Sent a Messenger invite",
        // Key reset notices (added after update 1.5.1)
        ["chat.keys_reset_peer"] = "{0} has reset their E2E encryption keys",
        ["chat.keys_reset_you"] = "You reset your E2E encryption keys; earlier messages can no longer be read",
        // calendar event share
        ["chat.preview_calevent"] = "Shared an event",
        ["chat.preview_location"] = "Shared a location",
        ["chat.calevent_rsvp"] = "RSVP",
        ["chat.calevent_add"] = "Add to calendar",
        // levemetes (added after update 2.0.1)
        ["chat.preview_levemete"] = "Shared a classified ad",
        ["chat.preview_market"] = "Shared a market find",
        ["chat.market_card_label"] = "Market",
        ["chat.market_card_view"] = "View on the market board",
        ["chat.leve_kind_looking"] = "Looking for",
        ["chat.leve_kind_offering"] = "Offering",
        ["chat.leve_cat_1"] = "House decoration",
        ["chat.leve_cat_2"] = "Gposing",
        ["chat.leve_cat_3"] = "Commissions",
        ["chat.leve_cat_4"] = "DJs",
        ["chat.leve_cat_5"] = "Venue staff",
        ["chat.leve_cat_6"] = "Bards & bands",
        ["chat.leve_cat_7"] = "Mercenary services",
        ["chat.leve_cat_8"] = "Crafting & gathering",
        ["chat.leve_cat_9"] = "18+ services",
        ["chat.leve_cat_unknown"] = "Other",
        ["chat.leve_card_view"] = "Open the listing",
        ["chat.leve_card_loading"] = "Loading listing...",
        ["chat.leve_card_unavailable"] = "This listing is no longer available.",
        // user notes (added after update 2.0.1)
        ["chat.menu_user_note"] = "User note",
        ["chat.note_hint"] = "Only you can see this note. It is saved on this computer and never sent anywhere.",
        ["chat.note_save"] = "Save note",
        ["chat.note_tooltip"] = "Your note:",
        // added after update 2.0.0.0 (message delete)
        ["chat.delete_message"] = "Delete message",
        ["chat.delete_message_body"] = "Delete this message for everyone? A note that you deleted it stays in its place.",
        ["chat.delete_message_confirm"] = "Delete",
        ["chat.deleted_by_author"] = "This message was deleted by its author.",
        // added after update 2.2.3 (echo)
        ["chat.preview_echo"] = "Shared an Echo room",
        ["chat.echo_card_label"] = "Echo room",
        ["chat.echo_card_host"] = "Hosted by {0}",
        ["chat.echo_card_members"] = "{0} watching",
        ["chat.echo_card_idle"] = "Nothing playing yet",
        ["chat.echo_card_view"] = "Join this room",
        ["chat.echo_card_loading"] = "Loading room...",
        ["chat.echo_card_unavailable"] = "This room has ended",
    };
}
