namespace AetherLove.Services.Localization;

internal static class HubErrorsPt
{
    public static readonly System.Collections.Generic.Dictionary<string, string> Strings = new()
    {
        ["huberror.generic"] = "Ocorreu um erro inesperado do servidor.",
        ["huberror.generic_detail"] = "Ocorreu um erro: {0}",
        ["huberror.invalid_request"] = "O servidor rejeitou a solicitação. Se isso continuar acontecendo, atualize o plugin.",
        ["huberror.unauthenticated"] = "Tua sessão não é mais válida. Faz login novamente.",
        ["huberror.banned"] = "Este perfil do AetherLove está banido.",
        ["huberror.account_banned"] = "A Tua conta foi banida.",
        ["huberror.server_closed"] = "O servidor está fechado no momento. {0}",
        ["huberror.rate_limited"] = "Estás a faz isso com muita frequência. Tenta novamente mais tarde.",
        ["huberror.profile_not_found"] = "Perfil não encontrado.",
        ["huberror.profile_not_visible"] = "Este perfil não está disponível.",
        ["huberror.deck_expired"] = "Este perfil não está mais no teu baralho. Atualiza o baralho e tenta novamente.",
        ["huberror.no_active_match"] = "Não tem mais match com este jogador.",
        ["huberror.peer_keys_missing"] = "Este utilizador ainda não configurou a encriptação E2E e ainda não pode conversar. Tenta novamente mais tarde.",
        ["huberror.key_bundle_exists"] = "As chaves de criptografia já estão configuradas para esta conta.",
        ["huberror.message_too_large"] = "Esta mensagem é longa demais para ser enviada.",
        ["huberror.bio_too_long"] = "Bio excede o limite de {0} caracteres.",
        ["huberror.lalafell_erp"] = "Roleplay adulto não está disponível para personagens Lalafell.",
        ["huberror.lalafell_nsfw"] = "Recursos NSFW não estão disponíveis para personagens Lalafell.",
        ["huberror.lalafell_nsfw_photo"] = "Fotos NSFW não estão disponíveis para personagens Lalafell.",
        ["huberror.nsfw_disable_blocked"] = "Remove as fotos NSFW e desativa o roleplay 18+ antes de desativar o NSFW.",
        ["huberror.img_too_large"] = "A imagem é grande demais ({0} MB). O máximo é {1} MB.",
        ["huberror.img_dimensions_too_large"] = "A imagem é grande demais ({0}×{1}). O lado mais longo pode ter {2}px.",
        ["huberror.img_crop_too_small"] = "A área de corte é pequena demais (mín. {0}px por lado).",
        ["huberror.img_decode_failed"] = "Não foi possível ler a imagem. Formatos compatíveis: PNG, JPEG, WebP, GIF.",
        ["huberror.img_payload_invalid"] = "Não foi possível enviar a foto. Seleciona a imagem novamente.",
        ["huberror.report_self"] = "Não podes denunciar a ti mesmo.",
        ["huberror.report_reason_required"] = "Descreva o problema, por favor.",
        ["huberror.report_reason_too_long"] = "O motivo é longo demais (máx. {0} caracteres).",
        ["huberror.report_target_gone"] = "Este perfil não existe mais.",
        ["huberror.report_duplicate"] = "Já denuncias-te este usuário recentemente. Nossa equipa está analisando.",
        ["huberror.feedback_required"] = "Digita uma mensagem antes de enviar.",
        // added after update (1.3.1)
        ["huberror.reswipe_nothing_to_undo"] = "Não há nada para desfazer.",
        ["huberror.reswipe_already_matched"] = "Você não pode desfazer em um perfil com quem já deu match.",
        ["huberror.reswipe_quota_exhausted"] = "Você já usou seu desfazer de hoje.",
        ["huberror.superlike_quota_exhausted"] = "Seus superlikes de hoje acabaram.",

        // added after update 1.4.3
        ["huberror.character_limit_reached"] = "Você pode ter no máximo {0} personagens de RP.",
        ["huberror.character_name_invalid"] = "Nomes de personagem devem ter entre 3 e 50 caracteres.",
        ["huberror.character_not_found"] = "Esse personagem não existe mais. Recarregue e tente novamente.",

        // added after update 1.5.0
        ["huberror.patreon_disabled"] = "A ligação ao Patreon está indisponível de momento.",
        ["huberror.patreon_already_linked"] = "Já existe uma conta do Patreon ligada ao seu perfil.",
        ["huberror.patreon_not_linked"] = "Não há nenhuma conta do Patreon ligada ao seu perfil.",
        ["huberror.patreon_account_taken"] = "Essa conta do Patreon já está ligada a outra conta do AetherLove.",
        ["huberror.patreon_link_failed"] = "Não foi possível concluir a ligação ao Patreon. Tente novamente.",
        ["huberror.places_disabled"] = "Lugares está indisponível de momento.",
        ["huberror.venue_not_found"] = "Este local já não existe.",
        ["huberror.venue_limit_reached"] = "Você atingiu o limite de {0} locais.",
        ["huberror.venue_name_invalid"] = "O nome do local deve ter entre 3 e 60 caracteres.",
        ["huberror.venue_description_too_long"] = "A descrição ultrapassa o limite de {0} caracteres.",
        ["huberror.venue_times_invalid"] = "Um dos horários de funcionamento é inválido.",
        ["huberror.venue_times_too_many"] = "Um local pode ter no máximo {0} horários de funcionamento.",
        ["huberror.venue_review_own"] = "Você não pode avaliar o seu próprio local.",
        ["huberror.venue_review_too_long"] = "Sua avaliação ultrapassa o limite de {0} caracteres.",
        ["huberror.venue_review_rating_invalid"] = "Escolha uma nota de 1 a 5 estrelas.",
        ["huberror.venue_rsvp_invalid"] = "Essa abertura já não aceita presenças.",

        // Multi-profile (added after update 1.5.1)
        ["huberror.profile_locked"] = "Este perfil ocupa uma vaga de supporter e está bloqueado no momento.",
        ["huberror.profile_limit_reached"] = "Você atingiu seu limite de perfis.",

        // Messenger (added after update 1.5.1)
        ["huberror.messenger_disabled"] = "O messenger está indisponível no momento.",
        ["huberror.msgr_code_not_found"] = "Nenhum usuário encontrado com esse código.",
        ["huberror.msgr_self"] = "Esse é o seu próprio código.",
        ["huberror.msgr_already_contact"] = "Vocês já são contatos.",
        ["huberror.msgr_request_pending"] = "Sua solicitação ainda está pendente.",
        ["huberror.msgr_contact_limit"] = "Você atingiu seu limite de {0} contatos.",
        ["huberror.msgr_pending_limit"] = "Você tem solicitações pendentes demais (máx. {0}).",
        ["huberror.msgr_not_contact"] = "Vocês não são contatos.",
        ["huberror.msgr_group_limit"] = "Você pode possuir no máximo {0} grupos.",
        ["huberror.msgr_group_full"] = "Grupos podem ter no máximo {0} membros.",
        ["huberror.msgr_not_owner"] = "Apenas o dono do grupo pode fazer isso.",
        ["huberror.msgr_not_member"] = "Você não é membro deste grupo.",
        ["huberror.msgr_group_name_invalid"] = "Esse nome de grupo não pode ser usado.",
        ["huberror.msgr_adds_disabled"] = "Este usuário não aceita solicitações de contato.",
        ["huberror.msgr_keys_missing"] = "As chaves de criptografia estão desatualizadas; tente novamente em instantes.",
        ["huberror.msgr_image_rejected"] = "Essa imagem não pode ser enviada. Escolhe outra imagem ou contacta o suporte se achas que é um engano.",
        ["huberror.msgr_storage_full"] = "O teu armazenamento de imagens está cheio. Apaga algumas imagens ou espera que as mais antigas expirem e tenta novamente.",
        ["huberror.msgr_image_too_large"] = "Essa imagem é demasiado grande.",
        ["huberror.msgr_image_invalid"] = "Não foi possível ler essa imagem.",
        // levemetes (added after update 2.0.1)
        ["huberror.levemetes_disabled"] = "O Levemetes está desativado de momento.",
        ["huberror.leve_not_found"] = "Este anúncio já não existe.",
        ["huberror.leve_invalid"] = "Não foi possível guardar o anúncio. Verifica os dados.",
        ["huberror.leve_limit_reached"] = "Já tens {0} anúncios. Apaga um ou deixa um expirar.",
        ["huberror.leve_too_long"] = "O texto é demasiado longo (máx. {0} caracteres).",
        ["huberror.leve_image_rejected"] = "Esta imagem não pode ser enviada. Escolhe outra ou contacta o suporte se achares que é um engano.",
        ["huberror.leve_review_own"] = "Não podes avaliar o teu próprio anúncio.",
        ["huberror.leve_review_too_long"] = "A tua avaliação é demasiado longa (máx. {0} caracteres).",
        ["huberror.leve_review_rating_invalid"] = "Escolhe uma classificação de 1 a 5 estrelas.",
        ["huberror.leve_reviews_disabled"] = "O autor desativou as avaliações neste anúncio.",
        ["huberror.leve_renew_too_soon"] = "Este anúncio foi renovado há pouco. Tenta mais tarde.",
        // holiday mode (added after update 2.0.1)
        // wayfinder (added after update 2.1.3)
        ["huberror.wayfinder_disabled"] = "O Wayfinder está desativado de momento.",
        ["huberror.wayfinder_no_challenges"] = "De momento não há desafios disponíveis. Volta em breve!",
        ["huberror.wayfinder_no_reachable"] = "Os desafios que restam estão em zonas que ainda não desbloqueaste. Sintoniza mais eteritos e volta!",
        ["huberror.wayfinder_daily_limit"] = "Usaste os {0} inícios de hoje.",
        ["huberror.wayfinder_active_exists"] = "Já tens um desafio em curso.",
        ["huberror.wayfinder_no_active"] = "Este desafio já não está ativo.",
        ["huberror.wayfinder_expired"] = "Acabou o tempo! Este desafio expirou.",
        ["huberror.wayfinder_not_scout"] = "Não tens permissão para adicionar pontos de referência.",
        ["huberror.wayfinder_invalid"] = "Não foi possível guardar o ponto de referência. Verifica os teus dados.",
        ["huberror.wayfinder_image_rejected"] = "Esta foto não pode ser enviada. Tira outra, ou contacta o suporte se achares que é um erro.",
        ["huberror.holiday_message_too_long"] = "A tua mensagem de férias é demasiado longa (máx. {0} caracteres).",
        ["huberror.holiday_message_invalid"] = "Esta mensagem de férias não pode ser usada. Reformula-a, por favor.",
        // yapper (added after update 2.1.3)
        ["huberror.yapper_disabled"] = "O Yapper está desativado de momento.",
        ["huberror.yapper_no_profile"] = "Configura primeiro o teu perfil do Yapper.",
        ["huberror.yapper_banned"] = "Não podes publicar agora. Contacta o suporte se achares que é um erro.",
        ["huberror.yapper_handle_taken"] = "Esse nome de usuário já está ocupado.",
        ["huberror.yapper_handle_invalid"] = "Os nomes de usuário têm de 3 a 20 caracteres: letras, números e underscores.",
        ["huberror.yapper_handle_rejected"] = "Esse nome de usuário não pode ser usado. Escolhe outro, por favor.",
        ["huberror.yapper_profile_rejected"] = "Esse texto não pode ser usado no teu perfil. Reformula-o, por favor.",
        ["huberror.yapper_rename_too_soon"] = "Mudaste o teu nome de usuário há pouco tempo. Tenta de novo em {0} dias.",
        ["huberror.yapper_blocked"] = "Não podes interagir com este usuário.",
        ["huberror.yap_not_found"] = "Este yap já não existe.",
        ["huberror.yap_too_long"] = "Esse yap é demasiado longo (máx. {0} caracteres).",
        ["huberror.yap_too_many_images"] = "Um yap pode ter no máximo {0} imagens.",
        ["huberror.yap_image_rejected"] = "Essa imagem não pode ser publicada. Escolhe outra, ou contacta o suporte se achares que é um erro.",
        ["huberror.yap_image_too_large"] = "Essa imagem é demasiado grande.",
        ["huberror.yap_image_invalid"] = "Não foi possível ler essa imagem.",
        ["huberror.yap_embed_invalid"] = "O conteúdo partilhado já não está disponível.",
        ["huberror.yap_edit_window_closed"] = "O prazo para editar este yap terminou.",
        ["huberror.yap_nsfw_mismatch"] = "A tua classificação de conteúdo não permite isso.",
        ["huberror.yap_invalid"] = "Não foi possível guardar o yap. Verifica os teus dados.",
        ["huberror.yap_dm_not_allowed"] = "Este usuário não pode receber suas mensagens.",
        ["huberror.yap_dm_keys_missing"] = "@{0} ainda precisa terminar a configuração. Tente mandar mensagem daqui a pouco.",

        // store (added after update 2.2.3)
        ["huberror.store_disabled"] = "A loja está fechada para manutenção.",
        ["huberror.store_product_not_found"] = "Esse item não existe mais.",
        ["huberror.store_product_unavailable"] = "Esse item não está à venda agora.",
        ["huberror.store_insufficient_sparks"] = "Sparks insuficientes: custa {0} e você tem {1}.",
        ["huberror.store_limit_reached"] = "Você já tem o máximo ({0}) deste item.",
        ["huberror.store_quantity_invalid"] = "Essa quantidade não é permitida.",
        ["huberror.store_conflict"] = "A loja engasgou no meio da compra. Nada foi cobrado duas vezes; é só tentar de novo.",
        ["huberror.aetherling_disabled"] = "Neste momento não está a ouvir.",
        ["huberror.aetherling_exists"] = "Já existe um destes.",
        ["huberror.aetherling_none"] = "Não há aqui nada a quem dar isto.",
        ["huberror.aetherling_insufficient"] = "Sparks a menos: quer {0} e tens {1}.",
        ["huberror.aetherling_gated"] = "Ainda não. Primeiro tem de acontecer algo. Tenta outra vez daqui a {0} minutos.",
        ["huberror.aetherling_complete"] = "Já não aceita mais.",
        ["huberror.aetherling_unready"] = "Ainda não. Não está pronto para isso.",
        ["huberror.aetherling_named"] = "Já tem o nome dele.",
        ["huberror.aetherling_name_invalid"] = "Esse nome não serve. Tenta outro.",

        // echo (added after update 2.2.3)
        ["huberror.echo_disabled"] = "Ver em conjunto está desligado neste momento.",
        ["huberror.echo_room_not_found"] = "Essa sessão já terminou.",
        ["huberror.echo_room_full"] = "Esta sala está cheia ({0} pessoas).",
        ["huberror.echo_not_member"] = "Não estás nessa sala.",
        ["huberror.echo_not_owner"] = "Só quem criou a sala é que pode fazer isso.",
        ["huberror.echo_host_only"] = "Neste momento é o anfitrião que controla a reprodução.",
        ["huberror.echo_kicked"] = "Foste removido dessa sala.",
        ["huberror.echo_playlist_full"] = "A fila está cheia ({0} vídeos).",
        ["huberror.echo_live_room_exists"] = "Já tens uma sala a decorrer. Termina-a para abrires outra.",
        ["huberror.echo_invalid_video"] = "Isso não parece um link do YouTube.",
        ["huberror.echo_name_invalid"] = "Esse nome de sala não pode ser usado.",
        ["huberror.hangout_watch_room_invalid"] = "Essa sessão já não está disponível.",

        // aetherling growth (added after update 2.3.4)
        ["huberror.aetherling_no_crystal"] = "Não há nenhum cristal desse tipo para lhe dar.",
        ["huberror.aetherling_full"] = "Está bem cheio. Amanhã volta a ter fome.",
        ["huberror.aetherling_not_owned"] = "Não tem isso para vestir.",
    };
}
