namespace AetherLove.Services.Localization;

internal static class SettingsEs
{
    public static readonly System.Collections.Generic.Dictionary<string, string> Strings = new()
    {
        ["settings.section_plugin_settings"] = "Ajustes del plugin",
        ["settings.section_phone_size"] = "Tamaño del teléfono",
        ["settings.section_plugin_language"] = "Idioma del plugin",
        ["settings.section_general"] = "Ajustes generales",
        ["settings.section_notifications"] = "Notificaciones",
        ["settings.section_other"] = "Otros",
        ["settings.section_danger_zone"] = "Zona de peligro",
        ["settings.menu_language_theme"] = "Idioma y tema",
        ["settings.menu_appearance"] = "Apariencia del teléfono",
        ["settings.menu_chat_colors"] = "Apariencia del chat",
        ["settings.section_theme"] = "Tema",
        ["settings.back_arrow"] = "← Atrás",
        ["settings.chat_own_bg"] = "Fondo de tu chat",
        ["settings.chat_own_fg"] = "Texto de tu chat",
        ["settings.chat_peer_bg"] = "Fondo del chat del otro",
        ["settings.chat_peer_fg"] = "Texto del chat del otro",
        ["settings.chat_reset"] = "Restablecer",

        ["settings.phone_size_small"] = "Pequeño",
        ["settings.phone_size_medium"] = "Mediano",
        ["settings.phone_size_large"] = "Grande",
        ["settings.phone_size_xl"] = "XL",
        ["settings.phone_size_xxl"] = "XXL",
        ["settings.phone_size_caption"] = "Escala todo el teléfono. Los tamaños mayores son ideales para pantallas de alta resolución; XL y XXL están pensados para 4K y puede que no quepan en pantallas más pequeñas.",
        ["settings.section_mini_phone_size"] = "Tamaño del teléfono en miniatura",
        ["settings.mini_phone_size_caption"] = "Tamaño de la burbuja minimizada (se muestra cuando el teléfono está minimizado). La vista previa de abajo muestra el tamaño seleccionado.",

        ["settings.confirm_before_close"] = "Confirmar antes de cerrar el teléfono",

        ["settings.view_changelog"] = "Ver registro de cambios",
        ["settings.send_feedback"] = "Enviar comentarios",
        ["settings.terms_of_service"] = "Términos del servicio",
        ["settings.cancel"] = "Cancelar",

        ["settings.always_blur_nsfw"] = "Difuminar siempre el NSFW",
        ["settings.always_blur_nsfw_tooltip"] = "Cuando está activado, las fotos adicionales etiquetadas como NSFW en otros perfiles se difuminan hasta que haces clic para revelar cada una. Los avatares y los retratos principales siempre son aptos para el trabajo, en cualquier caso. Desactivar esto muestra cada foto tal cual.",
        ["settings.nsfw_profile"] = "Mi perfil es NSFW (+18)",
        ["settings.nsfw_profile_tooltip"] = "Marca tu perfil como para adultos/NSFW para que solo lo vean las personas que tienen el NSFW activado. Se activa automáticamente cuando añades fotos NSFW o eliges rol +18, y permanece activo hasta que las quites.",
        ["settings.nsfw_profile_locked"] = "No puedes desactivarlo mientras tengas fotos NSFW o rol +18 (ERP) seleccionado. Elimina primero tus imágenes NSFW y desactiva el rol +18.",

        ["settings.enable_notifications"] = "Activar notificaciones",
        ["settings.enable_notifications_tooltip"] = "Interruptor principal de todas las notificaciones. Desactívalo para silenciar todos los avisos de chat dentro del juego, los pop-ups y los sonidos de abajo.",
        ["settings.enable_notification_sounds"] = "Activar sonidos de notificación",
        ["settings.enable_notification_sounds_tooltip"] = "Los sonidos de notificación solo se reproducirán si el audio del juego y el audio de los efectos especiales no están silenciados. El control de volumen se gestiona desde el volumen de Windows.",
        ["settings.announce_messages_chat"] = "Anunciar mensajes nuevos en el chat del juego",
        ["settings.announce_matches_chat"] = "Anunciar coincidencias nuevas en el chat del juego",
        ["settings.popup_messages"] = "Mostrar un pop-up para mensajes nuevos",
        ["settings.popup_matches"] = "Mostrar un pop-up para coincidencias nuevas",
        ["settings.hide_notifications_in_combat"] = "Ocultar notificaciones en combate",
        ["settings.hide_notifications_in_combat_tooltip"] = "Cuando está activado, no recibirás ninguna notificación (ni avisos en el chat del juego, ni pop-ups, ni sonidos) mientras estés en combate.",
        ["settings.auto_open_minimized"] = "Abrir minimizado automáticamente al iniciar sesión",
        ["settings.pulse_optout"] = "Recibe mensajes increíbles del equipo de Aethernet para recordarte que deslices",
        ["settings.pulse_optout_tooltip"] = "De vez en cuando, AetherLove puede dejar un mensaje divertido en tu chat del juego. Desactívalo para detenerlos.",
        ["settings.combat_behavior"] = "Al entrar en combate",
        ["settings.combat_behavior_hide"] = "Ocultar el teléfono",
        ["settings.combat_behavior_minimize"] = "Minimizar a burbuja",
        ["settings.combat_behavior_leave_open"] = "Dejar abierto",
        ["settings.notification_sound"] = "Sonido de notificación",
        ["settings.play"] = "Reproducir",

        ["settings.delete_bullet_matches"] = "Todas tus coincidencias se eliminarán.",
        ["settings.delete_bullet_preferences"] = "Tus preferencias de coincidencia se borrarán.",
        ["settings.delete_bullet_pictures"] = "Tus fotos de perfil se eliminarán.",
        ["settings.delete_previous_failed"] = "El intento anterior falló: {0}",

        ["settings.deleting_title"] = "Eliminando cuenta",
        ["settings.deleting_body"] = "Eliminando tus datos y deshaciendo coincidencias con tus contactos",

        ["settings.warnings_title"] = "Advertencias de la cuenta",
        ["settings.no_warnings"] = "No hay advertencias registradas.",

        // Moderator messages
        ["settings.modmsg_title"] = "Mensajes del moderador",
        ["settings.no_modmsg"] = "No hay mensajes registrados.",
        ["settings.back_to_settings_arrow"] = "← Volver a los ajustes",

        ["settings.back_to_settings"] = "Volver a los ajustes",
        ["settings.feedback_thanks"] = "¡Gracias! Tus comentarios se han enviado al equipo de AetherLove.",
        ["settings.feedback_intro"] = "¿Encontraste un error, tienes una idea o quieres sugerir algo? Cuéntanoslo.",
        ["settings.feedback_note"] = "Ten en cuenta: los comentarios no se pueden usar para apelar un baneo o una advertencia.",
        ["settings.feedback_type"] = "Tipo",
        ["settings.feedback_kind_bug"] = "Error",
        ["settings.feedback_kind_improvement"] = "Mejora",
        ["settings.feedback_kind_other"] = "Otro",
        ["settings.feedback_your_message"] = "Tu mensaje",
        ["settings.sending"] = "Enviando…",
        ["settings.submit"] = "Enviar",
        ["settings.feedback_rate_limited"] = "Solo puedes enviar comentarios {0} veces por hora. Inténtalo de nuevo más tarde.",
        ["settings.feedback_send_failed"] = "No se pudieron enviar tus comentarios. Inténtalo de nuevo.",

        ["settings.contributors"] = "Colaboradores",
        ["settings.contributors_thanks_title"] = "Gracias",
        ["settings.contributors_intro"] = "AetherLove no sería posible sin:",
        ["settings.contributors_leads"] = "Responsables del proyecto: Astraea & Nihal",
        ["settings.contributors_council"] = "The Chon-Chon Council",
        ["settings.contributors_moderation"] = "Moderación: Su",
        ["settings.contributors_translators"] = "Traductores: Tears, Mufami, Terashi, Su, Astraea",
        ["settings.contributors_xivauth"] = "XIVAuth by KazWolfe",
        ["settings.contributors_punish"] = "Puni.sh",
        ["settings.contributors_dalamud"] = "The Dalamud project",
        ["settings.contributors_testers"] = "Todos los maravillosos beta testers de Eorzea.",

        // added after update 1.4.0
        ["settings.lock_position"] = "Bloquear posición",
        ["settings.lock_position_caption"] = "Al bloquear la posición no podrás mover el teléfono (grande y mini); quedarán fijos en su sitio.",

        // added after update 1.4.3
        ["settings.show_during_gpose"] = "Mostrar el teléfono durante la pose de grupo",
        ["settings.show_during_gpose_tooltip"] = "Mantiene el teléfono visible durante la pose de grupo (/gpose), anulando la opción de Dalamud que oculta las ventanas de plugins durante la pose de grupo.",
        ["settings.hide_during_cutscene"] = "Mostrar el teléfono durante las escenas",
        ["settings.hide_during_cutscene_tooltip"] = "Mantiene el teléfono visible mientras se reproduce una escena. Al desactivarlo se oculta durante las escenas (opción predeterminada).",
        ["settings.tomestone_emote"] = "Mostrar el gesto de tomo al usar la app",
        ["settings.tomestone_emote_tooltip"] = "Mientras el teléfono está abierto, tu personaje usa el gesto /tomescroll, como si lo estuviera leyendo. Solo empieza en una zona segura y nunca interrumpe otro gesto.",

        // added after update 1.5.0
        ["settings.menu_supporter"] = "Colaborador",
        ["settings.supporter_link_button"] = "Vincular cuenta de Patreon",
        ["settings.supporter_contacting"] = "Conectando con el servidor...",
        ["settings.supporter_awaiting_browser"] = "Termina la vinculación en tu navegador y vuelve aquí.",
        ["settings.supporter_open_again"] = "Abrir el navegador de nuevo",
        ["settings.supporter_cancel"] = "Cancelar",
        ["settings.supporter_you_are_title"] = "Eres Supporter",
        ["settings.supporter_you_are_body"] = "Tu cuenta de Patreon se vinculó correctamente y tu estado de Supporter está activado.",
        ["settings.supporter_nomember_title"] = "No se encontró membresía",
        ["settings.supporter_nomember_body"] = "Tu cuenta de Patreon se vinculó, pero no se encontró ninguna membresía activa. Si acabas de suscribirte, tu estado de Supporter se concede automáticamente en unas horas. También puedes desvincular y volver a intentarlo cuando tu membresía esté activa en Patreon.",
        ["settings.supporter_not_entitled"] = "Aún no se ha encontrado una membresía activa. Si acabas de suscribirte, tu rol se concede automáticamente en unas horas.",
        ["settings.supporter_unlink_button"] = "Desvincular Patreon",
        ["settings.supporter_unlink_confirm"] = "¿Desvincular esta cuenta de Patreon? Se te quitará el rol de Colaborador.",
        ["settings.supporter_failed"] = "La vinculación falló. Inténtalo de nuevo.",
        ["settings.supporter_retry"] = "Reintentar",
        ["settings.supporter_unavailable"] = "La vinculación de colaboradores no está disponible ahora mismo. Vuelve a intentarlo más tarde.",
        ["settings.supporter_link_expired"] = "La solicitud de vinculación caducó. Inténtalo de nuevo.",

        // added after update 1.5.1
        ["settings.supporter_linked"] = "Vinculado",
        ["settings.supporter_title"] = "Hazte colaborador",
        ["settings.supporter_intro"] = "Puedes apoyar el proyecto económicamente a través de nuestro Patreon. Todas las funciones de AetherLove son gratis para todos, y nada está ni estará nunca detrás de un muro de pago. Los colaboradores solo reciben un agradecimiento de corazón: límites más generosos y algunos extras con brillo, nuestra forma de decir que no podríamos hacerlo sin ti.",
        ["settings.supporter_perks_header"] = "Ventajas de AetherLove",
        ["settings.supporter_msgr_perks_header"] = "Ventajas de Messenger",
        ["settings.supporter_perk_msgr_groups_title"] = "Chats de grupo enormes",
        ["settings.supporter_perk_msgr_groups_body"] = "Añade amigos ilimitados por código, ten hasta 10 chats de grupo a la vez y reúne hasta 15 personas en cada uno.",
        ["settings.supporter_perk_msgr_storage_title"] = "Más almacenamiento en Messenger",
        ["settings.supporter_perk_msgr_storage_body"] = "Más espacio para los selfies e imágenes que compartes, y más tiempo antes de que caduquen.",
        ["settings.supporter_perk_profiles_title"] = "Dos perfiles",
        ["settings.supporter_perk_profiles_body"] = "Usa dos perfiles de AetherLove a la vez, perfecto para llevar varios OC o separar tu yo de rol del OOC.",
        ["settings.supporter_perk_photos_title"] = "Más espacio para brillar",
        ["settings.supporter_perk_photos_body"] = "Hasta 5 fotos de perfil extra, y 2 más por cada personaje de rol.",
        ["settings.supporter_perk_superlike_title"] = "Superlike",
        ["settings.supporter_perk_superlike_body"] = "Dile a alguien que de verdad te ha llamado la atención. Recibe una notificación de que le diste un Superlike, y si te da like de vuelta, hacéis match al instante.",
        ["settings.supporter_perk_rewinds_title"] = "5 retrocesos al día",
        ["settings.supporter_perk_rewinds_body"] = "¿Deslizaste demasiado pronto? Retrocede hasta 5 veces al día en lugar de solo una.",
        ["settings.supporter_perk_analytics_title"] = "Estadísticas más profundas",
        ["settings.supporter_perk_analytics_body"] = "Analíticas y estadísticas extra sobre quién te quiere y cómo funciona de verdad tu perfil.",
        ["settings.supporter_perk_colors_title"] = "Colores vivos",
        ["settings.supporter_perk_colors_body"] = "Tu nombre brilla como un arcoíris, cambiando lentamente de colores imposibles de ignorar.",
        ["settings.supporter_perk_badge_title"] = "Distintivo de Colaborador",
        ["settings.supporter_perk_badge_body"] = "Una etiqueta de Colaborador y una pequeña estrella junto a tu nombre. Ese pequeño lujo, merecido.",
        ["settings.supporter_how_heading"] = "Cómo funciona",
        ["settings.supporter_how_intro"] = "Ofrecemos tres niveles a distintos precios para que elijas lo que te resulte cómodo, y todos desbloquean exactamente las mismas ventajas. Ningún nivel obtiene más que otro.",
        ["settings.supporter_step1_title"] = "1. Suscríbete en Patreon",
        ["settings.supporter_step1_body"] = "Crea una cuenta de Patreon y suscríbete a cualquiera de nuestros niveles de colaborador, todos desbloquean las mismas ventajas.",
        ["settings.supporter_step2_title"] = "2. Vincúlalo a AetherLove",
        ["settings.supporter_step2_body"] = "Vincula tu cuenta de Patreon haciendo clic en el botón de abajo. Si tienes una membresía activa, tu cuenta se volverá premium al instante.",
        ["settings.supporter_become"] = "Hazte Colaborador en Patreon",
        ["settings.supporter_data_note"] = "Solo guardamos tu id de usuario de Patreon y si eres miembro de nuestra campaña. Nunca guardamos tu nombre, correo ni cuentas sociales.",
        ["settings.sup_learn_title"] = "Apoya AetherLove",
        ["settings.sup_learn_body"] = "Esta persona apoya AetherLove. ¿Quieres ver lo que te da apoyar el proyecto? Fotos extra, superlikes, estilos de nombre, estadísticas adicionales y más.",
        ["settings.sup_learn_more"] = "Más info",

        ["settings.sup_thanks_title"] = "¡Ya eres Supporter!",
        ["settings.sup_thanks_sub"] = "¡Gracias por apoyar AetherLove!",
        ["settings.sup_thanks_body"] = "Tu apoyo mantiene los servidores en marcha. ¡Disfruta de tus nuevas ventajas!",
        ["settings.sup_thanks_continue"] = "Continuar",
        // AetherLove-app notification master (added after update 1.5.1)
        ["settings.enable_aetherlove_notifications"] = "Activar notificaciones de AetherLove",
        ["settings.menu_nsfw"] = "Ajustes NSFW",
        // DTR server-info-bar entries (added after update 1.5.1)
        ["dtr.chats"] = "Chats",
        ["dtr.matches"] = "Matches",
        ["dtr.news"] = "Noticias",
        ["settings.show_dtr_count"] = "Mostrar contadores de no leídos en la barra de info del servidor",
        ["settings.show_dtr_count_tooltip"] = "Añade entradas de AetherLove (chats, matches, noticias) a la barra de información del servidor del juego, junto a los FPS y el ping. Cada una muestra su contador de no leídos y se oculta cuando no hay nada nuevo. También puedes ocultar entradas concretas en los ajustes de la barra de información del servidor de Dalamud.",

        // Multi-profile: the profile picker, switching, and delete-profile (added after update 1.5.1)
        ["settings.menu_switch_profile"] = "Cambiar de perfil",
        ["settings.delete_profile"] = "Eliminar perfil",
        ["settings.delete_profile_warning_intro"] = "Eliminar este perfil de AetherLove es permanente. Antes de continuar, esto es exactamente lo que ocurre:",
        ["settings.delete_bullet_profile"] = "Este perfil de citas se elimina y no se puede restaurar.",
        ["settings.delete_profile_account_stays"] = "Tu cuenta de AetherOS y tus demás aplicaciones no se ven afectadas. Puedes crear un perfil nuevo en cualquier momento.",
        ["picker.title"] = "Elegir perfil",
        ["picker.subtitle"] = "¿Quién hace swipe hoy?",
        ["picker.current"] = "Perfil actual",
        ["picker.banned"] = "Baneado",
        ["picker.finish_setup"] = "Terminar la configuración",
        ["picker.locked"] = "Espacio de supporter",
        ["picker.create"] = "Nuevo perfil",
        ["picker.create_sub"] = "Empezar un perfil de citas nuevo",
        ["picker.create_secondary"] = "Crear un perfil secundario",
        ["picker.create_supporter_pitch"] = "Un segundo perfil de AetherLove es una ventaja de supporter. Apoya el proyecto para desbloquear otra identidad de citas, con sus propios matches y chats, totalmente separada de la primera.",
        ["picker.locked_supporter_pitch"] = "Este perfil ocupa un espacio de supporter. Renueva tu estado de supporter para abrirlo de nuevo; no se ha borrado nada, solo está bloqueado.",
        ["picker.switching"] = "Cambiando de perfil...",
        ["picker.switch_failed"] = "No se pudo cambiar de perfil. Inténtalo de nuevo.",
        ["picker.share_as_title"] = "Compartir como...",
        ["picker.share_as_body"] = "¿Con qué perfil quieres compartir esto?",
        ["picker.share_as_current"] = "{0} (actual)",

        // Messenger (added after update 1.5.1)
        ["dtr.messenger"] = "Messenger",

        // added after update 2.0.0.0
        ["settings.section_time_format"] = "Formato de hora",
        ["settings.time_24h"] = "24 horas",
        ["settings.time_12h"] = "12 horas",

        // added after update 2.0.1
        ["settings.audio_sounds_off"] = "Los sonidos de notificaciÃ³n estÃ¡n desactivados.",
        ["settings.audio_sounds_enable"] = "Activar sonidos de notificaciÃ³n",
        ["settings.audio_volume"] = "Volumen de notificaciones",
        ["settings.audio_device"] = "Dispositivo de salida",
        ["settings.audio_device_default"] = "Predeterminado del sistema",
        ["settings.audio_test"] = "Reproducir sonido de prueba",
        ["settings.audio_test_ok"] = "Â¡Sonando! Si no oyes nada, prueba con otro dispositivo de salida arriba.",
        ["settings.font_header"] = "Fuente",
        ["settings.font_caption"] = "Se aplica a todo el texto del móvil. Los caracteres que falten en una fuente usan la fuente predeterminada.",
        ["settings.font_default"] = "Predeterminada",
        ["settings.phone_size_header"] = "Tamaño del móvil",
        ["settings.mini_phone_size_header"] = "Tamaño en miniatura",
    };
}
