namespace AetherLove.Services.Localization;

internal static class OsEn
{
    public static readonly System.Collections.Generic.Dictionary<string, string> Strings = new()
    {
        // added after update 1.5.1
        // App names
        ["os.app_clock"] = "Clock",
        ["os.app_snake"] = "Snake",
        ["os.app_doom"] = "DOOM",
        ["os.app_sudoku"] = "Sudoku",
        ["os.app_stacker"] = "Stacker",
        ["os.app_breaker"] = "Breaker",
        ["os.app_meteor"] = "Meteor Command",
        ["os.app_invaders"] = "Void Invaders",
        ["os.app_muncher"] = "Maze Muncher",
        ["os.app_camera"] = "Camera",

        // Notification shade
        ["os.notifications"] = "Notifications",
        ["os.notifications_empty"] = "No notifications",
        ["os.notifications_clear"] = "Clear all",
        ["os.notif_remove"] = "Remove",
        ["os.time_now"] = "now",
        ["os.qt_notifications"] = "Notifications",
        ["os.qt_sounds"] = "Notification sounds",
        ["os.qt_lock"] = "Lock phone position",
        ["os.qt_theme"] = "Next theme",
        ["os.qt_wallpaper"] = "Next wallpaper",

        // Home screen
        ["os.greeting_morning"] = "Good morning",
        ["os.greeting_afternoon"] = "Good afternoon",
        ["os.greeting_evening"] = "Good evening",
        ["os.greeting_night"] = "Up late?",
        ["os.widget_eorzea"] = "Eorzea",
        ["os.widget_status"] = "Connection",
        ["os.widget_connected"] = "Connected",
        ["os.widget_offline"] = "Offline",
        ["os.widget_unread"] = "{0} unread",

        // OS settings
        ["os.group_appearance"] = "Appearance",
        ["os.group_wallpaper"] = "Homescreen & Wallpaper",
        ["os.group_home"] = "Home screen",
        ["os.group_apps"] = "App specific settings",
        ["os.group_about"] = "About",
        ["os.wallpaper_gradient"] = "Theme",
        ["os.wallpaper_custom"] = "Yours",
        ["os.wallpaper_upload"] = "Upload image…",
        ["os.wallpaper_dim"] = "Darken wallpaper",
        ["os.home_edit_hint"] = "Hold an icon on the home screen to rearrange it. Drag icons into the dock or between pages.",
        ["os.home_reset"] = "Reset layout",

        // Love settings hub after the appearance move
        ["settings.menu_language"] = "Language & Time",

        // Weatherman app
        ["os.app_weather"] = "Weather",

        // Messenger app
        ["os.app_messenger"] = "Messenger",

        // Photos app
        ["os.app_photos"] = "Photos",

        // Home screen app launcher
        ["os.add_apps"] = "Add apps",
        ["os.add_apps_title"] = "Add apps",
        ["os.add_apps_hint"] = "Bring back an app you removed, or pin another installed Dalamud plugin.",
        ["os.add_apps_none"] = "No other plugins expose a main window.",
        ["os.add_apps_add"] = "Add",
        ["os.add_apps_added"] = "Added",
        ["os.add_apps_search"] = "Search apps...",
        ["os.remove_app_title"] = "Remove app",
        ["os.remove_app_body"] = "Remove {0} from your home screen?",
        ["os.remove_app_confirm"] = "Remove",
        // added after update 1.5.1
        ["os_onboarding.header_welcome"] = "Welcome",
        ["os_onboarding.header_design"] = "Make it yours",
        ["os_onboarding.header_name"] = "Your name",
        ["os_onboarding.header_terms"] = "Terms of Service",
        ["os_onboarding.welcome_title"] = "Welcome to AetherOS",
        ["os_onboarding.welcome_body"] = "This is your phone. Let's set it up: pick a look, choose a name, and agree to the ground rules. It only takes a moment.",
        ["os_onboarding.design_title"] = "Pick a design",
        ["os_onboarding.name_title"] = "What should we call you?",
        ["os_onboarding.name_body"] = "This name is used across AetherOS. You can pick a different display name for each app later.",
        ["os_onboarding.name_hint"] = "Name",
        ["os_onboarding.terms_title"] = "The ground rules",
        ["os_onboarding.terms_agree"] = "I agree to the Terms of Service",
        ["os_onboarding.finish"] = "Finish",
        ["os_onboarding.header_signin"] = "Sign in",
        ["os_onboarding.header_passphrase"] = "Passphrase",
        ["os_onboarding.tos_1"] = "AetherOS is a fan-made plugin, provided as-is with no warranty of any kind. It may break, lose data, or stop working at any time, and it is used entirely at your own risk.",
        ["os_onboarding.tos_2"] = "AetherOS is not affiliated with, endorsed by, or sponsored by Square Enix.",
        ["os_onboarding.tos_3"] = "FINAL FANTASY and FINAL FANTASY XIV are registered trademarks of Square Enix Holdings Co., Ltd. All other trademarks are the property of their respective owners.",
        ["os_onboarding.tos_4"] = "By continuing, you accept these terms.",
        // OS account avatar (added after update 1.5.1)
        ["os_onboarding.header_avatar"] = "Avatar",
        ["os_onboarding.avatar_title"] = "Add a photo",
        ["os_onboarding.avatar_body"] = "Pick a picture for your AetherOS profile. It's optional and only you see it; you can change it any time.",
        ["os_onboarding.avatar_choose"] = "Choose photo",
        ["os_onboarding.avatar_change"] = "Change photo",
        // two-onboarding split (added after update 1.5.1)
        ["os_onboarding.header_done"] = "All set",
        ["os_onboarding.done_title"] = "You're all set!",
        ["os_onboarding.done_body"] = "Your AetherOS account is ready. Enjoy your new phone!",
        ["os_onboarding.done_start"] = "Start using the plugin",
        ["os_onboarding.design_language"] = "Language",
        // combined OS profile step (added after update 1.5.1)
        ["os_onboarding.header_profile"] = "Your profile",
        ["os_onboarding.profile_name_label"] = "Your name",
        ["os_onboarding.profile_photo_label"] = "Your photo",
        // home button tooltip (added after update 1.5.1)
        ["os.home"] = "Home",
        ["os.mini_open"] = "Open full view",
        ["os.mini_power"] = "Turn the phone off",
        // settings-consolidation categories + reset-home confirm + profile edit (added after update 1.5.1)
        ["os.cat_general"] = "General",
        ["os.cat_appearance"] = "Appearance",
        ["os.cat_other"] = "Other",
        ["os.menu_general"] = "General",
        ["os.menu_appearance"] = "Phone appearance",
        ["os.menu_reset_home"] = "Reset home screen",
        ["os.reset_home_confirm_title"] = "Reset home screen?",
        ["os.reset_home_confirm_body"] = "This clears your custom icon layout and dock, restoring the default arrangement. Your apps and settings are not affected.",
        ["os.edit_profile"] = "Edit",
        // Daily Eorzean news app (added after update 1.5.1)
        ["os.app_news"] = "Daily Eorzean",
        ["os.news_notifications"] = "News notifications",
        ["os.news_tagline"] = "Est. · All the realm's news",
        ["os.news_latest"] = "Latest",
        ["os.news_more"] = "More stories",
        ["os.news_edition"] = "Edition · {0}",
        ["os.news_refresh"] = "Refresh",
        ["os.news_new"] = "New",
        // Feedback app (added after update 1.5.1)
        ["os.app_feedback"] = "Feedback",
        ["os.feedback_app_label"] = "Which app is this about?",
        ["os.feedback_general"] = "General",
        ["os.feedback_send_another"] = "Send more feedback",
        // generic share system (added after update 1.5.1)
        ["os.share_sheet_title"] = "Share to",
        // home grid + folders
        ["os.settings_home_screen"] = "Home screen",
        ["os.settings_home_grid_caption"] = "Icons rearrange automatically to fit the new grid.",
        ["os.new_folder"] = "New folder",
        ["os.folder_create"] = "Create",
        ["os.folder_name_hint"] = "Folder name…",
        ["os.folder_default_name"] = "Folder",
        ["os.folder_arcade"] = "Arcade",
        ["os.folder_media"] = "Media",
        ["os.folder_empty"] = "No apps yet. Drag an icon onto this folder to add it.",
        // photo filters + screenshot import
        ["os.filter_original"] = "Original",
        ["os.filter_mono"] = "Mono",
        ["os.filter_noir"] = "Noir",
        ["os.filter_sepia"] = "Sepia",
        ["os.filter_retro"] = "Retro",
        ["os.filter_cool"] = "Cool",
        ["os.filter_vivid"] = "Vivid",
        ["os.filter_fade"] = "Fade",
        ["os.filter_applying"] = "Applying…",
        ["os.screenshots_album"] = "Printscreens",
        // calendar app
        ["os.app_calendar"] = "Calendar",
        ["os.edit_filters"] = "Filters",
        ["os.edit_adjust"] = "Adjust",
        ["os.edit_brightness"] = "Brightness",
        ["os.edit_contrast"] = "Contrast",
        ["os.edit_hue"] = "Hue",
        ["os.edit_tint"] = "Tint",
        // guided OS tour
        ["os.settings_tour"] = "Take the tour",
        ["os.tour_next"] = "Next",
        ["os.tour_back"] = "Back",
        ["os.tour_skip"] = "Skip",
        ["os.tour_finish"] = "Done",
        ["os.tour_welcome_title"] = "Welcome to AetherOS",
        ["os.tour_welcome_body"] = "This is your phone: a home screen full of apps, with AetherLove as just one of them. Let's take a quick look around, it only takes a minute.",
        ["os.tour_homebtn_title"] = "Your home button",
        ["os.tour_homebtn_body"] = "You can always get back to the home screen with your home button, the one glowing at the bottom of the phone.",
        ["os.tour_pages_title"] = "Your home screen",
        ["os.tour_pages_body"] = "Your apps live here, spread over pages. Swipe left and right to move between them. The dots show which page you are on. Drag an icon to the edge of the screen. The page turns and the icon goes with it.",
        ["os.tour_widgets_title"] = "The widgets page",
        ["os.tour_widgets_body"] = "We just slid over to the widgets page for you. It sits to the left of your apps. It shows the clock with Eorzea time, your connection status and your latest notification. You can hold a card and drag it up or down.",
        ["os.tour_statusbar_title"] = "The status bar",
        ["os.tour_statusbar_body"] = "The highlighted strip at the very top shows the time, the battery and your connection to the AetherLove servers. It also shows how many notifications are waiting. A red warning icon appears there when the connection drops.",
        ["os.tour_shade_title"] = "Notifications",
        ["os.tour_shade_body"] = "Tap the top of the phone (or drag it down) to see your notifications, just like we did now. You also get quick settings and a brightness slider here. Tap a notification to open it, swipe it away to dismiss it.",
        ["os.tour_fake_notif_title"] = "Hello there!",
        ["os.tour_fake_notif_body"] = "This is what a notification looks like.",
        ["os.tour_badges_title"] = "Badges",
        ["os.tour_badges_body"] = "App icons show a little counter when something is waiting for you, like unread messages or new matches. Opening the app clears it. (Don't worry, you don't really have 67 of them.)",
        ["os.tour_dock_title"] = "The dock",
        ["os.tour_dock_body"] = "The bottom row stays on every page. It holds your favourite apps. Drag an icon in to keep it one tap away. Drag it back out when you change your mind.",
        ["os.tour_folders_title"] = "Folders",
        ["os.tour_folders_body"] = "Drop one icon on top of another and they become a folder. Tap the folder to open it. Rename it whenever you like. Drag an app out of the folder to put it back on the home screen. An empty folder disappears on its own.",
        ["os.tour_addapps_title"] = "More apps",
        ["os.tour_addapps_body"] = "Every app you removed is still in here. Your other Dalamud plugins are in here too. They can sit on the home screen like any other app.",
        ["os.tour_share_title"] = "Sharing",
        ["os.tour_share_body"] = "You can share venues, hangouts and more with your matches and friends. Sharing works from one app to another. Pick what to share, then choose where it goes. It arrives as a card you can tap.",
        ["os.tour_look_title"] = "Looks and layout",
        ["os.tour_look_body"] = "The highlighted Settings app is where you change how the phone looks. You can pick a theme, change the wallpaper, or upload your own. You can also resize the home grid and the phone itself.",
        ["os.tour_offline_title"] = "Offline",
        ["os.tour_offline_body"] = "You can keep using the phone even when AetherLove or one of its apps is offline. An app that needs the servers looks dimmed and shows a small marker. Every other app keeps working.",
        ["os.tour_arrange_title"] = "Move things around",
        ["os.tour_arrange_body"] = "You can drag an icon at any time. There is no edit mode to turn on first. Pick one up, carry it to a new spot, and let go. That spot can be on any page or in the bottom row.",
        ["os.tour_tilemenu_title"] = "Right-click an icon",
        ["os.tour_tilemenu_body"] = "Everything else an icon can do is one right-click away: put it in a folder, take it back out, mark it as seen, or take it off the home screen. Removing is never permanent, you can always put it back.",
        ["os.tour_homemenu_title"] = "Right-click the wallpaper",
        ["os.tour_homemenu_body"] = "Right-click any empty spot for the rest: add apps, make a folder, mark every new app as seen at once, or go and change the wallpaper.",
        ["os.tour_newapps_title"] = "New apps",
        ["os.tour_newapps_body"] = "When an update brings new apps, you get a list. You pick the ones you want. The apps you skip stay off the home screen until you ask for them. A new icon shows a small red 'new' label until you open it once.",
        ["os.tour_done_title"] = "That's the tour!",
        ["os.tour_done_body"] = "You can replay it any time from Settings. Now go explore the apps, and have fun out there.",
        ["os.photos_search_hint"] = "Search by name or location…",
        ["os.tt_prev"] = "Previous",
        ["os.tt_next"] = "Next",
        ["os.tt_edit"] = "Edit",
        ["os.tt_move"] = "Move to album",
        ["os.tt_share"] = "Share",
        ["os.tt_open_folder"] = "Open folder on disk",
        ["os.share_wallpaper"] = "Wallpaper",
        ["os.profile_edit_title"] = "Edit profile",
        ["os.profile_save"] = "Save",
        // home right-click menu (added after update 2.0.0)
        ["os.home_menu_lock_icons"] = "Lock icons",
        ["os.home_menu_unlock_icons"] = "Unlock icons",
        ["os.home_menu_wallpaper"] = "Change wallpaper",
        // news app tile rename (added after update 2.0.0)
        ["os.app_news_tile"] = "News",

        // battery easter egg (added after update 2.0.1)
        ["os.battery_grass_body"] = "We care about your health, don't forget to go out, hydrate and touch some grass ;-)",
        ["os.battery_grass_hint"] = "Please touch grass below to continue",
        ["os.settings_hide_battery_grass"] = "Hide the touch grass notification after empty battery",
        // levemetes (added after update 2.0.1)
        ["os.app_levemetes"] = "Levemetes",
        ["os.battery_grass_settings_hint"] = "(You can disable this joke under General in the Settings app)",

        // added after update 2.0.1
        ["os.menu_audio"] = "Audio settings",
        ["os.app_market"] = "Market",
        ["os.app_realtor"] = "Realtor",

        // added after update 2.1.3
        ["os.app_wayfinder"] = "Wayfinder",
        ["os.app_yapper"] = "Yapper",
        ["os.arcade_leaderboard"] = "Leaderboard",
        ["os.arcade_tab_weekly"] = "This week",
        ["os.arcade_tab_alltime"] = "All time",
        ["os.arcade_loading"] = "Loading...",
        ["os.arcade_empty"] = "No scores yet. Be the first!",
        ["os.arcade_error"] = "Couldn't load the leaderboard.",
        ["os.arcade_you"] = "You",
        ["os.arcade_back"] = "Back",

        // wallet app (added after update 2.2.1)
        ["os.app_wallet"] = "Wallet",

        // plappy birb (added after update 2.2.3)
        ["os.app_plappy"] = "Plappy Birb",

        // removable first-party apps (added after update 2.2.3)
        ["os.add_apps_section_removed"] = "Removed apps",
        ["os.add_apps_section_plugins"] = "Other plugins",

        // groove app (added after update 2.2.3)
        ["os.app_groove"] = "Groove",

        // store (added after update 2.2.3)
        ["os.app_store"] = "Store",
        ["os.store_preview_caption"] = "Preview only, not yet yours",
        ["os.store_preview_close"] = "Close the preview",
        ["os.store_preview_loading"] = "Loading the preview…",
        ["os.store_preview_failed"] = "Couldn't load the preview.",

        // added after update 2.2.3 (echo)
        ["os.app_echo"] = "Echo",
        // player and transport
        ["echo.play"] = "Play",
        ["echo.pause"] = "Pause",
        ["echo.mute"] = "Mute",
        ["echo.unmute"] = "Unmute",
        ["echo.skip"] = "Skip",
        ["echo.skip_tip"] = "Skip this video for everyone",
        ["echo.buffering"] = "Buffering…",
        ["echo.solo_idle"] = "Paste a link to start watching",
        ["echo.unavailable"] = "Unavailable",
        ["echo.close"] = "Close",
        // playlist
        ["echo.add"] = "Add",
        ["echo.add_hint"] = "Paste a YouTube or Twitch link",
        ["echo.added_by"] = "Added by {0}",
        ["echo.added_by_unknown"] = "Added by someone who left",
        ["echo.remove"] = "Remove",
        ["echo.queue_empty"] = "Nothing queued yet",
        ["echo.playlist_full"] = "The queue is full",
        ["echo.bad_link"] = "That is not a YouTube link",
        // room
        ["echo.room_code"] = "Room code",
        ["echo.copy_code"] = "Copy code",
        ["echo.copied"] = "Copied",
        ["echo.host_only"] = "Host only",
        ["echo.host_only_hint"] = "Only the host can control playback",
        ["echo.host_only_tip"] = "The host has locked the controls",
        ["echo.kick"] = "Remove",
        ["echo.kick_confirm"] = "Remove them from the room?",
        ["echo.leave_room"] = "Leave room",
        ["echo.end_room"] = "End room",
        ["echo.end_room_confirm"] = "End the room for everyone?",
        ["echo.you"] = "{0} (you)",
        ["echo.tab_playlist"] = "Playlist",
        ["echo.tab_members"] = "Members",
        ["echo.tab_chat"] = "Chat",
        ["echo.toggle_panel"] = "Show or hide the side panel",
        ["echo.new_messages"] = "{0} new messages",
        // room ended
        ["echo.room_ended_title"] = "Room ended",
        ["echo.room_ended_owner"] = "The host closed the room",
        ["echo.room_ended_owner_left"] = "The host disconnected",
        ["echo.room_ended_empty"] = "Everybody left",
        ["echo.room_ended_moderation"] = "This room was closed by moderation",
        ["echo.kicked_title"] = "Removed from the room",
        ["echo.kicked_body"] = "You were removed from {0}",
        // runtime and errors
        ["echo.runtime_title"] = "Echo needs its player",
        ["echo.runtime_body"] = "Video playback needs a small player component. It downloads once, and after that Echo is ready to play every time you open it.",
        ["echo.runtime_install"] = "Download it",
        ["echo.installing_title"] = "Getting Echo ready",
        ["echo.install_downloading"] = "Downloading…",
        ["echo.install_verifying"] = "Verifying…",
        ["echo.install_extracting"] = "Extracting…",
        ["echo.install_failed_title"] = "Download failed",
        ["echo.reinstall"] = "Reinstall",
        ["echo.retry"] = "Try again",
        ["echo.host_failed_title"] = "The player stopped",
        ["echo.host_failed_body"] = "It could not be restarted. Please try again.",
        ["echo.protocol_title"] = "Player version mismatch",
        ["echo.protocol_body"] = "Reinstall the Echo player to continue.",
        ["echo.embed_blocked_title"] = "This video cannot be embedded",
        ["echo.embed_blocked_body"] = "Its owner does not allow playback outside YouTube.",
        ["echo.video_gone_title"] = "Video unavailable",
        ["echo.video_gone_body"] = "It was removed or made private.",
        ["echo.bad_id_title"] = "Bad link",
        ["echo.bad_id_body"] = "That video id does not look right.",
        ["echo.player_error_title"] = "Playback failed",
        ["echo.player_error_body"] = "Something went wrong loading this video.",

        // avatar rings (added after update 2.2.3)
        ["rings.section_title"] = "Avatar ring",
        ["rings.picker_title"] = "Avatar ring",
        ["rings.none"] = "No ring",
        ["rings.none_owned_title"] = "No rings yet",
        ["rings.none_owned_body"] = "Avatar rings are decorative frames drawn around your picture, visible to everyone. Buy them with Sparks in the Store.",
        ["rings.open_store"] = "Open the Store",
        ["rings.preview_hint"] = "Everyone sees your ring wherever your picture shows.",

        // aetherling (added after update 2.2.3)
        ["os.app_aetherling"] = "Aetherling",

        // added after update 2.3.3
        ["os.app_notes"] = "Notes",
        ["os.app_together"] = "AetherParty",
        ["os.app_calculator"] = "Calculator",
        ["os.folder_utilities"] = "Utilities",
        ["os.app_timers"] = "Timers",
        ["os.app_racooner"] = "Racooner",
        ["os.app_skyswarm"] = "Sky Swarm",
        ["os.app_eordle"] = "Eordle",
        ["os.app_racer"] = "Lumi Racer",

        // echo playback settings (added after update 2.2.3)
        ["echo.settings_tip"] = "Playback settings",
        ["echo.settings_quality"] = "Video quality",
        ["echo.quality_auto"] = "Auto",
        ["echo.quality_720"] = "720p",
        ["echo.quality_1080"] = "1080p",
        ["echo.settings_captions"] = "Subtitles",
        ["echo.settings_autoplay"] = "Play the next video automatically",
        ["echo.settings_software_render"] = "Software rendering",

        // home screen management (added after update 2.3.4)
        ["os.home_menu_add_app"] = "Add app",
        ["os.home_menu_add_folder"] = "Add folder",
        ["os.tile_menu_remove_app"] = "Remove app",
        ["os.tile_menu_mark_seen"] = "Mark seen",
        ["os.home_menu_mark_seen"] = "Mark all apps as seen",
        ["os.tile_menu_take_out"] = "Take out of folder",
        ["os.tile_menu_move_to_folder"] = "Move to folder",
        ["os.tile_menu_remove_folder"] = "Remove folder",
        ["os.folder_delete_title"] = "Remove folder",
        ["os.folder_delete_body"] = "Remove \"{0}\" and the {1} apps inside it, or keep the apps and put them back on the home screen?",
        ["os.folder_delete_remove"] = "Remove folder and apps",
        ["os.folder_delete_keep"] = "Keep apps",

        // new app offer (added after update 2.3.4)
        ["os.new_apps_title"] = "New apps now available",
        ["os.new_apps_body"] = "This update brought some new apps. Pick the ones you want on your home screen. You can add the rest later from the home screen menu.",
        ["os.new_apps_continue"] = "Continue",
        ["os.app_levemetes_about"] = "Classified ads for Eorzea: post what you offer, browse what everyone else wants.",
        ["os.app_market_about"] = "Universalis prices, sale history and alerts for the items you keep an eye on.",
        ["os.app_realtor_about"] = "Empty housing plots across every world, updated as they open up.",
        ["os.app_wayfinder_about"] = "Track down waypoints out in the world and earn sparks for finding them.",
        ["os.app_yapper_about"] = "Short posts and pictures, follows, replies and private messages.",
        ["os.app_wallet_about"] = "Your sparks, plus every currency your character carries and how close it is to its cap.",
        ["os.app_store_about"] = "Spend sparks on themes, avatar rings and other trinkets.",
        ["os.app_groove_about"] = "A remote for whatever your PC is playing, plus the game's own volume sliders.",
        ["os.app_echo_about"] = "Watch videos together with friends, in sync.",
        ["os.app_notes_about"] = "Notes and lists, kept on this machine and nowhere else.",
        ["os.app_together_about"] = "Start or join a party, invite friends, and earn more sparks playing together.",
        ["os.app_calculator_about"] = "A graphing calculator, keypad and all.",
        ["os.app_timers_about"] = "Ocean Fishing, the Cactpot and the other clocks worth watching.",
        ["os.app_aetherling_about"] = "Attune an Aethercore and raise whatever hatches out of it.",
        ["os.app_snake_about"] = "The old one. Eat, grow, do not bite yourself.",
        ["os.app_stacker_about"] = "Stack the blocks, clear the lines, blame the last piece.",
        ["os.app_breaker_about"] = "Bounce a ball into bricks until there are no bricks.",
        ["os.app_meteor_about"] = "Shoot down what falls before it lands on your cities.",
        ["os.app_invaders_about"] = "Rows of aliens come down. You have one cannon.",
        ["os.app_muncher_about"] = "Clear the maze, dodge the ghosts, chase them while you can.",
        ["os.app_plappy_about"] = "Tap to flap. The pipes are not sorry.",
        ["os.app_doom_about"] = "The 1993 shooter, running inside your phone.",
        ["os.app_sudoku_about"] = "Nine by nine, a fresh grid whenever you want one.",
        ["os.app_racooner_about"] = "Catch what falls and get it home to the dens.",
        ["os.app_skyswarm_about"] = "Fly through the swarm for as long as you can hold on.",
        ["os.app_eordle_about"] = "One Eorzean word a day, six guesses.",
        ["os.app_racer_about"] = "Enter your Lumi in races and win sparks and prizes.",

        // together mode (added after update 2.4.0)
        ["os.party_title"] = "AetherParty",
        ["os.party_members"] = "{0}/{1}",
        ["os.party_start"] = "Start a party",
        ["os.party_join"] = "Join",
        ["os.party_join_hint"] = "Party code",
        ["os.party_code"] = "Code {0}",
        ["os.party_copied"] = "Copied!",
        ["os.party_leave"] = "Leave party",
        ["os.party_end"] = "End party",
        ["os.party_ended"] = "The party has ended.",
        ["os.party_dismiss"] = "Okay",
        ["os.party_invite"] = "Invite",
        ["os.party_error_full"] = "That party is full.",
        ["os.party_error_kicked"] = "You were removed from that party.",
        ["os.party_error_in_party"] = "You are already in a party.",
        ["os.party_error_not_found"] = "No party found for that code.",
        ["os.party_error_generic"] = "That did not work. Try again.",
        ["os.party_invite_message"] = "{0} invites you to a party! Open the phone's widget page and join with code {1}.",
        ["os.party_activity_echo"] = "Watch party live",
        ["os.party_activity_wayfinder"] = "Party hunt live",
        ["os.party_activity_racer"] = "Lumi race live",
        ["os.party_activity_generic"] = "Activity in progress",
        ["os.party_activity_open"] = "Open",
        ["os.party_chat_title"] = "Party chat",
        ["os.party_chat_hint"] = "Message your party...",
        ["os.party_chat_empty"] = "No messages yet. Say hi!",
        // message translation (added after update 2.4.0)
        ["os.translate"] = "Translate",
        ["os.translate_retry"] = "Translate again",
        ["os.translate_pending"] = "Translating...",
        ["os.translate_show_original"] = "Show original",
        ["os.translate_settings"] = "Translation settings",
        ["os.translate_consent_title"] = "Translate messages?",
        ["os.translate_consent_body"] = "Translations come from Google Translate. The text you translate is sent over the internet to Google, a third party. Nothing else is sent. Nothing is translated unless you ask for it.",
        ["os.translate_consent_enable"] = "Enable translations",
        ["os.translate_consent_cancel"] = "Not now",
        // translation onboarding + offer (added after update 2.4.0)
        ["os.translate_demo_source"] = "Bonjour ! On part explorer ensemble ?",
        ["os.translate_demo_result"] = "Hello! Shall we go exploring together?",
        ["os.translate_offer_title"] = "Translate any message",
        ["os.translate_offer_body"] = "This update adds translations. Right-click any chat message, profile bio or post and pick Translate.",
        ["os.translate_offer_enable_go"] = "Enable and continue",
        ["os.translate_offer_skip_go"] = "Continue without",
        ["os_onboarding.translate_title"] = "Understand everyone",
        ["os_onboarding.translate_body"] = "You can translate chats, profiles and posts into your language. Right-click any text and pick Translate.",
        ["os_onboarding.translate_later"] = "You can change all of this later in Settings, under Languages.",

        // together onboarding (added after update 2.4.0)
        ["os.party_intro_title_0"] = "Do things together",
        ["os.party_intro_body_0"] = "A party puts you and up to three friends on one screen. Share the code and they join. When one of you starts a watch party or a Wayfinder hunt, everyone else can join it.",
        ["os.party_intro_title_1"] = "Chatting together",
        ["os.party_intro_body_1"] = "Party chat sits in a small bar next to the phone. New messages appear there without you opening anything.",
        ["os.party_intro_title_2"] = "Bring your Aetherling",
        ["os.party_intro_body_2"] = "Together mode lets you share your Aetherling and see your party members' Aetherlings. Everything is opt-in.",
        ["os.party_intro_pets_show"] = "Show all Aetherlings from joined party members",
        ["os.party_intro_pets_share"] = "Let party members see mine",
        ["os.party_intro_pets_size"] = "How big should they be?",
        ["os.party_intro_f0_code"] = "One code invites everyone: share it, they join.",
        ["os.party_intro_f0_activity"] = "When one of you starts a watch party or a Wayfinder hunt, everyone else can join it.",
        ["os.party_intro_f0_size"] = "Up to four of you at once.",
        ["os.party_intro_f1_widget"] = "Manage the party from its card on the phone's widget page.",
        ["os.party_intro_f1_dock"] = "The roster stands beside the phone, so you see who is around at a glance.",
        ["os.party_intro_f1_chat"] = "Chat with your friends even when they are on other servers or data centers.",
        ["os.party_intro_pets_show_hint"] = "Their Aetherlings gather around yours out on the screen.",
        ["os.party_intro_pets_share_hint"] = "Members of your parties can see your Aetherling beside theirs.",
        ["os.party_in_party"] = "Currently in a party · {0}",
        ["os.party_intro_next"] = "Go on",
        ["os.party_intro_start"] = "Start",
        ["os.party_pet_size_0"] = "XS",
        ["os.party_pet_size_1"] = "S",
        ["os.party_pet_size_2"] = "M",
        ["os.party_pet_size_3"] = "L",
        ["os.party_pet_size_4"] = "XL",

        // widget page (added after update 2.4.0)
        ["os.widget_add_new"] = "Add new widget",
        ["os.widget_settings"] = "Widget settings",
        ["os.widget_remove"] = "Remove this widget",
        ["os.widget_clock"] = "Clock",
        ["os.widget_status"] = "Status",
        ["os.widget_notifications"] = "Notifications",
        ["os.widget_party"] = "AetherParty",

        // screenshot import consent (added after update 2.4.0)
        ["os.photos_screenshots_offer"] = "Add your game screenshots to Photos? Tap here to choose.",
        ["os.party_settings"] = "AetherParty settings",
        ["os.party_kick_tip"] = "Remove {0} from the party",
        ["os.party_kick_title"] = "Remove from party?",
        ["os.party_kick_body"] = "{0} will be removed from the party, and cannot join this one again.",
        ["os.party_kick_go"] = "Remove",
        ["os.party_chat_joined"] = "{0} joined the party",
        ["os.party_chat_wayfinder"] = "{0} started a Wayfinder hunt. Tap to join.",
        ["os.party_chat_racer"] = "{0} started a Lumi race. Tap to join.",
        ["os.party_chat_echo"] = "{0} opened an Echo room. Tap to join.",

        // listing boosts (added after update 2.5.2)
        ["os.boost_boosted"] = "Boosted",
        ["os.boost_featured"] = "Featured",
        ["os.boost_left"] = "Boosted, {0} left",
        ["os.boost_left_count"] = "You have {0} left.",
        ["os.boost_none"] = "You have no boosts. Get one in the Store.",
        ["os.boost_go"] = "Boost",
        ["os.boost_confirm_venue"] = "Boost this venue?",
        ["os.boost_confirm_ad"] = "Boost this ad?",
        ["os.boost_confirm_body"] = "It goes to the top of the list for 5 days. Pick the effect it wears.",
        ["os.boost_confirm_extend"] = "It is boosted for {0} more. This adds 5 days on top. Pick the effect it wears.",
        ["os.boost_style_0"] = "Aurora",
        ["os.boost_style_1"] = "Ember",
        ["os.boost_style_2"] = "Prism",
        ["os.boost_style_3"] = "Starlight",
        ["os.boost_venue_action"] = "Boost this venue",
        ["os.boost_ad_action"] = "Boost this ad",
        ["os.boost_get"] = "Get a boost",
        ["os.boost_shelf"] = "Your boosts",
        ["os.boost_pick"] = "Pick what to boost",
        ["os.boost_no_targets"] = "You have no live venue or ad to boost yet.",
        ["os.boost_done"] = "Boosted for {0}.",
        ["os.boost_venues"] = "Venues",
        ["os.boost_ads"] = "Ads",

        // echo playlist import (added after update 2.5.3)
        ["echo.playlist_confirm"] = "Add all {0} videos in this playlist?",
        ["echo.playlist_capped"] = "This playlist has {0} videos. Add the first {1}?",
        ["echo.playlist_add_all"] = "Add all",
        ["echo.playlist_add_one"] = "Add this video",
        ["echo.playlist_reading"] = "Reading the playlist...",
        ["echo.playlist_failed"] = "Echo could not read that playlist. Try the video link instead.",
        ["echo.playlist_added"] = "Added {0} videos.",
        ["os.echo_home_watch_playlist"] = "Playlists only work in a room. Start or join a room first.",

        // phone shell menu (added after update 2.5.3)
        ["os.phone_menu_exit"] = "Turn the phone off",
        ["os.phone_menu_minimize"] = "Minimise the phone",
        ["os.phone_menu_open"] = "Open the phone",
        ["os.phone_menu_lock"] = "Lock the position",
        ["os.phone_menu_unlock"] = "Unlock the position",
        // echo live streams (added after update 2.5.3)
        ["echo.live"] = "LIVE",
        ["echo.live_needs_player_title"] = "Live streams need a newer player",
        ["echo.live_needs_player_body"] = "This player cannot play live streams. Ordinary videos still work.",
        ["echo.live_needs_player_update"] = "A newer player is ready. Install it to watch live streams.",
    };
}
