namespace AetherOS.Apps.Eordle.Words;

internal static partial class EordleWords
{
    /// <summary>Curated common German answers, chosen to need no umlaut or eszett.</summary>
    private const string AnswersDeRaw = @"
ABEND ABTEI ACKER ADLER AGENT AHORN AKTIE AKTIV ALARM ALBUM ALTAR AMPEL
AMSEL ANGEL ANGST ANKER ANMUT ANTIK ANZUG APFEL ARENA ARMEE AROMA ASCHE
ATLAS ATMEN AUTOR
BADEN BAUCH BAUEN BAUER BEBEN BEERE BEIGE BESEN BETEN BEUTE BIBER BIENE
BINDE BIRKE BIRNE BISON BLATT BLECH BLICK BLIND BLITZ BLOND BLUME BLUSE
BODEN BOGEN BOHNE BOMBE BORKE BOXEN BRAND BRAUN BRAUT BREIT BRETT BRIEF
BRISE BRUCH BRUST BUCHE BUCHT BULLE BUSCH
CELLO CHAOS CHILI CHIPS CLOWN COACH COMIC COUCH CREME CURRY
DACHS DAMPF DATEI DATUM DAUER DECKE DEGEN DELTA DICHT DIELE DINGO DIODE
DISCO DOCHT DOGGE DRAHT DRAMA DRANG DRUCK DUELL DUMPF
EBBEN EBENE ECKIG EIFER EIMER EISEN EISIG EMSIG ENGEL ENKEL ERBEN ERBSE
ERNST ERNTE ESSEN ESSIG ETAGE ETHIK EXAKT EXTRA
FABEL FADEN FAHNE FALKE FALLE FARBE FASAN FAUST FEDER FEGEN FEIER FEIGE
FELGE FERNE FERSE FEUER FINNE FIRMA FISCH FLACH FLINK FLOTT FLUCH FLUSS
FOLGE FOLIE FORUM FRAGE FRECH FREMD FRIST FROST FUCHS FUNKE
GABEL GARBE GASSE GEBET GECKO GEIER GEIGE GEIST GENAU GENRE GERNE GERTE
GESTE GLANZ GLATT GLEIS GNADE GREIS GRIFF GRILL GROLL GRUBE GRUND GUMMI
GUNST GURKE
HABEN HAFEN HAFER HAGEL HAKEN HALLE HANDY HARFE HAUCH HAUEN HEBEL HEBEN
HECKE HEGEN HEIDE HENNE HERDE HIRSE HITZE HOBEL HOLEN HONIG HORDE HOTEL
HUMOR HUPEN
IDEAL IMKER INDEX INSEL IRREN
JACKE JAGEN JEANS JOKER JUBEL JUNGE JUWEL
KABEL KAKAO KAMEL KAMIN KAMPF KANAL KANTE KARTE KASSE KATER KATZE KAUEN
KEGEL KEHLE KELLE KERBE KERZE KETTE KISTE KLANG KLAUE KLEID KLIMA KLUFT
KNABE KNALL KNAPP KNETE KNIFF KNOPF KOALA KOBRA KOHLE KOMET KONTO KRACH
KRAFT KRANZ KREBS KREIS KREUZ KRIEG KRIMI KRONE KRUME KUGEL KUNDE KUNST
KURVE
LABEN LACHE LACHS LADEN LAGER LAMPE LANZE LARVE LASER LATTE LAUCH LAUNE
LEBEN LEDER LEERE LEGEN LEHRE LEIER LEISE LESEN LICHT LIEBE LILIE LIMIT
LINDE LINIE LINSE LISTE LITER LOBEN LOCKE LOGIK LOKAL LOSEN LOTSE LUCHS
LUNGE LUXUS
MACHT MAGEN MAGIE MAGMA MAKEL MALER MANGO MAPPE MARKE MARKT MASSE MAUER
MEISE MENGE MESSE METER MIENE MILBE MILCH MILDE MITTE MOBIL MODEL MODEM
MOTIV MOTOR MOTTE MULDE MUMIE MUSIK MUTIG
NABEL NACHT NADEL NAGEL NAGEN NAHEN NARBE NEBEL NEFFE NELKE NIERE NOBEL
NOTAR NOTIZ NUDEL
OBHUT OFFEN OLIVE ONKEL OPFER ORDEN ORGEL ORKAN OTTER OZEAN
PALME PANDA PAPST PARTY PASTA PASTE PAUKE PAUSE PEDAL PERLE PFAHL PFAND
PFEIL PFERD PFLUG PILOT PIRAT PISTE PIZZA PLAGE PLANE PLATZ POKAL POKER
POLKA PRISE PROBE PROSA PUDEL PUMPE PUNKT PUPPE
QUALM QUARK QUARZ QUITT QUOTE
RADAR RADIO RAGEN RAMPE RASEN RATTE RAUCH RAUPE RECHT REDEN REGAL REGEN
REIFE REIHE RENTE RIESE RINDE RINNE RITZE ROBBE ROGEN ROLLE ROMAN ROUTE
RUDEL RUDER RUFEN RUHEN RUHIG RUINE RUNDE
SACHE SAGEN SAHNE SAITE SALAT SALBE SALON SALTO SAMEN SANFT SAUER SAUNA
SCHAF SCHAL SCHEU SCHUH SEGEL SEGEN SEHEN SEHNE SEIDE SEIFE SEITE SEKTE
SENAT SENSE SICHT SILBE SIPPE SIRUP SITTE SKALA SOCKE SONDE SONNE SORGE
SORTE SPALT SPECK SPEER SPIEL SPION SPORT SPULE SPURT STAAT STADT STAHL
STALL STAMM STAND START STAUB STEIF STEIL STEIN STERN STETS STIEL STIER
STIFT STILL STIRN STOFF STOLZ STROM STUBE STUFE STUHL STUMM STURM STURZ
SUCHE SUMME SUMPF SUPPE
TADEL TAFEL TANGO TANNE TANTE TASSE TASTE TAUBE TEICH TEMPO TENOR THEKE
THEMA TIEFE TIGER TINTE TISCH TITEL TOAST TOBEN TONNE TORTE TOSEN TRAUM
TREUE TRICK TRIST TRUHE TULPE TURBO
UMWEG UMZUG UNFUG UNION UNRAT UNTAT URALT
VATER VILLA VIRUS VISUM VOGEL VOKAL VOTUM
WAAGE WACHE WACHS WAGEN WAISE WALZE WANGE WANNE WARZE WATEN WEBEN WEIDE
WEILE WEISE WELLE WELPE WERFT WESPE WESTE WETTE WIEGE WIESE WINDE WITWE
WOCHE WOGEN WOLKE WOLLE WONNE WRACK WUCHT WUNDE WURST
YACHT
ZANGE ZEBRA ZEDER ZEILE ZELLE ZIEGE ZIRKA ZITAT ZUCHT ZUNGE ZUTAT ZWANG
ZWECK ZWERG ZWIST
APRIL BLANK BLUFF BOWLE DELLE ELEND FATAL FROMM GALLE GELEE GLIED HAGER
HUMUS KARRE KRASS KRUMM LOTTO NONNE OPIUM PLATT PRALL SERUM STARR TABAK
TAPIR THESE
";

    /// <summary>Accepted German guesses beyond the answer pool: further nouns, inflected verb forms,
    /// plurals and function words.</summary>
    private const string GuessesDeRaw = @"
ACHSE ADERN AFFEN AHNEN AKTEN ALGEN ALLES ANBAU ANRUF ARMUT ATOLL AUGEN
AUTOS AXIOM
BARDE BARON BASIS BEIDE BELAG BERGE BERUF BETON BEVOR BEZUG BLASE BLUTE
BONUS BOOTE BORTE BRAVO BUSSE
CHROM
DAMEN DANKE DEKAN DEPOT DIEBE DIESE DIWAN DOGMA DOSEN DOSIS DUNST DURCH
EHREN EILEN EINEN EINST ELFEN ENDEN ENTEN ETWAS ETHOS EULEN
FAKIR FALTE FARCE FAUNA FAZIT FEHDE FIBEL FILME FJORD FLAIR FLORA FOKUS
FOTOS FRACK GABEN
GARDE GEBEN GEHEN GENIE GILDE GRIPS GRUFT
HALDE HARKE HASEN HAUBE HEXEN HIRTE HORST HOSEN HUNDE HYMNE
IDEEN IKONE INDIZ
JAHRE JEDER JETZT
KADER KAJAK KARAT KEINE KEKSE KILOS KINOS KIPPE KODEX KOLIK KOMIK KNAUF
KUPPE
LAKEN LASSO LEHNE LEINE LEVEL LIANE LIMBO LITZE LOTUS LUMEN LUNTE
MAMBA MANIE MASKE MEILE MEIST MIEZE MILAN MINZE MIXER MOTTO MUFFE
NEBEN NEXUS NICHT NOTEN NUGAT
OCHSE OHREN OPERN ORDER OSTEN
PACHT PAKET PANNE PAPPE PARKA PATER PELLE PESTO PFIFF PFOTE PFUND PHASE
PILZE PLUMP POLYP PORTO POSSE PREIS PRINZ PULLE
RABEN RANKE RASSE REBEN REGIE ROSEN RUBIN RUMPF RUNGE
SALVE SAMBA SCHAR SOGAR SOHLE SOLCH SPATZ SPIND SPRIT STOPP STROH STUCK
STUPS STUTE
TAGEN TARIF TATZE TENNE TEXTE THRON TIERE TOPAS TOREN TRAKT TRANK TRIEB
TROPF TROSS TRUPP TUMOR TWIST
UHREN UMBAU UNKEN UNTEN UNTER
VASEN VLIES VORNE
WATTE WEDER WELCH WENIG WICHT WIPPE WITZE WOBEI WOHER WOHIN WOMIT WORTE
WUCHS
ZACKE ZECKE ZEHEN ZIELE ZINKE ZONEN ZOTTE ZUBER ZUDEM ZUNFT ZUVOR ZWIRN
ATMET BADET BELLT BETET BIEGT DANKT DENKT DIENT DREHT DROHT FEHLT FOLGT
FRAGT KAUFT KLAGT KLEBT KOCHT KOMMT LACHT LEHRT LEIHT LERNT LIEBT LIEGT
MEINT MERKT NIMMT NUTZT PACKT PASST PLANT RAUBT REDET REIST RENNT SIEHT
SINGT SINKT SITZT SPART STEHT SUCHT TANZT TEILT WARNT WEINT WIRFT WOHNT
ZAHLT ZEIGT ZIEHT
BAUTE BEBTE HOLTE JAGTE KAMEN LASEN LEBTE LOBTE MALTE SAGTE SAHEN TOBTE
BLIEB FIELE GABST GEHST GIBST HATTE HOLST KAMST LIEST RIEFE SAGST WAREN
WARST WURDE
EBBTE EHRTE EILTE ERBTE FEGTE HEGTE HUPTE IRRTE KAUTE LEGTE NAGTE NAHTE
RAGTE RUHTE TAGTE TOSTE WAGTE WEBTE WEHTE WOGTE ZAGTE
BLIES BRACH KROCH SCHOB SCHUF SPUKT STIEG WUSCH
AMBRA BIWAK BONZE BRAUE EKZEM FESCH FIDEL JUNTA KLAMM LASCH OKAPI PEGEL
PINIE RITUS STELE STOLA TAIGA TANGA TONER
";
}
