namespace AetherOS.Apps.Eordle.Words;

internal static partial class EordleWords
{
    /// <summary>Curated common French answers, accents normalized to bare letters (the Motus convention).</summary>
    private const string AnswersFrRaw = @"
ACIER ACTIF ADIEU AGILE AIDER AIGLE AIMER AINSI ALORS AMBRE AMOUR AMPLE
ANCRE ANGLE ANNEE APPUI APRES ARBRE ARENE ARMEE ARMER ATOUT AUCUN AUSSI
AUTEL AUTRE AVANT AVARE AVIDE AVION AVOIR AVRIL
BAGUE BALAI BALLE BANAL BANDE BARBE BARRE BASSE BATON BEAUX BELLE BERGE
BICHE BIERE BIJOU BILLE BLANC BLOND BOIRE BOITE BOMBE BONTE BORNE BOTTE
BOULE BOURG BRAVE BRISE BRUIT BRUME BRUNE BUCHE BULLE BUSTE BUTTE
CABLE CADET CADRE CALME CANAL CANNE CARRE CARTE CASSE CAUSE CESSE CHAIR
CHAMP CHANT CHAOS CHAUD CHENE CHERE CHIEN CHOIX CHOSE CHUTE CIBLE CIRER
CITER CIVIL CLAIR CODER COEUR COLIS COLLE COMTE CONGE CONTE CORDE CORPS
COTON COUDE COURS COURT CRABE CRAIE CRANE CREER CREME CREPE CRIER CRISE
CROIX CRUEL CUIRE CULTE CURER CYCLE
DANSE DATER DATTE DEBUT DECOR DEGRE DENSE DEPOT DETTE DEUIL DIGNE DINDE
DINER DOIGT DORER DOSER DOUCE DOUTE DOUZE DOYEN DRAME DROIT DROLE DUREE
DURER
ECART ECHEC ECOLE ECRAN ELEVE ELIRE ENCRE ENFER ENJEU ENNUI ENTRE EPAIS
EPICE EPOUX ESSAI ETAGE ETANG ETAPE ETUDE EXACT EXCES EXODE
FABLE FACON FAIRE FARCE FATAL FAUTE FAUVE FEMME FENTE FERME FICHE FIERE
FILER FILET FILLE FINAL FINIR FIXER FLAIR FLEUR FOIRE FOLIE FOLLE FONTE
FORCE FORET FORME FORTE FOULE FOYER FRAIS FRANC FREIN FRERE FROID FRUIT
FUMEE FUMER FUSEE
GAINE GALET GAMIN GARDE GARER GATER GAVER GAZON GEANT GELER GENIE GENOU
GENRE GERBE GERER GESTE GIFLE GIVRE GLACE GLOBE GOMME GORGE GOSSE GRACE
GRAIN GRAND GRAVE GRIVE GUIDE
HACHE HAINE HALER HALTE HARDI HATER HAUTE HERBE HEROS HEURE HIBOU HIVER
HONTE HOTEL HOULE HUILE HUMER HUTTE HYMNE
IDEAL IDOLE IMAGE IMPUR INDEX INOUI ISSUE
JADIS JAMBE JAUNE JETER JEUNE JOLIE JOUER JOUET JUGER JUPON JURER JUSTE
KAYAK KOALA
LACER LACHE LAINE LAMPE LANCE LAPIN LARGE LARME LASSE LAVER LECON LEGER
LENTE LEVER LEVRE LIANE LIBRE LIEGE LIGNE LIGUE LILAS LIMON LINGE LISSE
LITRE LIVRE LOCAL LOGER LOUER LOUPE LOURD LOYAL LUEUR LUNDI LUTIN LUTTE
MAGIE MAIRE MALIN MAMAN MANIE MARDI MAREE MARGE MARIN MASSE MATCH MATIN
MEDIA MELER MELON MENER MERCI MESSE METAL METRE MEUTE MIEUX MILLE MIMER
MINCE MINER MISER MIXER MOINE MOINS MONDE MORAL MOTIF MOULE MOYEN MUGIR
MULET MUNIR MUSEE
NACRE NAGER NAINE NAPPE NAVET NEIGE NETTE NEUVE NICHE NIECE NOBLE NOEUD
NOIRE NONNE NOTER NOUER NUAGE NUIRE NULLE
OASIS OBEIR OCEAN ODEUR OFFRE OMBRE ONCLE ONGLE OPERA ORAGE ORDRE ORGUE
OSIER OTAGE OUEST OUTIL OVALE
PAGNE PAIRE PALME PANNE PAROI PASSE PATTE PAUSE PAVER PAYER PECHE PEINE
PELER PENTE PERDU PERLE PERTE PESER PETIT PHARE PHOTO PIANO PIECE PIEGE
PILER PINCE PIQUE PISTE PITIE PLACE PLAGE PLAIE PLEIN PLIER PLUIE PLUME
POCHE POELE POEME POIDS POING POINT POIRE POMME PORTE POSER POSTE POULE
PRIER PRISE PROIE PROSE PRUNE PUITS PUNIR PURGE
QUAND QUART QUETE QUEUE
RADIO RAIDE RAMER RASER RATER RAVIR RAYON REGAL REGLE REINE REPAS REPOS
REVER RHUME RICHE RIMER RIVAL ROCHE RODER RONDE ROSEE ROTIR ROUGE ROUTE
ROYAL RUCHE RUSER
SABLE SABRE SAINE SAINT SALER SALLE SALON SALUT SANTE SAPIN SAUCE SAULE
SAUNA SAVON SCENE SEIZE SELLE SEMER SERRE SEUIL SEULE SIEGE SIGNE SINGE
SOBRE SOEUR SOLDE SOMME SONGE SORTE SOUPE STADE STAGE STYLE STYLO SUCER
SUCRE SUITE SUJET SUPER
TABLE TACHE TAIRE TALON TALUS TANTE TAPIS TARIF TARIR TASSE TAUPE TAXER
TEMPS TENIR TENTE TERNE TERRE TEXTE THEME TIEDE TIGRE TIRER TISSU TITRE
TOILE TOMBE TONNE TORDU TORSE TOTAL TRACE TRAIN TRAIT TREVE TRIBU TRIER
TROIS TRONC TRONE TUILE TUYAU
UNITE URINE USAGE USINE USUEL UTILE
VACHE VAGUE VALSE VASTE VEINE VENIN VENIR VENTE VERBE VERRE VERTE VERTU
VESTE VEUVE VIDER VIEIL VIEUX VIGNE VILLE VINGT VIRER VISER VITRE VIVRE
VOILE VOLER VOTER VOTRE VOUER VOUTE
WAGON YACHT ZEBRE ZESTE
APPEL BIDON BILAN BISON BISOU BOCAL BONUS CACAO CANOE CAPOT CARGO CEDRE
CHALE CLONE COACH COLZA COMBO CREDO CUMIN DECES DELTA DEMON DEPIT DIVAN
DUVET ETAIN FAKIR FIBRE FLASH FORUM GALOP GAMME GELEE GITAN GLAND GNOME
GOLFE GRADE GRIEF GUEPE HAMAC HARPE HERON IGLOO IMPOT JOKER KARMA LABEL
LAGON LASER LATIN LOTUS LOYER LYCEE MACON MAGMA MAMBA METEO MICRO MODEM
MOTEL NAVAL NYLON OPIUM PATIO PAUME PIVOT POLKA QUOTA RADAR RATIO RECIF
RECIT REFUS RELAI RENNE REPLI RUBAN RUGBY SALSA SAMBA SATIN SCEAU SERUM
SIROP SONAR SOSIE STELE TABAC TABOU TAROT TATOU TEMPO TENOR TIARE TOTEM
TULLE TURBO VALET VENUE VERSO VIDEO VIGIE VIRUS VISON VODKA VOLET
";

    /// <summary>Accepted French guesses beyond the answer pool: further nouns, conjugated forms,
    /// plurals and function words.</summary>
    private const string GuessesFrRaw = @"
ABCES ACCES ACTES AGENT AIDES AIGRE AIGUE AILES ALGUE AMANT AMIES ANGES
ARMES ATLAS AUBES AVEUX
BAIES BAINS BANCS BASES BETES BLEUE BLEUS BOEUF BORDS BOUTS BRAVO BRINS
BRUNS BUTEE
CANON CARAT CIEUX CLOUS CLOWN COBRA COINS COUPE COUPS COUTE CUBES CURES
DAMES DENTS DIEUX DRAPS DUNES
ECRIT ELFES EPEES ETAIS ETAIT ETIEZ ETANT
FAITS FEVES FILMS FLOTS FOINS FONDS FOURS
GANTS GOUTS GRECS GRUES
HALLE HOUES
IDEES ILOTS IVRES
JOIES JOURS JUPES
LACES LIENS LIEUX LIONS LOUPS LUNES
MAINS MODES MURES
NOIRS NOTES
OEUFS ONDES
PAINS PAGES PERES PIEDS PILES PLANS PLATS PONTS PORCS PORTS PRETS
RANGS RATES REVES RIRES ROBES ROSES RUSES
SAUTS SOIES SOINS
TETES TOITS TOURS TROUS TYPES
VELOS VENTS VOEUX VOIES ZONES
AIMEE AIMES AIMEZ AIDEZ ALLEZ AURAI AURAS AUREZ AVAIS AVAIT AVIEZ AVONS
BOIRA BUVEZ CROIS CROIT DEVEZ DEVRA DIRAI DIRAS DIREZ DOIVE DONNE FAITE
FERAI FERAS FEREZ JOUES JOUEZ MANGE MONTE PARLA PARLE PENSE PREND RESTE
SAURA SAVEZ TIENS TIENT VIENS VIENT VOYEZ
COUPA CREVE CRIEE DANSA DORME DURES FILEE GARES JETEE JOUEE LAVEE LEVEE
LOUEE MENEE NOTEE POSEE RAMEE RUSEE SALEE SEMEE TIREE VOLEE VOTEE
SERAI SERAS SEREZ VERRA VIVRA PARTI SORTI DORMI SERVI SENTI SUIVI FINIT
PUNIT SUBIT BOUGE
FUTUR MAJOR ORNEE PALES RUDES SAGES SALES VIDES VIVES
";
}
