namespace AetherOS.Apps.Eordle.Words;

internal static partial class EordleWords
{
    /// <summary>Curated common English answers.</summary>
    private const string AnswersEnRaw = @"
ABOUT ABOVE ABUSE ACTOR ACUTE ADAPT ADMIT ADOPT ADORE ADULT AFTER AGAIN
AGENT AGILE AGING AGREE AHEAD AISLE ALARM ALBUM ALERT ALIEN ALIGN ALIKE
ALIVE ALLEY ALLOW ALLOY ALONE ALONG ALOUD ALTAR ALTER AMBER AMEND AMPLE
AMUSE ANGEL ANGER ANGLE ANGRY ANKLE ANNEX ANNOY APART APPLE APPLY APRON
ARENA ARGUE ARISE ARMOR AROMA AROSE ARRAY ARROW ASIDE ASSET ATLAS ATTIC
AUDIO AUDIT AVOID AWAIT AWAKE AWARD AWARE AWFUL
BACON BADGE BADLY BAKER BALMY BANJO BARGE BASIC BASIL BASIN BASIS BATCH
BATHE BATON BEACH BEARD BEAST BEGAN BEGIN BEGUN BEING BELLY BELOW BENCH
BERRY BIBLE BIRCH BIRTH BISON BLACK BLADE BLAME BLAND BLANK BLAST BLAZE
BLEAK BLEED BLEND BLESS BLIMP BLIND BLINK BLISS BLOCK BLOND BLOOD BLOOM
BLOWN BLUFF BLUNT BLUSH BOARD BOAST BONUS BOOST BOOTH BORED BOSSY BOTCH
BOUND BOXER BRAIN BRAKE BRAND BRASS BRAVE BREAD BREAK BREED BRICK BRIDE
BRIEF BRINE BRING BRINK BRISK BROAD BROIL BROKE BROOK BROOM BROTH BROWN
BRUSH BUDDY BUGGY BUILD BUILT BULKY BUNCH BUNNY BURNT BURST BUYER
CABIN CABLE CACHE CANDY CANOE CARGO CAROL CARRY CARVE CATCH CAUSE CEASE
CEDAR CELLO CHAIN CHAIR CHALK CHAMP CHANT CHAOS CHARM CHART CHASE CHEAP
CHEAT CHECK CHEEK CHEER CHESS CHEST CHIEF CHILD CHILI CHILL CHIME CHINA
CHIRP CHOIR CHOKE CHORD CHORE CHOSE CHUNK CHURN CIDER CIGAR CIRCA CIVIC
CIVIL CLAIM CLAMP CLASH CLASP CLASS CLEAN CLEAR CLERK CLICK CLIFF CLIMB
CLING CLOAK CLOCK CLONE CLOSE CLOTH CLOUD CLOWN CLUMP COACH COAST COBRA
COCOA COLON COLOR COMET COMIC CORAL COUCH COUGH COULD COUNT COURT COVER
CRACK CRAFT CRANE CRASH CRATE CRAWL CRAZE CRAZY CREAM CREED CREEK CREEP
CREPE CREST CRIED CRIME CRISP CROSS CROWD CROWN CRUDE CRUEL CRUMB CRUSH
CRUST CURLY CURRY CURSE CURVE CYCLE
DADDY DAILY DAIRY DAISY DANCE DATED DEALT DEATH DEBIT DEBUT DECAY DECOR
DECOY DELAY DELTA DEMON DENIM DENSE DEPOT DEPTH DERBY DETER DEVIL DIARY
DIGIT DINER DIRTY DITCH DIVER DIZZY DODGE DOING DONOR DONUT DOUBT DOUGH
DOZEN DRAFT DRAIN DRAKE DRAMA DRANK DRAWN DREAD DREAM DRESS DRIED DRIFT
DRILL DRINK DRIVE DRONE DROOL DROVE DROWN DRUNK DRYER DUSTY DUTCH DWELL
DYING
EAGER EAGLE EARLY EARTH EASEL EATEN EBONY EIGHT ELBOW ELDER ELECT ELITE
EMAIL EMBER EMPTY ENACT ENEMY ENJOY ENTER ENTRY EQUAL EQUIP ERASE ERROR
ESSAY ETHIC EVENT EVERY EXACT EXCEL EXERT EXILE EXIST EXTRA
FABLE FACET FAINT FAIRY FAITH FALSE FANCY FATAL FAULT FAVOR FEAST FENCE
FERRY FETCH FEVER FIBER FIELD FIEND FIERY FIFTH FIFTY FIGHT FINAL FINCH
FIRST FISHY FIXED FLAIR FLAKE FLAME FLANK FLASH FLASK FLEET FLESH FLICK
FLING FLINT FLIRT FLOAT FLOCK FLOOD FLOOR FLOUR FLOWN FLUID FLUKE FLUSH
FLUTE FOAMY FOCAL FOCUS FOGGY FORCE FORGE FORGO FORTH FORTY FORUM FOUND
FRAIL FRAME FRANK FRAUD FRESH FRIED FRONT FROST FROWN FROZE FRUIT FUDGE
FULLY FUNKY FUNNY FUZZY
GAUGE GAUNT GAVEL GECKO GENIE GENRE GHOST GIANT GIDDY GIVEN GIVER GLADE
GLAND GLARE GLASS GLAZE GLEAM GLIDE GLOBE GLOOM GLORY GLOSS GLOVE GOING
GOOSE GORGE GRACE GRADE GRAIN GRAND GRANT GRAPE GRAPH GRASP GRASS GRAVE
GRAVY GRAZE GREAT GREED GREEN GREET GRIEF GRILL GRIME GRIND GRIPE GROAN
GROOM GROSS GROUP GROVE GROWL GROWN GUARD GUESS GUEST GUIDE GUILD GUILT
GUISE GUSTO
HABIT HANDY HAPPY HARDY HARSH HASTE HASTY HATCH HAUNT HAVEN HAVOC HAZEL
HEART HEAVE HEAVY HEDGE HEFTY HEIST HELLO HENCE HILLY HINGE HIPPO HITCH
HOARD HOBBY HOIST HOLLY HONEY HONOR HORSE HOTEL HOUND HOUSE HOVER HUMAN
HUMID HUMOR HUNCH HURRY HUSKY HYENA
IDEAL IDIOM IDIOT IGLOO IMAGE IMPLY INBOX INDEX INFER INGOT INLET INNER
INPUT IRONY ISSUE IVORY
JELLY JEWEL JOINT JOKER JOLLY JUDGE JUICE JUICY JUMBO JUMPY
KAYAK KEBAB KHAKI KIOSK KITTY KNACK KNEAD KNEEL KNELT KNIFE KNOCK KNOWN
KOALA
LABEL LABOR LADEN LADLE LAGER LANCE LAPEL LAPSE LARGE LASER LATCH LATER
LATTE LAUGH LAYER LEAFY LEARN LEASE LEASH LEAST LEAVE LEDGE LEGAL LEMON
LEVEL LEVER LIGHT LILAC LIMIT LINEN LINER LIVER LLAMA LOBBY LOCAL LODGE
LOFTY LOGIC LOGIN LOOSE LORRY LOSER LOUSY LOVER LOWER LOYAL LUCKY LUNAR
LUNCH LUNGE LYRIC
MACRO MADAM MAGIC MAGMA MAIZE MAJOR MAKER MANGO MANOR MAPLE MARCH MARRY
MARSH MATCH MAYBE MAYOR MEANT MEDAL MEDIA MELON MERCY MERGE MERIT MERRY
METAL METER METRO MICRO MIDST MIGHT MIMIC MINER MINOR MINTY MINUS MIRTH
MODAL MODEL MODEM MOIST MOLAR MONEY MONTH MOODY MORAL MOTEL MOTIF MOTOR
MOTTO MOUND MOUNT MOURN MOUSE MOUTH MOVER MOVIE MOWER MUDDY MUMMY MUNCH
MURAL MUSIC MUSTY
NANNY NASAL NASTY NAVAL NEEDY NERVE NEVER NEWER NEWLY NICER NIECE NIGHT
NINTH NOBLE NOISE NOISY NOMAD NORTH NOTCH NOTED NOVEL NURSE NYLON
OASIS OCCUR OCEAN OFFER OFTEN OLIVE ONION ONSET OPERA OPTIC ORBIT ORDER
ORGAN OTHER OTTER OUGHT OUNCE OUTER OVERT OWNER OXIDE OZONE
PAINT PANDA PANEL PANIC PANSY PAPER PARKA PARTY PASTA PASTE PATCH PATIO
PAUSE PEACE PEACH PEARL PECAN PEDAL PENAL PENNY PERCH PERIL PESKY PETAL
PETTY PHASE PHONE PHOTO PIANO PICKY PIECE PILOT PINCH PINKY PITCH PIVOT
PIXEL PIZZA PLACE PLAID PLAIN PLANE PLANK PLANT PLATE PLAZA PLEAD PLUCK
PLUMB PLUME PLUMP PLUSH POINT POISE POKER POLAR POLKA POPPY PORCH POSSE
POUCH POUND POWER PRANK PRESS PRICE PRIDE PRIME PRINT PRIOR PRISM PRIZE
PROBE PRONE PRONG PROOF PROSE PROUD PROVE PROWL PROXY PRUNE PSALM PULSE
PUNCH PUPIL PUPPY PUREE PURSE
QUACK QUAIL QUAKE QUALM QUART QUEEN QUERY QUEST QUEUE QUICK QUIET QUILL
QUILT QUIRK QUITE QUOTA QUOTE
RABBI RABID RADAR RADIO RAINY RAISE RALLY RANCH RANGE RAPID RATIO RAVEN
RAZOR REACH REACT READY REALM REBEL RECAP REFER REIGN RELAX RELAY RELIC
REMIX REPAY REPLY RERUN RESET RESIN RETRO RHYME RIDER RIDGE RIFLE RIGHT
RIGID RINSE RIPEN RISKY RIVAL RIVER ROAST ROBIN ROBOT ROCKY ROGUE ROOMY
ROOST ROTOR ROUGE ROUGH ROUND ROUTE ROVER ROWDY ROYAL RUGBY RULER RUMOR
RURAL RUSTY
SADLY SAINT SALAD SALON SALSA SALTY SANDY SATIN SAUCE SAUNA SAVOR SAVVY
SCALD SCALE SCALP SCANT SCARE SCARF SCARY SCENE SCENT SCOLD SCONE SCOOP
SCOPE SCORE SCORN SCOUT SCOWL SCRAP SCREW SCRUB SEDAN SEIZE SENSE SERUM
SERVE SETUP SEVEN SEWER SHACK SHADE SHADY SHAFT SHAKE SHAKY SHALL SHAME
SHAPE SHARD SHARE SHARK SHARP SHAVE SHAWL SHEAR SHEEN SHEEP SHEER SHEET
SHELF SHELL SHIFT SHINE SHINY SHIRT SHOCK SHONE SHOOK SHOOT SHORE SHORT
SHOUT SHOVE SHOWN SHOWY SHRED SHRUB SHRUG SIEGE SIGHT SILKY SILLY SINCE
SIXTH SIXTY SKATE SKIER SKILL SKIRT SKULL SLAIN SLANG SLANT SLASH SLATE
SLEEK SLEEP SLEET SLICE SLICK SLIDE SLIME SLIMY SLING SLOPE SLOTH SMALL
SMART SMASH SMEAR SMELL SMILE SMIRK SMOKE SMOKY SNACK SNAIL SNAKE SNARE
SNARL SNEAK SNEER SNIFF SNORE SNOUT SNOWY SOAPY SOBER SOGGY SOLAR SOLID
SOLVE SONIC SORRY SOUND SOUTH SPACE SPADE SPARE SPARK SPAWN SPEAK SPEAR
SPECK SPEED SPELL SPEND SPENT SPICE SPICY SPIKE SPILL SPINE SPIRE SPITE
SPLIT SPOIL SPOKE SPOON SPORE SPORT SPOUT SPRAY SPREE SQUAD SQUAT SQUID
STACK STAFF STAGE STAIN STAIR STAKE STALE STALK STALL STAMP STAND STARE
STARK START STASH STATE STEAK STEAL STEAM STEED STEEL STEEP STEER STERN
STICK STIFF STILL STING STINT STOCK STOIC STOLE STOMP STONE STOOD STOOL
STOOP STORE STORK STORM STORY STOUT STOVE STRAP STRAW STRAY STRIP STRUT
STUCK STUDY STUFF STUMP STUNG STUNT STYLE SUAVE SUGAR SUITE SUNNY SUPER
SURGE SUSHI SWAMP SWARM SWEAR SWEAT SWEEP SWEET SWELL SWEPT SWIFT SWINE
SWING SWIRL SWORD SWORE SWORN SYRUP
TABBY TABLE TACIT TAKEN TAKER TALLY TALON TAMER TANGO TANGY TAPER TARDY
TASTE TASTY TAUNT TAWNY TEACH TEASE TEDDY TEETH TEMPO TENOR TENSE TENTH
TEPID TERSE THANK THEFT THEIR THEME THERE THESE THICK THIEF THIGH THING
THINK THIRD THORN THOSE THREE THREW THROB THROW THUMB THUMP TIDAL TIGER
TIGHT TILDE TIMER TIMID TIPSY TITLE TOAST TODAY TOKEN TONIC TOOTH TOPIC
TORCH TOTAL TOTEM TOUCH TOUGH TOWEL TOWER TOXIC TRACE TRACK TRACT TRADE
TRAIL TRAIN TRAIT TRASH TREAT TREND TRIAL TRIBE TRICK TRIED TROLL TROOP
TROUT TRUCE TRUCK TRULY TRUNK TRUST TRUTH TULIP TUMMY TUNIC TURBO TUTOR
TWEAK TWEED TWEET TWICE TWIRL TWIST
UDDER ULCER ULTRA UNCLE UNDER UNDID UNDUE UNFIT UNIFY UNION UNITE UNITY
UNTIL UPPER UPSET URBAN USAGE USHER USUAL UTTER
VAGUE VALID VALOR VALUE VALVE VAPOR VAULT VEGAN VENOM VENUE VERGE VERSE
VIDEO VIGIL VIGOR VILLA VINYL VIOLA VIRAL VIRUS VISIT VISOR VITAL VIVID
VOCAL VODKA VOGUE VOICE VOTER VOUCH VOWEL
WACKY WAFER WAGER WAGON WAIST WALTZ WASTE WATCH WATER WEARY WEAVE WEIGH
WEIRD WHALE WHARF WHEAT WHEEL WHERE WHICH WHIFF WHILE WHINE WHIRL WHISK
WHITE WHOLE WHOSE WIDEN WIDER WIDOW WIDTH WIELD WINCE WINDY WISER WITCH
WITTY WOKEN WOMAN WOMEN WOODY WOOZY WORLD WORRY WORSE WORST WORTH WOULD
WOUND WOVEN WRATH WRECK WRIST WRITE WRONG WROTE
YACHT YEARN YEAST YIELD YOUNG YOUTH
ZEBRA ZESTY ZONAL
";

    /// <summary>Accepted English guesses beyond the answer pool.</summary>
    private const string GuessesEnRaw = @"
ABACK ABASE ABATE ABBEY ABBOT ABHOR ABIDE ABODE ABORT ACORN ACRES ACRID
ACTED ADAGE ADDED ADDER ADEPT ADMIN ADOBE ADORN AGATE AGAVE AGLOW AGONY
AIDED AIDES AILED AIMED AIRED ALGAE ALIBI ALLOT ALOFT ALOHA ALOOF AMASS
AMBLE AMISS AMITY AMONG AMPED ANGST ANIME ANNUL ANODE ANTIC ANVIL AORTA
APHID APNEA ARBOR ARDOR AREAS ARGON ARMED ARSON ASHEN ASHES ASKED ATOLL
ATONE AUGUR AUNTS AURAS AVAIL AVERT AVIAN AWOKE AXIAL AXIOM AXLES AZURE
BACKS BAGEL BAKED BAKES BALER BALES BALLS BANDS BANGS BANKS BARNS BARON
BASAL BASED BASES BASTE BATED BATHS BATTY BAYOU BEADS BEADY BEAMS BEANS
BEARS BEATS BEECH BEEFY BEEPS BEETS BEFIT BEGAT BEGET BELCH BELIE BELLE
BELLS BELTS BERTH BESET BETAS BEVEL BIDET BIKER BIKES BILGE BILLS BINGE
BINGO BIOME BIPED BIRDS BLARE BLEAT BLEEP BLITZ BLOAT BLOBS BLOKE BLOTS
BLURB BLURS BOARS BOATS BODES BOILS BOLTS BONDS BONED BONES BONGO BOOKS
BOOMS BOOTS BOOZE BORAX BORNE BOSOM BOUGH BOWED BOWEL BOWLS BOXED BOXES
BRACE BRAID BRAWL BRAWN BRAYS BREWS BRIBE BRIMS BROOD BROWS BRUNT BRUTE
BUCKS BUDGE BUFFS BUGLE BULBS BULGE BULLY BUMPS BUMPY BUNKS BUOYS BURLY
BURNS BURPS BUSES BUSHY BUSTS BUTTE BUXOM
CABAL CABBY CACAO CACTI CADDY CADET CAGED CAGES CAIRN CAKED CAKES CALLS
CALMS CAMEL CAMEO CAMPS CANAL CANES CANNY CANON CAPED CAPER CAPES CARAT
CARDS CARED CARER CARES CARET CAROB CARPS CARTS CASED CASES CASKS CASTE
CASTS CATER CATTY CAULK CAVED CAVES CEDED CEDES CELLS CENTS CHAFE CHAFF
CHAPS CHARS CHATS CHEWS CHEWY CHICK CHIDE CHIMP CHINS CHIPS CHITS CHIVE
CHOMP CHOPS CHUCK CHUGS CHUMP CHUMS CHUTE CINCH CITED CITES CLACK CLAMS
CLANG CLANK CLANS CLAPS CLAWS CLAYS CLEAT CLEFT CLIME CLIPS CLOGS CLOTS
CLOVE CLUBS CLUCK CLUED CLUES CLUNG CLUNK COALS COATS CODED CODES COILS
COINS COLTS COMAS COMBO COMBS COMES CONCH CONDO CONES CONIC COOKS COOLS
COPED COPES COPSE CORDS CORED CORES CORGI CORKS CORNS CORNY COSTS COVEN
COVET COWED COWER CRABS CRAGS CRAMP CRAMS CRANK CRASS CRAVE CREAK CREPT
CRICK CRIES CROAK CROCK CROCS CRONE CRONY CROOK CROPS CROUP CROWS CRYPT
CUBED CUBES CUBIC CUFFS CULTS CUMIN CUPID CURBS CURDS CURED CURES CURIO
CURLS CURVY CUSPS CYNIC CYSTS
DAMES DAMPS DARED DARES DARTS DATES DAUNT DAWNS DAZED DEALS DEANS DEBTS
DECAF DECKS DEEDS DEEMS DEFER DEIGN DEITY DELVE DEMOS DENTS DESKS DETOX
DIALS DICED DICES DIETS DIMLY DINED DINES DINGO DINGY DIODE DIRGE DISCO
DISCS DITTO DITTY DIVED DIVES DOCKS DODGY DOGMA DOILY DOLES DOLLS DOLLY
DOMED DOMES DOOMS DOORS DOPES DORMS DOSED DOSES DOTED DOTES DOUSE DOVES
DOWDY DOWEL DOWNS DOWRY DOZED DOZES DRAGS DRAPE DRAWS DREGS DRIER DRIES
DRIPS DROID DROLL DROOP DROPS DRUMS DRYLY DUCTS DUDES DUELS DUETS DUKES
DULLY DUMMY DUMPS DUNCE DUNES DUSKY DUVET DWELT
EARLS EARNS EASED EASES EAVES EBBED EDGED EDGES EDICT EDIFY EDITS EERIE
EGGED EGRET EJECT ELATE ELEGY ELFIN ELOPE ELUDE ELVES EMBED EMCEE EMOTE
ENDED ENDOW ENSUE ENVOY EPICS EPOCH EPOXY ERECT ERODE ERUPT ETHER ETHOS
EVADE EVENS EVICT EVOKE EXALT EXAMS EXITS EXPEL EXTOL EXUDE
FACED FACES FACTS FADED FADES FAILS FAIRS FAKED FAKER FAKES FALLS FAMED
FANGS FARCE FARED FARES FARMS FASTS FATED FATES FATTY FAUNA FAWNS FAXED
FAXES FEARS FEEDS FEELS FEIGN FELLS FELON FENDS FERAL FERNS FETAL FETES
FEUDS FIBRE FICUS FIEFS FILED FILER FILES FILLS FILLY FILMS FILMY FILTH
FINDS FINED FINER FINES FIRED FIRES FIRMS FISTS FIVES FIZZY FJORD FLAGS
FLAIL FLAPS FLARE FLATS FLAWS FLAYS FLEAS FLECK FLEES FLIES FLOPS FLORA
FLOSS FLOWS FLUBS FLUES FLUFF FLUNG FLUNK FOALS FOAMS FOILS FOIST FOLDS
FOLKS FONTS FOODS FOOLS FORAY FORDS FORKS FORMS FORTE FORTS FOULS FOYER
FRAYS FREED FREER FREES FRETS FRIAR FRILL FRISK FRIZZ FROCK FROGS FROND
FROTH FUELS FUMED FUMES FUNDS FUNGI FURRY FUSED FUSES FUSSY FUTON
GABLE GAFFE GAILY GAINS GAITS GALAS GALES GAMER GAMES GAMMA GANGS GAPED
GAPES GASPS GATED GATES GAUZE GAWKY GAZED GAZES GEARS GEESE GEEKS GEEKY
GENES GENUS GERMS GIFTS GILLS GIRLS GIRTH GLEAN GLENS GLINT GLITZ GLOAT
GLOBS GLUED GLUES GLYPH GNARL GNASH GNATS GNAWS GNOME GOADS GOALS GOATS
GODLY GONGS GOODS GOOEY GOONS GOOFS GOOFY GORES GORSE GOUGE GOURD GOWNS
GRABS GRAFT GRAMS GRATE GRIDS GRIMY GRINS GRIST GRITS GROIN GROPE GROUT
GROWS GRUBS GRUEL GRUFF GRUNT GUANO GUAVA GULCH GULLS GULPS GUMBO GUMMY
GUPPY GUSTS GUSTY GUTSY
HACKS HAIKU HAILS HAIRS HAIRY HALLS HALTS HALVE HANDS HANGS HARES HARMS
HARPS HATED HATER HATES HAULS HAUTE HAWKS HEADS HEALS HEAPS HEARD HEARS
HEATS HEELS HEIRS HELIX HELMS HELPS HERBS HERDS HERON HERTZ HEXED HIDES
HIGHS HIKED HIKER HIKES HILLS HILTS HINTS HIPPY HIRED HIRES HIVES HOBOS
HOLDS HOLED HOLES HOMES HONED HONES HONKS HOODS HOOFS HOOKS HOOPS HOOTS
HOPED HOPES HORDE HORNS HOSED HOSES HOSTS HOTLY HOWLS HUFFY HULKS HULLS
HUMPS HUMUS HUNKS HUNTS HURLS HURTS HUSKS HUTCH HYMNS
ICILY ICING ICONS IDLED IDLER IDLES IDOLS IMBUE IMPEL INANE INAPT INCUR
INEPT INERT INKED INLAY IONIC IRATE IRKED ISLES ITCHY IVIES
JADED JAILS JAUNT JAZZY JEANS JEEPS JEERS JERKS JERKY JESTS JETTY JIBES
JIFFY JOEYS JOINS JOKED JOKES JOLTS JOUST JOWLS JUMPS JUNKS JUNTA JUROR
KARMA KEELS KEEPS KEYED KICKS KILLS KILNS KILTS KINDS KINGS KINKS KINKY
KIWIS KNAVE KNEES KNITS KNOBS KNOLL KNOTS KUDOS
LACED LACES LACKS LAIRS LAKES LAMBS LAMPS LANDS LANES LANKY LARKS LARVA
LASSO LASTS LATHE LAUDS LAWNS LEACH LEADS LEAKS LEAKY LEAPS LEAPT LEECH
LEEKS LEERS LEERY LEGGY LEMUR LENDS LEPER LEVEE LIARS LICKS LIENS LIFTS
LIKED LIKEN LIKES LIMBO LIMBS LIMES LIMPS LINED LINES LINGO LINKS LIONS
LISPS LISTS LITER LITHE LIVED LIVEN LIVES LOADS LOAFS LOAMY LOANS LOATH
LOBES LOCKS LOCUS LOFTS LOGOS LOINS LONGS LOOKS LOOMS LOONS LOOPS LOOPY
LOOTS LOPES LORDS LOSES LOTUS LOVES LUCID LULLS LUMEN LUMPS LUMPY LUNGS
LURCH LURED LURES LURID LURKS LUTES LYING LYMPH
MACAW MACES MAIDS MAILS MAIMS MAINS MALES MALLS MALTS MAMBO MANES MANGY
MANIA MANIC MANLY MARES MARKS MASKS MASON MASTS MATED MATES MATHS MAULS
MAUVE MAXIM MAZES MEALS MEATS MEATY MEDIC MELDS MELEE MELTS MEMOS MENDS
MENUS MEOWS MESAS MESSY METES MIDGE MILES MILKS MILKY MILLS MIMES MINCE
MINDS MINED MINES MINKS MINTS MIRED MIRES MISTS MISTY MITER MITES MITTS
MOANS MOATS MOCKS MODES MOLDS MOLDY MOLES MOLTS MONKS MOODS MOONS MOORS
MOOSE MOPED MOPES MORPH MOSSY MOTES MOTHS MOULD MOULT MOUSY MUCKY MUCUS
MUFFS MUGGY MULCH MULES MUMPS MURKY MUSED MUSES MUSHY MUSKY MUTED MUTES
MUTTS MYRRH MYTHS
NAILS NAIVE NAKED NAMED NAMES NAPES NAVEL NEARS NECKS NEEDS NEIGH NESTS
NEWTS NEXUS NICHE NICKS NIFTY NINES NIPPY NOBLY NODAL NODES NOOKS NOOSE
NORMS NOSES NOSEY NOTES NOUNS NUDGE NUKES NULLS NUTTY NYMPH
OAKEN OATHS OBESE OBEYS ODDER ODDLY ODORS OFFAL OGLED OGLES OGRES OILED
OINKS OKAPI OKAYS OLDEN OLDER OMENS OMITS OOZED OOZES OPALS OPENS OPTED
ORATE ORCAS OUSTS OUTDO OVALS OVARY OVENS OVOID OWING OWNED OXBOW
PACED PACES PACKS PACTS PADDY PAGED PAGER PAGES PAILS PAINS PAIRS PALER
PALES PALMS PANES PANGS PANTS PAPAL PARCH PARED PARES PARKS PARSE PARTS
PATHS PATTY PAVED PAVES PAWNS PEAKS PEALS PEARS PECKS PEEKS PEELS PEEPS
PEERS PELTS PENCE PERKS PERKY PERMS PESOS PESTS PHONY PICKS PIERS PIGGY
PILED PILES PILLS PINED PINES PINGS PINKS PINTS PIOUS PIPED PIPES PIQUE
PITHY PLAYS PLEAS PLEAT PLIED PLIES PLODS PLOPS PLOTS PLOWS PLOYS PLUGS
PLUMS PODGY POEMS POETS POKED POKES POLES POLLS POLYP PONDS PORES PORTS
POSED POSER POSES POSTS POUTS PRAMS PRAWN PRAYS PREEN PREPS PREYS PRIED
PRIES PRIMP PRODS PROMS PROPS PROWS PRUDE PSYCH PUCKS PUFFS PUFFY PULLS
PULPS PULPY PUMAS PUMPS PUNKS PUNTS PURRS PUSHY PUTTS PYGMY PYLON
QUADS QUAFF QUAYS QUELL QUIPS QUITS QUOTH
RACED RACER RACES RACKS RAFTS RAGED RAGES RAIDS RAILS RAINS RAKED RAKES
RAMPS RANKS RANTS RASPS RASPY RATED RATES RATTY RAVED RAVES RAYON READS
REAMS REAPS REARS REBUS REBUT RECUR REDID REEDS REEFS REEKS REELS REFIT
REHAB REINS RELIT REMIT RENAL RENDS RENEW RENTS REPEL RESTS REUSE REVEL
REVUE RHINO RIDES RIFTS RILES RINDS RINGS RIOTS RIPER RISEN RISES RITES
ROADS ROAMS ROARS ROBED ROBES ROCKS RODEO ROLES ROLLS ROOFS ROOMS ROOTS
ROPED ROPES ROSES ROUSE ROUTS ROWED ROWER RUBLE RUDDY RUINS RULED RULES
RUMBA RUMPS RUNES RUNGS RUNTS RUSES RUSTS
SACKS SAGAS SAGGY SAILS SAKES SALES SALVE SANDS SANER SAPPY SASSY SAVED
SAVER SAVES SCABS SCAMP SCAMS SCANS SCARS SCOFF SCOOT SCOUR SCRAM SCUBA
SCUFF SCULL SEALS SEAMS SEARS SEATS SECTS SEEDS SEEDY SEEKS SEEMS SEEPS
SEERS SELLS SENDS SEPIA SERFS SHAMS SHANK SHEDS SHEIK SHINS SHIPS SHIRE
SHOAL SHOES SHOPS SHOTS SHOWS SHUCK SHUNS SHUNT SHUSH SHUTS SIDED SIDES
SIDLE SIEVE SIFTS SIGHS SIGNS SILKS SILLS SILOS SINGE SINGS SINKS SINUS
SITAR SITES SIZED SIZES SKEWS SKIDS SKIES SKIFF SKIMP SKIMS SKINS SKIPS
SKITS SKULK SKUNK SLABS SLACK SLAMS SLAPS SLATS SLAYS SLEDS SLEWS SLINK
SLIPS SLITS SLOBS SLOGS SLOOP SLOPS SLOSH SLOTS SLUGS SLUMS SLUNG SLUNK
SLURP SLURS SLUSH SLYLY SMACK SMELT SMITE SMITH SMOCK SMOGS SNAGS SNAPS
SNIDE SNIPE SNIPS SNOBS SNOOP SNORT SNUBS SNUCK SNUFF SOAKS SOARS SOCKS
SOFAS SOILS SOLES SOLOS SONGS SOOTY SOPPY SORTS SOULS SOUPS SOUPY SOURS
SPANS SPARS SPASM SPATS SPEWS SPIED SPIES SPINS SPINY SPITS SPLAT SPLAY
SPOOF SPOOK SPOOL SPOTS SPRIG SPUDS SPURN SPURS SPURT STABS STAGS STAID
STARS STATS STAVE STAYS STEMS STEPS STEWS STILE STILT STOKE STONY STOPS
STOWS STRUM STUBS STUDS STUNS SUEDE SUING SULKS SULKY SUMAC SUNUP SURFS
SURLY SWABS SWANS SWAPS SWATS SWAYS SWIGS SWIMS SWOON SWOOP SYNCS
TABOO TACKS TACKY TACOS TAILS TAKES TALES TALKS TAMED TAMES TANKS TAPES
TARPS TARTS TASKS TAUPE TAXED TAXES TEAMS TEARS TEEMS TEENS TEENY TELLS
TEMPT TENDS TENET TENTS TERMS TESTS TESTY TEXTS THAWS THINS THUDS TIARA
TICKS TIDES TIERS TILED TILES TILLS TILTS TIMES TINGE TINTS TIRED TIRES
TITHE TOADS TOGAS TOILS TOLLS TOMBS TONAL TONED TONES TONGS TOOLS TORSO
TOTES TOURS TOUTS TOWNS TOYED TRAMS TRAPS TRAWL TRAYS TREES TREKS TRIMS
TRIOS TRITE TROTS TROVE TUBAS TUBBY TUBES TUCKS TUFTS TUMOR TUNAS TUNED
TUNER TUNES TURFS TURNS TUSKS TUTUS TWANG TWIGS TWINE TWINS TYING TYPED
TYPES TYPOS
UNCAP UNCUT UNITS UNLIT UNMET UNTIE UNZIP UPEND URGED URGES USERS USING
USURP UVULA
VALES VALET VANES VAPID VASES VEERS VEILS VEINS VENTS VERBS VESTS VEXED
VEXES VIALS VICAR VICES VIEWS VILER VINES VISAS VISTA VIXEN VOIDS VOLES
VOLTS VOTES
WADED WADES WAFTS WAGED WAGES WAILS WAITS WAIVE WAKES WALKS WALLS WANDS
WANED WANES WANTS WARDS WARES WARMS WARNS WARPS WARTS WASPS WATTS WAVED
WAVES WAXED WAXEN WAXES WEANS WEARS WEEDS WEEDY WEEKS WEEPS WELDS WELLS
WELTS WHACK WHELP WHIMS WHINY WHIPS WHIRS WHOOP WICKS WILDS WILES WILLS
WILTS WINDS WINES WINGS WINKS WIPED WIPER WIPES WIRED WIRES WISPS WISPY
WOMBS WOODS WOOLY WORDS WORDY WORKS WORMS WORMY WRAPS WREAK WRENS WRING
WRITS WRUNG
XENON XYLEM
YANKS YARDS YARNS YAWNS YEARS YELLS YELPS YOKES YOLKS YOURS YUCCA YUMMY
ZIPPY ZONED ZONES ZOOMS
";
}
