using System.Collections.Generic;

namespace AetherOS.Apps.Realtor.Localization;

/// <summary>The Realtor app's own UI strings, merged into the central tables at app registration.</summary>
public static class AppStrings
{
    private static readonly IReadOnlyDictionary<string, string> En = new Dictionary<string, string>
    {
        // added after update 2.0.1 (realtor)
        ["os.realtor_pick_world"] = "Choose a world",
        ["os.realtor_search_world"] = "Search worlds...",
        ["os.realtor_hero_sub"] = "open plots on {0}",
        ["os.realtor_stale"] = "reports up to {0} old",
        ["os.realtor_district_open"] = "{0} open",
        ["os.realtor_district_none"] = "None open",
        ["os.realtor_loading"] = "Checking the housing wards...",
        ["os.realtor_offline"] = "Housing data is unavailable right now. PaissaDB may be busy; try again in a moment.",
        ["os.realtor_retry"] = "Try again",
        ["os.realtor_unknown_world"] = "Pick a world to see its open plots.",
        ["os.realtor_ward_plot"] = "Ward {0} · Plot {1}",
        ["os.realtor_size_s"] = "S",
        ["os.realtor_size_m"] = "M",
        ["os.realtor_size_l"] = "L",
        ["os.realtor_filter_small"] = "Small",
        ["os.realtor_filter_medium"] = "Medium",
        ["os.realtor_filter_large"] = "Large",
        ["os.realtor_chip_fc"] = "FC",
        ["os.realtor_chip_personal"] = "Personal",
        ["os.realtor_lotto_accepting_open"] = "Accepting entries",
        ["os.realtor_lotto_results_open"] = "Results phase",
        ["os.realtor_lotto_unavailable"] = "Between lotteries",
        ["os.realtor_phase_label"] = "Current phase",
        ["os.realtor_time_label"] = "Time remaining",
        ["os.realtor_entries"] = "{0} entries",
        ["os.realtor_fcfs"] = "First come, first served",
        ["os.realtor_checked"] = "checked {0} ago",
        ["os.realtor_empty_district"] = "No open plots here right now.",
        ["os.realtor_empty_filtered"] = "Nothing matches these filters.",
        ["os.realtor_unit_m"] = "m",
        ["os.realtor_unit_h"] = "h",
        ["os.realtor_unit_d"] = "d",
        ["os.realtor_menu_tour"] = "App tour",
        ["os.realtor_tour_welcome_title"] = "Welcome to Realtor",
        ["os.realtor_tour_welcome_body"] = "Every open housing plot in Eorzea, right on your phone. Stop running ward to ward; see what's free before you ever leave the aetheryte.",
        ["os.realtor_tour_welcome_f1"] = "Browse every world, district, and data center",
        ["os.realtor_tour_welcome_f2"] = "Filter by plot size and who can buy: FC or personal",
        ["os.realtor_tour_welcome_f3"] = "Live lottery countdowns and freshness on every plot",
        ["os.realtor_tour_browse_title"] = "Scout like a pro",
        ["os.realtor_tour_browse_body"] = "Pick a world at the top right, then dive into a district to see each open plot with its ward, number, and price.",
        ["os.realtor_tour_browse_f1"] = "Your own world is selected automatically",
        ["os.realtor_tour_browse_f2"] = "The five districts show open counts at a glance",
        ["os.realtor_tour_browse_f3"] = "Size and tenant filters narrow the hunt",
        ["os.realtor_tour_lotto_title"] = "Mind the lottery",
        ["os.realtor_tour_lotto_body"] = "Most plots sell by lottery. Realtor shows which phase a plot is in and how long you have left to enter or claim.",
        ["os.realtor_tour_lotto_f1"] = "Entry and results countdowns per plot",
        ["os.realtor_tour_lotto_f2"] = "See how many entries a plot already has",
        ["os.realtor_tour_lotto_f3"] = "Every plot shows when a scout last checked it",
        ["os.realtor_tour_credit"] = "All housing data is crowdsourced by players running PaissaHouse and shared through PaissaDB. They are awesome!",
        ["os.realtor_tour_credit_link"] = "Visit PaissaDB",
        ["os.realtor_tour_reopen_hint"] = "You can reopen this tour any time with the question mark up top.",
    };

    private static readonly IReadOnlyDictionary<string, string> De = new Dictionary<string, string>
    {
        // added after update 2.0.1 (realtor)
        ["os.realtor_pick_world"] = "Welt auswählen",
        ["os.realtor_search_world"] = "Welten durchsuchen...",
        ["os.realtor_hero_sub"] = "freie Grundstücke auf {0}",
        ["os.realtor_stale"] = "Meldungen bis zu {0} alt",
        ["os.realtor_district_open"] = "{0} frei",
        ["os.realtor_district_none"] = "Keine frei",
        ["os.realtor_loading"] = "Wohngebiete werden geprüft...",
        ["os.realtor_offline"] = "Wohnungsdaten sind gerade nicht verfügbar. PaissaDB ist vielleicht ausgelastet; versuch es gleich noch einmal.",
        ["os.realtor_retry"] = "Erneut versuchen",
        ["os.realtor_unknown_world"] = "Wähle eine Welt, um ihre freien Grundstücke zu sehen.",
        ["os.realtor_ward_plot"] = "Bezirk {0} · Grundstück {1}",
        ["os.realtor_size_s"] = "S",
        ["os.realtor_size_m"] = "M",
        ["os.realtor_size_l"] = "L",
        ["os.realtor_filter_small"] = "Klein",
        ["os.realtor_filter_medium"] = "Mittel",
        ["os.realtor_filter_large"] = "Groß",
        ["os.realtor_chip_fc"] = "FG",
        ["os.realtor_chip_personal"] = "Privat",
        ["os.realtor_lotto_accepting_open"] = "Lose werden angenommen",
        ["os.realtor_lotto_results_open"] = "Ergebnisphase",
        ["os.realtor_lotto_unavailable"] = "Zwischen zwei Lotterien",
        ["os.realtor_phase_label"] = "Aktuelle Phase",
        ["os.realtor_time_label"] = "Restzeit",
        ["os.realtor_entries"] = "{0} Lose",
        ["os.realtor_fcfs"] = "Wer zuerst kommt, kauft zuerst",
        ["os.realtor_checked"] = "geprüft vor {0}",
        ["os.realtor_empty_district"] = "Hier ist gerade nichts frei.",
        ["os.realtor_empty_filtered"] = "Nichts passt zu diesen Filtern.",
        ["os.realtor_unit_m"] = "min",
        ["os.realtor_unit_h"] = "Std",
        ["os.realtor_unit_d"] = "T",
        ["os.realtor_menu_tour"] = "App-Tour",
        ["os.realtor_tour_welcome_title"] = "Willkommen beim Makler",
        ["os.realtor_tour_welcome_body"] = "Jedes freie Grundstück Eorzeas, direkt auf deinem Handy. Schluss mit dem Bezirks-Marathon; sieh nach, was frei ist, bevor du überhaupt losgehst.",
        ["os.realtor_tour_welcome_f1"] = "Stöbere durch jede Welt, jedes Wohngebiet und jedes Datenzentrum",
        ["os.realtor_tour_welcome_f2"] = "Filtere nach Grundstücksgröße und Käufer: FG oder privat",
        ["os.realtor_tour_welcome_f3"] = "Live-Countdowns zur Lotterie und Aktualität für jedes Grundstück",
        ["os.realtor_tour_browse_title"] = "Scouten wie ein Profi",
        ["os.realtor_tour_browse_body"] = "Wähle oben rechts eine Welt und öffne dann ein Wohngebiet, um jedes freie Grundstück mit Bezirk, Nummer und Preis zu sehen.",
        ["os.realtor_tour_browse_f1"] = "Deine eigene Welt wird automatisch ausgewählt",
        ["os.realtor_tour_browse_f2"] = "Die fünf Wohngebiete zeigen freie Grundstücke auf einen Blick",
        ["os.realtor_tour_browse_f3"] = "Größen- und Käuferfilter grenzen die Suche ein",
        ["os.realtor_tour_lotto_title"] = "Achte auf die Lotterie",
        ["os.realtor_tour_lotto_body"] = "Die meisten Grundstücke werden per Lotterie vergeben. Der Makler zeigt dir die aktuelle Phase und wie lange du noch Zeit hast.",
        ["os.realtor_tour_lotto_f1"] = "Countdowns für Lose und Ergebnisse pro Grundstück",
        ["os.realtor_tour_lotto_f2"] = "Sieh, wie viele Lose ein Grundstück schon hat",
        ["os.realtor_tour_lotto_f3"] = "Jedes Grundstück zeigt, wann ein Scout zuletzt vorbeikam",
        ["os.realtor_tour_credit"] = "Alle Wohnungsdaten werden von Spielern mit PaissaHouse gesammelt und über PaissaDB geteilt. Die sind großartig!",
        ["os.realtor_tour_credit_link"] = "PaissaDB besuchen",
        ["os.realtor_tour_reopen_hint"] = "Du kannst diese Tour jederzeit über das Fragezeichen oben neu starten.",
    };

    private static readonly IReadOnlyDictionary<string, string> Es = new Dictionary<string, string>
    {
        // added after update 2.0.1 (realtor)
        ["os.realtor_pick_world"] = "Elige un mundo",
        ["os.realtor_search_world"] = "Buscar mundos...",
        ["os.realtor_hero_sub"] = "parcelas libres en {0}",
        ["os.realtor_stale"] = "informes de hasta hace {0}",
        ["os.realtor_district_open"] = "{0} libres",
        ["os.realtor_district_none"] = "Ninguna libre",
        ["os.realtor_loading"] = "Revisando los distritos residenciales...",
        ["os.realtor_offline"] = "Los datos de vivienda no están disponibles ahora mismo. Puede que PaissaDB esté ocupado; inténtalo de nuevo en un momento.",
        ["os.realtor_retry"] = "Reintentar",
        ["os.realtor_unknown_world"] = "Elige un mundo para ver sus parcelas libres.",
        ["os.realtor_ward_plot"] = "Distrito {0} · Parcela {1}",
        ["os.realtor_size_s"] = "S",
        ["os.realtor_size_m"] = "M",
        ["os.realtor_size_l"] = "L",
        ["os.realtor_filter_small"] = "Pequeña",
        ["os.realtor_filter_medium"] = "Mediana",
        ["os.realtor_filter_large"] = "Grande",
        ["os.realtor_chip_fc"] = "CL",
        ["os.realtor_chip_personal"] = "Personal",
        ["os.realtor_lotto_accepting_open"] = "Aceptando boletos",
        ["os.realtor_lotto_results_open"] = "Fase de resultados",
        ["os.realtor_lotto_unavailable"] = "Entre loterías",
        ["os.realtor_phase_label"] = "Fase actual",
        ["os.realtor_time_label"] = "Tiempo restante",
        ["os.realtor_entries"] = "{0} boletos",
        ["os.realtor_fcfs"] = "Por orden de llegada",
        ["os.realtor_checked"] = "revisado hace {0}",
        ["os.realtor_empty_district"] = "Ahora mismo no hay nada libre aquí.",
        ["os.realtor_empty_filtered"] = "Nada coincide con estos filtros.",
        ["os.realtor_unit_m"] = "min",
        ["os.realtor_unit_h"] = "h",
        ["os.realtor_unit_d"] = "d",
        ["os.realtor_menu_tour"] = "Tour de la app",
        ["os.realtor_tour_welcome_title"] = "Bienvenido a Inmobiliaria",
        ["os.realtor_tour_welcome_body"] = "Todas las parcelas libres de Eorzea, directamente en tu teléfono. Deja de recorrer distritos; mira qué hay libre antes de salir de casa.",
        ["os.realtor_tour_welcome_f1"] = "Explora cada mundo, distrito y centro de datos",
        ["os.realtor_tour_welcome_f2"] = "Filtra por tamaño de parcela y comprador: CL o personal",
        ["os.realtor_tour_welcome_f3"] = "Cuentas atrás de lotería en vivo y frescura de cada parcela",
        ["os.realtor_tour_browse_title"] = "Explora como un profesional",
        ["os.realtor_tour_browse_body"] = "Elige un mundo arriba a la derecha y entra en un distrito para ver cada parcela libre con su distrito, número y precio.",
        ["os.realtor_tour_browse_f1"] = "Tu propio mundo se selecciona automáticamente",
        ["os.realtor_tour_browse_f2"] = "Los cinco distritos muestran las parcelas libres de un vistazo",
        ["os.realtor_tour_browse_f3"] = "Los filtros de tamaño y comprador acotan la búsqueda",
        ["os.realtor_tour_lotto_title"] = "Ojo con la lotería",
        ["os.realtor_tour_lotto_body"] = "La mayoría de las parcelas se venden por lotería. Inmobiliaria muestra en qué fase está cada parcela y cuánto tiempo te queda.",
        ["os.realtor_tour_lotto_f1"] = "Cuentas atrás de inscripción y resultados por parcela",
        ["os.realtor_tour_lotto_f2"] = "Mira cuántos boletos tiene ya una parcela",
        ["os.realtor_tour_lotto_f3"] = "Cada parcela muestra cuándo la revisó un explorador por última vez",
        ["os.realtor_tour_credit"] = "Todos los datos de vivienda los recopilan jugadores con PaissaHouse y se comparten vía PaissaDB. ¡Son geniales!",
        ["os.realtor_tour_credit_link"] = "Visitar PaissaDB",
        ["os.realtor_tour_reopen_hint"] = "Puedes reabrir este tour cuando quieras con el interrogante de arriba.",
    };

    private static readonly IReadOnlyDictionary<string, string> Fr = new Dictionary<string, string>
    {
        // added after update 2.0.1 (realtor)
        ["os.realtor_pick_world"] = "Choisissez un monde",
        ["os.realtor_search_world"] = "Rechercher un monde...",
        ["os.realtor_hero_sub"] = "terrains libres sur {0}",
        ["os.realtor_stale"] = "relevés datant d'au plus {0}",
        ["os.realtor_district_open"] = "{0} libres",
        ["os.realtor_district_none"] = "Aucun libre",
        ["os.realtor_loading"] = "Inspection des quartiers résidentiels...",
        ["os.realtor_offline"] = "Les données immobilières sont indisponibles pour le moment. PaissaDB est peut-être occupé ; réessayez dans un instant.",
        ["os.realtor_retry"] = "Réessayer",
        ["os.realtor_unknown_world"] = "Choisissez un monde pour voir ses terrains libres.",
        ["os.realtor_ward_plot"] = "Secteur {0} · Terrain {1}",
        ["os.realtor_size_s"] = "S",
        ["os.realtor_size_m"] = "M",
        ["os.realtor_size_l"] = "L",
        ["os.realtor_filter_small"] = "Petit",
        ["os.realtor_filter_medium"] = "Moyen",
        ["os.realtor_filter_large"] = "Grand",
        ["os.realtor_chip_fc"] = "CL",
        ["os.realtor_chip_personal"] = "Perso",
        ["os.realtor_lotto_accepting_open"] = "Inscriptions ouvertes",
        ["os.realtor_lotto_results_open"] = "Phase de résultats",
        ["os.realtor_lotto_unavailable"] = "Entre deux loteries",
        ["os.realtor_phase_label"] = "Phase actuelle",
        ["os.realtor_time_label"] = "Temps restant",
        ["os.realtor_entries"] = "{0} inscriptions",
        ["os.realtor_fcfs"] = "Premier arrivé, premier servi",
        ["os.realtor_checked"] = "vérifié il y a {0}",
        ["os.realtor_empty_district"] = "Rien de libre ici pour le moment.",
        ["os.realtor_empty_filtered"] = "Rien ne correspond à ces filtres.",
        ["os.realtor_unit_m"] = "min",
        ["os.realtor_unit_h"] = "h",
        ["os.realtor_unit_d"] = "j",
        ["os.realtor_menu_tour"] = "Visite de l'appli",
        ["os.realtor_tour_welcome_title"] = "Bienvenue dans Immobilier",
        ["os.realtor_tour_welcome_body"] = "Tous les terrains libres d'Éorzéa, directement sur votre téléphone. Fini les allers-retours entre secteurs ; voyez ce qui est libre avant même de partir.",
        ["os.realtor_tour_welcome_f1"] = "Parcourez chaque monde, quartier et centre de données",
        ["os.realtor_tour_welcome_f2"] = "Filtrez par taille de terrain et acheteur : CL ou perso",
        ["os.realtor_tour_welcome_f3"] = "Comptes à rebours de loterie en direct et fraîcheur de chaque terrain",
        ["os.realtor_tour_browse_title"] = "Prospectez comme un pro",
        ["os.realtor_tour_browse_body"] = "Choisissez un monde en haut à droite, puis ouvrez un quartier pour voir chaque terrain libre avec son secteur, son numéro et son prix.",
        ["os.realtor_tour_browse_f1"] = "Votre propre monde est sélectionné automatiquement",
        ["os.realtor_tour_browse_f2"] = "Les cinq quartiers affichent les terrains libres d'un coup d'œil",
        ["os.realtor_tour_browse_f3"] = "Les filtres de taille et d'acheteur affinent la recherche",
        ["os.realtor_tour_lotto_title"] = "Gare à la loterie",
        ["os.realtor_tour_lotto_body"] = "La plupart des terrains se vendent par loterie. Immobilier montre la phase de chaque terrain et le temps qu'il vous reste.",
        ["os.realtor_tour_lotto_f1"] = "Comptes à rebours d'inscription et de résultats par terrain",
        ["os.realtor_tour_lotto_f2"] = "Voyez combien d'inscriptions un terrain compte déjà",
        ["os.realtor_tour_lotto_f3"] = "Chaque terrain indique le dernier passage d'un éclaireur",
        ["os.realtor_tour_credit"] = "Toutes les données immobilières sont collectées par des joueurs utilisant PaissaHouse et partagées via PaissaDB. Ils sont formidables !",
        ["os.realtor_tour_credit_link"] = "Visiter PaissaDB",
        ["os.realtor_tour_reopen_hint"] = "Vous pouvez rouvrir cette visite à tout moment via le point d'interrogation en haut.",
    };

    private static readonly IReadOnlyDictionary<string, string> Pt = new Dictionary<string, string>
    {
        // added after update 2.0.1 (realtor)
        ["os.realtor_pick_world"] = "Escolha um mundo",
        ["os.realtor_search_world"] = "Buscar mundos...",
        ["os.realtor_hero_sub"] = "terrenos livres em {0}",
        ["os.realtor_stale"] = "relatos de até {0} atrás",
        ["os.realtor_district_open"] = "{0} livres",
        ["os.realtor_district_none"] = "Nenhum livre",
        ["os.realtor_loading"] = "Verificando os distritos residenciais...",
        ["os.realtor_offline"] = "Os dados de moradia estão indisponíveis agora. O PaissaDB pode estar ocupado; tente de novo em instantes.",
        ["os.realtor_retry"] = "Tentar de novo",
        ["os.realtor_unknown_world"] = "Escolha um mundo para ver os terrenos livres.",
        ["os.realtor_ward_plot"] = "Distrito {0} · Terreno {1}",
        ["os.realtor_size_s"] = "P",
        ["os.realtor_size_m"] = "M",
        ["os.realtor_size_l"] = "G",
        ["os.realtor_filter_small"] = "Pequeno",
        ["os.realtor_filter_medium"] = "Médio",
        ["os.realtor_filter_large"] = "Grande",
        ["os.realtor_chip_fc"] = "CL",
        ["os.realtor_chip_personal"] = "Pessoal",
        ["os.realtor_lotto_accepting_open"] = "Recebendo inscrições",
        ["os.realtor_lotto_results_open"] = "Fase de resultados",
        ["os.realtor_lotto_unavailable"] = "Entre loterias",
        ["os.realtor_phase_label"] = "Fase atual",
        ["os.realtor_time_label"] = "Tempo restante",
        ["os.realtor_entries"] = "{0} inscrições",
        ["os.realtor_fcfs"] = "Por ordem de chegada",
        ["os.realtor_checked"] = "verificado há {0}",
        ["os.realtor_empty_district"] = "Nada livre por aqui no momento.",
        ["os.realtor_empty_filtered"] = "Nada corresponde a esses filtros.",
        ["os.realtor_unit_m"] = "min",
        ["os.realtor_unit_h"] = "h",
        ["os.realtor_unit_d"] = "d",
        ["os.realtor_menu_tour"] = "Tour do app",
        ["os.realtor_tour_welcome_title"] = "Bem-vindo ao Imobiliária",
        ["os.realtor_tour_welcome_body"] = "Todos os terrenos livres de Eorzea, direto no seu telefone. Chega de correr de distrito em distrito; veja o que está livre antes de sair de casa.",
        ["os.realtor_tour_welcome_f1"] = "Explore cada mundo, distrito e data center",
        ["os.realtor_tour_welcome_f2"] = "Filtre por tamanho do terreno e comprador: CL ou pessoal",
        ["os.realtor_tour_welcome_f3"] = "Contagens regressivas da loteria ao vivo e frescor de cada terreno",
        ["os.realtor_tour_browse_title"] = "Explore como um profissional",
        ["os.realtor_tour_browse_body"] = "Escolha um mundo no canto superior direito e abra um distrito para ver cada terreno livre com distrito, número e preço.",
        ["os.realtor_tour_browse_f1"] = "Seu próprio mundo é selecionado automaticamente",
        ["os.realtor_tour_browse_f2"] = "Os cinco distritos mostram os terrenos livres num relance",
        ["os.realtor_tour_browse_f3"] = "Filtros de tamanho e comprador afinam a busca",
        ["os.realtor_tour_lotto_title"] = "Atenção à loteria",
        ["os.realtor_tour_lotto_body"] = "A maioria dos terrenos é vendida por loteria. O Imobiliária mostra em que fase cada terreno está e quanto tempo ainda resta.",
        ["os.realtor_tour_lotto_f1"] = "Contagens de inscrição e resultados por terreno",
        ["os.realtor_tour_lotto_f2"] = "Veja quantas inscrições um terreno já tem",
        ["os.realtor_tour_lotto_f3"] = "Cada terreno mostra quando um scout passou por lá pela última vez",
        ["os.realtor_tour_credit"] = "Todos os dados de moradia são coletados por jogadores com o PaissaHouse e compartilhados via PaissaDB. Eles são incríveis!",
        ["os.realtor_tour_credit_link"] = "Visitar o PaissaDB",
        ["os.realtor_tour_reopen_hint"] = "Você pode reabrir este tour a qualquer momento pelo ponto de interrogação lá em cima.",
    };

    private static readonly IReadOnlyDictionary<string, string> Ru = new Dictionary<string, string>
    {
        // added after update 2.0.1 (realtor)
        ["os.realtor_pick_world"] = "Выберите мир",
        ["os.realtor_search_world"] = "Поиск миров...",
        ["os.realtor_hero_sub"] = "свободных участков на {0}",
        ["os.realtor_stale"] = "данные не старше {0}",
        ["os.realtor_district_open"] = "{0} свободно",
        ["os.realtor_district_none"] = "Нет свободных",
        ["os.realtor_loading"] = "Проверяем жилые кварталы...",
        ["os.realtor_offline"] = "Данные о жилье сейчас недоступны. Возможно, PaissaDB перегружен; попробуйте чуть позже.",
        ["os.realtor_retry"] = "Попробовать снова",
        ["os.realtor_unknown_world"] = "Выберите мир, чтобы увидеть свободные участки.",
        ["os.realtor_ward_plot"] = "Квартал {0} · Участок {1}",
        ["os.realtor_size_s"] = "S",
        ["os.realtor_size_m"] = "M",
        ["os.realtor_size_l"] = "L",
        ["os.realtor_filter_small"] = "Малый",
        ["os.realtor_filter_medium"] = "Средний",
        ["os.realtor_filter_large"] = "Большой",
        ["os.realtor_chip_fc"] = "ФК",
        ["os.realtor_chip_personal"] = "Личный",
        ["os.realtor_lotto_accepting_open"] = "Приём заявок",
        ["os.realtor_lotto_results_open"] = "Итоги лотереи",
        ["os.realtor_lotto_unavailable"] = "Между лотереями",
        ["os.realtor_phase_label"] = "Текущая фаза",
        ["os.realtor_time_label"] = "Осталось времени",
        ["os.realtor_entries"] = "заявок: {0}",
        ["os.realtor_fcfs"] = "Кто первый, того и участок",
        ["os.realtor_checked"] = "проверено {0} назад",
        ["os.realtor_empty_district"] = "Сейчас здесь нет свободных участков.",
        ["os.realtor_empty_filtered"] = "Под эти фильтры ничего не подходит.",
        ["os.realtor_unit_m"] = "м",
        ["os.realtor_unit_h"] = "ч",
        ["os.realtor_unit_d"] = "д",
        ["os.realtor_menu_tour"] = "Тур по приложению",
        ["os.realtor_tour_welcome_title"] = "Добро пожаловать в Риелтор",
        ["os.realtor_tour_welcome_body"] = "Все свободные участки Эорзеи прямо в вашем телефоне. Хватит бегать по кварталам: посмотрите, что свободно, ещё до выхода из дома.",
        ["os.realtor_tour_welcome_f1"] = "Просматривайте любой мир, квартал и дата-центр",
        ["os.realtor_tour_welcome_f2"] = "Фильтруйте по размеру участка и покупателю: ФК или личный",
        ["os.realtor_tour_welcome_f3"] = "Живые таймеры лотереи и свежесть данных по каждому участку",
        ["os.realtor_tour_browse_title"] = "Разведка как у профи",
        ["os.realtor_tour_browse_body"] = "Выберите мир в правом верхнем углу, затем откройте квартал, чтобы увидеть каждый свободный участок с номером и ценой.",
        ["os.realtor_tour_browse_f1"] = "Ваш собственный мир выбирается автоматически",
        ["os.realtor_tour_browse_f2"] = "Пять кварталов показывают свободные участки с первого взгляда",
        ["os.realtor_tour_browse_f3"] = "Фильтры размера и покупателя сужают поиск",
        ["os.realtor_tour_lotto_title"] = "Следите за лотереей",
        ["os.realtor_tour_lotto_body"] = "Большинство участков продаётся через лотерею. Риелтор показывает, в какой фазе участок и сколько времени осталось.",
        ["os.realtor_tour_lotto_f1"] = "Таймеры приёма заявок и итогов по каждому участку",
        ["os.realtor_tour_lotto_f2"] = "Смотрите, сколько заявок уже подано на участок",
        ["os.realtor_tour_lotto_f3"] = "У каждого участка видно, когда разведчик проверял его в последний раз",
        ["os.realtor_tour_credit"] = "Все данные о жилье собирают игроки с плагином PaissaHouse и делятся ими через PaissaDB. Они великолепны!",
        ["os.realtor_tour_credit_link"] = "Открыть PaissaDB",
        ["os.realtor_tour_reopen_hint"] = "Этот тур можно открыть заново в любой момент через знак вопроса сверху.",
    };

    public static readonly IReadOnlyDictionary<string, IReadOnlyDictionary<string, string>> Packs =
        new Dictionary<string, IReadOnlyDictionary<string, string>>
        {
            ["en"] = En,
            ["de"] = De,
            ["es"] = Es,
            ["fr"] = Fr,
            ["pt"] = Pt,
            ["ru"] = Ru,
        };
}
