using System.Collections.Generic;

namespace AetherOS.Apps.Realtor.Localization;

/// <summary>The Realtor app's own UI strings, merged into the central tables at app registration.</summary>
public static class AppStrings
{
    private static readonly IReadOnlyDictionary<string, string> En = new Dictionary<string, string>
    {
        // added after update 2.0.1 (realtor)
        ["os.realtor_pick_world"] = "Choose a world",
        ["os.realtor_search_world"] = "Search worlds...",
        ["os.realtor_hero_sub"] = "open plots on {0}",
        ["os.realtor_stale_row"] = "(stale data)",
        ["os.realtor_menu_contribute"] = "Contribute?",
        ["os.realtor_contribute_title"] = "Where this data comes from",
        ["os.realtor_contribute_body"] = "Players who run the PaissaHouse plugin found every plot on this list. The plugin reports an open plot when a player walks past. Install it and run it yourself. Your own trips then keep this list fresh, even on worlds nobody else checks.",
        ["os.realtor_contribute_open"] = "Open the plugin installer",
        ["os.realtor_contribute_close"] = "Close",
        ["os.realtor_stale_pill"] = "{0} stale",
        ["os.realtor_bid_title"] = "You have a lottery entry",
        ["os.realtor_bid_detail"] = "Plot {0}, Ward {1}, {2}  ·  Lottery number {3}",
        ["os.realtor_stale"] = "reports up to {0} old",
        ["os.realtor_district_open"] = "{0} open",
        ["os.realtor_district_none"] = "None open",
        ["os.realtor_loading"] = "Checking the housing wards...",
        ["os.realtor_offline"] = "Housing data is unavailable right now. PaissaDB may be busy; try again in a moment.",
        ["os.realtor_retry"] = "Try again",
        ["os.realtor_unknown_world"] = "Pick a world to see its open plots.",
        ["os.realtor_ward_plot"] = "Ward {0} · Plot {1}",
        ["os.realtor_size_s"] = "S",
        ["os.realtor_size_m"] = "M",
        ["os.realtor_size_l"] = "L",
        ["os.realtor_filter_small"] = "Small",
        ["os.realtor_filter_medium"] = "Medium",
        ["os.realtor_filter_large"] = "Large",
        ["os.realtor_chip_fc"] = "FC",
        ["os.realtor_chip_personal"] = "Personal",
        ["os.realtor_lotto_accepting_open"] = "Accepting entries",
        ["os.realtor_lotto_results_open"] = "Results phase",
        ["os.realtor_lotto_unavailable"] = "Between lotteries",
        ["os.realtor_phase_label"] = "Current phase",
        ["os.realtor_time_label"] = "Time remaining",
        ["os.realtor_entries"] = "{0} entries",
        ["os.realtor_fcfs"] = "First come, first served",
        ["os.realtor_checked"] = "checked {0} ago",
        ["os.realtor_empty_district"] = "No open plots here right now.",
        ["os.realtor_empty_filtered"] = "Nothing matches these filters.",
        ["os.realtor_unit_m"] = "m",
        ["os.realtor_unit_h"] = "h",
        ["os.realtor_unit_d"] = "d",
        ["os.realtor_menu_tour"] = "App tour",
        ["os.realtor_tour_welcome_title"] = "Welcome to Realtor",
        ["os.realtor_tour_welcome_body"] = "Every open housing plot in Eorzea, right on your phone. Stop running ward to ward; see what's free before you ever leave the aetheryte.",
        ["os.realtor_tour_welcome_f1"] = "Browse every world, district, and data center",
        ["os.realtor_tour_welcome_f2"] = "Filter by plot size and who can buy: FC or personal",
        ["os.realtor_tour_welcome_f3"] = "Live lottery countdowns and freshness on every plot",
        ["os.realtor_tour_browse_title"] = "Scout like a pro",
        ["os.realtor_tour_browse_body"] = "Pick a world at the top right. Tap a district to see every open plot with its ward, number, and price.",
        ["os.realtor_tour_browse_f1"] = "Your own world is selected automatically",
        ["os.realtor_tour_browse_f2"] = "The five districts show open counts at a glance",
        ["os.realtor_tour_browse_f3"] = "Size and tenant filters narrow the hunt",
        ["os.realtor_tour_lotto_title"] = "Mind the lottery",
        ["os.realtor_tour_lotto_body"] = "Most plots sell by lottery. Realtor shows which phase a plot is in and how long you have left to enter or claim.",
        ["os.realtor_tour_lotto_f1"] = "Entry and results countdowns per plot",
        ["os.realtor_tour_lotto_f2"] = "See how many entries a plot already has",
        ["os.realtor_tour_lotto_f3"] = "Every plot shows when a scout last checked it",
        ["os.realtor_tour_credit"] = "All housing data is crowdsourced by players running PaissaHouse and shared through PaissaDB. They are awesome!",
        ["os.realtor_tour_credit_link"] = "Visit PaissaDB",
        ["os.realtor_tour_reopen_hint"] = "You can reopen this tour any time with the question mark up top.",

        // added after update 2.1.3
        ["os.realtor_menu_settings"] = "Settings",
        ["os.realtor_settings"] = "Realtor settings",
        ["os.realtor_settings_data"] = "Data",
        ["os.realtor_settings_alerts"] = "Alerts",
        ["os.realtor_set_stale"] = "Show stale entries",
        ["os.realtor_set_stale_hint"] = "Every entry comes from other players, through PaissaDB. Turn this on to also see houses nobody has checked in a while. They might still be available. The counts then show a stale pill, and the district screens list the stale plots. Turn it off and both stay hidden.",
        ["os.realtor_set_notify"] = "Notify me when the phase changes",
        ["os.realtor_set_notify_hint"] = "You get a phone notification when the housing lottery switches between accepting entries and publishing results. It appears in your notifications, and in chat when you log in. Opening the Realtor app clears it.",

        // added after update 2.3.4 (estate demolition watch)
        ["os.realtor_estate_title"] = "Estate at risk: about {0} days left",
        ["os.realtor_estate_detail"] = "{0}, away {1} days",
        ["os.realtor_estate_detail_more"] = "{0}, away {1} days  ·  +{2} more",
        ["os.realtor_menu_realty"] = "Owned realty",
        ["os.realtor_realty_title"] = "Owned realty",
        ["os.realtor_realty_days"] = "{0} d away",
        ["os.realtor_realty_entered"] = "Last entered {0}",
        ["os.realtor_realty_never"] = "Enter your house to start counting",
        ["os.realtor_realty_empty"] = "No private estate has turned up yet. Log in on a character that owns one and it will be listed here.",
        ["os.realtor_realty_note"] = "This count comes from what this install has seen, not from the game's own timer. The game demolishes your house after {0} days if you do not enter it. Each visit resets the clock.",
        ["os.realtor_home_row"] = "Home ({0})",
        ["os.realtor_home_teleport"] = "Teleport",
        ["os.realtor_set_estate"] = "Warn me before a house is demolished",
        ["os.realtor_set_estate_hint"] = "Square Enix demolishes a private estate once nobody has entered it for 45 days. The phone remembers when each of your characters last entered their own house. It warns you in chat and in your notifications well before the 45 days are up. Free Company houses and apartments are not tracked.",
    };

    private static readonly IReadOnlyDictionary<string, string> De = new Dictionary<string, string>
    {
        // added after update 2.0.1 (realtor)
        ["os.realtor_pick_world"] = "Welt auswählen",
        ["os.realtor_search_world"] = "Welten durchsuchen...",
        ["os.realtor_hero_sub"] = "freie Grundstücke auf {0}",
        ["os.realtor_stale_row"] = "(veraltete Daten)",
        ["os.realtor_menu_contribute"] = "Mithelfen?",
        ["os.realtor_contribute_title"] = "Woher diese Daten kommen",
        ["os.realtor_contribute_body"] = "Jedes Grundstück auf dieser Liste haben Spielende mit dem PaissaHouse-Plugin gefunden. Das Plugin meldet ein freies Grundstück, sobald jemand daran vorbeiläuft. Installiere es und lass es selbst mitlaufen. Deine eigenen Wege halten diese Liste dann frisch, auch auf Welten, die sonst niemand prüft.",
        ["os.realtor_contribute_open"] = "Plugin-Installer öffnen",
        ["os.realtor_contribute_close"] = "Schließen",
        ["os.realtor_stale_pill"] = "{0} veraltet",
        ["os.realtor_bid_title"] = "Du hast ein Los abgegeben",
        ["os.realtor_bid_detail"] = "Grundstück {0}, Bezirk {1}, {2}  ·  Losnummer {3}",
        ["os.realtor_stale"] = "Meldungen bis zu {0} alt",
        ["os.realtor_district_open"] = "{0} frei",
        ["os.realtor_district_none"] = "Keine frei",
        ["os.realtor_loading"] = "Wohngebiete werden geprüft...",
        ["os.realtor_offline"] = "Wohnungsdaten sind gerade nicht verfügbar. PaissaDB ist vielleicht ausgelastet; versuch es gleich noch einmal.",
        ["os.realtor_retry"] = "Erneut versuchen",
        ["os.realtor_unknown_world"] = "Wähle eine Welt, um ihre freien Grundstücke zu sehen.",
        ["os.realtor_ward_plot"] = "Bezirk {0} · Grundstück {1}",
        ["os.realtor_size_s"] = "S",
        ["os.realtor_size_m"] = "M",
        ["os.realtor_size_l"] = "L",
        ["os.realtor_filter_small"] = "Klein",
        ["os.realtor_filter_medium"] = "Mittel",
        ["os.realtor_filter_large"] = "Groß",
        ["os.realtor_chip_fc"] = "FG",
        ["os.realtor_chip_personal"] = "Privat",
        ["os.realtor_lotto_accepting_open"] = "Lose werden angenommen",
        ["os.realtor_lotto_results_open"] = "Ergebnisphase",
        ["os.realtor_lotto_unavailable"] = "Zwischen zwei Lotterien",
        ["os.realtor_phase_label"] = "Aktuelle Phase",
        ["os.realtor_time_label"] = "Restzeit",
        ["os.realtor_entries"] = "{0} Lose",
        ["os.realtor_fcfs"] = "Wer zuerst kommt, kauft zuerst",
        ["os.realtor_checked"] = "geprüft vor {0}",
        ["os.realtor_empty_district"] = "Hier ist gerade nichts frei.",
        ["os.realtor_empty_filtered"] = "Nichts passt zu diesen Filtern.",
        ["os.realtor_unit_m"] = "min",
        ["os.realtor_unit_h"] = "Std",
        ["os.realtor_unit_d"] = "T",
        ["os.realtor_menu_tour"] = "App-Tour",
        ["os.realtor_tour_welcome_title"] = "Willkommen beim Makler",
        ["os.realtor_tour_welcome_body"] = "Jedes freie Grundstück Eorzeas, direkt auf deinem Handy. Schluss mit dem Bezirks-Marathon; sieh nach, was frei ist, bevor du überhaupt losgehst.",
        ["os.realtor_tour_welcome_f1"] = "Stöbere durch jede Welt, jedes Wohngebiet und jedes Datenzentrum",
        ["os.realtor_tour_welcome_f2"] = "Filtere nach Grundstücksgröße und Käufer: FG oder privat",
        ["os.realtor_tour_welcome_f3"] = "Live-Countdowns zur Lotterie und Aktualität für jedes Grundstück",
        ["os.realtor_tour_browse_title"] = "Scouten wie ein Profi",
        ["os.realtor_tour_browse_body"] = "Wähle oben rechts eine Welt. Tippe auf ein Wohngebiet, um jedes freie Grundstück mit Bezirk, Nummer und Preis zu sehen.",
        ["os.realtor_tour_browse_f1"] = "Deine eigene Welt wird automatisch ausgewählt",
        ["os.realtor_tour_browse_f2"] = "Die fünf Wohngebiete zeigen freie Grundstücke auf einen Blick",
        ["os.realtor_tour_browse_f3"] = "Größen- und Käuferfilter grenzen die Suche ein",
        ["os.realtor_tour_lotto_title"] = "Achte auf die Lotterie",
        ["os.realtor_tour_lotto_body"] = "Die meisten Grundstücke werden per Lotterie vergeben. Der Makler zeigt dir die aktuelle Phase und wie lange du noch Zeit hast.",
        ["os.realtor_tour_lotto_f1"] = "Countdowns für Lose und Ergebnisse pro Grundstück",
        ["os.realtor_tour_lotto_f2"] = "Sieh, wie viele Lose ein Grundstück schon hat",
        ["os.realtor_tour_lotto_f3"] = "Jedes Grundstück zeigt, wann ein Scout zuletzt vorbeikam",
        ["os.realtor_tour_credit"] = "Alle Wohnungsdaten werden von Spielern mit PaissaHouse gesammelt und über PaissaDB geteilt. Die sind großartig!",
        ["os.realtor_tour_credit_link"] = "PaissaDB besuchen",
        ["os.realtor_tour_reopen_hint"] = "Du kannst diese Tour jederzeit über das Fragezeichen oben neu starten.",

        // added after update 2.1.3
        ["os.realtor_menu_settings"] = "Einstellungen",
        ["os.realtor_settings"] = "Makler-Einstellungen",
        ["os.realtor_settings_data"] = "Daten",
        ["os.realtor_settings_alerts"] = "Hinweise",
        ["os.realtor_set_stale"] = "Veraltete Einträge zeigen",
        ["os.realtor_set_stale_hint"] = "Alle Einträge kommen von anderen Spielern, über PaissaDB. Schalte das ein, um auch Häuser zu sehen, die länger niemand geprüft hat. Vielleicht sind sie noch frei. Die Zähler zeigen dann eine Plakette für veraltete Daten, und die Wohngebiete listen die veralteten Grundstücke. Schalte es aus, und beides bleibt verborgen.",
        ["os.realtor_set_notify"] = "Bei Phasenwechsel benachrichtigen",
        ["os.realtor_set_notify_hint"] = "Du bekommst eine Benachrichtigung aufs Handy, wenn die Haus-Lotterie zwischen Bewerbungsphase und Ergebnisphase wechselt. Sie erscheint in deinen Benachrichtigungen und beim Einloggen im Chat. Das Öffnen der Makler-App löscht sie.",

        // added after update 2.3.4 (estate demolition watch)
        ["os.realtor_estate_title"] = "Grundstück in Gefahr: noch etwa {0} Tage",
        ["os.realtor_estate_detail"] = "{0}, seit {1} Tagen fort",
        ["os.realtor_estate_detail_more"] = "{0}, seit {1} Tagen fort  ·  +{2} weitere",
        ["os.realtor_menu_realty"] = "Eigener Immobilienbesitz",
        ["os.realtor_realty_title"] = "Eigener Immobilienbesitz",
        ["os.realtor_realty_days"] = "{0} T fort",
        ["os.realtor_realty_entered"] = "Zuletzt betreten am {0}",
        ["os.realtor_realty_never"] = "Betritt dein Haus, damit die Zählung beginnt",
        ["os.realtor_realty_empty"] = "Bisher ist kein privates Grundstück aufgetaucht. Melde dich mit einem Charakter an, der eines besitzt, dann steht es hier.",
        ["os.realtor_realty_note"] = "Diese Zählung kommt aus dem, was diese Installation gesehen hat, nicht aus dem Timer des Spiels. Das Spiel reißt dein Haus nach {0} Tagen ab, wenn du es nicht betrittst. Jeder Besuch setzt die Uhr zurück.",
        ["os.realtor_home_row"] = "Zuhause ({0})",
        ["os.realtor_home_teleport"] = "Hin",
        ["os.realtor_set_estate"] = "Vor dem Abriss eines Hauses warnen",
        ["os.realtor_set_estate_hint"] = "Square Enix reißt ein privates Grundstück ab, sobald es 45 Tage lang niemand betreten hat. Das Telefon merkt sich, wann jeder deiner Charaktere zuletzt sein eigenes Haus betreten hat. Es warnt dich im Chat und in deinen Benachrichtigungen, lange bevor die 45 Tage um sind. Häuser von Freien Gesellschaften und Apartments werden nicht erfasst.",
    };

    private static readonly IReadOnlyDictionary<string, string> Es = new Dictionary<string, string>
    {
        // added after update 2.0.1 (realtor)
        ["os.realtor_pick_world"] = "Elige un mundo",
        ["os.realtor_search_world"] = "Buscar mundos...",
        ["os.realtor_hero_sub"] = "parcelas libres en {0}",
        ["os.realtor_stale_row"] = "(datos obsoletos)",
        ["os.realtor_menu_contribute"] = "¿Colaborar?",
        ["os.realtor_contribute_title"] = "De dónde salen estos datos",
        ["os.realtor_contribute_body"] = "Cada parcela de esta lista la encontraron jugadores con el plugin PaissaHouse. El plugin informa de una parcela libre cuando alguien pasa por delante. Instálalo y déjalo activo. Tus propios paseos mantienen esta lista al día, incluso en mundos que nadie más revisa.",
        ["os.realtor_contribute_open"] = "Abrir el instalador de plugins",
        ["os.realtor_contribute_close"] = "Cerrar",
        ["os.realtor_stale_pill"] = "{0} obsoletos",
        ["os.realtor_bid_title"] = "Tienes una entrada en el sorteo",
        ["os.realtor_bid_detail"] = "Parcela {0}, Barrio {1}, {2}  ·  Número {3}",
        ["os.realtor_stale"] = "informes de hasta hace {0}",
        ["os.realtor_district_open"] = "{0} libres",
        ["os.realtor_district_none"] = "Ninguna libre",
        ["os.realtor_loading"] = "Revisando los distritos residenciales...",
        ["os.realtor_offline"] = "Los datos de vivienda no están disponibles ahora mismo. Puede que PaissaDB esté ocupado; inténtalo de nuevo en un momento.",
        ["os.realtor_retry"] = "Reintentar",
        ["os.realtor_unknown_world"] = "Elige un mundo para ver sus parcelas libres.",
        ["os.realtor_ward_plot"] = "Distrito {0} · Parcela {1}",
        ["os.realtor_size_s"] = "S",
        ["os.realtor_size_m"] = "M",
        ["os.realtor_size_l"] = "L",
        ["os.realtor_filter_small"] = "Pequeña",
        ["os.realtor_filter_medium"] = "Mediana",
        ["os.realtor_filter_large"] = "Grande",
        ["os.realtor_chip_fc"] = "CL",
        ["os.realtor_chip_personal"] = "Personal",
        ["os.realtor_lotto_accepting_open"] = "Aceptando boletos",
        ["os.realtor_lotto_results_open"] = "Fase de resultados",
        ["os.realtor_lotto_unavailable"] = "Entre loterías",
        ["os.realtor_phase_label"] = "Fase actual",
        ["os.realtor_time_label"] = "Tiempo restante",
        ["os.realtor_entries"] = "{0} boletos",
        ["os.realtor_fcfs"] = "Por orden de llegada",
        ["os.realtor_checked"] = "revisado hace {0}",
        ["os.realtor_empty_district"] = "Ahora mismo no hay nada libre aquí.",
        ["os.realtor_empty_filtered"] = "Nada coincide con estos filtros.",
        ["os.realtor_unit_m"] = "min",
        ["os.realtor_unit_h"] = "h",
        ["os.realtor_unit_d"] = "d",
        ["os.realtor_menu_tour"] = "Tour de la app",
        ["os.realtor_tour_welcome_title"] = "Bienvenido a Inmobiliaria",
        ["os.realtor_tour_welcome_body"] = "Todas las parcelas libres de Eorzea, directamente en tu teléfono. Deja de recorrer distritos; mira qué hay libre antes de salir de casa.",
        ["os.realtor_tour_welcome_f1"] = "Explora cada mundo, distrito y centro de datos",
        ["os.realtor_tour_welcome_f2"] = "Filtra por tamaño de parcela y comprador: CL o personal",
        ["os.realtor_tour_welcome_f3"] = "Cuentas atrás de lotería en vivo y frescura de cada parcela",
        ["os.realtor_tour_browse_title"] = "Explora como un profesional",
        ["os.realtor_tour_browse_body"] = "Elige un mundo arriba a la derecha. Toca un distrito para ver cada parcela libre con su barrio, su número y su precio.",
        ["os.realtor_tour_browse_f1"] = "Tu propio mundo se selecciona automáticamente",
        ["os.realtor_tour_browse_f2"] = "Los cinco distritos muestran las parcelas libres de un vistazo",
        ["os.realtor_tour_browse_f3"] = "Los filtros de tamaño y comprador acotan la búsqueda",
        ["os.realtor_tour_lotto_title"] = "Ojo con la lotería",
        ["os.realtor_tour_lotto_body"] = "La mayoría de las parcelas se venden por lotería. Inmobiliaria muestra en qué fase está cada parcela y cuánto tiempo te queda.",
        ["os.realtor_tour_lotto_f1"] = "Cuentas atrás de inscripción y resultados por parcela",
        ["os.realtor_tour_lotto_f2"] = "Mira cuántos boletos tiene ya una parcela",
        ["os.realtor_tour_lotto_f3"] = "Cada parcela muestra cuándo la revisó un explorador por última vez",
        ["os.realtor_tour_credit"] = "Todos los datos de vivienda los recopilan jugadores con PaissaHouse y se comparten vía PaissaDB. ¡Son geniales!",
        ["os.realtor_tour_credit_link"] = "Visitar PaissaDB",
        ["os.realtor_tour_reopen_hint"] = "Puedes reabrir este tour cuando quieras con el interrogante de arriba.",

        // added after update 2.1.3
        ["os.realtor_menu_settings"] = "Ajustes",
        ["os.realtor_settings"] = "Ajustes de Inmobiliaria",
        ["os.realtor_settings_data"] = "Datos",
        ["os.realtor_settings_alerts"] = "Avisos",
        ["os.realtor_set_stale"] = "Mostrar entradas obsoletas",
        ["os.realtor_set_stale_hint"] = "Todas las entradas vienen de otros jugadores, a través de PaissaDB. Activa esto para ver también casas que nadie ha comprobado en un tiempo. Puede que sigan libres. Los recuentos muestran entonces una etiqueta de datos obsoletos, y las pantallas de distrito listan esas parcelas. Desactívalo y ambas cosas se ocultan.",
        ["os.realtor_set_notify"] = "Avisarme al cambiar de fase",
        ["os.realtor_set_notify_hint"] = "Recibes una notificación en el teléfono cuando la lotería de viviendas cambia entre aceptar solicitudes y publicar resultados. Aparece en tus notificaciones, y en el chat al iniciar sesión. Abrir la app de Inmobiliaria la borra.",

        // added after update 2.3.4 (estate demolition watch)
        ["os.realtor_estate_title"] = "Parcela en riesgo: quedan unos {0} días",
        ["os.realtor_estate_detail"] = "{0}, {1} días fuera",
        ["os.realtor_estate_detail_more"] = "{0}, {1} días fuera  ·  +{2} más",
        ["os.realtor_menu_realty"] = "Propiedades en posesión",
        ["os.realtor_realty_title"] = "Propiedades en posesión",
        ["os.realtor_realty_days"] = "{0} d fuera",
        ["os.realtor_realty_entered"] = "Última entrada: {0}",
        ["os.realtor_realty_never"] = "Entra en tu casa para empezar a contar",
        ["os.realtor_realty_empty"] = "Todavía no ha aparecido ninguna parcela privada. Entra con un personaje que tenga una y saldrá aquí.",
        ["os.realtor_realty_note"] = "Este recuento sale de lo que ha visto esta instalación, no del temporizador del juego. El juego derriba tu casa a los {0} días si no entras en ella. Cada visita reinicia el contador.",
        ["os.realtor_home_row"] = "Tu casa ({0})",
        ["os.realtor_home_teleport"] = "Ir",
        ["os.realtor_set_estate"] = "Avisarme antes de que derriben una casa",
        ["os.realtor_set_estate_hint"] = "Square Enix derriba una parcela privada cuando nadie entra en ella durante 45 días. El teléfono recuerda cuándo entró cada uno de tus personajes en su propia casa por última vez. Te avisa en el chat y en tus notificaciones mucho antes de que se cumplan los 45 días. Las casas de compañía libre y los apartamentos no se vigilan.",
    };

    private static readonly IReadOnlyDictionary<string, string> Fr = new Dictionary<string, string>
    {
        // added after update 2.0.1 (realtor)
        ["os.realtor_pick_world"] = "Choisissez un monde",
        ["os.realtor_search_world"] = "Rechercher un monde...",
        ["os.realtor_hero_sub"] = "terrains libres sur {0}",
        ["os.realtor_stale_row"] = "(données obsolètes)",
        ["os.realtor_menu_contribute"] = "Contribuer ?",
        ["os.realtor_contribute_title"] = "D'où viennent ces données",
        ["os.realtor_contribute_body"] = "Chaque terrain de cette liste a été trouvé par des joueurs qui utilisent le plugin PaissaHouse. Le plugin signale un terrain libre quand un joueur passe devant. Installez-le et laissez-le tourner. Vos propres balades gardent alors cette liste à jour, même sur les mondes que personne d'autre ne vérifie.",
        ["os.realtor_contribute_open"] = "Ouvrir l'installateur de plugins",
        ["os.realtor_contribute_close"] = "Fermer",
        ["os.realtor_stale_pill"] = "{0} obsolètes",
        ["os.realtor_bid_title"] = "Vous avez une candidature en cours",
        ["os.realtor_bid_detail"] = "Terrain {0}, quartier {1}, {2}  ·  Numéro {3}",
        ["os.realtor_stale"] = "relevés datant d'au plus {0}",
        ["os.realtor_district_open"] = "{0} libres",
        ["os.realtor_district_none"] = "Aucun libre",
        ["os.realtor_loading"] = "Inspection des quartiers résidentiels...",
        ["os.realtor_offline"] = "Les données immobilières sont indisponibles pour le moment. PaissaDB est peut-être occupé ; réessayez dans un instant.",
        ["os.realtor_retry"] = "Réessayer",
        ["os.realtor_unknown_world"] = "Choisissez un monde pour voir ses terrains libres.",
        ["os.realtor_ward_plot"] = "Secteur {0} · Terrain {1}",
        ["os.realtor_size_s"] = "S",
        ["os.realtor_size_m"] = "M",
        ["os.realtor_size_l"] = "L",
        ["os.realtor_filter_small"] = "Petit",
        ["os.realtor_filter_medium"] = "Moyen",
        ["os.realtor_filter_large"] = "Grand",
        ["os.realtor_chip_fc"] = "CL",
        ["os.realtor_chip_personal"] = "Perso",
        ["os.realtor_lotto_accepting_open"] = "Inscriptions ouvertes",
        ["os.realtor_lotto_results_open"] = "Phase de résultats",
        ["os.realtor_lotto_unavailable"] = "Entre deux loteries",
        ["os.realtor_phase_label"] = "Phase actuelle",
        ["os.realtor_time_label"] = "Temps restant",
        ["os.realtor_entries"] = "{0} inscriptions",
        ["os.realtor_fcfs"] = "Premier arrivé, premier servi",
        ["os.realtor_checked"] = "vérifié il y a {0}",
        ["os.realtor_empty_district"] = "Rien de libre ici pour le moment.",
        ["os.realtor_empty_filtered"] = "Rien ne correspond à ces filtres.",
        ["os.realtor_unit_m"] = "min",
        ["os.realtor_unit_h"] = "h",
        ["os.realtor_unit_d"] = "j",
        ["os.realtor_menu_tour"] = "Visite de l'appli",
        ["os.realtor_tour_welcome_title"] = "Bienvenue dans Immobilier",
        ["os.realtor_tour_welcome_body"] = "Tous les terrains libres d'Éorzéa, directement sur votre téléphone. Fini les allers-retours entre secteurs ; voyez ce qui est libre avant même de partir.",
        ["os.realtor_tour_welcome_f1"] = "Parcourez chaque monde, quartier et centre de données",
        ["os.realtor_tour_welcome_f2"] = "Filtrez par taille de terrain et acheteur : CL ou perso",
        ["os.realtor_tour_welcome_f3"] = "Comptes à rebours de loterie en direct et fraîcheur de chaque terrain",
        ["os.realtor_tour_browse_title"] = "Prospectez comme un pro",
        ["os.realtor_tour_browse_body"] = "Choisissez un monde en haut à droite. Touchez un quartier pour voir chaque terrain libre avec son secteur, son numéro et son prix.",
        ["os.realtor_tour_browse_f1"] = "Votre propre monde est sélectionné automatiquement",
        ["os.realtor_tour_browse_f2"] = "Les cinq quartiers affichent les terrains libres d'un coup d'œil",
        ["os.realtor_tour_browse_f3"] = "Les filtres de taille et d'acheteur affinent la recherche",
        ["os.realtor_tour_lotto_title"] = "Gare à la loterie",
        ["os.realtor_tour_lotto_body"] = "La plupart des terrains se vendent par loterie. Immobilier montre la phase de chaque terrain et le temps qu'il vous reste.",
        ["os.realtor_tour_lotto_f1"] = "Comptes à rebours d'inscription et de résultats par terrain",
        ["os.realtor_tour_lotto_f2"] = "Voyez combien d'inscriptions un terrain compte déjà",
        ["os.realtor_tour_lotto_f3"] = "Chaque terrain indique le dernier passage d'un éclaireur",
        ["os.realtor_tour_credit"] = "Toutes les données immobilières sont collectées par des joueurs utilisant PaissaHouse et partagées via PaissaDB. Ils sont formidables !",
        ["os.realtor_tour_credit_link"] = "Visiter PaissaDB",
        ["os.realtor_tour_reopen_hint"] = "Vous pouvez rouvrir cette visite à tout moment via le point d'interrogation en haut.",

        // added after update 2.1.3
        ["os.realtor_menu_settings"] = "Paramètres",
        ["os.realtor_settings"] = "Paramètres de l'agence",
        ["os.realtor_settings_data"] = "Données",
        ["os.realtor_settings_alerts"] = "Alertes",
        ["os.realtor_set_stale"] = "Afficher les entrées obsolètes",
        ["os.realtor_set_stale_hint"] = "Toutes les entrées viennent d'autres joueurs, via PaissaDB. Activez ceci pour voir aussi les maisons que personne n'a vérifiées depuis un moment. Elles sont peut-être encore libres. Les compteurs affichent alors une pastille de données obsolètes, et les écrans de quartier listent ces terrains. Désactivez-le et les deux restent cachés.",
        ["os.realtor_set_notify"] = "Me prévenir au changement de phase",
        ["os.realtor_set_notify_hint"] = "Vous recevez une notification sur le téléphone quand la loterie immobilière passe des candidatures aux résultats, ou l'inverse. Elle s'affiche dans vos notifications, et dans le chat à la connexion. Ouvrir l'appli Immobilier l'efface.",

        // added after update 2.3.4 (estate demolition watch)
        ["os.realtor_estate_title"] = "Terrain menacé : environ {0} jours restants",
        ["os.realtor_estate_detail"] = "{0}, {1} jours d'absence",
        ["os.realtor_estate_detail_more"] = "{0}, {1} jours d'absence  ·  +{2} autres",
        ["os.realtor_menu_realty"] = "Biens possédés",
        ["os.realtor_realty_title"] = "Biens possédés",
        ["os.realtor_realty_days"] = "{0} j d'absence",
        ["os.realtor_realty_entered"] = "Dernière entrée le {0}",
        ["os.realtor_realty_never"] = "Entrez dans votre maison pour lancer le compteur",
        ["os.realtor_realty_empty"] = "Aucun terrain privé n'est encore apparu. Connectez-vous avec un personnage qui en possède un et il figurera ici.",
        ["os.realtor_realty_note"] = "Ce décompte vient de ce que cette installation a vu, pas du minuteur du jeu. Le jeu démolit votre maison au bout de {0} jours si vous n’y entrez pas. Chaque visite remet le compteur à zéro.",
        ["os.realtor_home_row"] = "Chez vous ({0})",
        ["os.realtor_home_teleport"] = "Aller",
        ["os.realtor_set_estate"] = "Me prévenir avant la démolition d’une maison",
        ["os.realtor_set_estate_hint"] = "Square Enix démolit un terrain privé dès que personne n’y est entré pendant 45 jours. Le téléphone retient la dernière fois que chacun de vos personnages est entré chez lui. Il vous prévient dans le chat et dans vos notifications bien avant la fin des 45 jours. Les maisons de compagnie libre et les appartements ne sont pas suivis.",
    };

    private static readonly IReadOnlyDictionary<string, string> Pt = new Dictionary<string, string>
    {
        // added after update 2.0.1 (realtor)
        ["os.realtor_pick_world"] = "Escolha um mundo",
        ["os.realtor_search_world"] = "Buscar mundos...",
        ["os.realtor_hero_sub"] = "terrenos livres em {0}",
        ["os.realtor_stale_row"] = "(dados desatualizados)",
        ["os.realtor_menu_contribute"] = "Contribuir?",
        ["os.realtor_contribute_title"] = "De onde vêm estes dados",
        ["os.realtor_contribute_body"] = "Cada terreno desta lista foi encontrado por jogadores que usam o plugin PaissaHouse. O plugin avisa que um terreno está livre quando alguém passa por ele. Instale o plugin e deixe-o rodando. Os seus próprios passeios mantêm esta lista fresca, mesmo em mundos que mais ninguém verifica.",
        ["os.realtor_contribute_open"] = "Abrir o instalador de plugins",
        ["os.realtor_contribute_close"] = "Fechar",
        ["os.realtor_stale_pill"] = "{0} desatualizados",
        ["os.realtor_bid_title"] = "Você tem uma inscrição no sorteio",
        ["os.realtor_bid_detail"] = "Terreno {0}, Bairro {1}, {2}  ·  Número {3}",
        ["os.realtor_stale"] = "relatos de até {0} atrás",
        ["os.realtor_district_open"] = "{0} livres",
        ["os.realtor_district_none"] = "Nenhum livre",
        ["os.realtor_loading"] = "Verificando os distritos residenciais...",
        ["os.realtor_offline"] = "Os dados de moradia estão indisponíveis agora. O PaissaDB pode estar ocupado; tente de novo em instantes.",
        ["os.realtor_retry"] = "Tentar de novo",
        ["os.realtor_unknown_world"] = "Escolha um mundo para ver os terrenos livres.",
        ["os.realtor_ward_plot"] = "Distrito {0} · Terreno {1}",
        ["os.realtor_size_s"] = "P",
        ["os.realtor_size_m"] = "M",
        ["os.realtor_size_l"] = "G",
        ["os.realtor_filter_small"] = "Pequeno",
        ["os.realtor_filter_medium"] = "Médio",
        ["os.realtor_filter_large"] = "Grande",
        ["os.realtor_chip_fc"] = "CL",
        ["os.realtor_chip_personal"] = "Pessoal",
        ["os.realtor_lotto_accepting_open"] = "Recebendo inscrições",
        ["os.realtor_lotto_results_open"] = "Fase de resultados",
        ["os.realtor_lotto_unavailable"] = "Entre loterias",
        ["os.realtor_phase_label"] = "Fase atual",
        ["os.realtor_time_label"] = "Tempo restante",
        ["os.realtor_entries"] = "{0} inscrições",
        ["os.realtor_fcfs"] = "Por ordem de chegada",
        ["os.realtor_checked"] = "verificado há {0}",
        ["os.realtor_empty_district"] = "Nada livre por aqui no momento.",
        ["os.realtor_empty_filtered"] = "Nada corresponde a esses filtros.",
        ["os.realtor_unit_m"] = "min",
        ["os.realtor_unit_h"] = "h",
        ["os.realtor_unit_d"] = "d",
        ["os.realtor_menu_tour"] = "Tour do app",
        ["os.realtor_tour_welcome_title"] = "Bem-vindo ao Imobiliária",
        ["os.realtor_tour_welcome_body"] = "Todos os terrenos livres de Eorzea, direto no seu telefone. Chega de correr de distrito em distrito; veja o que está livre antes de sair de casa.",
        ["os.realtor_tour_welcome_f1"] = "Explore cada mundo, distrito e data center",
        ["os.realtor_tour_welcome_f2"] = "Filtre por tamanho do terreno e comprador: CL ou pessoal",
        ["os.realtor_tour_welcome_f3"] = "Contagens regressivas da loteria ao vivo e frescor de cada terreno",
        ["os.realtor_tour_browse_title"] = "Explore como um profissional",
        ["os.realtor_tour_browse_body"] = "Escolha um mundo no canto superior direito. Toque em um distrito para ver cada terreno livre com o bairro, o número e o preço.",
        ["os.realtor_tour_browse_f1"] = "Seu próprio mundo é selecionado automaticamente",
        ["os.realtor_tour_browse_f2"] = "Os cinco distritos mostram os terrenos livres num relance",
        ["os.realtor_tour_browse_f3"] = "Filtros de tamanho e comprador afinam a busca",
        ["os.realtor_tour_lotto_title"] = "Atenção à loteria",
        ["os.realtor_tour_lotto_body"] = "A maioria dos terrenos é vendida por loteria. O Imobiliária mostra em que fase cada terreno está e quanto tempo ainda resta.",
        ["os.realtor_tour_lotto_f1"] = "Contagens de inscrição e resultados por terreno",
        ["os.realtor_tour_lotto_f2"] = "Veja quantas inscrições um terreno já tem",
        ["os.realtor_tour_lotto_f3"] = "Cada terreno mostra quando um scout passou por lá pela última vez",
        ["os.realtor_tour_credit"] = "Todos os dados de moradia são coletados por jogadores com o PaissaHouse e compartilhados via PaissaDB. Eles são incríveis!",
        ["os.realtor_tour_credit_link"] = "Visitar o PaissaDB",
        ["os.realtor_tour_reopen_hint"] = "Você pode reabrir este tour a qualquer momento pelo ponto de interrogação lá em cima.",

        // added after update 2.1.3
        ["os.realtor_menu_settings"] = "Configurações",
        ["os.realtor_settings"] = "Configurações da imobiliária",
        ["os.realtor_settings_data"] = "Dados",
        ["os.realtor_settings_alerts"] = "Alertas",
        ["os.realtor_set_stale"] = "Mostrar entradas desatualizadas",
        ["os.realtor_set_stale_hint"] = "Todas as entradas vêm de outros jogadores, pelo PaissaDB. Ligue isto para ver também casas que ninguém verifica há um tempo. Elas ainda podem estar livres. As contagens passam a mostrar a etiqueta de dados desatualizados, e as telas de distrito listam esses terrenos. Desligue e os dois ficam ocultos.",
        ["os.realtor_set_notify"] = "Avisar quando a fase mudar",
        ["os.realtor_set_notify_hint"] = "Você recebe uma notificação no telefone quando a loteria de casas alterna entre aceitar inscrições e divulgar resultados. Ela aparece nas suas notificações, e no chat quando você entra no jogo. Abrir o app Imobiliária limpa o aviso.",

        // added after update 2.3.4 (estate demolition watch)
        ["os.realtor_estate_title"] = "Terreno em risco: faltam cerca de {0} dias",
        ["os.realtor_estate_detail"] = "{0}, {1} dias fora",
        ["os.realtor_estate_detail_more"] = "{0}, {1} dias fora  ·  +{2} outros",
        ["os.realtor_menu_realty"] = "Imóveis próprios",
        ["os.realtor_realty_title"] = "Imóveis próprios",
        ["os.realtor_realty_days"] = "{0} d fora",
        ["os.realtor_realty_entered"] = "Última entrada em {0}",
        ["os.realtor_realty_never"] = "Entra na tua casa para começar a contagem",
        ["os.realtor_realty_empty"] = "Ainda não apareceu nenhum terreno particular. Entra com um personagem que tenha um e ele aparece aqui.",
        ["os.realtor_realty_note"] = "Esta contagem vem do que esta instalação viu, não do temporizador do jogo. O jogo demole a tua casa após {0} dias se não entrares nela. Cada visita reinicia a contagem.",
        ["os.realtor_home_row"] = "A tua casa ({0})",
        ["os.realtor_home_teleport"] = "Ir",
        ["os.realtor_set_estate"] = "Avisar antes de uma casa ser demolida",
        ["os.realtor_set_estate_hint"] = "A Square Enix demole um terreno particular quando ninguém entra nele por 45 dias. O telefone guarda quando cada um dos teus personagens entrou pela última vez na própria casa. Ele avisa-te no chat e nas tuas notificações bem antes de os 45 dias acabarem. Casas de companhia livre e apartamentos não são acompanhados.",
    };

    private static readonly IReadOnlyDictionary<string, string> Ru = new Dictionary<string, string>
    {
        // added after update 2.0.1 (realtor)
        ["os.realtor_pick_world"] = "Выберите мир",
        ["os.realtor_search_world"] = "Поиск миров...",
        ["os.realtor_hero_sub"] = "свободных участков на {0}",
        ["os.realtor_stale_row"] = "(данные устарели)",
        ["os.realtor_menu_contribute"] = "Помочь?",
        ["os.realtor_contribute_title"] = "Откуда эти данные",
        ["os.realtor_contribute_body"] = "Каждый участок в этом списке нашли игроки с плагином PaissaHouse. Плагин сообщает о свободном участке, когда игрок проходит мимо. Поставь его и держи включённым. Тогда твои прогулки будут держать список свежим даже на мирах, которые больше никто не проверяет.",
        ["os.realtor_contribute_open"] = "Открыть установщик плагинов",
        ["os.realtor_contribute_close"] = "Закрыть",
        ["os.realtor_stale_pill"] = "{0} устарело",
        ["os.realtor_bid_title"] = "У тебя есть заявка на участок",
        ["os.realtor_bid_detail"] = "Участок {0}, район {1}, {2}  ·  Номер {3}",
        ["os.realtor_stale"] = "данные не старше {0}",
        ["os.realtor_district_open"] = "{0} свободно",
        ["os.realtor_district_none"] = "Нет свободных",
        ["os.realtor_loading"] = "Проверяем жилые кварталы...",
        ["os.realtor_offline"] = "Данные о жилье сейчас недоступны. Возможно, PaissaDB перегружен; попробуйте чуть позже.",
        ["os.realtor_retry"] = "Попробовать снова",
        ["os.realtor_unknown_world"] = "Выберите мир, чтобы увидеть свободные участки.",
        ["os.realtor_ward_plot"] = "Квартал {0} · Участок {1}",
        ["os.realtor_size_s"] = "S",
        ["os.realtor_size_m"] = "M",
        ["os.realtor_size_l"] = "L",
        ["os.realtor_filter_small"] = "Малый",
        ["os.realtor_filter_medium"] = "Средний",
        ["os.realtor_filter_large"] = "Большой",
        ["os.realtor_chip_fc"] = "ФК",
        ["os.realtor_chip_personal"] = "Личный",
        ["os.realtor_lotto_accepting_open"] = "Приём заявок",
        ["os.realtor_lotto_results_open"] = "Итоги лотереи",
        ["os.realtor_lotto_unavailable"] = "Между лотереями",
        ["os.realtor_phase_label"] = "Текущая фаза",
        ["os.realtor_time_label"] = "Осталось времени",
        ["os.realtor_entries"] = "заявок: {0}",
        ["os.realtor_fcfs"] = "Кто первый, того и участок",
        ["os.realtor_checked"] = "проверено {0} назад",
        ["os.realtor_empty_district"] = "Сейчас здесь нет свободных участков.",
        ["os.realtor_empty_filtered"] = "Под эти фильтры ничего не подходит.",
        ["os.realtor_unit_m"] = "м",
        ["os.realtor_unit_h"] = "ч",
        ["os.realtor_unit_d"] = "д",
        ["os.realtor_menu_tour"] = "Тур по приложению",
        ["os.realtor_tour_welcome_title"] = "Добро пожаловать в Риелтор",
        ["os.realtor_tour_welcome_body"] = "Все свободные участки Эорзеи прямо в вашем телефоне. Хватит бегать по кварталам: посмотрите, что свободно, ещё до выхода из дома.",
        ["os.realtor_tour_welcome_f1"] = "Просматривайте любой мир, квартал и дата-центр",
        ["os.realtor_tour_welcome_f2"] = "Фильтруйте по размеру участка и покупателю: ФК или личный",
        ["os.realtor_tour_welcome_f3"] = "Живые таймеры лотереи и свежесть данных по каждому участку",
        ["os.realtor_tour_browse_title"] = "Разведка как у профи",
        ["os.realtor_tour_browse_body"] = "Выберите мир в правом верхнем углу. Нажмите на квартал, чтобы увидеть каждый свободный участок с номером и ценой.",
        ["os.realtor_tour_browse_f1"] = "Ваш собственный мир выбирается автоматически",
        ["os.realtor_tour_browse_f2"] = "Пять кварталов показывают свободные участки с первого взгляда",
        ["os.realtor_tour_browse_f3"] = "Фильтры размера и покупателя сужают поиск",
        ["os.realtor_tour_lotto_title"] = "Следите за лотереей",
        ["os.realtor_tour_lotto_body"] = "Большинство участков продаётся через лотерею. Риелтор показывает, в какой фазе участок и сколько времени осталось.",
        ["os.realtor_tour_lotto_f1"] = "Таймеры приёма заявок и итогов по каждому участку",
        ["os.realtor_tour_lotto_f2"] = "Смотрите, сколько заявок уже подано на участок",
        ["os.realtor_tour_lotto_f3"] = "У каждого участка видно, когда разведчик проверял его в последний раз",
        ["os.realtor_tour_credit"] = "Все данные о жилье собирают игроки с плагином PaissaHouse и делятся ими через PaissaDB. Они великолепны!",
        ["os.realtor_tour_credit_link"] = "Открыть PaissaDB",
        ["os.realtor_tour_reopen_hint"] = "Этот тур можно открыть заново в любой момент через знак вопроса сверху.",

        // added after update 2.1.3
        ["os.realtor_menu_settings"] = "Настройки",
        ["os.realtor_settings"] = "Настройки Риелтора",
        ["os.realtor_settings_data"] = "Данные",
        ["os.realtor_settings_alerts"] = "Оповещения",
        ["os.realtor_set_stale"] = "Показывать устаревшие записи",
        ["os.realtor_set_stale_hint"] = "Все записи приходят от других игроков, через PaissaDB. Включите этот пункт, чтобы видеть и дома, которые давно никто не проверял. Они всё ещё могут быть свободны. Тогда у счётчиков появится плашка с устаревшими данными, а экраны кварталов покажут такие участки. Если выключить, скроется и то и другое.",
        ["os.realtor_set_notify"] = "Сообщать о смене фазы",
        ["os.realtor_set_notify_hint"] = "Вы получите уведомление на телефон, когда жилищная лотерея переключится между приёмом заявок и объявлением результатов. Оно появится в списке уведомлений, а при входе в игру ещё и в чате. Оно исчезнет, когда вы откроете приложение Риелтор.",

        // added after update 2.3.4 (estate demolition watch)
        ["os.realtor_estate_title"] = "Дом под угрозой: осталось примерно {0} дн.",
        ["os.realtor_estate_detail"] = "{0}, нет дома {1} дн.",
        ["os.realtor_estate_detail_more"] = "{0}, нет дома {1} дн.  ·  ещё {2}",
        ["os.realtor_menu_realty"] = "Своя недвижимость",
        ["os.realtor_realty_title"] = "Своя недвижимость",
        ["os.realtor_realty_days"] = "{0} дн. без визитов",
        ["os.realtor_realty_entered"] = "Последний вход: {0}",
        ["os.realtor_realty_never"] = "Зайди в свой дом, чтобы начать отсчёт",
        ["os.realtor_realty_empty"] = "Личных домов пока не нашлось. Зайди персонажем, у которого он есть, и дом появится здесь.",
        ["os.realtor_realty_note"] = "Этот отсчёт ведётся по тому, что видел этот компьютер, а не по игровому таймеру. Игра сносит твой дом через {0} дней, если ты в него не заходишь. Каждый визит обнуляет счётчик.",
        ["os.realtor_home_row"] = "Твой дом ({0})",
        ["os.realtor_home_teleport"] = "Домой",
        ["os.realtor_set_estate"] = "Предупреждать до сноса дома",
        ["os.realtor_set_estate_hint"] = "Square Enix сносит личный дом, если в него никто не заходил 45 дней. Телефон запоминает, когда каждый твой персонаж последний раз заходил в свой дом. Он предупредит тебя в чате и в уведомлениях задолго до конца 45 дней. Дома свободных компаний и апартаменты не отслеживаются.",
    };

    public static readonly IReadOnlyDictionary<string, IReadOnlyDictionary<string, string>> Packs =
        new Dictionary<string, IReadOnlyDictionary<string, string>>
        {
            ["en"] = En,
            ["de"] = De,
            ["es"] = Es,
            ["fr"] = Fr,
            ["pt"] = Pt,
            ["ru"] = Ru,
        };
}
